### ISSUE TITLE
X_MAX Y_MAX Z_MAX pins. 

### ISSUE THREAD

**Issue by GilesBathgate** [prusa3d/Prusa-Firmware#1]
In pins.h  the following pins are defined:

``` c++
  #define X_MAX_PIN 24
  #define Y_MAX_PIN 23
  #define Z_MAX_PIN 30
```

This contradicts the pinout: http://reprap.org/mediawiki/images/e/ef/MiniRambo1.3a-schematic-pg2.svg

It should be:

``` c++
  #define X_MAX_PIN 30
  #define Y_MAX_PIN 24
  #define Z_MAX_PIN 23
```

**Comment by GilesBathgate** [comment]
Perhaps the pinouts vary depending on the variant used. In which case these should be defined appropriately in each of the variant header files.

**Comment by ayourk** [comment]
It looks like this has been fixed as of commit https://github.com/prusa3d/Prusa-Firmware/commit/3c735786e368c14dba5fe9115b3bafb730176f58 .

**Comment by GilesBathgate** [comment]
Thanks
