### ISSUE TITLE
Parts fan keeps blowing after stop print

### ISSUE THREAD

**Issue by Brekel** [prusa3d/Prusa-Firmware#10]
It seems like (at least on the i3 MK2) the firmware doesn't turn off the parts fan when stop print is selected from the menu.

Of course it can be manually shut off but since printing has stopped an automatic M107 could be convenient.

**Comment by bubnikv** [comment]
Thanks, we are aware of this issue.
Vojtech

**Comment by Brekel** [comment]
Great work btw, by far the best firmware I've seen on 8-bit and lots of cool innovation!

**Comment by bubnikv** [comment]
Thanks, we appreciate it.
Vojtech

**Comment by ayourk** [comment]
Looks like this was fixed as of commit https://github.com/prusa3d/Prusa-Firmware/commit/ea197360ac851975da76fd27f7e3d2be2debb72e

**Comment by mrjohnc** [comment]
Bump, suggest this is closed :) @bubnikv
