### ISSUE TITLE
Filament Sensor Detection Option Discussion/Ideas

### ISSUE THREAD

**Issue by dot-bob** [prusa3d/Prusa-Firmware#1009]
So the filament sensor can detect filament presence and or movement/jam.  It also has the issue of occasionally false triggering an error with certain types of filament.  Is the typical error when false triggering a filament presence error or a movement error?

If the false positive is due to movement/jam detection failing could we get better sensor reliability with troublesome filaments if we can disable movement detection and leave presence detection enabled?

**Comment by clearbucketLabs** [comment]
it's a hardware/sensor issue.  there's no movement detection, just presence in firmware.   you could use the sensor on a bearing/wheel that the filament moves and that would work (indirectly).

**Comment by RetireeJay46** [comment]
Are you sure it's just a presence detector?  The active device on the filament sensor board is a laser sensor package used in optical mice, which definitely do sense motion.

**Comment by clearbucketLabs** [comment]
Yes but the firmware doesn't track the movement.   my guess is it's just a periodic check if it's present... if it did motion it needs to be synced with extruder movements and retracts too, which far as i know is probably too much for the 8 bit board at this point.  Plus it's not entirely reliable and accuracy is dependent on extrusion speed.  You could do it on some other platform (32 bit marlin/duet wifi etc..). they do exist already, usually mechanical/encoder based.

**Comment by mgx0** [comment]
Since the sensor is not reliable across all filaments, I would propose to add third option to the Filament Sensor: On, Off and **Load (example)**. This would disable the filament sensor when printing and enable it when not printing. Filament Autoload is useful feature, but it's annoying to either have autoload enabled and having fake alerts during printing, or No alerts furing printing and Autoload off. 

Simply, just let us to use the sensor Autoload only. In current state it's causing more problems than it serves it's purpose.

**Comment by clearbucketLabs** [comment]
i haven't had a whole lot of problems with it so far, even on shiny black petg.

**Comment by mgx0** [comment]
Well congrats on that. I have false alarms and pauses during every print using any PETG filaments from Devil Design, they are really shiny. And I'm not alone. 

Anyway, my suggestion is to add a new option, not to remove exising ones. You'd be able to continue using it and I'd be able to get my prints done without changing filament every few minutes when I forget to disable the sensor. The sensor should be working for autoloading all filaments, also transparent.

**Comment by jltx1** [comment]
Here is my solution: https://www.thingiverse.com/thing:3091625

**Comment by clearbucketLabs** [comment]
@jltx1 saw that, thanks :)  apparently this is how it's supposed to be used anyway...
