### ISSUE TITLE
Head rises and prints in the air

### ISSUE THREAD

**Issue by steveadapta** [prusa3d/Prusa-Firmware#1016]

**Comment by steveadapta** [comment]
After running a new file using Prusa control, the printer head works fins or the 3 first layers. The all of  sudden the head moves up about 20mm and starts printing in the air.

**Comment by dalgibbard** [comment]
Do you have an example gcode file?

**Comment by inquisitiveKangaroo** [comment]
Hi,
Prusa control might be slightly outdated. Slic3r PE should provide a better result. Please let me know incase it will not.
