### ISSUE TITLE
LCD Displaying "Sleep..." During USB Printing

### ISSUE THREAD

**Issue by TheZeroBeast** [prusa3d/Prusa-Firmware#1017]
Hello,
I'm running MK3 on 3.3.1 and Slic3r 1.41.0Beta.

During USB printing(SD Card printing may do the same) the LCD bottom info displays "Sleep..." as per screenshot.

Note: as per FW 3.3.0 release notes M86 S0 & M86 S1800 have been added to my Octoinstance, not sure if this would be contributing at all.

![img_3256](https://user-images.githubusercontent.com/20939095/43772477-9f1a38e0-9a85-11e8-9b38-2eb987324660.jpg)

Thanks,
Rob

**Comment by ptfly** [comment]
Same thing is happening to me on the latest FW on MK3S. I'm using Gcode to trigger Einsy pin and take a photo on a GoPro through esp8266 chip via `M42 S255 P73` and then using `G4 P200`. Once the delay is used, the message isn't cleared from the screen.

**Comment by ptfly** [comment]
v3.8.1 - same thing, not fixed :( May be this issue is too deep in the timeline!

**Comment by 3d-gussner** [comment]
I am reviewing issues and think this one isn't fixed.
What do you expect after G4 is timed out?
My guess that the "Sleep ..." message disappears and the "normal" Info Screen is shown again.
