### ISSUE TITLE
While trying to compile, different errors appear

### ISSUE THREAD

**Issue by ChristianKoenigs** [prusa3d/Prusa-Firmware#102]
Hi there. I tried to compile the latest version (3.0.11) and get this errors ... Perhaps it is only something missing, but i have NO idea how to fix this ... I've marked some of them with bold... Any ideas ???

In file included from /Marlin.h:23, from BlinkM.cpp:5:
/pins.h:44:1: warning: "X_MS1_PIN" redefined
/pins.h:7:1: warning: this is the location of the previous definition
/pins.h:45:1: warning: "X_MS2_PIN" redefined
/pins.h:8:1: warning: this is the location of the previous definition
/pins.h:51:1: warning: "Y_MS1_PIN" redefined
/pins.h:9:1: warning: this is the location of the previous definition
/pins.h:52:1: warning: "Y_MS2_PIN" redefined
/pins.h:10:1: warning: this is the location of the previous definition
/pins.h:58:1: warning: "Z_MS1_PIN" redefined
/pins.h:11:1: warning: this is the location of the previous definition
/pins.h:59:1: warning: "Z_MS2_PIN" redefined
/pins.h:12:1: warning: this is the location of the previous definition
/pins.h:112:1: warning: "E0_MS1_PIN" redefined
/pins.h:13:1: warning: this is the location of the previous definition
/pins.h:113:1: warning: "E0_MS2_PIN" redefined
/pins.h:14:1: warning: this is the location of the previous definition
In file included from /Configuration.h:728,
                 from /Marlin.h:22,
                 from BlinkM.cpp:5:
/thermistortables.h:10: warning: only initialized variables can be placed into program memory area
/thermistortables.h:173: warning: only initialized variables can be placed into program memory area
In file included from /Marlin.h:44,
                 from BlinkM.cpp:5:
/MarlinSerial.h: In member function 'void MarlinSerial::checkRx()':
/MarlinSerial.h:120: warning: unused variable 'c'

In file included from /Marlin.h:23,
                 from cardreader.cpp:1:
/pins.h:44:1: warning: "X_MS1_PIN" redefined
/pins.h:7:1: warning: this is the location of the previous definition
/pins.h:45:1: warning: "X_MS2_PIN" redefined
/pins.h:8:1: warning: this is the location of the previous definition
/pins.h:51:1: warning: "Y_MS1_PIN" redefined
/pins.h:9:1: warning: this is the location of the previous definition
/pins.h:52:1: warning: "Y_MS2_PIN" redefined
/pins.h:10:1: warning: this is the location of the previous definition
/pins.h:58:1: warning: "Z_MS1_PIN" redefined
/pins.h:11:1: warning: this is the location of the previous definition
/pins.h:59:1: warning: "Z_MS2_PIN" redefined
/pins.h:12:1: warning: this is the location of the previous definition
/pins.h:112:1: warning: "E0_MS1_PIN" redefined
/pins.h:13:1: warning: this is the location of the previous definition
/pins.h:113:1: warning: "E0_MS2_PIN" redefined
/pins.h:14:1: warning: this is the location of the previous definition
In file included from /Configuration.h:728,
                 from /Marlin.h:22,
                 from cardreader.cpp:1:
/thermistortables.h:10: warning: only initialized variables can be placed into program memory area
/thermistortables.h:173: warning: only initialized variables can be placed into program memory area
In file included from /Marlin.h:44,
                 from cardreader.cpp:1:
/MarlinSerial.h: In member function 'void MarlinSerial::checkRx()':
/MarlinSerial.h:120: warning: unused variable 'c'
cardreader.cpp: In member function 'void CardReader::lsDive(const char*, SdFile, const char*)':
**cardreader.cpp:84: error: 'pgm_read_ptr' was not declared in this scope**
cardreader.cpp: In member function 'void CardReader::initsd()':
**cardreader.cpp:168: error: 'pgm_read_ptr' was not declared in this scope
cardreader.cpp:173: error: 'pgm_read_ptr' was not declared in this scope
cardreader.cpp:178: error: 'pgm_read_ptr' was not declared in this scope
cardreader.cpp:184: error: 'pgm_read_ptr' was not declared in this scope**
cardreader.cpp: In member function 'void CardReader::openFile(char*, bool, bool)':
cardreader.cpp:263: warning: only initialized variables can be placed into program memory area
cardreader.cpp:270: warning: only initialized variables can be placed into program memory area
cardreader.cpp:272: warning: only initialized variables can be placed into program memory area
cardreader.cpp:278: warning: only initialized variables can be placed into program memory area
cardreader.cpp:286: warning: only initialized variables can be placed into program memory area
cardreader.cpp:295: warning: only initialized variables can be placed into program memory area
**cardreader.cpp:322: error: 'pgm_read_ptr' was not declared in this scope**
cardreader.cpp:324: warning: only initialized variables can be placed into program memory area
**cardreader.cpp:354: error: 'pgm_read_ptr' was not declared in this scope
cardreader.cpp:367: error: 'pgm_read_ptr' was not declared in this scope**
cardreader.cpp:369: warning: only initialized variables can be placed into program memory area
cardreader.cpp:376: error: 'pgm_read_ptr' was not declared in this scope
cardreader.cpp:378: warning: only initialized variables can be placed into program memory area
cardreader.cpp:383: error: 'pgm_read_ptr' was not declared in this scope
cardreader.cpp: In member function 'void CardReader::removeFile(char*)':
cardreader.cpp:422: warning: only initialized variables can be placed into program memory area
cardreader.cpp:449: warning: only initialized variables can be placed into program memory area
cardreader.cpp:455: warning: only initialized variables can be placed into program memory area
cardreader.cpp:457: warning: only initialized variables can be placed into program memory area
cardreader.cpp: In member function 'void CardReader::getStatus()':
cardreader.cpp:466: warning: only initialized variables can be placed into program memory area
cardreader.cpp:467: error: 'pgm_read_ptr' was not declared in this scope
cardreader.cpp:469: warning: only initialized variables can be placed into program memory area
cardreader.cpp:475: warning: only initialized variables can be placed into program memory area
cardreader.cpp: In member function 'void CardReader::write_command(char*)':
cardreader.cpp:500: error: 'pgm_read_ptr' was not declared in this scope
cardreader.cpp: In member function 'void CardReader::write_command_no_newline(char*)':
cardreader.cpp:512: error: 'pgm_read_ptr' was not declared in this scope
cardreader.cpp: In member function 'void CardReader::checkautostart(bool)':
cardreader.cpp:536: warning: only initialized variables can be placed into program memory area
cardreader.cpp:556: warning: only initialized variables can be placed into program memory area
cardreader.cpp:559: warning: only initialized variables can be placed into program memory area
cardreader.cpp: In member function 'void CardReader::chdir(const char*)':
cardreader.cpp:618: error: 'pgm_read_ptr' was not declared in this scope
cardreader.cpp: In member function 'void CardReader::updir()':
cardreader.cpp:639: warning: comparison between signed and unsigned integer expressions
cardreader.cpp:638: warning: unused variable 'd'
cardreader.cpp: In member function 'void CardReader::printingHasFinished()':
cardreader.cpp:664: warning: only initialized variables can be placed into program memory area
/ultralcd.h: At global scope:
/ultralcd.h:35: warning: 'void lcd_selftest()' declared 'static' but never defined
/ultralcd.h:36: warning: 'bool lcd_selfcheck_endstops()' declared 'static' but never defined
/ultralcd.h:37: warning: 'bool lcd_selfcheck_axis(int, int)' declared 'static' but never defined
/ultralcd.h:38: warning: 'bool lcd_selfcheck_check_heater(bool)' declared 'static' but never defined
/ultralcd.h:39: warning: 'int lcd_selftest_screen(int, int, int, bool, int)' declared 'static' but never defined
/ultralcd.h:40: warning: 'void lcd_selftest_screen_step(int, int, int, const char*, const char*)' declared 'static' but never defined
/ultralcd.h:41: warning: 'bool lcd_selftest_fan_dialog(int)' declared 'static' but never defined
/ultralcd.h:42: warning: 'void lcd_selftest_error(int, const char*, const char*)' declared 'static' but never defined
/ultralcd.h:44: warning: 'bool lcd_selfcheck_pulleys(int)' declared 'static' but never defined
/ultralcd.h:68: warning: 'blink' defined but not used
/ultralcd.h:211: warning: 'void lcd_colorprint_change()' declared 'static' but never defined
/ultralcd.h:212: warning: 'int get_ext_nr()' declared 'static' but never defined
/ultralcd.h:213: warning: 'void extr_adj(int)' declared 'static' but never defined
/ultralcd.h:214: warning: 'void extr_adj_0()' declared 'static' but never defined
/ultralcd.h:215: warning: 'void extr_adj_1()' declared 'static' but never defined
/ultralcd.h:216: warning: 'void extr_adj_2()' declared 'static' but never defined
/ultralcd.h:217: warning: 'void extr_adj_3()' declared 'static' but never defined
/ultralcd.h:218: warning: 'void fil_load_menu()' declared 'static' but never defined
/ultralcd.h:219: warning: 'void fil_unload_menu()' declared 'static' but never defined
/ultralcd.h:220: warning: 'void extr_unload_0()' declared 'static' but never defined
/ultralcd.h:221: warning: 'void extr_unload_1()' declared 'static' but never defined
/ultralcd.h:222: warning: 'void extr_unload_2()' declared 'static' but never defined
/ultralcd.h:223: warning: 'void extr_unload_3()' declared 'static' but never defined
/ultralcd.h:224: warning: 'void lcd_disable_farm_mode()' declared 'static' but never defined
/ultralcd.h:226: warning: 'void extr_unload()' declared 'static' but never defined
/ultralcd.h:229: warning: 'void lcd_ping_allert()' declared 'static' but never defined
/temperature.h:179: warning: 'temp_runaway_status' defined but not used
/temperature.h:180: warning: 'temp_runaway_target' defined but not used
/temperature.h:181: warning: 'temp_runaway_timer' defined but not used
/temperature.h:182: warning: 'temp_runaway_error_counter' defined but not used

**Comment by PavelSindler** [comment]
Hello, I have never observed this problem, but it can be caused by missing avr/pgmspace.h include. Please try to compile this version: https://github.com/prusa3d/Prusa-Firmware/commit/baeeb733e9b2eef482c35a15221b70e184e8d680
