### ISSUE TITLE
Add "Clean Nozzle" option during the print dialog

### ISSUE THREAD

**Issue by ghost** [prusa3d/Prusa-Firmware#103]
There should be a "Clean Nozzle" option which moves it to home up and out of the way of your print. I find that PETG is the biggest offender for a dirty nozzle and almost always by the time the first 4 layers are filled you will have some build up on the nozzle (which will drop off in the middle of a fill).

I have tried adjusting flow rate and first layer height but PETG is just sticky stuff. 

Conceptual Behavior: 
1. During a print the user selects "Clean Nozzle" from the LCD interface
2. Current position X,Y,Z are stored
3. Heat bed remains at print temperature to prevent warping and nozzle stays at print temperature.
4. Nozzle is raised up (as long as there is room on the Z axis) and goes to the home 0,0 position
5. Use a Q-Tip to clean your nozzle buildup.
6. Select resume to go back printing.

This would be a huge improvement when printing to be able to prevent a glob from falling off the nozzle or dragging across your print.

**Comment by fiveangle** [comment]
There is already a "change filament" option that will allow you to do this now.  Of course with it comes the requirement to purge the filament in the nozzle, which isn't needed [shrug]

**Comment by m-Th** [comment]
...besides that „Change Filament” is not discoverable for the user.
