### ISSUE TITLE
Invalid z position

### ISSUE THREAD

**Issue by DataCrypt** [prusa3d/Prusa-Firmware#1038]
If I hold down the knob/button on the MK3, it prompts to easily change the Z position - which is great.  If I scroll the knob to raise the z, it will go too far!  The hotend goes all the way up and the z axis starts to click since the rod screws start skipping (possibly stripping) the on the z axis nuts.  If possible, there should be some stop limit on the Z axis so it doesn't do this.

**Comment by XPila** [comment]
@DataCrypt it is not problem when Z axis is blocked, the sound you can hear is not screw-skiping/striping, just motor step-skipping. This is by design. The torque is adjusted to safe value.

**Comment by DataCrypt** [comment]
@XPila pila.  Thank you!  I was not aware of that.  Please disregard.
