### ISSUE TITLE
Turning off crash detection during print not working

### ISSUE THREAD

**Issue by LubosD** [prusa3d/Prusa-Firmware#1044]
Right now I'm printing a large flat surface, but a few bumps appeared on the print's surface unfortunately.

They trigger crash detection, but I want the print to try and follow through without me constantly approving the print resuming after every N crashes.

So I go into Tune -> Crash detection and set it to off, but it is still detected and still leads to the same confirmation screen :-(

FW 3.3.1

**Comment by akillmer** [comment]
I have the same issue.
