### ISSUE TITLE
Web Link broken 

### ISSUE THREAD

**Issue by 3d-gussner** [prusa3d/Prusa-Firmware#107]
Hi,

just saw that the link to the FIRMWARE 3.0.12-RC1 (MAY 22, 2017) **'Full detailed release log on Github'** link on the http://www.prusa3d.com/drivers/ website is broken.
It links to 'https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.0.12-RC1' and not to 'https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.0.12_RC1' with an underscore between 'v3.0.12' and 'RC1'

**Comment by PavelSindler** [comment]
Thanks for reporting. It is working now. Sorry for inconvenience.
