### ISSUE TITLE
3.4.0 RC1 - manual bed adjustment not storeable

### ISSUE THREAD

**Issue by RacingHell** [prusa3d/Prusa-Firmware#1083]
If I try to finetune the bed leveling via front/back/left/right, the values are resetted instantly to 0, one of them jumps to 50.
Please raise the values from +/- 50 to +/- 100 as well, since I couldn’t get an acceptable adjustment in the past. I have issues with big prints first layer.

**Comment by PavelSindler** [comment]
This has been fixed in PR https://github.com/prusa3d/Prusa-Firmware/pull/1045.
