### ISSUE TITLE
MK2 With 3.1.0 (up to and including RC2) keeps disconnecting from Repetier Host

### ISSUE THREAD

**Issue by witkop** [prusa3d/Prusa-Firmware#1087]
Since upgrading to 3.1.0 my MK2 keeps disconnecting from Repetier Host!
I note that there is an issue reported about Repetier in 3.1.0, but this does not appear to have been addressed.
If I go back to the previous firmware version, the problem does not arise.

Any suggestions?

**Comment by morimorida** [comment]
Same here. Have not updated my mk2 firmware since last November due to this
issue.

**Comment by 3d-gussner** [comment]
There is a merged pull request that might fix it from december 2017, BUT Prusa never updated the hex file.
So you can compile the MK2 branch yourself or try my firmware https://github.com/3d-gussner/Prusa-Firmware/releases/tag/v3.1.0-001-HFM

If you use my firmware please read the release notes.
