### ISSUE TITLE
M117 makes the extruder run backwards instead of displaying a message (no joke)

### ISSUE THREAD

**Issue by yschroeder** [prusa3d/Prusa-Firmware#110]
Ok, this one is kind of scary: `M117` results in inconsistent behavior. Sometimes the message does not get displayed and I even managed to make the extruder run backwards!

I am using release 3.0.11.

I am sending three commands right after each other:
```
M104 S0
M140 S0
M117 Heat off
```
The above code works correctly every time.

Also this works:
```
M104 S215
M140 S55
M117 Preheating for PLA...
```

However, this does NOT work:
```
M104 S230
M140 S85
M117 Preheating for PETG...
```
It sets the temperatures correctly, but the M117 command is (mostly) ignored.

This does work again:
```
M104 S230
M140 S85
M117 Heat off
```
EDIT: ~I believe the length of the message is not checked correctly before being sent to the LCD.~

Here is how to reproduce making the extruder run backwards:
* Unload filament via `M702`
* Load filament via `M701`
* Run the above gcode that did not print the message correctly

EDIT:
The printer just does not want to display the string PETG!
```
M117 P      # works
M117 PE     # works
M117 PET    # works
M117 PETG   # does not work (and extruder might run backwards)
```

EDIT2:
Every message that contains a capital G is ignored. M works fine though.
```
M117 G   # does not work
M117 oGo # does not work
M117 oo  # works
M117 M   # works
M117 oMo # works
```

**Comment by PavelSindler** [comment]
Thank you for reporting this issue. It has been fixed in https://github.com/prusa3d/Prusa-Firmware/commit/36091dcde4f1c83440186f4c112c1eeef3c5ea78 .
