### ISSUE TITLE
3.4.0 RC2 bug

### ISSUE THREAD

**Issue by jltx1** [prusa3d/Prusa-Firmware#1100]
There is s bug where you can see the firmware misinterpreted the gcode and collapsed the bottom perimeter and moved the side perimeter across the middle. I confirmed that the gcode out of slic3r is correct by loading into a third party gcode viewer which matches slic3r.  So this appears to be a firmware bug. 

![82526e3a-8725-42ec-b439-f6b8c9c145a2](https://user-images.githubusercontent.com/28034983/45002373-a3574f80-af9b-11e8-9701-b0daa8127683.jpeg)

**Comment by jltx1** [comment]
I reverted to v3.3.1 and the exact same gcode file is printing correctly now.

**Comment by PavelSindler** [comment]
Was it prited from SD card? Did that happen more than once? Can you please provide gcode file?

**Comment by jltx1** [comment]
Yes, from SD card.  This was 2 perimeters and multiple passes, so it was consistently making the error.  I will try to dig up the gcode this evening.  

-- Jon

**Comment by PavelSindler** [comment]
So did you find it? It would be very helpful.

**Comment by jltx1** [comment]
Yes, but won't let me attach.  I renamed it .png to fool the file loader.  Rename to .gcode.  Good luck.

> https://user-images.githubusercontent.com/28034983/45094697-9b092c80-b0e1-11e8-966b-69a01f0d583a.png

![perim_bug](https://user-images.githubusercontent.com/28034983/45094697-9b092c80-b0e1-11e8-966b-69a01f0d583a.png)

**Comment by PavelSindler** [comment]
Thank you! Testing...

**Comment by jltx1** [comment]
Not sure if this is useful, but this is the partial hash it showed when I did the git pull:  Updating 8cea3a7..1774378

I used Arduino 1.85 to compile.

**Comment by PavelSindler** [comment]
Ok, we can't reproduce the issue with gcode you provided. It seems that it will be ralted to fw version which you are using or eeprom state. Can you try 3.4.0-RC2 firmware version?

**Comment by jltx1** [comment]
I was using RC2, but maybe compile got corrupted.  I will try again.  Thanks for checking.  

-- Jon

**Comment by jltx1** [comment]
I re-pulled 3.4.0 RC2 and recompiled.  The binary is not the same size in bytes, so something is slightly different.  I flashed and am unable to reproduce this bug.  So either someone fixed it on HEAD or I somehow got a corrupt build.
