### ISSUE TITLE
Question: Does the power panic still works on MK3 with MMU2?

### ISSUE THREAD

**Issue by 3d-gussner** [prusa3d/Prusa-Firmware#1101]
As the MMU2 Controller doesn't have its own power source and uses the prodived Einsy 5V to run, does the PSU still have enough power during a power outage to
- store the position into EEPROM to be able to recover?
- lift the hotend to prevent burning of the printed part?

I hope that during the print with loaded filament the idle mmu2 controller doesn't consume to much power so the firmware can at least store the position into the EEPROM.

But what happens when the printer/mmu2 is in change filament mode?
As the mmu2 controller isn't power panic smart as the Einsy board it will try to finish the sequence and so draw power form the Einsy ==> PSU caps.

If Prusa supports power panic on a MK3 with MMU2, the firmware should also store the information if the load/unload/eject sequence is finished to be able to recover.

As far I can see, the mmu2 firmware checks after rest/power on with the F.I.N.D.A. the presence of filament.
But what happens if the power goes off during a load/unload/eject operation?
The mmu2 idler will be engaged and after reboot of the mmu2 controller thinking filament is present, so I don't do anything. And the printer will try to recover the print with an engaged mmu2 idler, which may add unwanted drag but even worse prevent the direct extruder to retract filament so prints will fail when the load sequence isn't completely finished.

**Comment by maximlevitsky** [comment]
This is a really good question. I bet that it doesn't....
