### ISSUE TITLE
3.4.0 RC2 time remaining

### ISSUE THREAD

**Issue by JoePrints** [prusa3d/Prusa-Firmware#1103]
Started a print multiple times, with Slic3r stating it would be 14H and some minutes. After starting print, time remaining on LCD says 3H 25M, runs down to zero, then restarted remaining time at 11H.
Same Gcode reports correctly in 3.3.1

**Comment by PavelSindler** [comment]
Thank you for reporting this. Can you please provide gcode file?

**Comment by JoePrints** [comment]
[city.zip](https://github.com/prusa3d/Prusa-Firmware/files/2354133/city.zip)

**Comment by PavelSindler** [comment]
Working on it! Thanks.

**Comment by 3d-gussner** [comment]
Shouldn't https://github.com/prusa3d/Prusa-Firmware/commit/990a5c9119b2515d265ecb10f745371f2fee3cbb have fixed this issue?
See also https://github.com/prusa3d/Prusa-Firmware/issues/986

**Comment by JoePrints** [comment]
For me, 3.3.1 displayed the correct time remaining with Slic3r PE 1.41.0 on everything including a 42 hr print.

**Comment by PavelSindler** [comment]
PR https://github.com/prusa3d/Prusa-Firmware/pull/1113 fixes this issue.
