### ISSUE TITLE
MK2.5  3.3.1-845: Bed level data not applied ~~only applied slightly~~

### ISSUE THREAD

**Issue by EddyMI3d** [prusa3d/Prusa-Firmware#1106]
Hi!
It may be, that this exact issue has been posted about before, but did not find one with this firmware version.

Here we go: I did all the Calibration and settings as recommended by the manual.
When it comes to the **First Layer Calibration**, it occurs, that the Z-axis does not follow the unevenness of the bed. ~~tries to follow the unevenness of the bed (the spindles are rotating slightly), but not that much that it compensates the bed mesh level data.~~
Still, in some areas of the first layer the printed filament is plain flat, in some others it just adheres. 

It worked way much better with the MK2S with Firmware 3.1.0

**Comment by slate0** [comment]
Might be related to this?
https://github.com/prusa3d/Prusa-Firmware/issues/1159

**Comment by EddyMI3d** [comment]
Thanks for that hint!
