### ISSUE TITLE
Slow z-axis movement

### ISSUE THREAD

**Issue by cropduster** [prusa3d/Prusa-Firmware#1118]
The z-axis moves extremely slow, regardless if done under settings at the orinter LCD or via Octoprint. All other axis move normally. 

However, this issue disappears after a print. When a print is competed, the z-axis moves normally again.

**Comment by Prusa-Support** [comment]
Hello! I am absolutely sorry this hasn't been replied to at the time of reporting. I believe this should be completely solved with the newer FW versions released in the meantime, do you still have issues with this? In case we can review in more detail. 

Alessandro Pantaleo
Prusa Research
