### ISSUE TITLE
MK2.5 remaining time doesn't work

### ISSUE THREAD

**Issue by p3ck** [prusa3d/Prusa-Firmware#1120]
See thread:
https://shop.prusa3d.com/forum/hardware-firmware-and-software-help-f44/elapsed-printing-time-not-shown-correctly-on-scree-t24325.html

68:15R is shown during every print and never shows the correct data from M73

**Comment by PavelSindler** [comment]
PR https://github.com/prusa3d/Prusa-Firmware/pull/1112 fixes this issue.
