### ISSUE TITLE
3.3.1 Firmware MK3 - Click Noise in the extruder when purging and during 1st skirt/loop

### ISSUE THREAD

**Issue by christizzz** [prusa3d/Prusa-Firmware#1122]
I just noticed on the Mk3 with latest firmware that during the Purge Line, the extruder clicks when it speeds up and then it does the travel move to start the skirt it also clicks 1 time when it starts the skirt...but the then it prints normally...

**Comment by Prusa-Support** [comment]
This thread could be related to issue https://github.com/prusa3d/Prusa-Firmware/issues/765.
Also, this thread has been silent for years.
For these reasons, this issue will be closed.

Please check the issue mentioned above to learn more about the conclusion of this case.
Comment below or feel free to open a new issue if you feel this issue deserves a separate discussion.

Michele Moramarco
Prusa Research
