### ISSUE TITLE
3.3.1 Screen Flickers when looking at status screen

### ISSUE THREAD

**Issue by christizzz** [prusa3d/Prusa-Firmware#1139]
Here is a video ( @5seconds you see the flicker) ... https://drive.google.com/open?id=1FCD4KI_knWb5RYr5cKG9GhpJK-c9VO19

The interval between each flicker is about 10-11 seconds..it is constant... so it might be firmware...

It looks like a refresh or somekind...

**Comment by maximlevitsky** [comment]
I confirm this

**Comment by christizzz** [comment]
Update..it happens also with 3.4
