### ISSUE TITLE
Change message "Is color clear?"

### ISSUE THREAD

**Issue by TonyLHansen** [prusa3d/Prusa-Firmware#114]
The message 

`const char MSG_FILAMENT_CLEAN_EN[] PROGMEM = "Is color clear?";
`

from language_all.cpp, would read better and make more sense in the context as

`const char MSG_FILAMENT_CLEAN_EN[] PROGMEM = "Is new color clear?";
`

The Spanish version also has the corresponding word "nuevo". You might consider add a similar word to the other languages.

**Comment by Swiftnesses** [comment]
Or even "colour" 😄
