### ISSUE TITLE
3.4.0 RC1/RC2/Final: Statistics Screen - Filament used shows weird numbers

### ISSUE THREAD

**Issue by RacingHell** [prusa3d/Prusa-Firmware#1149]
Hi,
since RC1 my statistics screen messed up. Filament used was something like 2xxx m on 3.3.1. Now it shows 65845.60 m. I haven't by faaar printed 200+ spools until now. :)

Any chanche to get that fixed?

**Comment by maximlevitsky** [comment]
It does work here, but what doesn't work on RC2 is that during the print, the total print time of current print starts to show an negative number in the statistics screen 
EDIT: Its a separate issue, with what seems to be a trivial fix. I opened up  issue #1151 for that.

**Comment by maximlevitsky** [comment]
For your issue, which printer do you have and from which firmware version did you update. I would strongly suspect that something messed up your EEPROM on the printer, since the code which prints the values looks ok to me.

**Comment by RacingHell** [comment]
I have a MK3 and updated every released firmware since january. As I told, updating 3.3.1 to 3.4.0 RC1 messed up my stats.

**Comment by maximlevitsky** [comment]
The eeprom layout must have changed I guess or something messed it up. We need a way to dump the eeprom through some G code.
Maybe the initial bootloader can be used to dump eeprom too, I don't know.
Anyway, don't think I can help on this yet.

**Comment by mkbel** [comment]
It looks like something has written 0x1 at 4083 EEPROM address.

**Comment by mkbel** [comment]
It looks like something has written 100 (0x64) at 4083 EEPROM address. It has been experimentally tested on printer. Writing 100 at 4083 EEPROM address caused total filament used statistic jump from 5.09m to 65541.09m. And would do equivalent for any original value less then 655.36m.

**Comment by mkbel** [comment]
Potential candidates:
extrudemultiply as it is commonly 100 and is written to EEPROM during power panic.

Check following code for underflow:
```
		if (total_filament_used > ((current_position[E_AXIS] - destination[E_AXIS]) * 100)) { //protection against total_filament_used overflow
			total_filament_used = total_filament_used + ((destination[E_AXIS] - current_position[E_AXIS]) * 100);
```

**Comment by RacingHell** [comment]
> 
> 
> It looks like something has written 100 (0x64) at 4083 EEPROM address. It has been experimentally tested on printer. Writing 100 at 4083 EEPROM address caused total filament used statistic jump from 5.09m to 65541.09m. And would do equivalent for any original value less then 655.36m.

Hmm.. in my case the original value was somthing around 2000 meters, now it's showing 65903.69m. As it was 65845.60m at the initial issue report it's incrementing healthy so far.

Not shure how to explain the difference of 368,69m. 65903.69-65535+2047= 2415,69m -> this could match my real statistics.

**Comment by mkbel** [comment]
> Hmm.. in my case the original value was somthing around 2000 meters, now it's showing 65903.69m. As it was 65845.60m at the initial issue report it's incrementing healthy so far.
> 
> Not shure how to explain the difference of 368,69m. 65903.69-65535+2047= 2415,69m -> this could match my real statistics.

So I am out of ideas now. The number reported looked like 2^16 for the first sight, so I suspected something like 16 bit unsigned number underflow. But numbers are stored or operated on with different scaling than 1 meter - 1 centimeter in case of EEPROM storage and 0.01 mm in case of RAM 32 bit unsigned integer. RAM value underflow would cause 42949.67296 meters jump.

Maybe this is completely random value with no pattern, caused by power failure or reset during EEPROM write. Statistics values are not protected against this.

**Comment by DRracer** [comment]
@RacingHell did a similar issue occur on later firmware upgrades? If not, we'd like to close this issue.

**Comment by RacingHell** [comment]
@DRracer I haven‘t tracked the issue for a long time, since I am actually not that active in printing. Maybe it was just a random bug from updating frequently from up the beginning of new releases.
