### ISSUE TITLE
Failing generate lang_en_fr.txt in FW 3.4.0 for MK3

### ISSUE THREAD

**Issue by 3d-gussner** [prusa3d/Prusa-Firmware#1150]
I try to generate the languages using make_lang.sh for FW 3.4.0 MK3 and get an error:
```
Entries in lang_en_fr.txt are different from lang_en.txt!
please check lang_en_fr.dif
make_lang.sh finished with errors!
```
the lang_en_fr.dif contains:
```
54d53
< "Crash detected. Resume print?"
97d95
< "Print time"
148d145
< "Lin. correction"
226d222
< "Prusa i3 MK2.5 ready."
257d252
< "Show pinda state"
286,287d280
< "Total filament"
< "Total print time"
311d303
< "XYZ calibration all right. X/Y axes are slightly skewed. Good job!"
313d304
< "XYZ calibration compromised. Front calibration points not reachable."
315,322c306
< "XYZ calibration compromised. Left front calibration point not reachable."
< "Load all"
< "Load filament 1"
< "Load filament 2"
< "Load filament 3"
< "Load filament 4"
< "Load filament 5"
< " [off]"
---
> "Unload all"

```

**How is Prusa able to generate and compile all the hex files, as we can't do that with the source.zip from the release?**
I know that i can modify the lang_en_fr.txt file to match the lang_en.txt BUT i thought that the provided source.zip is exactly the same Prusa uses to make the hex files.
 
How do we generate MK25 the two language hex files for the miniRAMbo? 

BTW compiling the MK3 hits the limits again. In the past i had strange issues on my MK2 when it was above 96-97%!

Arduino IDE 1.6.9 with FW 3.4.0 for MK3:
```
Sketch uses 253,632 bytes (98%) of program storage space. Maximum is 258,048 bytes.
Global variables use 6,266 bytes of dynamic memory.
```
Arduino IDE 1.8.5 with same FW 3.4.0 for MK3:
```
Sketch uses 243650 bytes (94%) of program storage space. Maximum is 258048 bytes.
Global variables use 6270 bytes of dynamic memory.
```

**Comment by maximlevitsky** [comment]
I confirm the same issue!

**Comment by Lino77** [comment]
My created MK3 hex file is only 817 kb that of Prusa 830. the MK2.5 617kb that of prusa 637 kb. with both missing ca.20 kb, where is the error

**Comment by 3d-gussner** [comment]
@Lino77 Did you compile with IDE 1.6.9 or 1.8.5?

**Comment by Lino77** [comment]
1.8.7 
the files from the Arduino, run.
but as soon as I want to wrap up the lang .... not working image

**Comment by 3d-gussner** [comment]
@Lino77 using a newer Arduino IDE version will generate a much smaller hex file. BUT Prusa still wants us to use IDE 1.6.9 even with IDE 1.8.5 it is 4% and with IDE 1.8.7 it is 5% smaller.

@PavelSindler @XPila @mkbel
When do you switch to IDE 1.8.x as the MK3 branch is hitting the limits 98% again and again? The past showed that getting close to the limits do result in strange behave of the printer, it works sometimes and sometimes not.

**Please update at least the how-to-build guide especially around the language part to build MK3 Hex files and MK2.5 hex files. And provide the code/scripts PRUSA uses to compile the release hex files**

**Comment by Lino77** [comment]
1.6.9 don't work for me 
Build-Optionen wurden verändert, alles wird neu kompiliert
/home/lino/arduino-1.6.9/hardware/tools/avr/bin/../lib/gcc/avr/4.8.1/../../../../avr/lib/avr6/libc.a(isspace.o): In function `isspace':
(.text.avr-libc+0x2): relocation truncated to fit: R_AVR_13_PCREL against symbol `__ctype_isfalse' defined in .text.avr-libc section in /home/lino/arduino-1.6.9/hardware/tools/avr/bin/../lib/gcc/avr/4.8.1/../../../../avr/lib/avr6/libc.a(cty_isfalse.o)
collect2: error: ld returned 1 exit status
exit status 1
Fehler beim Kompilieren für das Board RAMBo.

**Comment by Lino77** [comment]
lino@ubuntu:~/Dokumente/Prusa-Firmware-3.4.0_mk3/lang$ ./lang-check.sh de 
dictionary file: lang_en_de.txt - OK
language bin file: lang_de.bin - OK
header='a5 5a b4 4b 3c 28 42 01 3d d3 65 64 42 01 15 a0 '
magic='0xa55ab44b'
./lang-check.sh: 44: ./lang-check.sh: Bad substitution

**Comment by 3d-gussner** [comment]
@Lino77 did you modify the platform.txt as described in the readme.txt? And NEVER EVER update the AVR boards under boards manager in IDE 1.6.9!!! 
I use IDE 1.6.9 and IDE 1.8.5 in portable mode under Windows 10. Had to change few things (Paths) to be able to run the lang scripts.sh under git bash.

Here my results:

```
$ bash make_lang.sh de
de
make_lang.sh started
selected language=de
 checking input files...OK
 creating tmp files...OK
 comparing tmp files...OK
 generating lang_de.txt...OK
 generating lang_de.dat...OK
 generating lang_de.ofs...OK
 generating lang_de.bin:
  writing header (16 bytes)...OK
  writing offset table (644 bytes)...OK
  writing text data (9640 bytes)...OK
  updating signature...OK
 lang_table details:
  lt_count = 322
  lt_size  = 10300
  lt_chsum = 7b9a
make_lang.sh finished with success
```

and
```
$ bash lang-check.sh de
dictionary file: lang_en_de.txt - OK
language bin file: lang_de.bin - OK
header='a5 5a b4 4b 3c 28 42 01 9a 7b 65 64 ff ff ff ff '
magic='0xa55ab44b'
size='0x283c' (10300)
count='0x0142' (322)
binary data OK
```

**Comment by Lino77** [comment]
witch readme.txt 
modify platform.txt to enable float printf support: "compiler.c.elf.flags=-w -Os -Wl,-u,vfprintf -lprintf_flt -lm -Wl,--gc-sections"

**Comment by Lino77** [comment]
lino@ubuntu:~/Dokumente/Prusa-Firmware-3.4.0_mk3/lang$ ./make_lang.sh de
de
make_lang.sh started
selected language=de
 checking input files...OK
 creating tmp files...OK
 comparing tmp files...OK
 generating lang_de.txt...OK
 generating lang_de.dat...OK
 generating lang_de.ofs...OK
 generating lang_de.bin:
  writing header (16 bytes)...OK
  writing offset table (644 bytes)...OK
  writing text data (9640 bytes)...OK
  updating signature...OK
 lang_table details:
  lt_count = 322
  lt_size  = 10300
  lt_chsum = d33d
make_lang.sh finished with success

**Comment by Lino77** [comment]
lino@ubuntu:~/Dokumente/Prusa-Firmware-3.4.0_mk3/lang$ ./lang-check.sh de
dictionary file: lang_en_de.txt - OK
language bin file: lang_de.bin - OK
header='a5 5a b4 4b 3c 28 42 01 3d d3 65 64 42 01 15 a0 '
magic='0xa55ab44b'
./lang-check.sh: 44: ./lang-check.sh: Bad substitution
lino@ubuntu:/Dokumente/Prusa-Firmware-3.4.0_mk3/lang

**Comment by Lino77** [comment]
1.6.9 reinstall compile goes now
but not lang yet
@ 3d-gussner what is your approach

**Comment by Lino77** [comment]
Okay with windows its works now i don't know why

**Comment by 3d-gussner** [comment]
@Lino77 here some things I changed to be able to compile the firmware with languages:
1. Downloaded Arduino-IDE-1.6.9-windows.zip file from https://www.arduino.cc/download_handler.php?f=/arduino-1.6.9-windows.zip
2. extracted the zip in my `<path>`
3. created folder **portable** under `<path>\arduino-1.6.9-windows\arduino-1.6.9\`
Making it portable i can separate the Prusa Firmware IDE 1.6.9 from other Arduino projects, libraries, boards and sketches. It is dedicated for Prusa Firmware.
3.a so you have `<path>\arduino-1.6.9-windows\arduino-1.6.9\portable`
4. created a folder **output** under <path>arduino-1.6.9-windows\arduino-1.6.9\portable
4.a now you have `<path>\arduino-1.6.9-windows\arduino-1.6.9\portable\output`
5. added/modified to `<path>\arduino-1.6.9-windows\arduino-1.6.9\portable\preferences.txt` the lines 
```
board=rambo
boardsmanager.additional.urls=https://raw.githubusercontent.com/ultimachine/ArduinoAddons/master/package_ultimachine_index.json
build.path=<path>\arduino-1.6.9-windows\arduino-1.6.9\portable\output
build.verbose=true

...

serial.stopbits=1
sketchbook.path=<path>\arduino-1.6.9-windows\arduino-1.6.9\portable\sketchbook\libraries
software=ARDUINO
```
6. update the libraries when they show up BUT NEVER EVER update the **Arduino AVR Boards** in the board manger these must stay under IDE 1.6.9 at **version 1.6.11**
7. made some changes to the language sh scripts

- /lang/config.sh
```
# Arduino main folder:
export ARDUINO=<path>/arduino-1.6.9-windows/arduino-1.6.9

...

# Output folder:
export OUTDIR="<path>/arduino-1.6.9-windows/arduino-1.6.9/portable/output"
```
This matches my Prusa IDE 1.6.9 paths with the language sh scripts

- /lang/fw-clean.sh
```
rm_if_exists update_lang_es.out
rm_if_exists update_lang_fr.out
rm_if_exists update_lang_it.out
```
was missing to cleanup French files

- /lang/lang-build.sh
```
 generate_binary 'es'
 generate_binary 'fr'
 generate_binary 'it'
```
was missing to generate French files

- lang/lang-clean.sh
```
clean_lang()
{
 if [ "$1" = "en" ]; then
  rm_if_exists lang_$1.tmp
 else
  rm_if_exists lang_$1.tmp
  rm_if_exists lang_en_$1.tmp
  rm_if_exists lang_en_$1.dif
```
was missing to cleanup some .tmp files

- lang/make_lang.sh
```
case "$LNG" in
 *en*) lt_code='\x6e\x65' ;;
 *cz*) lt_code='\x73\x63' ;;
 *de*) lt_code='\x65\x64' ;;
 *es*) lt_code='\x73\x65' ;;
 *fr*) lt_code='\x72\x66' ;;
 *it*) lt_code='\x74\x69' ;;
 *pl*) lt_code='\x6c\x70' ;;
esac
```
The fr code was wrong

- lang/postbuild.sh
```
#check for messages declared in progmem1, but not found in lang_en.txt
echo -n " checking textaddr.txt..." >&2
if cat textaddr.txt | grep "^ADDR NF" > missing_in_lang_en.txt; then

...

#create binary file with all languages
rm -f lang.bin
if [ -e lang_cz.bin ]; then cat lang_cz.bin >> lang.bin; fi
if [ -e lang_de.bin ]; then cat lang_de.bin >> lang.bin; fi
if [ -e lang_es.bin ]; then cat lang_es.bin >> lang.bin; fi
if [ -e lang_fr.bin ]; then cat lang_fr.bin >> lang.bin; fi
if [ -e lang_it.bin ]; then cat lang_it.bin >> lang.bin; fi
if [ -e lang_pl.bin ]; then cat lang_pl.bin >> lang.bin; fi

```

changed the output of missing messages in the code to a file instead of to NULL
French part was missing

Still wait for Prusa to update their scripts and how-to build instructions. 
Hope that helps.

**Comment by 3d-gussner** [comment]
@XPila I had a way to generate multi language hex files BUT it has been fixed-broken again, which is very frustrating.

**CAN YOU PLEASE RELEASE THE CODE YOU ARE USING TO COMPILE THE HEX files you publish in the releases.**

I  use https://github.com/prusa3d/Prusa-Firmware/commit/0f02f9a4e35f2e0697711196b97a639f2e4d7d8b version of the MK3 branch which is FW 3.5.0-RC1 if i am not wrong.

AGAIN i am not able to make my modifications or even re-compile the original firmware.
Here my steps:
1. Changed `#define LANG_MODE` to `1 // sec. language support` to support multiple languages
2. Copied "variants/1_75mm_MK3-EINSy10a-E3Dv6full.h" as "Configuration_prusa.h" file from variants (EINSY)
3. Opened Arduino IDE 1.6.9 or 1.8.5 portable mode
4. Open in Arduino IDE Firmware.ino
5. Verify the code (modified "/portable/preferances.txt" file with my `build.path`) which generates "Firmware.ino.elf" "Firmware.ino.hex" files in my "/Arduino..../portable/output" folder as well under "/Arduino..../portable/output/sketch" the needed files for building language files and multilanguage firmware
6. Using Git bash in the "Prusa-Firmware/lang" folder
7. `bash lang-build.sh all` creates all need files
8. `bash fw-build.sh` generates these results
 ```
bash fw-build.sh
config.sh started
 Arduino main folder: OK
 Arduino builder: OK
 AVR gcc tools:
   objcopy OK
   objdump OK
 Output folder: OK
 Objects folder: OK
 Generated elf file: OK
 Generated hex file: OK
config.sh finished with success
postbuild.sh started
 checking files:
  folder  OK
  elf     OK
  objects OK
 running progmem.sh...OK
 running textaddr.sh...OK
 checking textaddr.txt...OK
 extracting binary...OK
 updating binary:
  primary language ids...OK
  primary language signature...OK
 converting to hex...OK
  secondary language data...Updating languages:
 Czech  : NG!
 German : NG!
 Italian: NG!
 Spanish: NG!
 French : NG!
 Polish : NG!
 converting to hex...OK

postbuild.sh finished with success
```

With a "firmware.hex" file which is bigger than the 1st one. BUT why do i get "NG!" during this procedure? In the past it was OK!
Also the "update_lang_??.out" files all have
```
update_lang.sh started
 selected language=es
 checking files...OK
 checking symbols...NG!\n  symbol _SEC_LANG not found!
update_lang.sh finished with errors!
```

So what happens here?
Also checking the "text.sym" file i cannot find the "_SEC_LANG" anymore.


Please helps us.

I would like to add other languages as i did in the past for the MK2 branch so children and non-native-english-speaking persons can use their printers easier.

**Comment by 3d-gussner** [comment]
Update:
Started to migrate @mkbel PF-build-env from Linux64 to Windows and works fine, checkout https://github.com/3d-gussner/Prusa-Firmware/tree/MK3-win_build. You just need to read notes to prepare Windows and than run `bash win_build.sh <varaiant>`. As soon i get some feedback from others i will try a pull request.

@XPila @mkbel @PavelSindler 
- Can you please let us know what format `lang-add.sh` expects in `lang_add.txt`?
- how does the `lang-import.sh` / lang-export.sh procedure works?

**Comment by 3d-gussner** [comment]
Checkout https://github.com/3d-gussner/Prusa-Firmware/wiki/How-to:-Build-Prusa-Firmware

**Comment by 3d-gussner** [comment]
As the pull request https://github.com/prusa3d/Prusa-Firmware/pull/1543 is pulled ... i close this issue
