### ISSUE TITLE
3.4 Final:   Doesnt Resume after FIlament runout / undetection

### ISSUE THREAD

**Issue by christizzz** [prusa3d/Prusa-Firmware#1154]
I was printing... then the Sensor triggered... the print head moved to the front right corner and the printer asked to unload filamen... after unloading and loagin filament... the print head moved to its last position and sits there and it started a blob on the print and didt move.  In the menu o pressed the resume print... the print head homed all axes really SLOW... and then moved back to  the print  to a wrong position and on a lower Z height wich destroyed the print on its path...i had to reset...

**Comment by nojan1** [comment]
Exactly the same thing happened to me. Except the filament got stuck on the spool, so didn't technically run out. Anyhow didn't resume correctly and crashed into the print.

**Comment by vw671** [comment]
Yup. I had exactly the same issue after runout detection. reverted back to 3.3.1

**Comment by MarcoZ76** [comment]
This happened also to me. Please solve asap

**Comment by mejlgaard** [comment]
I have had the exact same issue happening after updating to 3.4.0

**Comment by theinternetftw** [comment]
Same issue. This bug should maybe be renamed, as it's current name doesn't make clear quite how serious it is: the filament runout that starts the problem is a false positive (at least it was for me), which means it strikes at random and you can't take steps to avoid it, and trying to resume the print destroys the print instead.

At least it's easy to revert to 3.3.1.

**Comment by PavelSindler** [comment]
Fixed in PR https://github.com/prusa3d/Prusa-Firmware/pull/1174. We will prepare 3.4.1 asap. Thank you for reporting.

**Comment by KA-ARCHER** [comment]
Only in part, the print was going fine, it stopped printing the head came to the front right, asked to unload, then reload, went back to printing without problem. The print was OK. In the error statistics no comment, 0 errors.

**Comment by 3d-gussner** [comment]
@christizzz Is this still an issue? This post have been stale for long time. If it has been fixed please close this issue.
[stale]
