### ISSUE TITLE
Firmware 3.4.0: Remaining printtime not shown

### ISSUE THREAD

**Issue by Scotty59** [prusa3d/Prusa-Firmware#1155]
When connected to octoprint v1.3.9 the remaining printtime is not shown on the LCD.

**Comment by 3d-gussner** [comment]
Did you use newest Slic3r with standard profiles? Saw some user used custom profiles missing that option

**Comment by martysweet** [comment]
I had this problem also, as @3d-gussner mentioned, ensure "Firmware > Supports remaining times" is selected under Printer Settings in Slic3r.

**Comment by Scotty59** [comment]
Ok, thank you for pointing me in the right direction. Changed the profile in slicr and this was not marked.
