### ISSUE TITLE
Firmware 3.4.0 MK3: Axis value not displayed 

### ISSUE THREAD

**Issue by batezu** [prusa3d/Prusa-Firmware#1157]
After upgrade with arduino on display the value of Z in mm does not appear, only appears "?"
even if you go to move in the X Y Z settings, the value will not appear in mm but always "?"

**Comment by Panayiotis-git** [comment]
You should have missed the paragraph 1.3 of the compile instruction at Prusa's github page:
https://github.com/prusa3d/Prusa-Firmware

Check also the #1117

**Comment by batezu** [comment]
Thank you, now is correct!!
