### ISSUE TITLE
Filament sensor not responding in v3.4.0

### ISSUE THREAD

**Issue by ammas09** [prusa3d/Prusa-Firmware#1160]
To the point:
The filament sensor on my PRUSA i3 MK3 does not seem to be recognizing 90% or more of my filaments (most of which are solid, not clear, colors) such that it will not auto load the filament.  Of the few that actually auto load a message comes up recommending to disable the filament sensor.

Some more detail:
Prior to the v3.4.0 update for the MK3 I had numerous prints where it seemed to be constantly stopping and prompting me to remove and re-insert the filament (several times an hour).  \

I went through and cleaned the sensor with compressed air as recommended in the manual.   The issue still persisted.

I checked the wiring was connected securely and that the chamber surrounding the sensor was clean and free of all derbies.  The issue still persisted.

I removed the sensor itself and very very careful wiped it off with a special SLR camera lens cleaning cloth I have and you guessed it.  The issue still persisted...

So it came to the point where I just left the sensor disabled hoping that a future firmware update might help.  

I updated to v3.4.0 and now it tells me that it may not work or it just doesn't recognize my filament at all...  so still not working.

I contacted Prusa chat and explained all of this, they recommended that I clean the sensor (which I will try yet again when my current print completes) and that I come here and report my issue.

Any thoughts or ideas on how to get this working would be greatly appreciated.

If there are any details that would help please let me know and I will respond as soon as I can.

Thanks!

**Comment by Chris096** [comment]
Same thing for me + the Z axis is moving slow as a turtle on weed. But perhaps when you leave the Stealth mode it's back to normal. They should come with an update as soon as possible. Those are serious flaws.

**Comment by Crowlord** [comment]
I have found that the new FW has made the sensor far more sensitive. 

It has gone from being close to perfect to pretty much useless.

**Comment by PavelSindler** [comment]
@ammas09 this one sounds like faulty filament sensor to me. We are doing more tests now, so I will provide more information soon.
@Chris096 we finaly reproduced this issue today (slow Z in stealth mode). We have one printer with this behaviour here. I will check what is happening there and inform you later.

**Comment by ammas09** [comment]
@PavelSindler are there tests I can run to confirm if it is a faulty sensor? If it is how do I go about getting a replacement? Thanks.

**Comment by dikodahan** [comment]
I can confirm on my end that I have has many issues with black filaments, both PLA and PETG, before 3.4.0 and with the new firmware I do see that from time to time it stops the print, does a quick pull and push of the filament to make sure it's there and continues.
My experience is that it has improved the sensor behavior.

Nothing against your bad experience @ammas09, just wanted to add this as feedback for the developers!

**Comment by ammas09** [comment]
@dikodahan glad to hear the update is working for you.  The check method you described makes allot of sense for the firmware to do a quick check by moving the filament and confirm if there is an actual issue.

As a quick update for what I am seeing, I did take out the filament sensor and carefully clean and inspect it.  I could not see any visual issues with it.  I also cleaned out the extruder assembly with some compressed air while I had the sensor out.  Everything looked good in there as well.

After reassembly I have the same issues...

I may take a logic analyzer and/or oscilloscope and probe the signals coming out of the filament sensor to see if anything looks awry there.  The difficulty I have with that is I don't have a sample of a known good sensor to compare against.

**Comment by PavelSindler** [comment]
@Chris096 This should help:
update fw to 3.4.0 and connect on serial line (for example from Pronterface, Octoprint, Arduino IDE), then send M502 gcode on serial line. This will load default settings. Then store this settings to eeprom with M500 command. This will fix "slow printer in stealth mode" issue. If you have run PID calibration or if you have stored some custom settings to eeprom using M500, you will have to re-do these steps (usually just re-run PID calibration).

**Comment by PavelSindler** [comment]
@Chris096 Let me know if that helps. Also I would like to know if you have used fw which you have built yourself or if you are using just pre-built hex files from our website/github releases. Thank you.

**Comment by Chris096** [comment]
Hi, I'm not familiar with .hex files, I just use pre-built version that are
release.
I'm not sure I understand what to do when you say send M502 gcode on
serial, sorry?

Christian



Le mer. 19 sept. 2018 à 07:28, PavelSindler <notifications@github.com> a
écrit :

**Comment by geeksville** [comment]
Btw - I opened a similar (but not identical) bug report #1178.  My filament sensor worked _great_ with 3.3.1 but now very poorly with 3.4.0.

**Comment by geeksville** [comment]
@ammas09 
> I may take a logic analyzer and/or oscilloscope and probe the signals coming out of the filament sensor to see if anything looks awry there. The difficulty I have with that is I don't have a sample of a known good sensor to compare against.

I doubt that would show much (other than i2c or spi packets).  Their board is just a carrier for a fully self contained I2C/SPI part - it gets power and talks via serial protocol to the AVR on the einsy.  So not much to debug there if the part is talking to the einsy at all.  http://www.pixart.com/upload/PAT9125EL_GDS_V1.2_31052017_20171011150843.pdf

**Comment by ammas09** [comment]
@geeksville Good point.  I could decode the data being sent and look at the raw data being reported back to the einsy board, but without a basis for comparison I'm not sure how much insight that will actually provide.
