### ISSUE TITLE
Printer times out with octoprint when bad sensor is reported

### ISSUE THREAD

**Issue by Crowlord** [prusa3d/Prusa-Firmware#1168]
It seems that the busy signal is not sent when the "Detector not sensing reliably" message is on screen leading to an octoprint timeout.

As a workaround I have upped the timeout times in octoprint. 

FW 3.4.0 running on mk2.5
OctoPrint 1.3.9 running on OctoPi 0.14.0

**Comment by cbxbiker61** [comment]
I'm also seeing a timeout in OctoPrint.  I don't think I had a detector error since I didn't see anything unusual on the LCD when I discovered the problem.  I didn't notice the timeout immediately, maybe the detector error went away.

**Comment by michalxfanta** [comment]
Duplicate #1180
