### ISSUE TITLE
Change the direction of rotation of the controller in Main Menue

### ISSUE THREAD

**Issue by Devilscave** [prusa3d/Prusa-Firmware#1170]
It bothers me since I got my MK3 and I just can not get used to it. The direction of rotation of the controller to the menu is the wrong way around. Some things but like temperature regulation are right around. If I turn clockwise it goes down and around. For this purpose, the controller would have to sit to the left of the display. I have now resolved this error myself by crossing the two traces on the control board. Now, however, the settings of the individual values are the wrong way round, but I have to run there much less often than in the menu scrolling back and forth.

**Comment by Devilscave** [comment]
I took care of the problem myself. You can find instructions on Thingiverse.
https://www.thingiverse.com/thing:3103099

**Comment by cimoalpacino** [comment]
If I'm not wrong the direction could be inverted in firmware.

**Comment by Devilscave** [comment]
That's why I opened this message.

**Comment by cimoalpacino** [comment]
No need to solder.
Everything can be done in FW. 

https://github.com/prusa3d/Prusa-Firmware/blob/MK3/Firmware/lcd.h

Just need to play with encoder settings and thats it. 
See original Marlin FW examples and for different types of boards.

**Comment by Devilscave** [comment]
OK, I've got something to do with the firmware and how to play it. Did everything exactly followed but get now shortly before the end of the combination this error:        (my Arduino IDE is 1.6.9)

c:/program files (x86)/arduino/hardware/tools/avr/bin/../lib/gcc/avr/4.8.1/../../../../avr/lib/avr6\libc.a(isspace.o): In function **`isspace**':

(.text.avr-libc+0x2): relocation truncated to fit: R_AVR_13_PCREL against symbol `__ctype_isfalse' defined in .text.avr-libc section in c:/program files (x86)/arduino/hardware/tools/avr/bin/../lib/gcc/avr/4.8.1/../../../../avr/lib/avr6\libc.a(cty_isfalse.o)

collect2.exe: error: ld returned 1 exit status

exit status 1
Fehler beim Kompilieren für das Board RAMBo.

**Comment by Devilscave** [comment]
Should go in the firmware if you change the values x0B & x01 in line 214 & 215. But how can I import this?

**Comment by pedjas** [comment]
This is really annoying issue and as it looks like easy to fix in firmware
Hope it will be done soon.

**Comment by Panayiotis-git** [comment]
@pedjas If you have the original Prusa display or a compatible one (see LDO) everything works fine.
If you have a RepRap display then you have to modify the FW yourself or do the hardware fix.

**Comment by pedjas** [comment]
I have original display controller. No it does not work fine. 

Menus rotates are backwards. But some other settings are rotated normally.

Those are two issues: one that rotation is backward (by some opinions which is debatable) and second: it behaves differently in different parts of interface (which is not good at all).

I could follow advices to change wiring or move button, but then I would fix one issue and then other parts of interface would be moved backward.
