### ISSUE TITLE
start line expanding

### ISSUE THREAD

**Issue by Devilscave** [prusa3d/Prusa-Firmware#1171]
Starts the pressure not only with a straight line from left to right but a corner and a direction change. Since now and then by the straight line a small drop at the nozzle forms and sticks, burns and then lands somewhere in the pressure.

**Comment by stahlfabrik** [comment]
Are you aware that this start line is part of your slicers output? You can customize it if you want in your start gcode. It is not firmware

**Comment by Devilscave** [comment]
Where can I find that?
I found something in "Start G-Code".
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0  F1000.0 ; intro line
G1 X100.0 E12.5  F1000.0 ; intro line
G92 E0.0
M221 S{if layer_height==0.05}100{else}95{endif}

Where can i find a list of all comands for G-Code?

**Comment by stahlfabrik** [comment]
That is exactly the place. 

The marlin wiki has a good overview over most codes
