### ISSUE TITLE
3.4.0 Firmware - LCD font broke after print

### ISSUE THREAD

**Issue by cerw** [prusa3d/Prusa-Firmware#1172]
Hi

Flashed my i3 Mk3 and after 12h print I saw this on my LCD screen: 

![img_20180919_094401](https://user-images.githubusercontent.com/16146/45726815-7d64b880-bbf3-11e8-91ca-a78f2e69261f.jpg)

Did not see any odd behaver just thought it would be useful to report.

Thanks for making great printers!

**Comment by PavelSindler** [comment]
Hi, thank you for reporting this.

**Comment by rdavolio** [comment]
Same issue with me

**Comment by cerw** [comment]
This is still issue even on 3.4.1 only after successful print.

**Comment by cerw** [comment]
I still have this on 3.5.0 :(

**Comment by PavelSindler** [comment]
Does this appear after every succesfull print or is does it appear randomly? This may be caused by static electricity or broken LCD cable/connection.

**Comment by cerw** [comment]
After a successful print.

**Comment by PavelSindler** [comment]
Each time?

**Comment by cerw** [comment]
_Ano prosim_  Yes
