### ISSUE TITLE
MK3 reboots on gcode file, firmware 3.4.0

### ISSUE THREAD

**Issue by SherifNagy** [prusa3d/Prusa-Firmware#1183]
Hello,

I was looking at something to print yesterday, and I checked this website https://www.prusaprinters.org/10-handy-little-gadgets-for-beginners-in-3d-printing/

so I got the this https://www.prusa3d.com/downloads/g-codes/spool_clips_PLA_FAST.zip#_ga=2.245052421.1855916921.1537518101-1547292693.1533726187&_gac=1.3475204.1534943980.EAIaIQobChMI-MHg1sOA3QIVCLvtCh0n8wsTEAQYASABEgJhHPD_BwE gecode for spool clip, and once I picked to print it, the printer reboots, I tired it couple of times, and same behavior, however I am not sure if this exists in the previous firmware or not.

**Comment by PavelSindler** [comment]
Thanks, we will test it today.

**Comment by inquisitiveKangaroo** [comment]
Hi,
I have a problem to replicate it. So far it succesly finished the gcode everytime I tried to print it. Would be possible if you provided us more information such as type of your printer, wheras you print from SD card or via Octoprint. Anything what might be important.
Thank you

**Comment by SherifNagy** [comment]
Hello,

I am printing from the SDcard a 16G class 10 SDcard, I have Prusa i3 MK3 with latest firmware.

Regards,

**Comment by inquisitiveKangaroo** [comment]
Allright,
Such thing may occure by short circuit either in nozzle wiring or power source. Try to preheat nozzle, cool it down, then preheat the bed. If the problem occure both times I would recomend to exchange the power source. If it occures just once I would exchange bed wiring or heater wiring (depens on which one cause it). In case neither of those reboot the printer, please let us know and we will keep looking.)

**Comment by SherifNagy** [comment]
I will try that, but just to clarify, the printer works fine and prints other gcode, it just this gcode file that crashes it.

**Comment by SherifNagy** [comment]
Also I just did the test as @inquisitiveKangaroo suggested and nothing rebooted

**Comment by SherifNagy** [comment]
I did try again to print the same file from same SD card and it just worked !

**Comment by inquisitiveKangaroo** [comment]
Is it still happening or the issue totally disappeared? Could you provide us the gcode (not just the link you downloaded it from)?

**Comment by SherifNagy** [comment]
it did print, I will try again tomorrow, and here is the gcode attached 
[spool.zip](https://github.com/prusa3d/Prusa-Firmware/files/2415067/spool.zip)
