### ISSUE TITLE
Do bed level check while preheating instead of waiting for preheat to finish. 

### ISSUE THREAD

**Issue by Sporko** [prusa3d/Prusa-Firmware#1185]
Would just save a bit o' time.

**Comment by stahlfabrik** [comment]
You could do that yourself - you will just need to rearrange the "Start Gcode" in Slic3r.

But beware: The bed deforms a little when heated - so I would strongly recommend not to do it like you want;-)

**Comment by Panayiotis-git** [comment]
You can do this if you preheat only the hot-end and print with the bed at room temperature.

In fact, the heating bed deforms a lot while heated. Send a G80, G81 on a cool bed and repeat them after you heat it at 100oC. You will see by yourself the differences.

**Comment by Sporko** [comment]
Ah... awesome, thanks (newbie here.)  OK, I moved bed leveling to between wait for bed temp and wait for extruder temp.  At least it'll get started sooner if bed is ready first.
