### ISSUE TITLE
MK3 3.4.0 cannot exit long-press Z adjust after first layer calibration

### ISSUE THREAD

**Issue by bozzzzo** [prusa3d/Prusa-Firmware#1195]
While playing with the MMU I'm finding myself doing a lot of first layer calibrations to test that all filaments are loading properly...

If the first thing  after first layer calibration is complete I do a long-press I get the Z adjust which cannot be exited with another long press. I need to reset to get out...

**Comment by stahlfabrik** [comment]
On MK3 3.4.1 - no MMU - I also ran into the problem that the Long Press "move Z" menu could not be left. Had also to reset.

**Comment by Panayiotis-git** [comment]
@DRracer I think this should also be closed by the 
https://github.com/prusa3d/Prusa-Firmware/commit/33037d369cf35fb0ea8d962bb9c8d26df9dfd561
