### ISSUE TITLE
MK3 3.4.0 Trying to exit Z adjust with a long-press prevents exiting at all

### ISSUE THREAD

**Issue by bozzzzo** [prusa3d/Prusa-Firmware#1196]
Turn on MK3. long press the button. Z adjust appears. long press the button again. cannot exit from the Z adjust anymore. probably related to #1195

**Comment by stahlfabrik** [comment]
I have had the exact same issue happening on 3.4.1

**Comment by Panayiotis-git** [comment]
Why I think that after adjusting the Z height, a simple press to the button exits the screen?

**Comment by stahlfabrik** [comment]
@Panayiotis-git of course, if the bug is not in affect, that is how it SHOULD work.

When the bug happens, you can't leave the menu. You can only press reset.

**Comment by Panayiotis-git** [comment]
Finally, I got it!

ultralcd.cpp, line 7297, replace the content of menu_lcd_longpress_func with:

    void menu_lcd_longpress_func(void)
    {
        if (menu_menu == lcd_move_z) {
            lcd_long_press_active = 0;
            return;
        }

        move_menu_scale = 1.0;
        menu_submenu(lcd_move_z);
    }

**Comment by Panayiotis-git** [comment]
The commit 95b0506, changed the scope of the lcd_long_press_active, so the above fix is no longer valid.

**Comment by Panayiotis-git** [comment]
So, new fix:
lcd.cpp, method void lcd_buttons_update(void), line 803
partially uncomment the else block:

           if (lcd_long_press_active == 0)
            { //button released before long press gets activated
                newbutton |= EN_C;
            }
            else lcd_quick_feedback();

**Comment by maximlevitsky** [comment]
Still happens on 3.5.1. 100% reproducible.
Just do a long press to enter the Z axis mode and then another long press.

**Comment by sgoll** [comment]
The same happens with recent firmware version 3.6.0.

It also happens when long-pressing the knob during a print. In that case, why does the Adjust Z Height show up anyway? Does this make sense, or will the next G-Code command just override any changes that I make? Should it be possible to enter Adjust Z Height only when the print is paused?

The printer does not react to any user commands until restarted, even when the Adjust Z Height dialog disappears eventually.

(In my case, I ended up there because I wanted to do Live Z Adjustment and wasn't sure how to reach that. I would have expected to go there by long-pressing during a print.)

**Comment by ochm** [comment]
Yes, i found the same behavior in FW 3.6.0-2069 .
When the button is long pressed during print, it displays Z level change.
Well, the level can't be changed, OK, so the next press should return display to main menu, but does nothing, and after some timeout, the display is returned to main menu, but from this time the button does not react on press, and no menu can be accessed.
IMHO during print the long press of button should start the live Z adjust,
and after return from this process (after short press or timeout) the whole display should be fully functional.
Thanks for repair.

**Comment by Panayiotis-git** [comment]
The fix is a couple of posts above. You can give it a try. You have to compile the firmware yourself, though.

**Comment by ochm** [comment]
Thanks for information.
I payed for whole printer incl. firmware, not for DYI.

--
Martin

17. 3. 2019 v 9:30, Panayiotis-git <notifications@github.com>:

**Comment by myreauks** [comment]
This is still happening in the newest firmware. Even if you wouldn't add the live-z functionality during print for the long press, I think you should fix the printer user interface crash when long pressing the button during a print. I have a multiple hour print going currently, but cannot access the menu anymore as the printer is not responding to the button after long pressing it twice.

Is a fix coming in recent updates?

**Comment by 3d-gussner** [comment]
@bozzzzo Is this still an issue? If it has been fixed in a newer firmware version, please close this issue.
[stale]
