### ISSUE TITLE
Speed change returns to 100

### ISSUE THREAD

**Issue by jonbet83** [prusa3d/Prusa-Firmware#1208]
After a filament change on MMU 2 the speed defaults back to 100 even whens its been changed during the print.

**Comment by mikh3x4** [comment]
I would like to confirm this is indeed true and fixing it would make my workflow so much easier

**Comment by TickTock-** [comment]
Also, extruder temp reverts back to original temperature next time that same filament is loaded during the print.  Probably flow and the rest of the tune settings...  Tune needs to store independent values for each of the five MMU sources.

**Comment by JohnnyDeer** [comment]
Speed resetting between filament changes has already been fixed, I'm closing this issue.

**Comment by polygonalenippel** [comment]
I am experiencing speed reset between filament changes as well with the latest firmware.

- mk3s+, fw 3.9.3 3556
- mmu2s, fw 1.0.6 372

**Comment by simonemarin** [comment]
> I am experiencing speed reset between filament changes as well with the latest firmware.
> 
>     * mk3s+, fw 3.9.3 3556
> 
>     * mmu2s, fw 1.0.6 372

Same version same issue here
