### ISSUE TITLE
Firmware wish and filament sensor don't work

### ISSUE THREAD

**Issue by sheinrichs** [prusa3d/Prusa-Firmware#1210]
Hi,
is it posible to implement a selctor in the firmware MMU/Singel print it is realy uncomfortable to use the Printer in singel mode after installing the MMU the plug flap are in the wrong direction to unplug the cabel.
if there is a software solution to switch between singel and MMU mode it is only needed tu unscrew the PEFT Tube and a singel spool use is posible.

firmware MMU after a print don't know why the MMU has made no unloading the filament start at next day leds to an error course 1 filament is complitly loaded why i get an error if it realise there is a filament stil loaded why it don't preheat the nozzel by it self and do the unload instate of error maybe somtihng for the next MMU firmware. no error message self solution of this problem. maybe a short info in display wait printer is gettin ready or so.

while MMU is pluged the filament sensor don't work the printer try happaly printing even there is no filament loaded (i have unscrewd the TPFE tube and pull out the filament and printer don't stop(it was by testing to figureout why it was not printing the TPFE Tube length was to short and i had to recalibrate it))  without pluged MMU the sensor works fine firmware 3.4.0

regards Sascha

**Comment by JohnnyDeer** [comment]
Hi, this problematic is solved by MMU2S and single mode in PrusaSlicer, I'm closing this issue.
