### ISSUE TITLE
Error: Filament sensor is not responding Please check connection

### ISSUE THREAD

**Issue by toke2000** [prusa3d/Prusa-Firmware#1218]
with FW 331-845 all is working fine. 
After update to FW 3.4.0 - 1327 The sensor does not work anymore.
Back to an old FW all is working fine again.
i use slic3r to update the FW

Edit: FW 3.4.1 same problem. Sensor N/A

**Comment by zehkaiser** [comment]
Just tested 3.4.1-RC1 and the issue is still present. My filament sensor shows as N/A in the settings menu.

Edit: The sensor works fine with 3.3.1.

**Comment by KarlZeilhofer** [comment]
With MMU2 and FW-3.4.1 it seems to be completely deactivated. No smart behaviour at all.
