### ISSUE TITLE
FEATURE REQUEST: Prompt for filament before heating in MMU Single Material Mode

### ISSUE THREAD

**Issue by pleppik** [prusa3d/Prusa-Firmware#1219]
If you print in single material mode with the MMU, the printer needs to prompt for which filament to print with.

Currently this prompt happens after the preheating is complete and the printer has completed its bed leveling routine.

This can be several minutes after the print was started, and there is no audible alert to indicate that the printer needs attention. If the operator forgot that the printer needed attention, or left the room, it could be quite a while before the operator notices that he needs to select the filament.

It would be preferable to have the printer prompt for the filament selection immediately on starting the print, so that once the print is started the printer will not need additional attention to continue.

**Comment by JohnnyDeer** [comment]
This request has already been implemented, I'm closing.
