### ISSUE TITLE
Flash fails update for MK2S

### ISSUE THREAD

**Issue by wolbar** [prusa3d/Prusa-Firmware#1220]
This is the message I receive when trying to flash my i3 MK2S

avrdude: verifying ...
avrdude: verification error, first mismatch at byte 0x3c000
         0x04 != 0x87
avrdude: verification error; content mismatch

**Comment by AnHardt** [comment]
Firmware too large. Crash with bootloader area.

**Comment by wolbar** [comment]
Thank you.

**Comment by PavelSindler** [comment]
Can you pleasse tell me which firmware version and which hex file did you use or if you compiled firmware yourself?

**Comment by wolbar** [comment]
Sorry for confusion, I have not looked at Prusa for a year and became
confused with all of the models. I found the correct one. Good thing these
can't be bricked or I would have done it :0
