### ISSUE TITLE
[3.4.0] Disabling filament sensor (poor response) while printing crashes the head

### ISSUE THREAD

**Issue by nicolaszundel** [prusa3d/Prusa-Firmware#1228]
Hello,
 
Since I have upgraded to 3.4.0 I'm getting same issue like #1178.
But Once filament reloaded during print if I accept to disable the filament sensor, when the print resumes it just crashed in the already printed model (wrong Z) and stops.
When choosing not to disable, the prints resumes fine.
Printer crashes only if choosing to disable sensor by responding YES during print.
I'm printing from SD.

**Comment by PavelSindler** [comment]
It is fixed in latest release 3.4.1. Please upgrade.

**Comment by OutofDarts** [comment]
This is not fixed in 3.4.1.
