### ISSUE TITLE
No info on screen if speed is less then 27% in v3.4.1 mk3

### ISSUE THREAD

**Issue by dik123** [prusa3d/Prusa-Firmware#1231]
If I set speed via tune -> speed lower then 27% then only the file name is displayed on screen.
If I set speed to 27% or up all info will be displayed.

**Comment by inquisitiveKangaroo** [comment]
Hi,
thank you for your feedback. Seems like there is no such boundary like 27%, however, the info vanishes when your remainging time (which is increased by slowing the print speed) exceed 100 hours.
I belive we manage to fix this issue in the next release. Once again thank your for reporting it and I wish you happy printing time ;)

**Comment by PavelSindler** [comment]
Fixed in PR https://github.com/prusa3d/Prusa-Firmware/pull/1301.
