### ISSUE TITLE
MMU2 on MK3 Not working after Power Panic

### ISSUE THREAD

**Issue by tito2018** [prusa3d/Prusa-Firmware#1237]
After a power loss on the MK3 the MMU2 resets and "forgets" it was printing a Multi Color gcode when the power resumes, resulting in a wasted print since the unit only prints in single color mode after that. It does not seem to be storing its position on power outage. This is a major bug since it renders the Power Panic function useless when the Printer has the MMU2 attached.

**Comment by mylife4aiurr** [comment]
MMU2 has separate firmware:
https://github.com/prusa3d/MM-control-01/issues
