### ISSUE TITLE
MMU2: error state when printer boots with filament in FINDA

### ISSUE THREAD

**Issue by KarlZeilhofer** [prusa3d/Prusa-Firmware#1240]
Hi, 

it seems, there is no normal way to resolve the issue, when the printer was reset during a print. 

E.g. filament 1 is loaded into the extruder. Then the MMU2 LEDs are all flashing red. But in the menu there is no option "Eject Filament". 

The only way seems to open the MMU2 and disconnect  the bowden tube and manually unload the filament, cut it if necessary and put it back in place. 

Solution:
If the printer boots in this error state, there should be a dialoug to preheat the the extruder ram and eject the filament.

**Comment by mylife4aiurr** [comment]
MMU2 has separate firmware:
https://github.com/prusa3d/MM-control-01/issues

**Comment by KarlZeilhofer** [comment]
Thanks for that hint. But should I report it twice? This issue seems to fit better into this project, because the printer firmware is responsible for the UI on the LCD, right?

**Comment by gudnimg** [comment]
This is definitely solved in 3.13.0. Adding this to the Milestone as a reminder to close the issue.

**Comment by gudnimg** [comment]
Closing as this is now resolved with FW 3.13.0 and MMU FW 3.0.0 :)
