### ISSUE TITLE
MMU2: confusing term "Load Filament"

### ISSUE THREAD

**Issue by KarlZeilhofer** [prusa3d/Prusa-Firmware#1241]
that term is very confusing, since it is used for loading the extruder with filament and for loading the MMU2 with filament. For unloading there is a different term (unload vs. eject), but I'm not happy with them, since they are not self explaining. 

For loading I would suggest: 
* Load Filament into MMU
* Load Filament into Extruder

**Comment by AbeFM** [comment]
I am becoming partial to the term "Preload".

**Comment by laird** [comment]
It's an important distinction, but the display is small, so how about compressing down to:

- Load Extruder
- Load MMU

**Comment by AbeFM** [comment]
I like it

**Comment by inquisitiveKangaroo** [comment]
Solved in 3.5.0 - RC1 by 'Load filament' / 'Load to nozzle' features. Thank you for feedback, we appreciate it.)
