### ISSUE TITLE
MMU2: missing option to flood the nozzle

### ISSUE THREAD

**Issue by KarlZeilhofer** [prusa3d/Prusa-Firmware#1242]
before MMU2 i could flood the nozzle by preheating and selecting "Load Filament". 

But that doesn't work with MMU2 any more, since the the filament is only loaded into the MMU2. Pleas also refer to #1241. 

An option "Load Filament into Extruder" would help to solve this problem.

**Comment by inquisitiveKangaroo** [comment]
Solved in 3.5.0 - RC1 by 'Load filament' / 'Load to nozzle' features.

**Comment by inquisitiveKangaroo** [comment]
MMU Feature Requests #49

**Comment by inquisitiveKangaroo** [comment]
MMU Feature Requests #49
