### ISSUE TITLE
3.4.0 MK3 erratic eeprom value.

### ISSUE THREAD

**Issue by hon-po** [prusa3d/Prusa-Firmware#1245]
Tried to save a new PID value to eeprom and noted following new parameter with erratic value:
echo:Maximum feedrates - stealth (mm/s):
echo:  M203 Xnan Ynan Znan Enan
echo:Maximum acceleration - stealth (mm/s2):
echo:  M201 X960 Y960 Z4294967295 E4294967295

Suspect new entries added to eeprom after certain firmware version. Firmware description should remind users to restore eeprom to default value if the eeprom structure is changed.

**Comment by darBis** [comment]
Hi, this was fixed in latest firmware 3.4.1. see issue #1152
