### ISSUE TITLE
Incomplete GCode according to MK2S MMU Printer

### ISSUE THREAD

**Issue by bubnikv** [prusa3d/Prusa-Firmware#1252]
Prusa i3 MK2 firmware needs to be updated to search for the end of G-code delimiter (motor power off) over a longer G-code block than now.

See https://github.com/prusa3d/Slic3r/issues/1305

This issue was fixed for MK2.5 and MK3 already, it needs to be ported to MK2.

**Comment by spiff123** [comment]
Would be nice if this makes it in a 3.1.1 firmware...

**Comment by 3d-gussner** [comment]
Closing as the MMU1 is EOL
