### ISSUE TITLE
can't compile current Firmware

### ISSUE THREAD

**Issue by Devilscave** [prusa3d/Prusa-Firmware#1255]
I always get the following error while compiling the current firmware.
I have all done as described in the manual, I also use the IDE 1.6.9. But it always brings the same mistake. On the firmware, I have not changed anything, had anyone ever?

g:/3d drucke/mk3 software/arduino-1.6.9/hardware/tools/avr/bin/../lib/gcc/avr/4.8.1/../../../../avr/lib/avr6\libc.a(isspace.o): In function `isspace':

(.text.avr-libc+0x2): relocation truncated to fit: R_AVR_13_PCREL against symbol `__ctype_isfalse' defined in .text.avr-libc section in g:/f platte/3d drucke/mk3 software/arduino-1.6.9/hardware/tools/avr/bin/../lib/gcc/avr/4.8.1/../../../../avr/lib/avr6\libc.a(cty_isfalse.o)

collect2.exe: error: ld returned 1 exit status

exit status 1
Fehler beim Kompilieren für das Board RAMBo.

**Comment by Devilscave** [comment]
OK i found the problem. I skipped possition 3 under step 1. But that is not really understandable written. Which "platform.txt" is meant? And the command had to be adjusted a bit more. I changed it like this:
{compiler.c.elf.flags} -w -Os -Wl,-u,vfprintf -lprintf_flt -lm -Wl,--gc-sections _-mmcu={build.mcu}_
The last part (in italic) was already there, is that right? Can anybody confirm this?

**Comment by Panayiotis-git** [comment]
This is a place to post issues regarding the firmware. Not a place to post the failed tries to compile the firmware.
Please, have a quick look at the closed issues. I have lost the count of the issues opened regarding the exact same thing.
You may consider to use the forums to get support on this issue.

**Comment by 3d-gussner** [comment]
Checkout https://github.com/3d-gussner/Prusa-Firmware/wiki/How-to:-Build-Prusa-Firmware

**Comment by cimoalpacino** [comment]
this can also be closed

**Comment by 3d-gussner** [comment]
@Devilscave  Long time no update here. Can you please close this issue?
