### ISSUE TITLE
MMU2 bleep if problem with filaments

### ISSUE THREAD

**Issue by gwildavies** [prusa3d/Prusa-Firmware#1258]
The normal Prusa i3 Mk3 makes bleeping sound when there is a problem with a filament.
This is really useful for being notified of problems if you are not watching the printer.
So far the MMU2 does not make noises, so sometimes it sits for a long time before I notice there is a problem.
Please can you make it make noises if there is a problem loading?

**Comment by KarlZeilhofer** [comment]
highly related: https://github.com/prusa3d/MM-control-01/issues/46

**Comment by gudnimg** [comment]
Adding this to 3.13 Milestone.

**Comment by gudnimg** [comment]
Closing as this is now resolved with FW 3.13.0 and MMU FW 3.0.0 :)

When sound is enabled, the printer now beeps when there is an error screen.
