### ISSUE TITLE
3.4.1 temperature change

### ISSUE THREAD

**Issue by Builderdad** [prusa3d/Prusa-Firmware#1267]
3.4.1 firmware during temperature change from higher to lower temps drop 10 degrees below desired target before attempting to recover.
Example when moving from 215 to 205 temperature will drop to 195 before attempting to raise back to 205. If fan is on it can take a full minute to recover causing skips.

**Comment by Panayiotis-git** [comment]
I've checked the scenario you describe on 3.4.1 and the temperature has dropped to 203 before return and stay at 205.

Have you run the PID calibration on the hot-end?

**Comment by Builderdad** [comment]
Yes I have PID tuned. It only does it during a printing condition and not with manually adjusting temps. Testing manually I get the same result as you stated.
The scenario that it occurs is during a print, using latest Version of SLIC3R, first layer set to 215/60 no fan. After first layer completed settings change to 205/60 with cooling fan. Temperature drops to 195/196 very rapidly, almost as if heater was turned off. It then tries to climb back to target of 205 but struggle due to cooling fan.

**Comment by Panayiotis-git** [comment]
I suggest to try the PID calibration with fan on and see if it changes anything.

**Comment by Builderdad** [comment]
I have PID tuned with fan at 100%. It has had no effect on the problem.
I did try and run a print that changes temperature on layer 2 and brings
fan on layer 3. Temperature change worked without fan. As soon as fan came
on I loose 10° and struggle to recover.

**Comment by Panayiotis-git** [comment]
Have you tried the [e3d silicon socks](https://e3d-online.com/v6-sock-3pack) ?
