### ISSUE TITLE
White Prusa filament triggers Filament sensor to much on 3.4.1

### ISSUE THREAD

**Issue by pmaartense** [prusa3d/Prusa-Firmware#1271]
When using the WHITE Prusa PLA filament I get many filament sensor triggers on the above firmware
other colors don't trigger  the false negative.

I have to disable the sensor for this filament to make prints work.

**Comment by inquisitiveKangaroo** [comment]
Hi,
Thank you for report. The optical sensor receives various inputs from filaments with different refraction properties and every sensor is very different from another. We are trying to optimize the range which is valid for majority of materials and sensors, however, each optical sensor is really sencitive to any contamination. In future we will probably solve this by something like 'F.I.N.D.A.' sensor or any better option.
