### ISSUE TITLE
MMU2 Single Mode Load extruder to purge previous color

### ISSUE THREAD

**Issue by TimothyGold** [prusa3d/Prusa-Firmware#1273]
I know that that there have been a number of other issues that have been reported specific to MMU2 Single mode issues.. Some are listed below.

1. Octoprint not recognizing T? and asking to select the extruder number before printing.
2. Confusion about the load features and what they do.

I have found another issue that I think is primarily a combo of the 2 above.  If I do get the command to pick an active extruder  which sometimes works and sometimes does not and the extuder had another color in it previously, the purge lines in Single Mode Slicre is not adequate enough to get the color changed and will usually start the print with the previous color.  I have messed with the custom gcode for the purge but have not come up with a good enough solution to get the filament loaded and purged.  I think at some level I would like to second the requests that have been made to give us more control of "Loading the Extruder" independent of the "Load MMU".  In theory the gcode that is applied should work but I think in a normal color change in a regular multi material print the purge block takes up the rest of what is normally needed to clear the color.  This is not done in the current single mode color change.  More control is greatly needed......

**Comment by inquisitiveKangaroo** [comment]
Solved in 3.5.0 - RC1 by 'Load to nozzle' feature.)
