### ISSUE TITLE
M913 Not printing running currents

### ISSUE THREAD

**Issue by knoopx** [prusa3d/Prusa-Firmware#1277]
`tmc2130_print_currents` method is commented out

**Comment by PavelSindler** [comment]
These gcodes were used for our debugging/development purposes. We will change these gcodes little bit to follow standard. My collegue @XPila will look on it. Thank you for letting us know.

**Comment by PavelSindler** [comment]
Standard M907 gcode can be now used for setting motor currents on MK3.
Non-standard obsolete gcodes M910 - M918 have been disabled. However these gcodes can be still used by  uncommenting line  #ifdef TMC2130_SERVICE_CODES_M910_M918 in Configuration_prusa.h and rebuilding. M913 lines were uncommented.
Check these pull requests:

https://github.com/prusa3d/Prusa-Firmware/pull/1305
https://github.com/prusa3d/Prusa-Firmware/pull/1320

**Comment by vertigo235** [comment]
Are the M907 settings stored in EEPROM?  Is there a way to recover the currently set current?  If I restart my printer do the firmware default currents restore?

**Comment by Shootquinn** [comment]
> Standard M907 gcode can be now used for setting motor currents on MK3.
> Non-standard obsolete gcodes M910 - M918 have been disabled. However these gcodes can be still used by uncommenting line #ifdef TMC2130_SERVICE_CODES_M910_M918 in Configuration_prusa.h and rebuilding. M913 lines were uncommented.
> Check these pull requests:
> 
> #1305
> #1320

With M912 disabled, the community needs to know if M907 can be used in the same way as it is for the Mk2, or if this is still a scale factor from 0 - 62 (as current is set in Mk3 firmeware). Also, since the Mk2 can output higher currents from the A4982 than the Mk3's TMC2130 is capable of, a reasonable range of values for M907 should be specified.
