### ISSUE TITLE
(3.4.2) XYZ calibration now fails

### ISSUE THREAD

**Issue by Pathogenius** [prusa3d/Prusa-Firmware#1282]
3.3.1-845 works fine, I upgrade directly to 3.4.2 release, XYZ calibration fails. I revert to 331, calibration completes.

**Comment by Crunch69** [comment]
Does it fail on the second position?  That is where mine fails 1 out of 6 tries

**Comment by Pathogenius** [comment]
I'm not sure what you mean by 'second position'. If I remember correctly, it fails at the end of the 9-point ordeal, before it asks to put the sheet on. I'll have to double check.

**Comment by Pathogenius** [comment]
I adjusted Y-axis mechanics, due to noisy bearings, then using 331-845, got an XY skew of 0.07, then upgraded to 342, this time it passed all tested. Interestingly, even though nothing was changed mechanically, the new firmware reports a much higher skew of 0.31, nearly 300% worse. Over and out! :-)
