### ISSUE TITLE
Enable timeout on the "New version available, please update" dialog!

### ISSUE THREAD

**Issue by Patronics** [prusa3d/Prusa-Firmware#1284]
It is very frustrating to start a print in octoprint, expecting it to run overnight, just to realize in the morning that it hasn't started at all just because it was waiting for me to acknowledge the notification about the new update! 

It'd be a much better user experience if that alert automatically dismissed itself if the user doesn't interact after a certain amount of time (perhaps 5 minutes?) 

That way you don't get multi-hour prints you expect to run while you're doing something else that end up never starting until you expect them to be done

**Comment by haarp** [comment]
You can probably avoid this entirely by throwing out the M115 command from the start g-code.

**Comment by michalxfanta** [comment]
In firmware 3.8.0 we implemented a timeout for this dialog.
