### ISSUE TITLE
3.4.1 Hotend crashes into bed when going through mesh calibration at the start of a print

### ISSUE THREAD

**Issue by Crunch69** [prusa3d/Prusa-Firmware#1285]
3.4.1 Hotend crashes into bed when going through mesh calibration at the start of a print in octoprint.  The only way to sometimes stop it is to do a auto home from the calibration menu prior to starting the print

**Comment by inquisitiveKangaroo** [comment]
Hi,
have you tried to move your pinda probe slightly lower? 
Is it possible to share the gcode and a video of this behaviour? (every single detail might be important) .)

**Comment by Crunch69** [comment]
Dont have to move the PINDA only have to change to older firmware and problem goes away

**Comment by FabianSchwartau** [comment]
Same problem here. Cancleded a job using octoprint while he was calibrating. Started the job again after a couple of seconds and he crashed into the bed. After that he touched the bed while doing the wizard. Moving the pinda probe one quarter turn down solved the problem for me.

**Comment by 3d-gussner** [comment]
@Crunch69 Is this still an issue? If it has been fixed in a newer firmware version, please close this issue.
[stale]

**Comment by JohnnyDeer** [comment]
I'm closing this issue as stale, thanks for understanding.
