### ISSUE TITLE
FW 3.4.1 appears to be slower on boot and slower menu operation almost like the CPU is maxed out.

### ISSUE THREAD

**Issue by Crunch69** [prusa3d/Prusa-Firmware#1288]
FW 3.4.1 appears to be slower on boot and slower menu operation almost like the CPU is maxed out.  Also when using Octoprint there are command execution delays that did not exist in prior releases. 
I have re flashed the firmware a couple of times thinking it may have been corrupted and there were no changes

**Comment by inquisitiveKangaroo** [comment]
Hi,
thank you for your report. I have not met such behaviour after flashing to fw3.4.1 but I noticed a longer boot time when flashing fw3.2.1 on which the language packages were added. However, if you update your firmware regularly, there should not be any significant difference. Nothing with high CPU demant was added. 
In case you find out more clues we would be greatful if you let us know.)
Have a nice printing day.
