### ISSUE TITLE
Running 3.0.12-RC2 cannot load filament (motor running backwards)

### ISSUE THREAD

**Issue by EasyAsABC123** [prusa3d/Prusa-Firmware#129]
This was fine on firmware file that came with printer

**Comment by EasyAsABC123** [comment]
Even stranger it only happens for filament 1 and filament 3, filament 2 and filament 4 work (i don't have a multi-filament printer...and there is the issue wrong firmware for my printer...i'm "smart"

**Comment by matthova** [comment]
Having the same issue with 3.1.0 RC-1
