### ISSUE TITLE
Z Direction 

### ISSUE THREAD

**Issue by Lino77** [prusa3d/Prusa-Firmware#1296]
where can I invert the "Z direction" for Bed calibration
in Configuration_prusa #define INVERT_Z_DIR 1 to 0 changes the direction, for print and everything else,
but not for the bed calibration

**Comment by 3d-gussner** [comment]
Checkout https://github.com/prusa3d/Prusa-Firmware/pull/1263 ...guess it is for your zaribo cube style printer

**Comment by Lino77** [comment]
thanks , currently I have reversed the plug because I did not find it in the firmware as it should do.
