### ISSUE TITLE
Hotend crashes into bed when using print/G80 while the printer is in "Z live adjust" mode

### ISSUE THREAD

**Issue by Auge103** [prusa3d/Prusa-Firmware#1298]
**What:** 
- MK3
- Latest firmware to this date

**Issue:**
This occured to me when printing calibration squares:
When starting the print while the printer still shows the "Z live adjust" menu on the LCD, the hotend will crash into the bed at initial bed leveling before the print.
It seems that the PINDA probe and crash detection is somehow disabled in this mode - the PINDA will disable its LED, but the printhead never stops, crashes and continues.
The results are dramatic:  The hotend will crash into the bed, stamping a nice hole into the PEI surface, the Z motors will continue to push the X-carriage down until the whole carriage just breaks.
This issue does NOT occur when waiting for the live adjust menu to vanish or by pressing the button to close it right before starting G80 / a print again.

**Steps to reproduce:**
1. Connect the MK3 to any PC / Octoprint and switch everything on
2. Start a really small print (anything) via PC / Octoprint and let it finish. No issues so far.
3. Open Z live adjust on the LCD like you would do after a calibration print, don't change anything (or do, doesn't matter)
4. DON'T close the "Z live adjust" menu - just start the same print again via PC / Octoprint.
5. The printer should immediately start the initial bed leveling process while the Z adjust menu is still open - the hotend should crash right into the printbed at the very first calibration point, never stopping the Z motors. Not resetting the printer at this point will completely destroy the printbed, PEI sheet, X-carriage and printhead in a worst case scenario.

Closing the Z adjust menu before starting the print will enable the PINDA probe and crash detection again, thus never crashing.

For me, it just stamped two nice holes into the PEI sheet (not so nice at all) and I had to fix the X-carriage twice before finding the cause. For not-so-quick users, this could potentially destroy the whole printer.

**Thus, a world of warning if you want to replicate this: Have your finger on the reset button and be very quick!**

Possible duplicates:
https://github.com/prusa3d/Prusa-Firmware/issues/1248
https://github.com/prusa3d/Prusa-Firmware/issues/1285

**Comment by haarp** [comment]
You're right, this does seem similar to my #1419. And the other possible duplicates indicate that this is not uncommon. Prusa, any updates on this?

**Comment by 3d-gussner** [comment]
@Auge103 Is this still an issue? If it has been fixed in a newer firmware version, please close this issue.
[stale]

**Comment by JohnnyDeer** [comment]
I'm closing this issue as stale, thanks for understanding.
