### ISSUE TITLE
Feed Rate varies with Extruder Retraction Speed

### ISSUE THREAD

**Issue by AbeFM** [prusa3d/Prusa-Firmware#1300]
Version
1.41.1b (MMU) (And later)

Operating system type + version
win10x64

Behavior
Printing speed sets itself from 100% to Extruder Retraction Speed. Each time a filament change finishes, the printing speed sets itself to 35.
I changed the retraction speeds to (Ext1,2,3...) 36,37,38,39,33 respectively.
I came in and saw printer at 35%, overrode it to 100.
F2: 36%
F3: 37%
F4: ..
and the speed would be 35/36/37/38 as it progressed through the channels.

It seems it's grabbing the Retraction Speed from each Ext(n-1) and setting that as the speed when it is loading the filament.

I think that's a bug.

Is this a new feature request?
No

STL/Config (.ZIP) where problem occurs
Upload a zipped copy of an STL and your config (File -> Export Config)

SpeedsChanging.zip

prusa3d/Slic3r#1313

**Comment by rtyr** [comment]
This can be closed, it is not firmware related.

In older Slic3rPE versions, 35% speed override was used for flexible filaments by design. It is completely reworked in current PrusaSlicer version (speed is limited by maximum volumetric speed).
