### ISSUE TITLE
#define FANCHECK

### ISSUE THREAD

**Issue by swmarsh** [prusa3d/Prusa-Firmware#1311]
Having some issues with the #define FANCHECK.  I disable it as follows //#define FANCHECK which gives me the option to tell the printer if the hot end fan is spinning or the print fan is spinning like in the MK2s firmware. Only one problem.  It all work correctly just my heat bed starts to heat for no reason. I can not find anyway to disable the bed from heating when I disable this.  I have a 5v pwm noctua fan and a 2 wire blower for a print fan due to not being able to source a 3 wire in the USA.   I can complete the selftest this way but the beds slowly heats.  Any clues??

**Comment by 3d-gussner** [comment]
@swmarsh  Long time no update here. Can you please close this issue?

**Comment by Prusa-Support** [comment]
Hello! Sorry for intervening so late on this issue. Is the issue still actual in this specific case where you comment out the define FANCHECK? At this time, you can disable the fan check via printer menu: >menu >settings >fans check [on/off]. Of course disabling it at your risk and peril, overheating or simply heat creep can be an issue. 

Closing the issue for now given this info, but do not hesitate to let me know in case of more aspects to review, directly with me info@prusa3d.com mentioning me. 

Alessandro Pantaleo
Prusa Research
