### ISSUE TITLE
3.4.1 e-correct will not save in printer settings. If the printer is shut down the setting changes to OFF

### ISSUE THREAD

**Issue by Crunch69** [prusa3d/Prusa-Firmware#1317]
3.4.1 e-correct will not save in printer settings. If the printer is shut down the setting changes to OFF

**Comment by inquisitiveKangaroo** [comment]
Hey Crunch69,
Thank you for the report, we appriciate it. We'll try to fix it asap.

**Comment by 3d-gussner** [comment]
@Crunch69 Is this still an issue? If it has been fixed in a newer firmware version, please close this issue.
[stale]

**Comment by JohnnyDeer** [comment]
I'm closing this issue as stale, thanks for understanding.
