### ISSUE TITLE
MMU2 on mk2.5 with 3.4.2 does not load first filament with multicolor prints

### ISSUE THREAD

**Issue by langph** [prusa3d/Prusa-Firmware#1322]
I built the MMU2, calibrated it using the "secret" menu :-). When I print in single color mode, it alsks which extruder, the first filament does get loaded, print starts normally. When in multi color mode, the first filament does not load, cannot make it to load either. 

Edit: multi color printing works if I use the menu of the printer to load filaments, but not when I use the buttons on the MMU

Edit: what happens too when a print starts that the selector is at filament 1 and filament 2 is pushed out. This happens regularly but not always.

**Comment by JohnnyDeer** [comment]
Hi, this problematics is solved by MMU2S, I'm closing this issue.
