### ISSUE TITLE
Case Sensitivity for Commands and Filename 

### ISSUE THREAD

**Issue by AustinSaintAubin** [prusa3d/Prusa-Firmware#1325]
I am having an issue with the Prusa Firmware.
When sending the print file command the I have noticed that the firmware is case sensitive.
More details here: https://github.com/luc-github/ESP3D/issues/273

### FAIL 
```
M23 PRINT~1.GCO
M24
```

### WORKS
```
M23 test~1.gco
M24
```

-------------------

This is also odd because the file list is output in UPPERCASE, but requires lowercase input.
```
M20

Begin file list
/STOCK/MK3_PL~1.GCO 319820
/STOCK/MK3_PL~2.GCO 23525291
/STOCK/MK3_PL~3.GCO 10256022
/STOCK/MK3_PL~4.GCO 1163600
/STOCK/MK3_PL~5.GCO 3771043
/STOCK/MK3_PR~1.GCO 409041
/STOCK/MK3_P~33.GCO 17819561
/STOCK/MK3_P~38.GCO 224162
/STOCK/MK3_P~42.GCO 25074366
/STOCK/MK3_P~46.GCO 5966830
/STOCK/MK3_P~50.GCO 9991779
/STOCK/MK3_P~54.GCO 839525
/STOCK/MK3_P~58.GCO 21788066
/STOCK/MK3_P~62.GCO 2206259
/STOCK/MK3_P~66.GCO 3552905
/STOCK/MK3_P~70.GCO 7586128
PRINT~1.GCO 12739152
/BENCHM~1/3DBENC~1.GCO 3670093
/BENCHM~1/TEST_Y~1.GCO 1247554
/BENCHM~1/RIPPLE~1.GCO 1064312
/CONTAI~1/SD_HOL~1.GCO 130043
/CONTAI~1/SD_ADA~1.GCO 1132984
/CONTAI~1/SOAP_H~1.GCO 5925818
/CONTAI~1/MASTER~1/MASTER~1.GCO 16236540
/CONTAI~1/MASTER~1/MASTER~2.GCO 9633713
/PARTS-~1/HEATED~1/REPRIN~1.GCO 1308244
/PARTS-~1/HEATED~1/PRUSA_~1.GCO 1666128
End file list
```

**Comment by rbm78bln** [comment]
Hey guys!

Any news on this issue?

I was trying with the current firmware 3.10.0-4481 on my MK3S and was also stumbling on this issue: M20 returns uppercase filesnames and M23, M30, and M32 work only with lowercase filenames.

To me it actually doesn't matter what IS the case, yet all commands should make use of the same case...

**Comment by gudnimg** [comment]
It should be easy to convert the inputs for M23, M30, and M32 to lower case, thus any case would be supported but then there is no way to differeniate between two files with the same name but with different cases.

Regarding M20, I would expect to see the actual case on the file name in the same way as it is stored into memory. Whether it contains a capital letter, all upper case or all lower case. But if we do this I suppose we should maybe also make M23, M30 and M32 case sensitive? ( that is, the user must type the name exactly as listed by M20)

But converting anything the user inputs into lower case will atleast improve the situation? Anyone have thoughts on this?
