### ISSUE TITLE
Default TMC2130 wave is calculated incorrectly.

### ISSUE THREAD

**Issue by Beherith** [prusa3d/Prusa-Firmware#1326]
https://github.com/prusa3d/Prusa-Firmware/blob/702237388591356ab7901cece9cb7107a11602ff/Firmware/tmc2130.cpp#L875

The +0.5 is incorrect, as per page 32 of the tmc2130 datasheet.

**Comment by Beherith** [comment]
![image](https://user-images.githubusercontent.com/109391/48299967-38635100-e4d5-11e8-9d24-fa6532001778.png)

**Comment by AnHardt** [comment]
The +0.5 is needed **because** of the datasheet.

In the datasheet the rounding is explicitly determined. Because a cast from float to int works different, just cutting away the fractional part, the addition of 0.5f is needed.

**Comment by Beherith** [comment]
I see, my apologies. Thanks for clarifying!
