### ISSUE TITLE
M220 in gcode causes print to fail

### ISSUE THREAD

**Issue by oderbang** [prusa3d/Prusa-Firmware#1328]
When you add M220 in the gcode it causes the printer to fail.
I wanted to add M220 S100 before first layer and then M220 S150 after for the rest of the print in order to slow down the first layer.

i know there are other ways of achieving this in slicer but i wanted to use M220 in gcode file and it does not work.

Tried on multiple gcode files. 

Issue is on the MK3

**Comment by inquisitiveKangaroo** [comment]
Hi,
thank you for report. May I ask on which firmware you've been printing those gcodes? I tried it on multiple firmware versions and it worked in all cases. I would like to find out under which circumstances this issue occurs so please let us know if you noticed anything.

**Comment by oderbang** [comment]
Really sorry that I have not been able to reply.. I have been very busy with a new born child and work!

When i am home tonight I will get the firmware version (I believe it is 1 version out of date)
I can also send you an example of the gcode files that fail

Hope this will help

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by 3d-gussner** [comment]
Closing
