### ISSUE TITLE
3.5.0-RC1 Firmware for Prusa i3 MK3 and MK2.5 MMU2 Single Mode Gcode always heates to PLA Temps

### ISSUE THREAD

**Issue by TimothyGold** [prusa3d/Prusa-Firmware#1339]
I just tried the new Gcode in the new beta and this time printing from Octoprint the T codes seem to allow a Filament to be picked for the single mode print but when selected after slicing for PET the extruder and the bed heated for PLA temps and never did change to the actual sliced temps.  Had to revert back to the old way to print with Pet.

**Comment by PavelSindler** [comment]
Thank you for reporting this. Can you please provide gcode file?

**Comment by TimothyGold** [comment]
The gcode has already been overwritten because I used the send to printer option to octoprint. The starting gcode recommended in the beta release notes are what I used when slicing though.

**Comment by PavelSindler** [comment]
Starting gcode which is shown in release notes is just example how to use Tx and Tc codes. There are PLA temperatures in this starting gcode sequence. If you copy this from release notes and replace start sequence in your slicer PET profile or directly in your PET gcode file it will cause the issue.

**Comment by TimothyGold** [comment]
I apologize I just copied and pasted without double checking this part... I just assumed that it was a direct Custom G-Code Start which included - 
M104 S[first_layer_temperature] ; set extruder temp
M140 S[first_layer_bed_temperature] ; set bed temp
M190 S[first_layer_bed_temperature] ; wait for bed temp
M109 S[first_layer_temperature] ; wait for extruder temp

I will update the script with this and keep using this... 

Thanks.
