### ISSUE TITLE
Lots of magic numbers in `pat9125.c`

### ISSUE THREAD

**Issue by AnHardt** [prusa3d/Prusa-Firmware#1343]
There are lots of magic numbers in `pat9125.c`.
I'd love to understand what's going on.
The official [datasheet](http://www.pixart.com/upload/PAT9125EL_GDS_V1.2_31052017_20171011150843.pdf) is not very helpful about the registers and their content.

>     // Now continues the magic sequence from the PAT912EL Application Note: Firmware Guides for Tracking Optimization.

Maybe that paper can enlighten me. Sadly i can't find it.

Can anyone publish a link or the paper here? Please.

**Comment by trevjonez** [comment]
there is some further info if you dig through this: https://os.mbed.com/teams/PixArt/code/9125_referenceCode/

and here https://os.mbed.com/search/?q=PAT9125

**Comment by AnHardt** [comment]
Come on.
If `PAT9125_NEW_INIT` isn't poking purely random values to random registers someone had access to much deeper knowledge. Where does it come from?

**Comment by trevjonez** [comment]
I too would like to know where that info came from. I was just trying to add notes of further information I had found. It certainly wasn't everything 👍

**Comment by hazcoper** [comment]
A couple of years later, but I would be very interested in that info as well
