### ISSUE TITLE
Cold loads/unloads of the MMU2 should be permitted.  M302 is not properly implemented.

### ISSUE THREAD

**Issue by domesticatedviking** [prusa3d/Prusa-Firmware#1346]
It makes no sense to be forced to preheat the extruder in order to load or unload filament in the MMU2.   If M302 were properly implemented on the printer firmware, advanced users would be able to choose to disable cold extrusion prevention.

**Comment by PavelSindler** [comment]
Preheating extruder is not required when loading. 
When unloading nozzle must be preheated as filament can be in nozzle. It is the same with eject (eject works with filament loaded in nozzle. In this case it does unload and then eject). Loading to nozzle function also requires preheat of course. 
Can you describe scenario where cold unload/load should be permitted and currently isn't?

**Comment by domesticatedviking** [comment]
For some reason I can't replicate this issue today so I'm marking this closed.  I still would like a working  M302 at some point.   Thanks Pavel.
