### ISSUE TITLE
MMU2: Color change and filament ejection before first purge line is complete and during print

### ISSUE THREAD

**Issue by Petclaud** [prusa3d/Prusa-Firmware#1361]
Firmware:     3.5.0.
MMU2 FW:  1.0.2
Slic3r:           1.14.2
Printer:          MK3

The issue I am experiencing is as follows:

- Slice a two color model with Slic3r and sent a the GCode through Octoprint to the printer
- printer loads the right 1st filament and makes just +/-2 cm of the purge line 
- the the printer head moves up and to the far right side and does a 'color change'
- unloads the filament from the extruder head into the MMU2
- MMU2 selector moves and then ejects the filament some 15 cm from the MMU2 with a message on the screen to remove the filament
- after pulling back the filament manually, need to press the knob on the MK3
- filament loads to the extruder, ejects some filament
- printer asks for 'correct color change' and need to press the knob
- printer heats the bed up (apparently it cools down during this exercise), extruder moves back to where it stopped the purge line, moves down and finishes the purge line and starts the print

Also during the print, sometime suddenly the 'change filament' sequence and ejection of filament occurs while no buttons are pressed.

Very weird....

**Comment by Mustrum-Ridcully** [comment]
This might be linked I am seeing this with
Firmware: 3.5.0.
Slic3r: 1.14.2
Printer: MK3
The new firm ware has changed the way the wipe path is working in 2 ways the path now starts wiping at the triangle with the! in it and it no longer has the tiny start blob now the start blob is showing at the start of the perimeter path line this can cause a problem where the perimeter formes the outside of the brim

found this doing new coupons from https://shop.prusa3d.com/forum/assembl ... x-s25.html
now that I have both types of spring steel sheet i want solid notebook numbers switching back and forth with different sorts of plastic

**Comment by Petclaud** [comment]
It proved that this phenomenon was caused by false filament sensor triggers. I used Filamentum's Noble Blue PLA.

The reason why I did not suspected the filament sensor before, is twofold:
- 1st: did not had any false triggers with this filament before
- 2nd and most important: I could reproduce 3x in a row the 'filament change' during purging at exactly the same point. 

Anyway, something learned
