### ISSUE TITLE
filament loading issue on 3.5 

### ISSUE THREAD

**Issue by cnlson** [prusa3d/Prusa-Firmware#1366]
Flashed the newest 3.5 and when i select load filament in the menu it will eject filament slowly then goes to the front right and requests to switch filament, then finally loads. 

this has been repeatable for me today several times event after a reset.

**Comment by bar-bog** [comment]
I have seen the same problem today with 3.5 on mk3.
Additionally it looks like if the printer needs to push the filament few times after inserting it again (by pressing no in context menu few times) after finally answering yes it starts to extrude the fillament uncontrollably.

**Comment by 3d-gussner** [comment]
Closing as outdated
