### ISSUE TITLE
M107 causes "Print fan error" on FW 3.5.0

### ISSUE THREAD

**Issue by NeilW999** [prusa3d/Prusa-Firmware#1367]
If using Slice PE 1.41.2 with Prusa flexfill settings it will enable the fan with an M106 usually at about layer height 2.20. At the end of that layer ( rightly or wrongly ) it issues a disable fan command M107. The disable fan command always results in a "print fan error" being reported by the firmware.  This is on a MK3 with all latest drivers and firmware installed.

I would also add that I think the handling of the error appears wrong. The firmware turns off the heater for the extruder even though the extruder fan is still on. Eventually extrusion stops as the hotend cools. Print would have worked if the hotend had been left alone.

If the gcode is edited to remove the disable fan, the print proceeds without error.

This could of course be a problem with Slice PE but I don't know enough about Gcode.

**Comment by PavelSindler** [comment]
Thank you for reporting. Can you provide gcode file?
I don't understand what do you mean by wrong handling of error. Can you explain?
In case that fan is not spinning (signal from fan sensor seems like it is not spinning) we turn of nozzle, pause print (pause works with SD card printing and with Octoprint) but keep bed heated because we want possibility to resume print after user cleans fan.

**Comment by NeilW999** [comment]
When the print fan error occurred the printer did not stop printing, it did not pause. What happened was that the hot end got turned off and the printer continued to try printing. I tried this on both Pronteface and from SD card. Just to be clear, I am talking about a "print fan error" and not an "extruder fan error".

Maybe the fact it did not pause on error should be a new issue? When you can reproduce the fault maybe you will agree.

**Comment by NeilW999** [comment]
I'm afraid I can't get to a computer for a few days. However it should be very simple to reproduce the problem.

First create a rectangular block 100mm long, 20mm wide and 4mm high. Slice it with standard settings of "mk3 0.2(fast)", "Prusa flexfill 98A", "20% infill"
Then edit the gcode with your favourite editor. Search for the word "fan". If my memory serves me right there will only be four  occurrences that you should find.
At the start will be a disable fan M107.
At approx layer 2.20 will be an enable fan M106.
At the end of that layer will be a disable fan M107.
At the end of the file will be a disable fan M107.

Try printing the file it should cause the problem if the disable fan is present at layer 2.20. If the disable fan is commented out then I don't get an error.

Note 1: Being new to this I finally realised I could test and reproduce the problem with no filament loaded. I wasted a heap of flexfill thinking it was something I had done wrong.

Note 2: When I realised I didn't need filament I could print in thin air. So to very quickly reproduce the problem simply edit out most of the layers. I would leave from the start of the file to the first perimeter being drawn in. Then cut out all the gcode after that until the comment for layer 2.20 or whatever layer had the enable fan command in. Print that and it only takes a minute to reproduce the error.

**Comment by NeilW999** [comment]
Of course I probably could have saved a lot of typing by editing any model. Just insert an enable fan at the start of the layer and a disable fan at the end of the layer. If my theory is right then as long as the fan is enabled and then later during the print it is disabled it should cause the fault after a another minute or so of printing.

**Comment by donicrosby** [comment]
I'm also having this issue with my MK3 when using the PLA settings. I'm using Slic3r PE 1.40.1 win64. I can supply two gcode files that seemingly cause this issue.

**Comment by NeilW999** [comment]
Having returned to the printer after a week I can no longer reproduce the problem. I am sorry but I can only conclude that I have some weird hardware problem at the moment. I have now tried "wiggling" all the cables and still can't upset the hardware. I am going to keep on pursuing this in case I have missed something. I guess however this issue needs closing.

For information I have attached the gcode which shows the fan going on and off during layer 2.4. This was sliced with standard Prusa settings as above. I guess this was meant to happen, but it just coincendentally occured exactly where I have a "hardware" fault.

Attached is zip file with STL and 3 copies of the gcode.
"Rubber ..."  is normal output from Prusa.
"Verbose Rubber ..." has verbose gcode turned on.
"Cut " has from the 1st perimeter to layer 2.4 cut out 

[Fan error.zip](https://github.com/prusa3d/Prusa-Firmware/files/2647518/Fan.error.zip)

**Comment by NeilW999** [comment]
Don't close it yet its back!

**Comment by NeilW999** [comment]
Here is my recipe that always causes me a "Print Fan Error". To cut a long story short I had been having trouble printing Flexfill and I hadn't realised I had  changed the settings in Slicr, I had thought it was down to print speed or the volumetric extrusion. However I eventually found my printing problem was a slight misalignment in the Bondtech gears.  I am however still left with the "Fan Error" if I do slow down the print.

Here is a screenshot of my slicer settings:

![slicersettings](https://user-images.githubusercontent.com/45403149/49580226-4e362b80-f946-11e8-9828-5dfc974e8592.PNG)

So the only things changed are:
Max print speed is 15mm/s   ( 20mm/s does not fail, 10mm/s does fail )
All the Speeds for print moves have been set to 0
Output options have been set to verbose ( but that is not necessary to cause the fault)

Attached is the STL and GCODE I use to create the problem. There is also a version of the Gcode with all the later M107 disable fans commented out, this prints without error.

Also note please do not  try to print the gcode with filament loaded, this particular STL has bits hanging in free space.
[Fan error.zip](https://github.com/prusa3d/Prusa-Firmware/files/2653239/Fan.error.zip)

**Comment by jdn-za** [comment]
Also having this issue, only with newer firmware though....

**Comment by 3d-gussner** [comment]
@NeilW999 @jdn-za Is this still an issue? If it has been fixed in a newer firmware version, please close this issue.
[stale]

**Comment by NeilW999** [comment]
Can't reproduce on latest firmware (3.9.0) therefore closing
