### ISSUE TITLE
Nozzle temperature goes down and printer pause waiting the temperature raise again

### ISSUE THREAD

**Issue by bionno** [prusa3d/Prusa-Firmware#1368]
Hello, 

sometimes the printer pause printing because the nozzle temperature goes under the settings i've done (for instance i set the PLA to 206 Celsius and sometimes goes to 195 .. pause .. heating again ... when reaches 206 resume with little blob of filament) .

i've used the other 12V +/- on the Power Supply , connected to a DC 5V converter to supply the Raspberry with Octopi and 4 USB led stick .

Yesterday i've done the PID calibration and today i'll retry some print , maybe the problem was the PID calibration ... maybe the power consuming of Raspberry (i hope not because is only 3A/ 5V )  ... or maybe the Formware ..

**Comment by PavelSindler** [comment]
Which printer version and firmware version do you have?

**Comment by bionno** [comment]
> Which printer version and firmware version do you have?

MK2.5 with the last stable 3.5

**Comment by bionno** [comment]
Anyone tried out  this issue ?

**Comment by bionno** [comment]
TOday the printer give me the error " PREHEAT ERROR" ...  do you think it is a power supply problem because the DC converter and Raspberry PI3 with led light connected directly ?

Now i ve removed 2 led light from the Raspberry USB , hope this was the problem ..

**Comment by bionno** [comment]
MAybe this problem is related with this post "

https://github.com/prusa3d/Prusa-Firmware/issues/1362

**Comment by joseph-greiner** [comment]
I can confirm the original issue is happening for me. Firmware 3.5.0-1749, MKIII. No raspberry Pi, no accessories except the E3D silicone sock. Sometimes, not always, when the nozzle temp drops below the set temperature, when doing solid infill on my particular print, the printer will pause. Set temp is 250C, when the nozzle temp drops the print pauses and "heating" is displayed on the screen. I have never watched the temps before so I don't know if the temperature variation is new to this firmware. But the pausing definitely is. I am using the latest software package as well, Slic3r 1.41.2 win64.

Here are a couple videos of it pausing.
Pauses at the beginning and towards the end, shows the temperature screen.
https://www.youtube.com/watch?v=JKRrIBc07ME (2min)
Here is the main screen:
https://www.youtube.com/watch?v=SPiu-Dl-afs (20 sec)

--Quick edit, after reading about some of the other issues and testing a couple ideas, this behavior completely stops when the filament sensor is disabled, I was printing with black PETG. I forgot to disable it after printing with some blue PLA. So it seems that it is not a heating or  issue, just the filament sensor.

**Comment by ThomasBLarsen** [comment]
I have the same problem. Nozzle temperature drops, and the printer sometimes pauses to heat the nozzle. Using Firmware 3.5.1

![image](https://user-images.githubusercontent.com/3322745/51969551-fc58e000-2474-11e9-9bc2-e3f688f2ced2.png)

**Comment by bionno** [comment]
@inquisitiveKangaroo has closed the referred issue (https://github.com/prusa3d/Prusa-Firmware/issues/1362) so the new firmware upgrade , available in a week , will resolve the issue .

Thanks.
