### ISSUE TITLE
When will S-Curve Acceleration and Junction Deviation be added to the firmware?

### ISSUE THREAD

**Issue by Crunch69** [prusa3d/Prusa-Firmware#1373]
When will S-Curve Acceleration and Junction Deviation be added to the firmware?

**Comment by JoschaMiddendorf** [comment]
Will this even be possible on an 8 bit Einsy board?

**Comment by vertigo235** [comment]
MK4 with 32bit board

**Comment by stahlfabrik** [comment]
Use marlin! It is possible on einsy today.

**Comment by vertigo235** [comment]
I would just love to see LA 1.5
