### ISSUE TITLE
3.5.0 e-correct x-correct y-correct will not save in printer settings. If the printer is shut down the setting changes to OFF 

### ISSUE THREAD

**Issue by Crunch69** [prusa3d/Prusa-Firmware#1374]
3.5.0 e-correct x-correct y-correct will not save in printer settings. If the printer is shut down the setting changes to OFF

**Comment by stahlfabrik** [comment]
Yup can confirm. Annoying  since 3.4.1 at least

**Comment by inquisitiveKangaroo** [comment]
3.4.1 e-correct will not save in printer settings. If the printer is shut down the setting changes to OFF #1317

**Comment by 3d-gussner** [comment]
@Crunch69 Is this still an issue? If it has been fixed in a newer firmware version, please close this issue.
[stale]

**Comment by JohnnyDeer** [comment]
I'm closing this issue as stale, thanks for understanding.
