### ISSUE TITLE
MMU2 / Slic3r / Mk2.5 - Wrong filament printed for several layers, no indication of this in Slic3r preview.

### ISSUE THREAD

**Issue by domesticatedviking** [prusa3d/Prusa-Firmware#1375]
Slic3r 1.41.1+linux64,  Ubuntu 18.04.1LTS 
Printer:  MK2.5, Firmware 3.5.0-rc1-1688, MMU2 firmware: 1.0.2-132

Filament #3 was selected for several several layers instead of filament #4.  No indication this would happen in Slic3r preview.

Zipped 3mf
[shield setup.zip](https://github.com/prusa3d/Prusa-Firmware/files/2635210/shield.setup.zip)

**Print setup (red lambda objects configured as support blockers)**
![image](https://user-images.githubusercontent.com/6627466/49318531-c2d41a80-f4ad-11e8-9a6a-8454cbbf3ab2.png)

**Model as sliced:**
(5 material print, filament 1 configured as soluble HIPS filament, soluble supports)
![image](https://user-images.githubusercontent.com/6627466/49318494-991af380-f4ad-11e8-9efe-fc5d946a84f2.png)

**Printed output:**
![error shield](https://user-images.githubusercontent.com/6627466/49318833-f95e6500-f4ae-11e8-9688-5a6fc762794f.jpg)

**Comment by inquisitiveKangaroo** [comment]
Hi, thank you for your report.
It seems like the red wasn't purged properly. Is it possible to retry to slice it in 1.41.2 and print it on fw 3.5.0 - 1749 and share the result. Or to share the stl? .)

**Comment by domesticatedviking** [comment]
This is not a purge issue.  The color was wrong for several layers, each of which had material changes.
