### ISSUE TITLE
Leveling Interpolation Error

### ISSUE THREAD

**Issue by rwensley** [prusa3d/Prusa-Firmware#1376]
A close examination of many returns by G81 shows that the interpolated values range from slightly non-linear to grossly non-linear.  As these values are used to adjust Z during printing an issue may arise.
Attached is a screenshot from excel of a G81 response and a graph showing the non-linearity.

![interpolated points](https://user-images.githubusercontent.com/15789791/49346630-e25c7600-f65a-11e8-943d-5b477be3f19b.PNG)

**Comment by rwensley** [comment]
Looking at the algorithms available in the existing source, both of these calculations have errors in them.

A simple linear interpolation would work fine here.
Given X0 - X6 are known positions as well as Y0 - Y6
and
Z0, Z3, Z6 are known for each Y row

Then solving for Z(i) = ((x(i) - X0)*((Z3-Z0)/(X3-X0))+Z0 for X(i) < X3
or
Z(i) = ((x(i) - X3)*((Z6-Z3)/(X6-X3)+Z3 for X(i) > X3

Solving for X1, X2, X4, X5 for Y0, Y3, Y6 first then solve for the remaining values in the Y direction.

I am not a programmer so this is a far as I can go. 
I hope this helps.

**Comment by rwensley** [comment]
Opps...Closed it by mistake.  This is a serious issues and needs attention. IMO

**Comment by rwensley** [comment]
Here are the results of using the proposed algorithm to calculate the interpolated values.
Blue is present algorithm Orange is propsed
![leveling](https://user-images.githubusercontent.com/15789791/49527724-2082b100-f878-11e8-8dea-47865c46d931.PNG)

**Comment by Pathogenius** [comment]
This is interesting to me because it can explain some otherwise inexplicable anomalies in my bed mesh leveling attempts, specifically large sections of poorly leveled areas appearing after entering mesh correction values. I had previously assumed this was caused by Pinda/magnet errorsm but this explanation seems to fit better.

**Comment by rwensley** [comment]
So here is some additional data from older versions of firmware and other users. This confirms the issue.
![matthias keil](https://user-images.githubusercontent.com/15789791/49553692-97db3380-f8be-11e8-97fa-1a6d4a7aa6c9.PNG)
![tony johnson](https://user-images.githubusercontent.com/15789791/49553696-9c075100-f8be-11e8-8ff8-c0c57e51e35f.PNG)

**Comment by rwensley** [comment]
I failed to take the thermal sag of the heated bed into account.  It seems that the interpolation should NOT be linear and is likely correct as is.
Closing this issue.
