### ISSUE TITLE
Error Compiling PRINTER_TYPE

### ISSUE THREAD

**Issue by Sjaakwortel** [prusa3d/Prusa-Firmware#1380]
Followed the instructions from the readme to compile marlin for mk2.5, compiling gives error : 

" exit status 1 'PRINTER_TYPE' was not declared in this scope" 
This is connected to M45, but i cant seem to solve this, tried different versions of the arduino enviroment.

**Comment by timmmccoy** [comment]
I was able to solve this by editing the Configuration_prusa.h from the Firmware folder _instead_ of copying over the version from the variants folder.

With a code diff tool you can compare the variant file you chose against the "default" Configuration_prusa.h and figure out which edits you need to make.

Hope this helps.

**Comment by 3d-gussner** [comment]
@Sjaakwortel Long time no update here. Can you please close this issue?
