### ISSUE TITLE
[Feature request] Add M118 command

### ISSUE THREAD

**Issue by NewbieYnet414** [prusa3d/Prusa-Firmware#1381]
Hello I'm creating this ticket because ticket #921 is still opened without any response from developers.
**Wanted feature**
M118 command implemented as in vanilla Marlin.

**Explanation**
Please can you implement M118 command used to instruct host/G-code sender about events handled by printer firmware like unpausing print job from printer. This feature is already implemented in vanilla Marlin and is pretty handy.

**Background story**
I'm running 3D printing service on dormitory as activity of civil association. We are printing non-stop so I set up Octoprint for managing filament usage, remote controlling but in first place for queuing print jobs because in first month of usage we used 4kg of filament. And we are loosing lots of time on loading jobs to Octoprint. So using print queue I can speed up loading jobs via M0/M1 after each job pause FW let someone clean heatbed and confirm that with rotary button and start next job. Problem is that job is paused twice first on printer FW and after that on Octoprint which could be resumed by sending M118 A1 action:resume to printer and echoing back //action:resume.

**Comment by johnbiggs** [comment]
That does sound helpful. I wonder if adding a button to the Pi and writing an octopi plugin to detect that button would be faster than waiting for the Devs?

**Comment by NewbieYnet414** [comment]
That is not solution but workaround in first place. And probably not easy to do because Octoprint is running on VPS because slicing on raspberry will be way too slow. Raspberry is used only for camera and socat tty bridge between raspi and Octoprint on VPS.

Also why should someone write (reinvent wheel with square shape that can ride only on catenary shaped road) plugin that does only one thing of many that can be done with M118 which is supported by Marlin, Repetier, Octoprint, Pronterface.

**Comment by johnbiggs** [comment]
I’m just sharing the reality of the situation. It’s probably faster for you to implement a workaround than wait for this. Additionally the command seems like it requires a lot of memory which the Devs have none left.

**Comment by NewbieYnet414** [comment]
Hello @inquisitiveKangaroo any update on implementing M118?

**Comment by NewbieYnet414** [comment]
Hello,

hopefully, you will add this in the next release after more than 6 months from first ticket opened.

```
case 118: //M118
  {

    bool hasE = false,
    hasA = false;
    uint8_t strchr_pos = 5;

    for (uint8_t i = 2; i--;) {
      if ((strchr_pointer[strchr_pos] == 'A' ||
          strchr_pointer[strchr_pos] == 'E') &&
        strchr_pointer[strchr_pos + 1] == '1') {
        if (strchr_pointer[strchr_pos] == 'A')
          hasA = true;
        if (strchr_pointer[strchr_pos] == 'E')
          hasE = true;
        strchr_pos += 2;
        while (strchr_pointer[strchr_pos] == ' ')
          ++strchr_pos;
      }
    }
    if (hasE)
      SERIAL_ECHO_START;
    if (hasA)
      SERIAL_ECHO("//");

    SERIAL_ECHOLN(strchr_pointer + strchr_pos);

  }

  break;
```

**Comment by RLF1962** [comment]
Any update on m118 command being added to MK3s firmware? This feature would be very handy and a great addition to be able to use action commands in octoprint. Please add!!!

**Comment by AndrewLuebke** [comment]
I'm interested in this too.  It could be useful as a serial loopback interface.  I'm thinking that if I send random data as fast as I can and read it back then I can tune the serial interface speed or look for errors from a bad cable, etc.

**Comment by Jarves020** [comment]
Any Update on m118 integration in future Firmware releases?
Would help to trigger some Actions with Octoprint....
