### ISSUE TITLE
3.5.0  MK3 Printer won't stop after pause is press on the machine (temperature stop heating)

### ISSUE THREAD

**Issue by konghaw** [prusa3d/Prusa-Firmware#1382]
I pressed on the pause from the machine, nozzle temperature & bed temperature dropping but the print won't stop and keep continue with the movement. Re-press on pause results is the same. Next i proceed with stop print not fail, printer won't take the command. I am force to power off the machine with plugging the power source.

**Comment by zoltanf** [comment]
I had this happened to me yesterday. Printer was printing in stealth mode, I pressed pause print, nothing happens, printer keeps printing and I see that the temperature of the nozzle is now set to 0 and the actual temperature is dropping while the printer is still printing and extruding. I pressed the reset button when the low temperature started clogging the nozzle.
