### ISSUE TITLE
[Feature Request] sort gcode files on SD card by name as an option instead of only date

### ISSUE THREAD

**Issue by Photogad** [prusa3d/Prusa-Firmware#1383]
Title. I have a 3D printing business with about 300gcode files on my SD card and it would be nice to be able to have the printer sort them by name so I can keep similar designs together.

**Comment by PavelSindler** [comment]
You can sort files by name (alphabeticaly). It is in menu settings->sort.

**Comment by PavelSindler** [comment]
In your case I would recommend keeping files in multiple folders. Current sort implementation is limited to maximum 100 files in one folder.

**Comment by Photogad** [comment]
Wait we can already sort and have folders? Is this new? OMG you are amazing
