### ISSUE TITLE
[3.5.0] MK3. X-position lost on unpause

### ISSUE THREAD

**Issue by nojan1** [prusa3d/Prusa-Firmware#1384]
After having performed a pause during the print it seems the X-position was somehow lost or corrupted. This caused all the subsequent extrusions to be made about 4 cm to the right of their correct locations, ruining the print.

Maybe the printer should perform a re-home after unpause to make sure it knows where it is?

**Comment by Pathogenius** [comment]
3.5.0-RC1 (1688), I recently did a print which required a dozen or so M600 type filament changes, which I assume involves lots of 'pauses', print came out fine, no loss of position.

**Comment by PavelSindler** [comment]
Interesting... We will check again if steppers are not switched-off during pause.

**Comment by lohring** [comment]
I have a similar issue with my Mk3.  When printing objects that are close to the right edge the X axis looses position and moves several mm to the right.  This usually happens in the middle of the print and results in a crash.  The XYZ calibration must be rerun or subsequent prints will be offset.  Is this a circuit board problem?  I've reflashed and recalibrated the printer several times.  The printer ran perfectly for several months before this happened.

**Comment by Georsch** [comment]
Nach Firmware-Update auf 3.5.1 das gleiche Problem mit der X-Achse. Bei einem Crash oder Neustart des Druckers nimmt die X-Achse die letze Position als 0-Punkt an. Abhilfe schafft nur die X-Achse per Hand auf die 0-Position zu Fahren. Entweder nach Motor aus oder Nertz aus. Danach fährt die X-Achse auch wieder auf null. Mit der XYZ Kalibrierung funktioniert auch keine Referenzfahrt der X-Achse gegen null. Habe mir dadurch schon die Magnetplatte demoliert, da der Sensor, durch den Fehler, neben der Platte die Z-Achse zu weit nach unten fährt. Seltsamerweise funktioniert der X-Abgleich bei der Erstinbetriebnahmme, danach nicht mehr (mehrfach getestet, da zur Problemlösung die Firmware neu aufgespielt wurde).

**Comment by RichardHerold** [comment]
I'm having the same issue as Georsch. Since 3.6 every time i have to move it manually by hand. There is definitely a major regression here that should be looked at
