### ISSUE TITLE
Cosmetics in menu (podpora) on the LCD

### ISSUE THREAD

**Issue by martinpihrt** [prusa3d/Prusa-Firmware#1387]
Hi, in menu is cosmetics bug on the LCD...

![bug1](https://user-images.githubusercontent.com/7847139/49628608-68731680-f9e5-11e8-996d-c9cad54aeee3.jpg)
![bug2](https://user-images.githubusercontent.com/7847139/49628609-68731680-f9e5-11e8-92df-fb16fd44f9dd.jpg)
![fw](https://user-images.githubusercontent.com/7847139/49628611-68731680-f9e5-11e8-9a27-e6ea78557a07.jpg)

**Comment by inquisitiveKangaroo** [comment]
Hi,
Thank you for report. We will try to fix it asap.
