### ISSUE TITLE
FlashAir: hidden files and folders

### ISSUE THREAD

**Issue by Googliola** [prusa3d/Prusa-Firmware#1389]
After successfully configuring the mapped network drive on my Win8.1x64 notebook, I have had several issues with FlashAir:

1. newly created folders are hidden and cannot be accessed from PC. Folders show up when SDCard is inserted in cardreader
2. files are hidden on mapped drive, but are visible on Prusa and local card reader
3. filenames include the whole path _http://local-IP/GCode/subfolder/filename.gcode_ instead of just the filename (this is cosmetic, but annoying)

I checked issues here and in the forum but could not find anyone else having the same issues...which is strange.

MK3 with latest firmware 3.5.0 (but happened ever since 3.2.0 or even earlier)
FlashAir W-04 with firmware V4.00.03

**Comment by cnlson** [comment]
I also have a w-04 and had some of these issues. The strange file name was one of the issues, as well as the disappearing files when saving to the mapped drive

**Comment by Googliola** [comment]
@cnlson thanks for your confirmation. So it is not only me having this problem.
I checked Toshiba Firmware documentation for options to change the behaviour but to no avail....

**Comment by neophyl** [comment]
Not sure if its the same issue but I had something similar  and its not a Prusa or Flashair issue but a windows issue.  I was naming my gcode files with a % character, for example "Modelxx_0.15_20%infill.gcode"  They would show up on the printer lcd when print from sd was selected but wouldnt show up on the mapped drive in windows.  The issue is with the % character and the way webdav naming works.  If you stop using special characters everything shows up fine.

**Comment by Googliola** [comment]
Thanks for your heads-up @neophyl . It was bugging me again yesterday... I thought I tried that myself but I must have been sloppy and will check again and report back.
There would be a way to solve the issue on the software side: filter all invalid characters in the filename so everyone could use all the placeholders in file template.

**Comment by Googliola** [comment]
You are mostly right, the % character does mess up things on windows / webdav. As you can see below, the % causes several issues:
- filename is transformed to URL
- filesize is 0
- file cannot be deleted
![image](https://user-images.githubusercontent.com/505490/52666208-ec79db00-2f0d-11e9-8b21-05b652468403.png)
What you cannot see - which makes it much worse, is the fact that any files within the folder saved **after** the %-file (forth.txt, fifth.gcode) is invisible via webdav, but present still present. I think that explains my oberservations 1 and 2 in the initial post. Puzzling.
I removed all special characters from my profiles and will reformat my Flashair to start from scratch.

Nonetheless, filtering the characters before saving would be an easy fix on Slic3r - even tho it is not Prusas "fault"....

**Comment by neophyl** [comment]
That about matches what I remember.  Didn't have to reformat the flashair though, I just popped it back into my pc directly so it was a normal sd card access which shows all the files, deleted the files from my print directory and it was good to go.
