### ISSUE TITLE
Removing SD card while browsing files crashes machine

### ISSUE THREAD

**Issue by transplier** [prusa3d/Prusa-Firmware#1395]
Looks like the card removal detection isn't working while actually in the SD card menu itself. IIRC this worked fine in the past.

Repro:
1. Load an SD card (I used the one that came with the machine).
2. `Print from SD`
3. Remove card.

Expect: Prints a message, exits to main menu, anything other than just crashing :)
Actual: File list gets corrupted. Garbage sometimes gets printed to the screen. Machine locks up or sometimes resets itself. Basically the CPU loses its marbles.

**Comment by michalxfanta** [comment]
Thank you for reporting the error, we will deal with it.
