### ISSUE TITLE
Filament sensor triggering on  Glossy Black petg.  FW 3.5

### ISSUE THREAD

**Issue by jaybuie** [prusa3d/Prusa-Firmware#1401]
Filament sensor is failing randomly  on Glossy black petg. Appears to work fine on other colors.

**Comment by inquisitiveKangaroo** [comment]
Filament Sensor on MK3 not working properly with black PETG #1307
"filament sensor response is poor, disable it?" #1178

**Comment by inquisitiveKangaroo** [comment]
Hi, thank you for the feedback. We are aware of this issue and working on improvment.
