### ISSUE TITLE
Prusa 3.1 Compiling Issue for MK2S

### ISSUE THREAD

**Issue by 3DPrintingNoob** [prusa3d/Prusa-Firmware#1409]
I'm trying to compile Prusa firmware 3.1 and when I go to verify I get the following error in the image below. I've tried compiling in both Arduino 1.8.8 and 1.6.9. I'm a firmware noob/coding noob so I'd appreciate some feedback...thanks

![compiling error](https://user-images.githubusercontent.com/45909162/50050316-c4602e00-00bc-11e9-94bb-eac06d588b3b.JPG)

**Comment by ChrisVahi** [comment]
Have you followed all of the steps in the readme to the T? There are important steps that can't be ignored in there. Have you moved your electronics variant out of the "Variants" folder and renamed it Configuration_prusa? Z_SILENT in defined in that sketch. Try searching (ctrl-f) for "define Z_SILENT" in Arduino and make sure it can be found by the IDE. I found it around line 247 in Configuration_prusa.h. I see you're using Arduino 1.8.8. You may need to install an older version of Arduino.

**Comment by 3d-gussner** [comment]
@3DPrintingNoob Try my How-to that might help: https://github.com/3d-gussner/Prusa-Firmware/wiki/How-to:-Build-Prusa-Firmware

Also have a custom MK2/s firmware https://github.com/3d-gussner/Prusa-Firmware/releases/tag/v3.1.0-001-HFM including a merged communication fix that Prusa approved but never made the compiled hex file available.

You need to use the MK2 branch as this isn't merged yet in the default MK3 branch.

**Comment by 3d-gussner** [comment]
@3DPrintingNoob There is no update for long time. Is your issue fixed? If so please consider to close this issue.
