### ISSUE TITLE
Nozzle hit heat bed during first layer calibration (Mk3 3.5.1)

### ISSUE THREAD

**Issue by haarp** [prusa3d/Prusa-Firmware#1419]
Hey,

I just had the nozzle leave a nice mark on my steel sheet 😿 

It crashed during first layer calibration. Never had that happen before. Steps (can't verify, one hole in the PEI is enough for me 😉)

- Intend: Re-calibrate my Mk3 after upgrading to 3.5.1
- Run XYZ calibration successfully
- The steel sheet is now on the heatbed
- Start first layer calibration from the calibration menu
- During warmup, went into the menu and used the Live-Z entry to set a value close that what I'd expect it to be later on (-0.800)
- Still during warmup, long-pressed the button to manually raise Z up to around 185mm, to verify that both sides are even
- Warmup finishes, mesh bed leveling starts
- Z lowers until the nozzle is buried in the steel sheet, and further

I suspect either the manual raising of Z, the setting of Live-Z before the actual calibration process, or both was the reason it broke.

Normally I'd expect it to lower until the PINDA detects the steel sheet, then stop, so nothing bad could possibly happen. However, it seems PINDA was ignored under these conditions.

Note that the printer works fine now. I did not use an incorrect/too-low Live-Z value.

**Comment by Auge103** [comment]
Maybe this one is related, since it happens also after manually moving the Z axis? https://github.com/prusa3d/Prusa-Firmware/issues/1298    
I am also afraid to test this further myself, since I already got 2 holes in my sheet...

**Comment by inquisitiveKangaroo** [comment]
Hi
I don't understand why you pre-set your Live adjust Z value to -800 um...? This value might be slightly different after recalibration. 
I would recommend next time to pre-set the value to -500 um and fine tune the rest after first layer cal. starts for the case your new true offset is <800 um.

**Comment by haarp** [comment]
> Hi
> I don't understand why you pre-set your Live adjust Z value to -800 um...? This value might be slightly different after recalibration.
> I would recommend next time to pre-set the value to -500 um and fine tune the rest after first layer cal. starts for the case your new true offset is <800 um.

I didn't touch the hotend, so why would the value be different? Live Z mainly concerns the Z distance between nozzle tip and PINDA, doesn't it?

Anyway, live Z still was the same in the end, so wrong calibration can't have been the reason for this bug.

**Comment by 3d-gussner** [comment]
@haarp Is this still an issue? If it has been fixed in a newer firmware version, please close this issue.
[stale]

**Comment by JohnnyDeer** [comment]
I'm closing this issue as stale, thanks for understanding.
