### ISSUE TITLE
Selector stepper not moving with MMU2 v1.0.3

### ISSUE THREAD

**Issue by VjyedSC0UFMc8z** [prusa3d/Prusa-Firmware#1420]
I upgraded from MMU2 v1.0.2 to v1.0.3 and my selector stepper does not move when pressing the buttons or via the menu. I made it move with an unknown button press, but it's not consistent. I swapped the selector stepper plug into the idle plug and the selector stepper moves fine.

All steppers moved correctly when downgraded back to v1.0.2

**Comment by inquisitiveKangaroo** [comment]
> I swapped the selector stepper plug into the idle plug and the selector stepper moves fine.
> 
Hi,
I didn't really understood where did you plug the selector motor... to the five pin plug? O.o

**Comment by llama** [comment]
I have a new MMU2 which I just assembled (and immediately flashed v1.0.3) and having a similar  problem. My selector motor also moves when plugged in to the idler plug (the one for the motor labelled "extruder"). 

When I flash v1.0.2, my MMU2 controller boots then immediately all 5 LEDs flash red (the fault state). So I cant get my selector motor moving with any firmware 😞

**Comment by llama** [comment]
Yay found the problem. My filament detector ball bearing was stuck. I removed the FINDA and poked at it, loosening it up and now my MMU2 works! Surprising symptoms for such a problem. Thanks Prusa Live Support (Pavel and Marina), you guys rock!
