### ISSUE TITLE
Bug: after a collision, and start over, the outer perimeter is drawn inside the print.

### ISSUE THREAD

**Issue by DavidPhillipOster** [prusa3d/Prusa-Firmware#1429]
Firmware 3.5

I printed the box shown in the 'expectedgcode' screenshot. The far right edge curled up on the third layer so the print head hit it and the display signaled 'collision detected' and move the print head to the rear and to the left. I canceled the print, restarted the same file, but this time instead of drawing the right side perimeter, the print head laid down a diagonal line.

It was as if the collision detected print motion had contaminated where the printer though the far right corner was. It did this consistently on every layer until I pulled the power cord to force a power failure. After a power fail resume, the false position went away and the outer perimeters were what they should have been.

Expected: the gcode is a simple box, with an empty interior.

![expectedgcode](https://user-images.githubusercontent.com/5148308/50467544-605d2580-0958-11e9-8cbb-28cfaed8c772.png)

Actual: after the steps above, starting over from the beginning, the right edge of the box was extruded as a diagonal See 'actual' image. This 2-shell right diagonal was consistent from the very first layer until I stopped the print 12 hours later. The long diagonal to the right of it was an amazing bridge, but it stopped a few layers further up.

![actual](https://user-images.githubusercontent.com/5148308/50467546-6521d980-0958-11e9-8336-64acd5358efd.JPG)

**Comment by inquisitiveKangaroo** [comment]
Hi
This bug may occure when canceling an paused print. Sould be repaired by reseting the printer and it shall be fixed in fw 3.5.1 patch.
_Pause print -> stop print fix
Stopping paused print could lead to behaviour when some movements were missing during new print or first layer calibration. This has been fixed._
