### ISSUE TITLE
variable scope: local variable shadows outer variable

### ISSUE THREAD

**Issue by craiglink** [prusa3d/Prusa-Firmware#1430]
https://github.com/prusa3d/Prusa-Firmware/blob/d1ca73597b6ed695b46dcb33807a1a9ebc46d995/Firmware/mmu.cpp#L241

is the redefinition of filament expected here or should the code be using the outer variable like the other conditional blocks?

**Comment by workinghard** [comment]
You're right, redefinition can be removed. This variable is always being set before being used. Because it's in the MMU_DEBUG block, it doesn't affect the production release but make sense to remove it. 
Feel free to create a pull request.

**Comment by craiglink** [comment]
pr - https://github.com/prusa3d/Prusa-Firmware/pull/1438/commits

**Comment by gudnimg** [comment]
Closing as this code is now outdated (and removed).
