### ISSUE TITLE
[MK2s / 3.1.0] Losing Z-live calibration after every print

### ISSUE THREAD

**Issue by Boby71** [prusa3d/Prusa-Firmware#1433]
### MK2s / FW version 3.1.0

Just spent three days in finding out about the follwing behaviour:
**If you reset a the calibration data and you're only running only "Calibrate X-Y-Z" and "Calibrate Z", then the live-Z value will change with every print! If you do a "First layer calibration" as well, then the live-Z stays stable.**
This is very annoying and from my point of view a bug - you find some reports about it in the web (Facebook, Pursa forum) already. I know you're not actively developing the MK2s firmware anymore, but this affects many MK2s out there - I ran into this troubles after I did a recalibration after my original Pinda stopped working. Every user running into this issue will be left behind with a useless printer!

I see two possible ways to avoid this annoyance:
1) **Either** you demand a First layer calibration from the user (message in display, printer won't start working) 
2) **Or** you fix the problem that the firmware doesn't store the live-z when the first layer calibration hasn't been done.

I'm using my own live-Z calibration pattern for 1 1/2 years and therefore I did not rund the 1st layer calibration from the menu. I went crazy about the constantly changing live-Z (and I'm talking about huge changes, like -0,550 for the first successful print and -1,200 for the second print just to make it stick)

Thank you!

**Comment by 3d-gussner** [comment]
Hi @Boby71, as soon you do XYZ cal the the firmware expects you to rerun the 1st layer cal. Z cal doesn't reset the calibration status. Use G87 at the end of your custom 1st layer cal gcode.

I get every time i power up my MK2 a message that i have to run 1st layer cal after, or connect via octoprint.

More info https://github.com/prusa3d/Prusa-Firmware/issues/301 

Hope that helps

**Comment by Boby71** [comment]
@3d-gussner, thank you very much for the information and the link. That's a really mean one. My MK2s printer (latest official FW) doesn't require a first layer calibration after I've done a reset of the calibration data and only did the XYZ-calibration and a seperate Z calibration.

For my opinion, that's a nasty one...there is nothing in the documentation, I searched forums and Facebook groups without any success for DAYS. After three days of search I found out by coincidence, that the first layer calibration does the trick - and **because of you** I know now, G87 is the magic gcode solving all my problem.

Of course, when I look up for G87 now I find a lot of information, but when I searched for "live z changes every print" I found endless discussions about a loose pinda and the pinda-temp calibration - but not MY problem. I even talked to a guy who owns nine(!) different printers, is beta tester for Prusa - and he wasn't aware of this behavior too.

At least, the printer should stop working combined with a message "do the 1st layer calibration first (mandatory)". But this message never came for me and I was going crazy.

Thanks for clearing this up for me; I still hope for others the problem will be fixed; maybe it's the same for MK2.5 or MK3, who knows?

**Comment by ToshioMagic** [comment]
I'm having this issue on a mk2.5 with 3.9.0.

**Comment by chuyskywalker** [comment]
This thread saved my sanity. Adding 
```
G87  ; will cause the live z adjustments to actually SAVE after the print
G88

```
into my custom calibration gcode file FINALLY made it save the livez adjust values. I thought I was going mad!
