### ISSUE TITLE
Bug with power panic and filament runout

### ISSUE THREAD

**Issue by izzygold** [prusa3d/Prusa-Firmware#1440]
What happens:
After filament runs out and a power failure occurs it is impossible to continue printing

How to reproduce:
Print with not enough filament for the print, the print will pause and ask to enter a new filament, then shut down the power to the printer

What should happen:
The printer should turn on and ask to add new filament and resume printing.

**Comment by inquisitiveKangaroo** [comment]
Hi,
thank you for your feedback. We will take a look on it. Would be possible to provide us what is your FW version?
Have a nice printing day.)
Kangaroo

**Comment by izzygold** [comment]
FW version 3.5

**Comment by 3d-gussner** [comment]
@izzygold Is this still an issue? If it has been fixed in a newer firmware version, please close this issue.
[stale]

**Comment by JohnnyDeer** [comment]
I'm closing this issue as stale, thanks for understanding.
