### ISSUE TITLE
Printer Crashes When Stopping Print During Filament Change Operation

### ISSUE THREAD

**Issue by sarf2k4** [prusa3d/Prusa-Firmware#1441]
I am running the latest mmu and prusa printer firmware. Today I wanted to stop a mid print that is the operation during the filament change from f2 to f1. The message stated "please wait....." and after it finished the loading of f1, the printer just squished/crashes into the wipe tower. 

I believe that there is something wrong with the code to stop the print, where the printer will move into absolute coordinate probably about 20mm above the bed, while my position is about 30mm instead of relative position move of adding 20mm z axis movement, which is to raise the z axis. 

![20190104_120424](https://user-images.githubusercontent.com/9604217/50675204-78533a00-1027-11e9-8b7b-9652a1ef1cd2.jpg)

**Comment by JohnnyDeer** [comment]
Hi @sarf2k4, this issue has already been fixed. I´m closing.
