### ISSUE TITLE
Maintain Speed Modifier During MMU Print

### ISSUE THREAD

**Issue by Ziethriel** [prusa3d/Prusa-Firmware#145]
Currently a manual speed change made via the LCD during a MMU print is not preserved when making a tool change. I believe that a speed change should persist from tool to tool as the speed percent on the LCD should be a global modifier, more specific tweaks for different filaments and whatnot should be made in the slicer.

**Comment by bubnikv** [comment]
This should be a Slic3r request as Slic3r produces the speed modifier G-codes at each of the tool change.

**Comment by Ziethriel** [comment]
My bad, figured it would be a firmware thing since it's controlled on the machine. I'll submit it under slic3r. Thanks!

**Comment by bubnikv** [comment]
See https://github.com/prusa3d/Slic3r/issues/421
