### ISSUE TITLE
Firmware retract default value too large

### ISSUE THREAD

**Issue by GilesBathgate** [prusa3d/Prusa-Firmware#1453]
The default firmware retract is a value of 3mm see: 
https://github.com/prusa3d/Prusa-Firmware/blob/d679453b73143d5437ccda5e5f245d4c21b3d53b/Firmware/Configuration_adv.h#L381

The recommended values from e3d are 0.6mm for ABS and 0.8mm for PLA.
https://wiki.e3d-online.com/E3D-v6_Troubleshooting#Misconfigured_Retraction

As a workaround you can put:
`M207 S0.8`
in the start gcode.
http://marlinfw.org/docs/gcode/M207.html

**Comment by GilesBathgate** [comment]
The problem with such a large retraction is that it pulls hot filament up into the cold areas of the hotend where it can freeze, adhere and jam. This is especially noticeable on this test part:
![Example](https://i.imgur.com/1WOVhP7.jpg)

**Comment by workinghard** [comment]
This is only relevant if the slicer is using G10 command. So far the firmware retraction is barely used in any slicer. As you can see [here](https://github.com/slic3r/Slic3r/issues/1494) and [here](https://github.com/slic3r/Slic3r/issues/1494) it's more or less a nice to have for whatever reason.
Anyway, it does make sense to change the default value to 0.8 as the MK* series is using E3Dv6 extruder as default.

**Comment by GilesBathgate** [comment]
@workinghard Yes, you are right. The reason I logged this is that I had switched over to using Firmware retract because I was thinking "its better" after vaguely remembering a post about it on Prusa's blog. But I had forgotten to specify the S parameter in my M207 setup GCODE, and so all my prints had been suffering from the above problem. It was logged mainly in annoyance of my own foolishness, but hopefully good defaults make less fools of us all ;)

**Comment by workinghard** [comment]
Would be interesting to know how exactly it's better. If you find this blog post, please link it. I would like to know it.
Feel free to create a pull request with this change. I think it has a high chance to be approved right away and be merged into main branch.

**Comment by GilesBathgate** [comment]
So, all I could remember from the blog post was "its better", but I had forgotten about why, (the main advantage is different speeds for retract and unretract, however slicers support this now) furthermore the blog post mentions the use of the S parameter in the M207 command.
https://www.prusaprinters.org/slic3r-and-marlin-configuration-for-reprap-firmware-retraction-2/

I will create a PR.

**Comment by GilesBathgate** [comment]
Created PR https://github.com/prusa3d/Prusa-Firmware/pull/1481

Not sure how to test this locally, so I request that the upstream maintainers review and test.
