### ISSUE TITLE
Revamp of Pinda Temp Calibration

### ISSUE THREAD

**Issue by CCS86** [prusa3d/Prusa-Firmware#1454]
After watching the 3.5.x temp calibration run, I believe it is introducing error into the resulting calibration data.

It is probing the same spot on the bed to see how the pinda changes its triggering height, as the sensor changes temp. This method is based entirely on the assumption that the bed surface at this point remains in the exact same position. 

The problem is that the calibration routine is also changing the bed temp, and because of thermal expansion of all the bed/platform components, that same spot physically changes height. This gets erroneously rolled into the probe calibration data.

My thought for a more ideal temp calibration:

- Raise print head to near max height and turn on bed to the highest temp needed for pinda calibration

- Allow a long enough dwell so that physically all bed components stabilize. Pinda is still cool. The amount of dwell time could easily be established by attaching a dial indicator to the print head, indicating on the intended spot for probe calibration (I think bed center is better than the front corner used), then turn on the bed to the max temp and wait until indicator movement stops (time lapse would make this even easier).

- Now drop the head and probe the bed, creating a point set of height and probe temp.

- Wait close to the bed, as the pinda heats up, and continue probing when the pinda reaches specified probe temps.

**Comment by ghost** [comment]
This is really great idea!

**Comment by Tinker999** [comment]
I agree a simple but elegant approach which could eliminate the whole need for pre heating the Pinda. It needs to be tested but it looks easier and potentially more accurate than other methods use now. I know there is a wiki that has some other approaches. But I can’t find it. It would be great if we could get some of the  developers that came up with the other approaches to comment.

**Comment by stahlfabrik** [comment]
The other methods we have described here: https://github.com/PrusaOwners/prusaowners/wiki

**Comment by CCS86** [comment]
I dug around a bit in the firmware and found the temp calibration routine. Unfortunately, between my schedule and general faded comprehension of C++, I will not be the man for the job, hahaha

I think this is a relatively minor rewrite though. It looks like the probing location can be easy moved to bed center. Additional code added to move near the Z+ limit and dwell while the bed heats. Some code removed for the changes in bed temp.

**Comment by dougisfunny** [comment]
> 
> 
> I dug around a bit in the firmware and found the temp calibration routine. Unfortunately, between my schedule and general faded comprehension of C++, I will not be the man for the job, hahaha
> 
> I think this is a relatively minor rewrite though. It looks like the probing location can be easy moved to bed center. Additional code added to move near the Z+ limit and dwell while the bed heats. Some code removed for the changes in bed temp.

I might give it a look, where did you dig up that code so I don't have to search so much?

**Comment by CCS86** [comment]
Hopefully this permalink works:

https://github.com/prusa3d/Prusa-Firmware/blob/75523b149752c77c96a2eddd21471bf0ee3488a1/Firmware/Marlin_main.cpp#L4010

**Comment by CCS86** [comment]
@dougisfunny , did you take a look at the code?

**Comment by dougisfunny** [comment]
Nope, other projects have taken priority.

**Comment by GWdd** [comment]
Still broken ... lol.  But as far as my experience goes the current cal method is not worth including in the code. It actually made my Live-Z cals worse off after running the Temp cal.
