### ISSUE TITLE
3.5.1 - Print suddenly stops with "Press knob to preheat nozzle and continue."

### ISSUE THREAD

**Issue by mdwelsh** [prusa3d/Prusa-Firmware#1455]
I started a long print job this morning and all was going well for the first few layers. After a while, however, the printer paused unexpectedly with the message "Press knob to preheat nozzle and continue." This is on a print that I have done successfully before on pre-3.5.1 firmware; this behavior seems to be new in 3.5.1. Is this expected? What would cause this and is there a workaround (other than having to manually press the button)?

https://photos.app.goo.gl/uKHdg2LQtjstqMFT8

**Comment by inquisitiveKangaroo** [comment]
Hi, 
thank you for your report. I noticed something similar yesterday but it seemed quite odd and I wasn't sure what it was caused by. It's good to know I am not the only one so I'll keep an eye on it and will run some firther tests. If I find out anything I will let you know.)
Have a nice printing day

**Comment by Shackmeister** [comment]
I got this as well today after upgrading to 3.5.1, haven't experienced it before with 3.4.1

**Comment by mdwelsh** [comment]
I dug through the code a bit and see that this only triggers (I believe) when an M600 command is received. There is no M600 in the gcode I am using -- however, in fsensor.cpp:fsensor_update() I see an M600 is enqueued when the filament sensor notices a runout of reaches an error count threshold. Has anything in this logic changed recently? (Looking at the code it seems to not have changed since 3.5.0, which works fine for me.)

**Comment by Shackmeister** [comment]
I'm now downgrading, since I had this issue 8-10 times over the last day. Let me know if I can help with testing or something

**Comment by xoxota99** [comment]
Started having this issue today. Any update?

**Comment by Shackmeister** [comment]
I ran a calibration wizard and now it seems better. (error wise, prints does not seem better)

**Comment by bsrotten** [comment]
Mine does it on certain filaments only.

**Comment by mujido** [comment]
I had this problem and eventually noticed it was whenever I was printing with a shiny filament like gold silk. I eventually figured out it was false triggering on the filament sensor. If it is the same for you, you can disable the filament sensor when using problematic filaments.

**Comment by xoxota99** [comment]
Same solution as @mujido above. If / when it happens, go into the "Tune" menu (during print) and disable the filament sensor. Note that auto-load and filament out detection won't work with the sensor disabled.

Confusingly, this setting is located in a completely different menu (under "settings") when not printing...

**Comment by bobek** [comment]
I had similar situation, also caused by filament sensor, but in my case cleaning up the sensor fixed the issue. (A couple blows of compressed air did the trick)

**Comment by 3d-gussner** [comment]
@mdwelsh Is this still an issue with newest firmware? If not please close this issue.
[stale]

**Comment by bobek** [comment]
> @mdwelsh Is this still an issue with newest firmware? If not please close this issue.

I am currently on 3.9.0 and have not seen the issues for a long time. (I am not the author, so cannot close)

**Comment by mdwelsh** [comment]
I have not experienced this issue in a long time. Feel free to close.

**Comment by jsharf** [comment]
Just wanted to report that I experienced this on 3.9.3. It was near the end of a print and persisted for quite a while. I was out for 1-2 days so it must have persisted the whole time... very loudly. Sorry neighbors.

I was printing the prisa bottle opener that comes default on the machine, so it should be easy to find the guide

**Comment by S3D-r** [comment]
I also got this same problem yesterday, and since then it has kept stopping the prints. I have the filament sensor disabled, so, a dirty sensor shouldn't cause the issue. Any ideas?
