### ISSUE TITLE
M106 command blips the fan to 100% temporarily

### ISSUE THREAD

**Issue by zsoltmar** [prusa3d/Prusa-Firmware#1461]
Whenever in an off state (M107), any value M106 Sxxx will first ramp up the fan speed to 100% then lower it to the desired speed. How to disable this? Where and when did this behavior get introduced?
This behavior makes PWM applications unusable. Any insight would be highly appreciated!

**Comment by AnHardt** [comment]
9 Jan 2013
Configuration_adv.h
```
// When first starting the main fan, run it at full speed for the
// given number of milliseconds.  This gets the fan spinning reliably
// before setting a PWM value. (Does not work with software PWM for fan on Sanguinololu)
//#define FAN_KICKSTART_TIME 100
```

**Comment by AnHardt** [comment]
Sorry wrong repository.
21 Sep 2017

```// When first starting the main fan, run it at full speed for the
// given number of milliseconds.  This gets the fan spinning reliably
// before setting a PWM value. (Does not work with software PWM for fan on Sanguinololu)
#define FAN_KICKSTART_TIME 800
```
https://github.com/prusa3d/Prusa-Firmware/commit/6eb57da7705d31a323c313cdcf8578bbd765bc5b#diff-9e1297524ba660430362cb5b21be9cf5R71

**Comment by zsoltmar** [comment]
Much appreciated!
