### ISSUE TITLE
Cannot exit dialog if you enter Z height adjustment

### ISSUE THREAD

**Issue by tdiggity** [prusa3d/Prusa-Firmware#1462]
I encountered this while loading new filament during a print. 

When the dialog message that asks you to confirm if the color of the filament is correct, and you enter Z height adjustment by pressing and holding the control knob, you are then not able to select any options to continue the print.

**Comment by Panayiotis-git** [comment]
The fix is described in the https://github.com/prusa3d/Prusa-Firmware/issues/1196.

Both issues have the same root cause.

Unfortunately, not yet accepted.

**Comment by inquisitiveKangaroo** [comment]
Hi,
Thank you for the report. Bug confirmed on fw: 3.5.1.

**Comment by 3d-gussner** [comment]
@tdiggity Is this still an issue? If it has been fixed in a newer firmware version, please close this issue.
[stale]

**Comment by bozzzzo** [comment]
This now looks fixed. When a long press activates the Z height adjustment it is safe and possible to do either a long press, which does nothing, and a short press that returns to the screen that was active when Z height adjustment was activated.

**Comment by JohnnyDeer** [comment]
I'm closing this issue as solved, thank you all.
