### ISSUE TITLE
Change the way progress is calculated

### ISSUE THREAD

**Issue by UrielGuy** [prusa3d/Prusa-Firmware#1463]
As far as I can tell right now it's showing how much of the file was printed in bytes. 
A better way to calculate this might be the percentage of extruded material. 
I have a print that has big squares as a base that take 96% of the plastic, but just 14% of the GCODE, causing the percentage and time to be off.  
I believe what I'm suggesting is not complicated (There's already a counter for the E axis, it just needs the total length that can be easily calculated by going over the file) and will give users a better measurement

**Comment by Mjankor** [comment]
Actually, the firmware is directly reading time remaining from the M73 gcodes in the file. If time estimates are incorrect, then that's due to Slic3r. You may want to post this to the Slic3r page. Having said that, I think the Slic3r estimates are pretty accurate.
