### ISSUE TITLE
M109 S always waits for cooldown

### ISSUE THREAD

**Issue by haarp** [prusa3d/Prusa-Firmware#1474]
Hello,

I'd like to file a feature request. Very frequently I see start g-codes that first heat up the nozzle and bed to an intermediary temperature, then start mesh bed levelling, then wait for the final printing temperature to be reached. This is pretty clever as it saves some time and prevents oozing during bed levelling.

It doesn't work so well when you are printing several jobs in a row. The nozzle and bed will still be hot, so M109 and M190 will wait for them to cool down before continuing, only for the job to heat them up again immediately afterwards.

My proposal is to add a parameter to M109 and M190 that tells the printer to wait for both to heat up, but if the current temperature exceeds the requested temperature, simply continues without pausing.

Thank you!

**Comment by Photogad** [comment]
Try m109 S instead of R

I.e. m109 S60, not m109 R60

**Comment by haarp** [comment]
> Try m109 S instead of R

Thanks, it's nice to see that Marlin implements this already. Unfortunately it appears to be broken in the Prusa firmware, as it will still wait for cooldown.

**Comment by Photogad** [comment]
Weird it's working for me? Unless I'm not understanding what you're trying
to do

**Comment by haarp** [comment]
> Weird it's working for me? Unless I'm not understanding what you're trying to do

Weird indeed. Reproduction:

- Connect via serial interface
- Send M109 S200 imediately followed by M300
- > printer waits until hotend reaches 200°C, then beeps
- Send M109 S150 immediately followed by M300
- > printer waits until hotend cools to 150°C, then beeps

If M109 S worked as intended, the beep should immediately follow the M109 S150 command.

**Comment by haarp** [comment]
Okay, I had a look at the code, https://github.com/prusa3d/Prusa-Firmware/blob/MK3/Firmware/Marlin_main.cpp#L5529

Both M109 and M190 set CooldownNoWait=true when S is specified, however only the bed temperature actually uses that variable. Therefore only the bed temperature can actually use the S feature, while the extruder will invariably wait for cooldown.

**Comment by haarp** [comment]
Err, I was partially wrong. The culprit is TEMP_RESIDENCY_TIME. If that is defined, which it is by default, wait_for_heater() will ignore CooldownNoWait, and always wait despite the S parameter being used for M109.

https://github.com/prusa3d/Prusa-Firmware/blob/MK3/Firmware/Marlin_main.cpp#L7829

**Comment by haarp** [comment]
This bug is still present in 3.7.2.

**Comment by Cloud-Galaxyman** [comment]
Can't you just use M104 S0? That way the printer won't have to execute the M109 command to completion.   You can set it to cooldown but it'll immediately move on to the next gcode and can be interrupted by commands other than M0/M1. 
Am I totally missing something?
