### ISSUE TITLE
MK3 3.5.1 infinite z calibration loop

### ISSUE THREAD

**Issue by jhoblitt** [prusa3d/Prusa-Firmware#1475]
I just finessed my mk3 get stuck in an infinite automatic z-calibration loop as the print surface wasn't put on squarely and one of the rear corners was slightly raised against the index pins.  Perhaps 2 or 3 calibration cycles would be reasonable before giving up?

**Comment by inquisitiveKangaroo** [comment]
Hi,
thank you for the report. I guess such behaviour can be annoying. We'll do someting about it.

**Comment by lowell80** [comment]
Any progress/schedule for this?   I'm hitting this somewhat regularly on my MK3/S and if it happens while I'm away from my printer I'm concerned that it may shake itself apart.
