### ISSUE TITLE
Make the mesh bed levelling speed adjustable

### ISSUE THREAD

**Issue by MartinMajewski** [prusa3d/Prusa-Firmware#1496]
I have a weird issue during the mesh bed leveling sequence. Simply speaking, the movement speeds (or the acceleration/jerk) are too high and I get an unpleasant vibration noise, especially on the Y-axis. As soon as the ninth point is checked and the travel movement speed is reduced both of my MK2.5 printers are running as smooth and usual.

Is there a way to reduce the travel speed during the calibration / MBL process to match the idle movement speeds set e.g. in Slic3r without having to recompile the firmware?

Best wishes,
Martin

**Comment by Johncoffee2017** [comment]
I have exactly the same issue. It's weird. First 1st & 2nd point are ok, movement to point 3 is noisy, to point 4 as well, then it's gone to 5 and 6. Movement to 7 is noisy again, to 8 is good and to 9 noisy again. Guess its identical to Martins observation.

**Comment by thijsdeschildre** [comment]
Same here. Living in an apartment, it's not nice.
