### ISSUE TITLE
Display in 3.5.1 German Translation 

### ISSUE THREAD

**Issue by alexnet1977** [prusa3d/Prusa-Firmware#1502]
The Temperature Display in 3.5.1 doesn't look fine in the german translation, 
the tabs don't fit and the Nozzle Temp got two degree signs (See photo)

![temperature](https://user-images.githubusercontent.com/47348202/52261119-9e227600-2928-11e9-808f-c183b8912629.jpg)

**Comment by leptun** [comment]
The two degree signs issue is caused by the transition from 3 decimals to 2 decimals (100 -> 99). The second degree sign remains undeleted on all languages, not just german.

**Comment by inquisitiveKangaroo** [comment]
Hi,
thank you for reporting this. We'll make it right asap.
