### ISSUE TITLE
Starting printing in wrong direction

### ISSUE THREAD

**Issue by AndWik** [prusa3d/Prusa-Firmware#1514]
After inserting the SDcard and start a print the MK3 sometimes, but quite frequently, starts moving in wrong directions. The bord may bang on the front, X banging on the right side or Z going upwards when trying to "home". It happens to both my MK3s and was introduced by the latest software.

A reset ALWAYS fix this so it can't be a slicer error. I almost always use Prusa Slic3r.

To me it seems to be an error in initialization as Reset always fix the issue.

I thought it was a combination of Preheat while adding the card but it happens if I skip preheat.

My printers are almost always left On. Maybe some parameters are left from the last print and not completely initiated.

Thanks
Mr Anders Wikström
Sweden

**Comment by Prusa-Support** [comment]
Hello! I am absolutely sorry this has been left unanswered for this long. Is the issue still relevant, or has it been solved with subsequent firmware upgrades? In case you still have issues with this aspect, do not hesitate to let me know via email info@prusa3d.com mentioning me ("attn: Alessandro"), we'll look into it. Closing the issue for now. 

Alessandro Pantaleo
Prusa Research
