### ISSUE TITLE
MK3 > 3.5.1 > pins_Einsy_1_0.h > TEMP_AMBIENT_PIN > wrong value

### ISSUE THREAD

**Issue by NielschB** [prusa3d/Prusa-Firmware#1517]
The TEMP_AMBIENT_PIN is set to a wrong value in file pins_Einsy_1_0.h. 
It is set to pin 5(A5) but the actual pin is 6(A6). 
Functionality is OK due to ADC_PIN_IDX() function which maps both input values 5 and 6 to value 6.

**Comment by PavelSindler** [comment]
We will check it, thanks.
