### ISSUE TITLE
3.5.2-RC1-3.7.1-RC1 - Print fan not detected during SelfTest

### ISSUE THREAD

**Issue by F0x06** [prusa3d/Prusa-Firmware#1520]
Hi ! 

On the latest 3.5.2-RC1 if i perform a Self-Test, the Print fan is not detected automatically and printer is asking if fans are rotating for a manual answer. Tested on previous version and auto detection worked before, probably related to recent PWM modifications ?

**Comment by Dolnor** [comment]
I've also noticed the Support page on Extruder info is showing print fan RPM way off. At just 100/255, reported revolutions are over 4500, while the full fan speed per specification caps at 4200?

**Comment by PavelSindler** [comment]
Hi and thank you for reporting this. We will re-add reliable automatic test for swapped fans detection soon.

**Comment by F0x06** [comment]
Same issue on `3.7.1-RC1`
