### ISSUE TITLE
LCD hieroglyphs

### ISSUE THREAD

**Issue by TigerClaw33** [prusa3d/Prusa-Firmware#1526]
Hi,
I built anf flashed the hardware exactly how described but after the first message "XYZ Research and Developement" I can only see lcd hieroglyphs in all variations. Do someone know why?

**Comment by Barnabasek** [comment]
From the compiling instructions - "In file "Firmware/config.h" set LANG_MODE to 0”. Then it should work. If not, some of the other steps were not folowed.

**Comment by Prusa-Support** [comment]
Hello! Sorry for the absolutely late response here. Was it with one of our original firmware versions, or anything different? Is the issue still relevant? In case of anything more to review, feel free to let me know at any time info@prusa3d.com mentioning me in the subject ("attn: Alessandro"), I'll be glad to help. 

Alessandro Pantaleo
Prusa Research
