### ISSUE TITLE
E Axis Stepper not initalized correctly until after homing or initial extrude

### ISSUE THREAD

**Issue by Nath5** [prusa3d/Prusa-Firmware#1530]
After a restart or a filament unload / load cycle the first extrude will be really fast like 10x the speed the motor should be moving. From that point onward everything is perfect. This behavior does not happen in stealth mode.  The problem goes away after the first extrude or by homing the printer before executing any extrude commands.

The problem can be reproduced by the following process:

1. Ensure filament is not loaded
2. Turn printer off and on again
3. Run M302 // Allow cold extrude
4. Run M83
5. Run G1 E100 F100  ( extruder motor will run really fast)

To Fix the problem

1. Ensure filament is not loaded
2. Turn printer off and on again
3. Run M302 // Allow cold extrude
4. Run G28 w // Home
5. Run M83
6. Run G1 E100 F100  ( extruder motor will spin correctly)

 A video of the problem can be seen here: https://youtu.be/IV8J4V7FqoE

I came across this problem after resetting my printer firmware. Normally I start with leveling Z and doing the first layer calibration.  This time I decided to start by calibrating me e-steps using the guide here [https://mattshub.com/2017/04/19/extruder-calibration/](url) . When I went to do the initial extrude my printer started pushing tons of filament through the nozzle and I had to quickly shut it down.

Let me know if you need any other details / videos.  Several people have reproduced the problem now.

**Comment by NielschB** [comment]
I also noticed this issue before, still present in FW 3.5.2 RC1. Good to know now that G28 W prevents this behavior.
