### ISSUE TITLE
Pause print is now BROKEN with 3.5.2.

### ISSUE THREAD

**Issue by zkirkpp** [prusa3d/Prusa-Firmware#1531]
WARNING:

Since updating to the 3.5.2 firmware yesterday the Pause function is screwed up. I hit pause on the MK3 LCD screen 7 hours into a print and the nozzle heater turns itself off as it should but the machine CONTINUES PRINTING. I was perplexed at first and then realized it was still trying to turn the extruder gears with cold filament and continuing all its movements. Luckily I was paying attention and stopped the print before it started grinding the filament as the temp dropped. To make matters worse this was a ton of Prusament that is now wasted.

Printing on an MK3 purchased May 2018.

**Comment by inquisitiveKangaroo** [comment]
Hi, thank you for your feedback. May I ask you what printer type you are using?

**Comment by zkirkpp** [comment]
> Hi, thank you for your feedback. May I ask you what printer type you are using?

Printing on an MK3 purchased May 2018.

**Comment by inquisitiveKangaroo** [comment]
Thank you, we will look on it. It sounds like high priority issue.

**Comment by inquisitiveKangaroo** [comment]
Hi,
The pause function works fine to me (tried on multiple printers). Could you provide us more info such as the g-code or even better a log where this issue appeared?

**Comment by inquisitiveKangaroo** [comment]
Maybe contact the customer support to exchange your Einsy for new one. We'd like to make further tests on yours.

**Comment by zkirkpp** [comment]
I reflashed the firmware and reset the printer to factory defaults and the
issue is resolved.

**Comment by 3d-gussner** [comment]
@zkirkpp If that issue is resolved you can close the issue yourself to clean up the issue list
