### ISSUE TITLE
Filament autoload runs without nozzle heating in 3.5.2

### ISSUE THREAD

**Issue by mark0815** [prusa3d/Prusa-Firmware#1532]
Just installed 3.5.2 on my MK3 and did the following:

1. Select unload filament from the menu
2. Printer asked for filament type, selected PET
3. Nozzle heated up, when the target temperature was reached the Printer asked to hit the knob to unload filament. Filament got unloaded, nozzle heating turns off.
4. Inserted new Filament, autoload kicks in and loaded the filament, without enabling the heating or asking for preheat.

I did the filament change quite quickly so the nozzle still had around 190 degree C during filament load.

**Comment by workinghard** [comment]
Loading is allowed if the nozzle is above 175C. It doesn't matter if autoload or manual load.

**Comment by mark0815** [comment]
Ok. I should have read the manual ;-)
