### ISSUE TITLE
Issue with MK3 3.5.2 and MMU 1.0.3

### ISSUE THREAD

**Issue by Raekro** [prusa3d/Prusa-Firmware#1534]
Hello,
I have a problem with an MK3 firmware 3.5.2 and an MMU 1.0.3. At the first filament change, at the time of ejection, the printer restarts. The problem does not occur with the combination 3.5.1 and 1.0.3 and the same Gcode file. 
I asked support if this was normal, they told me that no, the MMU in 1.0.3 is supposed to work with 3.5.2, and asked me to make a bug report here.
Tested: 
- Factory Reset MK3 : No ok
- Factory Reset MMU : No ok
- Downgrade 3.5.2 -> 3.5.1 MK3 : Ok

I still think that the 3.5.2 firmware is not functional with the MMU in 1.0.3. 

Is an update of the MMU planned? Have any of you encountered the same problem?

**Comment by PavelSindler** [comment]
We will look on it.

**Comment by Raekro** [comment]
> We will look on it.

Ok, Here is what happens on the LCD screen when the problem occurs :
[Issue#1534.mp4.zip](https://github.com/prusa3d/Prusa-Firmware/files/2865053/Issue.1534.mp4.zip)

**Comment by JohnnyDeer** [comment]
Hi @Raekro, is this still a issue on newest FW versions?

**Comment by Raekro** [comment]
> Hi @Raekro, is this still a issue on newest FW versions?

No problem since 3.6. Sorry for the inconvenience, I forget to close this report.

**Comment by JohnnyDeer** [comment]
@Raekro thank you for update.
