### ISSUE TITLE
Feature Request: Auto Print Latest File

### ISSUE THREAD

**Issue by assumptionsoup** [prusa3d/Prusa-Firmware#1536]
I've noticed that for most of my prints I'm always printing the latest file on the SD card. It would be nice if there was an option in the firmware to automatically print a file with a specific name on startup.  

Something that would be hard to accidentally discover, like `__auto_print__.gcode`.  On Startup / SD card insertion the printer could ask:
```
Do you want to start the automatic print file __auto_print__.gcode now?
[YES]   [NO]
```

Or another way to implement this could be a "Quick Print" option in the main menu to print the last modified file.
```
...
Print from SD card
Quick Print
...
```
That prompts:
```
Do you want to print awesome_print_v12.gcode now?
[YES]   [NO]
```
For me, this feature would reduce the amount of time I spend twiddling with the printer to do the same thing, and could reduce mis-clicked files due to the shoddy encoder.

**Comment by inquisitiveKangaroo** [comment]
Hi,
thank you for an interesting idea. However, if i understood you well I do not think the outcome would be much beneficial.
Let me explain: Right now (on FW: 3.5.2) when you insert the SD card, you get directly into the SDcard menu. Requiring to rotate the knob one step down a press it.
In case of implementing your feature you would get a message after inserting an SD card: 
'_Do you want to start the automatic print file auto_print.gcode now?
[**YES**]   [**NO**]_'
Probably set to 'no' by default. Which mean to start print you need to rotate the knob one step up a press it.
In case you want to print the first gcode it sounds quite the same to me, however, in case you do not, it would take you at least two extra clicks.

**Comment by assumptionsoup** [comment]
Ah, I hadn't realized that the newest firmware jumps you straight to the SD card menu. That makes this PR moot, as long as the printer needs to ask for confirmation.  A minor correction, is that you still have more steps to perform if you have folders on your SD card, as those show up first, and you have to scroll past them. But it's a small thing to delete those.

**Comment by Daverkex** [comment]
Duplicate from: #1610 I think that the other issue is more developed

**Comment by assumptionsoup** [comment]
@Daverkex  I agree. I'll close this issue. I like where the discussion is going in the other one.
