### ISSUE TITLE
Problem in czech language - menu failures 3.5.2

### ISSUE THREAD

**Issue by ochm** [prusa3d/Prusa-Firmware#1541]
In CZ language is something wrong...
![img_4122](https://user-images.githubusercontent.com/47606742/52878977-51c40b00-315e-11e9-829d-7a91fde752d4.jpg)

**Comment by 3d-gussner** [comment]
I guess as `Vypadky filamentu` 17 characters and not the 14 (english) that it looks off on the LCD.

The issue is in `/lang/lang_en_cz.txt`

```
#
"Filam. runouts"
"Vypadky filamentu"
```

But i can already see more possible issues like:
#```
MSG_SELFTEST_FILAMENT_SENSOR c=18 r=0
"Filament sensor:"
"Senzor filamentu:"
```
```
#MSG_FILAMENT_USED c=19 r=1
"Filament used"
"Spotrebovano filamentu"
```
