### ISSUE TITLE
MK3 FW 3.5.2 - Print Fan Error

### ISSUE THREAD

**Issue by Hotpocketdeath** [prusa3d/Prusa-Firmware#1546]
All my fans are working and I never had an issue with them until after I updated to 3.5.2.

After the update, Soon after the print fan turns on (4th layer PETG), the print will stop with a Print Fan Error.  But the fan is still working and air is flowing.

However, I am not using the stock Prusa blower fan.  A while back, it began to fail, so I purchased some Zaribo fan replacements.  There was no issue using this fan before updating and on 3.5.2 the printer works fine if I disable fan checking.

**Comment by jdn-za** [comment]
Same issue. Both petg and pla

**Comment by jdn-za** [comment]
So my issue was resolved by switching from using 2 fans to 1 fan (yes I had modded it to use 2)

I guess the new firmware is more sensitive to pwm pulses?

**Comment by oxivanisher** [comment]
I also had this error just now. Multiple times but with no fan mod or anything. Also with PETG and on a two-day-print at 46% (so it worked for almost 20h and then suddenly this error).

**Comment by oxivanisher** [comment]
> I also had this error just now. Multiple times but with no fan mod or anything. Also with PETG and on a two-day-print at 46% (so it worked for almost 20h and then suddenly this error).

My report could be false, since there is probably a broken wire on my circular fan. Once I have it replaced, I can say more.

**Comment by JPTa** [comment]
Same issue with 3.7.0. Same blower fan as Hotpocketdeath is using.

**Comment by koenner** [comment]
Could be coincidence with the firmware upgrade, but I had [this issue](https://www.youtube.com/watch?v=cbKcj5tHjP0).  Just want to share since it took a while to root cause this failure mode.  Also, note that the Prusa customer service in dealing with this issue is total garbage - not impressed.
