### ISSUE TITLE
Save Extruder Calibration M92

### ISSUE THREAD

**Issue by slider162** [prusa3d/Prusa-Firmware#157]
It would be nice to be able to save M92 back to the printer after calibration.  If this can't be done, then I would request that someone revisit the default value.  It would appear that 161.30 is under extruding by 6-8%.  M92 E175.32 is what worked for me because I was 8mm short after giving the G1 E100 F100 command.  

I'm not saying that I have enough data, but if anyone does, it would be someone at Prusa that could run a few tests with the new printers coming off of the line to get this in the <5% ballpark.  

https://mattshub.com/2017/04/19/extruder-calibration/

**Comment by GurliGebis** [comment]
It has been fixed in the 3.0.12-1 version, there just is no download up here for it.
For now, you can download the community modded version, that has these commits included right here: https://github.com/Sebastianv650/Prusa-Firmware
