### ISSUE TITLE
MK3S + MMU2S - filament runout irrecoverable

### ISSUE THREAD

**Issue by DimitarKrastev** [prusa3d/Prusa-Firmware#1571]
Printer version: 3.6.0-RC1
MMU2S version: 1.0.5

Scenario:
When printing with i3 MK3S and MMU2S the FINDA detect no filament during print (filament runout).

Actions taken:
I removed the old filament from the PTFE and the extruder and I pressed the right button. The MMU ejects the filament, starts beeping and the printer says "Remove old filament and press the knob to start loading new filament." 

Issue:
The knob does nothing. Neither button on the MMU cause any effect. Basically there is no way of telling the printer you have actually changed the filament and the print cannot be resumed.
Octoprint outputs: 
"Recv: echo:busy: paused for user"

**Comment by jindrichbenes** [comment]
Was this during printing with octoprint?

**Comment by DimitarKrastev** [comment]
Yes it was

**Comment by bruhmann** [comment]
I also had this happen to me today.  I'm not sure why it thought the filament ran out, as it had not run out, but the system thought it did.  I've been trying to adjust the FINDA, so maybe that improperly triggered it.  I'm also using octoprint.

**Comment by JohnnyDeer** [comment]
Hi @DimitarKrastev, is this still a issue?
