### ISSUE TITLE
MK3 Linearity correction value setting will not stay in firmware this started with FW3.4 and forward

### ISSUE THREAD

**Issue by Crunch69** [prusa3d/Prusa-Firmware#1585]
mk3 Linearity correction setting will not stay in firmware this started with FW 3.4 and forward.  When you enter the Linearity correction value in the firmware and start a new print the firmware resets the value to zero

**Comment by aemileski** [comment]
Duplicate of #1371

See [my comment](https://github.com/prusa3d/Prusa-Firmware/issues/1371#issuecomment-453804655) for details of fix, and temporary work-around.

**Comment by inquisitiveKangaroo** [comment]
Hi,
thank you for letting us know. Sry for the label mess (missclick :/ ).

**Comment by JohnnyDeer** [comment]
I'm closing this issue as stale, thanks for understanding.
