### ISSUE TITLE
Compiling instructions unclear

### ISSUE THREAD

**Issue by ghost** [prusa3d/Prusa-Firmware#1590]
platform.txt (packages\rambo\hardware\avr\1.0.1\platform.txt) only contains the following:

```
# RAMBo AVR Core and platform.
# ------------------------------

# For more info:
# https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5---3rd-party-Hardware-specification

name=RAMBo AVR Boards
version=1.5.6
```
 
thus, I cannot do as section 1c of the guide says.
Arduino version 1.8.5, windows 10, I checked the repository at "https://raw.githubusercontent.com/ultimachine/ArduinoAddons/master/package_ultimachine_index.json" and the file is empty too. Where do I find the platform.txt file everyone is referencing?

**Comment by 3d-gussner** [comment]
There are 3 platform.txt files and in the beginning I wasn't sure which had to be modified so I modified all I could find. That's one of the reasons we made the PF-build.sh script which does nearly everything to compile it correctly.

Just add "compiler.c.elf.flags={compiler.warning_flags} -Os -g -flto -fuse-linker-plugin -Wl,-u,vfprintf -lprintf_flt -lm -Wl,--gc-sections" to this platform.txt file and you can compile it correctly after a restart of Arduino IDE 1.8.5.
If Ultimachine updates their repository there is a chance that this will be overwritten with the next version.
