### ISSUE TITLE
Compiler warnings - dead code removed!

### ISSUE THREAD

**Issue by thess** [prusa3d/Prusa-Firmware#160]
For many reasons, it is always a best practice to remove (or account for) ALL compiler warnings. You never know when the compiler is going to actually catch semantic or logic errors for you - it is really good at that.

After integrating the latest Firmware changes into my clean-build environment, the following warnings showed up.

```
In file included from ultralcd.cpp:167:0:
ultralcd_implementation_hitachi_HD44780.h: In function 'void lcd_implementation_drawmenu_sdfile_selected(uint8_t, const char*, const char*, char*)':
ultralcd_implementation_hitachi_HD44780.h:1205:9: warning: unused variable 'i' [-Wunused-variable]
int i = 1;
^
ultralcd_implementation_hitachi_HD44780.h:1206:9: warning: unused variable 'j' [-Wunused-variable]
int j = 0;
^
```
The declaration of **i** and **j** in this context is not in the same scope as the outer declarations of these variables and indeed they are not referenced anywhere else. Most likely the compiler has optimized these 2 statements out entirely - I'm pretty sure that is not what you intended.

I would highly recommend you integrate my PR #138 to clean up such warnings and perhaps upon further review you'll find a couple more unintended errors.

**Comment by PavelSindler** [comment]
Thank you for your work @thess . It is on our schedule to integrate your PR and also clean some redundant code. We will do it as soon as possible, but there are now different tasks with high priority planned.
