### ISSUE TITLE
feature request: print autostart on specific filename

### ISSUE THREAD

**Issue by m-cas** [prusa3d/Prusa-Firmware#1610]
I'd like to have the possibility to put a file with a specific filename, e.g. __AUTOPRINT.gcode, and have the printer start this automagically.

**Comment by cimoalpacino** [comment]
I think this is already implemented.
You have to name your file as auto0.g to have it automatically run after boot up sequence.
If you want another file to start after this, you name it auto1.g and so on. 
Files must not be placed in subfolders.

**Comment by m-cas** [comment]
Cool! You mention boot up, will it also work on every card insertion (printer already booted)?
-
From my phone while mobile, please excuse any errors.

**Comment by cimoalpacino** [comment]
Don't know. I don't use this feature. 
Try it out and let us know. 
Cheers

**Comment by cimoalpacino** [comment]
Also, if it works, it would be nice to close this thread 😉

**Comment by m-cas** [comment]
tested it, it doesn’t work on card insertion. Request remains then with addendum “… it should also work on card insertion"

**Comment by michalxfanta** [comment]
Thank you for your interesting idea, we will add it to our backlog.
