### ISSUE TITLE
Nonsensical PINDA / Bed Levelling Values

### ISSUE THREAD

**Issue by Enverex** [prusa3d/Prusa-Firmware#1617]
I had a print suddenly decide that (on the first layer) it should instead shoot nearly 10cm in the air and carry on printing there.

![image](https://user-images.githubusercontent.com/958670/54088113-31006700-4352-11e9-84fb-1e06ec6cec06.png)

I assumed it was a slicer error, so I resliced, saved and reprinted. I forgot that I'd stored the PINDA reading though, and this is what it showed:

![image](https://user-images.githubusercontent.com/958670/54088123-57260700-4352-11e9-8b35-ee65bd72fd4b.png)

A few things worry me here. First is that it freaked out in the first place and the second is the lack of sanity checking. I wouldn't expect the firmware to accept bed variation levels of nearly 10cm.

**Comment by Enverex** [comment]
After running the test again, it's still reporting completely silly values for one of the interpolated points. 3cm this time, same area though:

![image](https://user-images.githubusercontent.com/958670/54288695-ccd2e280-459f-11e9-8ef7-2d16c6ccf12c.png)

(this is after a firmware reset)

**Comment by Enverex** [comment]
It does normally work though, for example here's what it looks like typically. 
![image](https://user-images.githubusercontent.com/958670/54290075-3bb13b00-45a2-11e9-9d18-c9907f6fe3e8.png)

**Comment by inquisitiveKangaroo** [comment]
Hi,
thank you for your feedback. We are already working on optimalization of MBL so we will prevent such behaviour from happening.
Have a nice printing day.)

**Comment by leptun** [comment]
There have been safety checks in the MK3 branch of the firmware for a long time that should prevent something like this from happening. So the MK2.5(S) and MK3(S) are safe from this.
