### ISSUE TITLE
Feature request: Option to Unload filament "again" during filament change

### ISSUE THREAD

**Issue by alyyousuf7** [prusa3d/Prusa-Firmware#1620]
I was printing something yesterday and the filament ran out during the print. It *beeped* and asked to press the knob the "unload the filament". It unloaded the remaining filament and I pulled it out. The printer asked me if the filament was unloaded. I said "Yes". (remember this)*

The printer asked me to insert a new filament and I did.

But right after I inserted the new filament, I realised I inserted a wrong color filament (could be a filament with different parameters) and needed to change. MK3 gave me three options:
- Yes - Filament was loaded, no issues
- Filament was not loaded
- Filament color was not correct

I guess over here, it would be nice to have "Unload filament" as 4th option.

\* The "unload filament" option at the time of inserting a new filament will also serve as an option to unload the filament if you mistakenly select "Yes" when it asked you if the filament was unloaded correctly. Similar to issue #59.

**Comment by uchobby** [comment]
I second the request. In my case, the filament did not load, possibly due to some bit of the prior filament in the extruder.  
If the "did it load" dialog had a "start over" option.
