### ISSUE TITLE
clicking during z live adjust returns to main menu

### ISSUE THREAD

**Issue by jhoblitt** [prusa3d/Prusa-Firmware#1626]
Running `420362` from master (~`3.6.0`) and clicking "the knob" during a menu triggered "z live adjust" exits back to the main menu while the test print cycle continues to run.  It seems like this should either be disallowed or the test print should be aborted.

**Comment by inquisitiveKangaroo** [comment]
Hi,
thank you for the feedback. May I ask what benefit you see in disallowing the exit from 'z live adjust'?
Have a nice printing day.
Kangaroo
