### ISSUE TITLE
Filament change on next layer change feature

### ISSUE THREAD

**Issue by birtalanelod** [prusa3d/Prusa-Firmware#1634]
Be able to set filament change when next time is layer change (Z). 
No need to babysit printer for layer changes when experimenting with "color" prints 

{Yes, there is Prusa color print webpage  ( btw it has bugs), but i would like to be able to directly on the printer. Eg.  I would like to print some keychains like in the picture only 1-2mm thick but 6 different colors are required.
![image](https://user-images.githubusercontent.com/34862871/54428285-50fea480-471d-11e9-9635-dcc40e6fb852.png) }

**Comment by jindrichbenes** [comment]
Hello,
I suggest you try latest Slic3r PE beta, with color print improved and implemented. Just press the (+) at the desired layer.

![image](https://user-images.githubusercontent.com/23054194/54688251-92c48c00-4b1d-11e9-85da-3afda3ed55a0.png)

![image](https://user-images.githubusercontent.com/23054194/54688274-9f48e480-4b1d-11e9-8c9a-f1a4e3898fc8.png)
