### ISSUE TITLE
MMU load to nozzle from menu doesn't perform ramming FW3.6.0

### ISSUE THREAD

**Issue by NielschB** [prusa3d/Prusa-Firmware#1637]
With firmware 3.6.0 on MK3, when unload filament is selected from the LCD menu, a ramming sequence is ran just before unloading the filament from the extruder. When load to nozzle is selected from LCD menu while filament is already loaded, it performs a filament unload without the ramming sequence, which causes a bad tip on the filament. I think the ramming procedure should be added here.

**Comment by PavelSindler** [comment]
Hi. thank you for feedback. That is good idea.
