### ISSUE TITLE
Crash detected after 7x7 mesh bed level

### ISSUE THREAD

**Issue by mgg4** [prusa3d/Prusa-Firmware#1645]
### Environment
Printer: Prusa i3 Mk3 / MMU2
Firmware: 3.7.0-RC1 (Printer) / 1.0.5 (MMU2)

### Issue
After detecting the last point in a 7x7 mesh bed level operation, the printer moves to the home position.  The display shows "Crash detected", and the 7x7 mesh bed level operation repeats.  This second mesh bed level attempt succeeds and the print proceeds.

**Comment by cyberboom2** [comment]
Mine do same its crash before starting 7x7 mesh points , after last point its go back into home position and  on screen say crash detected and restarting mesh leveling again, than printing.

**Comment by Crowlord** [comment]
In addition this appears to cause me timeouts on octoprint (#1642) I have disabled it.

**Comment by cosmith71** [comment]
I see this problem, too.  Not every time, but often enough that it is disabled.

**Comment by PavelSindler** [comment]
Hi all. @cyberboom2 , @Crowlord , @cosmith71 on which printers did it happen to you? MK3 or MK3S?

**Comment by cyberboom2** [comment]
Mk3

**Comment by cyberboom2** [comment]
Mk3

**Comment by Crowlord** [comment]
Mk3 makes 3!

**Comment by thomasdlap** [comment]
Following along, switching to 7x7 results in the same for me on mk3s,
switched back to 3x3 and works fine.

**Comment by cosmith71** [comment]
MK3.
________________________________

**Comment by leptun** [comment]
I also have a problem with a mk3. Don’t know if it’s related. It skips steps when going to the first point. It might be because of the fat bundle of cables at the back, but I’m not sure. Did not let it go through the mesh bed leveling. Reverted to 3.5.1 to avoid overheating board. Problem is gone, but there is only 3x3 mesh.

**Comment by mgg4** [comment]
I had this issue every time I started a print.  Over the weekend, I had occasion to tear down my hot-end to clear a bit of broken filament.  After reassembly of the hot-end, I performed a full Wizard self-test and calibration.  Since that time, there have been no further crashes before the mesh bed leveling is started.

**Comment by leptun** [comment]
I think the XYZ calibration is the one that fixed the issue

**Comment by cyberboom2** [comment]
No XYZ calibration not fixed it i try to do that same problem crashing

**Comment by michalxfanta** [comment]
Does this problem remain with the final FW 3.7.0?

**Comment by Crowlord** [comment]
It seems fixed.

**Comment by mgg4** [comment]
I haven’t experienced it, but that doesn’t mean the issue isn’t still there. You cannot prove a negative. 

--Mark

**Comment by cyberboom2** [comment]
Its been release final 3.7.0 version its been fixed crashing problem

**Comment by cyberboom2** [comment]
https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.7.0
