### ISSUE TITLE
Calibration Wizard impacted by USB Serial data

### ISSUE THREAD

**Issue by uchobby** [prusa3d/Prusa-Firmware#1646]
During a re-calibration operation, the printer would behave strangely. Such as starting to move in various directions and speed outside of the movements planned as part of calibration.  This kept occurring as I restarted the wizard and the calibration process.  During troubleshooting, I found that Simplify 3D was running and trying to send a print job.

I believe the prior print job had failed and was not "stopped" on S3D.  The printer was responding to GCode commands from S3D which complicated things greatly.  Once I stopped S3D, actually pulled the USB cable, then restarted the wizard, all went without issue.

I suggest that you ignore serial input traffic (USB) during any of the automated calibration processes.

**Comment by PavelSindler** [comment]
Thank you for reporting this issue.
