### ISSUE TITLE
STL sliced with S3D causes printer to behave abnormally but prints fine when sliced with Sli3r.

### ISSUE THREAD

**Issue by uchobby** [prusa3d/Prusa-Firmware#1647]
The attached file is g-code from S3D for a camera mount model I designed in Fusion360, sliced in Simplify 3D (4.1.1)  When this is printed from SD card or USB direct the MK3S (firmware 3.5.3) flips out around layer 3.  The problem is apparently with the g-code output from S3D but nothing in a g-code file should cause the awesome MK3 to totally flip its gord like this.

It beeps, shuts off heaters, then shows thermal runaway on the display.  I've seen the following behaviors while troubleshooting this over several attempts.

- Print shifts about 20mm back in Y. 
- Nozzle lowers slightly or could stay in place.
- Nozzle raises in Z (10-20mm) and continues trying to print in the air
- Continues trying to extrude even though the hot end is off, loud thumping as the filament slips on the drive.
- Seems as though the printer is lost, needs a reset. Sometimes it still talks over USB, sometimes not.

The following was attempted to "fix" the g-code file.  That none of these worked implies it is not "bad" g-code.
- Passed the STL through the online STL fixing tool
- STL Loaded it into mesh mixer did a minor transform

Sliced with Sli3r, exported to SD.  Printed perfectly.  It appears that S3D does something in the G-Code that causes strange behavior on the MK3.  

[CameraWallMount v1_fixed.zip](https://github.com/prusa3d/Prusa-Firmware/files/2976151/CameraWallMount.v1_fixed.zip)

**Comment by omniwired** [comment]
This sounds like a S3D issue on how it prepares the gcode.
I don't think this issue is related to firmware but to the S3D slicer and your settings.

**Comment by uchobby** [comment]
I think the key here is that the printer went nuts due to something in the g-code.  And I do mean nuts.  I would agree something is likely wrong with S3D but the printer should not be affected in this way.  There seems to be a defect in both S3D and the firmware.

I will be notifying S3D as well.  It would be wise to look at the file and adjust firmware to generate some error condition, to gracefully handle whatever "bad" comes from the g-code.

If I were not near the printer when these issues occurred, the printer could have been damaged.  In one case it did crash the extruder head, even though the crash detection was on.
