### ISSUE TITLE
Feature request: independent perimeter settings for outward-facing surfaces

### ISSUE THREAD

**Issue by haleypearse** [prusa3d/Prusa-Firmware#1649]
I usually print hollow but not fully enclosed objects, and for these I'm always balancing the different requirements of the inner and outer walls. This is similar to the "external perimeters" setting but would refer to only the faces that are largely exposed to the edges of the build volume. For instance, when I print speaker enclosures with convoluted inner structures, there are no settings to achieve a quality exterior finish that don't also apply to all inner surfaces. Settings for speed and number of perimeters would be most useful.

The algorithm could perhaps extend normal lines of the object's faces and distinguish whether they strike one of the object's other faces or the edge of the build volume first.

**Comment by PavelSindler** [comment]
Hi, you should open this issue in https://github.com/prusa3d/Slic3r repository.
