### ISSUE TITLE
3.7.0 rc1 mmu2s printer doesn't pause after mmu2 load error using octoprint

### ISSUE THREAD

**Issue by Brandoskey** [prusa3d/Prusa-Firmware#1652]
The printer will fail to load filament from the mmu2, turn off the hotend heater and then continue to "print" without pushing filament instead of pausing and waiting for user intervention.

This happens on an mmu2s through octoprint.

**Comment by PavelSindler** [comment]
We will try to reproduce this issue. Thanks for reporting.

**Comment by PavelSindler** [comment]
Yes we confirm the issue. Thanks for reporting. We will fix it.

**Comment by brad-stone** [comment]
Same problem here.  Glad to see it is confirmed and being fixed (hopefully) soon.

**Comment by DesignFlaw06** [comment]
Also experiencing this issue in the released 3.70.

**Comment by mkbel** [comment]
Fixed in https://github.com/prusa3d/Prusa-Firmware/pull/1713
