### ISSUE TITLE
MK3 3.6.0 Print stall after purge line using MMU2

### ISSUE THREAD

**Issue by bashmost** [prusa3d/Prusa-Firmware#1660]
I am having a problem with the gcode after flashing. Now when my printer sees the second t-code it just stalls. The temps are all good and it will run all the way through the purge line but then it stalls at that spot. If I am using Pronterface or the Slic3r PE software to run my printer the terminal window shows "duplicit T-code ignored". If I open the code in an editor I can comment out the second T-code and the program will run correctly. 
If I am running from the SD card I still get the stall. Heatbed and extruder will stay heated but it will not go past the purge line. 
I have flashed and reflashed, downloaded and redownloaded, and tried going back to the old firmware but still have this issue. 
I would like to be able to print without having to hand edit my gcode file everytime. :)
firmware = 3.6.0-2069,
MMU2 FW = 1.0.5.297
Slic3r PE  1.41.3
This is the start of my code:
`
; generated by Slic3r Prusa Edition 1.41.3+win64 on 2019-03-18 at 19:11:37

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R497
M73 Q0 S501
M201 X1000 Y1000 Z1000 E8000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E1.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
M107
M115 U3.5.1 ; tell printer latest fw version
M83  ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G21 ; set units to millimeters

; Send the filament type to the MMU2.0 unit.
; E stands for extruder number, F stands for filament type (0: default; 1:flex; 2: PVA)
M403 E0 F0
M403 E1 F0
M403 E2 F0
M403 E3 F0
M403 E4 F0

;go outside print area
G1 Y-3.0 F1000.0
G1 Z0.4 F1000.0
; select extruder
T0
; initial load
G1 X55.0 E32.0 F1073.0
M73 Q0 S500
M73 P0 R497
G1 X5.0 E32.0 F1800.0
G1 X55.0 E8.0 F2000.0
G1 Z0.3 F1000.0
G92 E0.0
G1 X240.0 E25.0  F2200.0
G1 Y-2.0 F1000.0
G1 X55.0 E25 F1400.0
G1 Z0.20 F1000.0
G1 X5.0 E4.0 F1000.0
G92 E0.0

M221 S95
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
G92 E0.0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
T0                                    ******this is where it stalls always, if I remove it it works fine*****************
M900 K30; Filament gcode
G1 Z0.200 F10800.000
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2
`

**Comment by PavelSindler** [comment]
We will try to reproduce it and let you know. Thanks for reporting it.
