### ISSUE TITLE
MMU2S loading to nozzle should raise the Z axis

### ISSUE THREAD

**Issue by Dutchy-79** [prusa3d/Prusa-Firmware#1668]
Firmware 3.7.0-RC1-2175 MK3S MMU2S 1.0.5

I loaded filament 1 to nozzle, It preheated and the started loading. Though it did not raise the Z axis and now there's a big blob after asking me if it's loaded okay.

I think the Z should go up just like normal load on the MK3

**Comment by 3d-gussner** [comment]
As a workaround try to move z up before you load filament.
But I agree that the initial mmu2 filament load should be like the MK3 standalone lifting z by 2mm or if it is blow 25mm it moves to z height 25mm.

**Comment by Eddiiie** [comment]
Dupe of #1410  ?
