### ISSUE TITLE
[Feature Request] Add delay timer

### ISSUE THREAD

**Issue by karolzlot** [prusa3d/Prusa-Firmware#1669]
Please allow to start job from sd card with chosen delay, for example after 2 hours from the time user chose job

It should be very easy to add this feature

**Comment by Neolker** [comment]
Not sure if this is implemented, but you should try add at the beginning of the .gcode file:
`G4 S7200 ; Wait for 2 hours`
See here: http://marlinfw.org/docs/gcode/G004.html

**Comment by 3d-gussner** [comment]
@Neolker That will work, but if you have a gcode that you reprint often/ or later it will wait always 2 hours before it starts.
@qqgg231 Don't know how many users need/will use that. Maybe Octprint could help you to schedule prints.

**Comment by karolzlot** [comment]
@3d-gussner 

Now I see it is still not implemented in OctoPrint:
https://github.com/foosel/OctoPrint/issues/349

**Comment by michalxfanta** [comment]
Delaying the start of the print is against the recommendation to check the correct printing of the first layer.
