### ISSUE TITLE
[Feature request] Non-interactive variant of Tx + Tc G-codes

### ISSUE THREAD

**Issue by jeanblanchard** [prusa3d/Prusa-Firmware#1670]
As far as I can tell, the `T0` - `T4` G-codes are non-interactive equivalent to `T?`, but there is no way to specify the extruder using the new default (but undocumented) `Tx` + `Tc` commands.

Suggestion : implement G-codes like `Tx0` - `Tx4` to allow specifying the extruder when using Octoprint or the like.

**Comment by Naugrimohtar** [comment]
I use a Octoprint plugin which allows me to choose which filament via Octoprint (very handy). It replaces the Tx command with T0-T4 as appropriate. Unfortunately this happens when the extruder isn't yet warm so it just grinds trying to load it all the way.
