### ISSUE TITLE
EXTR. FAN ERROR should turn off bed heater

### ISSUE THREAD

**Issue by Gigahawk** [prusa3d/Prusa-Firmware#1671]
Just came back to a print that failed with `Err: EXTR. FAN ERROR` [with the bed still hot.](https://imgur.com/a/LVISL1W)

In this particular case it was due to filament getting stuck inside the extruder fan but I could imagine there might be other failure modes that would warrant turning off all heaters on the printer considering that the print has already failed.

**Comment by inquisitiveKangaroo** [comment]
Hi Gigahawk,
Recieving 'exter. fan error' should set your nozzle temp. to zero while keeping your bed still heated. The error means your noctua fan is stuck (printer do not detect enough RPM on the noctua). In many cases prints may finish well after cleaning the noctua fan because it is kept warm.
