### ISSUE TITLE
Incorrect Z display. 3.7.0 rc1

### ISSUE THREAD

**Issue by bigbobed** [prusa3d/Prusa-Firmware#1672]
Z=? on LCD. Z calibration correct but when moving on Z axis Z=? never changes.

**Comment by stahlfabrik** [comment]
I bet self compiled? If so set compiler flags according to readme

**Comment by bigbobed** [comment]
Yes.

**Comment by stahlfabrik** [comment]
I edited my answer above with a hint to the compiler flags you need to use

**Comment by bigbobed** [comment]
I was using the windows app so couldn't make the change. Installed on my pc and made the changes. Now get compile errors, can't compile on RAMBo.
