### ISSUE TITLE
Part of second layer missing

### ISSUE THREAD

**Issue by leftspin2k** [prusa3d/Prusa-Firmware#1673]
Originally posted in the Slic3r section, they say the gcode looks fine.
https://github.com/prusa3d/Slic3r/issues/2007

Version

firmware 3.5.1 release build
Prusa MK3 stock

Slicer
1.42.0-beta_win64
Operating system type + version

Operating System: Windows
System Architecture: 64 bit
Windows Version: Windows 10 (build 17134), 64-bit edition
3D printer brand / version + firmware version (if known)

Behavior

Slice using the stock configuration for 0.3mm Draft mode

export

Print the file.

first layer prints fine, second layer does not extrude during first 20% of the layer. printer moves over the region.

Print 1 and print 2 top sides

Reproduction of the print defect.

![](https://user-images.githubusercontent.com/35940722/54853323-ceda2700-4cac-11e9-8a20-09e67c8139a2.png)

Print 1 top side and Print 2 bottom side.

Shows that extrusion picks up at the same location in both prints. Not a filament feed issue unique to 1 machine.

![](https://user-images.githubusercontent.com/35940722/54853338-d7caf880-4cac-11e9-8998-b4fd31de99a4.png)

Project File (.3MF) where problem occurs

https://github.com/prusa3d/Slic3r/files/2998348/Draft.bug.zip

**Comment by inquisitiveKangaroo** [comment]
Hi,
did you try to flash a newer version of firmware?
Kangaroo

**Comment by michalxfanta** [comment]
Hello, the first layer is printed with 215 °C that's ok, but the second layer is switched to 195 °C and it is too low for PLA.
During temperature change, the temperature may drop temporarily below 195 ° C and the nozzle may temporarily clog. If the temperature drops below 170 ° C, the extrusion stops completely until the temperature rises again.

**Comment by michalxfanta** [comment]
196/5000
During temperature change, the temperature may drop temporarily below 195 ° C and the nozzle may temporarily clog. If the temperature drops below 170 ° C, the extrusion stops completely until the temperature rises again.

**Comment by leftspin2k** [comment]
Thanks for that explanation! It would be nice if there was a warning for that in Slic3r.
