### ISSUE TITLE
linear correction not saving 

### ISSUE THREAD

**Issue by Brr0** [prusa3d/Prusa-Firmware#1675]
Just messing around with linear correction and noticed after restart it is not there. I set it again and tried storing it by M500, turned the printer off and on and linear correction is on off again
Edit: fixed by setting the value and letting the menu back itself after some time to the main screen as described [here](https://github.com/prusa3d/Prusa-Firmware/issues/1371#issuecomment-453804655)

**Comment by Prusa-Support** [comment]
Hello! Sorry for the very late response to this thread. Checking on the situation and other threads, this should have been fixed from FW version 3.7.1, released a few weeks after the opening of this thread  - I am closing the issue for now for this reason. 

Alessandro Pantaleo
Prusa Research
