### ISSUE TITLE
M915 Stealth Mode Code not Recognized when sent from octoprint terminal

### ISSUE THREAD

**Issue by benjaminmakowsky** [prusa3d/Prusa-Firmware#1676]
When attempting to place printer into Silent Mode from terminal with code M915 it states it is an unknown code

**Comment by F0x06** [comment]
If i remember correctly, the M915 command is not implemented in the firmware, or partially and commented, i already implemented it in the past, I'm not using it anymore. The only way to switch between modes is from LCD for now.
