### ISSUE TITLE
[Idea] Disable Steppers on MMU2 when not in use?

### ISSUE THREAD

**Issue by ggrote** [prusa3d/Prusa-Firmware#1681]
It would be nice if the steppers on the MMU2 will be disabled when they are not in use while printing. Especially if a print does not need to change the filament.
Otherwise they are making a constant rustle sound.

**Comment by dikodahan** [comment]
+1 for that!

**Comment by 3d-gussner** [comment]
Shutting down all mmu2 steppers could get a bigger issue as these could loose their position. 
- disable the mmu2 extruder shouldn't be an issue
- disable the mmu2 idler would need to rehome every time it wakes up, as the position is critical to load/unload filament
- disable the selector could be the biggest issue as it could move and make unloading very hard.

**Comment by michalxfanta** [comment]
Exactly like @3d-gussner said, keeping steppers on is on purpose.

**Comment by ggrote** [comment]
Ok makes sense. Thank you anyway for the explanation.
