### ISSUE TITLE
Please restore old unload temperature requirement behavior

### ISSUE THREAD

**Issue by Commod0re** [prusa3d/Prusa-Firmware#1688]
The new filament unload preheat requirement is obnoxious and wasteful, why must I wait for a preheat when the nozzle is already 195C? Why does that preheat trigger a bed preheat? Please restore the old behavior of simply allowing the unload procedure as long as the nozzle is still above a certain temperature, or at least don't preheat the bed

**Comment by m-cas** [comment]
Agreed. Personally I'd prefer the 2nd choice: leave the thing as is but do not heat up the bed.

**Comment by Panayiotis-git** [comment]
I also dissagree with the heat-bed preheat. When I want to remove the filament I do not want to wait for the heat-bed to also warm up. For this I use the preheat menu.

**Comment by leptun** [comment]
You don’t have to wait for the bed. Once the hotend reaches the target temp - ~10deg you can press to remove filament.
I agree with you that the bed does not need to be heated though. I will try to implement this change.

**Comment by ctilley83** [comment]
It should not heat the bed.  All I want to do is load filament sometimes.

**Comment by michalxfanta** [comment]
We think about it.

**Comment by Crowlord** [comment]
My tuppence worth

Loading heat the bed
Unloading dont.

**Comment by timur-tabi** [comment]
The original behavior was better.  Heating the bed is pointless, and we shouldn't need separate temperatures for different filaments.  Just heat the nozzle to around 200 degrees and then unload or load.

**Comment by bpvarsity** [comment]
I like the bed heating up. They just need to make it a user selectable option for those that don't want it

**Comment by timur-tabi** [comment]
Bed temperature has nothing to do with load/unload, and there are already too many options.  It used to be so simple - click unload, and then it heats the nozzle and unloads.  There was nothing wrong with that behavior.

**Comment by Panayiotis-git** [comment]
If I want to preheat the bed I use the Preheat option. The heating of the bed during loading/unloading is pointless.

**Comment by m-cas** [comment]
I share exactly the same viewpoint. 

-
From my phone while mobile, please excuse any errors.

**Comment by ttabi** [comment]
This issue is not stale.

**Comment by 3d-gussner** [comment]
@ttabi This has been solved with https://github.com/prusa3d/Prusa-Firmware/pull/2335.
