### ISSUE TITLE
Put version info in release filenames

### ISSUE THREAD

**Issue by tracernz** [prusa3d/Prusa-Firmware#1690]
Minor nit, but makes life a bit easier. Instead of the files being named like `FW_MK3-EINSy10a.hex`, add the version in so we get something like `FW_3.7.0_MK3-EINSy10a.hex`. That should give a nice sort order even if you have multiple printers of different models.

**Comment by michalxfanta** [comment]
Hello, that's a good idea, we'll think about it.

**Comment by 3d-gussner** [comment]
Using the PF-build.sh script will generate that kind of names. We added that to have unique filenames. During the update procedure the user can double check which FW she/he is uploading and in case of a needed downgrade it is way easier.

**Comment by tracernz** [comment]
This was fixed some time back.
