### ISSUE TITLE
Bug/Feature? - Resume after pause and power off like in power outage

### ISSUE THREAD

**Issue by quarkcz** [prusa3d/Prusa-Firmware#1695]
When power goes off, printer will resume printing.

When I manually pause print and then power goes off, it DOES NOT resume. 

I wanted to move printer to another room. I know about power outage function so I didn't worry about my print. I paused printing (to be more gentle to my printer), powered off, moved printer, plugged in, but no resume poped up. Whole print was lost.

So now I know, that if I want to move printer, i can't pause print, I have to switch off power during print and them move it. It feels very illogical to do it this way, but seems to be only way possible today. Could you please fix this?

**Comment by mkbel** [comment]
Reproduced.

**Comment by unixunion** [comment]
Is there progress on this? When I have MMU failure, it sometimes gets stuck on resuming position..., and doing a power cutout and back in again doesn’t resume

**Comment by wavexx** [comment]
It's a know limitation of the PP function currently #2325, #2249, #2001

**Comment by DoctorMarshall** [comment]
Reproduced.
Can we have a ETA of this? Seems like it could be a quick fix and is hanging for 2 years already.

Thanks!
