### ISSUE TITLE
Automatic print failure detection 

### ISSUE THREAD

**Issue by Dev-DT** [prusa3d/Prusa-Firmware#1705]
Hi 

Do you think that the PINDA probe could be used to detect print failures?

E.g if you start regularly detecting stuff higher than the nozzle, the print has likely failed.

**Comment by leptun** [comment]
Could you please clarify what you mean by things being detected higher than the nozzle.
Please note that pinda only detects metals (such as the print bed or a spatula), not plastic. If that is what you meant, it is not possible.

**Comment by michalxfanta** [comment]
It's exactly as @leptun said, PINDA only detects metals. Cannot be used to detect print failure.
