### ISSUE TITLE
Display in fw 3.7 Italian translation

### ISSUE THREAD

**Issue by giudiceanto** [prusa3d/Prusa-Firmware#1708]
1. In the calibration menu, the second line should be "Wizard" but instead there is a displacement of the third line "Calibrazione primo layer"
You can abbreviate the third line in "Calib. primo layer"
![20190407_110614](https://user-images.githubusercontent.com/26503971/55720628-91da9800-5a01-11e9-83d0-cfe485639f31.jpg)

2. During the calibration, when the display asks if the plate is on the heatbed, again a misplacement.
You can modify the phrase in "La piastra d'acciaio è sul piano?"
![20190407_103916](https://user-images.githubusercontent.com/26503971/55720641-9737e280-5a01-11e9-8d0b-57a26feeba43.jpg)

**Comment by Prusa-Support** [comment]
Hello! I am sorry this has been unanswered for so long. I believe however this has been solved in the meantime in the more recent firmware releases. I'll close the issue based on the info I have at hand, but in case of more similar issues, do not hesitate to let me know via email info@prusa3d.com mentioning me ("attn: Alessandro"), we'll look into it. 

Alessandro Pantaleo
Prusa Research
