### ISSUE TITLE
Filament change menu should include the unload option

### ISSUE THREAD

**Issue by bagobones** [prusa3d/Prusa-Firmware#172]
I find that the filament sometimes does not unload correctly during the filament change... There is no option to try again if it has failed when using the built in change command. Currently it only includes the yes complete and load again option.

It would be preferable to run unload again (it happens once automatically at the beginning of the change) than to manually pull open the tension or even unscrew the tension screws and reassemble just to do a simple change.

**Comment by Naugrimohtar** [comment]
I agree. Is there a way to upvote?

**Comment by mrjohnc** [comment]
+1 also

**Comment by daktylus** [comment]
+1

**Comment by ChiefPoints** [comment]
I only recently started to use the color change ability and this definitely is a must have feature. All to often the filament fails to fully eject on the first run and you are left with the choice of loosening the tension or forcibly pulling the filament up.

**Comment by tkircher** [comment]
Yes, we definitely need this option.

**Comment by pinsonn** [comment]
+1

**Comment by Naugrimohtar** [comment]
+1 for this

**Comment by bagobones** [comment]
Given the age of this request I am guessing I will not see this for my old MK2s if it ever gets implemented.

This is quite an old request at this point.. Surprised more people where not very frustrated with it.
