### ISSUE TITLE
7x7 mesh bed leveling - how?

### ISSUE THREAD

**Issue by ochm** [prusa3d/Prusa-Firmware#1724]
I recently upgraded MK3 to 3.7.0-2201, but mesh bed leveling which is done prior each print is still 3x3. What I'm doing bad? The Start G-code contains command G80.
Thank you.

**Comment by ochm** [comment]
Probably not set in Settings, closing.

**Comment by cimoalpacino** [comment]
Please close this thread.

Use search and you can find the answer:
https://github.com/prusa3d/Prusa-Firmware/issues/1618
