### ISSUE TITLE
Axis moving opposite directions on random gcode - MK3S with the firmware 3.7.0

### ISSUE THREAD

**Issue by ghost** [prusa3d/Prusa-Firmware#1733]
I have a problem with my MK3S with firmware 3.7.0. When I try to print exported gcode, axis trying to move opposite directions.

Z - moving up
X - moving towards idler pulley
y - moving front

This exact same gcode working fine with the MK2S. I did export this gcode with Slic3r 1.41.3 - Prusa Edition

**Comment by michalxfanta** [comment]
Could you send us this GCODE?

**Comment by ghost** [comment]
Please refer following zip file. Please print and review "aucasaurus-100.gcode" file. This gcode having problem with the axis opposite moving with my Prusa MK3S printer.

[gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/3123702/gcode.zip)
