### ISSUE TITLE
FlashAir: IP Address is not being shown

### ISSUE THREAD

**Issue by selectnone** [prusa3d/Prusa-Firmware#1734]
Since I updated to firmware **prusa3d_fw_3_7_0_MK25S** , my FlashAir IP address is no longer being shown.

The Support menu lists **FlashAir IP Addr:** but there is nothing shown underneath.

Clicking that menu-item doesn't show the address.

This card worked fine with my firmware from 2017.

The FlashAir functionality otherwise seems to work as expected.

**Comment by ochm** [comment]
You can take a look to your DHCP server and you can make IP reservation to give your printer always the same IP.

**Comment by odaki** [comment]
@selectnone 
If you were having problems using FlashAir W-04, my fix may fix the problem.

https://github.com/prusa3d/Prusa-Firmware/pull/2397
