### ISSUE TITLE
[Suggestion] Nozzle change quick button

### ISSUE THREAD

**Issue by cyxlops** [prusa3d/Prusa-Firmware#1750]
It would be really nice to have a quick shortcut button in main menu to initiate a nozzle change. Where nozzle temp is set to 285 instantly without the need to dig deeper into settings and rotate the knob multiple times. It just improves efficiency this way.

**Comment by crua9** [comment]
It would also be interesting if they added within that a guide on what to do step by step. I mean you have the lcd panel, and it can tell the user what to do.

**Comment by gudnimg** [comment]
Duplicate of https://github.com/prusa3d/Prusa-Firmware/issues/1579 we've now implemented "Nozzle Change" menu into the firmware.
