### ISSUE TITLE
Tone of the sound doesn't change - Fixed

### ISSUE THREAD

**Issue by crua9** [prusa3d/Prusa-Firmware#1756]
This is for 3.7.  I'm not sure if this is a problem with other recent firmware changes since it was a while since I updated my printer.

So I normally run the following code at the start of a print in the gcode
```
; gcode start sound
M300 S440 P500
M300 S880 P500
M300 S440 P500
```

And the following at the end

```
; gcode end sound
M300 S440 P1500
M300 S587 P1500
M300 S440 P1500
M300 S587 P1500
```
The point of the sounds is to let me know when a print is about to start and end. The problem is the tone doesn't change even if the command above tells it to as seen.

**Comment by JagerSprinkles** [comment]
Same as #1588

**Comment by leptun** [comment]
This should be fixed in latetest Mk3 branch since timer2.h was disabled.
Not sure if it’s in this current release though. 

You might be able to try Mk3.7.0-RC1 and see the problem fixed.

**Comment by crua9** [comment]
I can confirm this is fixed in the newest update.

Thanks devs.
