### ISSUE TITLE
Firmware Reset procedure changed 3.0.12

### ISSUE THREAD

**Issue by ghost** [prusa3d/Prusa-Firmware#177]
http://help.prusa3d.com/mk2-firmware/factory-reset-to-defaults

1. Click Reset
2. Hold Selector
3. Release Selector at Beep
4. Immediatly hold Selector again untill 2nd beep

This does not work anymore. Step 4 needs to be removed and 'all data' needs to be manually selected to do a factory reset.

**Comment by PavelSindler** [comment]
We are currently working on this. There are more things which needs to be changed. It should be all done this week.
