### ISSUE TITLE
3.7.0 MK3s, slowly moving moving away from print after finishing

### ISSUE THREAD

**Issue by Battleroid** [prusa3d/Prusa-Firmware#1773]
I went from 3.5.3 to 3.7.0 and this has been a pretty constant issue. I'm not sure what causes it either. Whenever prints finish the hotend moves upward normally, but then takes ~2 minutes to move to the far left side of the X axis. I'll try taking a video of it next time it occurs to demonstrate.

**Comment by ochm** [comment]
I'm on 3.7.0 long time, and at the end of print my i3 MK3 behaves absolutely normaly (do what is defined in my custom End G-code):
G4 ; wait
M221 S100
M104 S0
M140 S0
M107
G1 E-2 F2100
{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+1, max_print_height)}{endif} ;
G1 X100 Y200 F10800
{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+80, max_print_height)}{endif}
M84
