### ISSUE TITLE
"Stop Printing" forces us to unload at least one filament. Please change this

### ISSUE THREAD

**Issue by m-Th** [prusa3d/Prusa-Firmware#178]
When we choose "Stop Printing" a menu appears saying "Unload all"/"Unload current"/"Unload printing filament".

Please add an option saying just "Exit" (or similar). We want to keep all the filaments loaded, just to stop the printing.

**Comment by domesticatedviking** [comment]
I agree 100%.  Unloading and cutting filament on a single extrusion print that has to be aborted is wasteful, tedious, and unnecessary.

**Comment by 3d-gussner** [comment]
Question: You are talking about a Prusa i3 MK2(s) Multi Material? Because this doesn't happen on a MK2s SM.

**Comment by m-Th** [comment]
@3d-gussner : in title I said "...**at least one** filament". In the issue's body I quoted the menu with "Unload all/Unload current/Unload printing filament". 

From all these one can infer that indeed I am speaking about MK2S MM. :)

**Comment by ceryen** [comment]
I agree with this request.  I would like the option of simply pulling the currently extruded filament back into the multiplexer rather than fully unloading the filament.  Whenever I'm stopping a print, there's a very good chance I'm going to restart the same print, so I'd like to keep the same filament loaded.

**Comment by jokohoko** [comment]
Also agree, i seem to be using the reset button way to often when trying to make the multi material to work. (and resetting is mostly to skip the unload procedure.

**Comment by macfly1202** [comment]
Completely disappointed with this behavior at my first MMU stop print today. Why must we unload one or more filament COMPLETELY? why not unload 5 cm only? It would be great if this option - must often use option I say - could be added to the menu.

**Comment by Burner911** [comment]
I agree, I would also appreciate an option of being able to stop a print without having to completely remove at least one material.

**Comment by henrikkoch** [comment]
totally agree I have mentioned this to Prusa - They didn’t react on this at all


Med venlig hilsen
Henrik J. Koch

**Comment by edunad** [comment]
+1 this

Quite annoying, i had to stop the print because the model slided :P, it wasn't because of filament being stuck
