### ISSUE TITLE
Resume after print pause starts on wrong position

### ISSUE THREAD

**Issue by ochm** [prusa3d/Prusa-Firmware#1783]
In FW 3.7.0 i found strange behavior in my i3 MK3. I,'m not sure if it is a bug, but i have no such experience in previous versions.
If i do pause print, for example on first layer (just for test), after resume print, the nozzle start extrude filament away the point where the print was paused. Not so far away but away.
But whole print continues and finish OK (only with hole in first layer in this example).

**Comment by DJGoo** [comment]
I've noticed this too, it was a lot worse with the initial FW (3.5.3) on my MK3s, on 3.7.0 it usually only skips a small section but I've had it skip whole layers before.
