### ISSUE TITLE
Change Uart2 to use multi-cpu communication

### ISSUE THREAD

**Issue by WarlockD** [prusa3d/Prusa-Firmware#1785]
Just wondering if anyone would be interested in this.  AVR MCU's have a feature on their USART's that support one byte addressing on them.  Using this you can turn the USART into a mini-network.  Doing it like this would let you add more external devices, like an external display (the original reason why I am thinking of it)

At the end of the day, I want to hook up the display, MMU2 to this network using RS485 and do it with minimal cost.

**Comment by dronecz** [comment]
Did you try that already on this FW or is it just an idea?
