### ISSUE TITLE
[Improvement]: immediatly beep on file selection

### ISSUE THREAD

**Issue by toasta** [prusa3d/Prusa-Firmware#1799]
If you are going to print from sd and select a file, there's a delay between the
selection and the beep as a confirmation. This is likely caused by the check for
file-completeness (end marker?)

It's a bit irritating, especially for larger files because u don't  know if it has acceptet your click on the rotary encoder. Personally i think it would be better  to beep instantly and then check for file
completeness to give a timely "got it, working on it" feedback.

**Comment by PxT** [comment]
Duplicate of #1736?

**Comment by toasta** [comment]
yup. sorry. missed that.
