### ISSUE TITLE
No "Live Adjust Z" during Print?

### ISSUE THREAD

**Issue by m-Th** [prusa3d/Prusa-Firmware#181]
During my prints, suddenly I discover that I have only this menu which remains till the end of the print:

Info Screen
Tune Print
Pause Print
Stop Print
Statistics
Support

I don't know why and when appears but it is quite annoying to not have "Live Adjust Z" during Printing.

Please fix this.

**Comment by macfly1202** [comment]
I had the same question in the past: and the answer is: after z greater than 2.00, Z live adjust disappear. Normal behavior.

**Comment by GurliGebis** [comment]
You only use the Live Z adjust for the first layer, so after it reaches 2mm, it is hidden.

**Comment by m-Th** [comment]
ok - thanks. :) TIL.
