### ISSUE TITLE
Ignored gcode lines. Circle segment reduction?

### ISSUE THREAD

**Issue by Swesen** [prusa3d/Prusa-Firmware#1812]
I have a strange problem where my MK3S with MMU2S will just skip a couple gcode commands. I suspect this could be something where the firmware is trying to reduce the number of segments in a circle.

A part that produces this (at least this latest iteration) is a triangle shaped part with one right angle and the right angle is rounded. I tried via SD-card and octoprint, and slic3r PE 1.41.3, 1.42 beta1 and 2 to rule out any other component. This also happened with another part that had a large circular perimeter. Also the same part with the hole in the middle slightly more to the center had no problem printing...

I also tested to reduce the face count on the exported STL from fusion 360. Which helped on one of the parts but not the other.

![IMG_20190510_175606](https://user-images.githubusercontent.com/38762425/57540482-201da300-734d-11e9-913e-9b330c377150.jpg)

![IMG_20190510_172953](https://user-images.githubusercontent.com/38762425/57539640-3591cd80-734b-11e9-9567-79f3abcde7cb.jpg)
![IMG_20190510_171628](https://user-images.githubusercontent.com/38762425/57539641-3591cd80-734b-11e9-998e-e4198e8fa3d2.jpg)
![IMG_20190510_171623](https://user-images.githubusercontent.com/38762425/57539643-3591cd80-734b-11e9-8686-67176e3125f9.jpg)
![IMG_20190510_171524](https://user-images.githubusercontent.com/38762425/57539644-362a6400-734b-11e9-94c2-5a7cf22f7033.jpg)

**Comment by leptun** [comment]
Please post the gcode as I want to test this on my mk3

**Comment by Swesen** [comment]
The one that say hidef is the high face count one that both fails on and the other one is where one fine one fail gcode. I took a video on this problem also, will upload shortly.
[Gangjarn v2_0.2mm_PET_MK3SMMU2S (2).zip](https://github.com/prusa3d/Prusa-Firmware/files/3167389/Gangjarn.v2_0.2mm_PET_MK3SMMU2S.2.zip)

**Comment by Swesen** [comment]
Recorded from after purge line but I zoom in at the problem at around 1 min https://youtu.be/VxURmfWbbfs

**Comment by Swesen** [comment]
This seems like some random firmware/EEPROM corruption that happened on my einsy board. After flashing the same firmware(the same file that I uploaded 1 month ago when I upgraded my MK3 to MK3S with MMU2S) that had the problem it now prints these files without problem...
