### ISSUE TITLE
MM3S/MMU2S Under-extrusion upon leaving wipe tower

### ISSUE THREAD

**Issue by cjbaar** [prusa3d/Prusa-Firmware#1816]
I have had this issue since I first received the MMU2 last year. No recent software/firmware updates seem to have addressed it. Whenever the printer goes through the purge process after changing filaments, it either over-retracts or under-primes leaving the wipe tower, and the first extrusion is significantly low (several mm). This happens on every tool change, regardless of filament or layer.

Is there a setting for this in Slic3r PE? If so, I am not seeing it. There seem to relatively few settings for wipe tower speed, flow, etc.

**Comment by cjbaar** [comment]
This isn't the greatest picture, but you can see where the first few items are under-extruded.
![IMG_3900](https://user-images.githubusercontent.com/1058385/57565018-f37c8200-7372-11e9-9440-2078a5041c8d.jpeg)

**Comment by cjbaar** [comment]
Another (mediocre) pic after the print finished. You can see the poor extrusion on the first white and dark grey pixels. There are around 6,500 pixels in this print (1.8mm^2), and the first off the wipe tower are the only ones that look like this.
![57927725545__732719C2-5137-4378-9C99-CDAD4E2AFC7F](https://user-images.githubusercontent.com/1058385/57571051-387dd400-73c6-11e9-8034-5630679040dd.jpeg)

**Comment by cjbaar** [comment]
Another example I see on pretty much every print. This is the first layer, wipe tower on the right, and you can see the gap in the skirt (about 8mm).
![IMG_3911](https://user-images.githubusercontent.com/1058385/57668313-2ec1bf80-75c4-11e9-8b23-ffae3f50d035.jpeg)

**Comment by cjbaar** [comment]
2nd layer, first tool change, same under-extrusion
![IMG_3914](https://user-images.githubusercontent.com/1058385/57669231-55cdc080-75c7-11e9-9199-0418329bfc03.jpeg)

**Comment by bynnek** [comment]
I've seen this issue as well and just assumed I had something set wrong.  Interesting to see someone else with the same problem.

**Comment by MalikDrako** [comment]
I am guessing this is an issue with PrusaSlicer, since I am running into it when using a Palette 2 instead of MMU2S

![IMG_0149e](https://user-images.githubusercontent.com/12055311/63726930-8b638600-c813-11e9-8faa-6dc736bfc7a7.jpg)

**Comment by cjbaar** [comment]
You are correct @MalikDrako. I even knew that when I created this, but clearly posted it in the wrong place. Thanks for the input.

**Comment by cjbaar** [comment]
I re-opened this in the slicer forums:
https://github.com/prusa3d/PrusaSlicer/issues/2834
