### ISSUE TITLE
3.7.1 Language Issue?

### ISSUE THREAD

**Issue by Crazy-Crosshair** [prusa3d/Prusa-Firmware#1831]
I have a problem on My MK3 (non S) with 3.7.1 i am in a Loop when the printer asks me to choose a Language. If i choose German he will ask me again and again. If i choose English everything is fine.

**Comment by leptun** [comment]
Try factory resetting the printer deleting all settings

Link: https://help.prusa3d.com/article/SYvbQ66IXF-factory-reset

**Comment by Crazy-Crosshair** [comment]
I resetted the Language. Same Problem. 

Point to Deutsch  -> Copy selected language? -> Yes - Original Prusa i3 Prusa Research Language update... -> List of Languages to choose frome

**Comment by leptun** [comment]
Try reflashing 3.7.1 and if it still fails try 3.7.0. Also is this compiled by you or downloaded from the releases?

**Comment by Crazy-Crosshair** [comment]
It is right from your Homepage (https://www.prusa3d.de/treiber/)

**Comment by Crazy-Crosshair** [comment]
Reflashing to 3.7.1 worked for me!

**Comment by leptun** [comment]
Great to hear.
