### ISSUE TITLE
Added Modifier does not affect layer height

### ISSUE THREAD

**Issue by Sn1ckerson** [prusa3d/Prusa-Firmware#1840]
I tried to use a modifier (slab) to adjust the layer height of my print.
My part is printed in .2mm however I wanted to decrease the layer height between z=1mm and z=3mm to increase the details in that area.
After positioning the modifier, I added "Layers and Perimeters and adjusted the layer height to 0.1 mm. Sliced it and everything stays 0.2 mm...

**Comment by michalxfanta** [comment]
This is probably not a firmware issue but a slicer.

**Comment by AikiAviator** [comment]
:-) done. thanks.
