### ISSUE TITLE
Feature Request: Allow for extruder control when MMU load/unload fails

### ISSUE THREAD

**Issue by jzkmath** [prusa3d/Prusa-Firmware#1841]
Sometimes when I have a load/unload failure in my MMU2S, the filament is stuck in the extruder. It would be nice if I had a few more options to correct failures when this happens, such as performing an unload with the extruder again, or being able to disable the holding torque on the extruder. 
Considering how good the bondtech gears are at holding filament, forcing the filament out normally results in the filament breaking.

**Comment by watersong** [comment]
Just to add to this ....

 I'd like to recommend a change to the code that resumes printing AFTER a MMU load issue is repaired.

Currently after repair it moves to swipe tower, loads filament, creates a blob on the tower, then resumes. The blob kills most any chance of completing the print as it hardens and blocks the print head or knocks the tower off.

Instead:
1 - repair the mmu load issue at the mmu
2 - press the prusa button and center print head above height it stopped, load and extrude
3 - confirm and clean up extrusion, press prusa button a 2nd time to move to swipe tower and resume printing
![2019-05-16 09 16 30](https://user-images.githubusercontent.com/8405451/57883362-34492080-77e3-11e9-9a23-b3bf2d308546.jpg)
