### ISSUE TITLE
MMU2S not releasing filament in single mode

### ISSUE THREAD

**Issue by OskarLeirvaag** [prusa3d/Prusa-Firmware#1847]
After loading filament to nozzle in single-mode the idler will not disengage and creates a lot of traction for the extruder.

Extruder visualizer on the MMU2S extruder motor will shot it spinning while printing (jerking) in single mode.

Setup:
Octoprint, v1.3.11
MK3S, v3.7.1
MMU2S, v3.7.1

**Comment by mkbel** [comment]
Can you attach gcode please? Do you use latest Slic3r? (preferred choose filament question commands has changed since first MMUv2 release) Do you start your print after MMU is detected by printer? (F? is shown on status screen)

**Comment by OskarLeirvaag** [comment]
Apparently same issue as with #1846, sorry about that
