### ISSUE TITLE
Elapsed time is much too high after print

### ISSUE THREAD

**Issue by PxT** [prusa3d/Prusa-Firmware#1849]
See photo at https://i.imgur.com/XUooqti.jpg.  
This print took about 18 hours, but printer thinks it was 1143 hours.
Printer: MK3/S + MMU2/S. 

Gcode is the MMU2S version from https://www.prusaprinters.org/prints/168-universal-auto-rewind-spool-holder-mm/files

**Comment by PatitoPatozo** [comment]
Have seen this too with the standard 2-color Benchy. "1170 hours 30 minute"

Print was successful (with a few loading issues - that were easy to solve).

![IMG_0580](https://user-images.githubusercontent.com/52384834/60401799-c97f5900-9b86-11e9-9250-07e65dd57c16.JPG)

**Comment by fdurrer** [comment]
I've observed this too on certain MMU prints with user interaction. As it happens only occasionally I think it depends in the type of user interaction but I have to investigate further when it happens next time.

**Comment by jsilva-iii** [comment]
I have a Mk2.5S+MMU2S  and have observed exactly the same - I have 10-20 Load failures and 2 MMU failures
![IMG_20190718_065934](https://user-images.githubusercontent.com/2212640/61583526-f62fec00-ab06-11e9-9164-24c4c668b8e1.jpg)

**Comment by jsilva-iii** [comment]
I have just looked at my overall stats and that is also messed up 
![MVIMG_20190721_104601](https://user-images.githubusercontent.com/2212640/61593608-a6592f80-abaf-11e9-8be8-c973f03f6146.jpg)

**Comment by jsilva-iii** [comment]
I have a MK2.5s + MMU2S FW 3.72 -  this is a new Rambo as of 24 June.

**Comment by uniacke1** [comment]
Ditto, I've observed it when prints have been paused in some form or another several times, manual pause included. I'd paused it to inspect if a layer shift was recoverable.
Note I've seen it on a standard Mk3 without an MMU as well.

**Comment by vintagepc** [comment]
Still present in 3.8.0-RC1. Print was interrupted/paused by "MMU needs attention" and is actually ~6h 

![IMG_0003](https://user-images.githubusercontent.com/53943260/63217084-992b5400-c10d-11e9-8053-44b8d77363bc.JPG)

**Comment by Kadah** [comment]
Looks like an integer underflow.
