### ISSUE TITLE
3.7.1 Firmware for MMU2/MK3S Single Extruder Print not purging filament anymore

### ISSUE THREAD

**Issue by TimothyGold** [prusa3d/Prusa-Firmware#1851]
I  have upgraded both MK3S firmware to 3.7.1 and am also using the new Prusa Slicer RC and now MMU2 Single filament prints no longer print a purge line and will continue the print missing part of the first layer.  I don't know for sure if this a Slicer issue or firmware issue.  I checked the start G-Code in the slicer and it is the same as the old slicer so I don't know why it is no longer working.  This happens even if I load filament to nozzle.  Just doesn't push enough filament to the nozzle.

**Comment by OskarLeirvaag** [comment]
Tested now with both octoprint and print-from-sd in singlemode, this is not an issue I experience.
FW 3.7.1
MK3S MMU2S
Octoprint 1.3.11
PrusaSlicer 2.0.0 + win64

Printer purges dropp, skips about 3cm then purges to end and back.

**Comment by TimothyGold** [comment]
The only thing I changed in the config after updating to 3.7.1 was to enable the filament ir sensor in all prints.  The sensor is obviously used in all MMu2 prints.  I will try a print tonight with this disabled on a single print to see if I can get it to act like the previous firmware.  Not sure what has changed other than this....

**Comment by OskarLeirvaag** [comment]
Ran tests with both IR and F.I.N.D.A working, both crash detection and filament-detection enabled.

**Comment by TimothyGold** [comment]
I do have a little longer PTFE tube from MMU2 to the extruder.  Do I need to re-calibrate this?  I thought that this didn't matter anymore.  I tried 5 different prints last night trying different methods loading first to the nozzle and then letting it load from mmu2.  The filament looks like it loads and I can see the IR Sensor sense the filament going to 1 then it puts the filament in and then retracts it a little just like it did in the old firmware but when it starts the purge the lines don't show up and the border circle does not show up and only starts to purge filament after it is in the print.  I guess I will also try to downgrade tonight as well to see if i am successful again...

**Comment by OskarLeirvaag** [comment]
Yes, yes you probbably should.

Directly from the MMU2S Handbook:
## 7.4 Individual filament calibration
Information for advanced MMU2 users, who already performed filament
length calibration before: although you can enter the service menu and run
Individual filament calibration procedure, there is no reason to do it anymore.
The length of the filament is automatically controlled thanks to the new IR
filament sensor.
The only reason to run the calibration is in case you have changed the length of the
front PTFE tube between the extruder and the MMU2S unit. With the calibration, the
filament loading will be faster. In that case, please refer to this manual:
https://manual.prusa3d.com/Guide/Service+menu+-+Individual+Filament+Calibration/842

## Source
[source](https://prusa3d.com/downloads/manual/prusa3d_manual_mmu2s_eng_1_00.pdf?2)

**Comment by gudnimg** [comment]
Adding this to the 3.13 milestone as a reminder to close this issue.
