### ISSUE TITLE
Feature Request: Pause *at layer N*

### ISSUE THREAD

**Issue by TickTock-** [prusa3d/Prusa-Firmware#1854]
Yes, this can be done many ways in the gcode but it would be very useful to be able to insert a pause after a long print has already started.  Maybe you had to adjust the flow for the first layer and want to change it back before the the next layer or you are running out of filament and would rather make the filament change right at a layer boundary.  Maybe have the pause feature go to a sub-menu with "Pause Now", "Pause at next layer", "Pause at layer N", "Pause at height Z".  All three new options aren't necessary but if I had to choose one, I would request the "Pause at height Z"

**Comment by michalxfanta** [comment]
Thank you for your interesting idea, we will add it to our backlog.
