### ISSUE TITLE
minor menu bug during print FW 3.7.1

### ISSUE THREAD

**Issue by OskarLeirvaag** [prusa3d/Prusa-Firmware#1858]
# Bug
A minor bug causes the menu-element "Support" to be duplicated sometimes in the main manu during printing from SD. Has though not been tested outside of printing.

![20190522_133017](https://user-images.githubusercontent.com/9082783/58172383-b7adba80-7c98-11e9-9a9a-aadcee8e041a.jpg)

## Replicate
To replicate the bug you might need to scroll upp and down in the printing menu while a print is running. If you scroll again it will fix itself. Replicated 3 times during the same print before reporting.

## Setup
 * FW 3.7.1
 * MK3S and MMU2S
 * PrusaSlicer 2.0.0+win64

## Files
ONly included first 5% of file due to copyright of the owner requesting item

[the_model_used.gcode.txt](https://github.com/prusa3d/Prusa-Firmware/files/3207193/the_model_used.gcode.txt)

**Comment by Prusa-Support** [comment]
Hello! I am sorry for the late response to this thread. Is this issue still there, or has it been solved in the meantime with newer FW versions? Let me know, if this is still occurring we can look into it. 

Alessandro Pantaleo 
Prusa Research
