### ISSUE TITLE
Add automatic peg/slot options to cut mode

### ISSUE THREAD

**Issue by 3dnoobie** [prusa3d/Prusa-Firmware#1865]
The new PrusaSlicer looks great!

One feature I've always wanted was for when cutting a model, to have it automatically create a peg and slot, so you can easily align/join the cut pieces. I know you can do it in modeling software, but that becomes more difficult when you're using thingiverse models or scaling things, which usually happens at print time, not modeling time.

I think appropriate options would be as follows:

1. Regular flat planar cutting
2. Adjust cutting plane angle (xyz)
3. Adjust peg/slot extrusion shape (circle, square, triangle, hexagon, arbitrary poly)
4. Adjust peg/slot extrusion depth (maybe independently, in the event you wanted to have extra space in the slot for another part or something)
5. Adjust peg/slot extrusion angle (relative to cutting plane, imagine oblique cutting plane and 0 degree z extrusion. 
6. Adjust peg/slot orientation (is peg on top or bottom of slice?)
7. Peg/slot number (1,2,3)
8. Peg/slot location in cutting plane ( adjustable relative to cutting plane i.e. 3 pegs in triangle, 2 pegs side by side)
9. Joiner type (edge locked jigsaw/dovetail, central peg/slot, edge locked peg/slot)

**Comment by leptun** [comment]
It is a nice feature, but you did not post this in the right place.

For slicer related issues and feature request please use https://github.com/prusa3d/PrusaSlicer
