### ISSUE TITLE
SL1 - changing host name crashes firmware

### ISSUE THREAD

**Issue by mylife4aiurr** [prusa3d/Prusa-Firmware#1868]
Didnt see a SL1 specific github address

Tried to change hostname from "prusa64-sl1" to something else and firmware crashed

firmware version 1.0.5
![20190523_170702 (1)](https://user-images.githubusercontent.com/31583073/58290143-ac38bd00-7d86-11e9-9b27-03faa18b92ff.jpg)

**Comment by filipkotoucek** [comment]
Same as https://github.com/prusa3d/Prusa-Firmware/issues/1872#issuecomment-496232149

**Comment by filipkotoucek** [comment]
This issue was fixed in newer versions. At the moment 1.1.1 is current stable version. You can updat ether via net update or download update bundle file here: https://www.prusa3d.com/drivers/. @michalxfanta please close this issue.
