### ISSUE TITLE
3.7.1 Z on readout showing "?"

### ISSUE THREAD

**Issue by Danafra** [prusa3d/Prusa-Firmware#1878]
As the title says, the readout on the LCD in the Z field always shows a question mark. This is a MK2.5S.
![20190527_131807](https://user-images.githubusercontent.com/32659658/58432776-16e94180-8082-11e9-8216-6b559f4bae64.jpg)

**Comment by Panayiotis-git** [comment]
Check this https://github.com/prusa3d/Prusa-Firmware/issues/1250

You have to follow carefully the build instructions.

**Comment by Danafra** [comment]
Ahh, I was having an issue locating the correct platform.txt file.  I didn't have one located at either location as indicated by the readme file.  I'll revisit this and make sure I edit the correct file.
Thanks!

**Comment by leptun** [comment]
If you fixed the problem, please close this issue.
