### ISSUE TITLE
Do not show update dialog when printing remotely

### ISSUE THREAD

**Issue by jenda122** [prusa3d/Prusa-Firmware#1892]
Hi,
it would be nice do disable the _New firmware version available_ when the job is submitted remotely e.g. via OctoPrint (or set some sane timeout for it), because now you need to press the knob, but the printer may be on the other end of the city :) (yeah, I have fixed it by flashing the new firmware remotely with avrdude, but our other users are not that tech-savvy, they just want to click "print" in OctoPrint...)

**Comment by michalxfanta** [comment]
We planning add a timeout to this announcement about new FW version at 3.8.0 version.

**Comment by leptun** [comment]
Feature was added. Please close the issue.
