### ISSUE TITLE
Wrong "Total filament" statistics

### ISSUE THREAD

**Issue by pboschi** [prusa3d/Prusa-Firmware#19]
General statistics report 128km filament usage after 24h of use...
Statistics during print are instead working correctly.

**Comment by cahe** [comment]
I can confirm this. Was using 3.0.7 or 3.0.6 firmware at the time.

**Comment by PavelSindler** [comment]
Thank you for information. It will be fixed in 3.0.10

**Comment by PavelSindler** [comment]
The issue has been fixed in since commit https://github.com/prusa3d/Prusa-Firmware/commit/fcce374a14b94ae6dc01466d9262a92d3ae1bf50
