### ISSUE TITLE
Feature Request: Z-height storage for power coated and flat sheet

### ISSUE THREAD

**Issue by mrcg** [prusa3d/Prusa-Firmware#1910]
I have the flat and powder coated stell sheat.
Both require different z-height offset values.
I would like to have the feature to store different z-heigt offset values for e.g. flat and powder coated sheet. It would be fine to have it named like sheet 1, sheet 2, sheet 3.
But also powder coated sheet and flat sheet as naming would be fine.

Thanks for considering this feature request.

**Comment by michalxfanta** [comment]
This new feature will be in next 3.8.0 firmware version.
