### ISSUE TITLE
Feature request - purge after pause

### ISSUE THREAD

**Issue by ohthetrees** [prusa3d/Prusa-Firmware#1916]
A little molten filament inevitably dribbles out during a pause. This blob can be a big problem when resumed, and has caused me failed prints. I suggest that after a print is resumed, that another purge be performed.

**Comment by ManuGithubSteam** [comment]
Hi

This can be problematic: Imagine you print something big on the build plate and the extruder can not reach down to the front anymore without touching the print. Like the cables your scrap over that part etc.

However, Purge into infill of the part would be possible i think but im not sure it is implemented yet for machines without mmu2s.

**Comment by leptun** [comment]
Purging into infill is not possible since it is something the slicer decides, not the firmware.

**Comment by ohthetrees** [comment]
Good point. But it could still purge into the air like it does with an M600 filament change.

**Comment by michalxfanta** [comment]
Thank you for your interesting idea, we will add it to our backlog.
