### ISSUE TITLE
DE translation bug(s) FW 3.7.2 RC1

### ISSUE THREAD

**Issue by jendit** [prusa3d/Prusa-Firmware#1921]
The German translation when accessing the print by SD card menu shows "Hauptmenue" at the top to get "Back" => OK
If accessing the same menu automatically by inserting an SD-Card, it shows "Back" instead (see picture).
![IMG_20190615_100055](https://user-images.githubusercontent.com/23548779/59548896-82258580-8f55-11e9-8639-4557e9be9305.jpg)

The statistics print time calculation shows d:h:m. Other than the additional empty space before m (see picture), the German translation would be t:s:m (days = Tage, hours = Stunden, minutes = Minuten).
![IMG_20190615_095407](https://user-images.githubusercontent.com/23548779/59548923-d466a680-8f55-11e9-8b76-70b43cb4cdb0.jpg)

**Comment by michalxfanta** [comment]
Thanks for reporting bugs in German translation.
