### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by lokus77** [prusa3d/Prusa-Firmware#1926]
Would be nice (and maybe unique feature, does not exist in any slicer) if the user could **paint in 3d view the seam position**  (across Z ). So user can decide where goes seam in each part of a model. Would be something like variable layer height editor.  Not sure if is easy to implement. 

Excelent Slicer, nice job prusa development team!

**Comment by leptun** [comment]
I agree this would be a nice feature, but this is the wrong place to post it.

This is the repository for printer firmware. For anything slicer related, use https://github.com/prusa3d/PrusaSlicer

**Comment by lokus77** [comment]
sorry!! sure!!  gonna close or delete this one! 

Posted in slicer repo: https://github.com/prusa3d/PrusaSlicer/issues/2527
