### ISSUE TITLE
Firmware accepts extreme temperature values 

### ISSUE THREAD

**Issue by uchobby** [prusa3d/Prusa-Firmware#1930]
Prusa V3.7.1-2266
Gcode command temperature to 1500 degrees C.  The temperature begins to rise but fails a check to report "Preheat Error" stopping the print.  There are actually two firmware defects here.
1) "Preheat Error" is deceptive, sending the user into a bad troubleshooting path.  The error would be far better if it were more like "Temp Setting High" with a unique description.  It seems likely that a user could accidentally request a temperature high enough to cause serious damage to the extruder or worse.

In my case, I accidentally typed 2400 when I meant to type 240C into the "other layers" temp setting on a filament profile.  The printer failed with the "Preheat Error" after successfully printing the first layer of the print.

2) Seems the printer settings should include a max temperature that can be set based on the extruder limits, also the same for the bed.  Anytime these limits are exceeded with a command, the print fails with the "Temp Setting High" type error.
In my case the printer did start raising the extruder temp, the failure occurred because a temp check found the temp was not changing fast enough as a ratio to the target.
If I had put in 500C I might have destroyed my extruder or worse.

Related to this ticket originally created on the Slicer repo.
https://github.com/prusa3d/PrusaSlicer/issues/2525

**Comment by michalxfanta** [comment]
Hi, you are right, now when the printer processing GCODE with the request to 500 C the printer start heating. But at 300C heating stops with error Max temp. The check for unreachable temperature we will add in some of the future releases.
