### ISSUE TITLE
load to nozzle failure can result in blank LCD

### ISSUE THREAD

**Issue by PxT** [prusa3d/Prusa-Firmware#1941]
Machine:  MK3S + MMU2S
Firmware: 3.7.1-2266
MMU firmware: 1.0.5-297

Steps to reproduce:
* Preheat
* Load to nozzle -> Select filament
* Filament load fails for some reason (IR sensor doesn't see it, or filament doesn't engage gears properly, any reason at all for the purposes of this bug).  MMU2 goes into fail state with amber light flashing as expected
* Push 3rd button on MMU to retry the load
* LCD goes completely blank
Pushing the selector button takes the printer back to the main menu, so this is not a critical problem, but I think it is a bug.

**Comment by fopeczek** [comment]
I have similar bug.
But in my printer the LCD is all right.

**Comment by fopeczek** [comment]
I think to repair this bug you must somehow move the chimney with IR sensor...
![the](https://user-images.githubusercontent.com/46483193/75779867-bd254e80-5d5a-11ea-97f9-b6d41c8e08dd.png)
or edit the chimney to allow him to move freely on x axis.

**Comment by gudnimg** [comment]
Let's close this issue after 3.13.0 is released.

**Comment by gudnimg** [comment]
Closing as this is now resolved with FW 3.13.0 and MMU FW 3.0.0 :)
