### ISSUE TITLE
Load Filament 256 1st Layer Calibration in Setup Wizard

### ISSUE THREAD

**Issue by jsilva-iii** [prusa3d/Prusa-Firmware#1949]
MK2.5S+MMU2S - FW 3.7.2

After bed calibration in the setup wizard, one is prompted to load filament 1 and press ok - the mmu2S goes through it's initialization steps, then selector goes to the 5th filament and a message appears on the screen "Load filament 256" and if you inset filament in the 5th guide it won't load
![IMG_20190627_190847](https://user-images.githubusercontent.com/2212640/60309254-e57ec280-991a-11e9-8c50-b8e3842e347e.jpg)

**Comment by anagingcompiler** [comment]
This would sometimes happen with MK3S+MMU2S - FW 3.7.1 as well.

**Comment by karthonic** [comment]
Just got this issue myself, just flashed to FW 3.7.2

(All the while I'm trying to solve another issue entirely.)

**Comment by crioux** [comment]
Also having this issue wit FW3.7.2. It happens specifically if you do the calibration wizard and then when it asks you if you have loaded filament 1, if you say 'no' it prompts to load filament 256.

**Comment by AndyNewlands** [comment]
I have the exact same issue with MK3S FW 3.7.2-2363 & MMU2S FW 1.0.6-372

Also, if you persevere will the 5th guide, after a reboot, and get to it accept there's filament present, it will eventually start trying to pull filament for the Z-calibration from hole number ONE! (in which there's no filament.  Infuriating ;-)

**Comment by gudnimg** [comment]
Let's close this issue when 3.13 is released 👍

**Comment by gudnimg** [comment]
Closing as this is now resolved with FW 3.13.0 and MMU FW 3.0.0 :)
