### ISSUE TITLE
3.7.2 fan test Sunon

### ISSUE THREAD

**Issue by vvv850** [prusa3d/Prusa-Firmware#1956]
Was wondering what would happen if I flash this version and at the same time was using a Sunon fan instead of the Noctua during the self test phase. Thanks

**Comment by vertigo235** [comment]
If the auto test doesn't work it asks you to verify which fans are running like it use to.

**Comment by tbedore** [comment]
With a sunon fan it is still the same, just has higher RPM's the printer won't care about it.  Still senses the change in RPM whether or not it's Noctua.

**Comment by michalxfanta** [comment]
It's exactly like @vertigo235 said.
