### ISSUE TITLE
check if gcode file is complete 

### ISSUE THREAD

**Issue by Toifur** [prusa3d/Prusa-Firmware#196]
It would be great if the gcode will be checked for completeness and integrity before the actual print starts.

**Comment by GurliGebis** [comment]
What would define it as complete?

**Comment by Toifur** [comment]
Maybe an extra line of code in Slic3er PE generated files or a  "M84 ; disable motors"  in general.

It could help to avoid half done prints caused by an overhasty removed SD Card.

**Comment by GurliGebis** [comment]
But that would require all other slicers to do the same thing, and force people to end their gcode like that (the stop gcode can be changed by the user).

**Comment by probonopd** [comment]
This sounds to me like a generic feature request for upstream Marlin in general and not Prusa specific. What could be done is to check whether the final position of the extruder is further away from the last position where extruding was done, and show a warning if the two are too close or identical. I am not sure how relevant the use case is and whether it would justify the effort.

Do you often have incomplete files @Toifur and how do these happen?

**Comment by PavelSindler** [comment]
Hello, yes I am currently working on it and it should be in next release. I am checking M84 gcode in end section of file, which in my opinion should work with most slicers and it is probably better approach then adding some prusa specific gcode to end section. If file is not complete, there will be some warning message, but could continue anyway. Incomplete files are quite frequent problem. Usually user removes SD card during slicing.

**Comment by bubnikv** [comment]
This has been implemented long ago.
