### ISSUE TITLE
Fan naming misleading

### ISSUE THREAD

**Issue by haarp** [prusa3d/Prusa-Firmware#1960]
According to the firmware, the printer has two fans. "Nozzle fan" and "Print fan". This is misleading. One might expect the "nozzle" fan to be the one pointing at the nozzle, but it's precisely not that one. "Part" fan is also not ideal - the user might wonder, is it the fan cooling the printed part, or the printer's parts?

I'd suggest calling the nozzle fan: Coldend fan, Leftside fan, Heatsink fan, or a better word I couldn't think of right now.

Cheers!

**Comment by tkircher** [comment]
At the very least, the naming should be consistent with the hardware naming conventions - hotend fan and print fan. The firmware messages also use extruder fan and nozzle fan in different places to refer to the same thing. So it's not even consistent.
