### ISSUE TITLE
MK2.5/S Firmware 3.7.2 infinite unload/load loop when printing

### ISSUE THREAD

**Issue by tjhawkey** [prusa3d/Prusa-Firmware#1964]
My printer gets stuck in an infinite unload/load cycle when trying to print.
It preheats, mesh bed levels, but then unloads the filament before printing. 
When I unload and re-load, it goes through the mesh bed leveling and asks for an unload again.
The built in first layer calibration works fine.

**Comment by leptun** [comment]
Please post the gcode which generates the problem.

**Comment by leptun** [comment]
Also test that the filament sensor is working by going to “Main menu”-> “Support”->”Sensor info”. Check with the filament unloaded that the value changes corectly when inserting the tip of the filament in the extruder. If it shows a constant 0, then it is always senses as no filament present, hence the filament unload and reload.

**Comment by tjhawkey** [comment]
Du-oh. The filament sensor isn't working. I'll track that down.
But, it would seem that if you have the sensor enabled and you say that the filament is loaded OK, that the firmware would point out the mis-match with the sensor state.
Thanks.

EDIT--yes, the sensor was plugged in one pin off (hard to see behind the other wires).
All works now, but I'd still see if there's a way to flag a disconnect between "filament loaded" and no filament sensed.

**Comment by barthap** [comment]
I had the same issue, filmament sensor plug was loose.
