### ISSUE TITLE
Not possible to cancel live Z calibration once starts.

### ISSUE THREAD

**Issue by maximlevitsky** [prusa3d/Prusa-Firmware#1968]
Like the tile says, if you start a live Z calibration, you can't stop it, unless you reset the printer.

**Comment by leptun** [comment]
Are you refering to “mesh bed leveling” at the begining of a print or the “First layer cal.”?

**Comment by maximlevitsky** [comment]
First layer cal.

**Comment by mws-rmain** [comment]
I have experienced the same issue.
Pressing the knob dumps you to the menu structure, but the calibration routine continues.
It would be great if the 'pause / stop' etc menu could be displayed instead to retain control.
