### ISSUE TITLE
If SD card is removed during a print printer just stops movements and sits there.

### ISSUE THREAD

**Issue by maximlevitsky** [prusa3d/Prusa-Firmware#1970]
As the title says. If happens during the first layer, that can damage the print surface.
I triggered that on purpose, but didn't wait that much because of the fear of damaging the print surface.

**Comment by theaquarium** [comment]
This is supposed to happen. During a print, the printer reads gcode directly from the file on the SD. I don't believe that the printer has any RAM that can be used to store the gcode, so this is most likely fixable.

**Comment by maximlevitsky** [comment]
In a sense that printer can't continue printing - sure!
But the printer should abort the print and raise print head instead of sitting here and heating up the PEI.
