### ISSUE TITLE
Gcode M190 doesn't appear to wait when bed it hotter that the target

### ISSUE THREAD

**Issue by maximlevitsky** [prusa3d/Prusa-Firmware#1973]
'M190 S[first_layer_bed_temperature]' appears not to wait for the bed temp if it is already higher that given value. Don't know if this is supposed to happen, and even if so it would be very nice to have a gcode that waits for specific bed temp as opposed to it beeing above the given value.

**Comment by haarp** [comment]
http://marlinfw.org/docs/gcode/M190.html

Using S instructs the printer to not wait when the temperature already is higher. You'll want to use R

**Comment by maximlevitsky** [comment]
Oh sorry!
