### ISSUE TITLE
FW3.7.1 and 3.7.2: Unable to resume print while paused in intro line

### ISSUE THREAD

**Issue by ochm** [prusa3d/Prusa-Firmware#1977]
FW3.7.1 
I paused print while executed intro line. After resume print didn't continue, no movement...

**Comment by leptun** [comment]
Is this something that can be repeated? Aka did it happen more than once?

**Comment by ochm** [comment]
It happened to me one time, i had no reason to do it again, but i can test it, after 3 days, i have looong printing progress.

**Comment by leptun** [comment]
I don't print from the sd card so I didn't use the built-in pause function. Also my print queue is full for now. Can't help you with testing, but can ask you some more things.

Where did you pause the print exactly?
Where did the movements stop?
Can you post what is reported by the printer on the serial? (That is if you can recreate the scenario). Just use arduino ide serial monitor and connect over usb.
Are you using a modified start gcode script or the built-in defaults in PrusaSlicer?

**Comment by ochm** [comment]
I can reproduce it as many times as i want. Now tested at 3.7.2 The start gcode is little bit modified:
M115 U3.7.2 ; tell printer latest fw version
M83  ; extruder relative mode
G28 W ; home all without mesh bed level
G1 Z3
G1 X50 Y50 F5000
M140 S[first_layer_bed_temperature] ; set bed temp
M109 S160 ; Set extruder temp before bed level
M190 S[first_layer_bed_temperature] ; wait for bed temp
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
M109 S[first_layer_temperature] ; wait for extruder temp
M300 S440 P25
M221 S100 ; Set flow to 100
G92 E0.0
G1 X50.0 E10.0  F800.0 ; intro thin line
G1 X100.0 E6.0  F800.0 ; intro thiner line
G92 E0.0
M221 S{if layer_height<0.075}100{else}95{endif}

I do pause somewhere between intro thin and thiner line.
Extruder moves up, bed still heat and moves front, hotend stops heating. OK.
After resume hotend heats to working temperature, extruder and bed moves to paused position, and...
nothing more. Bed is on desired temperature, hotend is on desired temperature, but no moves, no print.
OK, time to stop print. Selected from menu, display shows Print aborted, but, the bed heating is stopped, but nothing more! Hotend is still heated, and not moved up. The only way to stop printing is to press Reset button.
I try it two times with the same behavior, I made some video (it is too big to upload) 
try do download https://drive.google.com/open?id=1XhGJZq9711LuVdObFxT5XJ7uks2sOGR7
Serial log (attached), whole gcode attached.
[putty.zip](https://github.com/prusa3d/Prusa-Firmware/files/3413291/putty.zip)
[Redukce2_0.2mm_PETG.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/3413322/Redukce2_0.2mm_PETG.gcode.zip)

**Comment by wavexx** [comment]
There was a long list of pause/resume fixes which is now available in the 3.9.0 (currently in beta). More likely PR which could have fixed this is #2274. Could you give it a shot?

**Comment by gudnimg** [comment]
As this issue is likely stale and no longer an issue in FW 3.12 at this point I think it’s OK to close the Github issue.

If there is still an issue I think its better to have a new Github issue opened.  We are not going to debug an old FW like 3.7.2 :)
