### ISSUE TITLE
Can not compile current version

### ISSUE THREAD

**Issue by CdRsKuLL** [prusa3d/Prusa-Firmware#1994]
Hi, I've been trying to compile the current version. The 3.7.1 compiles and works fine. Tried the 3.7.2 and I'm getting the following error. I have copied mk3 varient over and renamed it Configuration_prusa but not changed anything else.

```
wiring.c.o (symbol from plugin): In function `__vector_23':

(.text+0x0): multiple definition of `__vector_23'

sketch\heatbed_pwm.cpp.o (symbol from plugin):(.text+0x0): first defined here

c:/users/cdrsk/prusa/arduino-1.8.5/hardware/tools/avr/bin/../lib/gcc/avr/4.9.2/../../../../avr/bin/ld.exe: Disabling relaxation: it will not work with multiple definitions

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board RAMBo. 
```
Same Arduino (1.8.5) compiles 3.7.1 fine, errors on this version.  Any ideas?

**Comment by deliopoulos** [comment]
It's seems that you are using Windows. PF-build.sh for windows is broken. You can try custom [PF-build.sh](https://github.com/prusa3d/Prusa-Firmware/files/3389609/PF-build.zip) or patch arduino 1.8.5 with files from [PF-build-env](https://github.com/deliopoulos/PF-build-env)

**Comment by CdRsKuLL** [comment]
Thanks deliopoulos that sorted it. 

Just for others. I clicked on the PF-build-env-Win and downloaded the files. I then copied all the files in the hardware folder into the hardware folder in C:\Program Files (x86)\Arduino\hardware  .. I then selected the new Prusa-rambo board from the arduino menu instead of the rambo board I had installed before.  :-)

**Comment by GilesBathgate** [comment]
The cause is the redefinition of TIMER0_OVF_vect in the PF-build-env this is removed from wiring.c as follows

```diff
--- ~/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.c	2019-09-20 13:48:17.000000000 +0100
+++ PF-build-env-1.0.6/1.8.5-1.0.3-linux-64/portable/packages/PrusaResearch/hardware/avr/1.0.3/cores/prusa_einsy_rambo/wiring.c	2019-12-17 11:15:16.000000000 +0000
@@ -37,9 +37,15 @@
 
 volatile unsigned long timer0_overflow_count = 0;
 volatile unsigned long timer0_millis = 0;
-static unsigned char timer0_fract = 0;
+//static unsigned char timer0_fract = 0;
 
-#if defined(TIM0_OVF_vect)
+// As of Prusa Firmware 3.8 we need to disable the Arduino's hardcoded TIMER0_OVF_vect
+// to be able to replace it with our own implementation for HW PWM heatbed control.
+// That's also the one and only reason we need to define our own "board"
+// for the Arduino IDE.
+#if 0
+
+#if defined(__AVR_ATtiny24__) || defined(__AVR_ATtiny44__) || defined(__AVR_ATtiny84__)
 ISR(TIM0_OVF_vect)
 #else
 ISR(TIMER0_OVF_vect)
@@ -62,6 +68,8 @@
 	timer0_overflow_count++;
 }
 
+#endif
+
 unsigned long millis()
 {
 	unsigned long m;

```
