### ISSUE TITLE
"Smoother prints of diagonal lines" not working in 3.0.9

### ISSUE THREAD

**Issue by Ixyam** [prusa3d/Prusa-Firmware#20]
After upgrading to 3.0.9, medium/large surfaces show "waves" on diagonal fillings, after downgrading to 3.0.8 those waves dissapear automatically, seems like 3.0.9 modifications were performed over an older version than 3.0.8.

I attached 2 images that show same surface printing: with 3.0.9 (waves) and with 3.0.8 (perfect)

![fw3 0 8](https://cloud.githubusercontent.com/assets/24275741/20761905/cafaf774-b724-11e6-803a-9ef6975c96c5.jpg)
![fw3 0 9](https://cloud.githubusercontent.com/assets/24275741/20761907/cb117ed6-b724-11e6-99eb-6e2c2a0eecc6.jpg)

**Comment by NikoDelarich** [comment]
Why was this closed? I have noticed this issue on my printer as well...
