### ISSUE TITLE
Problems after Powerpanic with MMU2

### ISSUE THREAD

**Issue by dkeipp** [prusa3d/Prusa-Firmware#2013]
I dicovered the following behavior (repeatable) at my MK3S with MMU2S:

If the power is cut off while there is a loading error at the MMU it is not possible to restart the print caused by two bugs:
1. The printer ask (after Power on) to resume printing, if confirmed he heats up the bed, but then nothing more happens. even some minutes after the bed reaches the set value the nozzle set temperature is still at 0°C. That means that the printer doesent set the temperature of the nozzle. As a workaround it helps to go to preheat or temp. Settings and select the temperature manually. When then tho nozzle hits the set point the printer try to resume the print and leds to the second issue:
2. After the printer reaches temperatures he try to load the filament (what failed just before the power has gone). The load of the filament had success and he moves on to the purge tower.
And here comes the main problem. The printer is not on the last printing hight because if there is a MMU load fail the printer rises the head some mm and then try to recover on this Z hight.
I think the code in the Powerpanic feature stores the last printing hight but not the "raised some mm because of MMU load error" height. After return of power the printer doesnt have the right Z height to successfull recover the print.

**Comment by beegmouse** [comment]
+1

**Comment by void269** [comment]
Same issue here.
