### ISSUE TITLE
[BUG] Z Calibration can be triggered while nozzle is HOT.

### ISSUE THREAD

**Issue by ManuGithubSteam** [prusa3d/Prusa-Firmware#202]
Hi

As described, If the nozzle is hot from a previous print and in the phase of cooling down. I can still start Z Calibation wich, if the print curled up and moved the pinda probe up result in the nozzle crashing hot into the bed wich leaves marks in the PEI.

This happend to me and it can be easy avoided if the temp gets checked before Z calibration. Like it does when doing XYZ Calibration.

Thanks
Manuel

**Comment by mrjohnc** [comment]
Would this be affected by the difference in depth measured when the nozzle is hot vs cold? 

I know this is being addressed with the extra temp sensor in the Pinda probe in MK3, so perhaps if this isn't suitable for MK2 its suitable for MK3?
