### ISSUE TITLE
[3.7.2] Unload filament Too fast at beginning

### ISSUE THREAD

**Issue by forestqc69** [prusa3d/Prusa-Firmware#2041]
MK3S with 3.7.2, manual Unload filament is so fast at the beginning that it scrapes the filament in half and filament won't be moved, then after 1.5 seconds goes to a more slow/normal speed.

Idler is properly adjusted.

**Comment by leptun** [comment]
@forestqc69 I've used both MK3 and MK3S extruder and have never seen the issue you are describing. Could you maybe make a video of the unload process and also a picture of the idler tension? I want to compare with my printer.
