### ISSUE TITLE
Possible Bug in util.cpp is_whitespace_or_nl

### ISSUE THREAD

**Issue by BoCoKeith** [prusa3d/Prusa-Firmware#2053]
In util.cpp:

```
inline bool is_whitespace_or_nl(char c)
{
    return c == ' ' || c == '\t' || c == '\n' || c == 'r';
}
```
Shouldn't it be "|| c == '\r'"?

**Comment by leptun** [comment]
Yes, that should be '\r'. I'm surprised it doesn't cause real problems. The thing is that it isn't used anywhere. Only the function under it is used and that one is correct.

Can you please make a PR with this?

**Comment by BoCoKeith** [comment]
I've never made a pull request before.  I think I created one, hopefully I did it right.  Please let me know anyone viewing this sees that I did it wrong.

**Comment by leptun** [comment]
It is ok.

**Comment by DRracer** [comment]
@BoCoKeith your PR was merged, would you mind closing this issue?
