### ISSUE TITLE
LCD unstable - content scrolls left and right

### ISSUE THREAD

**Issue by shilbert01** [prusa3d/Prusa-Firmware#2054]
During a print the LCD begins showing weird output. I can decipher MMU and error 0 (actually Fehler 0 - in German).

The print (two color sheep) seems to continue just fine.

**Comment by shilbert01** [comment]
A few minutes later the LCD stopped scrolling content left and right and I can now see that this is not an error but show the number of load failures for the MMU. So in other words it is just the normal display output but the content gets scrolled off-screen and moves around for some time.

**Comment by leptun** [comment]
This sounds like problems in translations where the displayed text is too long and overflows on the next line. https://photos.app.goo.gl/N8AnJcfDX6pps83K7
Take a look at another example in italian. Is it simmilar?

**Comment by leptun** [comment]
Also what firmware version are you using? (both printer and mmu). And what hardware? (S or not)

**Comment by shilbert01** [comment]
Firmware is 3.7.2-2363 on Mk3S and  1.0.5-300 on MMU2S. Language is German.
I will upload a photo later today.
