### ISSUE TITLE
static assertion failed: Z-range too high

### ISSUE THREAD

**Issue by TigerClaw33** [prusa3d/Prusa-Firmware#2067]
Hi, 

I am using a mod but cannot change the max. Z-value from 210 to 320. 

> Error: Marlin_main.cpp:3017: error: static assertion failed: Z-range too high, change the T type from uint8_t to uint16_t

Do I have this line here 
`static_assert(Z_MAX_POS < (255- FILAMENTCHANGE_ZADD), "Z-range too high, change fsensor_clamp_z<uint8_t> to <uint8_t>");
	sprintf_P(buf, gcodeMove, fsensor_clamp_z<uint16_t>(current_position[Z_AXIS]) )`

for Zmax 320 to
	`static_assert(Z_MAX_POS < (365 - FILAMENTCHANGE_ZADD), "Z-range too high, change fsensor_clamp_z<uint8_t> to <uint16_t>");
	sprintf_P(buf, gcodeMove, fsensor_clamp_z<uint16_t>(current_position[Z_AXIS]) )`

**Comment by Vogs27** [comment]
Same problem too. You solved?

**Comment by Vogs27** [comment]
Well, I think we should change uint8_t to uint16_t at line 7157 of Marlin_main.cpp an then comment out "static_assert(Z_MAX_POS < (255- FILAMENTCHANGE_ZADD), "Z-range too high, change the T type from uint8_t to uint16_t");". I'm testing this for problems, I let you know. In the meantime, if someone more skilled than me, can confirm my thought, I'll be glad.

**Comment by bogeyf14** [comment]
Did yall find a solution? I have the same problem.

Tried changing uint8 to uint16 on line 7157 but no dice. I did not try to comment out the error line. I figure it is there for a reason.

**Comment by gore80** [comment]
uncomment
//#define FILAMENTCHANGE_ZADD 2
in CONFIGURATION_PRUSA_H

**Comment by Demolux** [comment]
That solved it for me... while I don't know the consequences

**Comment by nicolai-wachenschwan** [comment]
I think I kind of fixed it: look up the  calls of "gcode_M600_filament_change_z_shift()" by searching for "gcode_M600_filament_change_z". Then change the datatype given at this line form uint8_t to uint_16t.
At last comment the static assert, because you made the suggested change.

**Comment by Prusa-Support** [comment]
Hello! Sorry for intervening so late on this thread. Sadly, I wouldn't be able to give an answer on a mod on an official capacity, but from what I see it should be just about the data type as @nicolai-wachenschwan mentioned - I wouldn't be able sadly to confirm if such mod would be safe to do or if it might incur in bugs, though - it really would have to be considered "at own risk and peril" - but I reasoned the same way as in the previous replies with the info at hand, the 365 is "outside of the 8 bit" and the error should have stemmed from that. 

Alessandro Pantaleo
Prusa Research

**Comment by nicolai-wachenschwan** [comment]
Hey Alessandro, Thank you for your time! I greatly appreciate your constant support, even on old problems :)

I did the mods as I described above, so far everything works just fine. 

In the current version the function gets called only once. Within the function everything gets converted, so no problems there, and the return value gets interpreted as float, so the mod should be fairly safe. 
but I can totally understand mods deleting the warrenty :P

**Comment by BladebornStudio** [comment]
In the Marlin_Main.cpp file you need to update the FilamentChange_Zadd from...

static_assert(Z_MAX_POS < (255 - FILAMENTCHANGE_ZADD)

to...

static_assert(Z_MAX_POS < (Z_MAX_POS +45 - FILAMENTCHANGE_ZADD)

Worked for me!

**Comment by Prusa-Support** [comment]
Hello! Thank you for the responses! @BladebornStudio I am thinking about yours - in theory, it works, but the issue there is that you're checking the hardcoded Z_MAX_POS "against itself" and adding/subtracting something else. So I'm having doubts on what if that Z_MAX_POS might change (errors, anything that might change it in other pieces of the code by mistake, etc.). Which is the reason I believe there was the static assert "not comparing to itself" but "other values". I see it a bit riskier than other solutions to be honest. 

Alessandro Pantaleo
Prusa Research

**Comment by BladebornStudio** [comment]
Makes sense, what would be a good way to go about it?

Sent from my iPhone

On Jun 26, 2022, at 11:10 AM, Prusa-Support ***@***.***> wrote:

﻿

Hello! Thank you for the responses! @BladebornStudio<https://github.com/BladebornStudio> I am thinking about yours - in theory, it works, but the issue there is that you're checking the hardcoded Z_MAX_POS "against itself" and adding/subtracting something else. So I'm having doubts on what if that Z_MAX_POS might change (errors, anything that might change it in other pieces of the code by mistake, etc.). Which is the reason I believe there was the static assert "not comparing to itself" but "other values". I see it a bit riskier than other solutions to be honest.

Alessandro Pantaleo
Prusa Research

**Comment by Prusa-Support** [comment]
Hello, sorry for the late response from my side! Unfortunately, I wouldn't be able to give a better solution, it would sadly be out of our knowledge, but I just wanted to point out that possible "risk" in that comparation (comparing to "itself"). Sorry for not having more knowledge on this aspect. 

Alessandro Pantaleo
Prusa Research
