### ISSUE TITLE
Mk3s filament sensor random issues filament change even when disabled.

### ISSUE THREAD

**Issue by 3dmonkeynl** [prusa3d/Prusa-Firmware#2073]
Filament sensor issues random changes on printing even with the sensor disabled in the menu.
Had this a couples times I disabled it because it gave me multiple changes when using Fillamentum Vertigo Starlight.

**Comment by michalxfanta** [comment]
You wrote about MK3S filament sensor, but in S version is installed IR filament sensor, which does not depend on the type of filament. And checking if the filament is present or not is mechanical. In MK3 was installed optical filament sensor, which has detected some filaments incorrectly. Which do you have?

OLD optical filament sensor
![optical_filament_sensor](https://user-images.githubusercontent.com/45625875/62476344-15857500-b7a7-11e9-8a70-cd468344bd2c.jpg)

NEW IR filament sensor
![IR__filament_sensor](https://user-images.githubusercontent.com/45625875/62476374-233afa80-b7a7-11e9-94c8-e2d4cd2fb4a8.jpg)

**Comment by 3dmonkeynl** [comment]
I have the new IR filament sensor.

**Comment by michalxfanta** [comment]
In this case, try to adjust the position of the filament sensor a little and check the sensor state switching in the menu *Support > Sensor info* when inserting the filament manually.

**Comment by StudentSA** [comment]
Hey, Im having the same issue on my i3 MK3. Randomly in a print its been asking me to change filament??? I am on latest Firmware (3.7.2) and Slicer (2.0.0)

**Comment by 3dmonkeynl** [comment]
Sensor adjusted, but for small prints I don't have any issue's (1/2 hour prints) 
Will test some longer duration print to see if it pops up again.

**Comment by gysnst2** [comment]
I am having major issues with my MK3s MMU2 asking for filament changes.  Right MMU2  it has 5 to choose from not The case.  the print will pause for no known issue and ask me to remove the filament and reload.  Then i hit the dial on the LCD button to continue.
