### ISSUE TITLE
Increase eeprom sheets storage

### ISSUE THREAD

**Issue by wavexx** [prusa3d/Prusa-Firmware#2076]
To followup on #1909, I'd recommend to increase the internal Sheets storage from 3 to a larger number before it's too late to easily extend the struct. I'm not discussing UI here, we can think about it later, this is just about future-proofing.

8 would allow for 4 sheets with different values for each side.
Or let's go overkill with 12, space is not a problem, and we could eventually reclaim it later.

I'd recommend to add two defines, EEPROM_MAX_SHEETS and EEPROM_USED_SHEETS.
Then, count/increment the sheets from the end:

first_sheet = EEPROM_MAX_SHEETS - 1
next_sheet = EEPROM_MAX_SHEETS - ((active_sheet + 1) % EEPROM_USED_SHEETS) - 1

in order to ensure the head is free until we start to use it.

**Comment by DRracer** [comment]
@wavexx There will be 8 sheet presets in the final FW 3.8.0 . Would you mind closing this issue?
