### ISSUE TITLE
Sheet rename cursor does not clear

### ISSUE THREAD

**Issue by vintagepc** [prusa3d/Prusa-Firmware#2089]
Found in 3.8.0-RC1, Mk3S.

The caret below the selected letter does not clear when pushing the knob to move to the next letter.

![IMG_0001](https://user-images.githubusercontent.com/53943260/62814108-a8dae500-badc-11e9-878a-bc1522ce3777.JPG)

**Comment by Dippyskoodlez** [comment]
It felt like this was intended to signify the character had changed.
