### ISSUE TITLE
Sheet cannot be changed after visiting uncalibrated sheet's setup menu. (3.8.0-RC1)

### ISSUE THREAD

**Issue by vintagepc** [prusa3d/Prusa-Firmware#2090]
3.8.0-RC1, MK3S. 
I've noticed sometimes the sheet will refuse to change. This happens after I've been in the "HW setup" menu and entered the submenu for a sheet that is not calibrated. (e.g. a live-Z of zero and it cannot be selected)
When in this state, I can select the top menu "sheet" option as many times as I want, it will not change away from "Smooth"  (my second sheet entry - I have two sheets defined). 
To recover I have to enter the menu for an already calibrated sheet and back out again.

**Comment by shro70** [comment]
Yeah same issue here. I have another strange issue. My Z axis is moving by itself few step each second.
