### ISSUE TITLE
Press the knob to resume nozzle temperature does nothing (3.8.0-RC1)

### ISSUE THREAD

**Issue by antimix** [prusa3d/Prusa-Firmware#2095]
Filament jammed during the First Layer calibration at the eject. The filament is still into the extruder and hot end.  There is the message on LCD "Press the knob to resume nozzle temperature".
The nozzle should be heated in order to remove the filament. 
No intervention could be done until the nozzle is hot. But pressing the knob, nothing happens.
Either pressing all buttons on MMU does nothing. Printer is stuck.

**Comment by vintagepc** [comment]
I noticed it had no effect but for me either, but once I confirmed on the MMU with its right button for ~1 sec it resumed without needing to touch the printer knob.
