### ISSUE TITLE
First Layer calibration often failed at the end due to filament jam (3.8.0-RC1)

### ISSUE THREAD

**Issue by antimix** [prusa3d/Prusa-Firmware#2096]
First Layer calibration often failed at the end, when it extract the filament.
The filament shaping is not optimised on the MK3S firmware as it is in PrusaSlicer, and so is very easy that the filament assumes [an anchor or bubble shape](http://www.tidus2000.altervista.org/uploads/IMG_20190810_190227.jpg), and jams in the extruder before exit from the gears.
It is advisable to write a filament shaping capability into the firmware, so that it could be used for each **Unload** functionality.
Issue  #2052 may be conducted to the same problem.

**Comment by vintagepc** [comment]
Maybe worth lumping #2079 under this umbrella as well for non-slicer handled MMU unload fixes.
