### ISSUE TITLE
2..0 Error Exporting Config Bundle

### ISSUE THREAD

**Issue by AbeFM** [prusa3d/Prusa-Firmware#2097]
I exported a config bundle in my release version of 2.0, when I tried to load the bundle into 2.1a, I got the following error:

![image](https://user-images.githubusercontent.com/42385/62826808-58fd2c00-bb77-11e9-88cf-a716643d89a2.png)

Looking at the export, checking the specific line, I found that to be the last in the file:

![image](https://user-images.githubusercontent.com/42385/62826793-f7d55880-bb76-11e9-8d62-21a4fea5a844.png)

From this I infer my export didn't work right. Curiously, PS2.0 exits during/after the config bundle export, perhaps it is crashing, I do not know its intended behavior. It indicates it is exporting, then blinks out of existence after a short pause.

The first time, I did it with a temporary profile in memory from a project I had just loaded. The second time I did it clean, both times the error was on the same line, but this may make sense if it doesn't add the temporary one to the bundle.

**Comment by vintagepc** [comment]
You should report this to https://github.com/prusa3d/Prusaslicer/issues as it's a slicer issue, not a firmware issue.

**Comment by AbeFM** [comment]
That's.... right.

Thanks. :-)
