### ISSUE TITLE
Problematic heatbed LED [3.8.0. RC1 MK3S]

### ISSUE THREAD

**Issue by jnko266** [prusa3d/Prusa-Firmware#2100]
After flashing new FW, on one printer the LED of the heatbed is blinking too fast and on second printer it isn't blinking at all. See attached video: 
https://www.dropbox.com/s/ipznusacw1p57b5/IMG_1351.MOV?dl=0

**Comment by vintagepc** [comment]
(The fast flashing is normal if you are changing from within 3.5.1-3.7.0 when the PWM was at a higher rate, but risked cooking parts on the einsy board. The PWM rate had to be decreased.)

**Comment by Prusa-Support** [comment]
Hello! Sorry for intervening so late on this thread. Closing the issue given the info on the previous comment. 

Alessandro Pantaleo
Prusa Research
