### ISSUE TITLE
after runout, MMU2s fails to heat nozzle before attempting to load new filament

### ISSUE THREAD

**Issue by aarchiba** [prusa3d/Prusa-Firmware#2108]
If the filament runs out (spurious in my case but the sequence is the same), the MMU2S retracts, moves the selector aside, ejects the current filament, and prompts the user to load a new filament. When the user does this, they get the usual "is filament loaded?" prompt on the LCD, but since the nozzle has been let cool down, the extruder won't turn and the filament is never successfully loaded, let alone running clear. Even if one hits "yes" and the print resumes, the loading process is never completed. Correct behaviour would be to return the nozzle to temperature before attempting to load a new filament.

**Comment by michalxfanta** [comment]
Which firmware version do you use?

**Comment by aarchiba** [comment]
MK3S 3.7.2-2363
MMU2 1.0.5-297
