### ISSUE TITLE
[3.7.2] MMU [1.0.5] Terminal Command "user button pressed"

### ISSUE THREAD

**Issue by R0m3oF0x** [prusa3d/Prusa-Firmware#2113]
During the filament change, after two unsuccessful attempts, further malfunctions occur which can only be corrected manually. The only thing the operator has to do is press the knob.

Please create a possibility that the pressure on the rotary knob can be generated remotely by terminal command (e.g. by Octoprint).

**Comment by leptun** [comment]
This is not possible from terminal since serial communication is halted while other commands execute.

**Comment by JohnnyDeer** [comment]
This issue is same as #2112, I´m closing.
