### ISSUE TITLE
[V3.7.2 (1.0.5)] MMU2S - Print clock wrong when unable to load filament

### ISSUE THREAD

**Issue by JasXSL** [prusa3d/Prusa-Firmware#2122]
Was printing over night when the MMU failed to load the final filament. I continued the print in the morning, and the filament loaded just fine. Once it finished, the total print time went ballistic. Either that or the flux capacitor is broken.

![2 month print](https://i.imgur.com/OauWKYY.jpg)

Sliced with PrusaSlicer 2.1.0 Alpha

**Comment by vintagepc** [comment]
This is a duplicate of #1849.
(Not MMU specific, happens when anything pauses a print for user interaction)
