### ISSUE TITLE
Weird "Print from SD" menu behavior

### ISSUE THREAD

**Issue by leptun** [prusa3d/Prusa-Firmware#2125]
The video sums it up: https://photos.app.goo.gl/h4XR5QjQeRZzRU4s7
@DRracer Please try checking this issue on a random sd card.

**Comment by DRracer** [comment]
@leptun yes, I've managed to simulate the same behavior ... there seems to be a +-1 offset issue. The Spitfire_.... filename should rotate, but the last character is sometimes blank (space) as if the filename wasn't long enough.
Are you willing to fix it ;) ?

**Comment by maximlevitsky** [comment]
I don't thing I have seen exactly the same bug but I have seen something similar:
Sometimes long print file name just doesn't start scrolling until you nudge it with up/down encoder movement.

**Comment by leptun** [comment]
@maximlevitsky The #2155 PR should fix that issue as well.
