### ISSUE TITLE
M109, M190 Do not meet Marlin specs

### ISSUE THREAD

**Issue by GWdd** [prusa3d/Prusa-Firmware#2126]
M109 / M190 - according to Marlin, should have two argument options:

- R - set temperature and wait for temp to reach absolute setpoint (wait for cooling or heating).
- S - set temperature and wait for temp to be at or above setpoint- 
 
Prusa firmware will wait for heating or cololing when M109 Sxxx is used. Which does not meet the Marlin spec. 

see: http://marlinfw.org/docs/gcode/M109.html

 There are cases where the S option as designed by the Marlin team are useful.

**Comment by haarp** [comment]
Duplicate of #1474. I've opened a trivial PR that'll fix this in #2060, but got no reaction yet.
