### ISSUE TITLE
Feature Request: Option to confirm sheet profile before a print

### ISSUE THREAD

**Issue by TehH4rRy** [prusa3d/Prusa-Firmware#2143]
Open to suggestions on how to implement this in the menu and still make the printer user friendly. Twice now I've nearly gouged my smooth sheet with negligence after swapping from textured sheet. 

Perhaps an option after selecting a print file to "Confirm print sheet" 

Or I put a sticky note to remind me to check sheet profile before printing.

**Comment by vintagepc** [comment]
This has been requested in #2093 as well.

**Comment by TehH4rRy** [comment]
> 
> 
> This has been requested in #2093 as well.

Right you are! This
