### ISSUE TITLE
Feature Request: Make sheets available via M503 and M500

### ISSUE THREAD

**Issue by 3d-gussner** [prusa3d/Prusa-Firmware#2153]
As changing sheet names and values can be a pain in the bu7t, I would like to suggest to make these available via M503 and M500 gcodes.

This way we could easy change
- Sheet Numbers
- Sheet Names
- Sheet Live-Z values

**Comment by vintagepc** [comment]
This would be a nice advanced-user alternative to #2091

**Comment by vintagepc** [comment]
I'm going to attempt to implement this feature on a fork. Stay tuned :-)

**Comment by vintagepc** [comment]
I chose not to do M500/3 as that separates a "working memory" value from eeprom values; sheets are always referenced from eeprom so it made more sense to just add a new special code for manipulating sheets one at a time.

**Comment by 3d-gussner** [comment]
Close it as @vintagepc has a good PR and can be discussed there.
