### ISSUE TITLE
Digital signature is invalid

### ISSUE THREAD

**Issue by kyjak** [prusa3d/Prusa-Firmware#2157]
Users cannot open the COM port of prusa cause of missing digital signature under windows 10.
![image](https://user-images.githubusercontent.com/15310250/64065754-ed582d00-cc11-11e9-9cd7-280794669e9b.png)

**Comment by Janys** [comment]
Hi! Are you using the latest drivers 2.2.6 available from https://www.prusa3d.com/drivers/ ? We have recently updated the package with newly signed drivers. The signature should be valid till March 2020.

**Comment by kyjak** [comment]
Yes, I uninstalled all prusa, including drivers, installed 2.2.6. I think the old drivers got stuck somewhere, any steps for "forced" total removal?

**Comment by Janys** [comment]
Yes, right-click the faulty driver in the Device Manager and select Uninstall, then tick the box saying "Delete driver software for this device". That should ensure the drivers are removed completely. Then try reinstalling 2.2.6. Please let me know if it worked. I'll definitely do some change to the code, so the next driver package will remove these old drivers automatically.
