### ISSUE TITLE
Feature Request: Separate Belt Status Test

### ISSUE THREAD

**Issue by brotherdust** [prusa3d/Prusa-Firmware#2175]
Hello!
When doing fine-tuning of the belts on my MK3S, I have to run a full self-test every time I make an adjustment. Would it make sense to have a separate belt status test available in addition to the full self-test? This would make belt adjustment a lot faster.
Thanks!

**Comment by haarp** [comment]
planned for firmware 3.9, see #1937

**Comment by brotherdust** [comment]
Oh! Ok! Thanks!
