### ISSUE TITLE
Live-Z adjustments made during print not saved if button is not pressed.

### ISSUE THREAD

**Issue by cmmtchll** [prusa3d/Prusa-Firmware#2176]
Config: MK3S
FW: 3.8.0 (final)

Steps: Start print.  During print, menu to Live Adjust Z.  Change the value.  Don't 'click'.  Print another item...
Result: adjusted Live-Z is lost.

Expect: I think the value should be saved....I adjusted and left it.  I've had 3 prints not properly aligned because of this...keep forgetting.

**Comment by leptun** [comment]
Live-adjust-Z is only saved when exiting that menu. This is needed since the eeprom has a limited number of write cycles and this way they are minimized.

**Comment by DRracer** [comment]
@leptun exactly
