### ISSUE TITLE
FW 3.8.0, sheet rename menu. Holding button to adjust Z breaks menu.

### ISSUE THREAD

**Issue by BeldrothTheGold** [prusa3d/Prusa-Firmware#2179]
Hello Team, 

Love the new Sheets menu. Thanks for all of your hard work!

Noticed this bug quite by accident. 

It seems the button stops responding in the rename menu if you hold the button rather than quick push it. Like if you are attempting to adjust Z while in the rename menu. It persists even after the menu times out. I have to reset the printer to fix it.

Hope it's a simple fix. 

V/R
Scott

**Comment by BeldrothTheGold** [comment]
@Panayiotis-git, @DRracer, @leptun 

I have tested the change @Panayiotis-git recommended from https://github.com/prusa3d/Prusa-Firmware/issues/1196#issuecomment-439501656.

This does indeed fix the bug which locks up the UI. I highly suggest this is tested and committed if it doesn't cause any regressions. 

Also, some brief testing of long-press in other menus with the fix in place validates @DRracer's statement that long-press still causes some strange behavior in other settings menus. 

I will work on this some more and submit another pull request.

**Comment by BeldrothTheGold** [comment]
Looks like @DRracer was able to implement an excellent solution.  I will close this issue now.

**Comment by DRracer** [comment]
@BeldrothTheGold thanks ;)
