### ISSUE TITLE
Feature Request: Add option to automatically unload E when safety timeout.

### ISSUE THREAD

**Issue by DavidUnboxed** [prusa3d/Prusa-Firmware#2190]
When the safety timer is triggered, I would like to have the extruder unload so that filament is not left to cool in the extruder. Cooling in the extruder makes some filaments more difficult to manage/remove/resume. (suggested by the wonderful SunshineFLGirl, my geekette).

**Comment by michalxfanta** [comment]
Thank you for the idea, we will consider implementation.
