### ISSUE TITLE
motors of Z axis and MMU2(S) does not turn off and keeps being warm/hot

### ISSUE THREAD

**Issue by Mirarkitty** [prusa3d/Prusa-Firmware#2191]
Firmware 3.8.0rc2 (and probably older).

Two motors of the MMU2 and the Z-axis motors keep running after the print. This seems to be a waste of electricity to heating the room.

![image](https://user-images.githubusercontent.com/3462581/64690521-ea223400-d490-11e9-8f41-fc3dffcf209b.png)
![image](https://user-images.githubusercontent.com/3462581/64690530-ed1d2480-d490-11e9-8d3a-cd04b9872282.png)
![image](https://user-images.githubusercontent.com/3462581/64690540-f1494200-d490-11e9-9d9f-35b21f72d71f.png)
![image](https://user-images.githubusercontent.com/3462581/64690547-f4dcc900-d490-11e9-8440-de1372eb147c.png)

Images >24 hours after the last print. The X and Y motors do turn off.

**Comment by leptun** [comment]
That is not the Y axis, that’s the Z axis (up/down). It is always on in order to prevent a sqewed Z axis (one side higher than the other).

As for the MMU motors, only the idler should be kept on always and maybe even the selector. The pulley motor could be disabled, however that is not a priority.

There are also other reports on github about the MMU motors. You can search for those as well. Hope this helps.

**Comment by Mirarkitty** [comment]
You are absolutely right with the Y/Z.

However I think it could very well turn off after say an hour and go back to the state it has when shut off (so it recalibrates Z). Same with the MMU. The printer can obviously handle a complete power off.

**Comment by Mirarkitty** [comment]
And this is absolutely a low priority issue, there's about 500 issues that should have higher priority. It's still an issue though.

**Comment by leptun** [comment]
It will be kept in mind. We’re kinda busy at the moment with the fratures for 3.9. Thanks for reporting🙂.

**Comment by gudnimg** [comment]
As we've improved in 3.13.0 the MMU side greatly in this regard so the motors are turned off when not used. I think we can close this issue once 3.13.0 is released. => adding this issue to our milestone as a reminder to close this issue.

**Comment by gudnimg** [comment]
Closing as this is now resolved with FW 3.13.0 and MMU FW 3.0.0 :)
