### ISSUE TITLE
MMU2(S) Idler skips steps after homing

### ISSUE THREAD

**Issue by leptun** [prusa3d/Prusa-Firmware#2192]
I noticed that after the idler homes and goes to position saved in eeprom, in some cases (not always) it will skip a step as it switches to StealthChop. If normal mode is used, hence no mode switch after homing, it will not skip that step.

**Comment by gudnimg** [comment]
@leptun do you agree we can close this issue when 3.13.0 is released? I can add this to our milestone as a reminder.

**Comment by leptun** [comment]
Yep. Forgot I even opened this.

**Comment by gudnimg** [comment]
Closing this since FW 3.13.0 is now released with new MMU FW
