### ISSUE TITLE
MMU2(S) filament grinding when loading to gears

### ISSUE THREAD

**Issue by leptun** [prusa3d/Prusa-Firmware#2193]
In single mode MMU, after the menu selection the filament gets loaded right away. The problem is that since the hotend is still not up to temp, the gears don't spin and the filament gets grinded at the MMU unit. This could be fixed by temporarily disabling cold extrusion while loading to gears.

**Comment by vintagepc** [comment]
^^ Interesting observation. With a Skelestruder and a slightly longer bowden tube (fixed distance +1-2 additional "nudges"), the load stops after the "fixed" distance where it expects to find the sensor. Then resumes once the hot end is up to temp and the Tc command is issued.

Alternate option could be to simply use a slightly shorter distance to load to just before the gears and finish the load later.

**Comment by leptun** [comment]
Duplicate of #1837. Closing...
