### ISSUE TITLE
[3.8.0 MK3s] Calibrate Z does not level the X axis gantry in Stealth Mode

### ISSUE THREAD

**Issue by cryocide** [prusa3d/Prusa-Firmware#2200]
Expected behavior:  Stealth Mode is temporarily disabled while Z calibration is completed.

Actual behavior:  Attempting to Calibrate Z while in Stealth Mode results in a slight raise of the X Axis gantry regardless of where it sits or how level the X idler and motor mounts are or aren't.  The gantry never crashes into Z Max at low motor current to place sides at their known max height before proceeding with mesh bed leveling.  I suspect that it gives up immediately because Stealth Mode disables crash detection.  The result is, best case, a lot of Z compensation for a "tilted" bed.  Worst case is a damaged bed.  This probably also happens during the Calibration Wizard, but I haven't tested that specifically.

Temporary workaround:  Manually switch to Normal Mode, then calibrate Z, then switch back to Stealth Mode if desired after the process completes.

Recommended fix:  When beginning Calibrate Z or any other calibration, read current user-set mode setting, switch to Normal mode, complete operations, and then switch back to the previously-read user-set mode.

**Comment by leptun** [comment]
@cryocide Thanks for reporting this. A fix has been merged for this issue. #2263. It will appear in the upcoming 3.8.1 final release.
