### ISSUE TITLE
MK3S. No MMU. Error Tn on changing filament after runout.

### ISSUE THREAD

**Issue by rongith** [prusa3d/Prusa-Firmware#2207]
Here what says the octoprint
```
Not sending T1, that tool doesn't exist according to the printer profile or was reported as invalid by the firmware
Recv: echo:T1
Recv: Invalid extruder
T0 reported as invalid, reverting to T1
Recv: ok
Not queuing T1, that tool doesn't exist according to the printer profile or was reported as invalid by the firmware
Recv: echo:T1
Send: N425006 T1*14
Not sending T1, that tool doesn't exist according to the printer profile or was reported as invalid by the firmware
Recv: Invalid extruder
T0 reported as invalid, reverting to T1
Recv: ok

```
Before printing the joined file, I printed some parts with multimaterial without MMU the some T0 and T1 commands where sent. That may have confused the printer.

It may safe for me to send a T0 command in the Start G-Code. Else the printer stick to T1 if before I printed a file finishing with T1.

[PoulieDavier-r08 - FDM-95.zip](https://github.com/prusa3d/Prusa-Firmware/files/3614348/PoulieDavier-r08.-.FDM-95.zip)
[PoulieDavier-r08 - FDM-20190915-191834-(P)0.25-095pc-vmax-MK3-(F)FormFutura ASA(ApolloX) -i-(P)PMK3S-M860-35-1-(V)2.1.0-rc2+win64-(T)3h11m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/3614341/PoulieDavier-r08.-.FDM-20190915-191834-.P.0.25-095pc-vmax-MK3-.F.FormFutura.ASA.ApolloX.-i-.P.PMK3S-M860-35-1-.V.2.1.0-rc2%2Bwin64-.T.3h11m.gcode.zip)

**Comment by mmb88** [comment]
Hi , i have had also this issue and found the problem in the printer profile of octoprint.
Change the number of Extruders from 1 to 5 in the settings and the T-Code will work again.
