### ISSUE TITLE
USB diagnostics aren't enabled

### ISSUE THREAD

**Issue by Bob6162** [prusa3d/Prusa-Firmware#2210]
When doing an X Y Z cal it would be really nice to have the values sent out the USB so they can be looked at. That would help a great deal if the calibration fails. Having a message that says “Calibration Fails check the manual” is really not much help when you don’t know why it is failing. Again, I would guess that you already have that switch in you firmware and it is probably disabled when compiled. Adding it into the Calibration menu would seem to be easy . (Yeah, easy for me to say since I am not the one doing it).

**Comment by michalxfanta** [comment]
If you connect the printer with a USB cable and run for example Pronterface, you can read data from XYZ calibration.

**Comment by Bob6162** [comment]
I heard that from someone before and I must be doing something wrong because all I got was the Iteration number and a string of "Busy Processing" comments.
