### ISSUE TITLE
Firmware 3.8.0 First Layer Cal. possible accident

### ISSUE THREAD

**Issue by thilojaeggi** [prusa3d/Prusa-Firmware#2222]
The Z Offset from 3.7.2 will be saved as Smooth1 even if you don't have the Z Offset Value of the Smooth Sheet set. This causes issues when you start the First Layer Cal. on 3.8.0 because it will dig into the bed if the smooth sheet is installed. Maybe it should ask if the Value of 3.7.2 is for the Powder coated one or smooth one to prevent damage to the smooth sheet.

**Comment by ItayZiv** [comment]
Yeah seems from the logs that it just saves to the first one, I would just change the name of the first sheet in the meanwhile. Hopefully they change it so it asks you which one to save to.

**Comment by zoltan-l** [comment]
I have encountered the same after flashing the 3.8.0 now I have a sheet with nice holes in the starting point of the sheet.

**Comment by thilojaeggi** [comment]
It's fixed in in the latest firmware. (Not beta)

zoltan-l <notifications@github.com> schrieb am So., 13. Okt. 2019, 21:55:
