### ISSUE TITLE
Add Beep when MMU2 Load Failed

### ISSUE THREAD

**Issue by SiwatS** [prusa3d/Prusa-Firmware#2232]
Add an option to make the buzzer go beep beep when the mmu fail to load so i know that I need to wake up and go fix it

**Comment by michalxfanta** [comment]
This feature we scheduled in some next release.

**Comment by JohnnyDeer** [comment]
This feature is already implemented, I´m closing.

**Comment by eqrx** [comment]
Hi, could somebody point me to the implementation of the fix? I am using version 3.9.3 and the printer does not beep on load failure and I do not see any option to enable that. Is that something that comes with newer version, do I need to configure something?

Thank you all very much :)

**Comment by JohnnyDeer** [comment]
Hi @eqrx, just set your sound setting to loud or assist.
