### ISSUE TITLE
Missing translations in v3.8.1-RC1

### ISSUE THREAD

**Issue by 3d-gussner** [prusa3d/Prusa-Firmware#2254]
Following the [translation.md](https://github.com/prusa3d/Prusa-Firmware/blob/MK3/lang/translations.md)  document, I have found several new messages which have not been added to `lang_en.txt` and `lang_en_??.txt.

```
First you will select filament you wish to use for calibration. Then select temperature which matches your material.
I will start to print line and you will gradually lower the nozzle by rotating the knob, until you reach optimal height. Check the pictures in our handbook in chapter Calibration.
If you have more steel sheets you can calibrate additional presets in Settings / HW Setup / Steel sheets.
Is any filament loaded?
PINDA
Please insert filament to the extruder, then press knob to load it.
Please insert filament to the first tube of MMU, then press the knob to load it.
Please load filament first.
Select filament:
Select temperature which matches your material.

```

It would be nice that before creating a new Tag / Release this procedure would be add to make sure that new messages aren't forgotten.
Also the `/lang/po/` files have not been updated.

**Comment by 3d-gussner** [comment]
@DRracer 
The `lang-export.sh` script has still the bug that the last message isn't generated in `Firmware.pot` and `Firmware_xx.po` files, if it doesn't end with two `LF`. And now it also struggles also with `\n` to find the correct file and line.

As I was preparing the PR for missing translations and I struggled again in the hole translation procedure:
- 1st the "bug" i commented here https://github.com/prusa3d/Prusa-Firmware/pull/2050#issuecomment-539614170
- but also after using POEdit to make the translations and using `lang-import.sh` script the `/lang/lang_en_xx.txt` files are quite different to the new generated `/lang/po/new/lang_en_xx.txt` files
  - As non-translated messages in `/lang/lang_en_xx.txt` have `"\x00"` and the `/lang/po/new/lang_en_xx.txt`have `""`

Example
- `/lang/lang_en_de.txt`
```
#
"Crash detected. Resume print?"
"Crash erkannt. Druck fortfuehren?"

#
"Crash"
"\x00"

#MSG_CURRENT c=19 r=1
"Current"
"Aktuelles"

```
- vs. `/lang/po/new/lang_en_de.txt`

```
#
"Crash detected. Resume print?"
"Crash erkannt. Druck fortfuehren?"

#
"Crash"
""

#MSG_CURRENT c=19 r=1
"Current"
"Aktuelles"

```

What am I doing wrong?
How does Prusa translate the messages?
Can i use POEdit (free version available) or do I have to use PhraseApp (phraseapp.com) (starts from 140$/month)?
Or do I have to translate directly into the `lang_en_xx.txt` files?

**Comment by DRracer** [comment]
@3d-gussner internally, we edit the lang_en_xx.txt files directly (which is much faster for now). We only produce PO files for external collaborants, who prepare the translations. We then copy the new sentences into lang_en_xx.txt.
Yes, you are right, lang-export (and may be others) don't like the \x0a (the backslash is missing).
Let's fix this completely together in FW 3.9.

**Comment by 3d-gussner** [comment]
@DRracer Thanks for the feedback... So for the moment I will not update the `/lang/po/*` files and folders just add the translations directly in the `lang_en_xx.txt` files when i do a PR.

Meanwhile I will try to work on that issue.

Just to be clear, the goal is still to use the scripts
- to generate `*.po` files
- be able to send them to translators
- import the translated `/lang/po/new/*.po` files
- check if they are not corrupted
- improve the multi language support

**Comment by 3d-gussner** [comment]
Too long open...
