### ISSUE TITLE
Feature request: Raising Z  higher when pausing manually

### ISSUE THREAD

**Issue by MonoSann** [prusa3d/Prusa-Firmware#2257]
Sometimes it is neccesary to pause the print manually, to clean the nozzle from molten fillament.
Often this happens during the first few layers.
Raising the Hotend 80 mm higher then the recent value during pause, would make cleanig a lot easier.
Thx.

**Comment by quiccsilvver** [comment]
I would like move Z enabled during the pause (and then being able to restart as normal).

**Comment by michalxfanta** [comment]
We planned new type of pause especially for this situation, we named it Maintenance pause. Will be included in one of the next releases.
