### ISSUE TITLE
[Feature Request] Filament selection when starting MMU print (just like single mode)

### ISSUE THREAD

**Issue by Chrismettal** [prusa3d/Prusa-Firmware#2260]
When starting a single mode print on an MMU machine, you will get promted as to which of the loaded filaments you want to use for the print, which is great.

The same functionality for multi material prints would be awesome. When starting a 2 material print for example the machine would prompt you something like:

Select Filament to use for:
[e1 white PLA]
 1   2   3   4  -5- 

Select Filament to use for:
[e2 black PLA]
 1   2  -3-  4   5 

The [] part would reflect the original settings in Prusaslicer when creating the code.

I oftentimes create 2 or 3 material codes and when slicing the code i never know where "the correct" materials will be loaded later so i end up reloading black and white PLA all the time into slots 1 and 2 even though they are already loaded in 3 and 5 for example.

**Comment by michalxfanta** [comment]
Thank you for your interesting idea, we will add it to our backlog.
