### ISSUE TITLE
Feature request: Show heater utilization, both extruder and heatbed

### ISSUE THREAD

**Issue by cool-RR** [prusa3d/Prusa-Firmware#2261]
It'll be nice to be able to see the utilization percentage of both the heatbed and the extruder while printing. This means, take the total amount of time that the extruder heater was enabled in the last second, and divide it by 1 second. i.e. when you're approaching 100% extruder heater utilization, you're likely to run into the thermal runaway protection and get your print aborted.

This can be useful when tweaking a PETG profile, since you're keeping your fan low to avoid cooling the extruder too much and running into the thermal runaway protection.

These can be shown in a secondary Info display that isn't shown by default.

**Comment by michalxfanta** [comment]
Thank you for your interesting idea, we will add it to our backlog.
