### ISSUE TITLE
FW 3.8.0 Line break not working

### ISSUE THREAD

**Issue by dronecz** [prusa3d/Prusa-Firmware#2262]
Hello,

can someone pls explain me why was this: 

`#define SERIAL_PROTOCOLLN(x) (MYSERIAL.print(x),MYSERIAL.write('\n'))` 

changed to this:
`#define SERIAL_PROTOCOLLN(x) (MYSERIAL.println(x)/*,MYSERIAL.write('\n')*/)`

in [this](https://github.com/prusa3d/Prusa-Firmware/commit/c4d5e332c89e998c2ab9a60ca866a860a7a03eff?diff=unified) (Marlin.h) commit? 

We use these functions and with new define it is not sending line break through  serial line. 

Thanks

**Comment by leptun** [comment]
Hi. These functions were changed in order to save flash. They still send the line break, but it's a bit different.
Before you would send `something\n`, but now with this change it's `something\r\n`. Maybe that carriage return breaks your implementation.
