### ISSUE TITLE
Screen "Failures MMU" corrupted

### ISSUE THREAD

**Issue by mkh595** [prusa3d/Prusa-Firmware#2275]
MK3S: 3.8.0-2684
MMU2: 1.0.6-372

![20191016_085105](https://user-images.githubusercontent.com/30566575/66903882-7c26da80-f003-11e9-88f1-0844ae4e62b5.jpg)
![20191016_085115](https://user-images.githubusercontent.com/30566575/66903893-8052f800-f003-11e9-8e81-b12f73a2f27e.jpg)

**Comment by gudnimg** [comment]
Closing this Github issue as it seems to be stale at this point. If there are any memory corruptions today it would be nice to have a new Github issue.
