### ISSUE TITLE
FW 3.7.1 & 3.8.0 -  Selftest fails on the Hotend Thermistor 

### ISSUE THREAD

**Issue by mptrs** [prusa3d/Prusa-Firmware#2278]
Related to this clossed issue: #116 

I'm getting this error again after flashing to version 3.8.0.

I will double check the termistor, but don't expect this to be the problem (as 3.7.0 works just fine).
3.8.0 gives me very unstable temperatures (set to 215 and goes from 180 to 230, very strange)

Creating this issue because the other was closed and seems like noone resolved it.

**Comment by leptun** [comment]
Try running a pid calibration, but be very careful. This kind of oscillation usually signals a faulty thermistor. You might also try doing a factory reset as values might have gotten corrupted between versions. Does downgrading fix the issue?

**Comment by mptrs** [comment]
I did the pid calibration hoping to fix the unstable temperature during printing, but unfortunately it didn't.
Will downgrade to 3.7.0 and test again.
After that a factory reset on 3.8.0

**Comment by mptrs** [comment]
Weird stuff. Flashed to prusa3d_fw_MK25_3_7_0_RAMBo13a_en-de.hex -> self test fails. Flashed to prusa3d_fw_MK25_3_7_0_RAMBo13a_en-cz.hex -> self test OK

Will do some more testing.

**Comment by leptun** [comment]
Forget about selftest for the moment. Look at the temperature oscilation while preheated while moving the cable bundle in different positions.

**Comment by cimoalpacino** [comment]
On my original MK2.5 I have a stable temperature. 

Running prusa fw 3.7.0 on Ramps board on my (semi-original prusa bear) MK2S gives a stabile temperature, while 3.8.0 oscilates a lot. Even after pid calibration.

I had to manually guess and try pid parameters to get a stable temperature.

My pid values for 3.8.0 on my MK2S are
#define  DEFAULT_Kp 20
#define  DEFAULT_Ki 0.4
#define  DEFAULT_Kd 50

**Comment by leptun** [comment]
There wasn’t any change regarding pid between 3.7.0 and the latest firmware.

**Comment by leptun** [comment]
@cimoalpacino Maybe the new bed heating affects the thermistor circuitry on rhe ramps. I haven’t played with the hardware, but I think that it’s prone to electrical interference.

I can say the same about miniRambo vs EinsyRambo. On the old board without heating and just letting everything cool down results in shaky temperature reading. That printer is not stock, so it might vary.

**Comment by mptrs** [comment]
> Forget about selftest for the moment. Look at the temperature oscilation while preheated while moving the cable bundle in different positions.

Ok, moving cables make the temperature reading go crazy. So it looks like there is something wrong with the cable?

**Comment by leptun** [comment]
It is very plausible that there is a small breakage in the cable. Most likely near the heater block. I’d suggest you also check the connection to the board, although the first option is more likely.

**Comment by cimoalpacino** [comment]
@leptun, probably you're right.
Anyway, with manually set pid values i get very stable temps.

**Comment by mptrs** [comment]
> It is very plausible that there is a small breakage in the cable. Most likely near the heater block. I’d suggest you also check the connection to the board, although the first option is more likely.

Released all cableties to check the cables, wiggled the cables again and no oscilation anymore :\
Managed the cables a bit smoother and wiggled again and again no oscilation.

Still not 100% sure the is no problem with the cable so will test some more.

@leptun thanks for pointing out it's more likely to be hardware than software!
