### ISSUE TITLE
XYZ Calibration Info Menu Option Pauses Print

### ISSUE THREAD

**Issue by screwyluie** [prusa3d/Prusa-Firmware#228]
While you're printing if you go into Support > XYZ cal. details your print will pause until you click out of that screen and then it resumes.

I don't know if it's supposed to do that, but if it is then perhaps it's not something that should be available during a print.

**Comment by madhunm** [comment]
@screwyluie when you are printing, that menu shouldnt come at all...

**Comment by screwyluie** [comment]
I'm on the latest RC (the one with the linear advance) and it is there, and I was exploring and it paused my print... that'll teach me lol

**Comment by PavelSindler** [comment]
@screwyluie, did you print from SD card?

**Comment by screwyluie** [comment]
no I was printing from usb

**Comment by PavelSindler** [comment]
Xyz details menu pauses printing. It was hidden when printing from SD card, but it was not hidden when printing from USB. It is now hidden also when printing from USB (PR https://github.com/prusa3d/Prusa-Firmware/pull/233 ). This is just hotfix. It would be better to rework xyz cal. details menu to be non-blocking, but it has low priority now.
