### ISSUE TITLE
Feature Request: Option to pause the print when running out of filament

### ISSUE THREAD

**Issue by Blup1980** [prusa3d/Prusa-Firmware#2281]
The current behavior when running out of filament with firmware 3.8.0 is:

- The printer detects the missing filament
- The printer goes to a parking position and cool down the extruder but keeps the bed on. 
- The printer asks the user to press a button to start to unload the filament leftover.
- Then the printer ask for loading a new filament with no way to go to the main menu of go to a mode where the nozzle or/and the bed is powered off.

I propose the following behavior for the last point
- The printer ask for loading a new filament or enter Pause mode.

Why is it useful ?
Sometime when running out of filament, we don't have immediately access to a new spool.
This could happens when printing a very large part and underestimating the amount of required/available filament. One doesn't want to kill a print that already lasted 24 hours or more. Thus the printer waits until a new spool is delivered for instance.
When that happens, the only option is to let the printer in the state where it is in the parked position with the extruder off. The problem it that it still has the bed enabled at possibly relatively high temperature. If the printer has to stay in that mode for days it's a waste of energy.

The way I currently handle this case is by loading the printer with another small leftover of filament. Then I let the printer resume the print and immediately go to the menu to put the printer into Pause mode.
There I have access to the settings menu and I can set the print bed temp to 0°C or at least to a lower temperature if I don't want to risk problems with part adhesion.
Once the correct filament is available, I unload my little placeholder filament and reload the printer with the correct spool.

Having the possibility to put the printer into pause mode when a filament run-out is detected would make this much easier and won't require a hack to trick the printer logic to put it into pause mode.

**Comment by bgiot** [comment]
Having the bed cooling down will make the printed piece not sticking to the bed anymore... not a good option I think...
