### ISSUE TITLE
3.8.0 Firmware on MK3S - XYZ Calibration text all garbled

### ISSUE THREAD

**Issue by ctabrizi** [prusa3d/Prusa-Firmware#2294]
The calibration still seems to work but all the instructions broke. Uploaded firmware via USB cable from PrusaSlicer 2.0.0+. See photo below:

<img width="870" alt="XYZ Calibration" src="https://user-images.githubusercontent.com/3836137/67519904-aeb48100-f65c-11e9-967f-3671c6d3be54.png">

**Comment by leptun** [comment]
Can you please provide more details about the issue?

Were you using a custom firmware?
Were you using English or another language.
Does it always break? Can you reproduce the issue again?
Does downgrading fix the issue?

**Comment by prusaprinter** [comment]
i have the same problem but if i just let it run then it normal fixes the issue its self

**Comment by Kachidoki2807** [comment]
Was it when you put down the steel sheet?

I got sometime, not often but it happens, the screen becoming blank when I put the steel sheet. On the next refresh the display come back to a normal status. I also already got this weird display, but I cannot remember precisely the conditions.
I suspect it is when I put the sheet too quickly or when the magnet are stronger than my fingers and the sheet slip out. :-) This maybe produce an EMC pulse that break the communication with the display through the ribbon cables.

**Comment by vintagepc** [comment]
The display is somewhat subject to static electricity, it has been known to get corrupted or even damaged from static zaps to the bed or display module. I've definitely had this happen a few times last winter when the air was very dry and at some point it damaged my LCD module. 

The PSU is grounded, so I suggest touching its metal casing before touching the printer or heat bed when the air is dry and static shocks likely.
