### ISSUE TITLE
Prusa MK3S bed calibration point not found

### ISSUE THREAD

**Issue by prusaprinter** [prusa3d/Prusa-Firmware#2296]
My Prusa Mk3s that I just got will not finish the bed calibration points, every time it says "bed calibration point not found". I have tested the P.I.N.D.A. probe and tensioned the belts to the perfect point but I still am not getting it to finish. I have tried to follow every comment online but none of them that I could find describe my problem. Every time it took 30 seconds to look for the calibration point but ends up just moving past the calibration point with the P.I.N.D.A. sensor not being close to the dashed circle.
	Please help I have been trying to fix it for about a week now and nothing will work.

**Comment by leptun** [comment]
A video of the calibration might be helpful. Does the printer complete selftest?

**Comment by prusaprinter** [comment]
yes

**Comment by prusaprinter** [comment]
i tried to watch videos of the problem but i couldn't find any

**Comment by leptun** [comment]
I'd like you make a video and upload it to something like google drive. I want to see how it does the calibration. What firmware version are you using?

**Comment by prusaprinter** [comment]
i do not have the printer now but i might be able to get a video of it by wed

**Comment by prusaprinter** [comment]
also the firmware that i am using is 7.1.2 i think

**Comment by leptun** [comment]
That version number never existed. Try re-flashing 3.8.1 firmware once you get the machine. https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.8.1

You have to use PrusaSlicer to upload the firmware to the machine.

**Comment by prusaprinter** [comment]
i will try to do that on wed to but i found the firmware that i have in it

https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.7.2

**Comment by 3d-gussner** [comment]
You can find the latest release https://github.com/prusa3d/Prusa-Firmware/releases/latest :-)

**Comment by Tanischacat2009** [comment]
Double check your PINDA probe height, reset your printer and try again.  This might help as I just updated firmware from 3.8.0 to 3.8.1 on my MK3s and had to try 3 times to get it to work, but it did work.  Adjusting the PINDA probe height corrected the error message that I was getting.

**Comment by prusaprinter** [comment]
i will trey to do that soon

**Comment by acidmang** [comment]
I'm having the same problem...  I did not run into it with 3.8.1 RC-1 but the 3.8.1 release seems to be random.  Still need a video?

**Comment by michalxfanta** [comment]
Please send us a video.

**Comment by prusaprinter** [comment]
I found that if I go to settings and then to move axis, then I would put the x and y to 0 the I would disable steppers and move the axis there. That would calibrate so then I would start a calibration and that worked
