### ISSUE TITLE
Wrong target temperature for heating up after power failure MK3s+MMU2s

### ISSUE THREAD

**Issue by FrHePo** [prusa3d/Prusa-Firmware#2303]
Hi there,
I encountered a firmware problem after experiencing a power failure. My firmware-version is 3.8.0-2684. As the power returned, my i3 MK3s with MMU2s resumed printing and started heating up again. The problem was that the target temperature for the nozzle was wrong. It was set to 14°C.
As a result the nozzle kept cooling down and I had to set the correct nozzle temperature manually. The bed target temperature was correct.
Best regards,
Frans

**Comment by leptun** [comment]
What was the target temperature before the power panic?

**Comment by FrHePo** [comment]
270°C 

Best regards,
Frans 

Am 31.10.2019 13:24, schrieb leptun:

> What was the target temperature before the power panic? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/prusa3d/Prusa-Firmware/issues/2303?email_source=notifications&amp;email_token=AL7WCMO2ILNBRIUXBLNPC6LQRLE7VA5CNFSM4JHJC3IKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECXR3QQ#issuecomment-548347330
[2]

**Comment by leptun** [comment]
@wavexx There appears that Power Panic saves the hotend and bed temperature as uint8_t. This becomes a problem for temps over 255deg. Do you want to make a pr with a fix or should I do it?

**Comment by FrHePo** [comment]
Ok. Yes please make a pr. Thanks! 

Best regards,
Frans 

Am 31.10.2019 13:38, schrieb leptun:

> @wavexx [1] There appears that Power Panic saves the hotend and bed temperature as uint8_t. This becomes a problem for temps over 255deg. Do you want to make a pr with a fix or should I do it? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/wavexx
[2]
https://github.com/prusa3d/Prusa-Firmware/issues/2303?email_source=notifications&amp;email_token=AL7WCMMNMSGSVXEXE6PQOFLQRLGTFA5CNFSM4JHJC3IKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECXTHGI#issuecomment-548352921
[3]
