### ISSUE TITLE
MMU2 retracts before extruder unloads in filament runout (Mk3S, 3.8.1/1.0.6)

### ISSUE THREAD

**Issue by vintagepc** [prusa3d/Prusa-Firmware#2313]
Just had this occur when my MMU print ran out of a certain colour mid print. Runout detection worked as expected, but the MMU did its retract cycle *before* the extruder had completed its unload. As a result there was no filament in the MMU for it to grab and retract. 

 I had to remove the bowden connector from the selector and pull the filament out manually before I could load replacement filament.

Please let me know if I should move or crosspost this to MM-control-01; not entirely sure whose domain this falls under but my suspicion is that the Mk3S firmware is the one telling the MMU to retract out of order.

Edit: in case it's relevant after reading other posts about MMU2 runout/change, I was in the post-colour change section of the print, so there was no wipe tower. I expect the behaviour would be similar during a single-mode print.

I've noticed a variant of this as well; after starting an MMU print if filament is already loaded, the MMU will forcibly retract from the extruder with the extruder not unloading, and when the nozzle may not be up to temperature yet.

**Comment by gudnimg** [comment]
@vintagepc do you think we can close this Github issue when 3.13.0 is released? Or is it still a relevant issue today.

**Comment by Prusa-Support** [comment]
@vintagepc @gudnimg 
This feels obsolete at this point so I'll close it but it can definitely be opened back if needed. 

Michele Moramarco
Prusa Research
