### ISSUE TITLE
Polycarbonate Preset Required for Preheating and First Layer Calibration.

### ISSUE THREAD

**Issue by anilrobo90** [prusa3d/Prusa-Firmware#2317]
Hi,

In Polycarbonate Preheat Profile set bed temperature of 105 Degrees and nozzle temperature of 270 Degrees.

**Comment by leptun** [comment]
@anilrobo90 I think that @michalxfanta said at some point that custom preheat profiles will come to a future firmware version.

**Comment by william14235** [comment]
Actually, 

you can change the setting for any type of filament
<img width="1440" alt="Screen Shot 2019-11-23 at 10 21 10 AM" src="https://user-images.githubusercontent.com/55214793/69483352-19cbb180-0ddb-11ea-977a-3236bf18fcad.png">
just go to the filament settings option and change the temperature. In the picture, it is 215 for pla, but I could make it 220 or 210. You can also make it different for the first few layers than the rest of the print.

**Comment by michalxfanta** [comment]
Yes, custom preheats profiles will come.

**Comment by Prusa-Support** [comment]
Hello! I'm sorry for intervening so late on this thread. We indeed implemented the PC preset in the meantime (275/110), closing this thread based on this info. 

Alessandro Pantaleo
Prusa Research
