### ISSUE TITLE
3.8.1 Sort SD by time not working

### ISSUE THREAD

**Issue by dlpgraphics** [prusa3d/Prusa-Firmware#2320]
Firmware version 3.8.1 sort the files by time not working. This is a i3 MK3S with Toshiba Flashair SD card.

**Comment by leptun** [comment]
Does the issue fix if you take the card out and reinsert it?

**Comment by leptun** [comment]
@dlpgraphics Your issue might be related to https://github.com/prusa3d/Prusa-Firmware/pull/1739
These changes have just been merged and will be released in the upcoming 3.9. Hopefully these were all the issues.

**Comment by draeath** [comment]
@dlpgraphics can you confirm if you still have this issue with a current firmware release?

**Comment by dlpgraphics** [comment]
This is working correctly now.

**Comment by draeath** [comment]
Can you close it then? ;)

Thanks for confirming.
