### ISSUE TITLE
3.8.1 XYZ calibration

### ISSUE THREAD

**Issue by SarlaGri** [prusa3d/Prusa-Firmware#2322]
I was running firmware 3.8.1 for a few weeks already without any issues. 

Then, after a print I wanted to check the nozzle. I attempted to raise Z-axis to +210. The printer did not stop at the end of the Z-axis as expected but tried to raise the carriage some more (similar to what it does for Z-azis calibration).

After this I could not print anymore. The mesh bed leveling failed every time. 

I've attempted to run XYZ calibration but the step always failed at the X-axis (check X-axis length).

I reset the printer to factory defaults. Still the error persisted for the X-axis. 

Contacted support and they instructed me to flash 3.8.0. I did this and the calibration completed successfully on the first attempt. 

So there seem to be at least 2 issues with 3.8.1
- the printer attempts to go beyond the +210mm for the Z-axis. 
- the printer fails calibration for X-axis.

Thanks!
Bogdan

**Comment by william14235** [comment]
This issue is everywhere, actually. Even on 3.8.0 when I checked the nozzle even if it was about halfway up the z-axis it would show as zero. The x-axis issue may have been caused by the extruder motor wire. This happened to me with my kit, so I ended up zip tying it
