### ISSUE TITLE
Mesh bed leveling correction

### ISSUE THREAD

**Issue by mmoraes80** [prusa3d/Prusa-Firmware#2324]
Hi,

The current mesh bed leveling correction is done as front, back, right and left. Why not make it as quadrants instead? Quadrants can be individually adjusted without overlapping each other or adjusted the same way in case one needs to adjust one entire side such as front, back, left or right..

![MBL](https://user-images.githubusercontent.com/44211704/68715428-fbaab980-056f-11ea-997d-2926a97507e3.jpg)

**Comment by william14235** [comment]
I think it's because it is more accurate with nine sections, and 3d printing needs extreme and precise accuracy.

**Comment by mmoraes80** [comment]
Where are you getting nine sections? The accuracy should come from the PINDA sensor, but it does not necessarily flattens the virtual bed 100%, so the extra adjustment by corner would be helpful.

**Comment by HarrySatt** [comment]
I would like to see the algorithm which takes account of the values set with the mesh bed correction values. what I see so far is that the middle position of the mesh bed is not hold fixed to the z level correction. Is this right?
