### ISSUE TITLE
Minor: Wrong "File incomplete" reporting

### ISSUE THREAD

**Issue by Panayiotis-git** [prusa3d/Prusa-Firmware#2328]
The incomplete file check, searches for the M84 command at the last 20000 bytes of the gcode file.
Since the Slicer generated files contains a ton of comments with the used configuration at the end of the file, there are cases when the 20000 bytes slot misses the M84 command.

Check the attached sample. I have defined 15 extruders.

Possible solution could be to skip the comments.

[FileIncomplete.zip](https://github.com/prusa3d/Prusa-Firmware/files/3852914/FileIncomplete.zip)

**Comment by michalxfanta** [comment]
Thanks for reporting this issue.

**Comment by Panayiotis-git** [comment]
I still get the false warning, but I can continue with the print

**Comment by gudnimg** [comment]
Assigning this to myself so the issue doesnt get closed. 

@Panayiotis-git have you looked into implementing a fix for this? I wonder why the firmware can’t parse the entire file line-by-line.

**Comment by gudnimg** [comment]
I’ve seen on Prusa Forum and Facebook reports that other people are still seeing this.

**Comment by 3d-gussner** [comment]
https://github.com/prusa3d/Prusa-Firmware/pull/4507 solves the issue.
