### ISSUE TITLE
mk2.5s 3.8.1 - "ignore fan error" setting is not ignored after pause and resume

### ISSUE THREAD

**Issue by UltraSalem** [prusa3d/Prusa-Firmware#2331]
mk2.5s printer with 3.8.1 firmware.

I have a dodgy side fan so in the printer settings I have turned off fan warning so that I can still use the printer while waiting for the new fan to arrive (fan spins but isn't sending rpm signal, so I can print fine but the firmware doesn't like it).

However, if I pause the print using the pause option, and then click resume print, the printer will do a fan check and throw a fan error and refuse to resume printing. I have to stop and start the print fresh (the ignore fan error setting stays set correctly in settings).

If the ignore fan warning is set in settings it should also apply to the fan check after pause/resume.

**Comment by leptun** [comment]
@UltraSalem Thanks for reporting. We will fix this in the 3.9 release
