### ISSUE TITLE
add Preheat to last used temperature option on pause menu

### ISSUE THREAD

**Issue by AbeFM** [prusa3d/Prusa-Firmware#2338]
(reposted by request from https://github.com/prusa3d/MM-control-01/issues/162)
When Pause Print is selected, the printer sets the nozzle temperature to 0.

Most of the time Pause is selected, it is to work on something. Since the head lifts, I suggest there is no harm in leaving the nozzle heated for ~1-2 minutes, or until there are no user interactions for a short period.

Also:
I'm printing at, for instance, 220/50. I have a plethora of options to preheat to, but as none of them are the temps I'm using, I have to wait for a temperature change, load, unpause, then wait for it to go to the print temperature from the preset one.
If "Temperature When Paused" was an option it would be a LOT more useful.

At minimum, it is inconvenient. For some materials, it would ruin a print.

**Comment by michalxfanta** [comment]
Thank you for the idea, we will consider its implementation.
