### ISSUE TITLE
Z offset for textured sheet not properly saved after restart

### ISSUE THREAD

**Issue by davebg** [prusa3d/Prusa-Firmware#2340]
Firmware: 3.8.1
First layer calibration for textured sheet is not properly saved after a restart. Even though the value obtained during the calibration is displayed after a restart, the printer ignores it and starts printing with a different offset.
Steps to recreate the issue:
1. Start from a fresh flash of the firmware with cleared previous calibration details
2. Calibrate first layer for Smooth sheet 1. In my case the Z offset for Smooth sheet is -1.250
3. Calibrate first layer for Textured sheet 1. In my case the Z offset for Textured sheet is -1.750
4. After calibration finished run a power off/power on cycle.
5. Start printing with Textured sheet selected from the settings menu and without touching any settings regarding Z offset
6. The print is too high, requires manual adjustment of Live Z to a value of -2.080.
7. After the print finishes perform a power off/power on cycle.
8. Live adjust Z shows -2.080, which was defined during the previous print.
9. Start printing without changing any settings
10. This time the nozzle is too low, requires manual adjustment to -1.750.
11. After the print finishes perform a power off/power on.
12. Live adjust Z shows -1.750
13. Start printing - again the nozzle is too high and requires adjustment to -2.080

This behavior is observed only when both Textured sheet and Smooth sheet are calibrated. If only one sheet is calibrated and used there is no variation in the behavior and the printer keeps the defined Z offset value. 

Printed with offset -2.080
![20191121_104055](https://user-images.githubusercontent.com/9250371/69336512-55456f00-0c67-11ea-8d70-7e15fa5ec9ab.jpg)

Left one printed with offset -2.080 after a restart. To the right, put as a reference - same square printed before the restart again with offset -2.080
![20191121_105138](https://user-images.githubusercontent.com/9250371/69336511-55456f00-0c67-11ea-893c-1c37fcdf941c.jpg)

**Comment by william14235** [comment]
Did you use the new feature that allows you to store more than one sheet on the printer? I think you have to choose your default printing sheet in the settings so you dont have to manually calibrate each time and so you can switch the calibration. Basically, maybe you didn't set your default sheet to textured.
