### ISSUE TITLE
[MK3S][3.8.1] - Selftest shows incorrect failure messages if MINTEMP error occurs during test

### ISSUE THREAD

**Issue by dmerner** [prusa3d/Prusa-Firmware#2350]
Today I was tracking down an issue where my printer was failing prints and only displaying a "MINTEMP fixed" message.

At the beginning of my debugging, I ran a self-test to see if there was any issues reported.  The test would fail during the Y axis test with a "Y axis length" message.  Clicking out of that message would then display the same "MINTEMP fixed" message.

The issue for me ended up being a bad thermistor cable for the heated bed.  If the heatbed cable bundle moved in a certain way it would act like the thermistor was disconnected for a moment and would then fail whatever it was currently doing whether it be a print or a test.

The main problem that I see here is that the selftest shouldn't be showing erroneous fail messages if it is interrupted by a MINTEMP error mid-test.  I ended up wasting time checking the belts and Y axis bearings when the actual problem was something completely unrelated.

I'm not certain if this occurs with the extruder thermistor.  You can probably replicate this issue by unplugging and quickly replugging the thermistor cable from the einsy board during the selftest.

**Comment by michalxfanta** [comment]
Thanks for reporting this issue, we will fix it in one of the next releases.
