### ISSUE TITLE
3.8.1 Print head makes random moves

### ISSUE THREAD

**Issue by mdaneman** [prusa3d/Prusa-Firmware#2358]
After updating to firmware 3.8.1 the printhead takes random moves during print and then comes back. For example it may move all the way to the left, then move back and continue printing (leaving a   hole in the print since it was in the wrong place for a while).  This happens on nearly every print. Reverting to 3.8.0 fixes the issue.   I tried installing 3.8.1 and doing a factory reset on the printer - this still didn't fix the issue.
See the streak and gap in the middle square on the attached image

![RandomHeadMove_3 8 1](https://user-images.githubusercontent.com/35081544/70369596-f55ae500-1870-11ea-84ec-3f2def266029.jpg)

**Comment by michalxfanta** [comment]
Could you send us a used G-code?

**Comment by mdaneman** [comment]
Sure.  Here's the g-code.  However, I've had it happen with other prints as well.

[0p2_140mm_FiveSquare_0.4n_0.2mm_PLA_MK3S_29m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/3940540/0p2_140mm_FiveSquare_0.4n_0.2mm_PLA_MK3S_29m.gcode.zip)

**Comment by 3d-gussner** [comment]
@mdaneman
- Which printer? MK3s, MK3?
- Stock or community or custom firmware?
- Do you print from SD or via USB?
   - If USB how?
   - Did you try another SD card?

**Comment by mdaneman** [comment]
Printer is MK3S using stock firmware. I printed via Octoprint. Didn’t check if printing from SD still has the issue or not.

**Comment by JohnnyDeer** [comment]
@mdaneman, Is this issue still actual with latest FW version and PrusaSlicer?
