### ISSUE TITLE
Calibration starts in the middle of the bed

### ISSUE THREAD

**Issue by william14235** [prusa3d/Prusa-Firmware#2360]
So basically, I was calibrating my printer before a print. It came down, the bed moved all the way to the back, but the extruder went straight to the middle. I tried it again and it worked after I reset the printer. Has anyone else encountered this problem before?

**Comment by william14235** [comment]
Also, this happened twice now

**Comment by 3d-gussner** [comment]
@william14235
- Which printer? MK3s, MK3, MK2.s or MK2.5?
- Which Firmware version?
- Stock or community or custom?
- Do you print from SD or via USB?
   - If USB how?
   - Did you try another SD card?
- What changed?
   - Did it work before (older firmware)?
   - Something else changed?
- Can you reproduce the issue? If so how?
