### ISSUE TITLE
[FEATURE REQUEST] Maintenance intervals

### ISSUE THREAD

**Issue by cvengels** [prusa3d/Prusa-Firmware#2377]
It would be a nice feature to get a maintenance warning after x hours of printing.

For example to retighten all the screws, checking belt tension, cleaning and oiling all shafts and so on. Just like in cars that demand an oil change or inspection every x miles/kilometres.

**Comment by 3d-gussner** [comment]
Like the idea, every environment might be different, dusty place and so on. But in general it is something that could be useful.
- Print time xxxx triggers a message
- Message shouldn't block the printer but at least delay it for a moment every time it starts up
  - until it is acknowledged that it was done

For the users don't want this
- a menu may be useful to enable this feature or not

**Comment by 3d-gussner** [comment]
@Sc0tty83 The Feature issue template is there for a reason, so please try next time to fill it in.
