### ISSUE TITLE
[FEATURE REQUEST]<embed image in GCODE - not just for MINI>

### ISSUE THREAD

**Issue by ruedli** [prusa3d/Prusa-Firmware#2391]
In 2.2 alpha there is support for an embedded thumbnail picturing the printed object. This is only supported for the MINI.

It would be great to also have that (configurable output) feature for other slicer variants, then it e.g. could be made visible in an octoprint plugin, or even with the (windows) browser as thumnails and in preview with a suitable configured GCODE editor / viewer.

**Comment by 3d-gussner** [comment]
@ruedli I think you should open this feature request in https://github.com/prusa3d/PrusaSlicer repository.

**Comment by ruedli** [comment]
oops, that is indeed where it belongs... closing this one... Thx @3d-gussner  !
