### ISSUE TITLE
When pausing a print and cooling down the hotend the cooling fan does not restart when restarting the print

### ISSUE THREAD

**Issue by mrjohnc** [prusa3d/Prusa-Firmware#24]
When pausing a print and cooling down the hotend the cooling fan does not restart when restarting the print. It is possible to restarting it by going into the tune menu but this mean the fan runs constantly not only when needed.

Firmware 3.0.9

**Comment by ayourk** [comment]
If you are pausing an SD card print from the LCD menu, I think I've committed a potential fix via https://github.com/prusa3d/Prusa-Firmware/pull/31/commits/6129c9167d342cf09413a04b837c58c76d10a9e5 which is in my pull request #31

**Comment by mrjohnc** [comment]
@ayourk yes, this issue was from an SD card print, hope your pull request fixes the problem :)

**Comment by ayourk** [comment]
The fix for this should now be merged into the main tree via https://github.com/prusa3d/Prusa-Firmware/commit/ab4f5d25cc4b8c98b21127d960e6eea43e3e384a
