### ISSUE TITLE
strange behavior in calibration menu with 3.1.0-RC1

### ISSUE THREAD

**Issue by pieterbos** [prusa3d/Prusa-Firmware#240]
First - I really like the linear advance feature and usually it prints fine. However, today I encountered something strange with firmware 3.1.0-RC1:

I switched on the printer. It displayed the sorting files message. I then entered the calibration menu. The printer sounded a loud beep from the speaker. Then the printer was very slow to respond in the menu system - only more than a second after turning the dial it would change lines on the screen. It beeped loudly when entering or leaving the calibration menu instead of the usual subtle tick-sound.

I turned the printer off and on again and everything was back to normal.

**Comment by PavelSindler** [comment]
Hello @pieterbos and thank you for reporting it. It is probably the same issue as https://github.com/prusa3d/Prusa-Firmware/issues/226 and it should be fixed by https://github.com/prusa3d/Prusa-Firmware/pull/241 PR.
