### ISSUE TITLE
Don't keep Bed heated if last unload failed

### ISSUE THREAD

**Issue by redlukas** [prusa3d/Prusa-Firmware#2419]
Hardware: i3 MK3S & MMU2S
Firmware: MK3S: 3.8.1, MMU2S 1.0.6
#### Observed Behaviour:
If the last unload of the Filament fails, the Printer goes into "MMU needs attention" mode. This lets the Nozzle cool down, but keeps the Bed warm
#### Expected Behaviour:
The printer checks if the failed unload operation was the last one. In this case, it would still display the "MMU Needs Attention" error, but let the heated bed cool down
#### Advantages if implemented:

- Less danger of the hot bed (fire/burn risk)
- Less power consumption
- If you are lazy like me and use a short bowden tube and a small piece of filament to trick the FINDA when printing in MMU Single mode to avoid the tedious process of loading the filament trough the Buffer the plate will no longer stay hot, even if the print is otherwise finished and this will let the bed cool down.
![IMG_20200104_212853](https://user-images.githubusercontent.com/6354044/72505314-f99afa80-383f-11ea-93ce-f93ebff69e52.jpg)

**Comment by wpegden** [comment]
Maybe it makes more sense for this to be a change in the slicer/gcode?  You just want to unset the bed temperature before the final unload instead of after it.  Logically, if you don't ask the firmware to change the temperature until after the unload, it seems like the correct behavior should be to wait until the load has succeeded.

**Comment by ANTALIFE** [comment]
I suspect the reason for keeping the heatbed on is to keep the part secured to the surface. If it turns off then the thing you are printing will cool enough to naturally shrink and come off the bed

**Comment by redlukas** [comment]
> I suspect the reason for keeping the heatbed on is to keep the part secured to the surface. If it turns off then the thing you are printing will cool enough to naturally shrink and come off the bed

how would that be relevant on the last unload? the print would be finished. I get why the bed is being kept heated on other filament change fails, but this issue is specifically for the last unload.

**Comment by ANTALIFE** [comment]
Ah my bad, missed the "last" in unload

**Comment by 3d-gussner** [comment]
How should the printer know that this was the last unload command?

The printer executes one g-code line after another so if there is a user attention needed it will wait until the user does something or runs in an timeout. The bed temp is hold as @ANTALIFE mentioned to not loose the print.

The processor doesn't have the resources to load all g-code and analyse it.
