### ISSUE TITLE
First layer calibration menu

### ISSUE THREAD

**Issue by Panayiotis-git** [prusa3d/Prusa-Firmware#243]
At i3 MK2S running v3.1.0-RC1, while printing the Calibration > First layer cal.(ibration) pattern, the menu contains invalid options, like Load/Unload filament, Settings, Calibration...

**Comment by Panayiotis-git** [comment]
I've created a pull request with the fix. Please review.

**Comment by Panayiotis-git** [comment]
Test with https://github.com/prusa3d/Prusa-Firmware/pull/309.

**Comment by inquisitiveKangaroo** [comment]
Hi
Thank you for fixing it.)
