### ISSUE TITLE
[BUG]Tone Frequencies on 3.9.0 broken

### ISSUE THREAD

**Issue by midnightsmith89** [prusa3d/Prusa-Firmware#2432]
**Printer type** MK3S
**Printer firmware version** 3.9.0 Beta

**MMU Upgrade** MMU2S
**MMU upgrade firmware version** 1.0.6

**Describe the bug**
  Printer does not change tone notification frequency, just length.  Used to pre 3.7.0
 Read that it is supposed to be fixed in 3.9.0, tested, still does not work.
  
**To Reproduce**
 enter any M300 combination such as below "StarWars" Theme and tone does not change frequency (pitch), only length.
M300 S2959 P150
M300 S0 P150
M300 S2959 P150
M300 S0 P150
M300 S2959 P150
M300 S0 P150
M300 S1864 P300
M300 S0 P150
M300 S5919 P300
M300 S0 P150
M300 S4978 P150
M300 S4978 P150
M300 S4434 P300
M300 S0 P150
M300 S5919 P300
M300 S0 P150
M300 S4978 P150
M300 S4978 P150
M300 S4434 P150
M300 S3729 P300
M300 S0 P150
M300 S5919 P300
M300 S0 P150
M300 S4978 P150
M300 S4978 P150
M300 S4434 P300
  
**Expected behavior**
  Variable frequency or pitch tone to indicate different statuses.
  
**G-code**
Place into printer and run, no need for heatup ect.
Github wont let me attach gcode file.

**Comment by leptun** [comment]
@midnightsmith89 Thanks for reporting. This issue IS planned fot 3.9.0, but there were some issues with this feature for 3.9.0-beta. Hopefully in a few weeks it will be merged into 3.9.0-RC1.

As for uploading gcode files, compress them to a zip file and upload that instead.
