### ISSUE TITLE
  [ENHANCEMENT] Rename "Ambient" temperature to "Einsy"

### ISSUE THREAD

**Issue by Strat00s** [prusa3d/Prusa-Firmware#2441]
**Printer type** - [MK3S]

**Is your enhancement related to a problem? Please describe.**
  IIRC, the "ambient" thermistor is on the Einsy board, so whenever the Einsy gets hot, the thermistor heats up as well, thus giving kinda wrong "ambient" temperature readings.
  
**Describe the solution you'd like**
  Rename the "Ambient" sensor/measurement to "Einsy" or something similar. Because trust me, the air in my room is not sitting at 41°C.

**Comment by wavexx** [comment]
> Rename the "Ambient" sensor/measurement to "Einsy" or something similar. Because trust me, the air in my room is not sitting at 41°C.

Your printer enclosure is too large ;)
