### ISSUE TITLE
[FEATURE REQUEST] tune nozzle temperature per-filament with MMU2S

### ISSUE THREAD

**Issue by wpegden** [prusa3d/Prusa-Firmware#2442]
MK3S+MMU2S

Currently in the "tune" menu, we can choose a nozzle temperature to use instead of the gcode settings.  When using an MMU2S, the MK3S (usually) knows which filament it is currently printing with.  In these cases we should be able to set the nozzle temperature on a per-filament basis.  That way we can tune the nozzle temperature for just a single filament.

**Comment by michalxfanta** [comment]
Thank you for an interesting idea, implementation in the current state would not be trivial, but we will consider it in the future.
