### ISSUE TITLE
  [ENHANCEMENT] collect detailed filament loading statistics (MMU2S)

### ISSUE THREAD

**Issue by wpegden** [prusa3d/Prusa-Firmware#2445]
For the MK3S+MMU2S, it would be helpful if detailed statitics could be logged and checked regarding filament loading and unloading (not just when manual intervention was required).  For example, how often was second loading attempt required?

This would help dial in precise settings for very reliable operation, since the user would have more data to respond to other than total loading failures.

**Comment by wpegden** [comment]
Just to be clear, the idea for these statistics is that they would be collected on a per-filament basis.  So for each filament, one could see how often loading slow moves were required after the initial fast move, how often a completely new loading attempt was made, and how often manual intervention was required.

**Comment by michalxfanta** [comment]
Thank you for an interesting idea, this data would certainly help to identify some printing problems.
