### ISSUE TITLE
[BUG][3.9.0-BETA] Printer resets on MMU filament runout

### ISSUE THREAD

**Issue by vintagepc** [prusa3d/Prusa-Firmware#2464]
**Printer type** - MK3S
**Printer firmware version**-  3.9.0-BETA

**MMU Upgrade** -. MMU2S
**MMU upgrade firmware version** - 1.0.6

**Describe the bug**
Was running in single mode near the end of a spool. The printer paused when the FINDA  detected a runout. It tried to unload but the tail  of the filament got caught. This caused the extruder to chew into the filament until the IR sensor also read 0. At this point the printer  rebooted. 

Possibly related/shared cause to #2301, #1993, but certainly more severe - the linked issues prevent a print from starting, but this situation can result in a failed print after many hours and much wasted material.

**To Reproduce**
Simulate a filament runout followed by a situation where both sensors report 0 - e.g. grinding or perhaps a divot in the filament from a previous grind passing the extruder bondtechs.
  
**Expected behavior**
Printer should pause and MMU should indicate it needs attention. 
  
**G-code**
N/A, can be done with any gcode.

I'm logging this for reference, I should have some time in the next day or two to dive into the issue and either find the cause or even implement a fix. Will keep you posted.

**Comment by jurcja1** [comment]
I would like to add similar bug with beta 3.9.0 FW and MMU2s. 

When filament runs out, printer is waiting for new filament (message on display) to be feeded in MMU unit and then continuing in print, but MMU unit took filament back but does not park selector beside used filament and does not push old filament to take it out. Is anyone facing same issue during testing BETA FW with MMU2s? 

Thank you.

**Comment by vintagepc** [comment]
> I would like to add similar bug with beta 3.9.0 FW and MMU2s.
> 
> When filament runs out, printer is waiting for new filament (message on display) to be feeded in MMU unit and then continuing in print, but MMU unit took filament back but does not park selector beside used filament and does not push old filament to take it out. Is anyone facing same issue during testing BETA FW with MMU2s?
> 
> Thank you.

I believe you're expected to remove the runout leftovers from the rear of the MMU, the reverse of what you'd do to load a new one.

**Comment by jurcja1** [comment]
> 
> 
> > I would like to add similar bug with beta 3.9.0 FW and MMU2s.
> > When filament runs out, printer is waiting for new filament (message on display) to be feeded in MMU unit and then continuing in print, but MMU unit took filament back but does not park selector beside used filament and does not push old filament to take it out. Is anyone facing same issue during testing BETA FW with MMU2s?
> > Thank you.
> 
> I believe you're expected to remove the runout leftovers from the rear of the MMU, the reverse of what you'd do to load a new one.

I thought and that was in previous version, that when filament runs out printer is waiting and filament is in MMU unit like on the picture.

![59256420-32347f00-8c34-11e9-9e1c-62b43d67c8ab](https://user-images.githubusercontent.com/27567377/73871539-52155480-484e-11ea-9d27-b190a9b80aa3.png)

But filament it pushed back in rear PTFE tube completely.

**Comment by vintagepc** [comment]
I could very well be wrong.  👍

**Comment by vintagepc** [comment]
Filed #2466 to address this. Both of my situations were caused by a filament runout while the current filament was in an unknown state. 
 The PR makes it handle this state gracefully  by requiring a user filament change.
