### ISSUE TITLE
Feature request: Add "Max acceleration" to Tune menu

### ISSUE THREAD

**Issue by cool-RR** [prusa3d/Prusa-Firmware#247]
It'll be nice if we could edit the maximum acceleration while a print is in program using the Tune menu.

**Comment by joeynuggetz** [comment]
id like this too

**Comment by leptun** [comment]
This is not possible since it is changed a lot inside the gcode and it wouldn't stick. Just like with temperatures after a certain layer: If you change it manually and then it is changed in gcode, the gcode value is used

**Comment by maximlevitsky** [comment]
Actually this is very possible to do, just the same way as the speed and extrusion flow override is done.
Just make it a percent of the actual value the gcode sets.
In the same way the fan speed could be modified safety from the tune menu, by using a percent,
of the speed that gcode sets.
