### ISSUE TITLE
  [ENHANCEMENT] Warn that stealth mode can't be used for belt calibration.

### ISSUE THREAD

**Issue by Strat00s** [prusa3d/Prusa-Firmware#2472]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MK3s

**Is your enhancement related to a problem? Please describe.**
I was trying to "calibrate" my belts via the belt status option inside calibration menu and every time, a printer told me that there was an error and that I should "check axis length x". But all I needed to do was to disable stealth mode.

P.S.: The calibration was kinda useless anyway, as even after some serious tightening, the belt status went up instead of down.
  
**Describe the solution you'd like**
Maybe add a warning that it can't be calibrated in stealth mode or automatically disable the stealth mode before the "calibration".

**Comment by leptun** [comment]
@Strat00s Thanks for reporting.
We’ll fix this issue for the final 3.9.0 release.

**Comment by vintagepc** [comment]
That should also fix #2356... good find. Also, derp on my part for not cluing in that stealth mode might impact this.

**Comment by vintagepc** [comment]
I have a tentative fix in https://github.com/vintagepc/Prusa-Firmware/tree/%232472-%232161-belt-test-stealth-mode
Will test tonight and PR.
