### ISSUE TITLE
[BUG]MMU2S -MK3S - wrong filament selected after "MMU needs attention"

### ISSUE THREAD

**Issue by MB3Y** [prusa3d/Prusa-Firmware#2476]
**Printer type** MK3S
**Printer firmware version**  3.8.1_2869
**MMU Upgrade** MMU2S
**MMU upgrade firmware version 1.0.6-372

**Describe the bug**
- I ran into a "MMU needs user attention" (F2 didn't retrack until the end, blocking F1 to come up)
- My solution was : retract manual F2 and press the MMU2 reset button to let it figure out how to continue
- Result: MMU resets, does not calibrate the Filament position and hence starts feeding the current filament (still being F2)
  
**To Reproduce**
donno.. I prefer not to get that MMU needs user attention :)
  
**Expected behavior**
The MMU&MK3S should first of all ensure calibration of filament position before it attempts to feed filament.
As I only got this once: Suppose that I did not retrack the filament far enough - hence it's partly my error to block the calibration of filament position as filament is blocking selector to move...
...also in that case I'd expect the machine NOT to start feeding filament, but to go back in error mode, allowing me to figure out what is wrong and still correcting it. I haven't paid attention... but I don't know if it is the MMU or the MK3S that holds the filament position?? MK3S shows "F?" at startup... so maybe that guy is holding the filament position... (which I would find rather strange...)
In the error condition the MK3S did show "F1" on screen! while "F2" was in fact used in the print - so at least there was an error in the synchronisation of both units... wouldn't it be correct to recalibrate filament after each "MMU needs attention"?!?
Hence my suggestion to solve these type of problems: have MK3S force the filament unknown state "F?" and force MMU2S to recalibrate - only communicate on filament availability after good calibration and only print when filament availability is correctly in sync between both MK3S and MMU2S
  
**G-code**
[MoneyPileBase-v20_0.15mm_PLA_MK3SMMU2S_3h53m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/4177435/MoneyPileBase-v20_0.15mm_PLA_MK3SMMU2S_3h53m.gcode.zip)

**Comment by gudnimg** [comment]
Adding this ticket to our 3.13 milestone as a reminder to close this issue. `MMU needs user attention` is no longer a thing in the upcoming release :)

**Comment by gudnimg** [comment]
Closing as this is now resolved with FW 3.13.0 and MMU FW 3.0.0 :)
