### ISSUE TITLE
  [ENHANCEMENT] Better factory_reset() implementation

### ISSUE THREAD

**Issue by leptun** [prusa3d/Prusa-Firmware#2483]
This menu uses an entirely proprietary implementation and is really wasteful in general.
Also, the text string are not PROGMEM! (wasted RAM).
Add more actions to the menu, such as `Clear UVLO` and mark calibrations as completed for debugging (disables the annoying startup screen on a factory reset EEPROM).

This is a note for later on.

**Comment by vintagepc** [comment]
Linking #2099 for reference.

**Comment by ManuGithubSteam** [comment]
+1
