### ISSUE TITLE
[ENHANCEMENT] Better "Belt test" implementation

### ISSUE THREAD

**Issue by leptun** [prusa3d/Prusa-Firmware#2484]
As of now, the function always raises the Z a certain amount. `raise_z_above()` should be used instead.
Also the LCD rendering could be improved.

Note for later.

**Comment by vintagepc** [comment]
I'm happy to include this in my open PR on the function. 
Is there a suggested layout for the LCD rendering or is that more of a "could be better, not sure how yet"?

**Comment by leptun** [comment]
The layout is mostly ok. I’m more concerned about the way the screen is rendered.

**Comment by vintagepc** [comment]
Ah, the custom LCD_belttest_print function that redraws everything? I did think that could be cleaned up. Something more compact/efficient that only updates the relevant display section, correct?

**Comment by leptun** [comment]
Yep
