### ISSUE TITLE
[QUESTION] LCD is blank and I'm getting "W25X20CL not responding." in the console

### ISSUE THREAD

**Issue by papaiatis** [prusa3d/Prusa-Firmware#2489]
I'm about to finish building my MK3S printer. I had some troubles with flashing the firmware that I reported here: https://github.com/prusa3d/Prusa-Firmware/issues/2486
Now I (probably) have a working bootloader and firmware and wanted to start up the machine but the screen just not turning on at all. I checked the cables 100x times, tried them in reverse, swapped them to no avail. 
I'm seeing the following output in the console with two LCD related errors:

![image](https://user-images.githubusercontent.com/3688096/74339558-a1a2d580-4da4-11ea-84f0-fa62f01d69b0.png)

I went through all the reported issues here that mentions W25X20CL but neither of them helped.
I tried disconnecting all cables except power from PSU and LCD cables, didn't help.
I tried flashing earlier firmwares with PrusaSlicer and also tried flashing the recent one using Arduino IDE, didn't help.
I tried commenting out `#define W25X20CL` but then the buzzer just keeps beeping when I turn the printer on. 
I can measure 5V between pin 9 and 10 on EXP1 connector so probably LCD gets the power. 

I also have a spare Arduino Mega and RAMPS 1.4 on which I'm still running an old version of Marlin. I connected the LCD to this board, and connected the board via USB to my laptop and the LCD was working. 

On the back of the LCD I see these texts: "RepRapDiscount Smart Controller" and "Robotale 3D_Print" and "2013-0729 SmatrConteallerD.PCB". It is a red color PCB.

I'm out of ideas now. 
Could someone please help?

**Comment by leptun** [comment]
What happens if you only connect the P1 cable? In my case only the display works correctly (and click button). Try this so that we can really rule out the connector possibility.

I can only help you with small steps so that I can maybe figure out what is going wrong.
Also, is the LCD identical to the one on the Prusa? Maybe a picture of the back of the lcd pcb?

**Comment by leptun** [comment]
I find it really weird that the cable swapping and reversing didn’t help in any way. The buzzer thingy is the way my printer behaved at some point when I wired my lcd the wrong way.

**Comment by papaiatis** [comment]
Connecting only P1/EXP1 resulting in this output:

![image](https://user-images.githubusercontent.com/3688096/74368218-7a173180-4dd3-11ea-990f-d97ab4b48539.png)

Still, the LCD is blank. Not even the backlight turns on.
If I swap EXP1 with EXP2 then the screen flickers for a couple of times but that's it.

**Comment by leptun** [comment]
This still sounds really weird. At the very least with only P1 connected the SPI is no longer broken.
Which EXP2 connector did you connect? P1board-P2display or P2board-P1display?

**Comment by papaiatis** [comment]
![IMG_20200212_201140](https://user-images.githubusercontent.com/3688096/74368462-fb6ec400-4dd3-11ea-854d-19765039f9e8.jpg)
![IMG_20200212_201158](https://user-images.githubusercontent.com/3688096/74368474-04f82c00-4dd4-11ea-9a9b-4d25cd658862.jpg)

**Comment by papaiatis** [comment]
> Which EXP2 connector did you connect? P1board-P2display or P2board-P1display?

Sorry, I'm not sure I follow this question. 
By default it should be EXP1 -> P1 and EXP2 -> P2, right? 

Indeed it is really weird. I'm thinking maybe there is still something wrong with the bootloader/firmware. Or I have a faulty Einsy board.

**Comment by leptun** [comment]
Just pointing it out, the connector housings on the lcd module seem to be rotated 180deg compared to the official prusa lcd.
![image](https://user-images.githubusercontent.com/17808203/74368980-45a87300-4ddd-11ea-99b9-ace6ce81410c.jpeg)

**Comment by leptun** [comment]
> > Which EXP2 connector did you connect? P1board-P2display or P2board-P1display?
> 
> Sorry, I'm not sure I follow this question.
> By default it should be EXP1 -> P1 and EXP2 -> P2, right?
> 
> Indeed it is really weird. I'm thinking maybe there is still something wrong with the bootloader/firmware. Or I have a faulty Einsy board.

You said you did some swapping, so I was asking which way you connected them just so that I was sure I understood the way you connected them.

**Comment by papaiatis** [comment]
Okay, by swapping I meant EXP2 -> P1 and EXP1 -> P2. 

> Just pointing it out, the connector housings on the lcd module seem to be rotated 180deg compared to the official prusa lcd.

Well, that could be the indeed the problem. Unfortunately I can only plug the connectors in one way. So let me cut off that piece of plastic that prevents me to doing so.

**Comment by leptun** [comment]
I think that you can carefully slide the plastic cover off and insert it the other way on the pcb. The metal pins should remain on the board.

**Comment by papaiatis** [comment]
OMG!!! That was it!
I carefully removed the cover and plugged the cables 180degrees and it worked!
I own you a lot. I really appreciate your time and help!
I'll create new ribbon cables and will put the connector the other way around so I can put the covers back.

**Comment by leptun** [comment]
Glad I could help.
