### ISSUE TITLE
Is there any planing for making the new firmware compatible with the MKI?

### ISSUE THREAD

**Issue by Maaajaaa** [prusa3d/Prusa-Firmware#25]
Hi,
I was wondering if Prusa Research was working on making the newer firmware compatible with the MKI, since e115c5145f61dbe6926cfb2ac6d678c4e75ab5d2 is the latest commit that works with the MKI. If not I would like to do that.

**Comment by PavelSindler** [comment]
We would like to make new firmware compatible with MKI, but there are another tasks with higher priority now, so unfortunatelly I can't tell you the completion date.
