### ISSUE TITLE
[BUG] Pulls out filament which is not there

### ISSUE THREAD

**Issue by espr14** [prusa3d/Prusa-Firmware#2501]
i3 MK3S FW 3.8.1

1. Printer has no filament inserted. 
2. Start printing.
3. Printer tries to pull out filament even sensor say 0 !!!

Should not pull out or should it?

**Comment by leptun** [comment]
What do you mean by pulling out? Is it the filament change routine that you are talking about? (Press the knob to unload...)
If yes, then this is normal as from the firmware’s perspective a filament runout just occurred.

**Comment by espr14** [comment]
Yes, it's about automatic unloading. I can imagine situation where it makes sense.
