### ISSUE TITLE
  [ENHANCEMENT]Give Control Over Mintemp/Maxtemp Error

### ISSUE THREAD

**Issue by sarf2k4** [prusa3d/Prusa-Firmware#2506]
Applies for all printer I presume.

I recently got my printer broken due to a long print which has a good first layer, the print job supposed to be 9h 30m but when I came back home it became a huge blob and mess. I noticed the printer's screen showed "ERR: mintemp" and I checked further, thermistor wire snapped due to the blobs too. I am unable to go to the printer's menu to test anything either due to the lock down. Thanks to that my house didn't get caught in fire because of thermal runaway, my very first to be precise. The only thing I can control is long press the knob to raise the z axis.

My solution/enhancement to this here is, keep show in the info screen that mintemp error still present, let the user go into the menu and do everything else to test other features if it's still functional rather than a full lock down. For example if the hotend's thermistor not plugged or wire has been snapped/broken, prevent that element from being used such as heating it up, but let the user able to heat up the heatbed. And supposed to be vice versa if the heatbed has mintemp/maxtemp error, prevent the bed from heating up or if both has mintemp/maxtemp error, prevent both from being heated up while retaining all other controls such as moving all the axis, fan control, also prevent to print from sd as well if one of the min/max temp error are present.

**Comment by vkhurana** [comment]
It should be pretty easy to change the value and recompile - https://github.com/prusa3d/Prusa-Firmware/blob/d167b3bd787efcdd55e94cbb80bbbaba482c4285/Firmware/variants/1_75mm_MK3-EINSy10a-E3Dv6full.h#L292

I'm not sure if Prusa3D recommends doing this though? Maybe the devs can recommend something else?
