### ISSUE TITLE
  [ENHANCEMENT] Fan is on while waiting for nozzle heating

### ISSUE THREAD

**Issue by espr14** [prusa3d/Prusa-Firmware#2518]
i3 MK3S FW 3.8.1

1. Printer is printing
2. Filament runs out
3. Printer moves to the corner and turns nozzle heating off
4. I press button to start heating
5. Front fan is still running which slows down the heating.

Solution: turn fan off during heating and then turn it back on.

**Comment by Photogad** [comment]
+1

**Comment by ManuGithubSteam** [comment]
+1 
This would alsp speed up normal heating of the alu block not just at a filament change...

**Comment by gudnimg** [comment]
For filament change this issue was fixed recently here https://github.com/prusa3d/Prusa-Firmware/pull/3746 (will be included in 3.13)

For resuming a print from RAM, this will be this will be fixed here https://github.com/prusa3d/Prusa-Firmware/pull/3443

**Comment by Prusa-Support** [comment]
Hello, the new FW 3.13.0 is out, merging the fixes for this issue.
Please give the new firmware a try and possibly share feedback.

Michele Moramarco
Prusa Research

**Comment by espr14** [comment]
I sold my i3 so no way how to check that.
