### ISSUE TITLE
Should Bed and Finda Temperatures are 28°C immediately after switching on printer

### ISSUE THREAD

**Issue by jsilva-iii** [prusa3d/Prusa-Firmware#2530]
Please, before you create a new question, please make sure you searched in open and closed issues and couldn't find anything that matches.

**What is your question?**

**Comment by leptun** [comment]
Please close this duplicate/mistake issue

**Comment by jsilva-iii** [comment]
Today the offset was only two degrees, I verified the same result by flashing with FW 3.8 and then 3.9 RC1.
