### ISSUE TITLE
What should Bed and Finda temperatures be immediately after switching on printer

### ISSUE THREAD

**Issue by jsilva-iii** [prusa3d/Prusa-Firmware#2531]
I updated to FW 3.9.0 RC2 today on my MK2.5S with MMU2S - The room temperature was 24°C, I have an enclosure with a thermometer and it was showing 24.5° - Immediately on powering on the printer the two temperatures(Finda and Bed) were 28°. Prior to the update,  the Finda and bed temperatures were pretty close to the temperature that was being indicated on my enclosure thermometer.  Why the reason for the 4° increase in temperature?

**Comment by leptun** [comment]
There was no increase in temperature. The thermistors always had an offset.

**Comment by gudnimg** [comment]
I assume the question was answered. Closing as the Github issue is stale.
