### ISSUE TITLE
[QUESTION]Error message when compiling - Could not determine Eclipse version

### ISSUE THREAD

**Issue by killerb77** [prusa3d/Prusa-Firmware#2542]
Trying to compile 1.06 version and when compiling I get this error message:

-- Could not determine Eclipse version, assuming at least 3.6 (Helios). Adjust CMAKE_ECLIPSE_VERSION if this is wrong.

I am running pop os 19.10. using the build.sh script.

Everything else seems to be ok.

Here is the full output:

bmw@pop-os:~/Downloads/MM-control-01$ ./build.sh 
rm: cannot remove '*': No such file or directory
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- The ASM compiler identification is GNU
-- Found assembler: /home/bmw/Downloads/MM-build-env-1.0.0/avr/bin/avr-gcc
-- Could not determine Eclipse version, assuming at least 3.6 (Helios). Adjust CMAKE_ECLIPSE_VERSION if this is wrong.
-- Check for working C compiler: /home/bmw/Downloads/MM-build-env-1.0.0/avr/bin/avr-gcc
-- Check for working C compiler: /home/bmw/Downloads/MM-build-env-1.0.0/avr/bin/avr-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/bmw/Downloads/MM-build-env-1.0.0/avr/bin/avr-g++
-- Check for working CXX compiler: /home/bmw/Downloads/MM-build-env-1.0.0/avr/bin/avr-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bmw/Downloads/MM-control-01-build
[40/40] Generating HEX image
bmw@pop-os:~/Downloads/MM-control-01$

Any ideas on how to clear the error message?

**Comment by leptun** [comment]
This is the bug tracker for the printer firmware. For MMU2/S firmware, please post here: https://github.com/prusa3d/MM-control-01
