### ISSUE TITLE
[BUG] After Belt test the X,Y steppers are locked.

### ISSUE THREAD

**Issue by ochm** [prusa3d/Prusa-Firmware#2547]
**Printer type** - MK3S
**Printer firmware version**-  3.9.1-RC1

**Describe the bug**
When printer belt test routine is finished, the X, Y steppers are locked.
  
**To Reproduce**
Run Belt test and when finished try to move bed or extruder by hand.
  
**Expected behavior**
After Belt test the X and Y steppers should be released immediately,.
  
**G-code**
N/A

**Video**
N/A

**Comment by leptun** [comment]
@DRracer this issue is not fixed. Please reopen the issue.
