### ISSUE TITLE
[FEATURE REQUEST] MMU2 random color change

### ISSUE THREAD

**Issue by flinke-flasche** [prusa3d/Prusa-Firmware#2548]
is it possible to integrate a random color change for the MMU2 like the Palette 2?

Maybe it's possible to insert some values like 
- how often you like to change
- which of these extruder you like to use -> 1, 2, 3, 4, 5 (checkboxes for each extruder)
- min. Number of lines each color
- max. Number of lines each color
- purge on/off

**Comment by vintagepc** [comment]
This would need to be built into the slicer (PrusaSlicer) as it would need to account for the wipe tower etc - I'd suggest you move your feature request there.

The printer firmware alone cannot do that. (sorry)

**Comment by flinke-flasche** [comment]
Oh,  yes you're right. i thought i posted it on Prusa Slicer.
