### ISSUE TITLE
[BUG] uncontrolled movements of the stepper motors   

### ISSUE THREAD

**Issue by ixtrader** [prusa3d/Prusa-Firmware#2555]
When selecting "Print from SD card" and navigate to deeper subdirectory some of the stepper motors are moving in arbitariy directions. The only way to stop this ist to restart the system.

Software version prusa3d_fw_3_8_1_MK3.
Printer MK3 no upgrade
I can reproduce the problem with the following steps using this
[directory structure](https://forum.prusaprinters.org/wp-content/uploads/wpforo/default_attachments/1585079980-prusaMK3SelectProblem.zip)

1. Powering mk3 up and inserting SD Card.
2. navigate trough directory of SD Card. 
3. When reaching Directoy
      \1\2\3\4\5\MasterSpool_V4_002_Export3_PARTA_RTP-pet.gcode
   the steper motors are starting to move uncontrolled.

I investigated the problem a little bit deeper. 

    Reformatted SD Card.  -> problem exists
    rewirtten Firmware 3.8.1 -> problem exists
    downgrade to Firmware 3.7.2 -> problem resolved

by downgrading to Firmware 3.7.2 the problem was resolved.

There might be a bug in your memory management.

**Comment by leptun** [comment]
Does the problem go away if you use 3.9-RC1?

**Comment by vintagepc** [comment]
For reference I took a look at this in the original forum thread and I could not repro the issue with the current RC:
https://forum.prusaprinters.org/forum/original-prusa-i3-mk3s-mk3-hardware-firmware-and-software-help/uncontrolled-movements-of-the-stepper-motors/#post-201736

**Comment by ixtrader** [comment]
I tried the current 3.9.0 RC1. Within this version the printer can select the problematic Directory.
But you should investigate why the problem exists in Version 3.8,1. The problem might be serious and can affect a complet other funtion in the new RC1.

**Comment by vintagepc** [comment]
It just occurred to me that at some point @leptun showed me a video with something similar going on, so if it's no longer occurring then I am reasonably confident that the underlying issue was found and fixed, and that it didn't just magically go away.

**Comment by TheDuggem** [comment]
It sounds similar to #2237

**Comment by leptun** [comment]
It sounds really similar and that’s the issue. I’ve already fixed it before, but somehow it came back because of something else.
I have a suspicion of what might go wrong, but I’m not sure.
