### ISSUE TITLE
[BUG]URGENT - Can't downgrade firmware

### ISSUE THREAD

**Issue by forestqc69** [prusa3d/Prusa-Firmware#2567]
MK3 - 3.9.0-RC

After having trouble with the print speed too slow with 3.9.0, I decided to flash back the 3.8.1 version, but I won't downgrade.  The procedure goes through with PrusaSlicer/Upgrade firmware, but when I look at the support menu on the printer, it's still 3.9.0-RC showing. And the new features of 3.9.0 are still present on the printer (different text and menus)

**Comment by forestqc69** [comment]
Could flash a freshly downloaded version..

**Comment by leptun** [comment]
Please provide the logs from the Update window in PrusaSlicer
