### ISSUE TITLE
[BUG] The Move Extruder menu ignores the M302 (Allow cold extrude)

### ISSUE THREAD

**Issue by Panayiotis-git** [prusa3d/Prusa-Firmware#2577]
The M302 command allows for a cold extrusion. The following sequence of commands indeed moves the extruder, even with cold hotend:
M302
M83
G1 E4

But the Move Extruder by the Settings menu, responds with the "Preheat the nozzle!" error.

Printer type: MK3S
Printer firmware version: 

Expected behavior
  The Move Extruder by the Settings menu, should allow the movement of the extruder, if a M302 (or M302 S<temp>, where temp < current) has already been sent to the printer.

**Comment by Panayiotis-git** [comment]
It seems that at the `ultralcd.cpp`, the method `lcd_move_e()` compares the hotend temperature with the default `EXTRUDE_MINTEMP`, instead of the `extrude_min_temp` that the M302 sets.

Also, the `EXTRUDE_MINTEMP` is used at several places in the source. If the `M302 S<temp>` is supposed to override the default `EXTRUDE_MINTEMP`, then the use of the default value instead of the override should be revisited.

**Comment by leptun** [comment]
@Panayiotis-git Started working on this issue. https://github.com/leptun/Prusa-Firmware/tree/MK3-cold_extrude
Right now, my only real issue is that the code size increases quite a bit, something I don't like.
Also, I haven't tested the changes yet (ItShouldWork™, but who knows ¯\\\_(ツ)\_/¯).
