### ISSUE TITLE
[QUESTION] Code weirdness in G80

### ISSUE THREAD

**Issue by leptun** [prusa3d/Prusa-Firmware#2579]
```
		if (degHotend(active_extruder) > EXTRUDE_MINTEMP && temp_cal_active == true && calibration_status_pinda() == true && target_temperature_bed >= 50) {
			current_position[E_AXIS] += default_retraction;
			plan_buffer_line_curposXYZE(400, active_extruder);
		}
```
This snippet of code at the end of G80 makes no sense. Why only unretract when Temperature calibration is used?

**Comment by Panayiotis-git** [comment]
At the beginning of the G80 command there is the following code:
```
#ifndef PINDA_THERMISTOR
		if (run == false && temp_cal_active == true && calibration_status_pinda() == true && target_temperature_bed >= 50)
		{
			temp_compensation_start();
			run = true;
			repeatcommand_front(); // repeat G80 with all its parameters
			enquecommand_front_P((PSTR("G28 W0")));
			break;
		}
        run = false;
#endif //PINDA_THERMISTOR
```
The `temp_compensation_start()` function, does a retraction:
```
	if (degHotend(active_extruder) > EXTRUDE_MINTEMP) {
		current_position[E_AXIS] -= default_retraction;
	}
	plan_buffer_line_curposXYZE(400, active_extruder);
```

I think that the unretract should be enclosed in a:
`#ifndef PINDA_THERMISTOR`

**Comment by leptun** [comment]
Thanks, that makes a lot more sense.
Now that I think about it, why don’t we always retract during MBL? It just seems logical doing so.

**Comment by vintagepc** [comment]
On the topic of hidden gems, I found this lurking in lcd.cpp:

```
#ifdef VT100
 uint8_t lcd_escape[8];
#endif
```
What is a VT100,you ask? 🤣 
https://en.wikipedia.org/wiki/VT100

**Comment by leptun** [comment]
@vintagepc it’s not hidden code, it is my code :).
The vt100 codes are escape sequence of characters that trigger a certain terminal command. In our case, we had home and set cursor that were useful for the lcd.
These were quite wasteful, so I changed the code to not use them anymore. I commented out the code so that I could save close to 1KB of flash

Edit: fix misinformation

**Comment by vintagepc** [comment]
Interesting - either way it gave me a good laugh!
