### ISSUE TITLE
[BUG]Preheat (sub)menu

### ISSUE THREAD

**Issue by espr14** [prusa3d/Prusa-Firmware#2587]
i3 MK3/S FW 3.9.0 RC1

Preheat menu has items (PLA, PETG, ...) with arrow (->) at the right side. This indicates sub menu but there is no sub menu. Can you remove the arrows?

**Comment by Panayiotis-git** [comment]
The reason for the arrow '>' is that the screen used as the Preheat menu, is also used for the Load/Unload/Eject/Cut filament and even for the First layer calibration. Except for the preheat screen, for all the other choices the selection of a filament item goes to a 'wait for the heating to finish' screen.
