### ISSUE TITLE
[BUG]Unable to print after filament insertion

### ISSUE THREAD

**Issue by espr14** [prusa3d/Prusa-Firmware#2588]
i3 MK3/S FW 3.9.0 RC1

1. Start printer without filament
2. Go to "Print from SD" card menu
3. Insert filament (autoloads)
4. Select a file
5. Nothing happens but should start printing instead

**Comment by leptun** [comment]
I’ve also noticed that there are certain actions that make the sd print become stuck when starting.
Pretty sure that in my case I did no autoloading.
Is it a MK3 or a MK3S? The filament sensor implementation is different based on what printer model you have

**Comment by espr14** [comment]
I have MK3S MMU2 that uses optical gate.
