### ISSUE TITLE
[QUESTION] Code that sends remaining print time

### ISSUE THREAD

**Issue by radimkohout** [prusa3d/Prusa-Firmware#2604]
**What is your question?**
Which part of code replies to M73:
NORMAL MODE: Percent done: x; print time remaining in mins: y

**Comment by leptun** [comment]
https://github.com/prusa3d/Prusa-Firmware/blob/66ffb8489ac34cd62605ea744e262c429f7c479f/Firmware/Marlin_main.cpp#L6188-L6211

**Comment by radimkohout** [comment]
Thanks
