### ISSUE TITLE
[BUG]Print speed changes by 1% after changing the speed

### ISSUE THREAD

**Issue by espr14** [prusa3d/Prusa-Firmware#2611]
i3 MK3S FW 3.9.0 RC1

1. Start print
2. Increase or decrease the speed by turning the wheel during the print
3. Once you stop, the speed changes after 1 second by 1% up or down (depending on the direction of user change).

For example, I go up to 200% and after a second it will show 201%.

**Comment by leptun** [comment]
Fixed by #2585

**Comment by Photogad** [comment]
It's not just in the printing speed, it's everywhere in the whole menu. I think the LCD on the mk3 is just too laggy. Lots of times I'll be scrolling with the wheel to the print I want to start  on the SD card, and I think I have the right one selected, but just as I click it to start the print, it selects the wrong one and starts printing the wrong thing.

I've since learned to operate the LCD screen much slower and wait a few seconds before clicking anything.

**Comment by espr14** [comment]
The LCD is slow because board is slow. There are lot of compromises so it's hard to do it better. But take a look on Original Prusa Mini. It uses faster board with more RAM. After initialization the LCD is much quicker.

**Comment by Photogad** [comment]
> The LCD is slow because board is slow. There are lot of compromises so it's hard to do it better. But take a look on Original Prusa Mini. It uses faster board with more RAM. After initialization the LCD is much quicker.

Any chance well ever see a new board/lcd as an addon to the mk3?  Maybe mk3.5 .... Hmm

**Comment by espr14** [comment]
There's a chance, always. But hard to say when. Still, you can take HW from MINI, put it in MK3 and modify the MINI FW (larger print volume). However, MINI board provides single Z driver and there could be other issues.

**Comment by leptun** [comment]
> It's not just in the printing speed, it's everywhere in the whole menu. I think the LCD on the mk3 is just too laggy. Lots of times I'll be scrolling with the wheel to the print I want to start on the SD card, and I think I have the right one selected, but just as I click it to start the print, it selects the wrong one and starts printing the wrong thing.
> 
> I've since learned to operate the LCD screen much slower and wait a few seconds before clicking anything.

The Print from SD menu is notorious for this as well. I have a PR that greatly increases the performance in that menu. You could give it a try. #2405

**Comment by Photogad** [comment]
> > It's not just in the printing speed, it's everywhere in the whole menu. I think the LCD on the mk3 is just too laggy. Lots of times I'll be scrolling with the wheel to the print I want to start on the SD card, and I think I have the right one selected, but just as I click it to start the print, it selects the wrong one and starts printing the wrong thing.
> > I've since learned to operate the LCD screen much slower and wait a few seconds before clicking anything.
> 
> The Print from SD menu is notorious for this as well. I have a PR that greatly increases the performance in that menu. You could give it a try. #2405

will that make it into an official release? I'm stil learning how to compile firmware

**Comment by leptun** [comment]
Maybe, the soonest might be 3.10 tho. Enough PRs for now. If you want, I can send you a compiled binary.
