### ISSUE TITLE
Give credit where credit is due

### ISSUE THREAD

**Issue by sorki** [prusa3d/Prusa-Firmware#2625]
Unlike `Prusa-Slicer` the README is missing a note that this a derivative work based on `Marlin` firmware. Please fix.

**Comment by jimhigson** [comment]
There's a repo for the slicer separate from the firmware repo.

**Comment by sorki** [comment]
slicer repo is fine.

**Comment by wavexx** [comment]
@sorki can you reticulate more splines over the README and see whether the citation seems fine.

**Comment by sorki** [comment]
Sure @wavexx - Citation and the whole intro does look good to me, thank you!
