### ISSUE TITLE
[BUG] Firmware crashes to random characters on screen when hotend thermal runaway is triggered

### ISSUE THREAD

**Issue by jimhigson** [prusa3d/Prusa-Firmware#2626]
**Printer type** - MK2.5S
**Printer firmware version**-  3.8.1

**MMU Upgrade** - no
**Describe the bug**
Please see [this thread in the forum](https://forum.prusaprinters.org/forum/original-prusa-i3-mk2.5s-mk2.5-hardware-firmware-and-software-help/printer-screen-crashes-displays-random-gibberish-chars-mid-print/) for a screenshot and discussion

There is a bug in the firmware whereby the printer screen instead of properly reporting a thermal runaway error, it shows random chars. This makes it very difficult to diagnose runaway issues without an octopi since there is no reporting of what the problem is.

We can see that this is a runaway from the console in octopi.
  
**To Reproduce**
Start a print, trigger a mintemp in some way. In my case this was caused by a faulty thermistor. Probably unplugging the thermistor mid-print would work.
  
**Expected behavior**
On causing the mintemp, random chars will be shown on the screen rather than an error message.
  
**G-code**
Applicable to any g-code.

**Video**
  Please attach a video. It usually helps to solve the problem.

![14A6B8CE-22D8-48B8-8DF4-E66397DDD6B7-600x500](https://user-images.githubusercontent.com/136306/79977543-5852be80-8496-11ea-914c-ded84fe9e503.jpeg)

![Screenshot-2019-11-24-at-22 52 04](https://user-images.githubusercontent.com/136306/79977647-86380300-8496-11ea-8aad-b0a3785ee645.png)

**Comment by leptun** [comment]
Already fixed in 3.9-RC1

**Comment by 3d-gussner** [comment]
@jimhigson Please consider to close this issue as this has been fixed already.
