### ISSUE TITLE
[ENHANCEMENT] Allow to change print speed while not printing

### ISSUE THREAD

**Issue by yschroeder** [prusa3d/Prusa-Firmware#2655]
When I change the print speed in the `Tune` menu during a print, this speed also applies for subsequent prints. If I do not want to print the next print with the increased speed as well, I have to wait until the new print starts for the `Tune` menu to become available and set the speed back to 100%.

I would like to be able to set this speed while NOT printing (when the printer is idle).

**Comment by leptun** [comment]
But you already can do that. Just spin the knob while in the status screen.

**Comment by yschroeder** [comment]
Interesting I did not know that... Anyway, the `Tune` menu could be available while not printing, right?

**Comment by leptun** [comment]
Don’t really see the point in doing so. Most, if not all options in the Tune menu are also available in the Settings menu. The Settings menu just has extra options that are not available during the print

**Comment by yschroeder** [comment]
Could we then still integrate the speed setting into the settings menu? Then we have a named option for this (for completeness).
