### ISSUE TITLE
[BUG]Autoload can be triggered during "Is colour clear" message

### ISSUE THREAD

**Issue by awenelo** [prusa3d/Prusa-Firmware#2667]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK3S
**Printer firmware version**-  3.8.1, 3.9.0-RC1, 3.9.0-RC3, 3.9.0

**Describe the bug**
After loading/autoloading filament, a message asking "Is the filament is extruding and in the right color?" is displayed. If the filament sensor goes from 1 to 0 and back to 1 while this message is displayed, once the current loading procedure is done, it runs the loading cycle again. Also, during the second loading cycle, the printer chirps, as if it were about to display a message but doesn't do anything.
  
**To Reproduce**
Enable Autoload
Preheat
Insert filament until the filament sensor is triggered
Remove filament
Wait for the "Is the filament extruding and with the right color?" is displayed
Insert filament
Click "Yes"
Autoloading re-starts
Wait for chirp
No message appears
  
**Expected behavior**
If filament is newly detected during the message, exit loading procedure and then start again,  ignore it, or display the expected message.

**Comment by floridaservices** [comment]
I have noticed this behavior as well.  , running the 2.5S variant, 3.9.0-RC1
