### ISSUE TITLE
SOUND when preheat is done

### ISSUE THREAD

**Issue by angelozap** [prusa3d/Prusa-Firmware#2673]
Every time you set a preheat you have always to check if the printer has reached the temperature directly on the display. The same thing happens when a file is ready to be printed after the printer has heated up, and a small amount of material has leaked from the nozzle and you want to remove it before the calibration phase.
  
Solution:
A (special) sound, once the printer has finished the preheat function, would be perfect to alert the user that the printer has reached the temperature! It would be also useful to alert that, in case a print is launched, it is about to start.

>PREHEAT
>PLA
>HEATING...
>HEATING DONE > SOUND ALERT

**Comment by flashman21** [comment]
I missing this feature too.
thanks
