### ISSUE TITLE
[BUG] Printer reboots after choosing a file to print from SD card.

### ISSUE THREAD

**Issue by Gdeszyk** [prusa3d/Prusa-Firmware#2678]
**Printer type** - MK3s

**Printer firmware version**-  3.9.0

**Describe the bug**
  After choosing a file from SD card the printer reboots. Printing from Octoprint works fine.
  Have already tried to flash the firmware twice and resetting EEPROM by sending M502, M500. 
  
**To Reproduce**
  Insert a card, choose a file, push the button. 
  
**Expected behavior**
  Printer starts printing.
  
**G-code**
  https://drive.google.com/open?id=11xv9nGS_93SwnZDhttkoqmcGCuIqu2xf

**Video**
  https://www.youtube.com/watch?v=4FDDCZgiOC8

**Comment by leptun** [comment]
Hello! Thanks for reporting.
The crash is happening because of the Thumbnail in the gcode file. It is not currently supported by the MK3 firmware.
There is a workaround to this issue, however. I submitted a feature request to the PrusaSlicer repository where I explained how it works: https://github.com/prusa3d/PrusaSlicer/issues/4127

**Comment by Gdeszyk** [comment]
> Hello! Thanks for reporting.
> The crash is happening because of the Thumbnail in the gcode file. It is not currently supported by the MK3 firmware.
> There is a workaround to this issue, however. I submitted a feature request to the PrusaSlicer repository where I explained how it works: [prusa3d/PrusaSlicer#4127](https://github.com/prusa3d/PrusaSlicer/issues/4127)

Wow, haven't thought of that. I'm usually using octoprint and really like these thumbnails :) I wanted to do some maintenance on my RPi hence using SD card atm. Thanks! Case closed I guess  :)

**Comment by leptun** [comment]
Glad I could help. If after you disable the thumbnails the issue is resolved, then please close the ticket.

**Comment by maclakey** [comment]
Thanks for this... I was about to pull my hair out!

**Comment by leptun** [comment]
We’ll soon have a new method for solving this issue that is entirely done in firmware, so no prusaSlicer intervention. We simply make the firmware parse gcode comments much faster so there is no need to skip the section any longer
