### ISSUE TITLE
Feature request: When using silent mode limit maximum acceleration

### ISSUE THREAD

**Issue by mrjohnc** [prusa3d/Prusa-Firmware#268]
Accidentally or unknowingly leaving the acceleration above about 1000mm/s in a print can often make prints quite loud. For large prints that have to run over a long period of time (which you may be more likely to want to be quieter) it can be over an hour before the infill starts being printed and you realise that you accidentally left the infill on high speed.

Please allow an option somewhere to limit maximum acceleration to perhaps 1000mm/s or whatever you think is suitable.

**Comment by inquisitiveKangaroo** [comment]
Hi
Thank you for the feedback. Better silent mode was added to the MK3, using new drivers.
