### ISSUE TITLE
Statistic menu

### ISSUE THREAD

**Issue by epetit91** [prusa3d/Prusa-Firmware#2705]
Hi,
I loaded the new 3.9.0 firmware on my MK3S and I noticed that the Statistics menu no longer appears during printing.
Did anyone observe this?
Thanks

**Comment by leptun** [comment]
The only moments when the Statistics menu is not shown are when you are printing from USB / rPI port or when you are running the first layer calibration.

**Comment by epetit91** [comment]
Thank you.
