### ISSUE TITLE
[QUESTION] M-Code to query stealth/normal mode?

### ISSUE THREAD

**Issue by hergtoler** [prusa3d/Prusa-Firmware#2708]
I've searched, and the closest thing I can find is M914/M915 to set the mode.  I only want to query what the current mode is.  Is there a code that allows this?

**Comment by leptun** [comment]
No, there isn’t a gcode for that.
If you understand the firmware, you can easily mod this in to some unused Mcode value.
The variable that says what mode is selected is tmc2130_mode
You implement the command in process_commands()

**Comment by hergtoler** [comment]
Yeah, easy enough.
#2709

**Comment by 3d-gussner** [comment]
Duplicate of https://github.com/prusa3d/Prusa-Firmware/issues/2477 or not?

**Comment by hergtoler** [comment]
The question has been answered, and options for implementation are being discussed.
