### ISSUE TITLE
[BUG]<MMU2s not loading filament after Firmware upgrade>

### ISSUE THREAD

**Issue by tre4b** [prusa3d/Prusa-Firmware#2720]
MK3s with the recent 3.9 software
MMU2s also with the recent 1.06 firmware
printing via Octoprint

MMU2s was good (not perfect but reliable) Upgraded to  new firmware.

Unable to achieve loading.

The Motor driving the selector bearings gets very hot to the touch (normal?)
Most times the filament goes down to the extruder,  I see the little door move (which triggers the filament sensor)  then it all reverses out.  After 3 attempts like this the cutting action does trigger but subsequent attempt to load also fails.

When it does decide to load into the extruder, which is very rare,  I get a really loud clattering sound from the extruder.  Sounds like the MMU2s is still holding/driving the filament and the extruder is trying to pull it faster than that.  

Only solution when this happens is to turn off the printer at the switch and pull out the filament by hand while the extruder is still hot.  Extracted filament is mangled for the bottom 3 or 4 inches.  The rest of the filament is mangled up to about 1.5 feet.

On inspection extruder is full of little flakes/shards of filament.   driving rollers in MMU2s have bits of filament embedded these have to be scraped out blade, by blade.

I can cheat and bypass by removing the bowden tube from the extruder.  Triggering the load then waiting for the filament to come out of the bowden tube.  As it appears I manually push filament from a second roll into the top of the extruder and it loads normally and works from that filament.

This can be reproduced by any attempt to load filament to the nozzle.  Loading filament to the MMU2s does succeed most times.  Issues only seem to occur when loading to the nozzle.

Any form of load to nozzle that is unattended
  
Printer loads filament and should print.
  
This happens without G-Code.  i.e. using the Load to Nozzle menu item on the printer, though it does also fail if responding to G-Code from PrusaSlicer.

Tried to do some video.  This time the filament stuck in the MMU2.  I suspect it is full of shards of filament and it is too late to clear out now so will try that again tomorrow.  These two are one of loading to the MMU2s and one of Trying to get the filament to load to the nozzle.

https://1drv.ms/u/s!AgggzSx2w9RQ3oFxFWrYnMh_ENsjUA?e=ojPTPq

**Comment by gudnimg** [comment]
Closing as this is now resolved with FW 3.13.0 and MMU FW 3.0.0 :)
