### ISSUE TITLE
[BUG] Resume menu after pressing reset to cancel 3.9.0

### ISSUE THREAD

**Issue by n4mb3r0n3** [prusa3d/Prusa-Firmware#2734]
Printer wants to resume a Print after pressing the reset button to cancel a print. Only power off and on will bring back normal function. 

**Printer type** - [MK3S]
**Printer firmware version**-  [3.9.0]
Issue wasn’t there with 3.8.1

**MMU Upgrade** - No MMU

**SD card or USB/Octoprint**
  Printing from SD

**Describe the bug**
  Printer wants to resume a print that was canceled with the reset button. 

If you try to resume the file from sd card the Extruder is jamming into the left end and tries to move more to the left. 
It stops to move after a while and raises the z axis. The display turns off and on and the printer is in normal mode. 
  
**To Reproduce**
  Start a Print Job and press reset to cancel it. 
 Resume menu appears and can’t be canceled.

**Comment by eeclark** [comment]
I did not think FW 3.9.1 was out.  Are you sure this is 3.9.1 and not 3.9.0?

**Comment by n4mb3r0n3** [comment]
It is 3.9.1. I am testing it.

**Comment by 3d-gussner** [comment]
It is more a self compiled version of the MK3 branch where Fw3.9.1 labled PRs have been merged since fw3.9.0 release.

**Comment by Panayiotis-git** [comment]
@n4mb3r0n3 I tried to reproduce your issue, but after the reset, the printer waits to the status screen as normal.
