### ISSUE TITLE
Feature Request: Have have printer verify correct live z preset is selected when print is started.

### ISSUE THREAD

**Issue by devsfan1830** [prusa3d/Prusa-Firmware#2738]
My printing habits have very much boiled down to PLA on the smooth sheet and PETG on the textured sheet as PETG adheres far to strongly to smooth and PLA really doesn't stick to textured that well for me. I'm working on it but quite often I swap the sheet but dont actually change my live z preset. I would like to propose a way to set a flag in a PrusaSlicer preset that sets the preferred live z. Then when the gcode is generated place this flag or value in the startup gcode that has the firmware check if the selected preset on the printer matches the PrusaSlicer preset. If there is a mismatch, pause heating and notify the user on the LCD to select the right one or ignore it.

I initially thought setting the preset itself via gcode would be a good idea but that would probably be to dangerous as you could likely end up with crashing the nozzle into the bed. Fortunately my preset selection mistakes just result in a fat elephants foot or non-adhesion. But I figure a check and pause would be safer.

**Comment by awenelo** [comment]
How would you suggest distinguishing sheets? It is possible to have up to 8 sheets, all with different, user-customizable names which the slicer does not know. Also, what would the printer do if the sheet identifier that is passed to it in the Gcode is not an actived sheet (hasn't been first layer calibrated) or does not exist (ex. telling the printer to use sheet 9)?
