### ISSUE TITLE
  [ENHANCEMENT] Adjustable Crash Detection Sensitivity

### ISSUE THREAD

**Issue by DFliyerz** [prusa3d/Prusa-Firmware#2741]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MK3S, MK3

**Is your enhancement related to a problem? Please describe.**
  I often get seemingly "false" crash detections on prints, especially in the y-axis. I usually just turn off crash detection for the rest of the print and don't run into any further issues, but it would be nice if I could still have it on for major crashes.
  
**Describe the solution you'd like**
  Add an option to adjust the crash detection sensitivity either in the printer UI, or through gcode that doesn't require you to flash firmware with //#define TMC2130_SERVICE_CODES_M910_M918 uncommented.

**Comment by ManuGithubSteam** [comment]
Yes false crashes are the reason why i have turned that off.

**Comment by kalleknall** [comment]
That would be nice. My Linear Rail mods causes false x-crash from time to time (i think).
