### ISSUE TITLE
  [ENHANCEMENT] Print fan cooldown

### ISSUE THREAD

**Issue by DFliyerz** [prusa3d/Prusa-Firmware#2742]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MK3S, MK3, possibly earlier

**Is your enhancement related to a problem? Please describe.**
  When you go into the preheat menu and select "cooldown," it just turns the heaters off. This makes the nozzle take a while to cooldown, when it could easily be sped up just by turning on the print fan. Of course you can go into settings and turn it on manually, but why not have it be part of the cooldown preheat option?
  
**Describe the solution you'd like**
  Make the "cooldown" preheat option turn on the print fan until the nozzle gets below a certain temp.

**Comment by Prusa-Support** [comment]
Hello! I am sorry this was not replied to for a long time. Thinking of this request, the print fan shouldn't really influence the nozzle temperature, the flow of air should be directed towards the print only, not towards the nozzle and block. So even if we had the print fan switched on during cooldown, it wouldn't change much. 

However, if you noticed that it happened in your case that the print fan does influence the nozzle temp, I'd recommend checking if the fan shroud is not "at an angle" pointing towards the block: it's relatively easy to "overtighten" the bolt keeping the fan shroud, which would result in this situation. 

I am closing the issue for now based on this aspect - in case of anything more you'd like to review, do not hesitate to let me know via email info@prusa3d.com mentioning me ("attn: Alessandro"). 

Alessandro Pantaleo
Prusa Research
