### ISSUE TITLE
[ENHANCEMENT] If print was aborted and new print starts within x seconds, ignore G80

### ISSUE THREAD

**Issue by ghost** [prusa3d/Prusa-Firmware#2743]
**Printer type** - MK3S
**MMU Upgrade** - N/A

**Is your enhancement related to a problem? Please describe.**
Sometimes minor tweaks have to be made that require a print be cancelled and then started again. When this happens (and it can happen several times) the previously recorded mesh information should still be accurate (as long as the bed does not cool)
  
**Describe the solution you'd like**
Allowing for the use of existing G80 data within a certain period after print cancellation would dramatically improve the printing experience. This could be done by ignoring G80 command in start gcode. This should not cause any issues on bed sheet change, since the user would have to select the right sheet in the printer - if necessary, changing sheet could enforce a new G80 request.

**Comment by ManuGithubSteam** [comment]
I second this. Sometimes a print needs to be aborted and the bed did not chnage if the printer was not moved and so it should just ignore G80 but appy the babysteps to get the nozzle to the corrrect height.
