### ISSUE TITLE
[BUG]run time statistic

### ISSUE THREAD

**Issue by Etom808** [prusa3d/Prusa-Firmware#2745]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MK3S]
**Printer firmware version**-  [3.90]

SD card 

under statistics , it says 54d 10h 30m
and I only owned the printer for 20 day. I did check the statistics during the first week and its said 3day.

**Comment by 3d-gussner** [comment]
Thanks for the bug report.
Can you connect your printer with Octoprint, Putty or another terminal software. Pronterface doesn't work here.
Run the following gcodes commands and report back the output values.
1. `D3 Ax0ff1 C4` 
2. `D3 Ax0fed C4`

The 1st one reads the eeprom value for used filament and 2nd the total time.

**Comment by 3d-gussner** [comment]
@Etom808 any update on this?

**Comment by Etom808** [comment]
Hello,

I'm waiting for my pi zero board to come in the mail.  Can I run these
commands using putty and my computer connected to the printer?

Thanks,
Elton

**Comment by Etom808** [comment]
0ff1 98 56 02 00
0fed 71 59 01 00

**Comment by Etom808** [comment]
my printer statistics show:
filament: 1532.40
61d 09h 53m

**Comment by RyanEwen** [comment]
I have the same issue. My printer shows approx 3800m filament used, which seems about right. However it says 615 days and I've only owned it for about 6 months and don't use it daily (and I use Octoprint).
```
Send: D3 Ax0ff1 C4
Recv: D3 - Read/Write EEPROM
Recv: 000ff1  2f d9 05 00
Recv: ok

Send: D3 Ax0fed C4
Recv: D3 - Read/Write EEPROM
Recv: 000fed  3b 86 0d 00
Recv: ok
```

**Comment by Prusa-Support** [comment]
Thanks for reaching us.

We may be looking at memory corruption.
Possibly quickly check all the menus and report if there is any missing menu, broken options, and especially lost values/profiles. You can use the following article as a guide while checking the menus.
https://help.prusa3d.com/article/lcd-menu-original-prusa-i3_142322

Next, a memory dump could be of help.

.
Dumps can be generated "dump memory" command in the menu, as per this article.
https://help.prusa3d.com/article/dump-memory-mk3-s-and-mk2-5-s_245237
Then the dump can be downloaded as per this article.
https://help.prusa3d.com/article/crash-dump_364959

Michele Moramarco
Prusa Research

**Comment by 3d-gussner** [comment]
We have found an issue with the pause time calculation and we will fix the stats with https://github.com/prusa3d/Prusa-Firmware/pull/4493

Please consider to close this issue.
