### ISSUE TITLE
[QUESTION] Why are there numbers in front of some headers?

### ISSUE THREAD

**Issue by awenelo** [prusa3d/Prusa-Firmware#2750]
In `README.md`, there are numbers in front of the `Automated tests`, `Documentation` and `FAQ` headers, but not `Build` and `Table of contents`. Why are there numbers in front of some, but not all level 1 headers? Also, why do these numbers start at 3, instead of 1?

**Comment by danielalexis** [comment]
i think the numbering is broken like in this PR https://github.com/prusa3d/Prusa-Firmware/pull/2736
