### ISSUE TITLE
  [ENHANCEMENT] Multiple saved option for first layer calibration

### ISSUE THREAD

**Issue by povi2946** [prusa3d/Prusa-Firmware#2752]
**Printer type** - [e.g. MK3S, MK3, MK2.5S, MK2.5, MK2S, MK2]
**MMU Upgrade** - [e.g. MMU2S, MMU2, MMU1]

**Is your enhancement related to a problem? Please describe.**
I have multiple steel sheet beds and sometimes for specific prints I need to swap them and every single time I need to re-calibrate the first layer because beds are different thickness.
  
**Describe the solution you'd like**
It would be nice to save calibration values and when I swap my bed choose if I want to recalibrate or just select pre-saved value.

Thanks!

**Comment by leptun** [comment]
There is such an option since fw 3.8.0. In the latest fw you can go to Settings->HW setup->Steel Sheets

**Comment by povi2946** [comment]
Thank you!!
