### ISSUE TITLE
  [ENHANCEMENT] Display FINDA and IR status on Info Screen and Loading/unloading screens

### ISSUE THREAD

**Issue by scooper4711** [prusa3d/Prusa-Firmware#2759]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - any that supports MMU
**MMU Upgrade** - Any MMU

**Is your enhancement related to a problem? Please describe.**
  When troubleshooting MMU load/unload failures, it's very frustrating when I cannot easily see the sensor status of the IR and FINDA sensors as they are key for understanding where the issue lies.

  
**Describe the solution you'd like**
I would like to have a the sensor value (0 or 1) for both the FINDA and IR sensors. easily visible on the Info Screen and any and all screens specific to the MMU, such as "loading filament 1", or MMU Load Failure. 
In order to conserve space on the screen, you could make it a single glyph icon for Finda and for IR sensors. E.g. a F for Finda value 0, or an inverted F (illuminated background, not illuminated F) for a Finda sensor value of 1. Same thing for the IR sensor.

**Comment by scooper4711** [comment]
This is also critical to see on e.g. “MMU requires attention”. Although I’d like to be able to access the menu then too in order to do things like move the extruder in order to help clear a jam.

**Comment by 3d-gussner** [comment]
As said in another issue the main screen is very full and has limited space.
Can you provide several ideas how it could look like?
This should be easier to discuss.
Also don't forget that beginners should be able to understand the displayed information.

**Comment by scooper4711** [comment]
the MMU is not sold to beginners. In fact, the marketing material tries to discourage beginners from buying it. 
Not to use one poor UI to justify another, but flashing a red LED either slowly or quickly kinda sets the bar pretty low for user experiences. 😆 🤣  
But to your point, this additional info would only appear if you have an active MMU. There are three character spots after the ⏩ 100% which indicates flow rate (something I never change). Use one for separation, then put the Finda and IR sensors in the two remaining spots.
I'm thinking something like this 
<img width="74" alt="Screen Shot 2020-08-22 at 12 30 12 PM" src="https://user-images.githubusercontent.com/1970249/90963351-1d788b80-e474-11ea-95f5-961f0db2b75b.png">
which shows the four possible states of the Finda and IR sensors: Both 0; Finda 1, IR 0; Finda 0, IR 1; Finda 1, IR 1.

**Comment by scooper4711** [comment]
If we wanted to get it more compact - just a single glyph - it could be done but would be less intuitive.
Illuminate the upper half of the character rectangle if the Finda is 1, and the lower half if the IR sensor is 1.
Or you could do inner and outer illumination of the rectangle:
⬜ : finda 0, IR 0 (this is supposed to be a white square)
🔳 : finda 0, IR 1
🔲 : finda 1, IR 0
⬛ : finda 1, IR 1

**Comment by scooper4711** [comment]
In the case of N/A, the two glyph approach could replace the F or I with a question mark.
If only using one glyph, then we can't represent N/A.

**Comment by scooper4711** [comment]
And if this gets voted down because the info screen is too dense already, then just adding the information (spelled out even) to the various MMU specific loading/unloading and error screens would be a *HUGE* boost.

**Comment by leptun** [comment]
Please avoid using custom characters, especially on the status screen. As it is now the code responsible for custom characters is really susceptible to bugs. I’ve implemented a better approach to this issue, but it’s still somewhat limited (max 16 custom characters, only 8 possible at a time, still not enough for the status screen).

**Comment by scooper4711** [comment]
What characters are available? Are emojis considered custom?
I was thinking the F and I were easy because they're Latin characters and the code should already be there for highlighting menu alternatives.
The other two approaches with a single glyph were spitballing because 3d-gaussner asked me to think of multiple implementations. The third idea is implemented with emojis, so if you support emojis we're set.

**Comment by leptun** [comment]
We are extremely limited by the display. It’s a character lcd, meaning you only have a grid of characters where you can write. On the lcd we have, it’s 20x4 characters. Each characters is made up of 5x8 pixels. By default, there is a pallete of characters that we can use that are included in the default character set. We can only add 8 5x8 characters to the lcd at a time.
As for having custom characters similar to the original character table, but inverted in color, that is also impossible without the aid of custom characters. Same goes for “emojis”, as we literally send the ASCII value to the screen and it does the drawing for us. Here is the default (or better said hardcoded) character set:

![](https://protostack.com.au/wp-content/uploads/HD44780_breadboard_05.jpg)

**Comment by scooper4711** [comment]
Thanks for this. 
So *adding* compact info on the info screen is out (at least my way of doing it) 
Would it be possible to *replace* the info screen if you have an MMU? Seeing the sensor status is way more important than eg seeing the flow rate. 
Or offer a second info screen To MMU users so users can choose. 
As things stand, the sensor info screen ismy info screen whenever I print with more than one filament. It would be nice to add remaining time to that. 😄
