### ISSUE TITLE
  [ENHANCEMENT] Better unload filament

### ISSUE THREAD

**Issue by ChipCE** [prusa3d/Prusa-Firmware#2771]
Printer type : MK3S

Problem :
 When filament is pulled out, sometime the sensor read the unstable signal that cause by the blob end of the filament and trigger auto load right after the filament is pulled out.
  
Describe the solution you'd like :
  Have some kind of short delay to prevent false detect when the filament is pulled out.

**Comment by ochm** [comment]
Turn off auto load.

**Comment by ChipCE** [comment]
@ochm that is not the solution. Even with autoload enabled the fw should have a solution for false triggering when filament is pulled out.

**Comment by Panayiotis-git** [comment]
@ChipCE I think it is a nice improvement
