### ISSUE TITLE
  [ENHANCEMENT]<Enter comprehensive title>

### ISSUE THREAD

**Issue by Sundheden** [prusa3d/Prusa-Firmware#2772]
Currently my i3 Mk3s preheats both the BED and the nozzle when preheating to unload filament. This is quite annoying, as this is the perfect time to clean the bed, while loading the filament. 

Bottom line: **There is no need for the entire bed to heat up, just to load/unload filament.**

**Comment by awenelo** [comment]
Please see #422, #2295, #2335, #2359 and #2765.

**Comment by Panayiotis-git** [comment]
There is already a PR that sorts this out. It is waiting for an approval.
https://github.com/prusa3d/Prusa-Firmware/pull/2335

If you can build the firmware yourself, you could give it a try.

**Comment by JohnnyDeer** [comment]
I'm closing this issue as duplicate.
