### ISSUE TITLE
[FEATURE REQUEST] User voice like page to vote up and down for new features

### ISSUE THREAD

**Issue by fscheps** [prusa3d/Prusa-Firmware#2779]
I would like to propose you create a User Voice type of page, where every user from the 3D Printing community can vote up for new stuff. This way you will be able to better understand what the people are asking for to get on their printers, as enhancements, etc.
This could be a way: 
https://www.uservoice.com/product

But there are Wordpress Plugins that allow you to do the same for example: 
https://themeforest.net/item/discy-social-questions-and-answers-wordpress-theme/19281265

Thank you for your consideration

**Comment by draeath** [comment]
I concur, there should be a better way for users to submit feedback than dog-piling in PR comments, such as in #2692

**Comment by mikolaszuza** [comment]
I like that idea :)
