### ISSUE TITLE
[FEATURE REQUEST] PC Blend option on First Layer Calibration menu

### ISSUE THREAD

**Issue by litecactus** [prusa3d/Prusa-Firmware#2781]
I've just gone to run a First Layer Calibration on my Prusa MK3S with the new Prusa PC Blend material, but there is no "PC Blend" option within that menu, nor is there an existing option that is hot enough for the default 275c that the PC Blend prints at.

Please can we add a PC Blend Option (i.e. 275c nozzle and 100c bed) to the First Layer Calibration settings menu?

**Comment by leptun** [comment]
Pretty sure the option exists. Have you checked the latest version?
In case the 3.9.0 version doesn't include the patch, expect that the next release will include it.

**Comment by DRracer** [comment]
The PC Blend preheat options is already present in 3.9.1-RC1 and it will be in the final release 3.9.1 as well.
Closing...
