### ISSUE TITLE
[BUG] "ok" missing with M25/M601

### ISSUE THREAD

**Issue by leptun** [prusa3d/Prusa-Firmware#2800]
Start any print from the SD card. Use putty or some other software to send M25/M601 via USB. The command will execute successfully (print paused and "// action:paused"), but no "ok" is sent. This happens because we use `cmdqueue_pop_front()` which destroys the `CMDBUFFER_CURRENT_TYPE` information from the current block in the cmdqueue, so ClearToSend() doesn't know that the command was from USB.

**Comment by 3d-gussner** [comment]
@leptun Please fill in the template correctly 🤣😂😍
