### ISSUE TITLE
[BUG] wrong end time on the printer display

### ISSUE THREAD

**Issue by jbriard** [prusa3d/Prusa-Firmware#2810]
**Printer type** - Prusa Mini
**Printer firmware version**-  4.2.0

**SD card or USB/Octoprint** - SD card

**Describe the bug**
 The end time is different from the web interface and the physical display.
The display show a wrong time.
  
![prusa-bug](https://user-images.githubusercontent.com/10330057/90500113-bc3a7a80-e14a-11ea-9f77-74c4fdef589a.png)
![IMG_20200818_115442](https://user-images.githubusercontent.com/10330057/90500146-c78da600-e14a-11ea-9682-a4992f71194a.jpg)

**To Reproduce**
  Just launch a print
  
**Expected behavior**file:///home/enky/Pictures/prusa-bug.png

  Having the same and right time in both interface.

**Comment by 3d-gussner** [comment]
@jbriard Thanks for the bug report but it is in wrong repository.
Please search in https://github.com/prusa3d/Prusa-Firmware-Buddy/issues and if you don't find anything open it there.

Please close this issue here, as it is in wrong place.
