### ISSUE TITLE
[FEATURE REQUEST] Display sensor readings when MMU2S fails

### ISSUE THREAD

**Issue by martijnvankekem** [prusa3d/Prusa-Firmware#2812]
When the MMU2S fails, give a user the possibility to show sensor readings, for example, the FINDA reading to help to determine a specific problem. Last time, my MMU2S seemed to fail due to a broken FINDA sensor, but I couldn't test this unless I'd cancel the print and would go to the Support menu manually.

Probably being able to open the Settings menu during an MMU2S fail would be enough. However, it could also help for the Prusa Printer to detect which error is detected by the MMU2S (for example the FINDA ball never goes down) and show relevant sensor readings on the screen when that happens, preferably with a user-friendly error message instead of only flashing LEDs.

**Comment by gudnimg** [comment]
Closing as this is now resolved with FW 3.13.0 and MMU FW 3.0.0 :)
