### ISSUE TITLE
[FEATURE REQUEST] Automatic power saving mode after finished print

### ISSUE THREAD

**Issue by androandra** [prusa3d/Prusa-Firmware#2815]
**Printer type** - MK3S

**Is your feature request related to a problem? Please describe.**
  Sometimes I start a lengthy print and go on a weekend trip. When I come back I notice that the printer has been standing by ever since it finished the print, wasting energy. 
  
**Describe the solution you'd like**
  A low power/ sleep mode with automatic engage after a finished print.

**Comment by DRracer** [comment]
The printer already does a enter a low power mode after finishing the print - all heaters are off, fans are off, motors are off. What else do you expect to be turned off? There is not much left in terms of running hardware. The only thing that remains running is the motherboard, LCD and the PSU.
Is you LCD shining bright? You can upgrade to the latest model which supports dimming.
