### ISSUE TITLE
[QUESTION] Wondering if bulges on corner of cube is normal

### ISSUE THREAD

**Issue by K13NN13** [prusa3d/Prusa-Firmware#2816]
Hi all, I was wondering if it is normal to have rounded edges on a square print when printing at higher layer heights such as 0.15 and 0.2, when printing at 0.1 the corners are much sharper. I have attached a picture to show a print with PLA at[ 0.1, 0.15 and 0.25](https://i.imgur.com/TeGiT30.jpg)

I have tried printing these on firmware 3.9 with a calibrated LA for PLA and I have also tried 3.8.1 but the result is the same sadly.

**Comment by wavexx** [comment]
The extra bulges on corners can be controlled using Linear Advance. For this, we recommend to update to the latest 3.9.1 FW which contains several fixes for it.

The default filament profiles should come with good defaults.
See this guide:

https://help.prusa3d.com/en/article/linear-advance_5877
