### ISSUE TITLE
How to use cmake and ninja properly on OSX with detailed instruction

### ISSUE THREAD

**Issue by bikebandit101** [prusa3d/Prusa-Firmware#2824]
Could you please provide more detailed instructions on how to use cmake and ninja? I am little a wits end over this because I cannot get the hex file to generate properly on OSX. I have instal avr-gcc through home brew and follow the little instructions provide. I do not know where to go from here. Cannot use the Arduino complier because I am on OSX catalina.

**Comment by DRracer** [comment]
Even though you are asking a slightly different thing (how to avoid using Arduino 1.8.5), I'd still mark this as a duplicate of issue #2658 .
