### ISSUE TITLE
[FEATURE REQUEST] TMC Sensorless Filament Jam Detection?

### ISSUE THREAD

**Issue by MohanMaker** [prusa3d/Prusa-Firmware#2827]
One feature I feel is missing from my new Prusa MK3S printer is **filament jam detection** and the ability to **detect a tangled filament spool**. I am aware that this is not possible using the filament sensor since it uses a metal ball and can not detect filament movement. 

But, I have seen discussions on the [Marlin GitHub](https://github.com/MarlinFirmware/Marlin/issues/14497) and [Duet3D Forms](https://forum.duet3d.com/topic/8000/use-of-using-extruder-stall-detection-during-filament-loading/8) about using TMC stallguard technology to measure the force that the extruder motor is applying and detect a jammed extruder. 

On the other forms, they concluded that this feature would be challenging to implement since stallguard values would have to be different with varying extruder systems, filaments, temperatures, and nozzle sizes, and since stallguard does not work well at the slow stepper motor movement speeds (in an extruder).

I wanted to bring this idea to the Prusa forms to see if anyone had any ideas about achieving this on a Prusa MK3/s or Mini? Has anyone tried this in the past and had any success? I feel that it may be possible, since, in Prusa-Firmware, we only have to develop for a small number of machines, while in Marlin, the firmware has to work with a wide range of extruders. Any ideas or proposals? 

Thanks! :)

**Comment by DRracer** [comment]
@MohanMaker thank you for sharing your idea, we know, we tried in the past ;) ... but the stallguard is too imprecise (i.e. it differs too much among machines, motors and environment) - the solution would have been too brittle and causing more confusion than actually solving a real (and relatively rare) problem.
If you don't mind, I'd close this issue...
