### ISSUE TITLE
[BUG] Crash detection not working with firmware 3.9.1 (MK3S)

### ISSUE THREAD

**Issue by NoNme1** [prusa3d/Prusa-Firmware#2839]
Hello,
Prusa support directed me here to submit a bug report. 
Printer: MK3S
FW version: 3.9.1 (latest release from the website)
No MMU
printed via SD card 

Crash detection on MK3S not working after I uploaded the new firmware. First noticed the issue on a tpu print that curled up and caused the toolhead to crash on the print and the x-axis to skip steps (didn't test on the Y-axis). the printer is on Normal mode and Crash det. is [on]

[github.zip](https://github.com/prusa3d/Prusa-Firmware/files/5263140/github.zip)

included in the zip is a video of the issue and the gcode used
crash detection does work when I flash 3.9.0 and print the same gcode.

Steps to reproduce:
preheated FLEX > Print > and selected the gcode, once the print has started, moving the toolhead does not cause the printer to re-home and resume the print as expected.

**Comment by MohanMaker** [comment]
I have the same issue here with firmware 3.9.1 on Prusa MK3S. Thanks for submitting the issue report @NoNme1

**Comment by SteWhite** [comment]
me too (3.9.1 on Prusa MK3S)

**Comment by Maintraxx** [comment]
me too

**Comment by nikil511** [comment]
Same here, with 3.9.2
(was working with older firmware)

**Comment by drelich** [comment]
I find it interesting that this thread hasn't been closed yet. I presume no solution/fix was found?

Just had a major layer shift on X axis as a result of a huge crash into the printed object curled up corner. Crash detection failed. I'm on 3.10.0 firmware...

**Comment by NoNme1** [comment]
Switching to the latest firmware (when it came out) fixed the bug for me.
Just forgot to close the thread.

**Comment by drelich** [comment]
I am on the latest and still no luck. Might as well just disable that feature as it is now, haha. Cheers.

**Comment by NoNme1** [comment]
I ended up leaving mine in power mode and hoped for the best haha, may the gods of FDM ever smile in your favor.
