### ISSUE TITLE
[BUG] 3.9.1 - LA 1.5 Saga continues...? (Overextrusion on small features)

### ISSUE THREAD

**Issue by vintagepc** [prusa3d/Prusa-Firmware#2843]
**Printer type** - MK3S
**Printer firmware version**- 3.9.1

**MMU Upgrade** - MMU2S
**MMU upgrade firmware version** - 1.0.6

**SD card or USB/Octoprint**
SD

**Describe the bug**
While we've made leaps and bounds over the previous versions, I just did a print that appears to still suffer from LA1.5 issues with small extrusions/starts/stops.

I did run the  LA calibration g-code and obtained a K value of 0.08, which agrees with the release notes as a valid default.
However, the lettering on the print suffers from massive overextrusion: 
![IMG_0016](https://user-images.githubusercontent.com/53943260/94046490-bd407680-fd9e-11ea-9fc0-8bea61695269.JPG)
  
For reference, here are some previous PETG filament chips I made with previous firmware versions. 

![IMG_0017](https://user-images.githubusercontent.com/53943260/94046979-6be4b700-fd9f-11ea-9c56-fc1d1e5219b0.JPG)

Pronterface snap of the region:
![image](https://user-images.githubusercontent.com/53943260/94047286-e281b480-fd9f-11ea-85a1-77fee37cb58a.png)

The filament was a freshly opened Prusament spool, so moisture should not factor into the problem.

**To Reproduce**
[Prusa_Red_PETG-0.2 PETG 24m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/5269823/Prusa_Red_PETG-0.2.PETG.24m.gcode.zip)

I printed the example G-code with Prusament Carmine Red, at 235C, K 0.08

Stock Prusament profile, except the K value was modified, and the temperature dialled back to (unsuccessfully) counter stringiness). 
  
**Expected behavior**
Non-overextruded lettering

**Comment by Kachidoki2807** [comment]
Can you provide the .3mf of this project?
I guess this is an issue more PrusaSlicer related (2.3.0-alpha0) or special settings, the printer has very weird travel moves, like an avoid crossing perimeters option enabled.

Below my print of your G-Code, not the best print I made on this printer, but the quality is quite decent. Prusament PETG Galaxy Black.
![image](https://user-images.githubusercontent.com/24781181/94187034-b6e9f180-fea7-11ea-912e-f41c792b7c5b.png)

Yes, maybe there is a bit overextrusion, but it can also be the small cumulated oozing during those weird travel move that take ages.

**Comment by vintagepc** [comment]
Yes, I do have 'avoid crossing perimeters' ticked; I know the travel paths are less optimized. 

Yours turned out better than mine, though the letters are also far stringier than expected. 

Standby; I resliced and am testing something now; will provide 3MF if that also has issues, or follow up if it resolves it.

**Comment by vintagepc** [comment]
Sorry for the false alarm. Turns out it was my fault; at some point through errant keypresses or some other means, the 'Extra distance after retraction' value had been changed to 0.2; Of course this caused overextrusion on de-retract. 

I changed that back to 0 and the print quality is acceptable again for PETG with the usual slight stringiness.
