### ISSUE TITLE
  [ENHANCEMENT]Ask before deleting XYZ-Calibration in calibration-menu

### ISSUE THREAD

**Issue by PaulGoldschmidt** [prusa3d/Prusa-Firmware#2849]
Hey together,

I've got a quick suggestion/enhancement for all i3 MK3's (maybe also MK2, MMU2 etc.), because I'm always frustrated when I recalibrate the printers of mine or do anything else in the calibration-menu: You won't a warning message or something to confirm that you want to delete the xyz-calibration values. Sometimes you accidentally hit the wrong menu-point and than have to recalibrate the xyz-axis and have to set the mesh-level new, so you will have at least 15-20 minutes wasted because of the small mistake of yours.
**I would suggest a small "are you sure?" question before you delete all of the calibration values.**

Happy to discuss about this enhancement.
Greetings from Germany,
Paul

**Comment by bubmann** [comment]
Hallo,
I stumbled upon this behaviour today, too. I tried to get a foothold while reading the PrusaSlicer source for a few days now, this seems more accessible ... if nobody else will, I might have to correct this oversight myself, if it's only for my own mental healths sake. my instinct would be to maybe empty and overwrite the values at the end of the calibration cycle, so you can just trigger a reset if it's started in error. but this counterintuitive behaviour might also be a necessity, I will have to read up on the code.
