### ISSUE TITLE
Problems after updating firmware

### ISSUE THREAD

**Issue by George1266** [prusa3d/Prusa-Firmware#285]
Ever since updating my firmware the calibration procedures are not working. It does not go through calibrate Z, I see no calibrate XYZ, during the printing of CalibrationV2.gcode the nozzle touches the bed and while trying to print the carriage gets half way across the print bed and stops like it has been jammed.

**Comment by 3d-gussner** [comment]
@George1266 you may want to try a factory reset http://help.prusa3d.com/38908-firmware-software/276545-factory-reset and re calibrate the printer.

**Comment by George1266** [comment]
I figured it out. I think my computer was updating the old firmware.

**Comment by 3d-gussner** [comment]
Great then you can close the issue
