### ISSUE TITLE
[BUG] Polish language does not work on 3.9.1 release

### ISSUE THREAD

**Issue by dlozinski** [prusa3d/Prusa-Firmware#2853]
On the first launch after flashing firmware version 3.9.1 MK3 (using PrusaSlicer 2.2.0+ on Mac) language choose menu pops up. Then if selected `Polski` language and confirmed, printer restarts and shows the same language menu again and again. Selecting `English` works.

**Comment by leptun** [comment]
Do other languages work or are all of them broken except English? Also, please try flashing again and post here the logs from the flashing process.

**Comment by dlozinski** [comment]
I have raspery Pi zero connected to the PI Port (running OctoPI). When I disabled PI port in the printer settings and flashed firmware again then I'm able to select `Polski` language.

**Comment by dlozinski** [comment]
I'm sorry I can't flash it again and save the logs right now because the printer is currently very bussy :)

**Comment by leptun** [comment]
I don't need logs anymore. What you said is enough for me. I know what went wrong since I am the one that created the bug apparently :)

**Comment by leptun** [comment]
Nevermind. I handled this case as well, so there shouldn't be a problem flashing even if you have a raspberry pi connected. So if it is possible (no need to rush) please send me a log with how it fails.

**Comment by Fredlandator** [comment]
I do have a similar issue with french language. 
after loading the firmware 3.9.1 using octoprint on a pi3+, firmware updater plug in, it asked me to choose a language. if french is chosen, it will then ask for a confirmation, and when confirmed , it reboots and ask for the choosen language again, and so on until you choose english.

samle if I unplug the pi from the mk3s.

I have no  idea about where to find logs, as it seems this may help help you fix this?

**Comment by leptun** [comment]
@Fredlandator Languages work after a firmware update only if you use PrusaSlicer for uploading the firmware. The Octoprint plugin for firmware update only flashes the main firmware, not also the languages

**Comment by Fredlandator** [comment]
Ok, good to know that it doesn't work fully if not using prusa slicer.

After quickly double checking, it is not mentioned in the provided protocol that you HAVE to use slic3r PE. I feel it should. Or maybe I missed this information in the paper?
