### ISSUE TITLE
[BUG]Errors during M860

### ISSUE THREAD

**Issue by AndrewLuebke** [prusa3d/Prusa-Firmware#2854]
**Printer type** - MK3S
**Printer firmware version**-  3.9.1

USB via Octoprint

**Describe the bug**
  For a couple of weeks when I compile the firmware myself and try to print something I no longer get "Recv: echo:busy: processing" messages instead I get "Communication timeout while printing, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves."  This eventually leads to the print failing with a rerequested line error.  The stock firmware does not do this and send the busy messages.  I've tried completely erasing the build environment and rebuilding from scratch with the same issue.  Prior to this I had no issues with my self-compiled firmware.  The first file is what happens with my firmware and the second with the stock firmware.
  
**To Reproduce**
Build the current firmware, start to print anything.  No busy messages instead communication timeouts.
  
**Expected behavior**
Should get busy messages and no errors.
  
[No Busy.txt](https://github.com/prusa3d/Prusa-Firmware/files/5358258/No.Busy.txt)
[Busy.txt](https://github.com/prusa3d/Prusa-Firmware/files/5358263/Busy.txt)

**Comment by leptun** [comment]
Can you please share a gcode or a PrusaSlicer profile that makes use of this M860 command? I want to make sure that I have a good base for the issue

**Comment by AndrewLuebke** [comment]
I tried it with numerous models and profiles, but here is the gcode I tested to get the errors I reported.

[Full_0.2mm_PLA_MK3S_6h38m.zip](https://github.com/prusa3d/Prusa-Firmware/files/5360447/Full_0.2mm_PLA_MK3S_6h38m.zip)

**Comment by AndrewLuebke** [comment]
This is the HEX file I generate when I compile.  I doubt whether it's a particular printer problem since if causes issues on all of my printers.

[prusa3d_fw_MK3S_3_9_1_3518.zip](https://github.com/prusa3d/Prusa-Firmware/files/5362247/prusa3d_fw_MK3S_3_9_1_3518.zip)

**Comment by leptun** [comment]
I found what was wrong. A fix will come soon.

**Comment by AndrewLuebke** [comment]
I can confirm that https://github.com/prusa3d/Prusa-Firmware/pull/2870 fixes my issue.  Thank you!
