### ISSUE TITLE
[BUG]<Enter comprehensive title>

### ISSUE THREAD

**Issue by bakerjvb** [prusa3d/Prusa-Firmware#2859]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MK3S]
**Printer firmware version**-(3.9.1 build 3518)

no mmu

**SD card

**Describe the bug**
  Arduino IDE failed to compile firmware 
Error was in eeprom.h.
static constexpr M500_conf * const EEPROM_M500_base = reinterpret_cast<M500_conf*>(20); //offset for storing settings using M500

error M500_conf is not a constant

To fix

I deleted "constexpr" making the line read
static M500_conf * EEPROM_M500_base = reinterpret_cast<M500_conf*>(20); //offset for storing settings using M500

and the Arduino IDE compiled the firmware correctly.

Tell me if I have made a mistake.

Rgds Julian Baker

**Comment by 3d-gussner** [comment]
Please close this issue as you have opened the same as another one.
