### ISSUE TITLE
[BUG] Build Checksum / Versioning Error

### ISSUE THREAD

**Issue by GWdd** [prusa3d/Prusa-Firmware#2861]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

MK3/S Driver-Firmware-PSLicer Downloads
**Printer firmware version**-  2.2.9.1 and 2.3.0

**Describe the bug**
SHA5 in download files doesn't match the actual file checksum
Security descriptor checksum doesn't match file (e.g., both 2.2.9.1 and 2.3.0 show same checksum signed by Prusa)
  
**To Reproduce**
Just look at the file download section of prusa.com
  
**Expected behavior**
Fix and make accurate the file descriptions, the internally signed checksums, and the website download section.
  
** Text Description **
The downloadable files need accurate checksums to ensure no man-in-the-middle attacks are taking place, and that the files downloaded are as produced by Prusa engineers. 

Two files, 2.3.0 released on March 23, 2020; and a later file now claiming to be most recent released on July 13, 2020, conflict with each other. Both have the same Prusa Signed checksum in the digital security fields. Both have the same files size. Both have a different actual checksum than the security descriptor say they should have.

The 2.3.0.0 file on my machine is Prusa Signed, dated March 23, 2020 07:31 SHA5 = 0eb1b7e9ac15637638310cc5288e8fee

The 2.2.9.1 file on my machine is Prusa Signed, dated  July  13, 2020 03:03 SHA5 = 0eb1b7e9ac15637638310cc5288e8fee

Oddly - even with a binary compare failing; both 2.2.9.1 and 2.3.0. are supposed to have the same checksum. So something is amiss.

And checksums on 2.2.9.1 do not match the certificates.

D:\Tools\Applications\Prusa 3D Printer>fciv prusa3d_win_2_2_9_1.exe
//
// File Checksum Integrity Verifier version 2.05.
//
8c5f0711cae119e955911ffc67d77405 prusa3d_win_2_2_9_1.exe

D:\Tools\Applications\Prusa 3D Printer>fciv prusa3D_win_2_3_0.exe
//
// File Checksum Integrity Verifier version 2.05.
//
d4328d12a7986c014b3f8bebf392f9c7 prusa3d_win_2_3_0.exe

 
<img width="569" alt="2 2 9 Capture" src="https://user-images.githubusercontent.com/32851040/96294030-f7212900-0fa8-11eb-948e-d469e2833ed7.PNG">

<img width="584" alt="2 3 0 Capture" src="https://user-images.githubusercontent.com/32851040/96294058-01dbbe00-0fa9-11eb-8ea2-2592c6be991d.PNG">

**Comment by DRracer** [comment]
@GWdd Please try the latest installation package, the signature should be up to date and valid. If not, please file a new issue. Thank you.
