### ISSUE TITLE
[FEATURE REQUEST] Put MMU2S in stealth mode after print completion

### ISSUE THREAD

**Issue by morimorida** [prusa3d/Prusa-Firmware#2871]
Is there a way for firmware to switch to stealth mode after print or during printer ildle time?  There is excessive noise if you have set it to normal mode.  I can manually switch it to stealth mode after print completion but then I keep forgetting to set it back to normal mode.

**Comment by Mirarkitty** [comment]
That sounds strange. Mine is absolutely silent. What noise does it make?

But since the motors are left on when it's not printing it might be a good idea to make it go into as quiet and power saving as possible mode?
