### ISSUE TITLE
  [ENHANCEMENT] FINDA and IR sensor status on "MMU load error"

### ISSUE THREAD

**Issue by morimorida** [prusa3d/Prusa-Firmware#2873]
Can we have a more helpful information along side with MMU load error and providing us with sensor status during the loading/unloading error?

Like

MMU failed to load...
IR = 1 , FINDA = 1

**Comment by vintagepc** [comment]
this is a duplicate of #2759 and #1845

**Comment by JohnnyDeer** [comment]
I´m closing as duplicate.
