### ISSUE TITLE
[FEATURE REQUEST] Pause print function availability when printing from Octoprint

### ISSUE THREAD

**Issue by morimorida** [prusa3d/Prusa-Firmware#2874]
When printing from SD card, there is a option to pause print.  I use this function to clean the nozzle when bugger accumulates on the nozzle (especially printing PETG).  However, when printing from Octoprint this function is gone so I need to revert to "Change Filament" function.  It would be nice if "Pause Print" function can be available when printing from Octoprint.

**Comment by leptun** [comment]
In octoprint you can set the gcode scripts for pausing,resuming and canceling to M601, M602 and M603 respectevly.
As for the firmware, there currently isn’t any menu option for triggering those scripts, but I think I know a way to implement them.
