### ISSUE TITLE
[BUG] MINI touched and bended hotend during Mesh Bed Leveling calibration

### ISSUE THREAD

**Issue by jakubmirejovsky** [prusa3d/Prusa-Firmware#2879]
Prusa MINI, firmware 4.2.1

Right after Mesh Bed Leveling (under Calibration), the nozzle goes down and touches and bends the hotend.
Video here: https://www.youtube.com/watch?v=4gR8gOi_ESg
  
**To Reproduce**
It happended to me when I:
- started printing (went for 15 minutes)
- paused printing for 6 hours
- resumed printing
- stopped printing after 5 minutes
- Z axis moved up
- first layer calibration
- Mesh Bed Leveling - here the problem was spotted. I tried it again with my camera on (see youtube link).

After resetting the printer, it went just fine.
  
**Expected behavior**
I expect nozzle not to touch the surface at all.
  
**G-code**
I am attaching the gcode, but I don't think it will be useful for debugging:
https://www.dropbox.com/s/63aloo0s4qaw169/Spi_FRA_public_up_cov_0.25mm_PLA_MINI_3h27m.gcode?dl=0

**Video**
https://www.youtube.com/watch?v=4gR8gOi_ESg (0:43)

**Picture**
https://www.dropbox.com/s/4r8s9gdie9yap9v/2020-10-31%2020.29.42.jpg?dl=0 (PEI damaged)

**Comment by vintagepc** [comment]
This github is for the MK3 firmware. You are looking for the Mini firmware repo:

https://github.com/prusa3d/Prusa-Firmware-Buddy

Please file your issue there.

**Comment by jakubmirejovsky** [comment]
https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/981
