### ISSUE TITLE
[BUG] MMU2S Filament load failure

### ISSUE THREAD

**Issue by brettvitaz** [prusa3d/Prusa-Firmware#2904]
**Printer type**
MK3S

**Printer firmware version**
3.9.2

**MMU Upgrade**
MMU2S

**MMU upgrade firmware version**
1.0.6

**SD card or USB/Octoprint**
Both SD and Octoprint are affected

**Describe the bug**
Extruder motor does not move after filament selection, causing failure to load selected filament. 
  
**To Reproduce**
1. Slice a single filament print
1. Start print on printer
1. At filament selection, select appropriate filament
  
**Expected behavior**
Pinter pre-heats hot end and loads filament successfully.

**Actual behavior**
Printer attempts to load filament, extruder does not respond likely due to cold extrusion protection, often failing to load filament.
  
**G-code**
[Shape-Cylinder_0.1mm_PLA_MK3SMMU2S_5m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/5612638/Shape-Cylinder_0.1mm_PLA_MK3SMMU2S_5m.gcode.zip)

**Comment by brettvitaz** [comment]
`Tx` gcode should wait until a safe temperature before loading.

**Comment by brettvitaz** [comment]
I have found this is a problem when using Octoprint and the plugin OctoPrint-Mmu2filamentselect. When the plugin times out and hands off the filament selection to the printer, the warm up is not respected.

**Comment by gudnimg** [comment]
In 3.13 (currently in development) `Tx` gcode won’t require the nozzle to be preheated. The filament will be loaded into the extruder gears and stopped when the filament sensor triggers. `Tc` gcode loads the filament from the gears and into the nozzle, this step requires preheating.

**Comment by gudnimg** [comment]
Closing as this is now resolved with FW 3.13.0 and MMU FW 3.0.0 :)
