### ISSUE TITLE
 [ENHANCEMENT] Add option when adjusting z-offset for build sheets to adjust all build sheets by a relative value

### ISSUE THREAD

**Issue by rcmaniac25** [prusa3d/Prusa-Firmware#2905]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MK3/S/+ (anything that can have multiple build sheets)

**Is your enhancement related to a problem? Please describe.**
No, it's a general time saving feature (see description below)
  
**Describe the solution you'd like**
If you have a single build sheet, the option to switch build sheets does not exist. If I change a nozzle or do some repair/maintenance on the extruder, there's a (good) chance I need to adjust the z-offset for the bed. This is generally easy.

Once you add additional build sheets, the option to switch sheets appears, and now when the same nozzle change/repair/maintenance occurs, each bed will probably need the z-offset adjusted. As a enhancement, allow adjusting all build sheets by a relative amount when adjusting z-offset. This should only show if there's more then one build sheet recorded.

Example:
- Sheet 1: -0.543
- Sheet 2: -1.122

I set to sheet 1 and specify I want to adjust z-offset. I eventually get the following:
Sheet 1
Z offset: -0.543 mm
= Continue
= Continue and Update All Sheets
= Start from zero

If I do "continue" or "Start from zero" then only this sheet is updated. If I do "Continue and Update All Sheets", then all sheets are adjusted by the relative change that occurred to sheet 1. So if I adjusted sheet 1 from -0.543 to -0.600, a difference of -0.057, then sheet 2 would also be adjusted from -1.122 to -1.179 (or I think it would actually save to -1.180 as precision is 0.002-0.003).

The purpose is to save time in adjusting build sheets when a system change occurs. It won't always be perfect, but it means you do a little bit of live-z adjusting instead of digging into a bed, loosing a first layer, or going "oh no, I forgot to adjust it" and needing to stop a print and adjust the z-offset on it's own.

Speaking of live z, it may be useful to have an additional option to live z adjust all sheets, but I don't think it's needed (and could add confusion if you're rushing to quickly adjust the first layer that you realized isn't as perfect as you hoped)

**Comment by MiniZagGi** [comment]
We would love this at work
