### ISSUE TITLE
[BUG] PS 2.2 estimate about 20% less than actual running 3.9.2 times

### ISSUE THREAD

**Issue by 3D-Musketeers** [prusa3d/Prusa-Firmware#2928]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches. -Did not find anything related to 3.9.2 in open or closed. 

Disclaimer, this is our first bug report. Please let us know if more information is needed. 

**Printer type** - MK3s
**Printer firmware version**-  9.9.2

**MMU Upgrade** - N/A
**MMU upgrade firmware version N/A

**SD card or USB/Octoprint**
  SD card

**Describe the bug**
Upgraded our machines from 3.8.x to 3.9.2 running identical Gcode prints now take about 20% longer whilst the PrusaSlicer estimate is unchanged
  
**To Reproduce**
Have only tested with a certain 2 files as we are in full production. As soon as this ends (a week or so) we will see if this can be replicated on other files. Did have a buddy test on his MK3s and had the same issue. Same file, sliced on the mini with identical settings resulted in a perfect estimate to print time. Issue seems to be MK3s specific

Slice file using PrusaSlicer 2.2.0 with stock filament settings (higher temps) and basically any speed settings (tried many with identical results for discrepancy) on an MK3s and it seems to reproduce this issue with the STL in the Google Drive below. The files were not designed by us, but rather a client. Files were made in Tinkercad. 

As soon as the printers were upgraded from 3.8.1 to 3.9.2 running identical code, this issue presented itself. Nothing else changed on the machines, even the filament as the same spool. 
  
**Expected behavior**
 Printer is accelerating and decelerating lazily, for reasons we cannot seem to identify other than the new LA 1.5. Video below: 

[3DMusketeers Video
](https://photos.app.goo.gl/Zyd6qwSfELaynN7k7
)
Machines are set to 800mm/s2 for acceleration, that is significantly lower than that. Visualizer shows that it is basically stopping right before the end, coasting, likely for LA 1.5 

Estimate 3hr20min Actual 4hr45min
Estimate 9hr40min Actual 11hr 17min
  
**G-code**
Find GCode and STL's here:  [3DMusketeers Drive](https://drive.google.com/drive/folders/1E6LCfHF9H5Zgi1YFHRqgb3sFgjZgaHeP?usp=sharing)

**Video**
[3DMusketeers video (same link)
](https://photos.app.goo.gl/Zyd6qwSfELaynN7k7
)
If you need additional information please do not hesitate to reach out. Talked to multiple people in the Prusa Discord and the ultimate decision was to report it here, although we fear it is a user error, other users were able to replicate the issue.

**Comment by JohnnyDeer** [comment]
Hi @3D-Musketeers, can you please try it with newest FW and PS? Thank you.
