### ISSUE TITLE
MMU wait for user issue.

### ISSUE THREAD

**Issue by totalitarian** [prusa3d/Prusa-Firmware#293]
Why do multi colour prints pause occasionally with the prompt on the lcd that says "wait for user...."

Tried to do a multi colour print last night and the print head stayed parked over the priming tower for hours on end. I tried to resume the print in the morning but the nozzle had melted the prime tower after being parked.

**Comment by bubnikv** [comment]
This wait is dictated by the Slic3r for you to inspect that all the filaments printing were primed correctly.
In case the priming towers collide with the object, Slic3r will wait for you to remove the priming towers and confirm.

We should improve Slic3r & firmware to provide a descriptive message on the printer display though.

**Comment by totalitarian** [comment]
I understand having it at the start, but it also seems to be doing this several times *during* the print. Is that normal?

**Comment by bubnikv** [comment]
The printer shall not stop during the print. Old firmware used to display "Wait" on a G4 G-code, which we use to flush the firmware planner queue at some point of time over the wipe tower, but that call should not stop the print.

Are you printing from a SD card or from an OctoPrint or Pronterface or any other application over the USB?

**Comment by totalitarian** [comment]
I'm printing from SD card, It's definitely pausing and waiting for user input when sat over the prime tower several times during a print

**Comment by cosmith71** [comment]
I had this happen today.  Approximately 9 hours into an SD print and the print head had stopped over the priming tower and was displaying "wait for user".  I'm not sure how long it had been that way (I hadn't checked on it in about 2 hours).  I was able to click the LCD knob and it started up again.

**Comment by cosmith71** [comment]
It just happened again.

Edit:  Firmware 3.1.0

![img_20171223_151130](https://user-images.githubusercontent.com/4393089/34322694-33707e54-e7f4-11e7-98da-57ce773952cc.jpg)
![img_20171223_151134](https://user-images.githubusercontent.com/4393089/34322695-348545c2-e7f4-11e7-94bf-529f55ef0b6a.jpg)

**Comment by cosmith71** [comment]
![img_20171224_101031](https://user-images.githubusercontent.com/4393089/34327986-9299fda2-e898-11e7-859d-482ce5569b83.jpg)
![img_20171224_101040](https://user-images.githubusercontent.com/4393089/34327987-96350808-e898-11e7-94a3-4752229f6147.jpg)

**Comment by ilusion316** [comment]
Same experiences here, please check https://shop.prusa3d.com/forum/original-prusa-i3-mk2-multi-material-f26/-wait-for-user--t6774.html for details. I believe there is an association with octoprint being connected and its communication with the printer while wiping.

**Comment by totalitarian** [comment]
I didn't have octoprint connected

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete. In case the issue is still not solved, please contact info@prusa3d.com.

Marina Curzi
Prusa Research
