### ISSUE TITLE
[FEATURE REQUEST]MMU2S: always step right after unloading to cut off strands

### ISSUE THREAD

**Issue by Mirarkitty** [prusa3d/Prusa-Firmware#2935]
**MMU Upgrade** MMU2S

**Is your feature request related to a problem? Please describe.**
When printing with filaments that don't get perfect tips but generate strands, it helps cutting them off with the selector. (Shape can be improved to improved this cutting and dropping strands.)

Currently this works fine (!!) on every move to the left since the blade will pass the strand, cutting it. The only issue is the rightmost filament (for any value of rightmost), which never will pass the knife.

**Describe the solution you'd like**
Add an option to always step to the right after unloading, thus cutting off the strands on the next left move. There is space to the right of the fifth position for cutting, so this should not be much of an issue to add in software.

**Comment by Mirarkitty** [comment]
Also see #2495 (question about cutting)

**Comment by rkarlsba** [comment]
I'd love to see this as well. Either in the firmware or somehow controllable via gcode.
