### ISSUE TITLE
[BUG] Octoprint Offline (Error: Printer keeps requesting line 36320 again and again, communication stuck)

### ISSUE THREAD

**Issue by Nagymadar** [prusa3d/Prusa-Firmware#2940]
**Printer type: Prusa MK2.5
**Printer firmware version: 3.9.1
**Octoprint USB Version 1.5.1
**Gcode: Slic3r Prusa Edition version 1.41.2+win64

Although it is a Octoprint error, it is new and seems to be related to the latest firmware only. The 3.9.1 MK2.5 firmware generates aborted print after ~15 mins on USB with Octoprint. Earlier firmware versions never had this issue. Googled it and many people seems to have this issue and advised to downgrade. Now downgraded to 3.9.0, and seems to work fine again.

**Comment by JohnnyDeer** [comment]
Hi @Nagymadar, can you please try it with newest FW and PS? Thank you.
