### ISSUE TITLE
  [ENHANCEMENT]<Cancel in choose filament dialog>

### ISSUE THREAD

**Issue by devrosx** [prusa3d/Prusa-Firmware#2944]
Enter what type of printer or upgrade the enhancement applies to.
Any MMU2S unit

**Is your enhancement related to a problem? Please describe.**

  
**Describe the solution you'd like**
If I enter a print, sometimes I skip the file when I turn the wheel (the shift move is not completely smooth) to the next wrong file and I have to restart the printer. Would be possible to add cancel or back button to choose filament table ...? It would save me a lot of time :) This could be usefull alse when you choose the wrong filament type by mistake. In this case would be great to add to print option change filament type button.

**Comment by pgilfernandez** [comment]
+1

It happens to me too... I would like to have this simple "cancel" option in the Filament selection screen

Thanks
