### ISSUE TITLE
[BUG] Heating disable by safety timer + empty display

### ISSUE THREAD

**Issue by MiOrt** [prusa3d/Prusa-Firmware#2947]
**Printer type** - MK3S
**Printer firmware version**-  3.9.1 - 3518

**MMU Upgrade** - no
**MMU upgrade firmware version -

**SD card or USB/Octoprint**
  n/a

**Describe the bug**
  After preheating PLA and filament change I needed to do some changes on the sliced file and went to the pc for approx. 3-5 minutes with heating still on. When I got back to the printer after this short time the display showed "Heating disable by safety timer" and after pressing the knob the display went blank with ">" in 3rd line. I could change the ">" from 3rd to 4th line by rotating the know but no further action was possible. Had to reset the printer.
  
**To Reproduce**
  No idea since this bug showed up before the regular safety timer should activate cool down.

**Expected behavior**
  n/a
  
**G-code**
  n/a

**Video**
  n/a

**Comment by gudnimg** [comment]
I can not reproduce this on 3.10.1-RC1

I preheated for PLA and the "Heating disable by safety timer" triggered after 30 minutes which is expected behaviour. Pressing the knob took be back to the Main info screen and printer was cooling down.
