### ISSUE TITLE
[BUG] One of the messages not displaying correctly in the printer screen

### ISSUE THREAD

**Issue by David-DL** [prusa3d/Prusa-Firmware#2958]
**Printer type** - MK3
**Printer firmware version**-  3.9.1-3518

**MMU Upgrade** - N/A
**MMU upgrade firmware version N/A

**SD card or USB/Octoprint**
Printing via Octoprint

**Describe the bug**
  With the printer idle, when the filament unload function is used, the message that appears on the screen after the heating is done do not displays correctly in the spanish language.
  
**To Reproduce**
- Set the printer language to spanish.
- With the printer idle and cold, select the unload filament option.
- When the heating is done, the following message will appear on the screen.

![image](https://user-images.githubusercontent.com/49383570/104248220-b5304380-542e-11eb-92c7-63da097b6fe0.png)
  
**Expected behavior**
  The message "Por favor, pulsa el dial para descargar el filamento" (Please, press the knob to unload the filament)
   is displayed correctly on the screen.

**Video**
  https://youtu.be/9QMROpwESY8

**Comment by JohnnyDeer** [comment]
I'm closing this issue as solved by mentioned #3022.
