### ISSUE TITLE
Static memory overwritten after print from SD start

### ISSUE THREAD

**Issue by HarrySatt** [prusa3d/Prusa-Firmware#2964]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK3S
**Printer firmware version**- 3.9.3

**MMU Upgrade** - none
**MMU upgrade firmware version : no

**SD card or USB/Octoprint**
 print via SD card

**Describe the bug**
  After preheating I started a print from the SD card. The display showed "static memory overwritten" and the heavy sound appeared. This was by moving stepper motors. Do not know which one because I immediatly shot down power to avoid damage.
After power up the printer worked again and did a perfect print.
  
**To Reproduce**
  At the moment not possible. Disappears after power down
  
**Expected behavior**
  Do not know. I want to get this in the records
  
**G-code**
  unknown

**Video**
  Not possible

**Comment by koisdigala** [comment]
I experienced this just now on a Mk3S with 3.10.0 firmware. Found someone else with the problem on Reddit, I'll paste their description and a link to Reddit. I experienced it in the same use-case as this poster.
https://www.reddit.com/r/prusa3d/comments/9k3sa8/got_static_memory_has_been_overwritten/
------
Got "static memory has been overwritten"

Oops.

I wanted to spool out a lot of filament to clean out the extruder, so I preheated for PLA, and when it hit 200 or so, I went to "move axis" and spun the wheel about 4 times.

I went back to "print from card" and clicked a file... and it sat there. I assumed it was waiting for the extruder to stop... but I noticed it was no longer responding to the spinner, and when the extruder did stop, I got "Error - static memory has been overwritten" and it hung.

Google says it's a stack-smash. It seems to be doing fine after cycling the power. It didn't appear to lose any calibrations.

That was a fun surprise.
