### ISSUE TITLE
[FEATURE REQUEST] G4 "sleep..." message and M117

### ISSUE THREAD

**Issue by daBernd** [prusa3d/Prusa-Firmware#2970]
In custom scripts I often use the G4 command. When used alone there is no message on the printer display. But used as G4 P1000 or G4 S2 the display shows sleep... - which does not disappear after the G4 command.
Also if you want to display a message like: "M117 Waiting for 30 sec" this message is replaced by the "sleep..." when followed by a "G4 P30000" command.

My Request is to add a message string option to the G4 command, or to check wether there is something written by a previous M117 command in the display already, and then not to replace it with a not-anything-saying "sleep..."

Also, let the "sleep..." disapear when the pause is over.

Best regards...

**Comment by PatB42** [comment]
well exactly same issue , still any reply or solution ? ?? after the M117 i type text but it only show on display for few sc then disappear even i added P500 ..

**Comment by buzkill420** [comment]
Up-vote!

**Comment by gudnimg** [comment]
This can be fixed similarly as for M601 in https://github.com/prusa3d/Prusa-Firmware/pull/3475
