### ISSUE TITLE
[FEATURE REQUEST]<Deactivating mmu2s in the menu>

### ISSUE THREAD

**Issue by mindelheini** [prusa3d/Prusa-Firmware#2973]
It would be great to have the option of deactivating the mmu2s in the menu of the printer so that I can use the printer without having to unplug the mmu from the mainboard if I want to use it with only one filament and without the mmu.

MK3S, MK3, MK2.5S
MMU2S, MMU2

**Comment by 3d-gussner** [comment]
@mindelheini Before you open a new issue request please read/fill in the template and search if this have been reported before.
This is a duplicated of https://github.com/prusa3d/Prusa-Firmware/issues/1876
Please close this issue.
