### ISSUE TITLE
[BUG] Initial XYZ calibration time incorrect

### ISSUE THREAD

**Issue by limited660** [prusa3d/Prusa-Firmware#2975]
**Printer firmware version**-  3.9.3

**Describe the bug**
  Display still shows 12 minutes for xyz calibration.
  
**Expected behavior**
  Update message to new time for the redesigned calibration of 3.9.3

https://github.com/prusa3d/Prusa-Firmware/blob/134f841380f8dfc704c28d9f0d598782bf732e81/lang/lang_en.txt#L365

**Comment by 3d-gussner** [comment]
Thanks for the comment, good point.

**Comment by gudnimg** [comment]
Issue was fixed here https://github.com/prusa3d/Prusa-Firmware/commit/7fef570d1b5230cd705f5d5d8219849772022c6d recently in 3.13 so I'm adding this to the 3.13 Milestone as a reminder for us to close this issue :)

**Comment by gudnimg** [comment]
Closing this as the fix is released with FW 3.13.0
