### ISSUE TITLE
[BUG] Stopping print while heating up leaves printer in strange state, reset required to get it working again

### ISSUE THREAD

**Issue by fe60** [prusa3d/Prusa-Firmware#3019]
**Printer type** MK3S
**Printer firmware version**  3.9.3

SD card ~~or USB/Octoprint~~

**Describe the bug**
Stopping a print while the printer is still heating up, leaves the printer in a strange state.
I have to reset the printer to trigger a new print.
  
**To Reproduce**
  * Start a print from SD card
	Use an arbitrary existing .gcode file. You will stop the print job before it starts printing.
  * Wait a moment to see temperature of nozzle raising.
  * Stop the print.
  * Fine
    * LED of print bed indicating heating is switched off
    * temperature of bed and nozzle drops
  * Wrong
    * Display still shows "Bed heating..."
    * It's not possible to start a new print. I have to reset the printer to start the next print.
  
**Expected behavior**
  Triggering a new print shall be possible without a reset. Just as it works when a print is stopped while it is already printing.

**Comment by scottmudge** [comment]
Edit: Ignore

**Comment by leptun** [comment]
@scottmudge Stopping an SD print during heatup should have worked correctly, so it is a bug. Just octoprint can't be canceled unless you use some plugin which does blocking behaviour on the host side, not the printer side.

**Comment by scottmudge** [comment]
The more you know!

**Comment by sberkovitz** [comment]
I have observed this behavior a few times but I do not need to restart the printer. It seems to clear on its own in a minute or so (haven't timed it, but can if that's useful). 

In this state, if you press and hold the button, you will get Live Z Adjust versus setting the Z axis value.

**Comment by fe60** [comment]
There was an older issue #2862, but it has been closed by a bot.

**Comment by fe60** [comment]
The bot asked for a comment, it gets a comment.

**Comment by gudnimg** [comment]
Assigned this to myself so it won't be closed. I can try test this when I find time. I think this issue is solved in 3.13.2... but I will have to test it to be sure.

**Comment by fe60** [comment]
Works as expected in 3.13.3
