### ISSUE TITLE
Printer Software crashing when trying to print gcode files containing letters such as "ä, ö or ü" (file sliced with PrusaSlicer)

### ISSUE THREAD

**Issue by JakobSuppan** [prusa3d/Prusa-Firmware#3025]

**Comment by scottmudge** [comment]
I thought the firmware command parser ignored characters outside of the standard ASCII range (0-127U)

Those characters are 132U, 153U, and 129U respectively. 

Are the characters comments inside the g-code file, or are they part of the filename?

**Comment by leptun** [comment]
The fatFS implementation used can only use the standard ascii range, not also the UTF-16 extended range that is supported by FAT32

**Comment by DRracer** [comment]
... closing this issue as the description doesn't follow the issue template. 
Moreover it is unclear where these characters occurred (inside a G-code file or in a file name).
