### ISSUE TITLE
Hardcoded +8 Y_MAX_POS  margin 

### ISSUE THREAD

**Issue by jbrunner** [prusa3d/Prusa-Firmware#3030]
Today I had a hard time to calibrate my Y axis length. The function lcd_selfcheck_axis_sg logs the measured axis length but when i set Y_MAX_POS to the measured length, selftest still fails.

Then I figured out, there is a hardcoded +8 margin:

https://github.com/prusa3d/Prusa-Firmware/blob/e010ca8ceb87e875d9353b55b8b69e97dca91cc5/Firmware/ultralcd.cpp#L7620

does it make sense to fix that?
In consequence Y_MAX_POS must be increased by 8 in firmware/variants/*.h.

**Comment by gudnimg** [comment]
This was introduced in 2017 with only the word "selftest". I have no idea why + 8 is needed.

https://github.com/prusa3d/Prusa-Firmware/commit/54ef2936c76d0846413b49c614d0cdb0f5910f1e#diff-5fbfdca43c192573e31d8e78d255c510fb6e213b118cf38173277ec2a2163880
