### ISSUE TITLE
[BUG]<Downgrade from 4.3.1 to 4.2. Is not possible 

### ISSUE THREAD

**Issue by Af5211** [prusa3d/Prusa-Firmware#3031]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [Prisa. Mini+]
**Printer firmware version**-  [4.3.1

**MMU Upgrade** - [e.g. MMU2S, MMU2, MMU1]
**MMU upgrade firmware version [e.g. 1.0.6, 1.0.6-RC2, ...]

**SD card or USB/Octoprint**
  Please let us know if you print via or USB

**Describe the bug**
  Downgrade 4.3.1 to 4.2.1 or 4.3 not possible
  
**To Reproduce**
  Please describe steps to reproduce the behavior.
  
**Expected behavior**
  
**G-code**
  Please attach a G-code. This will make it easier for us to replicate the error.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by leptun** [comment]
This is Prusa Mini related. Please post the issue here: https://github.com/prusa3d/Prusa-Firmware-Buddy/issues
Also, please fill the template next time.

**Comment by JohnnyDeer** [comment]
This issue is solved in MINI repository, I´m closing.
