### ISSUE TITLE
[BUG] M73 does not show any remaining time

### ISSUE THREAD

**Issue by fuso2001** [prusa3d/Prusa-Firmware#3037]
**Printer type** - MK3S+
**Printer firmware version**- 3.9.3 commit 3556

**MMU Upgrade** - MMU2S

**SD card or USB/Octoprint**
  Print via USB/Octoprint

**Describe the bug**
  M73 Commando only shows the completed percentages in the display. The remaining time display remains at 0. The messages via the USB interface towards the host are OK and contain the new "C" object. Time to change is a "-1" value.
  
**To Reproduce**
  Start a print and watch the display.
  
**G-code**
  G-Code was generated with PrusaSlicer and contains M73 commands

**Comment by 3d-gussner** [comment]
@fuso2001 Thanks for reporting. Please add next time that you compiled the firmware in the **Printer firmware version** part.

**Comment by fuso2001** [comment]
> **Printer type** - MK3S+
> **Printer firmware version**- 3.9.3 commit 3556
> 
> **MMU Upgrade** - MMU2S
> 
> **SD card or USB/Octoprint**
> Print via USB/Octoprint
> 
> **Describe the bug**
> M73 Commando only shows the completed percentages in the display. The remaining time display remains at 0. The messages via the USB interface towards the host are OK and contain the new "C" object. Time to change is a "-1" value.
> 
> **To Reproduce**
> Start a print and watch the display.
> 
> **G-code**
> G-Code was generated with PrusaSlicer and contains M73 commands

> @fuso2001 Thanks for reporting. Please add next time that you compiled the firmware in the **Printer firmware version** part.

> Okay, thank you for the answer. I now set starttime to _millis () in the M862.3 command. It works now.

**Comment by 3d-gussner** [comment]
Should be fixed with https://github.com/prusa3d/Prusa-Firmware/pull/3067

**Comment by JohnnyDeer** [comment]
I'm closing this issue as solved by mentioned #3067.
