### ISSUE TITLE
Calbration xyz showing strange behavior with defective PINDA Probe MK3

### ISSUE THREAD

**Issue by Sodamaexchen** [prusa3d/Prusa-Firmware#304]
when the PINDA Probe is defective or has a broken wire the XYZ Calbration on the MK3 starts to search for the calibration points at Z 210. 

see here: https://www.youtube.com/edit?o=U&video_id=X5-wjcL2GjU

There should be a waring "your PINDA Probe is defective" like during the auto home or mesh bed leveling.

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete.

Marina Curzi
Prusa Research
