### ISSUE TITLE
  [ENHANCEMENT] Support for 0.8mm nozzle in Prusa's Hardware Nozzle Size Menu

### ISSUE THREAD

**Issue by salmander** [prusa3d/Prusa-Firmware#3042]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MK3S, MK3S+ etc. 
**MMU Upgrade** - MMU2S

Along with PVB Prusament, Prusa has announced support for larger nozzle sizes i.e. 0.8mm. However, in the printer's nozzle size menu there are only 3 nozzle sizes listed: 0.25, 0.4, 0.6.

 
Please add support for choosing 0.8 mm nozzle as well.

**Comment by DRracer** [comment]
@salmander yes, this feature is coming soon, see PR #2951

**Comment by salmander** [comment]
Awesome. I will close this issue now
