### ISSUE TITLE
[FEATURE REQUEST]<ability to select individual object/s for brim >

### ISSUE THREAD

**Issue by dotinkering** [prusa3d/Prusa-Firmware#3044]
If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** - [MK3S]
**MMU Upgrade** - [MMU2S]

**Is your feature request related to a problem? Please describe.**
  A clear and concise description of what the problem is. Ex. I'm always frustrated when [I have multiple items in the slicer program and I would only like to have a brim around a one or two objects, not all the print objects]
  
**Describe the solution you'd like**
  I would like the ability to add brim on selected items rather than all the objects on the build plate. similar to changing the infill type or percentage or wall thickness.

**Comment by rtyr** [comment]
This is not firmware related. There are already opened feature requests for this in PrusaSlicer repository. https://github.com/prusa3d/PrusaSlicer/issues/286, https://github.com/prusa3d/PrusaSlicer/issues/1033.

This issue can be closed.
