### ISSUE TITLE
[QUESTION] Is MK2 firmware still being maintained?

### ISSUE THREAD

**Issue by jordansissel** [prusa3d/Prusa-Firmware#3045]
Hi!

Is MK2 firmware still maintained and available anywhere? On prusa3d.com/drivers and here, the oldest printers I see mentioned are the MK2.5.

**Comment by rtyr** [comment]
It is available on https://www.prusa3d.com/drivers/.

![mk2](https://user-images.githubusercontent.com/36745189/109271630-190ca100-7810-11eb-8a31-24e1bb63469a.jpg)

**Comment by jordansissel** [comment]
@rtyr Ahh I missed that, thank you!
