### ISSUE TITLE
Setup Wizard crashing on MK3

### ISSUE THREAD

**Issue by Sodamaexchen** [prusa3d/Prusa-Firmware#305]
About every second or third time using the setup wizard it crashes.  But not always at the same point. It happens after one tasks (e.g. self test) is finished and the next should start (e.g. axis calibration). 
with chrashing i mean that the printer restarts, like when you press the reset button.

**Comment by PavelSindler** [comment]
In RC1 printer was reseted in the end of selftest and during PID calibration. This was due to newly implemented watchdog, which is very good safety feature, but unfortunately, there were some cases, where it haven't worked well in RC1. It should be ok in RC2.
