### ISSUE TITLE
[ENHANCEMENT] add default sheets for Satin

### ISSUE THREAD

**Issue by mirineumark** [prusa3d/Prusa-Firmware#3051]
**Printer type** - MK3S+
**MMU Upgrade** - N/A

**Is your enhancement related to a problem? Please describe.**
  There is no steel sheet named after Satin sheets so you have to use Custom sheets
  
**Describe the solution you'd like**
Add a few slots for Satin1, Satin2, et cetera.

**Comment by DRracer** [comment]
@mneumark this is a very nice issue. It shows how some users understand the sheet profile slots - no offense, we are glad you reported this. 
Technically: all sheet preset slots are equivalent and differ only by their default names which can be changed by the user (even though typing 7 characters on the knob is a kind of retro game).

**Comment by mirineumark** [comment]
I know you can rename slots. I already renamed one to Satin. But if you are going to have smooth and textured defaults it's inconsistent to not have them for satin sheets too.

**Comment by awenelo** [comment]
@mneumark, release 3.10.0 adds satin sheets (`Satin 1` and `Satin 2`) to the default sheet names list. Please consider closing this issue.

To get the new names, you'll need to reset sheets 5 and 6 (previously `Custom1` and `Custom2`) using `Settings -> HW Setup -> Steel Sheets -> [sheet name] -> Reset`. Note that this will also reset the Z-offsets saved to these sheets.

**Comment by mirineumark** [comment]
Awesome. Thanks!
