### ISSUE TITLE
[FEATURE REQUEST] Make the printer go to stealth when not printing

### ISSUE THREAD

**Issue by lumilla** [prusa3d/Prusa-Firmware#3060]
Simply, when the printer finishes printing, if the user has set a setting like _Silent Idling_ when the printer finishehs printing. 
Dont get me wrong, its silent as it is but it doesnt cost anything to put it in stealth mode when its not printing, and if you can do that it will be a tiny bit quieter.

**Comment by DRracer** [comment]
@J3r0github I'm not sure if I understood correctly - the MK3/S/+ already switches the Z-motors into silent mode to lower even the noise coming from the PSU automatically when not printing. 

What else do you expect the printer does? Fans are off, motors are not moving, heaters are off... the only thing running at idle is the motherboard and that is completely silent.

**Comment by brettvitaz** [comment]
I have noticed this as well. When not in silent mode and not printing, the stepper motors whine. This is especially noticeable on the MMU2S for some reason.

**Comment by wavexx** [comment]
I think this might be due to "stepper hold". If you go to "Settings -> Disable steppers" do you notice a reduction in noise?

**Comment by JohnnyDeer** [comment]
I'm closing this issue because there are no responses.
