### ISSUE TITLE
[QUESTION]Pause/Resume functions improved in 3.10 release open a possibile resuming from octoprint?

### ISSUE THREAD

**Issue by gorobey** [prusa3d/Prusa-Firmware#3074]
Pause/Resume functions improved in 3.10 release open a possibile resuming print from octoprint?

**Comment by zeroflow** [comment]
Yes, you only have to set up octoprint accordingly.

I can confirm, that it works with the following settings:

Pausing commands: `M0, M1, M25, M600, M601`
After print job is paused: <nothing>
Before print job is resumed: `M602 ; Resume print`

What doesn't work is pausing with the default button.
There you have to add a seperate `M601` button.
If you put `M601` into `After print job is paused`, it will send additional `M601` commands when the print is paused by gcode.

**Comment by gorobey** [comment]
I intend on power loose:
I have not tried, but at moment, if i pause a print and power off, i can cab resume work, it is correct?
With new feature is possible "automate it"?!

**Comment by 3d-gussner** [comment]
At this moment please add
`M601` to After print job is paused: in OctoPrint
to get Pause/Resume from SD and Octoprint working

**Comment by DRracer** [comment]
@gorobey no, powering off the printer does not keep the paused print at all. This is NOT a pause/resume function.

The only similar situation is called the Power Panic which in fact does what you want, but the Octoprint cannot keep up AFAIK.

**Comment by zeroflow** [comment]
> At this moment please add
> `M601` to After print job is paused: in OctoPrint
> to get Pause/Resume from SD and Octoprint working

For me, this setting works when Pausing with the pause button, but not if I put M601 into the GCode.
This setting + M601 in gcode triggers repeated pauses, which mess everything up.

My understanding is:

GCode M610 -> Printer pauses -> Config M601 is queued in Octoprint -> Printer resumes (M602) -> Queued M601 is sent to printer -> Octoprint keeps sending gcode, printer continues moves, but hotend is turned off
