### ISSUE TITLE
[FEATURE REQUEST]<Add LA1.5 K-factor Calibration Routine to Prusa Firmware>

### ISSUE THREAD

**Issue by 5jvm0u4** [prusa3d/Prusa-Firmware#3076]
**Is your feature request related to a problem? Please describe.**
Since the K-factor differs with every different filament brand, sometimes even colors. It's reasonable, in my opinion, to add this function to the calibration menu, rather then going to Marlin's website every time to generate the gcode.
  
**Describe the solution you'd like**
Click into the calibration menu, run LA1.5 K-factor script, pick the K-factor interval and stepping, tell the user to pick the straightest line and record the corresponding K-factor. It's even better to have a dedicated setting in PrusaSlicer->Filament Setting->Advanced->LA1.5 K-factor for user to just type in their result.

P.S. Or make PrusaSlicer able to generate K-factor calibration pattern, but that's another topic for another day.

**Comment by DRracer** [comment]
please read https://www.prusaprinters.org/cs/prints/39968-la15-k-factor-calibration
