### ISSUE TITLE
  [ENHANCEMENT] Manual temperature entry should have a non-zero initial value 

### ISSUE THREAD

**Issue by domverity** [prusa3d/Prusa-Firmware#3085]
MK3S - When there is no heating explicitly set and you go to Settings -> Temperature -> Bed | Nozzle and click the wheel the enter a temp, the initial value is zero, but I would suggest that the majority use-case is setting bed to >=60 and nozzle to >=200, which causes excess wear-and-tear on the rotary dial spinning it through (mostly) useless numbers.

**Comment by Panayiotis-git** [comment]
Nice proposal. Relates to the https://github.com/prusa3d/Prusa-Firmware/issues/2733

**Comment by gudnimg** [comment]
I don't see why this would be needed. If you start a print then the printer will raise the temperature as set in the Prusa Slicer. I think it makes more sense to keep it as is.

Only use case I can see at the moment is if you want to heat up the nozzle to clean it/change it. Then its probably quicker to use the Preheat menu. (I think we could add an option to only preheat the Nozzle to save energy 🤔 )

Say we made this change... what if I start changing the temperature but then want to cancel? I would need to scroll all the way back to zero or turn off the printer.

**Comment by domverity** [comment]
@gudnimg as you say, the use-case here is non-printing purposes, like nozzle change. Nozzle-only preheat (and in fact bed-only preheat, for other reasons) would be a useful alternatives, as would jumping in increments of say 5C instead of 1C.

**Comment by mix579** [comment]
I *love* this idea. Every time I change a nozzle—and I do it a lot—I'm irritated that I have to spin the wheel like crazy to go from 0 to 285 degrees. Starting with 60 or even 80 would make a lot more sense.
