### ISSUE TITLE
Dutch translation in 3.10.0-RC1 firmware

### ISSUE THREAD

**Issue by nielssteenvoorde** [prusa3d/Prusa-Firmware#3087]
I'm now using your 3.10.0-RC1 firmware in my prusa i3MK3S printer and the dutch translation (Nederlands) doesn't show up under community made? Am I doing something wrong? Is there an explanation why it doesn't show up? I really was looking forward to this.

**Comment by DRracer** [comment]
@nielssteenvoorde did flashing the FW end up correctly? Including languages?

**Comment by 3d-gussner** [comment]
Please post here your Prusa Slicer Firmware update output you can see in advanced.

**Comment by 3d-gussner** [comment]
@nielssteenvoorde Can you please give us an update on this issue, or if solved close it?

**Comment by 3d-gussner** [comment]
[stale]  @JohnnyDeer please close this issue as it got stale and there is no reaction from owner.

**Comment by JohnnyDeer** [comment]
@nielssteenvoorde I'm closing this issue for not responding.

**Comment by nielssteenvoorde** [comment]
> @nielssteenvoorde did flashing the FW end up correctly? Including languages?

yes the flashing of the firmware was without any errors. I mostly do it by interface octoprint (firmware updater plugin). No problems there

**Comment by nielssteenvoorde** [comment]
> [stale] @JohnnyDeer please close this issue as it got stale and there is no reaction from owner.

sorry, i was in hospital for a while ;-(

**Comment by 3d-gussner** [comment]
Hope you are doing well again.
Octoprint Firmware flasher plugin can flash MK2.x with multiple languages BUT not MK3/S/+ as the languages are stored in the external flash and the plugin doesn't do the 2nd flash process which is implemented in PrusaSlicer.
Please use PrusaSlicer to flash MK3/S/+.
