### ISSUE TITLE
[BUG]Unknown M code: M33 in 3.10.0-RC1

### ISSUE THREAD

**Issue by CWStevens** [prusa3d/Prusa-Firmware#3092]
**Printer type** - MK3S
**Printer firmware version**-  3.10.0-RC1

**SD card or USB/Octoprint**
I print from the front panel / SD card, but monitor progress from Octoprint via Raspberry Pi Zero W mounted inside the control box.

**Describe the bug**
3.10.0-RC1 does not appear to support M33 any longer.  OctoPrint (using the "Long-SD-list-paths (1.0.0)" plugin script) uses the M33 command to retrieve the long filenames from the SD card. 
[https://github.com/Petttkous/OctoPrint-Longpathsdlist](https://github.com/Petttkous/OctoPrint-Longpathsdlist)
  
**To Reproduce**
Send: M33 /cam_cl\~2.gco
Recv: Unknown M code: M33 /cam_cl\~2.gco
  
**Expected behavior**
https://marlinfw.org/docs/gcode/M033.html
  
**G-code**
Send: M33 /cam_cl\~2.gco
Recv: Unknown M code: M33 /cam_cl\~2.gco
  
**Video**
n/a

**Comment by DRracer** [comment]
@CWStevens I don't think "_doesn't support M33 any longer_" is the correct wording - there has been no support for M33 at all yet. In 3.10.x we added another way of reporting long file names via `M20 L` which suits our purposes better (and requires negligible amount of additional code and RAM). We are testing this solution right now.

**Comment by CWStevens** [comment]
I thought it was at least partially working in the 3.9.3 release.  I see now that @foosel prefers the "**M20 L**" update for use in OctoPrint: [https://github.com/MarlinFirmware/Marlin/issues/19960]https://github.com/MarlinFirmware/Marlin/issues/19960
So, I retract my issue.

Thanks @DRracer !
