### ISSUE TITLE
[FEATURE REQUEST] Beep at the end

### ISSUE THREAD

**Issue by zerink** [prusa3d/Prusa-Firmware#3108]
An option BEEP AT THE END would be nice, and to be able to turn ON or OFF in the menu while printing.
My printer: I3 mk3s+

**Comment by 3d-gussner** [comment]
@zerink Please search the issues before creating a new one as this is a [duplicate] of https://github.com/prusa3d/Prusa-Firmware/issues/2398.
Please consider to close this issue.
