### ISSUE TITLE
[QUESTION]<Enter comprehensive title>

### ISSUE THREAD

**Issue by craiglink** [prusa3d/Prusa-Firmware#3126]
Please, before you create a new question, please make sure you searched in open and closed issues and couldn't find anything that matches.

**What is your question?**

what build settings / defines should be set to enable MMU2S support in the firmware verses creating non-mmu firmware.  Prusa published both when releasing Firmware.  The difference and settings to build both should be documented.  Thanks

**Comment by leptun** [comment]
There is no MK2.5/3 firmware that doesn’t support the MMU2. It’s the same binary file for both with and without the MMU2. The printer determines whether it’s a MMU2 printer or not at startup when attempting to communicate with the MMU2 unit.
