### ISSUE TITLE
  [ENHANCEMENT] Interface layer fan speed. 

### ISSUE THREAD

**Issue by jmdonhauser** [prusa3d/Prusa-Firmware#3127]
Printer: ALL Prusa printers applicable

Problem: Poor support interface layer quality
  
Solutions: update in prusaslicer that allows higher fan speed for interface layers so the layers solidify faster.

**Comment by wavexx** [comment]
@jmdonhauser you should file such as request in the PrusaSlicer repository

**Comment by JohnnyDeer** [comment]
As @wavexx wrote this issue should be in PrusaSlicer repository. @jmdonhauser please create there request following template.
