### ISSUE TITLE
Extruder head continues to move after 'stop print'

### ISSUE THREAD

**Issue by michgsy** [prusa3d/Prusa-Firmware#3131]
Started to notice an issue with my mk3s. I select 'stop print' part way through a print, and the print stops, but the extruder head does not go home. Instead, it stays where it is and stops moving/extruding. The next time the extruder head is prompted to move - either through a manual movement of the z-axis, or starting the next print, the extruder head will print the next few movements of the print that was stopped, stopping, lifting and homing after about 5 seconds, almost as if the print gcode has gotten stuck in its memory somehow

**Comment by wavexx** [comment]
Which firmware version and on what printer this happens?

**Comment by michgsy** [comment]
Latest firmware (V3.9.3 07/01/21) on an MK3S

**Comment by Prusa-Support** [comment]
Hello! Sorry for intervening on this so late. Was this resolved on the subsequent firmware released in the meantime? Let me know, in case of current issues with this we'll keep looking into it. 

Alessandro Pantaleo
Prusa Research
