### ISSUE TITLE
[ENHANCEMENT] If no files present on SD, do not show SD menu on SD card insertion 

### ISSUE THREAD

**Issue by MohanMaker** [prusa3d/Prusa-Firmware#3143]
**Printer type** - All

**Is your enhancement related to a problem? Please describe.**
Currently, when you insert the SD card into the printer, the print from SD menu pops up, showing the files on the SD card. Unfortunately, if there are no files present, the menu still pops up, just blank. 
 
**Describe the solution you'd like**
 If the printer detects that there are no files present on the SD card when it’s inserted, it should not pull up the files list menu.

**Comment by 3d-gussner** [comment]
@MohanMaker Thanks for the feature request.
But why would you like add extra code to disable the SD card menu if someone puts an empty card in?
If it is empty the user sees that it is empty and switches to a correct one.
Prusa-Firmware uses quite a lot of the limited resources of the atmega2560 and developers constantly try to squeeze additional features in.

**Comment by MohanMaker** [comment]
@3d-gussner Interesting, I did not think of it like that. It probably makes sense to leave it how it is, considering it would also use up some of the limited resources of the processor. I'll close the issue.
