### ISSUE TITLE
[BUG] No language selection possible

### ISSUE THREAD

**Issue by andreapede** [prusa3d/Prusa-Firmware#3144]
**Printer type** - MK3S+
**Printer firmware version**-  3.10.0

**Describe the bug**
  After firmware update, if you select "italian" in the language menu, the message o copy language appears but loop in the change language settings. 
 With english works correctly. Didn't try other languages.

**Comment by 3d-gussner** [comment]
@andreapede How did you flash the firmware?
At this moment only PrusaSlicer Firmware upload will work correctly for Multi-language firmware on MK3/S/+

Octoprint and other firmware updater DO NOT flash the external flash of the EINSY where the multi-languages need to be so the firmware can copy them correctly.

**Comment by andreapede** [comment]
Got it. I exactly did it with octoprint. I'll redo it with prusaslicer and I'll update this file

**Comment by 3d-gussner** [comment]
If it works please close the issue.

**Comment by andreapede** [comment]
> If it works please close the issue.

Doing from prusaslicer works perfectly. Ty
