### ISSUE TITLE
[BUG] MK3S, MMU2S, Octoprint filament cut after I manually correct filament loading error firmware 3.10

### ISSUE THREAD

**Issue by langph** [prusa3d/Prusa-Firmware#3152]
**Printer type** - MK3S+
**Printer firmware version**-  3.10.0
**MMU Upgrade** - MMU2S
**MMU upgrade firmware version 1.0.6
**USB/Octoprint**
  Please let us know if you print via SD card or USB/Octoprint

**Describe the bug**
 If filament loading fails after some tries, the filament loading problem has to be solved manually. A message like "pause for user" appears. Before that message there was no attempt to cut the filament. After I correct the problem manually ( cutting the filament and place it back in the mmu2) and press the middle button of the MMU2, the led becomes green but it then proceeds to cut the filament before loading it and starting the print,

**Expected behavior**
The filament should be cut and a new loading attempt after the filament cut should have failed before the message "pause for user" appears and not after the user has manually solved the issue

**Comment by JohnnyDeer** [comment]
Hi @langph, thank you for reporting. This issue is so specific and don't cause any fail therefore it have very low priority. Thank you for understanding.
