### ISSUE TITLE
[BUG] Octoprint M601 pause resumes without nozzle temperature control

### ISSUE THREAD

**Issue by mjroux1984** [prusa3d/Prusa-Firmware#3154]
Link to Octoprint bug: https://github.com/OctoPrint/OctoPrint/issues/4146

MK3S+
3.10.0

MMU2S
1.0.6

USB/Octoprint

**Describe the bug**
When gcode is run from Octoprint/USB with M601 pause embedded through Prusaslicer 2.3.1 layer height function, the printer will pause correctly, but after resuming from either the printer or the octoprint server, the printer will attempt to print without controlling temperature of the nozzle (nozzle will be cooled off to room temperature).  In addition, the LCD screen on the MK3S will go blank (backlight stays on, but not txt is shown).  This issue doesn't occur when same gcode is run from sd card.  When firmware is downgraded to 3.9.3, the issue does not occur over USB/Octoprint.
  
**To Reproduce**
Any gcode produced from Prusaslicer 2.3.1 with inserting pause at specific layer height (through I included example gcode with M601 pause after 1st layer)
Print over USB/Octoprint
Octopi 0.18.0
Octoprint 1.6.1 (safe mode and normal mode tried)
Use firmware 3.10.0 on MK3S+ and firmware 1.0.6 on MMU2S
  
**Expected behavior**
When resuming print, the printer would wait for nozzle temperature to reach required temperature.  Works as expected with firmware 3.9.3.
  
**G-code**
[pause_test_0.2mm_PETG_MK3SMMU2S_33m.zip](https://github.com/prusa3d/Prusa-Firmware/files/6517313/pause_test_0.2mm_PETG_MK3SMMU2S_33m.zip)

**Video**
none

**Serial.log from Octoprint**  issue occurs after timestamp "2021-05-20 17:35:58,172"
[octoprint-logs.zip](https://github.com/prusa3d/Prusa-Firmware/files/6517560/octoprint-logs.zip)

**Comment by mjroux1984** [comment]
Updated with serial.log from octoprint.

**Comment by wavexx** [comment]
Isn't this similar to https://github.com/prusa3d/Prusa-Firmware/issues/3148#issuecomment-843442610 ?

**Comment by mjroux1984** [comment]
> Isn't this similar to [#3148 (comment)](https://github.com/prusa3d/Prusa-Firmware/issues/3148#issuecomment-843442610) ?

Seems like it, my search for an existing bug wasn't adequate.  You may close it.

**Comment by wavexx** [comment]
Can't close it, as a creator you should be able to.

**Comment by mjroux1984** [comment]
This is a repeat of 3148.
