### ISSUE TITLE
[BUG]<special character in the file name doesn't let the printer print>

### ISSUE THREAD

**Issue by raff96** [prusa3d/Prusa-Firmware#3219]
Hi everyone, i was trying to print a file that had a " ° " in the name and when i tried selecting it in the printer it said that the file was incomplete, after a couple o new file from the prusaslicer i tried printing it again and even if i ignore the warning the printer just doesn't print it. When i realized that the problem what the character i just removed it from the name and everything went fine.
[INFO]
Printer: MK3/S
Firmware:3.10.0-4481
SD card: yes
video: https://drive.google.com/file/d/1gBdB3r3n7L1f2sOPdAnJk5rO-yd6iQs-/view?usp=sharing

**Comment by DRracer** [comment]
Please use only basic ASCII in the file names - that's a feature. The way FAT filesystem is done (no UTF-8) we cannot support anything beyond 32-127. I bet if you tried to open this file of yours on a computer with some other system encoding, it wouldn't be able to open it as well.
