### ISSUE TITLE
Brim runs over skirt. Skirt redundant when using brim

### ISSUE THREAD

**Issue by Spinnetti** [prusa3d/Prusa-Firmware#3231]
MK3
3.10.0.4481
SD

When selecting both brim and skirt, the skirt prints and the brim prints (or can print) over the skirt
  
**Expected behavior**
  Either:
     a) the skirt should print outside of the brim range, or 
     b) (preferred) the skirt is suppressed since the brim will do the job of the skirt anyway.

**Comment by 3d-gussner** [comment]
@Spinnetti This is PrusaSlicer related and not Firmware, please close this issue here and open it in https://github.com/prusa3d/PrusaSlicer/issues

**Comment by neophyl** [comment]
There is already a report for that in PS and it is intended operation apparently as it's under user control from their setting choices.

Also as the skirt can be made higher to act as a draft shield it is sometime handy to have it print on top of the brim for stability.  So it is not redundant.

**Comment by DRracer** [comment]
Not firmware related, closing
