### ISSUE TITLE
Elephant foot compensation causes disconnect from Brim

### ISSUE THREAD

**Issue by Spinnetti** [prusa3d/Prusa-Firmware#3232]
MK3
3.10.0.4481
SD

**Describe the bug**
Elephant foot compensation causes disconnect from Brim. Should shut off when brim is selected
  
**To Reproduce**
in all cases where both elephant foot compensation and brim are selected
  
**Expected behavior**
Either:
a) The brim should still be attached. 
b) (preferred) suppress either elephant foot compensation or brim since they don't seem to work together. My current workaround is to just not use elephant foot compensation

**Comment by 3d-gussner** [comment]
@Spinnetti This is PrusaSlicer related and not Firmware, please close this issue here and open it in https://github.com/prusa3d/PrusaSlicer/issues
