### ISSUE TITLE
Selecting any function after selecting load filament, the firmware crashes

### ISSUE THREAD

**Issue by Spinnetti** [prusa3d/Prusa-Firmware#3234]
MK3
3.10.0.4481
SD

**Describe the bug**
If I do an action like load filament, then pick another action, the software crashes and restarts (need to confirm specific action sequences). 
  
**To Reproduce**
From cold start, select load filament, then as its heating, select another function
  
**Expected behavior**
 Should have an option to cancel, and  disallow any actions other than <Cancel> till the current operation completes

**Comment by 3d-gussner** [comment]
I think there is already an reported issue. Please search the issues before creating a new one.

**Comment by DRracer** [comment]
Please try on the latest firmware: 3.10.1-RC1

**Comment by Spinnetti** [comment]
Will do, thanks

**Comment by DRracer** [comment]
@Spinnetti did FW 3.10.1-RC1 solve your issue?

**Comment by Spinnetti** [comment]
Thanks for the follow up. Sorry, haven't installed yet, will go download.

**Comment by JohnnyDeer** [comment]
This issue will be closed soon if autor will not respond.

**Comment by Spinnetti** [comment]
This is resolved. Now only allows cancel function as one would expect.

**Comment by Spinnetti** [comment]
With the latest firmware, still crashes. To Reproduce:

1. Select Load filament
2. While loading, I selected "Print from SD"

Result: Firmware crash and reboot.

**Comment by leptun** [comment]
@wavexx Could this be stack smashing again because of st_sync?

**Comment by wavexx** [comment]
Yeah might be. While the filament is loading, we're running another loop which allows menu selection.
If I understand the correct sequence, it's:

- Load filament
- If preheat is needed, allow it to finish
- Filament starts to load
- Select "Print from SD"

**Comment by Spinnetti** [comment]
Latest update fixed.. Only option after preheat is cancel which is a "good enough" solution.

**Comment by flohoff** [comment]
I experienced the same crash.

1. Unloaded filament.
2. Pushed new filament in
3. While filament was pulled in i selected "Print from SD" 
4. and had an immediate restart/crash.

This is with newest firmware prusa3d_fw_MK3S_MK3S+_3_11_0_4955.hex. Flashed yesterday.

**Comment by wavexx** [comment]
This should be handled correctly with #3564 (feedback would be welcome)

**Comment by Spinnetti** [comment]
Thanks for that... Will check.
