### ISSUE TITLE
Enable global settings that each quality setting inherits unless overridden.

### ISSUE THREAD

**Issue by Spinnetti** [prusa3d/Prusa-Firmware#3236]
MK3
3.10.0.4481
SD

- Enable global settings that all the quality settings inherit (unless overridden) so I don't have to edit every quality setting. For instance, I want brims to default to 4mm, no skirt lines, and turn off elephant foot compensation when a brim is used for all profiles instead of the default. Right now, I have to select for every setting and every material independently.

**Comment by 3d-gussner** [comment]
@Spinnetti This is PrusaSlicer related and not Firmware, please close this issue here and open it in https://github.com/prusa3d/PrusaSlicer/issues
