### ISSUE TITLE
Simplify/allow independent print settings (where sensible) for each object in the print

### ISSUE THREAD

**Issue by Spinnetti** [prusa3d/Prusa-Firmware#3238]
MK3
3.10.0.4481
SD

Simpler way to modify settings by part. For example, I have 3 parts on the bed, I want to click on that body, then set the layer height, brim, skirt etc. for each part separately. All parts would get the same settings as current by default, but if I click on just one part, any changes apply to just that part.

**Comment by 3d-gussner** [comment]
@Spinnetti This is PrusaSlicer related and not Firmware, please close this issue here and open it in https://github.com/prusa3d/PrusaSlicer/issues
