### ISSUE TITLE
Non-planar printing

### ISSUE THREAD

**Issue by Spinnetti** [prusa3d/Prusa-Firmware#3239]
MK3
3.10.0.4481
SD

Add non-planar printing option so curved top surfaces have better print quality. Initially, could do it just based on user direction with a warning since I know the code doesn't know if a particular printer will crash the surface or not depending on the shape - could leave that up to the user and make it a beta feature.

**Comment by 3d-gussner** [comment]
@Spinnetti This is PrusaSlicer related and not Firmware, please close this issue here and open it in https://github.com/prusa3d/PrusaSlicer/issues
