### ISSUE TITLE
"Sacrificial slab - floating support"

### ISSUE THREAD

**Issue by Spinnetti** [prusa3d/Prusa-Firmware#3240]
This:

https://www.youtube.com/watch?v=omZo31BTU30&ab_channel=XYZeeMaker

Great idea, uses less material, gets same result as full supports.

**Comment by 3d-gussner** [comment]
@Spinnetti This is PrusaSlicer related and not Firmware, please close this issue here and open it in https://github.com/prusa3d/PrusaSlicer/issues

**Comment by Spinnetti** [comment]
got it. thanks.
