### ISSUE TITLE
HOTEND not preheating after power OFF recovery

### ISSUE THREAD

**Issue by FrantisekPitak** [prusa3d/Prusa-Firmware#3241]
the problem occurs on  MK3 printers (so far I have these ones only), the latest version of sw.

 How to reproduce the problem:
    1. Bring printing to a stage (by Gcode): change filament.
    2.  Let the printer be until it changes to "hotend down due to safety timmer" 
    3.  Simulate the electricity blackout
    4. confirm to recover the printing 
    
  After those steps, only the bed is preheated .. the hotend stays at room temperature.

**Comment by DRracer** [comment]
I'm afraid this is a know limitation of the PowerPanic function ... and has been for a long time.
