### ISSUE TITLE
[QUESTION] Is the Einsy-Rambo 1.1b motherboard open source?

### ISSUE THREAD

**Issue by easonjim** [prusa3d/Prusa-Firmware#3258]
Dear all,
    Is the Einsy-Rambo 1.1b motherboard open source?

**Comment by 3d-gussner** [comment]
If I am not wrong it is, but look here:
https://reprap.org/wiki/EinsyRambo
https://github.com/ultimachine/Einsy-Rambo
https://github.com/ultimachine/Einsy-Rambo/blob/1.1a/board/Project%20Outputs/Schematic%20Prints_Einsy%20Rambo_1.1a.PDF

As this is the Prusa-Firmware repository and this is a hardware question, please close this issue.

**Comment by easonjim** [comment]
Dear  3d-gussner,
      thanks
