### ISSUE TITLE
[BUG] Inserting/Removing the SD card while sorting can crash/get-stuck

### ISSUE THREAD

**Issue by wavexx** [prusa3d/Prusa-Firmware#3264]
**Printer type** - MK3+
**Printer firmware version**-  3.10.1-RC1
**MMU Upgrade** - n/a

**SD card or USB/Octoprint**
SD

**Describe the bug**
The "Sorting files" progress bar can get stuck if you remove and re-insert the SD card
  
**To Reproduce**
- Remove SD card
- Reset printer
- Insert SD card
- Remove SD card while "Sorting files"
- Quickly re-insert the SD card

At this point, sorting might either 1) get stuck forever 2) continue happily but then show "card removed" 3) stop sorting, and restart correctly 4) get stuck and crash 5) continue and show a broken SD menu (and crash shortly afterwards)

All options available :)
  
**Expected behavior**
The FW shouldn't get stuck.

I think the issue in this case is that the menu_lcd_lcdupdate_func() re-triggers the sorting code while the old didn't finish yet.

**Video**

https://user-images.githubusercontent.com/1017726/129461243-61a74088-2c3e-42ff-b3c3-a08eb8b1bda3.mp4

**Comment by gudnimg** [comment]
@wavexx wasn't this issue fixed in 3.10.1? Can this issue be closed?

**Comment by wavexx** [comment]
I know we had some fixes, but I didn't retest
