### ISSUE TITLE
MMU2S comprehensible messages

### ISSUE THREAD

**Issue by fabiencomte** [prusa3d/Prusa-Firmware#3272]
Hello,
MMU2S is not always perfect :-) so it should be really usefull to add informations about what MMU2S is doing on MK3S display.

Exemple:
"Unloading filament 1" => 
"Unloading filament 1\r\nFilament in extruder = 1 / MMU = 1\r\nExtruder motor backward\r\nMMU motor backward"
"Unloading filament 1\r\nFilament in extruder = 0 / MMU = 1\r\nExtruder motor stopped\r\nMMU motor backward"
"Unloading filament 1\r\nFilament in extruder = 0 / MMU = 0\r\nExtruder motor stopped\r\nMMU motor stopped"

If need some space:
backward = -1
stopped = 0
forward = 1

**Comment by gudnimg** [comment]
Closing as this is now resolved with FW 3.13.0 and MMU FW 3.0.0 :)
