### ISSUE TITLE
[QUESTION] Compilation problem on Arduino IDE on Windows

### ISSUE THREAD

**Issue by abe-dk** [prusa3d/Prusa-Firmware#3273]
When compiling the firmware for MK3 using Arduino IDE on Windows I get the following error:

```
wiring.c.o (symbol from plugin): In function `__vector_23':

(.text+0x0): multiple definition of `__vector_23'

sketch\heatbed_pwm.cpp.o (symbol from plugin):(.text+0x0): first defined here

c:/users/ander/appdata/local/arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld.exe: Disabling relaxation: it will not work with multiple definitions

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board RAMBo.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

````
I found the exact same question in the issue https://github.com/prusa3d/Prusa-Firmware/issues/1994 but it is from 2019 and I'm not able to follow the instructions. Please give me an up to date reply. Perhaps you could also tell what exactly is the problem with Windows and this.

**Comment by leptun** [comment]
I think you might be using the incorrect board definition. The prusa specific board definition for the Einsy needs to be uses, not the generic rambo.
Make sure you follow the instructions here carefully: https://github.com/prusa3d/Prusa-Firmware#using-arduino
