### ISSUE TITLE
[BUG] Filament runout issue

### ISSUE THREAD

**Issue by jlshelby** [prusa3d/Prusa-Firmware#3276]
**Printer type** - [e.g. MK3S, MK3, MK2.5S, MK2.5, MK2S, MK2]
**Printer firmware version**-  [e.g. 3.8.1, 3.8.1-RC1, ...]
MK3S

**MMU Upgrade** - [e.g. MMU2S, MMU2, MMU1]
**MMU upgrade firmware version [e.g. 1.0.6, 1.0.6-RC2, ...]
MMU2S

**SD card or USB/Octoprint**
  Please let us know if you print via SD card or USB/Octoprint
SD card

**Describe the bug**

Filament 2 ran out of filament and stopped. I loaded the next spool and it started to resume printing however the MMU stopped feeding filament and created a split between the two. Then the filament piece from the MMU to the heat element continued to feed the last bit from the first spool until it ran out but instead of detecting it had no more filament it just continued to print with no filament resulting in several layers not being applied and ruined the long print.
  
**To Reproduce**
  Please describe steps to reproduce the behavior.
  
Not sure how to recreate other than having a spool run out and reproducing but the firmware is:
MKS3 3.10.0
MMU2S 1.0.6

**Expected behavior**
  
**G-code**
  Please attach a G-code. This will make it easier for us to replicate the error.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by jlshelby** [comment]
With the firmware in the ticket the filament will run out and continue printing without any detection that there is no filament. I have gone back to 3.7.2 (1.0.5) to resolve the issue.

**Comment by gudnimg** [comment]
Adding to 3.13 milestone as a reminder to close this ticket. This issue should be already fixed in 3.13.

**Comment by gudnimg** [comment]
Closing as this is now resolved with FW 3.13.0 and MMU FW 3.0.0 :)
