### ISSUE TITLE
[FEATURE REQUEST] Retract after filament Autoload

### ISSUE THREAD

**Issue by rastagandalf** [prusa3d/Prusa-Firmware#3279]
When loading filament before a print, the filament oozes from the nozzle quite a bit until the print is actually started by the user.
I always do a manual retract of say 3...5 mm (by releasing the extruder spring and pulling back slightly). 
Not doing this results in the oozed out filament being trapped in the first layer sometimes. 
A solution would be a short retract after loading filament and accepting that it is extruding in the right colour.

**Comment by Prusa-Support** [comment]
Thanks for sharing your idea.

Cleaning up the nozzle after loading filament would still be necessary. The pressure of plastic in the nozzle will be dialed while purging plastic in the intro line, at the beginning of a print.
You may want to wait for a little after the filament loading to let the filament ooze a bit longer before cleaning up. This should be enough or, alernatively, you can retract a bit of filament right away - as you do.
At the end of a print, the default wipe movement and a retraction should reduce the oozing of the pre-loaded print, but cleaning the nozzle between prints is still advisable.

The feature request sounds legit though and can be inspiration for further firmware improvements.

Michele Moramarco
Prusa Research
