### ISSUE TITLE
[BUG] TMC2130_SERVICE_CODES_M910_M918 breaks compiling

### ISSUE THREAD

**Issue by KrX3D** [prusa3d/Prusa-Firmware#3284]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK3S
**Printer firmware version**- Prusa-Firmware-3.10.1-RC1 but also didnt work with the official 3.10 Version

**Describe the bug**
When i uncomment "#define TMC2130_SERVICE_CODES_M910_M918" in Configuration_prusa.h i get this error
  
![image](https://user-images.githubusercontent.com/18599852/136071667-e0acdc59-5ff2-4963-9eee-fa8c6a3513f4.png)

when its commented out, everything works. 
in FW version 3.9.3 everything worked when uncommenting this

**Comment by gudnimg** [comment]
This should work: replace any `tmc2130_init()`, the function now requires a parameter input ![image](https://user-images.githubusercontent.com/8218499/136110819-ec2c62a0-ae58-4863-93bf-21cd39c6d252.png)

**Comment by gudnimg** [comment]
Fix was merged into 3.10.1 branch: https://github.com/prusa3d/Prusa-Firmware/pull/3304

**Comment by gudnimg** [comment]
As this was fixed in 3.10.1, 2 years ago I'm closing this issue.
