### ISSUE TITLE
[QUESTION] 3.10.1 Release Date?

### ISSUE THREAD

**Issue by Danafra** [prusa3d/Prusa-Firmware#3287]
Sorry for such an elementary question, but has there been any discussion as to when this will be released?

For that matter, is there a way one can check to determine progress to release here?

**Comment by gudnimg** [comment]
I am curious as well. Release Candidate 1 has been out for roughly 3 months now. 🤔

**Comment by jiri-jirus** [comment]
RC1 is not able to connect via OctoPrint on my printers. Did anyone suceed with this?

**Comment by marcolivierroy** [comment]
> 

It works with mine. Make sure you put the right config for the port you are using. (USB Std B or Header Socket)

**Comment by jiri-jirus** [comment]
> > 
> 
> It works with mine. Make sure you put the right config for the port you are using. (USB Std B or Header Socket)

well this seems to be related to new SN reading code

**Comment by 3d-gussner** [comment]
@Danafra It has been released :partying_face:  please close the question.
