### ISSUE TITLE
MMU2 PTFE Tube Length

### ISSUE THREAD

**Issue by seanfrisbey** [prusa3d/Prusa-Firmware#3289]
My understanding is that the PTFE tube length between the MMU2 and the extruder is hard coded somewhere. It would be really nice to be able to configure that somewhere so that I could detach the MMU2 from the printer frame. I would like it to be OUTSIDE the Lack enclosure. It's quite the pain in the butt to hunch over the enclosure any time I need to fix a load/unload problem.

**Comment by Forfelet** [comment]
Hello @seanfrisbey,

With MMU2 (not S), the distance between MMU and extruder is a default value but it can be easily modified.
Please read this topic to modify this length
[https://help.prusa3d.com/en/guide/service-menu-individual-filament-calibration_86376/](https://help.prusa3d.com/en/guide/service-menu-individual-filament-calibration_86376/)

**Comment by seanfrisbey** [comment]
Thanks, but I should have specified that I have the MMU2S >_<

**Comment by Forfelet** [comment]
For MMU2S, this procedure is not required. Length is defined by FINDA and IR sensor.
It's automatic, you can put one or two meters of PTFE tube. It's not a problem.
But, fast speed is locked for a specific length. This length is hard-coded.
After that, a slow speed is used to reach the extruder.

**Comment by seanfrisbey** [comment]
Yeah, I thought that would be the case. I was hoping to be able to adjust the "fast speed" length. It definitely creeps when it gets to the slow part. I'm just saying that I think it would be nice to be able to configure that somewhere.

**Comment by Forfelet** [comment]
Yes, I understand

**Comment by vintagepc** [comment]
The fast speed configure should still work for the S variant, even if it isn't mentioned anymore, IIRC
