### ISSUE TITLE
[FEATURE REQUEST] Make MK3(S) gcodes including M860 command compatible with MK3S+

### ISSUE THREAD

**Issue by rongith** [prusa3d/Prusa-Firmware#3290]
**Printer type**
MK3, MK3S, MK3S+

**Is your feature request related to a problem? Please describe.**
I have M860 S35 in my old MK3 and MK3S gcodes.
After upgrading to MK3S+, the gcodes don't work anymore as there is no temperature reported by the SuperPINDA. Pinda temp is 0.
As Temp is 0, the printer is stucked with the command M860 S35, waiting for the PINDA temp being 35°C.
  
**Describe the solution you'd like**
 Find a way to discard the M860 S35 if there is no temperature reported by the PINDA.

**Comment by gudnimg** [comment]
The firmware at the moment cannot tell the difference between MK3S and MK3S+ as I understand it. So I think a solution for this would be to add a new configuration file for MK3S+ and leave out the `PINDA_THERMISTOR` config... that way the printer will not respond to the M860 command as it is not a part of the firmware.

Kinda of a bug in my opinion but I think the `#define PINDA_THERMISTOR` should be kept in the configuration file as the settings obviously doesn't fit MK3S+.
![image](https://user-images.githubusercontent.com/8218499/137031914-5f377675-ce2a-4b47-8cb9-12fc0e345732.png)


Configuration files (none specifically for MK3S+):
![image](https://user-images.githubusercontent.com/8218499/137031662-4ac74fe4-c393-4112-8ffc-c5ec6d224e9a.png)
