### ISSUE TITLE
[FEATURE REQUEST] Pre-heat button becomes "cool down"  after toggle

### ISSUE THREAD

**Issue by Bigsciguy** [prusa3d/Prusa-Firmware#3293]
The pre-heat button on the mini+ menu is very convenient. Sometimes (especially when switching filament or doing repairs/maintenance) it's quite annoying to have to go through settings: temperature: cooldown to get everything back to room temp. Would be quite a nice addition for the Pre-heat button on the menu to switch to Cooldown after you have started pre-heating, and vice-versa.

**Comment by 3d-gussner** [comment]
@Bigsciguy Is it a request for the MK2.5/S,MK3/S/+ or for the Mini/+?
I don't understand your request as if you go to the `Preheat` menu on MK2.5/S,MK3/S/+ the last option is `Cooldown`.
