### ISSUE TITLE
[FEATURE REQUEST] Spool Join off warning for Multicolor prints

### ISSUE THREAD

**Issue by NightSkySK** [prusa3d/Prusa-Firmware#3296]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** - MK3S
**MMU Upgrade** - MMU2S

**Is your feature request related to a problem? Please describe.**
Usually, I print on my MK3S + MMU2S in single mode with spool join function "On".
Last few hours I was looking for a reason why my multicolour print gcode doesn't initiate filament change. I've tried the same gcode through Octoprint and via SD card, always with the same result. It seems that the issue was caused, because I've made "Spool join" function "On", once I turn it off before the next try, suddenly the filament change worked correctly.
  
**Describe the solution you'd like**
I would see to a possible solution to this issue:
1. More full proof and more user friendly. Firmware to deactivate Spool Join function once the Multicolour Gcode is detected.
or
2. Display warning on the screen that for multicolour prints function Spool Join need to be deactivated (however it will not work so well in case of sending code via Octoprint.

**Comment by ulab** [comment]
Spool Join makes sense for multicolor too? While I have never been in this situation...

If I have only little filament left in slot 1, I can add more of the same color to slot 2 and still print with different colors in slot 1(2) and 3, 4, 5...

Did you [configure your Octoprint](https://help.prusa3d.com/en/article/octoprint-configuration-and-install_2182) correctly? 

> If you are using Octoprint with the Original Prusa MMU2S you will also have to set "Number of extruders" to 5, and tick the checkbox for "Shared nozzle".

**Comment by NightSkySK** [comment]
Yes, I have Octoprint correctly configured. Once I turn off spool join function on both sd prints and octoprint  one filament changes went without any problems. With spool join function on it wasn't working for me.
