### ISSUE TITLE
MK3 firmware not communicating via UART

### ISSUE THREAD

**Issue by KissmanCZ** [prusa3d/Prusa-Firmware#330]
I have connected Rpi zero with EINSY via UART. Octoprint can connect but there is timeout from printer.

`Connecting to: /dev/ttyAMA0Changing monitoring state from 'Offline' to 'Opening serial port'Connected to: Serial<id=0xacba7790, open=True>(port='/dev/ttyAMA0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitorChanging monitoring state from 'Opening serial port' to 'Connecting'Send: N0 M110 N0*125There was a timeout while trying to connect to the printerChanging monitoring state from 'Connecting' to 'Offline'Connection closed, closing down monitor`

Same for Repetier Server.

**Comment by Allram** [comment]
Tried with baudrate 125200?

**Comment by KissmanCZ** [comment]
Yup... same :(

`Connecting to: /dev/ttyAMA0Changing monitoring state from 'Offline' to 'Opening serial port'Connected to: Serial<id=0xad0bc4d0, open=True>(port='/dev/ttyAMA0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitorChanging monitoring state from 'Opening serial port' to 'Connecting'Send: N0 M110 N0*125There was a timeout while trying to connect to the printerChanging monitoring state from 'Connecting' to 'Offline'Connection closed, closing down monitor`

**Comment by KissmanCZ** [comment]
Same

`Connecting to: /dev/ttyAMA0Changing monitoring state from 'Offline' to 'Opening serial port'Connected to: Serial<id=0xad06e450, open=True>(port='/dev/ttyAMA0', baudrate=125200, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitorChanging monitoring state from 'Opening serial port' to 'Connecting'Send: N0 M110 N0*125There was a timeout while trying to connect to the printerChanging monitoring state from 'Connecting' to 'Offline'Connection closed, closing down monitor`

**Comment by KissmanCZ** [comment]
Just tried disable internal bluetooth from ttyAMA0 and disabled console on UART... but same :(

`Connecting to: /dev/ttyAMA0Changing monitoring state from 'Offline' to 'Opening serial port'Connected to: Serial<id=0xac95c730, open=True>(port='/dev/ttyAMA0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitorStarting baud rate detectionChanging monitoring state from 'Opening serial port' to 'Detecting baudrate'Trying baudrate: 250000Send: N0 M110 N0*125Baudrate test retry: 4Send: N0 M110 N0*125Baudrate test retry: 3Send: N0 M110 N0*125Baudrate test retry: 2Send: N0 M110 N0*125Baudrate test retry: 1Send: N0 M110 N0*125Baudrate test retry: 0Send: N0 M110 N0*125Trying baudrate: 125200Send: N0 M110 N0*125Baudrate test retry: 4Send: N0 M110 N0*125Baudrate test retry: 3Send: N0 M110 N0*125Baudrate test retry: 2Send: N0 M110 N0*125Baudrate test retry: 1Send: N0 M110 N0*125Baudrate test retry: 0Send: N0 M110 N0*125Trying baudrate: 115200Send: N0 M110 N0*125Baudrate test retry: 4Send: N0 M110 N0*125Baudrate test retry: 3Send: N0 M110 N0*125Baudrate test retry: 2Send: N0 M110 N0*125Baudrate test retry: 1Send: N0 M110 N0*125Baudrate test retry: 0Send: N0 M110 N0*125Trying baudrate: 230400Send: N0 M110 N0*125Baudrate test retry: 4Send: N0 M110 N0*125Baudrate test retry: 3Send: N0 M110 N0*125Baudrate test retry: 2Send: N0 M110 N0*125Baudrate test retry: 1Send: N0 M110 N0*125Baudrate test retry: 0Send: N0 M110 N0*125Trying baudrate: 57600Send: N0 M110 N0*125Baudrate test retry: 4Send: N0 M110 N0*125Baudrate test retry: 3Send: N0 M110 N0*125Baudrate test retry: 2Send: N0 M110 N0*125Baudrate test retry: 1Send: N0 M110 N0*125Baudrate test retry: 0Send: N0 M110 N0*125Trying baudrate: 38400Send: N0 M110 N0*125Baudrate test retry: 4Send: N0 M110 N0*125Baudrate test retry: 3Send: N0 M110 N0*125Baudrate test retry: 2Send: N0 M110 N0*125Baudrate test retry: 1Send: N0 M110 N0*125Baudrate test retry: 0Send: N0 M110 N0*125Trying baudrate: 19200Send: N0 M110 N0*125Baudrate test retry: 4Send: N0 M110 N0*125Baudrate test retry: 3Send: N0 M110 N0*125Baudrate test retry: 2Send: N0 M110 N0*125Baudrate test retry: 1Send: N0 M110 N0*125Baudrate test retry: 0Send: N0 M110 N0*125Trying baudrate: 9600Send: N0 M110 N0*125Baudrate test retry: 4Send: N0 M110 N0*125Baudrate test retry: 3Send: N0 M110 N0*125Baudrate test retry: 2Send: N0 M110 N0*125Baudrate test retry: 1Send: N0 M110 N0*125Baudrate test retry: 0Send: N0 M110 N0*125Changing monitoring state from 'Detecting baudrate' to 'Offline'Changing monitoring state from 'Offline' to 'Error: No more baudrates to test, and no suitable baudrate found.'Connection closed, closing down monitor`

**Comment by Allram** [comment]
And you are sure you are using the correct pins? I think they got changed from what they originally was.

**Comment by KissmanCZ** [comment]
Yes, I am sure... I cannot use wrong pins, because printed frame has predefined holes for them.

![25074889_10214522795961251_1917672334208437951_o](https://user-images.githubusercontent.com/13331823/34071110-90cf2a9c-e271-11e7-9768-411f8d89c14e.jpg)

**Comment by KissmanCZ** [comment]
https://github.com/foosel/OctoPrint/issues/2293 :( Prusa team, pls release this feature ASAP. Thanks!

**Comment by PavelSindler** [comment]
Hello @KissmanCZ , which fw version do you have?
It should work in RC2 version which can be downloaded from our website https://www.prusa3d.com/drivers/

**Comment by PavelSindler** [comment]
In RC2 firmware version, you must enable using second USART in settings menu.

**Comment by PavelSindler** [comment]
We are currently also working on some basic guideline how to setup it. It will be posted here soon.

**Comment by tibor-vavra** [comment]
## OctoPi on Raspberry Pi Zero W with Original Prusa MK3 HowTo
------

- Download OctoPi img
  https://octopi.octoprint.org/latest

- Unzip it

- Download Etcher tool
  https://etcher.io/

- Write it on micro sd card for RpiZeroW by Etcher

- Edit config file on written sd card filesystem **octopi-network.txt, uncomment and edit section what you want to use**

![image](https://user-images.githubusercontent.com/4319021/34161930-65ac6704-e4d2-11e7-8d4b-80b353c50e54.png)

  This example will add **OctoPi** to wi-fi network **"testik"** with password **"12345678"**

  ​

- Put it in your printer, turn on and set in menu **Settings -> 2nd USART [on]**

- Find **ip adress** of this **OctoPi** in network

- Connect on it by ssh (default user is **'pi'** and password is **'raspberry'**)

- Run: **sudo raspi-config**

- In menu **Interfacing Options -> Serial** -> on question **'Would you like a login shell to be accessible over serial?'** answer **No** and on question **'Would you like the serial port hardware to be enabled?'** answer **Yes**.

![interfacing](https://user-images.githubusercontent.com/4319021/34161971-807f5cee-e4d2-11e7-86b1-a851f7c23f7c.png)

![serial_menu](https://user-images.githubusercontent.com/4319021/34161988-8d26c450-e4d2-11e7-9ef5-3e5d1100800c.png)

![login_shell](https://user-images.githubusercontent.com/4319021/34161996-9299b956-e4d2-11e7-856b-9a458c050e30.png)

![serial_enable](https://user-images.githubusercontent.com/4319021/34162006-9670e63a-e4d2-11e7-806e-54406bddd390.png)

![overlook](https://user-images.githubusercontent.com/4319021/34162016-9cf23f5e-e4d2-11e7-9205-ebf06f4775ee.png)


  Press **Finish** button and **reboot it**

  ​
- Go to **ip address** of **OctoPi** in your web browser to **settings option(wrench icon on right top)** and add new serial port **/dev/ttyS0** and baud rate to **115200**. 

![octoprint_main](https://user-images.githubusercontent.com/4319021/34162031-a7aa26d2-e4d2-11e7-94f8-05878b94999f.png)

![octoprint_options](https://user-images.githubusercontent.com/4319021/34162037-ae477850-e4d2-11e7-8d03-49abbf0f8919.png)


- After **reset** you will be able to make connection to the printer 
![octoprint_connection](https://user-images.githubusercontent.com/4319021/34162041-b45b958c-e4d2-11e7-96bd-b148c178c47e.png)

**Comment by Pretender1988smg** [comment]
HI i tried exacly the same and i still get a timout.... Did some one got it to work?

**Comment by AustinSaintAubin** [comment]
https://help.prusa3d.com/l/en/article/Loz15FAgEk-octo-print-raspberry-pi-zero-w

**Comment by adamit79** [comment]
thank you, it worked
