### ISSUE TITLE
[BUG]Build fails if `TEMP_STAT_LEDS` is enabled

### ISSUE THREAD

**Issue by gudnimg** [prusa3d/Prusa-Firmware#3314]
**Describe the bug**
If `TEMP_STAT_LEDS` preprocessor definition is enabled in `Configuration.h` the build will fail. This is because the two preprocessor symbols `STAT_LED_RED` and `STAT_LED_BLUE` are not defined anywhere in the project. I suspect this is some leftover code from Marlin? We can potentially remove this code alltogether to reduce code *noise*.

![image](https://user-images.githubusercontent.com/8218499/145648165-69635386-fa1c-4072-ae4b-5c91646897b4.png)

  
**To Reproduce**
Enable `TEMP_STAT_LEDS` preprocessor definition.
  
**Expected behavior**
Build succeeds without any warnings or errors.

**Comment by JohnnyDeer** [comment]
Hi @gudnimg, thank you for reporting. We are aware of this bug, unfortunately at this moment have low priority. We will fix it in one of the future releases. Thank you for understanding and patience.

**Comment by gudnimg** [comment]
@JohnnyDeer I created a pull request https://github.com/prusa3d/Prusa-Firmware/pull/3327 that will resolve this issue.
