### ISSUE TITLE
[BUG]Custom Pause Print Message is overwritten

### ISSUE THREAD

**Issue by RodKimmell** [prusa3d/Prusa-Firmware#3316]
**Printer: MK3S**
**Firmware: 3.10**

**MMU: None**

**Print via SD Card**

**Describe the bug**
The PrusaSlicer's Custom Pause Message is quickly overwritten with 'Printer Paused' rendering the custom message ineffective.  The beeper does not sound according to the Sound Setting rules as does a Color Change.
  
  **To Reproduce**
* In PrusaSlicer, create a box shape.  
* In the Preview Mode, add a 'Pause Print' and custom message at any layer.  
* Monitor the LCD display as the paused layer begins to print.

**Expected Behavior**
* Printer pauses and persistently displays the Custom Message.
* Beeper sounds according to Sound Setting rules.

**G-code**
The relevant G-Code begins at Line 404 in the attached file.  Search for "MAGNETS".

**Video**
Attached iPhone video demonstates the bug
[Pause_Test.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/7714837/Pause_Test.gcode.zip)

https://user-images.githubusercontent.com/45301979/146081423-7d7d8b7a-3ac9-4537-aaf3-00242f626cf1.MOV

.

**Comment by gudnimg** [comment]
I am able to reproduce this issue with PrusaSlicer 2.4.0 and MK3S+ FW 3.10.1
Gcode test file: It stops after the first layer [test_file.zip](https://github.com/prusa3d/Prusa-Firmware/files/7762536/test_file.zip)

<img width="960" alt="image" src="https://user-images.githubusercontent.com/8218499/147091431-d45c79da-64db-462c-93b6-fa8055e0c336.png">

**Comment by FrHePo** [comment]
Has this bug enough priority to get solved in the next regular (or beta) version? Generally it would be really good to have more transparency concerning planned bug addressing!

**Comment by gudnimg** [comment]
I have a solution for this issue (M601) 😄 Where if you call M117 with a message then call M601 to pause the print, the custom message will stay on the screen. Seems to only cost about 10 bytes of flash. I will create a PR soon, just need to test this more. This probably doesn't have the highest priority, but I can't speak on behalf of the firmware team at Prusa :)
