### ISSUE TITLE
[bug] Sdbasefile.cpp please help

### ISSUE THREAD

**Issue by eddog833** [prusa3d/Prusa-Firmware#3325]
Arduino: 1.8.15 (Windows 10), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

SdBaseFile.cpp:297:25: error: variable or field 'getpos' declared void

 void SdBaseFile::getpos(filepos_t* pos) {

                         ^~~~~~~~~

SdBaseFile.cpp:297:25: error: 'filepos_t' was not declared in this scope

A:\PI3A Pro\Marlin\SdBaseFile.cpp:297:25: note: suggested alternative: 'fpos_t'

 void SdBaseFile::getpos(filepos_t* pos) {

                         ^~~~~~~~~

                         fpos_t

SdBaseFile.cpp:297:36: error: 'pos' was not declared in this scope

 void SdBaseFile::getpos(filepos_t* pos) {

                                    ^~~

A:\PI3A Pro\Marlin\SdBaseFile.cpp:297:36: note: suggested alternative: 'pow'

 void SdBaseFile::getpos(filepos_t* pos) {

                                    ^~~

                                    pow

A:\PI3A Pro\Marlin\SdBaseFile.cpp: In member function 'int SdBaseFile::peek()':

SdBaseFile.cpp:931:3: error: 'filepos_t' was not declared in this scope

   filepos_t pos;

   ^~~~~~~~~

A:\PI3A Pro\Marlin\SdBaseFile.cpp:931:3: note: suggested alternative: 'fpos_t'

   filepos_t pos;

   ^~~~~~~~~

   fpos_t

SdBaseFile.cpp:932:11: error: 'pos' was not declared in this scope

   getpos(&pos);

           ^~~

A:\PI3A Pro\Marlin\SdBaseFile.cpp:932:11: note: suggested alternative: 'pow'

   getpos(&pos);

           ^~~

           pow

A:\PI3A Pro\Marlin\SdBaseFile.cpp: At global scope:

SdBaseFile.cpp:1498:25: error: variable or field 'setpos' declared void

 void SdBaseFile::setpos(filepos_t* pos) {

                         ^~~~~~~~~

SdBaseFile.cpp:1498:25: error: 'filepos_t' was not declared in this scope

A:\PI3A Pro\Marlin\SdBaseFile.cpp:1498:25: note: suggested alternative: 'fpos_t'

 void SdBaseFile::setpos(filepos_t* pos) {

                         ^~~~~~~~~

                         fpos_t

SdBaseFile.cpp:1498:36: error: 'pos' was not declared in this scope

 void SdBaseFile::setpos(filepos_t* pos) {

                                    ^~~

A:\PI3A Pro\Marlin\SdBaseFile.cpp:1498:36: note: suggested alternative: 'pow'

 void SdBaseFile::setpos(filepos_t* pos) {

                                    ^~~

                                    pow

exit status 1

variable or field 'getpos' declared void

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by 3d-gussner** [comment]
@eddog833 Prusa Firmware build environment depends on  ArdunioIDE `1.8.5` and Board `Original Prusa i3 MK3/MK3S Einsy RAMBo`

See https://github.com/prusa3d/Prusa-Firmware#windows

The `PF-build.sh` script will download and create the needed build environment and guides you through the build process.

On Windows you have several options:
- GitBash
- WSL
- Virtual machine with Ubuntu 20.04 LTS

Hope that helps.

**Comment by gudnimg** [comment]
I think this issue can be closed

**Comment by gudnimg** [comment]
Closing this Github issue because it is stale
