### ISSUE TITLE
type in is_whitespace_or_nl?

### ISSUE THREAD

**Issue by abegines** [prusa3d/Prusa-Firmware#334]
did you mean ...?
`    return c == ' ' || c == '\t' || c == '\n' || c == '\r';`

when you say...
`    return c == ' ' || c == '\t' || c == '\n' || c == 'r';`

**Comment by thess** [comment]
Ah - you are correct. However, this function is never called so there is no apparent error. The firmware contains much detritus like this. Sigh...
