### ISSUE TITLE
[FEATURE REQUEST] MMU2S disable/bypass option through FIRMWARE

### ISSUE THREAD

**Issue by vladturdean** [prusa3d/Prusa-Firmware#3363]
Since I can't print as fast with the MMU2s, I would really like a option where you can disable/enable the MMU2s without removing the wiring whilst printing directly, as usual.

**Comment by krepsy3** [comment]
Seconded. I need this very much. When printing with large diameter nozzles, the filament tip is getting stuck CONSTANTLY in the extruder area. Its so tiring to be constantly removing the door and manually removing bits of wasted filament... For single mode prints, I see this as an absolute NECESSITY!

**Comment by leptun** [comment]
This feature is coming to fw 3.12 along with the new mmu2 firmware. See https://github.com/prusa3d/Prusa-Firmware/issues/1876#issuecomment-1045965924

**Comment by gudnimg** [comment]
Closing as this is now resolved with FW 3.13.0 and MMU FW 3.0.0 :)
