### ISSUE TITLE
[BUG] print speed does not return to 100% between prints

### ISSUE THREAD

**Issue by evils** [prusa3d/Prusa-Firmware#3374]
probably a side effect of fixing #1208 (which appears to be specific to material changes)

**Printer type** - MK3S+
**Printer firmware version** -  3.10.1

**SD card or USB/Octoprint**
  it definitely occurs with Octoprint, presumably also from SD card

**Describe the bug**
  overriding the print speed (rotating the knob on the info screen) persists between prints
  this means that when adjusting the print speed of a previous print,
  the first layer of the next print will print too fast

  i've had at least one instance where i compensated for a slow speed by cranking up the speed several hundred percent, and ended up with the first layer on my next print going way too fast
  
**To Reproduce**
  1. while printing something, adjust the print speed
  2. print something else (or the same thing)
  3. see the print speed still set to the previous adjusted speed
  
**Expected behavior**
  print speed to persist between material changes (don't break #1208)
  and print speed to reset to 100% at the start of a print

**Notes**
  resetting the speed between prints may bite someone when they were expecting the machine to stay slow
  but that's a situation where i think i'd be more likely to go fix the speed in the slicer
  some people may rely on the speed setting to persist, but it seems best for them not to, and instead fix it in the slicer

  i would expect the gcode to force the printer's speed to 100% at the start, so maybe this is a slicer issue, i believe i've had this issue with prusa slicer and super slicer

**Comment by ochm** [comment]
Just edit your start or end gcode to set the 100% speed. This is not a bug, IMHO.

**Comment by evils** [comment]
I think editing gcode should be a last resort, not the "correct" way of getting a sensible behaviour
rather, a way to get past sensible behaviour for advanced users.
Moreover, it does not make this sensible behaviour the default for the printer.

Persisting the speed between prints means there's a context the user must keep track of,
in order to have a reasonable expectation of what speed the next print will print at.
This to me seems ok for advanced users who messed with the gcode
(they did something to expect unusual behaviour)
but not for novice users, or even multiple advanced users that may not communicate the context to each other.
(i think this isn't a well known issue because i suspect it resets between power cycles)

For me, subsequent prints are usually not related and even if they are,
speeding up the print at the end, does not mean i want a faster first layer when i print the same again.

I think the "right way" to persist a speed setting is by configuring the print to behave that way in the slicer
and the firmware should take that speed setting from the gcode unless told otherwise **for the current print**.

**Comment by evils** [comment]
> Just edit your start or end gcode to set the 100% speed. This is not a bug, IMHO.

thanks, i'm adding [`M220 S100`](https://marlinfw.org/docs/gcode/M220.html) to the start and end G-code in my slicer settings
but i consider this a workaround to a firmware bug
