### ISSUE TITLE
[BUG] Can set temperature to 999 degrees Celsius

### ISSUE THREAD

**Issue by galagithub** [prusa3d/Prusa-Firmware#3396]
Firmware: 3.10.1 (see MK3_3.10.1 branch)

Gcode commands override any temperature limits!

M140, M190, M104, M109 affected!
Each of these commands can set ANY temperature, just try to set it to 999 degrees and it works.

In case of bed, thermal runaway occurs on my printer, but it goes over 130 degrees before it is triggered.
In case of the hotend I've stopped the test at 350 degrees because I have a aluminum block, the temperature could rise more if let.

This is fixed in my fork of Prusa-Firmware, see branch MKx_COMPAT_3.11.0 on my github.

**Comment by susajr** [comment]
Hello, 
thank you for the bug report, it is noted and hard temp limits will be implemented.
