### ISSUE TITLE
[Feature Request / Idea] Implement M906 with `tmc2130_val2cur()`

### ISSUE THREAD

**Issue by gudnimg** [prusa3d/Prusa-Firmware#3401]
**Is your feature request related to a problem? Please describe.**

This is not a feature I request specifically, just an idea for using unused code. 

When I was looking at the M907 code I noticed that Prusa firmware does not implement M906. But we may already have code tthat can be used to implement M906. See `tmc2130_val2cur()`. https://github.com/prusa3d/Prusa-Firmware/blob/e1ebc826544c9848c3926cba35a605af91cb16d5/Firmware/tmc2130.cpp#L1130

![image](https://user-images.githubusercontent.com/8218499/153750548-eca40964-d9a9-48ef-9d54-22ad8da58983.png)

I have no plans on implementing this myself, please consider this ticket as a *note*. Anyone in the community is of course welcome to try to implement this 😄

**Comment by leptun** [comment]
We have M907 that does exactly this (without the I argument).
Btw, it's tmc2130_cur2val, not tmc2130_val2cur. The second one is indeed unused.

**Comment by gudnimg** [comment]
@leptun my mistake, I meant M907, M905 isn't available.

**Comment by leptun** [comment]
Well, M907 and M906 can be identrical as far as I am concerned. They do basically the exact same thing with TMC drivers. I'd personally leave these as they are now. We can look at this later if we still have space.
