### ISSUE TITLE
[BUG]Multi-page error messages not cycling when kill() is called

### ISSUE THREAD

**Issue by leptun** [prusa3d/Prusa-Firmware#3402]
Probably the timebase is disabled or the entire firmware is halted after the message is displayed in kill().
https://photos.app.goo.gl/GEPiacbpJ4NUDSM29

**Comment by gudnimg** [comment]
I encountered this issue today. If started a print but then stopped the print while homing was ongoing. Then this message appeared and I couldn't do anything but turn off the printer.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/8218499/155007560-45f96013-c996-4058-9a75-db4a441a952d.png">
