### ISSUE TITLE
[FEATURE REQUEST] New Gcode to set the minimum safe Z height for crash detect rehome.

### ISSUE THREAD

**Issue by ggppjj** [prusa3d/Prusa-Firmware#3419]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** - MK3S+
**MMU Upgrade** - MMU2

**Is your feature request related to a problem? Please describe.**
  I was printing an MMU print with no sparse layers enabled, and had a crash detect on the wipe tower after it was lower than the printed object in the bottom left of the build plate. It entered a crash detect loop after incorrectly rehoming against the print.

**Describe the solution you'd like**
A Gcode that allows the slicer to inform the printer of the minimum safe z-height for rehome would allow the printer to rehome correctly when objects are printed individually.

**Comment by mmalecki** [comment]
I've also ran into this problem. Another approach I've pondered is recording maximum Z-height visited during print, and then moving to that + MMU pause Z-lift, but there doesn't appear to be a clean way to approach that.

Alternative solution that could work, that doesn't involve custom Gcode, would be to implement `G60` and `G61` (save and restore position). After layer change, we'd then `G60 S0` (save position in slot 0), and on MMU error, before moving to MMU pause position, we'd `G61 S0 Z` (move to saved position in slot 0, limited to Z axis).

**Comment by mmalecki** [comment]
I hacked [this together](https://github.com/mmalecki/Prusa-Firmware/tree/g60-g61). Will test it over the coming days - initial test was a failure (print didn't resume after MMU OK), but I think the idea may be sound.
Edited to add: second test was a failure as well, with the same failure mode. I've yet to compare to just `MK3` branch - it could be something there, and not my patch, but I doubt it.

**Comment by Prusa-Support** [comment]
Hello! Thank you @ggppjj for the request and @mmalecki for sharing the possible solution for this. I brought this to our devs attention, so that they can further review and evaluate this. We'll update here in case of more info from our side - of course, any more feedback anyone might have is absolutely welcome and appreciated! 

Alessandro Pantaleo
Prusa Research

**Comment by ggppjj** [comment]
Thank you Alessandro!

It is my hope that this can be evaluated for inclusion on the still-forming 3.13.0 milestone, I am of the opinion that it would be a nice polish to an otherwise excellent feature that would fit nicely into the overall theme of MMU fixes that 3.13.0 appears to target, and also have the added benefit of shoring up the "print objects individually" functionality and could more reliably allow print farm operators to keep automatic crash detection enabled for example (although I admit that the last point is only a hypothetical on my part, not operating or working with anyone operating a print farm myself or knowing their settings preferences).

**Comment by 3d-gussner** [comment]
@gudnimg Please have a look at this feature request and the approach by @mmalecki https://github.com/prusa3d/Prusa-Firmware/issues/3419#issuecomment-1183326609

**Comment by 3d-gussner** [comment]
@ggppjj Thanks for the feature request.
In FW 3.14.0 you will be able to use `M125 Z<lift value>` to change the Z lift height.

**Comment by ggppjj** [comment]
Thank you! 

Glad to be of help, if only to start a conversation.
