### ISSUE TITLE
[BUG] Printer permanently crashes and is not able to finish print

### ISSUE THREAD

**Issue by devproof** [prusa3d/Prusa-Firmware#3447]
**Printer type** - MK3S
**Printer firmware version** -  3.10.1 

**MMU upgrade** - no MMU

**SD card or USB/Octoprint** SD Card

**Describe the bug**
The printer randomly crashes at different points and I was never able to finish the attached print. I tried it four times and even resliced and moved the position of the object. The slicer is PrusaSlicer 2.4.0. This was introduced with 3.10.1 and only happens on this firmware version. After rolling back to 3.10.0, I was able to print this model 6 times in a row without any failure.
  
**To Reproduce**
Print attached gcode with PETG. Sometimes it fails after 6 hours, sometimes after 20. I believe it ends up in a crash and reboots the printer.
  
**Expected behavior**
No crash.
  
**G-code**
[Kassetten_0.2mm_PETG_MK3S_22h13m.zip](https://github.com/prusa3d/Prusa-Firmware/files/8306663/Kassetten_0.2mm_PETG_MK3S_22h13m.zip)

**Comment by wavexx** [comment]
How did it crash? By self-restarting showing a "FIRMWARE CRASH!"?

**Comment by djcb52** [comment]
Hi 
I have this issue. At various stages the print stops feeding filament and the print has to be stopped or stops before finishing. Printed the same file with the same filament on my Flashforge Adventurer 3 perfectly. I even disconnected my MMU2 thinking it was causing the issue. No difference.
Very frustrating. Going back to previous firmware.

**Comment by wavexx** [comment]
These behaviors can be quite different internally, so it would be helpful to be extra-precise if you saw this happening.

A printer crash should self-restart and show a "FIRMWARE CRASH!" message.

If the printer stops feeding filament, does it keep on moving or it completely stops?

**Comment by djcb52** [comment]
Hello

The printer head keeps moving.

I'm going to re burn the printer and MMU firmware.

Any other suggestions welcomed.

Regards
Dale J Brown
Email: ***@***.***
Mobile: 0403 055 485
Postal Address : PO Box 421 Maldon Vic 3463

**Comment by wavexx** [comment]
It helps tremendously if you write down everything you do. After flashing the FW, the printer resets.

From this point, make a note of every single action (push encoder -> enter sd menu -> select file) until the printer starts printing. If you can record a video while starting the print that's also excellent.

The reset is important, as it brings the printer to a known state. If you do something unrelated before, reset the printer before recording.

Keep the original gcode you used to start the print and attach it as well.
When it crashes, also make a video if possible, so that we can try to understand the crash behavior.

We suspect these crashes are due to some other bug which is triggered before the print actually starts, but finding where is not easy. I tried to print the above gcode twice, but it didn't result in a crash. Any extra detail helps.

**Comment by djcb52** [comment]
Thanks for the tip!

I'm on holidays for a few days. When I get back, I'll try what you
suggested.

Regards
Dale J Brown
Email: ***@***.***
Mobile: 0403 055 485
Postal Address : PO Box 421 Maldon Vic 3463

**Comment by ldboehm** [comment]
I just updated my PRUSA MK3S, and am having this same issue.
However, it only seems to happen on very wide prints.  It crashes after a few layers but always in the same spot when the carriage is always to the extreme far right side

**Comment by wavexx** [comment]
@ldboehm the same as above applies. Please attach the gcode of the print, and if you can also take a video of how the printer crashes. If there's a "FIRMWARE CRASH!" message we can also get the internal crash log from the printer with your help.

**Comment by djcb52** [comment]
Will do.

Regards
Dale J Brown
Email: ***@***.***
Mobile: 0403 055 485
Postal Address : PO Box 421 Maldon Vic 3463

**Comment by ldboehm** [comment]
> 

I just got it to happen again.
Print stops
Error on the printer is: "ERR: PRINT FAN ERROR"
This print is a PETG print with no cooling turned on for the extruder. the cooling fan for the carriage was on and spinning.

**Comment by wavexx** [comment]
@ldboehm that's completely different from what I was expecting. Can you attach the gcode of the print that shows this?

**Comment by ldboehm** [comment]
And it happens at the same spot.
I'm trying it now again with filament cooling turned on.
This is basically a rectangular shape, so it passes this position many times as it raises up.
[Archive.zip](https://github.com/prusa3d/Prusa-Firmware/files/8366190/Archive.zip)

No obstruction on the fans.
stops about 25% of the way in each time.
Running PRUSA Slicer 2.4 through Octoprint to an MK3S
I've been using this setup for years and never a problem like this.

**Comment by ldboehm** [comment]
> @ldboehm that's completely different from what I was expecting. Can you attach the gcode of the print that shows this?forget my post for now.  I found the fan problem. A wire disconnected from the front fan on the fan board itself.
