### ISSUE TITLE
[FEATURE REQUEST] Factory Reset too easy to do inadvertently causing loss of important stats

### ISSUE THREAD

**Issue by crabbedh** [prusa3d/Prusa-Firmware#3448]
Printers affected
[MK3S+]   but possibly many other Prusa models

The **total filament** and **print time** are important statistics an owner will use to determine when to service their printer. However, I have inadvertently zeroed these stats, via a FACTORY RESET 4 times in my first month of operation (even though IT is my profession). For whatever reason, if the print goes south, hitting the reset button will stop the head and prevent any potential damage. Then the Z axis must be raised to get the head away from the print which requires a long press of the rotary switch. However, if one doesn't wait until the reset is fully processed after hitting the reset button ...  and then immediately does a long press on the black switch, a factory reset is immediately initiated which zeros these important parameters. 

**Edit** I just read some bug reports about the Print Time not being computed properly.. so maybe this has something to contribute to my print time stats not working.. I had assumed it was being zeroed by the factory reset. I just completed an 11 hour print job with no problems (no resets) and the print time stayed on 6h 50m. Looks like the print time feature just doesn't work.

**Edit #2**
Just now learned that print time is not tracked through the OctoPrint system I use. Thus print time is ** NOT** zeroed via factory reset… so my suggestion was based on inaccurate understanding of how the system was tracking time.

I would, though, make the factory reset less easy to trigger.

========. Please ignore ================

Solution #1
=============
Put a "yes/no" question when a factory reset is about to be initiated so this doesn't happen inadvertently.

Solution #2
==========
Make it much harder to do a factory reset.. maybe it is intended that the factory reset needs to hold down both buttons for a long time.. but this is not the case..  at the least look for BOTH buttons down for 10 seconds....

Solution #3
============
Don't zero the stats on a factory reset

**Comment by 3d-gussner** [comment]
Closing as #4809 solves it.
