### ISSUE TITLE
G4 (dwell) breaks M601 (pause)

### ISSUE THREAD

**Issue by tross5** [prusa3d/Prusa-Firmware#3453]
**Printer type**: Prusa Mini (not Mini+)
**Firmware version**: 4.3.4

**USB / Octoprint**: USB

**Describe the bug**:
I recently wrote some custom "Start G-code" in PrusaSlicer to get around the temperature dependence problems associated with the M.I.N.D.A. sensor. Part of this customization includes the `G4` dwell command to allow a thermal equilibrium to be reached before running the mesh bed leveling process. The code modifications solve the M.I.N.D.A. associated problems, but introduce a separate problem. Specifically, if the dwell duration is 120 seconds or longer (`G4 S120`), the print head fails to park during a pause (`M601`) and at the end of a print. The print does pause, it's just that the print head remains directly on the print.

To test whether the problem was specifically with the `G4` command or one of my other start code modifications, I reverted to the original Prusa Mini start G-code and manually entered a `G4` command just before mesh bed leveling. Sure enough, `G4 S30` works as intended, but `G4 S120` breaks the `M601` command.

**To reproduce**:

1. Slice a cylinder (or anything else) with the Original Prusa MINI and MINI+ printer profile.
2. Insert a pause print command at some arbitrary layer.
3. Re-slice the object and export the G-code.
4. Open the G-code in a text editor and insert `G4 S120` just before `G29 ; mesh bed leveling`
5. Run the G-code

Note that using `G4 S30` in the above example provides the expected behavior.

**Expected behavior**:
Print extruder and bed park at the `M601` command and upon print completion, i.e. extruder moves up and to x = 0 and bed moves to y = 120.

**Comment by 3d-gussner** [comment]
@tross5 This repository is for the MK2,2.5 and MK3 8-bit printers please open the issue in the MINI repository https://github.com/prusa3d/Prusa-Firmware-Buddy and close this one.
