### ISSUE TITLE
  [ENHANCEMENT] MMU2S in error state - add delay before heaters turn off 

### ISSUE THREAD

**Issue by floridaservices** [prusa3d/Prusa-Firmware#3463]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MK3S
**MMU Upgrade** - MMU2S

**Is your enhancement related to a problem? Please describe.**
  When troubleshooting a feed issue with the MMU2S it is frustrating to have it automatically turn off the hot end automatically when it  has a problem.  I agree that turning off the hot end is a wise design decision when the MMU2S thinks there is a problem but there should be a delay before it does so.  Currently there is no delay so when troubleshooting a feed issue this heater disable routine adds unnecessary frustration to a routine troubleshooting process<pull out filament, refeed it, try again>, especially if this process has to be repeated.  I want control over the heater, especially since I am hands on.    
  
**Describe the solution you'd like**
I would like the hot end heat setting to remain unchanged for a period of time.  I used the example 10 minutes, that would be acceptable.  Ideally I would like an override to bypass the timer completely because I find it unnecessary in my setup.

**Comment by gudnimg** [comment]
Closing as this is now resolved with FW 3.13.0 and MMU FW 3.0.0 :)
