### ISSUE TITLE
[BUG] FW doesn't build if `BABYSTEPPING` is disabled

### ISSUE THREAD

**Issue by gudnimg** [prusa3d/Prusa-Firmware#3464]
**Printer type** - Any
**Printer firmware version** -  master branch, 3.10.1 and earlier

**MMU upgrade** - N/A
**MMU upgrade firmware version** - N/A
**SD card or USB/Octoprint** - N/A

**Describe the bug**
If `BABYSTEPPING` is disabled in `Configuration_adv.h` then the firmware will fail to build. There is code in ultralcd.cpp which doesn't respect this setting. 
  
**To Reproduce**
Comment out `#define BABYSTEPPING` in `Configuration_adv.h` and try to build the firmware. I get the following result:

![image](https://user-images.githubusercontent.com/8218499/161833281-56f23988-d93a-4ab7-9b92-3ab1adb1297c.png)

  
**Expected behavior**
  Firmware should build. But I'm not sure what the expected behaviour is in the LCD. Should the babystepping menu be disabled completely?

**Comment by 3d-gussner** [comment]
@gudnimg Still valid or can it be closed?

**Comment by gudnimg** [comment]
It is still valid but this is very low priority (not sure if it's worth fixing at this point). Closing this issue for now.
