### ISSUE TITLE
[BUG]<Fan Spin up every 5-6 Seconds>

### ISSUE THREAD

**Issue by juckendesAuge** [prusa3d/Prusa-Firmware#3469]
**Printer type** - [MK3s+]
**Printer firmware version** -  [3.10.1-4697]

**SD card or USB/Octoprint**
 In print and without print. Only turn on the Fan in the Menue Settings/Temperature/Fanspeed
You can hear and see it with print with Pet-G, because the Printfan is not set to 100% (255)

**Describe the bug**
  Fan Spin up to 100% every 5-6 Seconds
  
**To Reproduce**
  Go to the Menue Settings/Temperature/Fanspeed and set it to 100 or 150
  
**Expected behavior**
  That the fan rotates constantly at the set speed.
  
**Video**
https://youtu.be/KOiB7L9xlAc

**Comment by 3d-gussner** [comment]
@juckendesAuge Thanks for the "bug" report.
It has been already discussed in Pull requests and issues. Please try next time to search the github in open and closed issues and pull requests before opening a new issue.
   
The fans generate at low RPM so much noise on the signal line that it is hard to distinguish if it is spinning or not. To be able to get some "readable" values the fan is forced to spin up.

I know it is annoying that the part fan spins up from time to time especially with cooling sensitive filaments.

Please also have a look at https://github.com/prusa3d/Prusa-Firmware/issues/1516
