### ISSUE TITLE
Extruder feed rate changes to random values when starting new print on MMU

### ISSUE THREAD

**Issue by moisedanieln** [prusa3d/Prusa-Firmware#348]
I am having some problems with my MK2S MMU when printing from SD card. If i use Single Extruder Mode and i change the current extruder when starting a new print(the gcode asks T?), the extruder speed changes randomly to over 100%. The bigest change so far was up to 133%. First i believed it was a Slic3r issue but the gcode outputs M203 at 100%. I also found that the same gcode file gives diferent speed errors when changing the extruder. This behaviour has appeared after upgrading to vs 3.1.0

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete.

Marina Curzi
Prusa Research
