### ISSUE TITLE
[QUESTION]README.md file seems out of date. Which file do we flash?

### ISSUE THREAD

**Issue by MadoxLabs** [prusa3d/Prusa-Firmware#3484]
The README file says that, for windows builds, 'Export compiled Binary" creates the file "Firmware.ino.rambo.hex".
Actually two files get created: "Firmware.ino.with_bootloader.prusa_einsy_rambo.hex" and "Firmware.ino.prusa_einsy_rambo".
Which of these files should be used to flash? Or under what conditions should each file be used?

**Comment by leptun** [comment]
You need to use `Firmware.ino.prusa_einsy_rambo.hex` if flashing using the bootloader (via the einsy USB port, so the default way).
If you are using a programmer on the ICSP header, then use the "with bootloader" hex file

**Comment by MadoxLabs** [comment]
Awesome, thanks
