### ISSUE TITLE
[BUG]Nefunkční fw 3.10.+

### ISSUE THREAD

**Issue by Netrval** [prusa3d/Prusa-Firmware#3488]
[log.txt](https://github.com/prusa3d/Prusa-Firmware/files/8602458/log.txt)
Dobrý den
 
Od verze 3.10.+ se mi nedaří aktualizovat naši tiskárnu. Zkoušel jsem poslední verzi fw 3.11.0 a stále stejný výsledek, Instalace projde vše se tváří OK. Ale displej se v různých fázích zasekne a tiskárna už dále nekomunikuje. Prostě po dokončení instalace naběhne výběr jazyku a dál už nic. Jde o tiskárnu i3 MK3, je z roku 11.12.2017. Naštěsti je stále funkční fw 3.9.3

Na základě diskuze s podporou jsem zkoušel i reset do továního nastavení https://help.prusa3d.com/article/full-system-refresh-original-prusa-i3_133258. Výsledeke je pořád stejný, při nahrání fw 3.10.+ nenaběhne ani úvodní wizard, jen úvodní obrazovak displeje a dále už tiskárna na nic nereaguje.

fw 3.9.3 je funkční.
 
Přikládám log z upgradu

**Comment by Vossberger** [comment]
=> #3321
