### ISSUE TITLE
Firmware for PT1000 Thermistor

### ISSUE THREAD

**Issue by williamrehndell** [prusa3d/Prusa-Firmware#3492]
It would be perfect if you can make a FW for PT1000 Thermistors also. 

Why? 
Alot of Prusa users is upgrading with that type of Thermistor! 

Thanks!

**Comment by 3d-gussner** [comment]
Duplicate of https://github.com/prusa3d/Prusa-Firmware/issues/3302

**Comment by 3d-gussner** [comment]
Duplicate of https://github.com/prusa3d/Prusa-Firmware/issues/3302
