### ISSUE TITLE
distinguish between "c" filament changes and "p" pauses when reporting "time until" in the display

### ISSUE THREAD

**Issue by krhackbarth** [prusa3d/Prusa-Firmware#3499]
was Issue #8206.

I have prints where I pause the print to insert an RFID tag and then stop the print later for a color change.  Right now, the display shows "time until" each item with a "c".   I'd like more information by indicating time until pause with a "p" and time until filament change with a "c".  You could even rotate through all three (including time remaining in the print "r").  I hear this has to first be supported in the firmware.

**Comment by 3d-gussner** [comment]
I think that the functionality like it is implemented is working fine and additional `p` would
- use more resources, which is very limited on the Atmel 2560. 
- also would need different Slicers to support it (more human resources are needed, and ??? if approved)
- and may confuse users

Imagine  hh:mm`c` ==> time to `C`hange filament or time for Intera`c`tion with printer

**Comment by krhackbarth** [comment]
I would only want it to be supported for PrusaSlicer.  I don't think it would confuse users.  But if you don't have the memory or time then it can't be done.

**Comment by arekm** [comment]
Possible workaround - add ```M117 Last operation was XXX``` (like pause or color change) to pause and color change g-codes in slicer. But no idea how long M117 message is visible on lcd.

**Comment by gudnimg** [comment]
> But no idea how long M117 message is visible on lcd.

The message should stay on the screen until the print is resumed. Though this is only valid on the `MK3` branch (FW 3.12)

**Comment by arekm** [comment]
Ok, so this workaround will not work then.

**Comment by Prusa-Support** [comment]
Thank you for participating in our community.

Please consider closing this issue if your all questions have been answered.

Michele Moramarco
Prusa Research

**Comment by krhackbarth** [comment]
sounds like it can't be done.
