### ISSUE TITLE
[FEATURE REQUEST] Report print status for prusa connect or other loggers

### ISSUE THREAD

**Issue by jokohoko** [prusa3d/Prusa-Firmware#3511]
At the moment prusaConnect works great if you print trough the interface. But if you start a print from the SD card it cannot show any progress or print time in the interface. 
Likewise i wanted to program a monitor that keeps track of printer usage in our farm at the university to detect issues or to know how bussy they are. But there does not seem to be any Gcode to provide insight in the print currently printing. It could be enough to periodically print out the time remaining information or the filename of the active print. But preferably this should need a separate gcode.

If i missed anything i would like a reference to the documentation. But i did not find any insight into this information.

And later on this would also improve the interface of prusaconnect since it now shows ERROR if someone starts a print from the SD card.
![image](https://user-images.githubusercontent.com/6534647/172658855-56bc6d8b-1de7-41a6-9ea1-1cb75b9f86a7.png)

**Comment by jokohoko** [comment]
I stand corrected. On some files it does show the information...
Can anyone here tell me what gcode is used then to provide this information?

I will be logging communication between the two this weekend to find out.
So this request can probably be closed. But it would be nice to have official documented support for this.

**Comment by Prusa-Support** [comment]
Hello! Thank you for the report and sorry for the late response. A possible suspect can be that some of the GCodes that didn't show that info could have been not sliced with Prusa Slicer, or with an older version of Prusa Slicer, or it could be that the function "supports remaining times" could have been deactivated for these prints. Reference screenshots below. 

Alessandro Pantaleo
Prusa Research


![image (28)](https://user-images.githubusercontent.com/103262060/173839529-5ff52852-1053-4117-a9e9-c97b1d316fcd.png)
---
![image (29)](https://user-images.githubusercontent.com/103262060/173839574-a0efbba5-50ba-48cd-b2be-cc44e2776e31.png)

**Comment by jokohoko** [comment]
There is a Gcode for this it turns out. M27. So the bug is more on the prusaConnect side where it is not always shown or requested correctly.

**Comment by Prusa-Support** [comment]
Hello! Thank you for your response and for the report on this aspect - I'll move the thread to the Prusa Connect section, it can be good for our devs to notice and evaluate it. 

Alessandro Pantaleo
Prusa Research
