### ISSUE TITLE
[BUG] Start of the printing takes too long when Preheat is activated before FLC

### ISSUE THREAD

**Issue by Barnabasek** [prusa3d/Prusa-Firmware#3514]
**Printer type** -  MK3S
**Printer firmware version** -  3.11.0

**Describe the bug**
When you run Preheat (PLA) from the menu prior to First Layer Calibration (with PLA preset), it takes anywhere from 20 seconds to 1,5 minute before the printer starts printing the calibration print. Even AFTER it's already heated to the desired temperature. It seems to be waiting for something for a very long time.

This doesn't happen if you run just the First Layer Calibration straight without manual "Preheat". The printer starts the print within a few seconds after it reaches the desired temperatures.

2 videos for illustration:
First one is a normal First Layer Calibration procedure, run on a "hot" printer (the printer was already preheated from the previous print and the reset button was pressed before running this calibration. The temp at that moment is 200/59). Print starts almost immediately after temps reaches 215/60.

Second one is the one that shows the issue. First, "Preheat" for PLA is activated from the menu and I wait until it reaches 215/60. Then I run "First Layer Calibration" from the menu and select PLA (00:32-00:40 in the video). Even though the printer is already at 215/60 it doesn't start printing until 02:23 mark while it still shows "Bed Heating...." .
So it takes 1 minutes 43 seconds of waiting for the bed to heat, even though the desired temps have already been reached.

https://user-images.githubusercontent.com/35784551/173823890-c8d68767-33c3-4720-b29c-6c4f65f62756.mp4

https://user-images.githubusercontent.com/35784551/173823908-fd862bd4-c87b-407e-8223-1b4c91433590.mp4

**Comment by wavexx** [comment]
Internally, when calling M109 and M19*, "temperature residency" kicks in every time. This means that even following a preheat, the next print will still hit the residency timeout without starting immediately, which feels wrong.

On top of that, when already *at* the set temperature, the waiting loop can take a longer time to break out. I didn't take a look at why this is the case, but I do confirm by experience that it can take a surprisingly long amount of time...
