### ISSUE TITLE
[BUG]<M206 Command Stuck on sending>

### ISSUE THREAD

**Issue by bb00799** [prusa3d/Prusa-Firmware#3515]
Printer: Prusa MK3s+
Printer Firmware: Modified 3.11.0  (changed the Z travel limits)
Connected via USB to a Pronterface 

I am running a research project on developing a penetrating nozzle for use in FFF-style printers, and in doing so I have to set a new home. I am trying to do it manually using the M428 command (which doesn't exist for Prusa) or the M206. But whenever I try and set M206 it is just set on "SENDING M206". Am I missing something in the firmware that I need to comment out or initialze?

To Reproduce: Simply connect Prusa to an Pronterface dashboard and try and set an offset using M206, it has always been stuck on sending for me
  
![image](https://user-images.githubusercontent.com/98406503/175127134-ddaced44-f744-4157-9022-ee35399ae9b2.png)

**Comment by gudnimg** [comment]
```
    /*!
	### M206 - Set additional homing offsets <a href="https://reprap.org/wiki/G-code#M206:_Offset_axes">M206: Offset axes</a>
    #### Usage
    
        M206 [ X | Y | Z ]
    
    #### Parameters
    - `X` - X axis offset
    - `Y` - Y axis offset
    - `Z` - Z axis offset
	*/
    case 206:
      for(uint8_t i=0; i < 3; i++)
      {
        if(code_seen(axis_codes[i])) cs.add_homing[i] = code_value();
      }
      break;
```

M206 should not do anything if you only send “M206”. You can’t send any other gcode command?  Just by looking at your serial window it looks fine.

**Comment by bb00799** [comment]
> 

Thanks for getting back to me, I did select a set of offsets following the M206 command and it still was stuck on "SENDING: M206 X0 Y0 Z5"

I want to clarify that these are just random values to test whether the command works in the first place (hence why I didn't follow it up with M500)

**Comment by gudnimg** [comment]
I’m not convinced its hanging / not working. M206 doesnt send any string to the serial window as confirmation it did anything. One thing you could try is to add `MYSERIAL` calls like below. That should tell you if the code is run at all.

I dont have my printer in front of me to test but I recall the firmware should let you know if the command is invalid. 

```
    /*!
	### M206 - Set additional homing offsets <a href="https://reprap.org/wiki/G-code#M206:_Offset_axes">M206: Offset axes</a>
    #### Usage
    
        M206 [ X | Y | Z ]
    
    #### Parameters
    - `X` - X axis offset
    - `Y` - Y axis offset
    - `Z` - Z axis offset
	*/
    case 206:
      MYSERIAL.println(“M206 received”);
      for(uint8_t i=0; i < 3; i++)
      {
        if(code_seen(axis_codes[i])) cs.add_homing[i] = code_value();
      }
      MYSERIAL.println(“M206 done”);
      break;
```

**Comment by bb00799** [comment]
> 

Oh I did not know I could add that I will add that to my next round of firmware changes and throw that in my printer tomorrow! Ill reply back if it worked etc.

Thanks

**Comment by bb00799** [comment]
> ###

This worked! Thanks
