### ISSUE TITLE
[BUG] Z-Home keeps changing?

### ISSUE THREAD

**Issue by bb00799** [prusa3d/Prusa-Firmware#3517]
Printer: Prusa MK3s+
Printer Firmware: Modified 3.11.0 (changed the Z travel limits)
Connected via USB to a Pronterface

I am running a research project on developing a penetrating nozzle for use in FFF-style printers. And I am running into an issue where every time I hit the "Z-Home" function on Pronterface, the Home will move up about 0.15mm from the prior home and then trigger an endstop (not allowing me to move the nozzle down in the negative direction). Does anyone have any experience in fixing this? For clarification the only thing I have changed in my code is the Z_MAX_POS from 210 to 175, this is done to account for the longer nozzle.

**Comment by wavexx** [comment]
I guess the PINDA is lowered in this setup? Perhaps too low?
Can you try sending G30? Does this change anything?

There's an initial raising when homing from the LCD, this is used to avoid scraping the bed before XY is homed. However this is now done only if Z is low, so you shouldn't be able to get into that situation.

Maybe we never accounted for the possibility that we can exceed Z_MAX in some corner case.
