### ISSUE TITLE
extended "gcode" to rename/manage sheets

### ISSUE THREAD

**Issue by neslekkim** [prusa3d/Prusa-Firmware#3534]
editing sheet names and possibly ordering them, is a pain using the printers UI, would it be possible to have some sort of extended commands, or something that we could send using gcode/pronterface/prusaslicer to administer such features?
Usage of the sheets are useful for sheets itself, but also for having sheet+nozzle combos when one often swaps back and forth between a couple nozzles, but using the UI kinda prohibits this usage.

**Comment by wavexx** [comment]
Related PR #2201
