### ISSUE TITLE
[FEATURE REQUEST] A user defined pre-heat temperature

### ISSUE THREAD

**Issue by Area5142** [prusa3d/Prusa-Firmware#3537]
I often print with filaments that require a high temperature on the build plate (PC, PETG). Therefore I use the pre-heat function to warm up the printer while finishing the GCode to be printed.

Since the nozzle heats up much faster than the build plate, the nozzle often starts dripping and the melted filament stays in the nozzle for a long time at high temperature (can degrade).
To avoid this, I would like to be able to heat up the build plate to the working temperature, but only heat up the nozzle to 160-170 degrees (as it also happens in the Prusa Mini+ start code).

Today I solve the problem with a small GCode file which sets the nozzle temperature to 170 degrees and the build plate to working temperature.
A better solution would be a user defined pre-heat temperature which could be set as needed and is saved in EEPROM.

It could also be handy in other situations where the pre-defined settings don't match.

**Comment by Prusa-Support** [comment]
Thanks for sharing your idea.

The purpose of this feature request seems similar to #3279, but this is surely an equally valid method to reduce oozing.

My general recommendation is to wait several seconds before cleaning loaded material, so more plastic will ooze right away and be wiped off together with the loaded material. Yet an alternative could be making the extruder retract some filament.

The MINI uses a Bowden tubing feed system, which tends to ooze more and for a longer time compared to direct drive extruders. I believe this is the main reason why waiting for the nozzle to cool at 170°C before the mesh bed leveling is adopted on the MINI.
It could make sense to bring similar functionality to the MK3 even though, as long as you wait for a little before removing loaded material oozing should not be problematic.

This is a fair feature request in the end and can be an inspiration for further firmware improvements.

Michele Moramarco
Prusa Research
