### ISSUE TITLE
Menu -> Preheat -> Nozzle Change

### ISSUE THREAD

**Issue by JoeyMarkowitz** [prusa3d/Prusa-Firmware#3539]
It would be helpful to include a Nozzle change preheat setting configured to only heating the nozzle to 285 deg C as per instructions for changing the nozzle in the following youtube video by Prusa.

https://www.youtube.com/watch?v=txt6sxV6X88

**Comment by Prusa-Support** [comment]
This issue will be closed as a duplicate of #2972.

Michele Moramarco
Prusa Research
