### ISSUE TITLE
3.1.1 b138 RC3: Bed heater remains on at full power after temperature calibration

### ISSUE THREAD

**Issue by phildubach** [prusa3d/Prusa-Firmware#354]
Temp. calibration takes a long time, so users are likely to walk away and let it complete on its own.
At the end, it displays a message saying the calibration is complete, click to continue.
Until the user clicks the button, the bed heater remains on at full power. The heater should turn off once the process is complete, without waiting for user confirmation.

**Comment by phildubach** [comment]
Confirmed in source:
https://github.com/prusa3d/Prusa-Firmware/blob/07fe9abe444c957e4c183a48fe112ff4531fc466/Firmware/Marlin_main.cpp#L3167

Firmware waits for user to press the button before turning off the bed heater.
This only applies to the new PINDA probe with the integrated thermistor. The code path for the old PINDA probe correctly shuts off the bed heater before waiting for the button press.

**Comment by phildubach** [comment]
Simple fix. See pull request #359

**Comment by michalprusa** [comment]
Hello phildubach,
thank you for your cooperation and provided patch.
Looks good, I merged the PR, it'll be in RC4 release.
Have a good one!
