### ISSUE TITLE
[BUG]<Nozzle temperature does not rise>

### ISSUE THREAD

**Issue by TaroYamada1225** [prusa3d/Prusa-Firmware#3540]
**Printer type** - MK3S
**Printer firmware version** -  3.11.0

**Describe the bug**
I am rewriting the firmware using pt100 for high temperature printing.After I did a factory reset to get it back, I installed the default firmware from Prusa Slicer. However. The nozzle temperature stops at 160 ~ 170 ℃ and the temperature does not rise. Can you tell me if you have similar symptoms?

**To Reproduce**
Changed #define TEMP_SENSOR_0 in Configration_purusa.h from 5 to 247

**Comment by wavexx** [comment]
How are you building the firmware? It might be that Configuration_prusa.h is overwritten.
Try changing Firmware/variants/[your variant file] instead.
