### ISSUE TITLE
[FEATURE REQUEST] Show firmware-version in boot splash screen

### ISSUE THREAD

**Issue by MiOrt** [prusa3d/Prusa-Firmware#3553]
I would like to suggest to change the boot splash screen a little bit and show the current firmware-version on boot (MK3S, maybe already implemented for other printers which I don't owe).

**Comment by Prusa-Support** [comment]
Hello! Thank you for the request. I could notice now some of the thumbs up come from our dev, so all noted from our side ;) 

Alessandro Pantaleo
Prusa Research

**Comment by leptun** [comment]
Proposal implementation:
https://photos.app.goo.gl/JKVee4jkvd5BFtxY7

**Comment by MiOrt** [comment]
Looks good to me, thumbs up!
