### ISSUE TITLE
Please add a an option to keep the extruder and bed hot during a pause.

### ISSUE THREAD

**Issue by rokemronnie** [prusa3d/Prusa-Firmware#3611]
**Is your feature request related to a problem? Please describe.**
I often embed metal nuts and magnets in my prints. If I put a Pause in the G-Code, to insert the part, I get delamination, I believe that's because the part cools during the pause. If I put a color change in the G-Code, which keeps the extruder and bed hot during the color change, the print is fine.

**Describe the solution you'd like**
An option to keep the extruder and bed hot during a pause in the print. In addition to preventing delamination, it would also heat up the metal part, improving adhesion of the plastic to it.

**Describe how it would work**
Either add an option to the slicer for a pause without disabling the heaters, or change the firmware to give the option of keeping things hot when the print is paused.

**Describe alternatives you've considered**
As mentioned, I used the color change option to pause the print while keeping things hot.

**Comment by neophyl** [comment]
I was adding the following when the issue was moved -

How Pause is handled is up to the printer firmware.  So any issue raised should be wherever handles your printers firmware.  
For a Mk3 that is https://github.com/prusa3d/Prusa-Firmware/issues  or for a mini https://github.com/prusa3d/Prusa-Firmware-Buddy/issues

If you don't have a Prusa printer then it needs to be with whoever made it.  So what printer do you have rokemronnie ?

**Comment by Prusa-Support** [comment]
Thank you for reaching us.

Correct, that seems to be on the printer's firmware side, unless the printer is controlled by a 3rd party host software (e.g. Octoprint...) as explained here https://github.com/prusa3d/Prusa-Firmware/issues/3498#issuecomment-1182092698.

Our firmware normally should let the nozzle cool down to prevent clogs from excessive oozing while keeping the heatbed temperature up.
Also mind there could even be other reasons for a delamination issue (insufficient flow, non-optimal nozzle temperature, excessive cooling...).

In this case, information about printer type, firmware version, upgrades/mods, and print modality (SD, USB, Octoprint...) may help.

Michele Moramarco
Prusa Research
