### ISSUE TITLE
Repetier Server

### ISSUE THREAD

**Issue by strongbow1** [prusa3d/Prusa-Firmware#362]
Repetier Server cannot communicate with the printer. It connects but will not send anything to the printer. The older version of the firmware did work. could you please address this issue I have to revert to astroprint or octoprint for the time being

**Comment by KissmanCZ** [comment]
Which version of firmware, which printer, which connection? I am using latest on my MK3 with GPIO & USB too and all working fine with latest Repetier Server.

**Comment by strongbow1** [comment]
Prusa i3 Mk2s using the firmware 3.1.0 the latest one you can download from the Prusa support web page and I am using repetier server vers 0.86.2

**Comment by KissmanCZ** [comment]
So u must read better ;) there is a notice on Prusa driver page:

> Changes in 3.1.0 final: There’s a known bug using Repetier server, please wait for the next release if you’re using it

So, wait for the next release or downgrade ;) for a while...

**Comment by cboileau** [comment]
Is there ever going to be another firmware update with a fix for this? It's been broken since November with no update

**Comment by 3d-gussner** [comment]
@cboileau Which firmware and printer do you use?
@strongbow1 The MK2 branch merged a serial communication fix on 17. Nov 2017 but the latest release hex files you can get from Prusa is from 12. Nov 2017 so you it is missing that fix.

Try to compile the MK2 branch for yourself or checkout my https://github.com/3d-gussner/Prusa-Firmware/releases/tag/v3.1.0-001-HFM for the MK2/s/MMU

**Comment by 3d-gussner** [comment]
@strongbow1 This is an old ticket and should have been solved with newer firmware release even for the MK2.

Please close it.
[fixed]
