### ISSUE TITLE
[BUG] Crash when stopping print sliced as "sequential printing"

### ISSUE THREAD

**Issue by Min-Tec** [prusa3d/Prusa-Firmware#3623]
### Description of the bug

When stopping a print which was sliced as "sequential printing" the extruder (nozzle) crashed into another (already printed) part while the printer was moving to its home position.

Gcode which had the problem is attached. The print was stopped when the fourth object started printing (1 to 3 already fully printed).

Could be solved when the z-axis would fully rise to the top before the x- and y-axis would move to their home position.

### Project file & How to reproduce

[Object_0.2mm_ASA_MK3S_2h35m.zip](https://github.com/prusa3d/PrusaSlicer/files/9617548/Object_0.2mm_ASA_MK3S_2h35m.zip)

### Checklist of files included above

- [X] Project file
- [ ] Screenshot

### Version of PrusaSlicer

Version 2.5.0+win64

### Operating system

Windows 10

### Printer model

Prusa i3 MK3s

**Comment by wavexx** [comment]
This is internally related to #3496. Looks like we need to keep track of the maximum Z seen on the current print to handle both.

**Comment by ulab** [comment]
This is still something that should be looked at.

**Comment by 3d-gussner** [comment]
@ulab Thanks for the reminder, but it is a duplicate and I assigned the #3496 to myself to follow up this request.
Closing it.
