### ISSUE TITLE
  [ENHANCEMENT]<Enter comprehensive title>

### ISSUE THREAD

**Issue by misko903** [prusa3d/Prusa-Firmware#3637]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

MK3

Please add the new PA sheet to menu of possible sheets. now only Custom is available.

Thank you :)

**Comment by Barnabasek** [comment]
You can rename ANY of the sheets in the menu to your liking. Click the sheet name and select Rename and change the name to PA sheet.

**Comment by Prusa-Support** [comment]
> You can rename ANY of the sheets in the menu to your liking. Click the sheet name and select Rename and change the name to PA sheet.

Exactly. Besides this, these sheets are not that popular at the moment, but our developers may consider adding pre-named sheet profiles in the future.

Thank you for your suggestion.

Michele Moramarco
Prusa Research

**Comment by misko903** [comment]
I know about the feature - renaming. But my sheet collection is growing and
there is already no reserve.

Even another topic - with Revo becomes nozzle changing too much hidden in
the menu.

Dňa st 5. 10. 2022, 16:09 Prusa-Support ***@***.***>
napísal(a):

**Comment by Prusa-Support** [comment]
The Nylon specific sheet profile was added in FW [3.12.0-RC1](https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.12.0-RC1).

This issue will be closed as completed now.

Michele Moramarco
Prusa Research
