### ISSUE TITLE
[BUG]<Gets stock in Prusa logo>

### ISSUE THREAD

**Issue by ghost** [prusa3d/Prusa-Firmware#3640]
**Printer type** - MK3S, 
**Printer firmware version** -  [ 3.10.1

**SD card 
   print via SD card 

**Describe the bug**
  I was trying to update to a 3.11. It get stock always in verifying firmware 100%. I try with to many different firmware, cables, PC/Mac,also I try to flash Xloader with no luck , I don’t know if my einsy Rambo is toasted. I’m a little frustrated because is practically a new machine.

  

**Error**
  eading 1##并＃##井##＃#井#＃并#井#＃＃#井并＃井##井#＃井##＃＃＃##＃＃#护＃我##我###1 100号 32.12S
avrdude-slic3r: verifying
avrdude-slic3r: verification
error, first mismatch at byte 0x0100
0x02 != 0x3f
avrdude-slic3r: verification error; content mismatch
avrdude-slic3r done.
Thank you.

**Comment by ghost** [comment]
![D563219D-872A-4DCD-A655-664330F38C37](https://user-images.githubusercontent.com/114741473/193261826-a401d807-66bc-45f0-b9d4-dd13707c642f.jpeg)
![1C4F31A4-126B-47DB-838F-7AE56E51DDF5](https://user-images.githubusercontent.com/114741473/193261841-ba595264-19f0-4eab-b835-c5c8b22a2e55.jpeg)

**Comment by leptun** [comment]
Please upload the complete log from the firmware flasher

**Comment by ghost** [comment]
> 

Hey thank for your quick response!!!!
Here is the log


avrdude-slic3r -v -p atmega2560 -c wiring -P /dev/cu.usbmodem14101 -b 115200 -D -U flash:w:0:/Users/machd/Desktop/prusa3d_fw_MK3S_MK3S+_3_11_0_4955.hex:i

avrdude-slic3r: Version 6.3-20160220-prusa3d, compiled on Sep  6 2022 at 09:19:15
                Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
                Copyright (c) 2007-2014 Joerg Wunsch


                Using Port                    : /dev/cu.usbmodem14101
                Using Programmer              : wiring
                Overriding Baud Rate          : 115200
                AVR Part                      : ATmega2560
                Chip Erase delay              : 9000 us
                PAGEL                         : PD7
                BS2                           : PA0
                RESET disposition             : dedicated
                RETRY pulse                   : SCK
                serial program mode           : yes
                parallel program mode         : yes
                Timeout                       : 200
                StabDelay                     : 100
                CmdexeDelay                   : 25
                SyncLoops                     : 32
                ByteDelay                     : 0
                PollIndex                     : 3
                PollValue                     : 0x53
                Memory Detail                 :

                                         Block Poll               Page                       Polled
                  Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                  ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                  eeprom        65    10     8    0 no       4096    8      0  9000  9000 0x00 0x00
                  flash         65    10   256    0 yes    262144  256   1024  4500  4500 0x00 0x00
                  lfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
                  hfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
                  efuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
                  lock           0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
                  calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
                  signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

                Programmer Type : Wiring
                Description     : Wiring
                Programmer Model: AVRISP
                Hardware Version: 15
                Firmware Version Master : 2.10
                Vtarget         : 0.0 V
                SCK period      : 0.1 us

avrdude-slic3r: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude-slic3r: Device signature = 0x1e9801 (probably m2560)
avrdude-slic3r: reading input file "/Users/machd/Desktop/prusa3d_fw_MK3S_MK3S+_3_11_0_4955.hex"
avrdude-slic3r: writing flash (250500 bytes):

Writing | ################################################## | 100% 44.28s

avrdude-slic3r: 250500 bytes of flash written
avrdude-slic3r: verifying flash memory against /Users/machd/Desktop/prusa3d_fw_MK3S_MK3S+_3_11_0_4955.hex:
avrdude-slic3r: load data flash data from input file /Users/machd/Desktop/prusa3d_fw_MK3S_MK3S+_3_11_0_4955.hex:
avrdude-slic3r: input file /Users/machd/Desktop/prusa3d_fw_MK3S_MK3S+_3_11_0_4955.hex contains 250500 bytes
avrdude-slic3r: reading on-chip flash data:

Reading | ################################################## | 100% 32.47s

avrdude-slic3r: verifying ...
avrdude-slic3r: verification error, first mismatch at byte 0x0100
                0x02 != 0x3f
avrdude-slic3r: verification error; content mismatch

avrdude-slic3r done.  Thank you.

**Comment by leptun** [comment]
From the log it looks like it's failing to verify the first upload stage data. I've never seen this error before. The only way for this to happen is if the hardware is faulty. Please contact Prusa support to get your board replaced.
You also said that you tried other cables, so that rules out a power issue. I don't think xloader works with this microcontroller. Only avrdude works using the "wiring" programmer type.

Did you flash the firmware _many_ times on that board? The board can only be flashed at least 10000 times before the flash starts dying in this way. I also see that you have different fuse settings than standard (hfuse 0xD0 vs the stock 0xD8).

**Comment by ghost** [comment]
Is there any other way to get fixed. If I buy those main chip and replace it and try to program again it can work again?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/114741473/193352072-97342d10-54c2-49a0-8df9-e5bc4a1de739.png)

**Comment by leptun** [comment]
Only the atmega2560 would need replacing for it to work again. And of course it would need the bootloader flashed again using a programmer.

**Comment by ghost** [comment]
What kind of bootloader do I need and programmer ?

**Comment by leptun** [comment]
Any AVR compatible programmer. It needs to be able to upload using the ICSP header.
The bootloader used is https://github.com/prusa3d/Arduino_Boards/blob/master/IDE_Board_Manager/prusa3dboards/bootloaders/prusa_einsy_rambo/stk500boot_v2_mega2560.hex
It is better if the Arduino IDE is used for "burning the bootloader" since that also sets the correct fuse settings.

Since this issue is not related to the 8bit firmware, I will be closing the issue. Please consider either contacting Prusa support if this is an original board or asking for technical help on the forum (for example, here: https://forum.prusa3d.com/forum/original-prusa-i3-mk3s-mk3-hardware-firmware-and-software-help/)

**Comment by Prusa-Support** [comment]
Thanks for bringing this to our attention.

You can reach the official Prusa Technical Support either via email or Live Chat.
https://help.prusa3d.com/article/customer-support_2287

I personally recommend writing an email to info@prusa3d.com, with reference to this issue (Prusa-Firmware/issues/3640), to my attention (Michele Moramarco).

We may want to start with installing the firmware on the Einsy board fully disconnected (except for PSU and computer), and taking this chance to take clear pictures of the Einsy board front and back without any connections.
Please continue via Tech Support.

Michele Moramarco
Prusa Resaerch
