### ISSUE TITLE
Wizard asks if filament is loaded

### ISSUE THREAD

**Issue by AdamMeadowsCRT** [prusa3d/Prusa-Firmware#366]
On Mk3 b142 firmware, when using the wizard, the printer asks if filament is loaded. 

Since there is a sensor can it not detect that filament is present?
If it requires movement perhaps the E axis could move a little to move the filament?

If its all stone cold then obviously that would be impractical as you would have to wait for heating too.

**Comment by inquisitiveKangaroo** [comment]
Hi
The first layer calibration mainly require PLA as the code is writen for PLA. The wizard wants to warn you to check if it's truly the PLA in the first place. However, you are right it would be possible.)
Thank you for interesting idea.)
