### ISSUE TITLE
[ENHANCEMENT] 3.11. Cooling Fan Stays on while colorchange M600

### ISSUE THREAD

**Issue by GMeyerGMeyer** [prusa3d/Prusa-Firmware#3670]
--> MK3S, 3.11, no MMU, Sd card, 

I printed a larger model and somehow Prusa Slicer 2.5.0 added a color change....  So 

1. after M600, he parked the printer head above the I3 sign of the prusa metal sheet. 
4. the printing cooling fan was still active. 
5. i was somewhere else, so i detected that message an hour later. 
6. While the printer wanted me to unload filament, the front fan was all the time engaged-> BUG. Thus, it was cooling down my printed element, which was, unfortunatley on that corner lifted up. :/
7. i unloaded filament, reloaded it, continued printing, still happy. 

Wanted Behaviour: If the printer detects that the filament stucks or is empty, ther printer does not print anymore, so 

- please turn off the front cooling fan, as it is not needet anylonger (cause we cant currently print) until we reload and restart printing. Thats all :)

I enclosed the model, and the g code. you will find it in line 130939. 

Thanks a lot!

![failure](https://user-images.githubusercontent.com/115288041/194616393-0de9cbb9-a96f-4184-b329-148c9277b63a.PNG)

Cheers George
[Model and GCode.zip](https://github.com/prusa3d/Prusa-Firmware/files/9741045/Model.and.GCode.zip)

**Comment by Prusa-Support** [comment]
Thank you for reaching us.

Apparently, this behavior is not intentional and can be improved.
On the other hand, the blowing fan may slightly mitigate oozing and may not be the main cause of the lifting corner on your print.

It seems the object is specifically large and printed with PLA on a textured sheet, so the chances of a detaching corner of the print were higher than usual.
Moreover, if the print fan blowing played a role, it was an unfortunate case that the filament change occurred at a low height, and was not accomplished in a short time.

Please consider the other possible causes of the little print issue but we thank you for the input.
Our developers may make use of this issue to enhance the filament change behavior.

Michele Moramarco
Prusa Research

**Comment by GMeyerGMeyer** [comment]
Thanks for your answer. 

The filament change came from a non reproducable slicing operation. When i resliced it the next run ( no changed settings) it produced code without the filament change. 

Still would be lovely if on next firmware the fan would stop working when filament change is in progress... 

I was capable of reproducing the source of lifting. Its the temperature sensor. If your environment is a bit cool (18°C), and you print large objects, the Heatbed does not lose as much energy above the sensor than in the corners of the bed. Thus, it heats the center to 60°C, but you have lower temperatures in the corners. When changing bed temperature to 68°C it worked all well.

**Comment by Prusa-Support** [comment]
Interesting how the color change occurred unintentionally. It would be interesting to study if reproducible. It may have been the case of an accidental click in Prusa Slicer though (it happened to me).

Exactly. The heat dissipation is stronger near the edges.
I think the heat dissipation is even slightly faster in the case of the Textured and Satin sheets compared to the Smooth sheet. Also, the temperature is only probed in the middle and the heater circuit is subdivided into three zones (non-concentric) - it wouldn't be possible to provide the perimetrical area with a higher power, that is not necessary though. 
The temperature gradient is usually negligible, but increasing the temperature is something I often recommend to be on the safe side, in case of large prints; plus, possibly use the most convenient sheet according to the print scenario. Careful though, a too-high bed temperature may cause warping and poor plastic segments blending.

For the curious ones, together with the announced series of "business" printers (farm printers in Dubai Expo 2020 and Prusa XL), we introduced a modular heatbed made of individually controlled 9×9 cm tiles 🙂 

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
I think the cause and complications of this issue are sorted out, but the issue will stay open so that our developers can consider it as an enhancement to improve the print fan behavior during the filament change.

Michele Moramarco
Prusa Research

**Comment by GMeyerGMeyer** [comment]
Hi Michele, 

yes, its been an unintentional click in the slicer. A checkbox would be nice when exporting like: 
"Do you realle want to use multiple colors?"
In Eding CNC i have those checkboxes for multiple G-Code Features. Very nice, clearyfies my actions... As an unintentional click is very likely for non dayly users like me...

Thanks a lot in advance.  

![1](https://user-images.githubusercontent.com/115288041/200111538-148427bd-0e01-4d35-b4c8-07d2a12d68a4.png)
