### ISSUE TITLE
[FEATURE REQUEST]  MK3s FW 3.12 Beta 1 Option to temporary Disable Temperature model, when changing nozzle

### ISSUE THREAD

**Issue by extremeall** [prusa3d/Prusa-Firmware#3719]
When changing nozzle with the temperature model enabled, you get a warning. This makes sense because the temperature fluctates. 

However a feature to temporary disable the check when changing nozzle would be great. 

Maybe even a nozzle changing menu item, that preheats the extruder to the correct temperature and disables the check

**Comment by Prusa-Support** [comment]
Thank you for your suggestion.
Sounds good. Our developers will think about it.

Michele Moramarco
Prusa Research

**Comment by F1rst-Lay3r** [comment]
Reproducible:	Yes
Printer model:	MK3S+ stock
Modifications:	Fan shroud removed during nozzle change.

That is an option I would like too. When changing the nozzle, you will now receive a 'Thermal Anomaly' warning. If it takes longer to change the nozzle, then an M112 follows. In itself great that the temperature model is doing its job, in case of a nozzle swap perhaps less desirable.

![20221204_150133](https://user-images.githubusercontent.com/93616156/205602270-66b8630c-940d-4b3b-97db-148c27bd4105.jpg)
![20221204_150211](https://user-images.githubusercontent.com/93616156/205602291-39a827ec-f9da-4a9a-a5fe-b62045c74213.jpg)

**Comment by Prusa-Support** [comment]
Thanks for your feedback.

For now, when needed, please consider sending codes `M310 S0` and `M500` to _disable thermal model protection_ and _save_, as per https://github.com/prusa3d/Prusa-Firmware/issues/3636#issuecomment-1315241854.

Michele Moramarco
Prusa Research

**Comment by wavexx** [comment]
This should be fixed by the new "Nozzle change" menu #3774

**Comment by Prusa-Support** [comment]
The new FW [3.12.0-RC2](https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.12.0-RC2) solves and closes this issue.
This is an almost definitive version so feel free to help with the final testing and share feedback here.
The issue could be re-opened if necessary.

Michele Moramarco
Prusa Research

**Comment by F1rst-Lay3r** [comment]
The 'Nozzle change'  menu option is a great solution to temporarily disable the temperature model.
One thing comes to mind: 
When selecting the option, the printer first homes and then the extruder moves to a high position for better access to the extruder. That's a nice feature also, but be aware that the online manual 'instructs' to temporarily store the print fan between the timing belt during a nozzle change. It could happen that one has already removed the print fan and stored it between the belts, prior to choosing the menu-option. This way, the belts will move while the print fan is clamped between the belts. Maybe that should be mentioned in the online manual. 

Above all: thank you for adding this feature!

**Comment by wavexx** [comment]
> This way, the belts will move while the print fan is clamped between the belts

I know I do this too!
