### ISSUE TITLE
[BUG]<Enter comprehensive title>

### ISSUE THREAD

**Issue by lamppis** [prusa3d/Prusa-Firmware#3736]
Prusa mk3s, FIRMWARE 3.11.0, octoprint.

Stringed filament got into the extruder fan. The printer stopped with ext fan error as it should. For some reason it kept the nozzle heated. Is this intentional? Seems bit dangerous.

**Comment by 3d-gussner** [comment]
@lamppis Thanks for the bug report, we will try to reproduce the issue.
I updated the description so it is easier to follow up.

**Comment by 3d-gussner** [comment]
I tested with OctoPrint and FW 3.11.0 and stalled the Hotend fan.
As you can see the heater and bed turned off.

Can you please try to reproduce the error and post a picture.

![Mon Nov  7 11:21:58 2022](https://user-images.githubusercontent.com/25530011/200286969-ab905f84-6e1f-47f8-8fcf-70114fdeeeee.png)
![Mon Nov  7 11:22:21 2022](https://user-images.githubusercontent.com/25530011/200287241-c910eb36-cff0-42df-9151-845d2ad1a637.png)
