### ISSUE TITLE
MK3 Print from USB 

### ISSUE THREAD

**Issue by alessandroame** [prusa3d/Prusa-Firmware#374]
With 3.1.1 b143 RC4 when I print from usb often the extruder "goes away" with a linear motion. When  reach the boundary come back to print.

**Comment by PavelSindler** [comment]
We are currently focusing on this issue. Please print from SD card for now. Thank you for understanding.

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete. In case the issue is still not solved, please contact info@prusa3d.com.

Marina Curzi
Prusa Research
