### ISSUE TITLE
[BUG] mk2.5S hidden "experimental" menu is empty

### ISSUE THREAD

**Issue by filewalker1** [prusa3d/Prusa-Firmware#3744]
**Printer type** MK2.5S
**Printer firmware version** -  3.10.0, 3.10.1, 3.11.0, 3.12.0-Beta1

**Describe the bug**
  It is possible to activate the hidden "experimental" Menu in the HW-Settings, but the menu is empty, no options at all.
  
**Expected behavior**
  see a similar menu as in the MK3, maybe missing the options which are mk3 specifig (e.g. e-cool mode - i think this feature is not available with the old stepper drivers?).

**Comment by leptun** [comment]
I'm not sure if anything could be placed in the menu. The available options are MK3 specific. We could hide the menu in the MK2.5 builds, but it's not like the MK2.5 is tight on resources at the moment.
@gudnimg Any idea what we could put here?

**Comment by filewalker1** [comment]
okay, i was not aware that none of the option is supported by mk2.5. If this is the case it is totally fine for me to leave this menu in MK2.5 builds. I am having problems with SNR recognition and support told me to try fake SNR from experimental menu, so i thought i is maybe a bug, that this option is not available on MK2.5

**Comment by gudnimg** [comment]
> I'm not sure if anything could be placed in the menu. The available options are MK3 specific. We could hide the menu in the MK2.5 builds, but it's not like the MK2.5 is tight on resources at the moment. @gudnimg Any idea what we could put here?

I think we can leave the menu empty, similarly how there is an empty menu when there is no SD card connected. I don't really see this as an issue.

**Comment by mrecman** [comment]
> > I'm not sure if anything could be placed in the menu. The available options are MK3 specific. We could hide the menu in the MK2.5 builds, but it's not like the MK2.5 is tight on resources at the moment. [@gudnimg](https://github.com/gudnimg) Any idea what we could put here?
> 
> I think we can leave the menu empty, similarly how there is an empty menu when there is no SD card connected. I don't really see this as an issue.

For example, I must use Delta fan with 8000rpm and I can set ALTFAN option to enable. Please return menu to MK2.5S firmware. Very thanks.

Send D3 Ax0d2b X01 or X00 via Serial has no effect. Read D3 Ax0d2b C1 return valid stored value even after restart, but vent still running at aprox. 8000rpm... :-(

**Comment by 3d-gussner** [comment]
@mrecman Changing the EEPROM value isn't enough as the variants for the MK2.5/S don't have
```
#define EXTRUDER_ALTFAN_DETECT
#define EXTRUDER_ALTFAN_SPEED_SILENT 128
```

You can change `#define EXTRUDER_AUTO_FAN_SPEED   255  // == full speed` to `#define EXTRUDER_AUTO_FAN_SPEED   128  // == alt fan speed` and compile the firmware.

>Please return menu to MK2.5S firmware.

In which version was it available?

**Comment by mrecman** [comment]
> [@mrecman](https://github.com/mrecman) Changing the EEPROM value isn't enough as the variants for the MK2.5/S don't have
> 
> ```
> #define EXTRUDER_ALTFAN_DETECT
> #define EXTRUDER_ALTFAN_SPEED_SILENT 128
> ```
> 
> You can change `#define EXTRUDER_AUTO_FAN_SPEED 255 // == full speed` to `#define EXTRUDER_AUTO_FAN_SPEED 128 // == alt fan speed` and compile the firmware.
> 
> > Please return menu to MK2.5S firmware.
> 
> In which version was it available?

Sorry. I mean ADD EXPERIMENTAL menu to MK2.5S firmware.

But I try compile firmware myself. Thanks.
