### ISSUE TITLE
MK3 Print from sd freeze

### ISSUE THREAD

**Issue by alessandroame** [prusa3d/Prusa-Firmware#375]
With 3.1.1 b143 RC4 when I print from sd often the printer freeze (with bed and hotend kept warm) until I press one time the knob.

**Comment by PavelSindler** [comment]
Hello @alessandroame , do you have some gcode file where this issue occured? Can you send it here?

**Comment by alessandroame** [comment]
Yes I've gcode but is a commercial model so I must send it privately. How can I do that?

**Comment by DiddyWolf** [comment]
I've also seen this issue on 3.1.1 b143 with the gcode attached.
[Speaker_Mount_v2.gcode.txt](https://github.com/prusa3d/Prusa-Firmware/files/1633684/Speaker_Mount_v2.gcode.txt)

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete. In case the issue is still not solved, please contact info@prusa3d.com.

Marina Curzi
Prusa Research
