### ISSUE TITLE
MK3 Tranparent TPU and filament sensor

### ISSUE THREAD

**Issue by alessandroame** [prusa3d/Prusa-Firmware#376]
With 3.1.1 b143 RC4 when I print transparent tpu (I've tried all sainsmart transparent colors) often the print stop, the bed go back the extruder go right and the printer ask to unload and then reload the filament.
When I disable the sensor or when I use pla with solid color the problem does not persist.

**Comment by cnlson** [comment]
i've had this happen a couple of times with solid colors. but it appears there might have been some over-retraction going on which caused it to need to be restarted.  Conversely I have printed Sainsmart transparent Pet-g with no issues at all

**Comment by funkycode** [comment]
I printed with white e3d edge filament (PETG) with no problem, while with black esun PETG I get constant requests to load and unload filament. 
Little bit hard to tell if it's coz of low temp, jams, retraction or colour.

**Comment by jolcese** [comment]
I have the same problem with transparent Sainsmart TPU and firmware 3.1.2

**Comment by renarsvilnis** [comment]
Currently printing a model with transparent Flexfill 98A, every 10-20min (everyother layer) I get the issue where I need to unload and load the filament. It's so annoying, as I'm in 3h of printing.

First time using flexfill - is it that it's a quirk with the filament itself or the filament sensor struggling with transparent filaments?

Have a bit with PLA (bundled grey) and PETG (black) and I never have had this issue with them.

Using `Prusa mk3` with `v3.2.1` firmware.

**Update:** Turned off filament sensor as mentioned by @alessandroame and printed fine

**Comment by westranm** [comment]
I'm having this same issue with eSun transparent florescent orange PETG on v3.2.0 firmware.  However, I have used clear, florescent green, and red transparent PETG filaments from YOYI without any issue.

**Comment by dipree** [comment]
I seem to have the same problem. When printing transparent Flex from Fillamentum the print stops and asks to reload. However, the same problem occurs with black SaintSmart TPU so I believe that it's not the transparency but the reflection of the surface? All the flexible materials are way more shiny as PLA, ABS etc.
