### ISSUE TITLE
New MK3 Firmware 143e and 150 causes X and Y belts to slip.

### ISSUE THREAD

**Issue by JagerSprinkles** [prusa3d/Prusa-Firmware#378]
I never had an issue with the X and Y belts slipping before I updated. The Y belt always slips right after the purge line when the head goes to the first point of the print. Later the X and Y belts will slip when doing a travel move. The slip happens when the head decelerates at the end of the move like the stepper is decelerating too fast.

I have reverted to firmware r137 and the problem is completely gone.

Some more info:
Printing from Octoprint 1.3.6 via USB
Same G-Code files slip on r143 and not on r137

I would have posted this to the Prusa forums but I am unable to log in there.

**Comment by craftit** [comment]
I've seen this issue on a brand new factory assembled printer, both printing from USB as well as from SD card though it took longer to happen.  Using lower poly versions of the parts, (which generate smaller gcode files) seems to reduce the chances of it happening.

**Comment by JagerSprinkles** [comment]
This is still a problem with version 150
