### ISSUE TITLE
3.13.0 returns 0 to "M862.3 Q" - Get printer type

### ISSUE THREAD

**Issue by TojikCZ** [prusa3d/Prusa-Firmware#3788]
MK3S MMU2S on 3.13.0-Alpha1 
Send "M862.3 Q" over serial. It should not return 0, but that's what seems to be happening

**Comment by gudnimg** [comment]
I am getting garbage from the command. 
![image](https://user-images.githubusercontent.com/8218499/205435497-e40ac0cb-bffa-461b-92c8-939570924e88.png)

**Comment by leptun** [comment]
@gudnimg It's because of a null pointer reference to progmem. See nPrinterType and sPrinterName which don't get initialized

**Comment by gudnimg** [comment]
This seems to resolve it 
M862.2 Q also returned 0, but now it returns the correct number 20302
![image](https://user-images.githubusercontent.com/8218499/205437158-e15a3c41-f926-4b9d-a54a-aece7ced1485.png)
