### ISSUE TITLE
[FEATURE REQUEST] MMU2s calibration only before print

### ISSUE THREAD

**Issue by seppelicous** [prusa3d/Prusa-Firmware#3807]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** - MK3s+
**MMU Upgrade** - MMU2s

**Is your feature request related to a problem? Please describe.**
  When starting the printer, the MMU makes loud knocking noise. When octoprint is connected, it does this again after establishing the connection. Then it calibrates again right before printing. The noise is terrible loud, especially when printer is next to sleeping rooms.
  
**Describe the solution you'd like**
 Kind of a silent feature, where the MMU will only be calibrated once the actual print starts.

**Comment by gudnimg** [comment]
@seppelicous just to be clear, are you talking about the homing being loud (Idler)?

I assume when Octoprint is connected, that restarts the printer and MMU => MMU re-homes.

**Comment by leptun** [comment]
This problem is also fixed in the (yet unreleased) mmu fw 2.x. Homing is now done using stall detection, so it should be considerably quieter.

**Comment by seppelicous** [comment]
@gudnimg correct, the revolver "hammers" a few times, which is extremely loud. 
Great to hear, that you are working on an update. Wouldn't it be possible to postpone the homing right close to the printing process or when pressing one of the 3 buttons? I mean, also the selector is only homing when the MMU is actually needed

**Comment by gudnimg** [comment]
> Wouldn't it be possible to postpone the homing right close to the printing process or when pressing one of the 3 buttons?

This isn't on our to-do list for 3.13. The homing is now considerably more silent. Additionally there will be an option for users to reduce the sound more, for example by slowing down the homing further.

**Comment by seppelicous** [comment]
Sounds great, thank you! Can't wait to see the release. Can we expect the update in the next weeks?

**Comment by gudnimg** [comment]
It should be sometime soon™ after 3.12 is released.
