### ISSUE TITLE
[FEATURE REQUEST] Allow independent movement of idler and selector in MMU2S for troubleshooting

### ISSUE THREAD

**Issue by SemaphoreSlim1** [prusa3d/Prusa-Firmware#3810]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** -MK3S+
**MMU Upgrade** - MMU2S

**Is your feature request related to a problem? Please describe.**
  When attempting to troubleshoot issues with the MMU, sometimes the selector will not move. Tearing everything apart and using a multimeter probe found that there was a bad wire. 
What was frustrating about this was  that it was not obvious if the selector was not moving because it was not *supposed to* move, or if it was just not getting signal. Same with the idler. An option to independently move just move the selector, or just the idler would have made troubleshooting much easier.
  
**Describe the solution you'd like**
 Just like we can independently move the x, y, z, and extruder in the settings, I'd like the additional option to independently move the idler and selector. After moving one or the other, I understand that this would put the MMU in some kind of new "indeterminate" state as it presently always assumes that the idler and selector are in sync. It would be acceptable for both the idler and selector to re-home prior to printing, or have an option to home them somewhere near the option to home the x,y, and z axises.

**Comment by Prusa-Support** [comment]
Thanks for the suggestion.

The user can check if the idler and selector can move by 5 positions, matching the LED on the top. The selector should be able to move by one extra (null) position.
Sincerely I'm not sure what benefit such as feature will bring to troubleshooting.

Michele Moramarco
Prusa Research
