### ISSUE TITLE
[BUG] Feedback on 3.12 Beta/RC 1

### ISSUE THREAD

**Issue by webRat** [prusa3d/Prusa-Firmware#3817]
I was running 3.12 beta prior to installing my revo 6, and recently, I had a blob on my MK3S+ -- So, I upgraded to the revo 6 since I already did it on both my Prusa Mini+ with great success.

I was also running the 3.12 beta version of the printer firmware.

3 days into some pretty intense printing, I noticed something in the air and came down to find bubbling filament on the print bed. I shut everything down, and waited for the air to clear up with assistance with a filter.

I immediately started suspecting the revo heater core since it's a known issue and my heater core does not have a blue wire. I documented everything, and worked with warranty exchanged and everything happened and I swapped out with a new heater core.

When I did the swap out, I upgraded to the 3.12 rc1 firmware.

I've been printing Christmas baubles all weekend long so that I can get some ornaments out to friends/family (Quantum PLA - raspberry green/gold, fun stuff). This morning, I started up my printer so that I can get everything going on. I hit print. The printer was supposed to go up to 220°, and I'm watching it climb to 280°. o_O

I cancel the print/shut it down, wait. I turned it back on, unloaded filament, did a PID tune, and then without any filament loaded, started a new print again. Once again, watched it climb to 236° (when it should have been 220°).

I decided to revert back to the 3.11 firmware to see if it's the firmware or the heater core.

So far, everything is fine again, and the temperatures have been stable. I recognize that I had too many variables changing, but I think I'm now pointing at the firmware as the issue.

**Comment by webRat** [comment]
I'm actually considering that 3.12 beta was responsible for the blob.

**Comment by webRat** [comment]
Video of it hitting 232° before dropping back down to 224°
https://photos.app.goo.gl/TyP7brwthUAyNa7h6

**Comment by webRat** [comment]
Grant at 3D Musketeers pointed out that it goes from `208 to 196` 26 seconds into the video. I'll double check that wiring isn't an issue.

**Comment by webRat** [comment]
![firmware_1 12rc](https://user-images.githubusercontent.com/59866/207123313-090da443-6eec-4c3a-9e28-56d3ced896ce.png)

This is 1.12 rc, printed last night. The above happened to me because I saw these flaws and decided to reprint them. I've had a successful prints with 1.12 rc, but I haven't been able to reproduce it since that successful print. Zero changes to gcode.

**Comment by webRat** [comment]
After I reverted back to 1.11, I reran the print. No changes to gcode.

![firmware_1 11](https://user-images.githubusercontent.com/59866/207123582-154cecde-f4ef-494e-ad27-2d80359538bb.jpg)

**Comment by wavexx** [comment]
The difference looks wild. The sudden drop in temperature in the video is suspicious indeed.

Did you try to do some basic cable/connector tests? Preheat to something lower where it seems "stable/safe" (down to 150C if necessary).

While it's hot, *slowly* move the cable bundle around, to see if there is any position where the temperature drops or raises, even for a brief time. You can also disable the steppers, and move the whole extruder left to right slowly. To move Z use the menu. I see this because the pattern seems correlated with extruder height and the entire top part looks bad.

If you can spot a pattern using the LCD, and it's quick to respond, it's usually the thermistor wires that make a false contact (this can be anywhere in the path, inside the cable, at the connector, in the core).

FW 3.12 is designed to be much more sensitive to this. However if you find a pattern, the same issue should be there in 3.11 as well (just as a counter-test).

If you can't find anything, FW 3.12 also has detailed temperature data to do extra checks. Add the following gcode:

```
M155 S1 C3
D70 I1
```

before starting your print and log the entire serial output, zip it and attach it here. We can use this to see what is going on.

**Comment by webRat** [comment]
> Did you try to do some basic cable/connector tests? Preheat to something lower where it seems "stable/safe" (down to 150C if necessary).

> While it's hot, slowly move the cable bundle around, to see if there is any position where the temperature drops or raises, even for a brief time.


That's my goal this tonight/this week. Just to be clear, the 2nd photo you see there is directly after flashing back to 1.11. There's a lot of back and forth movements on that print, especially vase mode. If there was cable issue, I'd expect to see it there as well. Not saying I won't investigate, I plan to. Will record screen, and add the gcode you recommended.

I haven't done the logging thing before, so I'll have to figure out how to do that.

**Comment by wavexx** [comment]
> Just to be clear, the 2nd photo you see there is directly after flashing back to 1.11. There's a lot of back and forth movements on that print, especially vase mode. If there was cable issue, I'd expect to see it there as well.

If there are short, but consistent cable faults from the thermistor, FW 3.11 will tent to report a temperature which is closer to the current average so it will have less overshoot. But it's just a guess.

Another test you can do is to use a different heater/thermistor on FW 3.12 (I assume you still have the original heater). If that still happens it would narrow down the issue to either FW or einsy fault.

**Comment by webRat** [comment]
> Another test you can do is to use a different heater/thermistor on FW 3.12 (I assume you still have the original heater). If that still happens it would narrow down the issue to either FW or einsy fault.

Original heater was involved in a blob and needs a clean-up, plus swapping everything back to stock would take considerable amount of time that I don't think I can commit to other than to temporarily connect it to the board and run a standard heat up/heat down test.

**Comment by wavexx** [comment]
Heh, I know the pain. Plugging it in might be ok if that still shows problems (then something would be _very_ wrong), however by itself is not enough. A faulty hotend might not show problems if you just leave it still.

**Comment by webRat** [comment]
Cable jiggling results with firmware 1.11
https://photos.app.goo.gl/mpUnm2Xkeb7rnqaa7

I haven't added the gcode or started logging yet.

**Comment by wavexx** [comment]
There are some temperature jumps also here (150->155, or 150->143 at 1:38). These are too big to be fluctuations. Move the cable close to the connectors inside the einsy too (the crimps can make a bad contact too).

When moving the bundle or extruder you need to go a lot slower if you want to identify a failure such as this. As in 1mm/s.

**Comment by wavexx** [comment]
News?

**Comment by webRat** [comment]
I think you're correct that it's a wire problem. I re-flashed 3.12:
https://photos.app.goo.gl/LSxQsWNwwyNU6WJL9 -- I disabled steppers, moved it side to side, nothing. Then I poked the wire harness from the back, and it immediately spiked.

**Comment by webRat** [comment]
For what it's worth, I am running a revo. I re-read my information above, and see that I forgot to declare it. I've replaced all the wiring, still having issues, but I see now it's a known issue. Hope the team can get this sorted. This has to be frustrating.

**Comment by Prusa-Support** [comment]
OK then please post the log of the thermal model calibration in issue https://github.com/prusa3d/Prusa-Firmware/issues/3636 if you don't mind.

Michele Moramarco
Prusa Research
