### ISSUE TITLE
[ENHANCEMENT] PF-build could use cmake to build

### ISSUE THREAD

**Issue by wavexx** [prusa3d/Prusa-Firmware#3843]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - n/a
**MMU Upgrade** - n/a

**Is your enhancement related to a problem? Please describe.**
PF-build.sh is currently using arduino-builder, but it should be switched to use cmake internally in order avoid a completely different build path.
  
**Describe the solution you'd like**
Change PF-build.sh to use bootstrap.py and cmake, so that there is one build system only.

**Comment by 3d-gussner** [comment]
Closing this working on it for FW 3.14.0
