### ISSUE TITLE
Firmware setting - Autoprint the first/newest/only file on the SD card after inserting.

### ISSUE THREAD

**Issue by Valthol** [prusa3d/Prusa-Firmware#3874]
Is your feature request related to a problem? Please describe.
I do believe that in 99% cases if we take out the SD card and insert it we ALWAYS want to print the first/newest file/only file on top of the list on the SD CARD.

Describe the solution you'd like
When you insert SD card it automatically goes to the browse menu, it would be awesome if a user could turn on an option in the settings that when SD card is inserted it automatically starts the print with newest file on it or a file with specific name.

Describe how it would work
For one printer it is not an issue, for 10 printers and 3 times a day loading SD card with always a new file - it is pretty time saving!

Describe alternatives you've considered
Could be also that it will automatically start the print only if there is ONLY one file in the SD card.

It should be different from the already present autoprint feature with filename auto1.g on bootup - we don't want to start multiple prints just by turning on the printers. We need a specific solution for when you insert a SD card with an intent to start the printing.

**Comment by Prusa-Support** [comment]
Thank you for your suggestion.

When you insert an SD card, the content of the card is immediately displayed. If the [sorting method](https://help.prusa3d.com/article/sd-card-sorting_2214) is set to '_date_', the gcode on the first line will be the most recently uploaded on the SD card.
It would only take scrolling one line down and pressing the knob for the user to start printing.
However. I understand that the feature you are requesting can be a time saver at the end of the day if you run a print farm.

Please notice that more recent printers with advanced boards (MINI and SL1) already support the one-click option (no-click may not sound very safe), but we are looking at very different boards.
Also please notice that Prusa Link supports a remote "upload & print" option, and Prusa Connect supports more advanced options that aim to ease print-farms management. This system is still in the early development stage but you can test it already (more info at https://connect.prusa3d.com/).

This said, I can't tell if this feature would realistically be supported on the MK3-series in the future, but you can leave the issue open as inspiration for further developments.

Michele Moramarco
Prusa Research
