### ISSUE TITLE
Thermal anomaly Mk3+Revo Micro

### ISSUE THREAD

**Issue by FrHePo** [prusa3d/Prusa-Firmware#3906]
**Printer type** - MK3 + Revo Micro + modded fan shroud
**Printer firmware version** - 3.12.0

**SD card
**Describe the bug** No calibration Temp Model possible -> Thermal anomaly is detected
     Reproducible: Yes
    Printer model: MK3 modified
    Modifications: E3D Revo Micro + different Fan + different Fan shroud (my own)
   
    Try to add a serial log of the print failing. Not yet tried to print. Switched off Temp Model (M310 S0).

  
**To Reproduce**
  Please describe steps to reproduce the behavior.
  
**Expected behavior**
  
**G-code**
  Please attach a G-code. This will make it easier for us to replicate the error.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by mix579** [comment]
What is says in the release notes. Revo not supported at this point.

**Comment by FrHePo** [comment]
Sure.

**Comment by arekm** [comment]
https://github.com/prusa3d/Prusa-Firmware/issues/3636#issuecomment-1380243362

**Comment by FrHePo** [comment]
Thanks!

**Comment by 3d-gussner** [comment]
@FrHePo Please close this issue and continue in  https://github.com/prusa3d/Prusa-Firmware/issues/3636#issuecomment-1380243362

**Comment by ZacharyACoon** [comment]
I was given a workaround to calibrate with a 75W heater that I think might apply to you.
https://github.com/prusa3d/Prusa-Firmware/issues/3963#issuecomment-1407484995

**Comment by FrHePo** [comment]
Closed as requested. Continued in https://github.com/prusa3d/Prusa-Firmware/issues/3636#issuecomment-1380243362.
