### ISSUE TITLE
[BUG] Nozzle change doesn't unload the filament

### ISSUE THREAD

**Issue by DominikPalo** [prusa3d/Prusa-Firmware#3951]
**Printer type** MK3S+
**Printer firmware version** -  3.12.0

**Describe the bug**
According to the [recommended procedure](https://help.prusa3d.com/article/changing-or-replacing-the-nozzle-mk2-5s-mk3s-mk3s_2069#procedure), the filament has to be unloaded AFTER preheating to 280 °C. Unfortunately, when I use the new "Nozzle change" functionality, the filament is not automatically unloaded after the desired temperature is reached (and it is not even possible to unload the filament manually - as the menu is locked during the "Nozzle change" procedure). A workaround is to restart the printer, unload the filament manually and start the "Nozzle change" procedure again...
  
**To Reproduce**
  1) Execute "Settings" -> "HW setup" -> "Nozzle change"
  2) Wait until the hotend reaches 280 °C
  3) Filament is not unloaded
  
**Expected behavior**
  1) Execute "Settings" -> "HW setup" -> "Nozzle change"
  2) Wait until the hotend reaches 280 °C
  3) If the filament is present, is it automatically unloaded

**Comment by mix579** [comment]
Yep. You have to unload the filament before you initiate the nozzle swap. The (old) instructions are incorrect. Plus, it never made sense to unload PLA or PETG at 280…

**Comment by Prusa-Support** [comment]
Hello! Thank you for reporting this, the article is now updated 🙂 

Alessandro Pantaleo
Prusa Research
