### ISSUE TITLE
[BUG] Wizard exist on start, without error

### ISSUE THREAD

**Issue by agehring** [prusa3d/Prusa-Firmware#3953]
**Printer type** - MK3S+
**Printer firmware version** -  3.12.0.5
**MMU upgrade** - N/A
**MMU upgrade firmware version** - N/A

**SD card or USB/Octoprint**
USB/Octoprint

**Describe the bug**
After update to 3.12, attempting to run wizard results in a beep and return to status screen without wizard running
  
**To Reproduce**
Update to 3.12, attempt to run wizard
  
**Expected behavior**
Wizard run though calibration
  
**G-code**
n/A

**Video**
Will record if needed

**Comment by 3d-gussner** [comment]
@agehring Thanks for the report. What is FW 3.12.0.5? The newest release is [FW 3.12.1](https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.12.1)
Please flash this firmware and report back.
