### ISSUE TITLE
[BUG] [CRITICAL] [WORKAROUND] [3.12.1] 75W heater.  Wizard calibration ignores temperature anomaly disable with M310 S0\nM500

### ISSUE THREAD

**Issue by ZacharyACoon** [prusa3d/Prusa-Firmware#3963]
75W heater.  (yup)

```
M310 S0; disable thermal model protection
M500; save settings across reboots
M310 A F1; run temperature calibration, THERMAL ANOMALY
```

Cannot proceed.

**Comment by wavexx** [comment]
This is expected. `M310 A F1` will check against the stock V6 heater (and complain that the heater is too powerful).
Is this a V6 with a 75W heater? In that case you have to set the power:

```
M310 S0 ; disable
M310 P75 ; set heater power
M310 A F0 ; calibrate for a different hotend
M310 S1 ; enable again
M500 ; optionally save if everything is working
```

**Comment by ZacharyACoon** [comment]
> This is expected. `M310 A F1` will check against the stock V6 heater (and complain that the heater is too powerful). Is this a V6 with a 75W heater? In that case you have to set the power:
> 
> ```
> M310 S0 ; disable
> M310 P75 ; set heater power
> M310 A F0 ; calibrate for a different hotend
> M310 S1 ; enable again
> M500 ; optionally save if everything is working
> ```

This worked as a workaround.  I'm going to spam this on some related issues to unblock people.

**Comment by ackerthehacker2** [comment]
If you disable thermal protection, does running calibration re-enables it?  Also, you might want to hilight in the documentation running PID calibration first as I think it will help with a lot of problems folks are having with non-moded printers).

**Comment by 3d-gussner** [comment]
@ZacharyACoon Please consider to close this issue.

**Comment by jdrozdz** [comment]
> This is expected. `M310 A F1` will check against the stock V6 heater (and complain that the heater is too powerful). Is this a V6 with a 75W heater? In that case you have to set the power:
> 
> ```
> M310 S0 ; disable
> M310 P75 ; set heater power
> M310 A F0 ; calibrate for a different hotend
> M310 S1 ; enable again
> M500 ; optionally save if everything is working
> ```

Not working for me

**Comment by Prusa-Support** [comment]
Thanks for getting in touch.

Now I hope you don't mind me closing this issue in favor of the similar one https://github.com/prusa3d/Prusa-Firmware/issues/4015, as the specific problem described by the author no longer applies.
The other issue instead focuses on different wattage heaters in general and will remain open for now.

Please find useful links and information in this [comment](https://github.com/prusa3d/Prusa-Firmware/issues/4015#issuecomment-1481686416), and feel free to take part in the relevant thread.

Michele Moramarco
Prusa Research
