### ISSUE TITLE
[BUG] PINDA Calibration fails with HOTEND FAN ERROR

### ISSUE THREAD

**Issue by fornellas** [prusa3d/Prusa-Firmware#3972]
**Printer type** - MK2.5S
**Printer firmware version** -  3.12.1

**MMU upgrade** - N/A
**MMU upgrade firmware version** - N/A

**SD card or USB/Octoprint**
Octoprint

**Describe the bug**

- PINDA calibration fails with hotend fan error.
  - Hotend fan works fine when printing thtough.
  - Self test passes.
- Bed is "forgotten" at 110C, until it is manually set to 0.
- Environment temperature is ~22C.
- PINDA Calibration worked fine with previous firmwares.
- When the failure happens, I noticed the hotend was passivelly heated up to 50C, and itts fan seems to start / stop in a loop every ~2s or so. I wonder if this is somehow triggering the hotend fan error.

**To Reproduce**

- Calibration > PINDA Cal.
  
**Expected behavior**
For calibration to conclude susccessfully.
  
**G-code**
N/A

**Video**

https://photos.app.goo.gl/ghdm51k6ZnYdyxb7A

![image](https://user-images.githubusercontent.com/1386232/215328770-cb600619-c26b-4afa-aea7-d6a3ce5ce4cb.png)

**Comment by gudnimg** [comment]
> When the failure happens, I noticed the hotend was passivelly heated up to 50C, and itts fan seems to start / stop in a loop every ~2s or so. I wonder if this is somehow triggering the hotend fan error.

@wavexx I wonder if this issue is related https://github.com/prusa3d/Prusa-Firmware/issues/3513 🤔

**Comment by gudnimg** [comment]
@fornellas does the error appear immediately? Or does it happen at a specific step in the calibration?

**Comment by fornellas** [comment]
@gudnimg the error happend 2-3 times, IIRC, all at step 6/6, which yes, has the hotend at 50C and bed at 110C.

I'm trying again now. 1/6 to 5/6 went somewhat quick, but it tseems to be stuck at step 6/6 for ~2h at this point. It seem whatever the calibration algorithm is doing, isn't converging to a result. All I get from serial at this point is:

```
echo:busy: processing
T:50.01 E:0 B:110.0
T:50.06 E:0 B:110.0
echo:busy: processing
T:50.09 E:0 B:110.0
T:50.00 E:0 B:110.0
echo:busy: processing
T:50.02 E:0 B:110.0
T:50.12 E:0 B:110.0
echo:busy: processing
T:50.02 E:0 B:110.0
T:50.04 E:0 B:109.9
```

**Comment by gudnimg** [comment]
I suspect this is where the firmware is getting stuck: https://github.com/prusa3d/Prusa-Firmware/blob/c9722c2b63b66e32c55f6fb477d952116ca21c62/Firmware/Marlin_main.cpp#L4987

The bed target at 110°C hints at this.

**Comment by gudnimg** [comment]
@fornellas There should be at the start a log which has this string: `"start temperature: "` it should include `start_temp` could you check what it shows?

It seems to me `start_temp` is 70°C, but that doesn't sound right.

**Comment by fornellas** [comment]
@gudnimg sorry for the late reply, just updated to 3.12.2-5713 and tried again. It is one more time stuck on 6/6 for over 1h:

```
zcat prusa-PINDA-Calibration.log.gz | grep -Ev '^(echo:busy|T:)'
MMUstart
echo: 3.12.2-5713
echo: Last Updated: Feb 28 2023 08:57:48 | Author: (none, default config)
Compiled: Feb 28 2023
echo: Free Memory: 2858  PlannerBufferBytes: 1792
echo:Stored settings retrieved
adc_init
FSensor ENABLED
echo:SD init fail
echo:SD init fail
echo:enqueing "G76"
echo:Enqueing to the front: "G28 W0"
PINDA probe calibration start
start temperature: 35.0
LCD status changed
MMU not responding - DISABLED

ZERO: 0.172

Step: 1/6 (skipped)
PINDA temperature: 35 Z shift (mm):0

Step: 2/6

PINDA temperature: 40.0 Z shift (mm): 0.010
Step: 3/6

PINDA temperature: 45.2 Z shift (mm): 0.025
Step: 4/6

PINDA temperature: 50.0 Z shift (mm): 0.050
Step: 5/6

PINDA temperature: 55.0 Z shift (mm): 0.070
Step: 6/6
```


[prusa-PINDA-Calibration.log.gz](https://github.com/prusa3d/Prusa-Firmware/files/11033014/prusa-PINDA-Calibration.log.gz)

**Comment by gudnimg** [comment]
Thank you for the logs! :) Looking at it, it seems to confirm my suspicion that the firmware is getting stuck in one of the `while` loops

https://github.com/prusa3d/Prusa-Firmware/blob/c9722c2b63b66e32c55f6fb477d952116ca21c62/Firmware/Marlin_main.cpp#L5037

Unfortunately the firmware is not reporting the current PINDA temperature which seems very strange to me. The PINDA temperature reading is apparently not reaching 60°C But we don't know what the current temperature the sensor sees since its not in the logs.

**Comment by gudnimg** [comment]
@fornellas is the PINDA maybe too far away from the bed? How does your PINDA position compare to the image below?

![image](https://user-images.githubusercontent.com/8218499/226740510-20f18dc9-df32-4a55-a396-e209e9275537.png)

**Comment by fornellas** [comment]
It was like this (about "1 zip tie" high):

![image](https://user-images.githubusercontent.com/1386232/226750300-2999e953-3121-4bc6-af61-f92f7f4829f2.png)

I've pushed it down a bit:

![image](https://user-images.githubusercontent.com/1386232/226750353-0e8c1f9f-957a-4c47-b8ea-0214403db7a0.png)

and tried again and... it worked.

It seems there are 3 things to consider here:

- The fan error maaay have been related to the temperature being at the threshold of the fan starting / stopping, and at low PWM values, the fan wouldn't turn.
- The fact that there's no time limit to this calibration is a bit concerning: IMHO it should have one.
- If the time limit is reached, potentially adding a suggestion to check the distance between the PINDA probe and the bed would be helpful.

Thanks for the help @gudnimg !

I'll leave this ticket open in case someone decides to work on any of the items above (or discuss further), at least for my case, "case closed" :-D

**Comment by 3d-gussner** [comment]
Please close this issue as users can search also for closed one
