### ISSUE TITLE
MK3S: Thermal Anomaly annoying (option to deactivate that "feature")

### ISSUE THREAD

**Issue by Dephrilibrium** [prusa3d/Prusa-Firmware#4026]
Heyho Prusa-Dev-Team,

since my last firmwareupdate my printer beeps around all the time when I change my printer nozzle (1-2 times a week). I had already the case that my neighbours woke up (thin walls) and asked me after that.

Therefore it would be cool to have an option in the menu where I can disable that "feature".

Kind regards,
Deph

**Comment by sbellon** [comment]
They already have an option "Nozzle change" in the menu where it is disabled in order to change the nozzle.

**Comment by 3d-gussner** [comment]
@Dephrilibrium Please consider to close this issue as @sbellon pointed out the solution.
