### ISSUE TITLE
[BUG] FW 13.2.x: Very loud Extruder when loading Filament

### ISSUE THREAD

**Issue by marcelismus** [prusa3d/Prusa-Firmware#4042]
**Printer type** - MK3S+
**Printer firmware version** -  3.11.x -> 3.12.1

**MMU upgrade** - No.
**MMU upgrade firmware version** - n/a

**SD card or USB/Octoprint**
Checked both, but not relevant.

**Describe the bug**
When loading filament, the motor revs up and starts making clicking noises - videos are worth 1,000 words. Previously, with the original Prusa hotend, I thought it was a clog. But because I wanted to switch to the Revo Six anyway, I installed the hotend and the extruder shows similar behavior when loading the filament. So clog can be excluded. 

Correct temperature, nozzle 0.4mm inserted, nozzle 0.4mm stored in the printer settings. I had completely reset the printer and successfully ran the wizard. However, this did not bring any improvement. 

I then switched back to firmware 3.11.x and lo and behold, it works again. Again to the firmware 3.12.1 and again the problem with the noisy extruder. Back to the 3.11 and it works again.
  
**To Reproduce**
Unload Filament. Load Filament, same.
  
**Expected behavior**
Loading Filament without THAT noise. ;-)

**Video**
https://user-images.githubusercontent.com/4125999/220135513-eb522da2-1813-4003-94eb-3401ee8b0552.mp4

**Comment by 3d-gussner** [comment]
@marcelismus Thanks for the report. At the beginning I was not able to reproduce this issue. But at some point it happened. I just don't have a reproducible way to see when it happens.

Do you have a way to reproduce this issue?
A detailed step by step would be great.
Like
1. Filament unloaded
2. power on printer
3. Fil. sensor shows 0 in LCD -> Support -> Sensor Info
4. FSensor active
5. Auto load active
6. Preheat or set nozzle temp
7. push filament into extruder
8. auto load starts
9. ....

**Comment by Prusa-Support** [comment]
Thanks for the feedback and the video. 
The fact that you can reproduce the problem only on the most recent firmware is probably not a coincidence, this sounded like a mechanical problem though (misaligned drive gear, improperly tensioned idler door, debris on the gears...), and we could hardly reproduce the problem on our side without clear instructions.

Please review the extruder assembly, hardware, and cleaning, and let us know if this issue is still relevant.

Michele Moramarco
Prusa Research

**Comment by marcelismus** [comment]
Sorry, I had not followed up on this topic. But I can not give instructions for reproduction, because it basically always happens. No matter if filament was loaded before or not, no matter if on and off....

With the version 13.2.2 it seems to be solved, a downgrade to 13.2.x led then however again to the result, hardware-sided I can exclude it. Checksums seem correct, I have not looked at more. Since but probably not a big issue and for me at least the last 1-2 days solved, the ticket can be closed.
