### ISSUE TITLE
[BUG]3.12.1 crashes in a middle of a print

### ISSUE THREAD

**Issue by ackerthehacker2** [prusa3d/Prusa-Firmware#4045]
**Printer type** - MK3S+
**Printer firmware version** -  3.12.1

**MMU upgrade** - none
**MMU upgrade firmware version** - n/a

**SD card or USB/Octoprint**
 USB/Octoprint

**Describe the bug**
Printing a job multiple times ...have already printed this 5 times ... in the middle of print, the printer crashes/resets itself
  
**To Reproduce**
Not doing anything special.  Have a serial.log
  
**Expected behavior**
Not crash
  
[roll_PrusaRoller_0.2mm_PETG_MK3S_6h27m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/10799771/roll_PrusaRoller_0.2mm_PETG_MK3S_6h27m.gcode.zip)
[serial.log.zip](https://github.com/prusa3d/Prusa-Firmware/files/10799772/serial.log.zip)

**G-code**
attached

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by ackerthehacker2** [comment]
Its not octoprint crashing ... Octoprint has been up for almost 2 days but it could be Prusaslicer ...was running the 2.6 alpha version ...I'll switch back if it happens again.

**Comment by v1p3r0u5** [comment]
@ackerthehacker2 Just out of curiosity, as it sounds very similar to a problem I am having. Do you print inside an enclosure or do you print somewhere with higher ambient temperatures than 30 degrees celsius?

see #4000

**Comment by ackerthehacker2** [comment]
I have a space heater in my office and its 78F which is 26C

**Comment by v1p3r0u5** [comment]
So then it is most likely not the same issue as I am having.

**Comment by ackerthehacker2** [comment]
Its still crashing for no reason ...
[serial.log.zip](https://github.com/prusa3d/Prusa-Firmware/files/10841189/serial.log.zip)

**Comment by gudnimg** [comment]
@ackerthehacker2 it looks like a power supply issue. UVLO/INT4 is triggered when the printer is turned off.
![image](https://user-images.githubusercontent.com/8218499/221629475-a359cd65-ee83-44e8-84c3-cb0297e4efc6.png)

![image](https://user-images.githubusercontent.com/8218499/221629724-39bdb9d1-557a-4526-a6c6-e8cd7bce4076.png)

**Comment by shawly** [comment]
Had this exact UVLO issue yesterday in the middle of a print, this happened after I upgraded to 3.12.2 and I also have a lot of stringing since the upgrade after the thermal calibration...

**Comment by Prusa-Support** [comment]
Thanks for reaching out to us.

Did a _FW crash_ error occur?
If so, a dump should be automatically generated and available to be downloaded.
https://help.prusa3d.com/article/crash-dump_364959

It may be useful for our developers to understand the problem.

Michele Moramarco
Prusa Research

**Comment by Rob70ar** [comment]
I’m having the same problem running 3.12.2 and 3.12.1. So far the workaround seems to use 3.11 😡😡😡

**Comment by DidaJI** [comment]
I also have the same problem, I had to go back to version 3.11

**Comment by ackerthehacker2** [comment]
Unfortunately, you can’t do that with a Revo nozzle.

**Comment by Prusa-Support** [comment]
In case of _FW crash_ error please provide the dump file for our developers to move the investigation forward.
https://help.prusa3d.com/article/crash-dump_364959

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
Is this issue still relevant?
Also please notice that a new firmware version is out.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
We couldn't confirm the presence of a bug.
The issue can be closed as stale now but feel free to comment below in case you have further feedback to share.

Michele Moramarco
Prusa Research
