### ISSUE TITLE
Update Firmware from SD card

### ISSUE THREAD

**Issue by julie777** [prusa3d/Prusa-Firmware#4068]
Note: I am duplicating this in both PrusaSlicer and in PrusaFirmware
Slicer issue 9972

**Is your feature request related to a problem? Please describe.**
When I select print from SD card file on MK3S+ I often get a notification that there is new firmware available and I should update. But at that moment all I can do is to click the button to make the message go away and start printing. Then later I have to move a computer within USB cable reach of the printer to update the firmware.

**Describe the solution you'd like**
Somehow PrusaSlicer is checking for new firmware and I imaging adding that information to the gcode file that I am about to print.

1. I would like the slicer to notify me that new firmware is available. It could do this by always saving the firmware file to the its configuration directory for all printers that I have setup.
If the slicer sees a new firmware version it could download it and ask if I would like to save it to the sdcard.
2. The printer could just check the SD card for a firmware file and if it is a newer version ask if I want to install it.
3. The printer could then install its own firmware, like other printers do.

**Describe how it would work**
Be as descriptive as your skill level allows you.

**Describe alternatives you've considered**

**Additional context**
Add any other context or paint drawing about the feature request here.

If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** -  MK3S+

**Is your feature request related to a problem? Please describe.**
  
**Describe the solution you'd like**

**Comment by gudnimg** [comment]
I doubt its possible to update the 8-bit AVR firmware via SD card with the current hardware/bootloader. 

The slicer has no idea what firmware is on your printer, it has no way to communicate with the firmware other than to upgrade the firmware via USB cable.

**Comment by 3d-gussner** [comment]
Sorry, but I doubt that this possible and even if we don't have the resources for this.

Hope it is okay that we close this feature request.
