### ISSUE TITLE
[BUG]<language selection doesn´t work with new firmware>

### ISSUE THREAD

**Issue by MartinD000** [prusa3d/Prusa-Firmware#4074]
**Printer type** - [MK3S+]
**Printer firmware version** -  [3.12.2]

**used interfaces** - SD card + Prusalink
  
**Describe the bug**
 Since i installed the firmware 3.12.1 i can not change the language. 
 I bought the printer last year and changed it to german. With the new firmares 3.12.1 and then later 3.12.2 (installed with Win11 + usb cable) i am not able to switch from english to german. If i chose german it seems that it will change it, but it ends again in the language menü until i pick english. 
-> ends in a loop, only chance to escape is to choose engish.
  
**To Reproduce**
try to change language
  
**Expected behavior**
I would expect that after choosing german, the language will change to german.
  
**G-code**
n.a.

**Comment by 3d-gussner** [comment]
@MartinD000 Please use Prusa Slicer to flash you printer.
If you still have issues please report your PrusaSlicer firmware update output log.
Try a different USB port and USB cable. Try to disconnect other USB devices and don't use a USB Hub.

**Comment by MartinD000** [comment]
@3d-gussner thank you for support, i now flashed the firmware again, using the **PrusaSlicer 2.5.0**, which can be downloaded from the Prusa homepage. **Now it works!** German language can be selected and runs without problem. 

Maybe the problem was that i used one of the alpha versions of the Slicer 2.6.0 Alpha3 or Alpha4? 
My topic is closed now, language selection works. Thanks 👍
