### ISSUE TITLE
  [ENHANCEMENT] Move printer head to top on filament runout.

### ISSUE THREAD

**Issue by mggevaer** [prusa3d/Prusa-Firmware#4083]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - [e.g. MK3S]

**Is your enhancement related to a problem? Please describe.**
When the printer runs out of filament, the head moves to the side, the cable coming from the back of the extruder can then hit large pieces being printed, potentially knocking them out of place.
You can see this in the image below.
![20230314_183342](https://user-images.githubusercontent.com/41551215/225101563-148f575e-17d3-470e-bc1d-70dc8cb9c46a.jpg)

  
**Describe the solution you'd like**
When the filament runs out, move the head to the top before moving it to the side, this will reduce the likelihood of this happening.

**Comment by 3d-gussner** [comment]
@MartijnGevaert Thanks for the request. We gonna look into that. BTW great picture to show your issue and concern about knocking off a print.

**Comment by mggevaer** [comment]
@3d-gussner I also created a ticket on the hardware repo for a hardware fix that could completely fix extruder cable drooping issues, not only reduce the odds of them on filament changes.
https://github.com/prusa3d/Original-Prusa-i3/issues/196

Printers with the hardware upgrade also wouldn't need this firmware fix, meaning there wouldn't be the potential downside of less access to the extruder on filament change when your printer is in an enclosure.

**Comment by Prusa-Support** [comment]
Thank you for your suggestion.

Probably parking the print-head to the left side will help too.
However, a well-tensed extruder cable should reduce risks of collision.

Michele Moramarco
Prusa Research
