### ISSUE TITLE
Constant beep when Mk3S/+ idles after print when temps under 10°C with 3.12.2 firmware

### ISSUE THREAD

**Issue by danchar4** [prusa3d/Prusa-Firmware#4095]
**Printer type** 
- Mk3S/Mk3S+ - original hot-end with silicone sock
- prusa thermistor tests OK

**Printer firmware version**
- 3.12.2

**SD card or USB/Octoprint**
- SDCard

**Describe the bug**
The printer is in an unheated garage and temperatures drop below 10°C overnight. If the printer finishes printing when it is cold, then a constant beep is emitted when it reaches MINTEMP.  Accompanying the beep is a blank LCD and the extruder cold-side fan spinning at full speed.

**To Reproduce**
- Upgrade firmware from 3.11.x to 3.12.2
- Run thermal model calibration
- Start a print - any print
- During print, ambient temperature drops below MINTEMP or ~10°C
- Print completes
- Once hotend cools down to MINTEMP, there is a loud continuous high-pitched tone, the LCD is blank with backlight on, and the extruder cold-side fan spins at full speed.
- Pressing reset button does NOT immediately resolve the issue. Machine resumes constant beep even after reset. Only way to stop is to shut PSU off, warm up the hotend with heatgun, and then switch it back on

-  does NOT repro on Mk2.5/2.5S with 3.12.2
-  does NOT repro with 3.11.x firmware

 
**Expected behavior**
 - MINTEMP error shown on screen _without_ audible alarm

**Workarounds**
- disable thermal model
- downgrade to 3.11.x firmware 
- keep hotend above ~15°C
- disable audible alarm

**Related issues**
- Likely the same root cause as:  #3987 and/or #3898 but my issue is with factory hotend so is perhaps a more general case

**Comment by danchar4** [comment]
Oops I missed this issue which is probably the same but on v3.12.0 firmware.  #3898

**Comment by Prusa-Support** [comment]
You are right, this is a duplicate. Thanks for reporting anyway.
Our developers are on it.

This issue will be closed as a duplicate.

Michele Moramarco
Prusa Research
