### ISSUE TITLE
[BUG] FW 3.12.2 Thermal Calibration Failed on Mk3s Revo Hotend 

### ISSUE THREAD

**Issue by alexcua** [prusa3d/Prusa-Firmware#4097]
**Printer type** - [MK3S]
**Printer firmware version** -  [3.12.2]

**SD card or USB/Octoprint**
  SD Card

**Describe the bug**
  
**To Reproduce**
 Tried to run Thermal Model Calibration
TM: Initial C est
After a few seconds, STOPPED the Print Aborted.
Tried clearing the TM error and trying again.
Same result.

All other self tests passed.

https://user-images.githubusercontent.com/11653709/226387787-6cb396df-3698-499f-87a9-1d23f44c7161.mov

**Comment by sarusani** [comment]
"Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches."

https://github.com/prusa3d/Prusa-Firmware/issues/3636

**Comment by 3d-gussner** [comment]
Thanks for your report. Please search the github issues before reporting a new issue.
Please read the release notes and [here](https://github.com/prusa3d/Prusa-Firmware/issues/3636#issuecomment-1451733927) you can find more information and how to contribute.
