### ISSUE TITLE
I need to (firmware) change 9 points of Bed Level to 4

### ISSUE THREAD

**Issue by hbougard** [prusa3d/Prusa-Firmware#4099]
Hello everybody!
total newbie here, I'm trying to revive and learn from an old Prusa MK2 

I got a little frustration because the heatbead is damage, in the middle right (around point # 6) its crashed)
I already tried to create Gcode and/or Initial Gcode so it's skips the auto level... and tried to Skipp the dagame point or center points but it keeps Overriding to 9 points...
  
So, i was wondering.
Is there a way to change From Firmware so the machine is order to bed level calibrate 4 points on corners instad of the 9 points in the 3x3 bed matrix??

Im using 3.2.3 version

I hope someone can save my life! its so hard to find heatbeds in my country :(

**Comment by 3d-gussner** [comment]
@hbougard Sorry to hear that your MK42 bed is damaged and you have issues to run the MBL. 
As MK2 isn't supported anymore please have a look around https://github.com/prusa3d/Prusa-Firmware/blob/MK2/Firmware/mesh_bed_calibration.cpp and you gonna have to compile the firmware your self.

Issue is that the MK42 bed has these calibration points at defined locations and you can't "move" them
![image](https://user-images.githubusercontent.com/25530011/226924450-19b806d5-5c46-4af6-85b5-1b42554a0ab6.png)


You can also "Ignore" the MBL gcode `G80` in PrusaSlicer profile Start Gcode section
![image](https://user-images.githubusercontent.com/25530011/226925757-553994cf-c10e-4280-8c70-69be1311cd49.png)

**Comment by Prusa-Support** [comment]
Yet an alternative could be attaching a spring steel sheet with strong paper clips along the front and rear edge - **not recommended** though.
At that point, the whole surface will be metallic, and you can possibly customize the [G80 parameters](https://help.prusa3d.com/article/prusa-specific-g-codes_112173) - again **not recommended**.

Can this issue be closed please?

Michele Moramarco
Prusa Research
