### ISSUE TITLE
Add serial speed option

### ISSUE THREAD

**Issue by pboschi** [prusa3d/Prusa-Firmware#41]
Could you please add serial speed option, in order to choose at least between 115200 and 250000?

**Comment by ghost** [comment]
I would image the max serial speed it limited by the hardware. Eg. Arduino's supported baud rates are 300, 600, 1200, 2400, 4800, 9600, 14400, 19200, 28800, 31250, 38400, 57600, and 115200. When using Octoprint 115200 is used so this seems to be the maximum.

**Comment by arekm** [comment]
@inquisitiveKangaroo Why closed?

(That pull request had noting to do with this issue)

Does anyone know if 250000 (or higher?) speed works well and reliably with prusa mk3 (and newer) hardware boards?

Higher speeds would be even more interesting than meatpack https://github.com/prusa3d/Prusa-Firmware/pull/2955

Edit: found this https://github.com/prusa3d/Prusa-Firmware/pull/184 which doesn't look promising.

**Comment by Prusa-Support** [comment]
Yeah, according to https://github.com/prusa3d/Prusa-Firmware/pull/184 it wouldn't really work well.

Michele Moramarco
Prusa Research
