### ISSUE TITLE
FW 3.12.2 seems still nt to support Hotend Revo

### ISSUE THREAD

**Issue by Momboz52** [prusa3d/Prusa-Firmware#4100]
**Printer type** - MK3S with Revo hotend
**Printer firmware version** -  3.12.2

Printing via USB/Octoprint, i.e. PrusaLink

**Describe the bug**
  TMC still doesn't work in my environment. After starting the Thermal Model Calibration it stops and says "STOPPED" then "Print aborted" although I am not printing anything but just trying to execute a TMC.
  
**To Reproduce**
  Firmware upgrade to version 3.12.2 then restart my machine.
  
**Expected behavior**
  I am expecting a normal and full Thermal Model Calibration.
  
**G-code**
  None

**Video**
  Display messages already sent to you via chat line.

**Comment by 3d-gussner** [comment]
Thanks for your report. Please search the github issues before reporting a new issue.
Please read the release notes and [here](https://github.com/prusa3d/Prusa-Firmware/issues/3636#issuecomment-1451733927) you can find more information and how to contribute.
