### ISSUE TITLE
[BUG] Checksum Error during Octopi Print

### ISSUE THREAD

**Issue by buliwyf42** [prusa3d/Prusa-Firmware#4103]
Printer type - [MK3S]
Printer firmware version - [3.12.2]

SD card or USB/Octoprint: Octoprint

A Checksum error is reported and it seems the printer requests a line again. 
After several messages like that, the print is canceled from octoprint. 
I printed the same gcode file several times before. 
  

Just print. 
  
Print without error
  
[Hase_3_3_8mm_0.3mm_PLA_MK3S_4h57m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/11039085/Hase_3_3_8mm_0.3mm_PLA_MK3S_4h57m.gcode.zip)

Here is the log from the Terminal:
[error.txt](https://github.com/prusa3d/Prusa-Firmware/files/11039108/error.txt)

**Comment by sarusani** [comment]
This normally means that there's a problem with the connection between your raspi and the printer. If you're using a USB cable, replace it and make sure it's fully plugged in. If you're using the RPI port, check that it's plugged in all the way and the soldering on all the pins is proper.

**Comment by Prusa-Support** [comment]
Thanks for reaching out to us.

> This normally means that there's a problem with the connection between your raspi and the printer. If you're using a USB cable, replace it and make sure it's fully plugged in. If you're using the RPI port, check that it's plugged in all the way and the soldering on all the pins is proper.

These are actually good pieces of advice.
Was it helpful?

Besides this, is the issue actually related to the most recent firmware version?
Please try downgrading the firmware to see if the problem persists.
If it persists, please also give it a try with a factory reset of the printer's Einsy board, and try re-flashing Octoprint on the external board.

We can't even exclude a problem specific to the board (Raspberry?), or Octoprint software.
The vendor may be able to assist you with the board, and [Octoprint](https://octoprint.org/)'s community may have further recommended troubleshooting steps to share.
Please keep us posted.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
Is this issue still relevant?

This issue may be closed as stale in a few weeks
We would like to hear back from you.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
This issue will be closed as stale.

Please return to us if you can confirm a firmware bug after reviewing all the above.
We would also appreciate hearing back from you even in the case you identified and solved the problem.

Michele Moramarco
Prusa Research
