### ISSUE TITLE
Does the PID calibration routine assume temp < target?

### ISSUE THREAD

**Issue by tkircher** [prusa3d/Prusa-Firmware#4116]
Prusa MK2.5S, latest firmware (v3.12.2)

I changed out the nozzle and ran a print, then realized I should have tuned PID. So I navigated to PID calibration and started it, with the nozzle still at 220C. Got a thermal runaway error and a very loud continuous E-stop beep. Waited until the temperature had dropped to 180C and then started PID tuning again, which ran successfully this time. Tried preheating to 220C again and ran PID calibration, same thermal runaway error. Seems like the PID routine does not check the temperature before it starts?

**Comment by Prusa-Support** [comment]
Thanks for your message.

As far as I know, the starting temperature is not relevant but it would normally start below the target temperature and cross the target temperature in 5 heating cycles, aiming to reduce temperature fluctuations.
https://help.prusa3d.com/article/pid-tuning_2265
Not sure if starting with the nozzle temperature above the target temperature could be problematic. Was this the case?

The _thermal runaway_ error instead will occur if the temperature drops by 15°C (or more) and doesn't recover within 45 seconds.
https://help.prusa3d.com/article/thermal-runaway-i3-series_2131

It may seem like the thermistor or the heater is not working correctly after all.

**Recommended test.**
Set a nozzle temperature of 250°C (settings > temperature) and check how much time the nozzle will take to reach the target temperature. Please start at room temperature (<30°C) and unload the filament to prevent clogs during the test.
If the nozzle doesn't reach the target temperature within 100'', please promptly abort (the thermistor or the heater doesn't work reliably). In normal conditions, the nozzle heater is expected not to reach this target in more 80''-90'', much faster could be consider an anomaly ([multimeter](https://help.prusa3d.com/article/multimeter-usage_2117) testing recommended).
Once at target temperature, slide the extruder along the axis, also gently wiggle the cables behind every few centimeters. Move slowly and observe the temperatures on the LCD.
Will the temperature change over the movements? If so is the temperature change sudden (partially damaged thermistor) or gradual (partially damaged thermistor)?

Michele Moramarco
Prusa Research

**Comment by tkircher** [comment]
No, everything works perfectly otherwise.

**Comment by Prusa-Support** [comment]
So all in all, starting the PID tuning above the PID tuning target temperature may lead to a failure - which is kind of understandable -  but, apparently with problematic consequences.

Thanks for the heads up. This may be an inspiration for future improvements.

Michele Moramarco
Prusa Research
