### ISSUE TITLE
Printer not pausing on adding pause/sign detected 

### ISSUE THREAD

**Issue by DragonDon** [prusa3d/Prusa-Firmware#4118]
I decided to try two-colour printing and following the “this looks like a sign” prompt.  

 I got notified that the printer had stopped but I could still hear it running. Indeed it was when  went to it. 

I am using OctoPrint. All plugins/base OS is up to date.  Printer Firmware is not updated due to language bug in update.  

I think the pause should have been at z 2.6 but  the code shows the m600 at z 2.2. 

Related specs

E5P
- firmware v 1.70.2 BL 

PrusaSlicer
- 2.5.0

OctoPrint
- v1.8.7

OctoPi
- v 0.18.0

RaspberryPi
- 3 Model Plus Rev 3

GCode Generated

https://pastebin.com/Cxy73Yqq

Please ask if there are other details I can add to troubleshoot this.

**Comment by plampix** [comment]
This sounds like it's an issue with your (non-prusa!) firmware. Please make sure it actually supports M600.

**Comment by DragonDon** [comment]
After some digging around, this seems now to be the likely case.  Thanks.
