### ISSUE TITLE
[BUG]MK3s+ will not complete z calibration.

### ISSUE THREAD

**Issue by wisonlau** [prusa3d/Prusa-Firmware#4121]
**Printer type** - MK3S+
**Printer firmware version** -  3.12.2

**MMU upgrade** - no
**MMU upgrade firmware version** - not applicable

**SD card or USB/Octoprint**
SD card

**Describe the bug**
The Z calibration wizard stops when the nozzle drops to the bed. "Calibration failed! Check the axes and run again." I have done the temp model calibration.
  
**To Reproduce**
I select z calibration on the LCD.
  
**Expected behavior**
I expected the nozzle to drop to the bed and begin its calibration process.

**Video**
> http://43.132.168.109/93_1680357690.mp4

**Same question**
https://github.com/prusa3d/Prusa-Firmware/issues/4039#issuecomment-1492965895

**Comment by michael-borck** [comment]
Video suggest some z-binding towards the top.   Try removing the bearings for the z-axis lead screws and see if you still have the problem.

**Comment by 3d-gussner** [comment]
@wisonlau You have a highly modified printer (BTW looks nice).
As @michael-borck mentioned above, I also can hear at 4:10 min that something is binding up during the lift, which the firmware (TMC feedback) interprets as reached the top. Also at 6:30 where you move it to 210 I can hear some resistance. 
As the distance is smaller than the expected 210ish mm it fails.
  
Please ensure that the Z motion is smooth.
- Try to remove the lead screw top bearings, restrain these cause more issues than it helps. The Z rods ensure the correct motion.   
- Check the POM nuts are running smoothly
  - I always slightly un-tighten the screws before putting the X gantry on the Z lead screws
  - Move several times up and down so the POM nuts align themself to the lead screws and then tighten these
- Also try to collect the serial output during the wizard or calibration, this can help to find the issue.

This is not a BUG it is a hardware issue, please consider to close this issue.

I also saw the REVO nozzles so please check out https://github.com/prusa3d/Prusa-Firmware/issues/4105 and if you can provide some logfiles.

**Comment by wisonlau** [comment]
Thank you, it's this issue that caused it.
