### ISSUE TITLE
[BUG]MK3 PAT9125 sensor not recognized

### ISSUE THREAD

**Issue by emard** [prusa3d/Prusa-Firmware#4126]
on MK3 filament sensor PAT9125 is not longer
recognized as filament presence source however
its hardware readings are ok, seen in
support->sensor info

happened somewhere between v7089 and v7122

**Comment by leptun** [comment]
is it autoload, runout or jam detection that isn't working?

**Comment by emard** [comment]
printer "thinks" as no filament present, it constantly
asks to replace filament.

in Support->Sensor info there is only line
PINDA: 0/1
this line was at v7089, I tried v7122 and v7174
now this line is missing:
Fil.Sensor: 0/1

Next lines seem ok
B: 80   Xd: 0
S: 17   Yd: 20102

when I remove or insert filament they change correctly

**Comment by leptun** [comment]
Oke. I'll check that issue out soon. Fixing now other worse bugs that were introduced in the latest merging spree (which you might have also noticed).

**Comment by emard** [comment]
Yes :) I noticed knob press clicks but doesn't enter SD directory,
some obvious bug, should be fixed soon or already it is

**Comment by leptun** [comment]
Didn't know about that one. Adding it to the list now :)

- [x] LCD knob rotation
- [x] Factory reset menu overwritten
- [x] Settings menu corruption
- [x] PAT9125 thinks no filament is present
- [x] SD menu click issue

**Comment by gudnimg** [comment]
> Yes :) I noticed knob press clicks but doesn't enter SD directory,
some obvious bug, should be fixed soon or already it is

It may be something is consuming the button event too soon.

Does the SD directory work if you rotate the knob? If so that indicates a problem with `lcd_draw_update`. Should always be set if either clicked or rotated.

**Comment by emard** [comment]
When I click 2nd time on the SD directory it enters it,
but then when I try to print file.gcode, no matter how
much I click knob, it won't start printing.
