### ISSUE TITLE
MK3 Statistics are invalid. all firmwares including 3.1.1 b143 RC4

### ISSUE THREAD

**Issue by cnlson** [prusa3d/Prusa-Firmware#414]
In my case it appears that both the time and amount of filament are invalid. for others it was just the filament. Also Fail stats do not count the number of filament fails, either from cuts running out of filament or from extruder skipped steps

![20180112_152910](https://user-images.githubusercontent.com/1442027/35059934-743e702a-fb82-11e7-9ff4-df38699ff1f8.jpg)

forum threads 
https://shop.prusa3d.com/forum/original-prusa-i3-mk3-f30/crazy-statistics-my-printer-thinks-i-ve-printed-75-t13570.html

https://shop.prusa3d.com/forum/original-prusa-i3-mk3-f30/statistics-error--t13432.html

**Comment by camlesom** [comment]
Have you tried the new [3.1.1 RC5 release](https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.1.1-RC5)? It says in the release notes that they fixed the failed stats.

**Comment by cnlson** [comment]
i'll check it. likely this can be closed
