### ISSUE TITLE
MK3 RESET if folder structure is to long

### ISSUE THREAD

**Issue by Richardgriff** [prusa3d/Prusa-Firmware#416]
I have installed 3.1.1 RC5 on my MK3 tonight and have noticed the following issue

I have the attached G code within the following folder structure

\MK3\Torque Drivers\PETG\0.5 NM\Torque_Capall.gcode

When i try to tun this gcode the printer resets

if i move the Torque_Capall.gcode to the following location the gcode executes.

\MK3\Torque_Capall.gcode

i suspect there maybe and issue with the length of the folder structure or i have the gcode nested down to many levels.

[Torque_CapAll.zip](https://github.com/prusa3d/Prusa-Firmware/files/1640647/Torque_CapAll.zip)

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete.

Marina Curzi
Prusa Research
