### ISSUE TITLE
Unpredictable axis move after Selftest on 3.0.10 RC1

### ISSUE THREAD

**Issue by ChrisP-Git** [prusa3d/Prusa-Firmware#42]
On the 3.0.10 RC1, if I try to move Z axis just after SelfTest, the result is unpredictable, X and Y axis movement are triggered as well. 

Once these X&Y axis move stopped, everything seems to behave as intended.

**Comment by PavelSindler** [comment]
Thank you for reporting this. It will be fixed in next commit.

**Comment by PavelSindler** [comment]
It has been fixed in https://github.com/prusa3d/Prusa-Firmware/commit/5a584d947a682c7587ec2b55ddcd351e3bfabe2e
