### ISSUE TITLE
MK3 PINDA2 Wild Random Reading

### ISSUE THREAD

**Issue by TheZeroBeast** [prusa3d/Prusa-Firmware#421]
I think I may have stumbled upon an issue that occurred when running the Build150 firmware PINDA2 Calibration resulting in a z-offset of **32.725mm** which could have led to the nozzle being run into the bed.

After some investigation I have found that it occurs when a negative z-offset is read in calibration. The float that is saved to EEPROM isn't read with the small negative offset resulting in this error.
I have done a lot of tweaking and testing to streamline the calibration that I will submit in a pull request if you would like to review and use any changes to make the firmware better.

![pinda2 test errors](https://user-images.githubusercontent.com/20939095/35193139-5bca816c-feea-11e7-8813-f873e5563c4e.png)

Data from my Calibration tests and notes on changes tried and their results.
[PRUSA MK3 PINDA2 Investigation.pdf](https://github.com/prusa3d/Prusa-Firmware/files/1649671/PRUSA.MK3.PINDA2.Investigation.pdf)

Rob

**Comment by jettoblack** [comment]
I was having this problem and it was completely preventing me from being able to print using b150 RC5 firmware (thought maybe my PINDA was defective), but TZB's firmware fix worked for me and now I can print again.  I hope you will consider merging his pull request into the next release!

Please see this thread for pictures and more details:
https://shop.prusa3d.com/forum/original-prusa-i3-mk3-f30/live-z-huge-variance-over-the-bed-bad-pinda-or--t13889.html

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete.

Marina Curzi
Prusa Research
