### ISSUE TITLE
[QUESTION]<How is FW_COMMIT_NR defined>

### ISSUE THREAD

**Issue by easonjim** [prusa3d/Prusa-Firmware#4211]
Dear,
  How is FW_COMMIT_NR defined? Random characters? Or an incremental algorithm?

thank you.

**Comment by leptun** [comment]
It is the number of commits in the tree of that git branch. It is automatically computed when building with cmake. Every commit that we make increments that number by one. A merge commit also increments it by one. Hope this helps.
@3d-gussner should know more details about this.

**Comment by easonjim** [comment]
@leptun thanks, I found this file: ProjectVersion.cmake，inside there is build_number.

**Comment by 3d-gussner** [comment]
@easonjim At this moment the build number (which is based on git hub commit) isn't updated with cmake. We are working on that for the final firmware release. 
The official build server subtracts at this moment some commits. So a github commit 7313 results in 6816.

`PF-build.sh` one the other hand always uses the github commit number as FW_COMMIT_NR and this is also shown in the LCD Support.

**Comment by easonjim** [comment]
@3d-gussner thanks，I got it.
