### ISSUE TITLE
[FEATURE REQUEST] Option to CANCEL filament change (in case of blockage)

### ISSUE THREAD

**Issue by Cyberman-tM** [prusa3d/Prusa-Firmware#4218]
Prusa Mk3S+

Just had it happen - somethings blocked when I tried to replace the runout filament.
None of the options are of any use, had to turn off the printer to get out of the menu. Just continuing only means more grinding.

What's needed is an option to cancel the filament change, maybe even cancel the whole print. It should happen rarely, but it does.

**Comment by Prusa-Support** [comment]
Thanks for your suggestion.

If you don't mind canceling the print, you can promptly hit the reset button - if the hotend is clogged, the print probably failed too.

Our developers will make their considerations about the feature request.

Michele Moramarco
Prusa Research
