### ISSUE TITLE
FW 3.12.2 Thermal Anomaly

### ISSUE THREAD

**Issue by KimA998** [prusa3d/Prusa-Firmware#4227]
Printer MK3S+
FW 3.12.2-5713

MMU2S
MMU FW 1.0.6

Via USB/Octoprint

**Describe the bug**
When doing tool change at a layer height in PrusaSlicer (2.6.0-alpha6) I get Thermal Anomaly Just before and after the wiping. 
The alert comes when I make "old fashion way" color change at layer height in a single object with only one part (I slice with MMU settings to select one of the five tools).
If I do real MMU tools changes in an object with multiple parts and select each part and give a specific color - NO Thermal Anomaly comes.
  
**To Reproduce**
  Every time I use the  "Old way" to change color, as described above, I get Thermal Anomaly Alert. I have now reproduced the alerts three times.
If I print in MMU single mode - NO alerts.
  
**Expected behavior**
It seems the FW has a problem when changing filament with two different temperature settings. In my example I started the first 20 layers with Your original Prusament PETG Prusa Orange and for the rest layers a 3DEksperten PETG. Your PETG runs at 230 and I print 3DEksperten PETG at 240 degrees. And the alerts only comes just before and after tools changes.

When the alerts came I checked all my step motors and no one was hot - only the MMU idler motor was hotter but I could still hold my hand on it. When checking the LCD hot end and heat bed Target and real temperatures where correct.
  
**G-code**
  Please attach a G-code. This will make it easier for us to replicate the error.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by Burtronix-Fab** [comment]
Similar issue:

Printer MK3S
FW 3.12.2-5713

Describe the bug:
I hadn't used the MK3S for more than a year (used Mini instead). Upgraded firmware, ran the thermal calibration, printed a couple PETG signage models (low profile, under 1.5mm). No problem.

Tried to print a couple single-color PLA models, roughly 40mm tall. Multiple thermal failures at random layers roughly 10-20mm. Ran the thermal calibration again with the same results.
