### ISSUE TITLE
[FEATURE REQUEST] Add a filament drying mode for heat bed

### ISSUE THREAD

**Issue by amatulic** [prusa3d/Prusa-Firmware#4232]
[This YouTube video](https://www.youtube.com/watch?v=WC3jvuq-uq8) explains how to use the heat bed and a cardboard filament box as an effective, zero-cost filament dryer. It makes perfect sense; the heat bed can maintain a stable low temperature and the box with a few holes provides the enclosure and convection needed to pull the moisture away.

I just tried it with my MK3S. With a spool of moisture-contaminated Prusament PETG in the box on the build plate, I went into Settings, set the bed temperature to 50°C, and it worked fine until the "safety timer" shut it down.

In looking for a way to disable the safety timer, I came across issue #3778, which is closed, but unrelated to the use case of using the heat bed as a controlled-temperature filament dehydrator.

I also came across #1347, which says I can use `M86 S0` to disable the safety timer, but I would need to hook up a laptop to the printer via Octoprint to do this. I *could* do that, but I'd rather see:
* An option on the front panel to disable the safety timer **only** for the heat bed, OR
* A "filament dryer" mode available in the front panel menu, with presets for PLA, PETG, ABS, etc, and a duration.

Edit: I always print from the SD card. I don't use Octoprint. I know I could store a g-code file on the SD card with the command to disable the safety timer, but it would be nice to have a filament drying mode built into the firmware somehow. I understand that Bambu did this with their printer.

**Comment by sarusani** [comment]
You can create a file with the gcode you want to run and run it from your card, no octoprint needed.

Create a new file, for example "disableSafetyTimer.gcode"
Edit the file and add M86 S0. Copy it to your SD Card and just run it like you would with a print.

**Comment by cinmay** [comment]
I'm currently trying out the gcode from this model. I had to modify it a little but it seems to be working fine. 
https://www.printables.com/model/135985-diy-print-bed-filament-dryer

I agree in general that it would be cool to have drying mode just built inn to the firmware though.

**Comment by Prusa-Support** [comment]
Thanks for sharing your ideas.

Our developers will look into this.

However, I noticed the Prusament spool was placed on a 50°C source of heat.
Please be advised that the black Prusament spool's sides may separate from the core if placed on such a hot hatbed for some time. For more information please check the ['Drying filament' Help article](https://help.prusa3d.com/article/drying-filament_332086).

Michele Moramarco
Prusa Research

**Comment by amatulic** [comment]
Issues become stale and auto-closed because Prusa is understaffed? It should remain an open issue until a PrusaSlicer developer deliberately closes it based on sound judgment or team discussion, not a bot-determined age. In all my previous jobs, issues could remain open for years if they were considered desirable to have but low priority.

There are also over 100 unresolved pull requests in the queue, some years old, and some of which have comments that suggest high community demand. Do they also get auto-closed due to being stale?

**Comment by 3d-gussner** [comment]
@amatulic Thanks for interact here and look at auto stale issues.
We introduced the stale bot as many tickets have not been updated for long time by owners or outdated.
  
This feature request may be something for some people but most will not use it. The SD card gcode is a good solution without using of additional resources in the firmware.

Disabling safety timers in the firmware are a sensitive topic and chances are slim to none that something like this will make it into the firmware.

Especially if there is a "controlled" and wanted way to achieve the result by a gcode file pointed out by https://github.com/prusa3d/Prusa-Firmware/issues/4232#issuecomment-1576512050

**Comment by 3d-gussner** [comment]
>There are also over 100 unresolved pull requests in the queue, some years old, and some of which have comments that suggest high community demand. Do they also get auto-closed due to being stale?

We don't stale bot any PRs but in the last months we started to look more into the community PRs. You can see that even very old community PRs have been merged in different releases.
There are [38 PRs without a milestone](https://github.com/prusa3d/Prusa-Firmware/pulls?q=is%3Aopen+is%3Apr+no%3Amilestone)  and we gonna look into these. Some of the PRs just not have been merged or reviewed due to resource shortages.
Lately we were able to reclaim some resources BUT still we fight for every byte used by PRs and some are higher in the priority queue than others.

Hope that explains a bit the current situation with the PRs.

Which are the `high community demand` PRs you are referring to?

**Comment by amatulic** [comment]
>  may be something for some people but most will not use it.

I created this request because it was my understanding that Bambu Labs already has this feature built into their firmware. Whether people use it or not, from a business perspective it would make sense to meet or exceed the features available in competing products.

Regarding my comment about pull requests: Apologies, I got confused between this repo and the PrusaSlicer repo, which has a huge backlog of PRs. I totally understand the resource constraints you must be facing for firmware.

**Comment by 3d-gussner** [comment]
@amatulic NP about the PR queue.
As said disabling the safety features in Firmware isn't something we will do.

Even if the competition has a feature it doesn't mean that we NEED to have it as well, if that isn't considered "safe" in our view.

The SD gcode is a set of instructions which doesn't compromise the safety and is very variable to change for different needs and setups.

It would be possible to add this feature using the gcode BUT it would use quite a lot of resources which are very limited on this 8-bit ATmel Mega 2560
- It would need a new LCD menu with multiple presets
- Also setting temps and duration are on LCD

If somebody from the community is willing to create a PR for that (with very low resources costs), I am more than happy to review it and start the internal discussion if we could merge/implement it.  Of course NO compromise of the default safety features would be allowed. 

I would love to be able to get as many features as possible requested from the community into the firmware, but we need to be very careful with the resources.
We managed to get some of these into the firmware and glad that the PR owners were willing to revive old PRs. It will continue and every feature request and PR will be reviewed. It only may not happen instantly and some we gonna need to turn down.

Thanks again for your request and interacting on Github.

**Comment by amatulic** [comment]
Thanks for your consideration and explanation of the issues involved. Based on that, and the fact that there is a workaround, it would be best to close this request.

**Comment by 3d-gussner** [comment]
@amatulic As you are the owner of the ticket, please consider to close it yourself. For me it "feels" better when WE don't close issue but the owner after discussing the topic.

**Comment by amatulic** [comment]
In my last message, I selected "Close as not planned" but I didn't see that it closed. Trying again.

**Comment by amatulic** [comment]
The "wontfix" tag got added, that's all. I don't see that this ticket is closed. Selecting "Closed as completed" this time.
