### ISSUE TITLE
  [ENHANCEMENT] change order of points in mesh bed leveling to spiral

### ISSUE THREAD

**Issue by KubaMiszcz** [prusa3d/Prusa-Firmware#4234]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MK3S+, MK3, MK2.5S, MK2.5, MK2S, MK2

**Is your enhancement related to a problem? Please describe.**
change order of point to spiral like this:
![image](https://github.com/prusa3d/Prusa-Firmware/assets/18091038/ada81ab1-da52-4d9d-8d5f-1d9908ca30b8)

summary path now=8+2.82=10.82a
spiral=9.41a

**Comment by leptun** [comment]
While this would result in marginally faster mesh bed leveling, it has to be considered that not only 3x3 MBL is supported, but also 7x7. A spiral approach could be applied also to that.
Personally, I don't really see a reason to make it a spiral. It doesn't really save that much time and it would just make the code in G80 more flash expensive, something we don't really afford on the 8 bit platform.

Something that might be of interest is this PR I am preparing for 3.14: #4183.
What this does is that it only probes the bed in the area where the print will be, so it should be considerably quicker.
Here is an example of it in action. The number of points probed increases or decreases as needed. In the video it performs a small 3x3 mesh in the center of the bed.

https://user-images.githubusercontent.com/17808203/236611576-491db0dd-bd9f-49e0-aa0d-96ef5c3dd046.MOV

**Comment by KubaMiszcz** [comment]
maybe, but it is easy to implement
both versions has 9 commands, differs only in arguments (coords), it's not a big deal but but when easy to implement it is worth of it even if it reduce time by 1.41*timeBetweenPoints (~1s ?) = 1.41s

in 7x7 difference is even bigger (assume 1s between points):
time now = 56.46s, number of commands=49
spiral = 52.23s, number of commands=49

feature you show is also really cool, will it work on prusa mk3s+? i saw it on clip abaout MK4, is it available in new firmware alpha version?
