### ISSUE TITLE
[BUG] MK4 Screen turning off/flickering at random times

### ISSUE THREAD

**Issue by HaWiWe** [prusa3d/Prusa-Firmware#4267]
**Printer type** - [e.g. MK3S, MK3, MK2.5S, MK2.5, MK2S, MK2]
MK4

**Printer firmware version** -  [e.g. 3.8.1, 3.8.1-RC1, ...]
5.0.0-alpha3 Firmware for Original Prusa MK4

**SD card or USB/Octoprint**
USB

**Describe the bug**
The screen of my new MK4 often turns off in the middle of prints (but not always), the print will finish but the screen either turns black, partially turns black/white or shows the wrong colours. It's basically all of the behaviour found in this thread: https://forum.prusa3d.com/forum/english-forum-original-prusa-i3-mk4-assembly-and-first-prints-troubleshooting/mk4-screen-goes-blank-after-some-time/

I do use the newest alpha firmware, since this was a proposed fix, so this can't be it. I also checked all the cables and made sure they were seated right. I linked a video of the problem. I'd be happy to get some pointers as to what is really causing the problem.
  
**To Reproduce**
There is no way to reproduce it since it happens at random times.
  
**Expected behavior**
The screen should not turn off/show wrong colours.

**Link to a video of the problem**
https://youtu.be/2D3mrdGKFMA

**Comment by gudnimg** [comment]
FYI MK4 repository is located here https://github.com/prusa3d/Prusa-Firmware-Buddy

This repository is only for the 8-bit printers.

**Comment by HaWiWe** [comment]
Thanks for the information, I followed the link from the official post: https://forum.prusa3d.com/forum/input-shaping/5-0-0-alpha3-firmware-for-original-prusa-mk4/. They have it wrong themselves then. 😑

**Comment by 3Delights** [comment]
**FYI**: I've fixed the link on the forum.
