### ISSUE TITLE
statistics during print invalid rc5 150 firmware. 

### ISSUE THREAD

**Issue by cnlson** [prusa3d/Prusa-Firmware#429]
if you have a print which exceeds 10 hours things get strange. 
this may also affect the overall statistics, i;m not sure

First, the picture of the front showing right around 11 hrs of printing
next various peeks at the statistics in the menu for the print showing 50 hrs 99 minutes 99 seconds

FYI all pictures are in chronological order, so yes it did wrap from 99 minutes 43 seconds to 00 minutes 97 seconds.

![20180122_201510](https://user-images.githubusercontent.com/1442027/35254906-f8687f8e-ffb1-11e7-948e-56551dea3fe5.jpg)
![20180122_201525](https://user-images.githubusercontent.com/1442027/35254907-f894a348-ffb1-11e7-9a1f-b130e041280d.jpg)
![20180122_201559](https://user-images.githubusercontent.com/1442027/35254908-f8b08338-ffb1-11e7-8f8e-5ad10b39bdea.jpg)
![20180122_201748](https://user-images.githubusercontent.com/1442027/35254909-f8c8d46a-ffb1-11e7-9ec9-0f06bc04c44d.jpg)
![20180122_201802](https://user-images.githubusercontent.com/1442027/35254910-f91f704a-ffb1-11e7-9ba8-54cb05bcfef8.jpg)

**Comment by cnlson** [comment]
a few hours later....
![20180122_231704](https://user-images.githubusercontent.com/1442027/35259388-3a91797e-ffcb-11e7-81fc-541455300ace.jpg)
![20180122_231715](https://user-images.githubusercontent.com/1442027/35259389-3a9ffa30-ffcb-11e7-9c08-d979f02749df.jpg)

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete.

Marina Curzi
Prusa Research
