### ISSUE TITLE
Have "Unload filament" reshape plug at end of filament before unloading

### ISSUE THREAD

**Issue by ceryen** [prusa3d/Prusa-Firmware#43]
When unloading filament, there is sometimes a plug at the end of the filament that prevents the filament from being pulled through the hole at the top of the extruder body.  Would it be possible to have the "Unload filament" function briefly push the filament through the hotend to reshape the plug at the end of the filament before unloading the filament?  This would also need to be added to the M600 filament change function.

**Comment by joeynuggetz** [comment]
Do you end your print jobs with an extraction? Only issue I've ever had with unloading is the melted strand that remains when you pull it out which loves to tangle itself in the fan.

**Comment by ceryen** [comment]
No, I rarely end print jobs with extraction.  I typically get plugs when I've had the printer off for some time, then I preheat specifically to unload the filament.

**Comment by bubnikv** [comment]
I am sure it does not quite answer the original issue, but I am usually
pulling the filament by hand using the atomic method:
http://support.3dverkstan.se/article/10-the

It has the benefit of cleaning the nozzle at each cold pull.

**Comment by sylphio** [comment]
My 10 cents. On my mk3, i got a blob 100% of time (unchanged prusa setting PLA/PTEG) and it jam at top extruder body hole. The only way to get a proper unload on my printer is to extrude 20mm before unloading.  So, in my case, this can be a game-changer in term of reliability.

**Comment by inquisitiveKangaroo** [comment]
Extraction speeds were tuned in newer firmware versions. Also the ramming feature was adden into the slicer PE for MM prints.
