### ISSUE TITLE
  [ENHANCEMENT] Add "Thermal Modelling Debug" option to "Experimental Menu" in the printer.

### ISSUE THREAD

**Issue by ggppjj** [prusa3d/Prusa-Firmware#4303]
**Printer type** - All with Thermal Modelling
**MMU Upgrade** - N/A

**Is your enhancement related to a problem? Please describe.**
  Currently, Thermal Modelling is arguably difficult to disable for people that have non-stock hotends, and even more arguably not quite ready after a few revisions for the non-stock hotend that Prusa is targeting (Revo). It's not like it's crazy difficult or anything, but it does feel like the experience is lacking polish. 
  
**Describe the solution you'd like**
  There is an "[Experimental Menu](https://help.prusa3d.com/article/experimental-menu-mk3-s-_161213)" in the printer that is "capable of adjusting the defining parameters of some components", which I believe should include being able to debug and/or disable Thermal Modelling. Ideally, the setting would exist to disable or quieten the thermal modelling beeping, add some additional debug tools for TM that might help support debug issues with TM (logging to SD or similar if that is possible, a standard routine that could be run and the results of that saved for devs to inspect or similar), and/or allow the user to disable TM from this advanced menu. Preferably, an option to disable TM until the next firmware version would be available here.

**Comment by mix579** [comment]
+1 as I strongly believe this TM was at best released too soon, or worse, is fundamentally flawed.

**Comment by Patrick-Schmitt** [comment]
+1 but yes, it works currently with my Revo, but would appreciate more control over TM.

**Comment by gbzh01** [comment]
I am having 6 printers with Revos and none of them work for the TM

**Comment by ggppjj** [comment]
@gbzh01 please comment in issue #4288.
