### ISSUE TITLE
[BUG] The Action of new folder inside Prusalink doesn't work

### ISSUE THREAD

**Issue by justoeu** [prusa3d/Prusa-Firmware#4320]
**Printer type** 
MK4

**Printer firmware version** 
4.7.2

**SD card or USB/Octoprint**
USB CARD

**Describe the bug and Reproduce**
This Bug is simple to reproduce, Inside the PrusaLink, access the storage click in add new folder, input new name and waiting... This process its not work.

<img width="1717" alt="Screenshot 2023-08-07 at 13 24 15" src="https://github.com/prusa3d/Prusa-Firmware/assets/304801/857d87fc-aaf3-4876-b459-236e796608f1">

**Comment by 3d-gussner** [comment]
@justoeu This repository is for the 8-bit MK3/S/+ and MK2.5/S printers. Please close your issue here and open a new one in https://github.com/prusa3d/Prusa-Firmware-Buddy which is for the 32-bit printers like Mini, MK4 and XL.

**Comment by justoeu** [comment]
This Bug is incorrect to this firmware
