### ISSUE TITLE
[BUG] Mk3S+ with MMU3 not re-heating after safety timer

### ISSUE THREAD

**Issue by stepikovo** [prusa3d/Prusa-Firmware#4324]
**Printer type**
Mk3S+
**Printer firmware version**
3.13.0

**MMU upgrade**
MMU3
**MMU upgrade firmware version** 
3.0.0

**SD card or USB/Octoprint** 
PrusaLink 0.7.0

**Describe the bug**
 The printer detected a crash, repeatedly, so it paused. After confirming I didn't want to continue with the print, the MMU tried to pull the filament out of the nozzle, as with any other end of the print, however, the nozzle was cold at this point (30 min safety timer) yet the printer ignored that and never reheated the nozzle so the MMU triggered an error - filament in Finda.
 The only way out of this was restarting the printer as the LCD menu is not accessible through the MMU's error message.
  
**To Reproduce**
  Trigger the 30-minute safety timer where the filament is still in the nozzle (so not after filament runout for example).
  
**Expected behaviour**
The printer should re-heat the nozzle before any following action.
  
**G-code**
The issue is not G-code relevant.

**Comment by gudnimg** [comment]
This is related to https://github.com/prusa3d/Prusa-Firmware/pull/4207 it looks like to me when USB printing, canceling the print here doesn't actually stop the print on the printer side. This can certainly be improved.

Probably not new in 3.13.0
