### ISSUE TITLE
MMU2 not homing after resent firm wear update. 

### ISSUE THREAD

**Issue by HayHay7274** [prusa3d/Prusa-Firmware#4345]
Please, before you create a new question, please make sure you searched in open and closed issues and couldn't find anything that matches.

**What is your question?**

**Comment by 3d-gussner** [comment]
@HayHay7274 Thanks, but we have already an open ticket (searched idler in github issues) https://github.com/prusa3d/Prusa-Firmware/issues/4285
Please read the comments there.

Closing it.

**Comment by HayHay7274** [comment]
Thank you.
I'm new to 3D printing and I don't know how and where to change or even find this stuff that is being talked about can someone help, please?
