### ISSUE TITLE
  [ENHANCEMENT] MMU3 - Keep MMU3 L/R buttons active during error conditions

### ISSUE THREAD

**Issue by happykatz** [prusa3d/Prusa-Firmware#4350]
**Printer type** - MKS3+
**MMU Upgrade** - MMU3

**Is your enhancement related to a problem? Please describe.**
During an error condition, only the middle button of the MMU3 is active. The left / right buttons are disabled.

This is an issue when filament jams in the selector. I'd like to be able to move the selector aside to a "neutral" position on the far right, where I can cut the jammed filament, remove the blade cover, and remove the filament remnants prior to rehoming.

Without the option to move the selector with the buttons, I must adjust it by manually rotating the selector motor, which I would prefer not to do. My other choice is to select "retry" from the interface, which will only cause the selector to re-home, dragging the stuck filament with it and compounding the problem.
  
**Describe the solution you'd like**
Enable the left / right buttons on the MMU3 during error conditions.

**Comment by DRracer** [comment]
@happykatz once we free up some space, we'll add an option to move the selector aside to allow easier access to the unit. We have this item on our list already.
