### ISSUE TITLE
[BUG] MMU3 - Intermittent failure to re-home on error recovery

### ISSUE THREAD

**Issue by happykatz** [prusa3d/Prusa-Firmware#4351]
**Printer type** - MK3S+
**Printer firmware version** -  3.13.0

**MMU upgrade** -MMU3
**MMU upgrade firmware version** - 3.0.0

**SD card or USB/Octoprint**
USB/Octoprint

**Describe the bug**
I recently received my MMU3, which is replacing my old MMU2S on my MK3S+. I have successfully built the device and installed it, and have successfully completed the Sheep print with PLA. All of my equipment is stock, including the (much improved!!) filament buffer.

I am using the [rotating rings toy ](https://www.printables.com/model/7876-rotating-rings-toy) with Prusament and Overture PETG as my test print (gcode attached). I chose this object because it has multiple tool changes on each layer, for a total of 360+ tool changes, which makes it a good stress test. At this point, I am experiencing failure on average every 200 tool changes or so - with this print, I will have 1-2 load failures.

The load failures are all the same: the filament will form a string which then gets jammed in the selector as the selector moves, preventing the filament from loading properly. The selector will then try to re-home as a part of its recovery process, dragging the stuck filament with it (see pics). I will then:
1) Manually rotate the selector motor so that it is on the far right hand side (NOTE: the left and right buttons on the MMU are disabled during failure states, so manual rotation is the only option.)
2) Open the MMU by loosening the tension screws on either side of the device
3) Remove the cover for the blades on the selector
4) Cut the filament and remove any filament that remains in the selector
5) Select "retry" from the interface, and allow the selector to re-home and reload the filament.
Most of the time, the system then recovers and can continue.

Twice, however, the selector does not re-home after step 5) above, meaning that the selector will remain on the far right side, while the chosen filament is reloading into the air. In this case, the print is not recoverable, and I must reset the printer and start again, as from the error screen I cannot access any other function of the menu.
  
**To Reproduce**
NOTE: This error is intermittent, and will not always occur under these conditions.
 1) Wait for filament to jam.
 2) Recover filament jam as described above.
 3) Select "retry" from the interface.
If the error occurs, the selector will not re-home, but the filament to be loaded will load anyway into the air.
  
**Expected behavior**
 The selector should re-home, and the print proceed as normal.
  
**G-code**
[3_Cool_PETG_Rotating Rings Toy_0.4n_0.2mm_PETG,PETG,PETG,PETG,PETG_MK3SMMU3_13h56m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/12448487/3_Cool_PETG_Rotating.Rings.Toy_0.4n_0.2mm_PETG.PETG.PETG.PETG.PETG_MK3SMMU3_13h56m.gcode.zip)

**Pics**
NOTE: I don't have a clear pic of the green filament "air loading", but you would see this right after the manual selector position pic, and the correct LED for the green filament would be lit.

![buildplate](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/7b7a0a1e-ff7d-462e-8435-fd37dac9a131)
![errorcode](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/7c8788a0-e1f0-4060-91b4-2285dc67a069)
![filamentjam](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/3e6057e0-b794-4a95-8233-a25166af8a2b)
![jammedfilament_tip](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/e1a2b162-d50b-4072-9fff-063ef424e75e)
![manual selector position](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/ce695f4d-ebc7-4d86-bca9-8409c9b7d787)

**Comment by DRracer** [comment]
@happykatz now that's a well documented bug report, thank you :+1: 

I'm wondering how it may happen that the selector doesn't rehome when it is supposed to do so every time ... the only thing which comes to my mind currently: when the selector doesn't rehome, what is the state of FINDA? Does it have it's LED on (I mean the LED inside the FINDA).

**Comment by happykatz** [comment]
Let me check this again today. I don't have a setup that will allow me to take and store a video of the entire print, but if I get the filament jam with the rehoming error, I will take a video clip that shows the state of the FINDA. 

One last thought: the second time that I encountered this problem, I was able to successfully get the selector to rehome by pressing the middle button on the MMU3. This was odd as pressing "retry" from the interface did NOT initiate the rehome.

**Comment by happykatz** [comment]
I was able to reproduce the error today - unfortunately, the error was not recoverable (MMU middle button produced the same result).

In this scenario, the filament load error was triggered with the filament in the correct position, and no obvious stringing on the filament. There was also no obvious blockage causing the FINDA to fire, although its LED was off and it reported its state as FI1. 

Briefly: I tried manually repositioning the selector, and then retrying first with the button and then with the interface "retry". In both cases the selector did not re-home and the filament loaded in air. I also tried tightening the tension screws with the same result. 

The steps I followed were these (photos / videos following each step) :

1) Notified of filament load error (FI1). 
![Step 1 - Filament Load Error](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/5bf95541-2678-4300-af74-e7180e321acd)

2) Observed position of selector. 
![Step 2 - Review Position of Selector](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/11fd4d8b-2218-4461-93ba-2c4c373b02b0)

3. Observed position / tip shape of other filaments.
![Step 3 - Review Position of other Filaments](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/c9ebfbad-5f6f-4b5e-a363-6bd9fa019da9)

4. Manually rotated the selector to neutral position to clear filament (none obvious, but following steps reported in the bug description). FI reads 1 at this step ![Step 4 - Rotate Selctor FI1](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/6fa7d417-4586-4ea8-b144-040264c298b3)

5. Cleared the selector with the small hex key. Afterwards, FI reads 0, and LED is on. 

6. Double checked that FINDA can still fire when filament present using small hex key. FI reads 1, LED off when hex key present. ![Step 6 - Double check FINDA FI1](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/305ddc3a-5cf7-4eb1-8f77-fb92915f2d89)

7.  Initiated a retry using the interface. Selector does not re-home and filament loads in the air (video) 
https://github.com/prusa3d/Prusa-Firmware/assets/71985281/30cd4286-af7e-4170-afdd-60b0ddf5e1ba

8. Intiated a retry using the MMU middle button. Selector does not re-home and filament loads in the air (video) https://github.com/prusa3d/Prusa-Firmware/assets/71985281/196354cf-d656-40af-93cc-52f745c27eb4

9. Checked whether tension screw position was related to failure by tightening the screws. 
![Step 9 - Tightening Tension Screws](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/46721930-51ff-4e65-bc46-01658fb1bfcb)

10. Initiated a retry using the MMU middle button a second time, with the same result - no re-home, filament in air (video).
https://github.com/prusa3d/Prusa-Firmware/assets/71985281/4bb56ccb-ae71-4b8d-a282-c613c4134a33

11. Checked whether the problem exists in other than the neutral position - manually repositioned the selector and initiated a third retry with the same result. (video) https://github.com/prusa3d/Prusa-Firmware/assets/71985281/366867ab-dac7-47f4-914d-a5ec7692835d

12. Finally, I concluded that the error was unrecoverable, and took some additional pictures of the idler state with the top of the unit open, and of the build plate.
![View 1 - Internal State of the Idler](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/8de3fa38-6211-4318-a61b-51f60321e798)
![View 2 - Internal State of the Idler](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/a5d6b12f-0fd0-4a48-916e-1f43779ad996)
![View 3 - Internal State of the Filaments](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/99ce83db-cd00-4084-9052-1aff6d50d84f)
![View 4 - Buildplate](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/f94210ee-78df-4df2-ba9e-452c9ba83d32)

_A few notes -_ 

FI was at 0 throughout: there was never a case where the FINDA read the presence of a filament when it should not have (except possibly for the original error). In the latter tests, the idler advanced filament 2 slightly as well as filament 5 - this persisted even when the tension in on the screws was reduced.

![Note - Position of Filament 2](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/3cd025b9-2915-481d-8194-cdc296d66930)

![Note - FI0 Throughout](https://github.com/prusa3d/Prusa-Firmware/assets/71985281/601705b7-452e-4c2e-9f97-90e1eae1aa5d)


I am hoping that this is an easy fix. Since the error is unrecoverable, it means that I can lose a multi-hour print mid-way with no recourse.

**Comment by happykatz** [comment]
Adding a coda to this. I suspect that the issue that I am seeing is related to the following known issue in the release notes:

`Known issues
During final testing of the FW 3.13.0 and MMU3 3.0.0 developers discovered a rare issue, which we will address in a future release. In case the MMU print stops with an error and needs user interaction a power panic will cause issues to recover from the power panic.`

The description of the issue is somewhat vague (" a power panic causes issues to recover from power panic"), but my reading of this is that that the power draw on the steppers disrupts power to the arduino, causing a reset / partial reset of the arduino and results in the system losing state. 

My experience of arduino devices is that they will prefer the power supply running through USB (covering the case that they are being run in debug mode through a host computer). My assumption is that this behaves like any other arduino device and that by supplying continuous power through the USB port, I will be able to prevent the power disruption even under heavy draw.

I have since connected a 5V power supply through the USB port (just like connecting to a USB host for debugging purposes) and have not had a recurrence of this problem.

I would be interested to know if this analysis is correct, and if the planned upcoming fix described in the notes will address this issue w/o additional power supply.

**Comment by gudnimg** [comment]
A power panic is a complete power outage. Meaning the whole printer shuts down while printing. Power panic recovery on subsequent boot-up attempts to recover the XYZ positions and the position in the gcode file to resume correctly.

The known issue mentioned in the release notes is a problem on the printer side and not MMU. If the print is paused due to an MMU error screen, and a power panic occurs. Then recovering the print will fail as the printer will use incorrect XYZ positions. This will be fixed in 3.13.2. 

I think it’s not related to the issue you’re describing.

If only the the MMU is having power supply issues there is unfortunately not much the firmware can do except raise an error screen. You may get a TMC or MCU error screen in that case (or communication timeout). Randomly even.

**Comment by cozmo14047** [comment]
So i have this problem where it dosent home but I have suspect that it only does it when the error is on port 4 or 5 I don't know if it's coincidence or not could you let me know what ports its doing it for you many thanks @happykatz

**Comment by happykatz** [comment]
Hi @cozmo14047 - I saw this on port 5, but also on port 2 in other experiments. My "workaround" based on the observation from @gudnimg was to eliminate the possibility of an MMU-only power issue by plugging the control port to a continuous 5V power supply. Since that time, I have not had a recurrence of the not-homing-on-error problem; however, I  have also significantly reduced my error count, so this may be co-incidental. Hope this helps!

**Comment by cozmo14047** [comment]
@happykatz 

Thanks what do you mean plugging controll port into power whst control port

**Comment by cozmo14047** [comment]
> @happykatz
> 
> Thanks what do you mean plugging controll port into power whst control port

The usb port to update the mmu leave that connected to the mmu

**Comment by cozmo14047** [comment]
> Hi @cozmo14047 - I saw this on port 5, but also on port 2 in other experiments. My "workaround" based on the observation from @gudnimg was to eliminate the possibility of an MMU-only power issue by plugging the control port to a continuous 5V power supply. Since that time, I have not had a recurrence of the not-homing-on-error problem; however, I have also significantly reduced my error count, so this may be co-incidental. Hope this helps!

I installed a new controller board and haven't had it since.
