### ISSUE TITLE
[QUESTION] problem with compile the source code 1.0.6 of the MMU2S

### ISSUE THREAD

**Issue by Axolotelking** [prusa3d/Prusa-Firmware#4353]
I am working on my master thesis right now and I am new to programming firmware, for my project I wanted to change the MMU2S for using continuous fibers.

I would appreciate it verry much if you could help me, because I can’t compile the source code 1.0.6 of the MMU2S. The Problem is this specific line “static const uint16_t fw_buildnr =${GIT_PARENT_COMMITS};” in version.h, and I don’t know which number I need to compile this code into a .hex file.

The other possibility would be using the MMU3.0.0 source code but I couldn’t find it.

I hope you could help me with this problem.

**Comment by 3d-gussner** [comment]
Closed duplicate https://github.com/prusa3d/Prusa-Firmware/issues/4359

**Comment by 3d-gussner** [comment]
@Axolotelking We looked into your request and working on it. At this moment I can't tell you more.

**Comment by Axolotelking** [comment]
Ok thank you very much

**Comment by gudnimg** [comment]
MMU FW 3.0.1 source code is public here: https://github.com/prusa3d/Prusa-Firmware-MMU

So I'm closing this issue as solved for now
