### ISSUE TITLE
[QUESTION]URGENT: Need source Code of V. MMU3.0.* for Master Thesis

### ISSUE THREAD

**Issue by Axolotelking** [prusa3d/Prusa-Firmware#4359]
Dear all,

I would need the source code of  V. MMU3.0.* for using a custumized MMU2S, with differant motors and sensors for my thesis.
I would need this version because i can't compile MMU1.0.6 because of following code line errror:

 
![Code line 1](https://github.com/prusa3d/Prusa-Firmware/assets/66320690/5706103e-2d40-48b6-9335-87efa1702edc)
![code line 2](https://github.com/prusa3d/Prusa-Firmware/assets/66320690/b4d8b070-4c8b-4cc2-afdb-b49a13a8a318)

Thank you for the support!

**Comment by 3d-gussner** [comment]
@Axolotelking Please don't spam the issue tracker. You already have opened a ticket.
