### ISSUE TITLE
Heater/Thermistor Selftest error - FIRMWARE 3.1.0

### ISSUE THREAD

**Issue by d777** [prusa3d/Prusa-Firmware#436]
Selftest error !
Please check:
Heater/Thermistor
Not connected

**Comment by jin3lee** [comment]
i have the same issue

**Comment by Prusa-Support** [comment]
Hello! Sorry for the very late response to this issue. Was everything solved in the meantime? In case it is not, can you please let me know via email (info@prusa3d.com mentioning "attn: Alessandro" in the subject)? We can test it in detail from there - it could be related with loose, or damaged cable, most likely. I am closing the issue, in case of anything related with this please let me know via email, I'll be glad to help! 

Alessandro Pantaleo
Prusa Research
