### ISSUE TITLE
[BUG] Thermal model calibration fails with surprising results (stock V6 nozzle, NOT REVO)

### ISSUE THREAD

**Issue by staspika** [prusa3d/Prusa-Firmware#4367]
**Printer type** - MK3S+, with stock V6 hotend (not Revo)
**Printer firmware version** - 3.13.0

**MMU upgrade** - none
**MMU upgrade firmware version** - n/a

**SD card or USB/Octoprint**

  SD card is taken out and nothing is connected to USB port

**Describe the bug**

After starting thermal model calibration, one of the following usually happens (it seems random which one):

1. At some point the printer emits screeching noise and reboots. After reboot, LCD usually shows following message: "Firmware crash was detected. Contact support".
2. Sometimes (although I have no MMU and it is disabled in the settings) LCD shows following message: "MMU NOT RESPONDING" and proposes to either reset or disable MMU.
3. Although all of the Setup Wizard up to that point is completed, after reboot the printer invites to start Setup Wizard from scratch.
  
**To Reproduce**

  Run complete factory reset. After reboot, run the Setup Wizard as usual. Get to the thermal model calibration step. Choose "OK" and wait as the printer attempts to calibrate the thermal model. Wait for the scratching noise, reboot and a message about firmware crash.
  
**Expected behavior**
  Thermal calibration should finish without problems.
  
**Video**

Here is one video. I have more, but the size exceeds the 100 MB quote. Unfortunately, there is a background fan noise throughout the whole video, but the screeching sound emitted by the printer is nevertheless clearly audible:
https://github.com/prusa3d/Prusa-Firmware/assets/26161325/107a58ef-667e-406d-81c0-d1ca00dd6e2b

**Comment by staspika** [comment]
After downgrading to 3.12.2 or 3.12.1, I am unable to reproduce this exact behaviour. After upgrading again to 3.13.0 the same unpredictable behaviour is back.

**Comment by vadim-ryazanov** [comment]
Same (or similar here) with REVO flavour: E3DREVO_fw_MK3S_MK3S+_3_13_1_6876.hex
After flashing firmware and trying to run Thermal Model Calibration, printer starts to heat up the nozzle, screams and quits after reaching around 50 C on the first step of the calibration.

**Comment by 3d-gussner** [comment]
@vadim-ryazanov Please contact E3D support. The issue is probably that you have E3D v6 values in the EEPROM and flashing the new E3DREVO_fw_MK3S_MK3S+_3_13_1_6876.hex doesn't reset these.

**Comment by mmcglumphy** [comment]
Doing a factory reset before the firmware update cleared those values for me. After that, calibration finishes successfully.

**Comment by staspika** [comment]
Not for me (see my initial comment, where I clearly state that I start by doing factory reset). Also (again, see my initial comment), I do *not* have REVO on my printer, only a new stock V6 hotend. I replaced the old one as suggested by Prusa Support representative, whom I initially contacted about this problem. This did not fix the problem.

**Comment by alextremblay** [comment]
I have an E3D REVO nozzle,
Did a factory Reset
flashed E3DREVO_fw_MK3S_MK3S+_3_13_2_7080.hex
Also experiencing a loud screech and printer reboot shortly after starting thermal calibration (when it gets to about 50-60C)

flashed 3.12.2 (first version with TM support for REVO), same outcome

For now, I've downgraded back to 3.11 so i can get back to a working printer.

If there's any other workaround I should test, please let me know. I'll re-flash 3.13.2 and try it
