### ISSUE TITLE
[BUG]3.13.1/3.0.0 MK3+/MMU2S Safety Timer firing during initial Setup causes weird printer state

### ISSUE THREAD

**Issue by trevorbattle** [prusa3d/Prusa-Firmware#4378]
MK3+, originally started as MK2 but upgraded along. Firmware 3.13.1 from github, compiled with VSCode windows.

MMU2S with 3.0.0 firmware. (Printer source code modified to accept 3.0.0 instead of 3.0.1.)

OBSERVATION:

When doing initial printer setup, if the Safety Timer fires, the printer gets in a weird state.

TO REPRODUCE:

Start initial printer setup.

Follow along, but get to a state where the printer is hot, but the printer is waiting for input.

Do nothing for a long time. Wait until Safety Timer fires.

Screen will say "Heating disabled by safety timer." with the choices being "Yes" and "No". Neither of those options make sense.

![20230907_011758](https://github.com/prusa3d/Prusa-Firmware/assets/9663438/8c0612fe-57c0-4907-a0b9-70533f3e073c)

**Comment by gudnimg** [comment]
Hi 👋 Can you elaborate what you mean by `initial printer setup`? The image you posted looks like the MMU Error screen is trying to render on top of the Safety Timer screen. (The clock symbol in far right corner suggests this to me)

**Comment by trevorbattle** [comment]
Sorry. I was going through the procedure that starts with "I am your original Prusa i3 printer".

The printer is older and well proven, so the procedure should have been straightforward. I just walked away while it was happening and got distracted and didn't return for a long time.

Disabling heating was the right action, just the UI makes no sense.

**Comment by Iv4nS** [comment]
this is still occurring, indeed the options of "yes" and "no" do not make sense and I don't know what I'm really answering to, you can easily get there by doing the wizard, completing the Mesh bed leveling and then leaving the printer without inputting anything
