### ISSUE TITLE
[BUG] Crash Detected during Calibration leads to screen going to main

### ISSUE THREAD

**Issue by addohm** [prusa3d/Prusa-Firmware#4382]
MK3S+ Running the latest release firmware.

During a first layer calibration, if a crash is "detected" and the printer tries to correct itself, the screen on the printer goes back to the main screen and you can't stop the processes or adjust on the calibration.  This is 100% repeatable.

**Comment by gudnimg** [comment]
Hi there’s a similar bug report here: https://github.com/prusa3d/Prusa-Firmware/issues/4377

I havent tested this yet myself but I would think first layer calibration can’t recover from a axis crash. Similar to how it can’t recover on filament runout event (which is forcefully disabled due to this)
