### ISSUE TITLE
[BUG] XYZ Calibration Hang in FW 3.13.2

### ISSUE THREAD

**Issue by drawlerr** [prusa3d/Prusa-Firmware#4415]
Printer: MK3S-R
FW3132-RC1-Build7068 E3DREVO

Octoprint on attached Pi Zero 2 W

Re-attempting XYZ calibration after moving things around and upgrading to Revo hotend.
  
**To Reproduce**
Click Calibrated XYZ in LCD
  
**Expected behavior**
Extruder head should orbit/scan searching for each calibration point until it finds it.
 
**Actual behavior**
Extruder does not move at all once calibration process begins.  All calibration messages are logged, but no progress is made and calibration fails on first point:
Recv: xyzcal_searchZ no signal
Recv:  x=1190 y=601 z=-2398
Recv: xyzcal_measure_leave

**Comment by gudnimg** [comment]
@drawlerr Have you contacted Prusa technical support? Does the issue persist if you switch to 3.11 and then back to 3.13.2?

Pinging @Prusa-Support
