### ISSUE TITLE
Feature Request : Long term pause that lasts through power off/reset.

### ISSUE THREAD

**Issue by MAPReiff** [prusa3d/Prusa-Firmware#442]
Ok, here's my idea:

- 2 pause options, 1 like it is now, 1 long-term.
- The long-term one will save its position & data as a new gcode file that can be used to resume a print later on.
- It would be like the power panic on the mk3, but not automatic and could work for the mk2/s/mmu aswell.
- Good for long projects that you might not want to leave running overnight.
- You select the new option, it gives you a save confirmation, and you power off the machine. When you turn it back on, it asks if you would like to resume the previously paused print.

**Comment by clearbucketLabs** [comment]
i've just paused a print, turned off the bed and left the thing on for a week... then resumed it when i came back.  Good if the power goes out though or somehow you need to transfer the printer to another location.

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete.

Marina Curzi
Prusa Research
