### ISSUE TITLE
[BUG]<M310 S0 starts thermal model calibration instead of disabling after fresh flash>

### ISSUE THREAD

**Issue by mcginnisa** [prusa3d/Prusa-Firmware#4422]
**Printer type** MK3S
**Printer firmware version** 3.13.1

**MMU upgrade** none
**MMU upgrade firmware version** N/A

**SD card or USB/Octoprint**
Octoprint

**Describe the bug**
After compiling (only change i made was pinda position) and flashing 3.13.1, and immediately sending M310 S0 with octoprint, MK3S starts thermal model calibration instead of disabling the thermal model. I skipped all initial setup and calibration of the printer, going to the main menu, and then sending M310 S0. 
  
**To Reproduce**
send M310 S0 immediately after firmware flashing without going through any initial setup. 
  
**Expected behavior**
M310 S0 should disable thermal model, not start thermal model calibration

**Comment by 3d-gussner** [comment]
The printer only starts the Thermal Calibration when the Wizard didn't finished correctly.
