### ISSUE TITLE
[BUG] German tune menu missing text

### ISSUE THREAD

**Issue by ulab** [prusa3d/Prusa-Firmware#4434]
**Printer type** - MK3S
**Printer firmware version** -  3.13.1

**Describe the bug**
[Users have reported](https://www.printables.com/group/3d-printing-community-germany-dXZjmRk/comments/1178058) that the German translation of the tune menu is not showing text for the two lines "Speed" and "Main" since version 3.13.0.
  
![image](https://github.com/prusa3d/Prusa-Firmware/assets/504616/c35e43af-a8f5-405b-bbe4-f1f2ac36d6c3)

**To Reproduce**
Install 3.13.1, load German, start printing and check the "Feineinstellung" menu.
  
**Note**
The English menu does not have this issue:

![image](https://github.com/prusa3d/Prusa-Firmware/assets/504616/162c6fb6-f4df-4ae7-88f2-91fc08e2a16a)

**Comment by sarusani** [comment]
Duplicate of https://github.com/prusa3d/Prusa-Firmware/issues/4384, https://github.com/prusa3d/Prusa-Firmware/issues/4406 & https://github.com/prusa3d/Prusa-Firmware/issues/4413.

Already solved in [3.13.2](https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.13.2-RC1).

**Comment by ulab** [comment]
Oh wow. I didn't find anything when I was looking for them. Closing this ticket.
