### ISSUE TITLE
[BUG]<First layer calibration not working when filament sensor is switched off>

### ISSUE THREAD

**Issue by ArjanStr** [prusa3d/Prusa-Firmware#4443]
MK3,  prusa3d_fw_MK3S_MK3S+_3_13_1_6876.hex

The menu hangs on 'filament loaded?' 
When the filament sensor is switched on, all is ok.
In previous firmware versions this was working ok.

**Comment by frogale** [comment]
I can confirm that.. I am using Revo edition 3.13.1 and cannot proceed with first layer calibration.. filament sensor off..

**Comment by gudnimg** [comment]
Closing since this was fixed in 3.13.2
