### ISSUE TITLE
First layer calibration not working when filament sensor is switched off

### ISSUE THREAD

**Issue by ArjanStr** [prusa3d/Prusa-Firmware#4444]
### Description of the bug

First layer calibration not working when filament sensor is switched off.
When the menu is asking for 'filament loaded?' both options yes and no do not forward the menu
Prusa MK3, prusa3d_fw_MK3S_MK3S+_3_13_1_6876.hex firmware.
When the filament sensor is switched on, all is working ok

### Project file & How to reproduce

Do first layer calibration with filament sensor switched off

### Checklist of files included above

- [ ] Project file
- [ ] Screenshot

### Version of PrusaSlicer

prusa3d_fw_MK3S_MK3S+_3_13_1_6876.hex

### Operating system

windows 10

### Printer model

Prusa MK3

**Comment by ArjanStr** [comment]
Sorry, this is a firmware issue, not a slicer issue, but I'm sure it will be picked up by Prusa.

**Comment by frogale** [comment]
I can confirm that.. I am using Revo edition 3.13.1 and cannot proceed with first layer calibration.. filament sensor off..

**Comment by gudnimg** [comment]
@frogale Fix is coming in 3.13.2, you can use https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.13.2-RC1 if you want, but the final 3.13.2 should come next week with some minor changes on top of RC1.

**Comment by gudnimg** [comment]
Closing since this was fixed in 3.13.2
