### ISSUE TITLE
[BUG]<baby bug: language spelling error>

### ISSUE THREAD

**Issue by ESF-nl** [prusa3d/Prusa-Firmware#4447]
Sorry to bother you with this small issue but my printer writing incorrect bothers me. In the language file for Dutch 
[https://github.com/prusa3d/Prusa-Firmware/blob/MK3/lang/po/Firmware_nl.po](url)
at line 229 there is a small language typo. The text "kalibrere" should be "kalibreren" the N is missing at the end.

**Comment by sarusani** [comment]
Thanks for reporting!

**Comment by 3d-gussner** [comment]
@ESF-nl This message is shown when the printer encounters an issue and enforces an auto Z calibration.

Ik denk `kalibrere Z` is niet heelmaal just, zou `Kalibreren Z` of `Z kalibreren` beter zijn? Nederlands is niet mijn moedertaal.

**Comment by ESF-nl** [comment]
Yes, Dutch is my mothertongue and this was indeed my issue. Please change "kalibrere" into "kalibreren". The position of the axis name is not such an issue. This can be written as prefix or suffix. I'd propose to keep it in line with the orignal English version.

**Comment by gudnimg** [comment]
Closing this issue because a fix has been merged into 3.14 development branch.
