### ISSUE TITLE
boards.h #defines are inconsistent

### ISSUE THREAD

**Issue by crioux** [prusa3d/Prusa-Firmware#445]
Not sure if this is supposed to be this way or not, but it's confusing:

in boards.h:

#define BOARD_EINSY_0_4a         304

but in variants/1_75mm_MK3-EINY10a-E3Dv6full.h   (and others)

#define MOTHERBOARD BOARD_EINY_0_4a

Note 'EINY' vs 'EINSY'. Looks like MOTHERBOARD is being defined to an empty value for MK3 machines. Obviously things have been 'working' but it's probably some kind of typo/oversight, right? Is this 'MOTHERBOARD' define used for anything important?

:)

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete.

Marina Curzi
Prusa Research
