### ISSUE TITLE
[BUG]<Enter comprehensive title>

### ISSUE THREAD

**Issue by srjacob999** [prusa3d/Prusa-Firmware#4467]
**Printer type** MK4
**Printer firmware version** -  5.00
**MMU upgrade** - No MMU
**MMU upgrade firmware version** - NO MMU

** USB/Octoprint**
 
**Describe the bug**
  When using the MK4 with Octoprint, the printer status and job times do not appear on the printer LCD
  
**To Reproduce**
  Run the printer with Octoprint
  
**Expected behavior**
  Print status should appear on the LCD screen
  
**G-code**
Any print

**Video**
 None

**Comment by 3d-gussner** [comment]
@srjacob999 This is the repository for MK2.5/S MK3/S/+ 8-bit printers. Please open the issue here https://github.com/prusa3d/Prusa-Firmware-Buddy which is form the 32-bit printers MINI, MK4, XL.
