### ISSUE TITLE
  [ENHANCEMENT] [Prusa-Link_Connect] G-code for MMU status for Prusalink

### ISSUE THREAD

**Issue by Ro3Deee** [prusa3d/Prusa-Firmware#4473]
**Printer type** - MK3S
**MMU Upgrade** - MMU2S (with FW 3.0.1)

**Is your enhancement related to a problem?**
With FW 3.13.0 and MMU FW 3.0.0, an option to disable/enable the MMU2 was implemented in MK3 firmware and menu (see https://github.com/prusa3d/Prusa-Firmware/issues/1876#issuecomment-1658145989).

This option or, at least, the viewing of **status of the MMU (enabled/disabled)** should be available in Prusa-Link/Connect.
  
**Describe the solution you'd like**
  @TojikCZ  says here https://github.com/prusa3d/Prusa-Link/issues/872#issuecomment-1785157285 that a gcode is necessary.

**Comment by 3d-gussner** [comment]
@petrubecheru Closing this issue as we implemented `M709` with https://github.com/prusa3d/Prusa-Firmware/pull/4474 

Forgot to Thank you for the idea and interacting on github. Very appreciated.
