### ISSUE TITLE
[BUG] Prusa XL Multitool - Selecting Reprint at the end of a print does not preserve Spool choices

### ISSUE THREAD

**Issue by amarilio** [prusa3d/Prusa-Firmware#4477]
**Printer type** - XL
**Printer firmware version** -  5.1.0-alpha2

**SD card or USB/Octoprint** USB

**Describe the bug**
At the end of a print there is a dialog asking you if you'd like to reprint the object. The reprint will not select the same spools you have chosen before the print if they were changed.
  
**To Reproduce**
1. Slice a multicolor print and send it to print
2. On the printer, remap the filament color (e.g. 1->2 2->1) and reprint
3. At the end of the print, select to reprint the object.
4. Filaments remapping is not preserved.
  
**Expected behavior**
Reprint should be identical to the original print.

**Comment by gudnimg** [comment]
Hi, please open the issue here https://github.com/prusa3d/Prusa-Firmware-Buddy/issues that repo is for all 32-bit printers. 

This repo however is only for the 8-bit printers (MK3S+ and older models)
