### ISSUE TITLE
[BUG] Precise Stepping BSOD - MK4 5.1.0-alpha2+13126

### ISSUE THREAD

**Issue by PTW-105** [prusa3d/Prusa-Firmware#4481]
**Printer type** - MK4
**Printer firmware version** -  5.1.0-alpha2+13126

**MMU upgrade** - N/A - No MMU
**MMU upgrade firmware version** - N/A

**SD card or USB/Octoprint**
  USB drive directly connected to MK4

**Describe the bug**
  While printing a 42-hour print, I returned to the MK4 beeping with a blue screen with a title of precise_stepping.cpp:447.  This gcode file was produced using PrusaSlicer 2.7.0-alpha1-win64.  BIN crash dump from the printer and a photo of the error that was displayed on screen are attached to this report.  The g-code file is too large to attach here (31MB) but is available upon request.  This is the first time I have observed this BSOD issue and first time I have tried printing this g-code file.
  
**To Reproduce**
  Print g-code file (too large to attach, but available upon request) from USB drive connected to MK4 running firmware 5.1.0-alpha2+13126 and wait to see if BSOD occurs.
  
**Expected behavior**
  I expected the provided g-code file to print successfully.
  
**G-code**
  BIN crash dump and photo of the displayed error are attached to this report.  Unfortunately, g-code file is 31MB and too large to attach.  Please contact directly with alternate transfer method.

**Video**
  No video is available for this error, however a photo of the BSOD error screen is attached.

![20231105_162202](https://github.com/prusa3d/Prusa-Firmware/assets/10904125/a7e60eb8-8fc8-4e8b-9580-43741c1ac446)
[dump_buddy.zip](https://github.com/prusa3d/Prusa-Firmware/files/13261291/dump_buddy.zip)

**Comment by 3d-gussner** [comment]
@PTW-105 This is the repository for the Prusa MK2.5/S and MK3/S/+ please open a new ticket here https://github.com/prusa3d/Prusa-Firmware-Buddy
