### ISSUE TITLE
[BUG] Display lock when changing run-out filament

### ISSUE THREAD

**Issue by marobi** [prusa3d/Prusa-Firmware#4483]
**Printer type** - XL
**Printer firmware version** -  5.1.0 -alpha2

**
![IMG_1925](https://github.com/prusa3d/Prusa-Firmware/assets/31653/10f72101-b0e8-4775-b364-26badd0760e4)
Print using USB stick

**Describe the bug**
  After systems runs out of filament, it tries to retract last piece of filament. However it fails to do so. I manually removed PTFE tube form extruder and pulled out rest of filament (direct extruder side) and reinstalled PTFE tube. This action is displayed. It comes up with a new display text (see uploaded image). However systems does not see filament loading and you can NOT back out of the displayed text. Only solution is to power down/up system. It nicely recover but immediately resumes printed while no filament is loaded. I paused the system and pushed in the new filament and resumed the print. Luckily that worked.
  
**To Reproduce**
  - run out of filament
  - tell system it did not retract filament correctly
  - system will display (uploaded image)
  - insert new filament (and remove it and reinsert it ...)
  - system will NOT recognize insertion and stays stuck in displayed text.
  - power down/up system
  - system will resume print without loading filament
  
  
**G-code**
 NA

**Video**
Picture of display

**Comment by 3d-gussner** [comment]
@marobi This is the repository for the Prusa MK2.5/S and MK3/S/+ please open a new ticket here https://github.com/prusa3d/Prusa-Firmware-Buddy
