### ISSUE TITLE
[FEATURE REQUEST]<MK4 display saving>

### ISSUE THREAD

**Issue by joker3d** [prusa3d/Prusa-Firmware#4485]
Hello, i got a idea for feature. is it possible to make screen timer for turn off screen on MK4? (display saving)
for me is good idea. when is not printing, turn off display after setted time.
for example type of sub menu:

**Screen off :** always / when not printing
**Timer:** 1min/ 10min/ 20min/ ...etc

Thanks :)

**Comment by 3d-gussner** [comment]
@joker3d This repository is for Prusa Mk2.5/S and MK3/S/+ please open the feature request here https://github.com/prusa3d/Prusa-Firmware-Buddy
