### ISSUE TITLE
After cooling down due to too many extruder crashes a cold unload is attempted when resuming with the "retry" option

### ISSUE THREAD

**Issue by ruedli** [prusa3d/Prusa-Firmware#4489]
**Printer type** - MK3S+
**Printer firmware version** -  v3.13.2
**MMU upgrade** - MMU3
**MMU upgrade firmware version** - 3.0.1
**SD card or USB/Octoprint**  SDcard
**Describe the bug**
When a print pauses due to too many crashes, the extruder cools down.

Then the ONLY option is to review the problem and choose RETRY from the menu, however: it then results to attempt to unload from a cold extruder, which always fails for obvious reasons.  
**To Reproduce**
 Make the printer pause due to extruder crashes (.e.g. hit the moving extruder), until the extruder will no longer home and pause. Wait for cool down, then try to recover.  
**Expected behavior**
 After selecting "retry" the extruder should be heated up to working temperature, for an unload to succeed.
**G-code**
  Not relevant.
**Video**
  Sorry: not available, let me know if you cannot reproduce from my description.

**Comment by kevinsaucier** [comment]
Just piling on here to make sure this one gets some love.  I've had this happen multiple times when a print crashes overnight and I try to resolve it in the morning.  The only fix is to reset the printer and set the nozzle temp before it attempts to resume the unload loop again.  It will then heat up enough and 'usually' allow you to unload, though I still sometimes have to pull the PTFE tube from the extruder and manually pull the filament out.  Less than ideal, for sure.

**Comment by Majklzbastlirny** [comment]
Just had the same issue (MK3s+ FW: 3.13.3-7094 [With Revo], MMU3 FW:3.0.2

**Comment by Patronics** [comment]
I'm encountering the same issue, it's especially problematic because it grinds the filament, so can cause more major clogs. It's also frustrating that there's no option in the interface to reheat the nozzle first, or to not attempt an unload.
