### ISSUE TITLE
[FEATURE REQUEST] Add Filament cutting function after filament change.

### ISSUE THREAD

**Issue by dameningen4914** [prusa3d/Prusa-Firmware#4490]
Printer Type : MK3S + MMU3

Add filament cutting function after filament change.
When filament change for color printing, mmu will ramming filament tip for better filament loading.
but if prusa add filament cutting after filament change. ramming function is no more to need.
filament tip shape is very sharp every filament change and it will reduce filament load error.

**Comment by Prusa-Support** [comment]
Thanks for your suggestion.

Ramming and finely tuned settings will still be strictly necessary to reduce residues of plastic, filament blockage, tube wearing, etc... Not to mention that probably a lot of pieces of plastic will collect around the selector in no time, and the blade will need to be replaced frequently.
This may not seem to be a big deal but the continuous use of the blade would increase the operation complexity, theoretically, without real benefits. I'll try to explain.

Based on our tests, cutting filament is not required if the printer and the filament are in good condition.
Filament cutting is a valid backup option for sporadic minor automated interventions.
Also, based on our tests, if filament cutting is frequently enforced colo changes, that means there is probably something wrong with the hotend assembly, or the heat-break, the temperatures, the settings, the tubes, the filament itself, and more...

Michele Moramarco
Prusa Research
