### ISSUE TITLE
File not complete

### ISSUE THREAD

**Issue by ShadowsRealm3D** [prusa3d/Prusa-Firmware#4506]
### Description of the bug

Sorry if this has been reported, I couldn't find anything current. Using Prusa Slicer 2.7.0-bet1 and higher are giving me "File not complete, do you want to continue?" error when trying to print from SD Card. This happens when trying to print on my MK3S with MMU2S. This has happened with Prusa Slicer 2.7.0-beta1 and rc1. I have rolled back to 2.7.0-alpha and have not received this issue when printing from SD card with the same exact sliced file. I've formatted both SD cards and re-sliced and tried to print and the error persists. Printer still prints file without any issues.  

### Project file & How to reproduce

Can't upload .3mf file or gcode as I cannot zip it. 

### Checklist of files included above

- [ ] Project file
- [ ] Screenshot

### Version of PrusaSlicer

2.7.0-beta1/2.7.0-rc1

### Operating system

Edition	Windows 11 Home Version	22H2 Installed on	‎3/‎7/‎2023 OS build	22621.2715 Experience	Windows Feature Experience Pack 1000.22677.1000.0

### Printer model

Prusa MK3S with MMU2s; software vers 3.13.2 (3.0.1 MMU2S)

**Comment by rtyr** [comment]
The printer/FW checks the last 20k characters for M84 command. PS2.7.0 generates more comments at the end of the g-code and we are apparently over 20k in some cases. We will likely have to increase it in the firmware.

**Comment by 3d-gussner** [comment]
https://github.com/prusa3d/Prusa-Firmware/pull/4507 solves the issue.
