### ISSUE TITLE
[BUG] Hotend cools off in Pause Print/ Change Filament

### ISSUE THREAD

**Issue by zeitung-ger** [prusa3d/Prusa-Firmware#4516]
[MK3]
[3.13.2]
[NO MMU]
[SD-Card]

**Description**
Hotend cools down when I try to change the filament in the "Pause Print" Menu.
  
**How to Reproduce**
When the filament sensor is turned off and the print paused, the heating of the hotend will shut off. 
Now when I try to change the filament, the extruder motor will not move at all, because the temperature is way too low.
I can neither unload or load any filament. The only workaround is to go into the Tune Menu, manually turn up the Nozzle Temperature, unload/load filament and resume the print. This only started happening since the latest update.
  
**Expected behavior**
The nozzle usually kept its temperature.

**Comment by 3d-gussner** [comment]
@zeitung-ger Thanks for the bug report. This has been fixed and be available in the next release.

Tested with current MK3 branch build:
1. Start SD print
2. Pause print via LCD
   1. hotend will be set to 0°C and we not gonna change this to prevent cooking of the filament
4. Wait until temp ~160°C (lower than clod extrusion)
5. Tune -> Change filament
   1. reheats to previous temperature
   2. unload and load filament procedure
   3. back to pause state with hotend set to 0°C
 6. Wait for temp to drop to ~160°C
 7. Resume print
   1.  heats the hotend to previous temp and continues to print.

Please consider to close this issue
