### ISSUE TITLE
[BUG] Y Axis Calibration Fails on Firmware v5.1.0

### ISSUE THREAD

**Issue by Yeungster** [prusa3d/Prusa-Firmware#4518]
**Printer type** - MK4
**Printer firmware version** - 5.1.0

**MMU upgrade** - N/A
**MMU upgrade firmware version** - N/A

**SD card or USB/Octoprint** - USB

**Describe the bug**
Y axis calibration is failing for me after re-running a full calibration following upgrade to firmware v5.1.0
  
**To Reproduce**
Re-ran the full printer calibration or XYZ calibration wizard which fails continuously every time for me. This occurred after installing the printer into an enclosure. I followed all troubleshooting steps and couldn't resolve the issue. This included resetting the printer settings and a full restore to factory settings. I eventually downgraded the printer to v5.0.1 without changing anything else and the printer passes every time.
  
**Expected behavior**
 Calibration to run and for the printer to pass the XYZ calibration phases using firmware v 5.1.0 without having to downgrade to a previous version of firmware (which successfully passes the test every time)
  
**G-code**
N/A

**Video**
N/A

**Comment by 3d-gussner** [comment]
@Yeungster This is the repository for Prusa MK2.5/S MK3/S/+ please open the ticket for MINI, MK4, XL in Prusa-Buddy-Firmware https://github.com/prusa3d/Prusa-Firmware-Buddy

And please close it here.
