### ISSUE TITLE
"filament autoload" option is not saved properly.

### ISSUE THREAD

**Issue by sylphio** [prusa3d/Prusa-Firmware#452]
hi, 

   When the filament sensor is enabled, "filament autoload" is enabled by default.
If the "filament autoload" is disabled afterward in the settings will revert back to enabled at each printer restart.

Tested on b143 and b150.

Thank

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete.

Marina Curzi
Prusa Research
