### ISSUE TITLE
[BUG]Unknown Error / Unable to Show Details

### ISSUE THREAD

**Issue by Jam-ehz** [prusa3d/Prusa-Firmware#4521]
Prusa Mini+
5.1 Nov 23 Stable FW

Using OctoPrint

Started a print job overnight, checking it in the morning the print was successful, but it was constantly beeping with this error screen:

![PXL_20231125_132012500](https://github.com/prusa3d/Prusa-Firmware/assets/54636955/250dc8c0-2259-4b1a-b16d-f951e587cf35)

Unknown Error, and Unable to show deta(ils?)

Haven't been able to reproduce it, but here's the error dump file and gcode that was used:
[dump_buddy.zip](https://github.com/prusa3d/Prusa-Firmware/files/13515300/dump_buddy.zip)

Not very helpful with an error like this, but might as well throw it out there in case someone else has it!

**Comment by 3d-gussner** [comment]
@Jam-ehz This is the repository for Prusa MK2.5/S MK3/S/+ please open the ticket for MINI, MK4, XL in Prusa-Buddy-Firmware https://github.com/prusa3d/Prusa-Firmware-Buddy

And please close it here.

**Comment by Jam-ehz** [comment]
Ah, Sorry!
