### ISSUE TITLE
 [ENHANCEMENT] A better norwegian translation

### ISSUE THREAD

**Issue by trondkla** [prusa3d/Prusa-Firmware#4522]
In https://github.com/prusa3d/Prusa-Firmware/pull/4510 the norwegian translation for REPRINT was added.
It does not fit the other language used in the Norwegian translations.
I have translated many PRs recently, but didn't get to this before it was merged.

Instead of "Nytt opptrykk" (in lang/po/Firmware_no.po), it should be "Gjenta print"

**Comment by 3d-gussner** [comment]
@trondkla Thanks again for the translation, closing this as #4528 has been merged.
