### ISSUE TITLE
[ENHANCEMENT] Faster preheat. M104 M109 M140 M190 enhacement

### ISSUE THREAD

**Issue by KOBALT3D** [prusa3d/Prusa-Firmware#4532]
**Printer type** - MK3S, possibly all Prusa models

Preheating process is sometimes long (using LCD menu or starting g-code) because uses PID method. It also causes oozing until temperatures are stable.
  
I am suggesting to add another parameter to all heating commands, **P** (as full Power) for example to temporarily disable PID heating and therefore use maximum power until temperature exceeds specified value. Then the PID mode will be reactivated. Alternative solution might be to use this method automatically if heating is off, e.g. after cooldown command.

example:
`M190 S60 P`
`; start heating bed using 100% power,`
`; wait until temperature reaches 60 degrees,`
`; switch to PID mode and continue`

Additionally, there might be useful also this variant for someone:
`M104 S215 P200`
`; start heating hotend using 100% power,`
`; wait until temperature reaches 200 degrees,`
`; turn off heater. Temperature is still increasing few degrees even if heater is off.`
`; when temperature starts decreasing switch to PID`

**Comment by Panayiotis-git** [comment]
Isn't PID regulating the temperature with the exact same logic? As long as the deviation of the current temperature to the set temperature is large enough, it uses the maximum power to heat the element.

Have you calibrated the PID controllers of your printer?

**Comment by KOBALT3D** [comment]
PID also reduces (cycles) power before temperature reaches specified value. This will slow the heating process. If you preheating from room temperature to certain temperature there is no need to slow down the heating process or to reach precisely certain temperature. The temperature will be stabilized relatively fast during homing, Mesh Bed Leveling and purge line printing.
