### ISSUE TITLE
[FEATURE REQUEST] MK4 Maintenance Reminder

### ISSUE THREAD

**Issue by girak49** [prusa3d/Prusa-Firmware#4535]
What: Maintenance reminder feature based on print hours.
For:  MK4
Related requests:
#3059 open, slated for FW 3.14.1 on MK3 
#3483 closed, but Prusa-Support stated this feature is already planned for the new generation boards (like the 32-bit Buddy) and in PrusaConnect for other devices (like the MK3- series, based on Einsy 8-bit board).

I would like to request a simple maintenance reminder system based on [recommended interval of 200 print hours](https://help.prusa3d.com/article/regular-printer-maintenance-mk4_419000). 
The MK4 are marketed as reliable work horses. On the [MK4 homepage](https://www.prusa3d.com/product/original-prusa-mk4-3d-printer-8/), the first sentence that is used to explain it is "The MK4 is the latest edition of our flagship 3D printing workhorse." Regular maintenance is a must if reliability is expected. Such a feature is even more valuable and necessary today now that input shaping is available. The higher accelerations puts even more stress on the printer. A quote from [Input Shaper Prusa Knowledge Base:](https://help.prusa3d.com/article/input-shaper-mk4-xl-mini-_451816) "We strongly suggest performing basic maintenance on the MK4 before you start to use the Input shaper to achieve the best possible print performance." Our cars remind us when to change the oil, I think our printers should too! :)
A simple reminder every 200 print hours to perform the recommended maintenance would be greatly appreciated. 
Thank you!

**Comment by girak49** [comment]
I have additional thoughts on how this reminder could be implemented.

- The reminder could pop up on printer boot-up or before a print starts if there are users who never shut off their printer
- The reminder could be dismissed because maintenance was completed or be asked to be reminded again later
- In the maintenance settings, you cold look up how many print hours since last routine maintenance
- Perhaps give users the ability to reset the 200 hour clock for whatever reason.
- The reminder could have a QR code to the [maintenance website](https://help.prusa3d.com/article/regular-printer-maintenance-mk4_419000)

**Comment by 3d-gussner** [comment]
@girak49 Is this a request for the 8-bit or 32-bit firmware? If it is for the MK4 please close this issue here as this is for Mk2.5/S and MK3/S/+

**Comment by girak49** [comment]
Oops, my bad. This is for the 32-bit firmware.
