### ISSUE TITLE
[BUG][MK4/5.1FW/2.7.1PS/bgcode]Random filament ejection / filament sensor bug?

### ISSUE THREAD

**Issue by MilleniumDawn** [prusa3d/Prusa-Firmware#4539]
So, i updated to the latest PrusaSlicer 2.7.1.

The latest PrusaSlicer now give you binary gcode (bgcode) if your printer support it(can be disable), the MK4 latest firmware do.

So i updated my MK4 to the latest 5.1 firmware(i did the new filament sensor calibration as requested on boot).

Now its my first print with all those new setting, and its still going, but it already stopped printing twice, beeping, and ask me if the filament was ejected corretly (because it randomly ejected the filament....)

I was able to put back the filament in and restart the print.

Ive check the bgcode i sent to the printer and there no Tool Change from what PrusaSlicer G-code viewer is showing me (you cant check the file yourself since its binary now...)

The more i think about it, the more i think its a false positive of the filament sensor thinking it ran out... rather than a tool change.

I was affected by the filament sensor bug where a new filament was not detected... so i guess it was over corrected?

https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3129

**Printer type** - MK4
**Printer firmware version** -  5.1.0

**SD card or USB/Octoprint**
  USB through PrusaConnect

**Describe the bug**
  Repeated random filament ejection during print.
    
**G-code**
  Please attach a G-code. This will make it easier for us to replicate the error.
[Mix-Guard Archer - Based_0.25n_0.12mm_PLA_MK4_15h45m.bgcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/13679739/Mix-Guard.Archer.-.Based_0.25n_0.12mm_PLA_MK4_15h45m.bgcode.zip)

**Comment by 3d-gussner** [comment]
@MilleniumDawn This is the repository and issue tracker for the 8-bit Mk2.5/MK3S please close it here and reopen it in the 32-bit MINI, MK4, XL repository https://github.com/prusa3d/Prusa-Firmware-Buddy
