### ISSUE TITLE
Cannot remedy failed filament sensor at critical moment.

### ISSUE THREAD

**Issue by dsjove** [prusa3d/Prusa-Firmware#4575]
**Printer type** - MK4
**Printer firmware version** - latest

**Describe the bug**
The filament sensor can fail due to regular use (dust, globs, etc). If it detects filament runout, the firmware properly goes into filament change mode. But if the sensors continually reads true (despite use of compressed air, etc), the MK4 remains stuck on the "please remove screen". As a user, we need the ability to tell the printer to just continue. 
  
**To Reproduce**
  Random moments during filament runout change.
  
**Expected behavior**
The "remove filament" screen to have a "continue anyway", "pause print", or a way to disable sensor at that moment.
  
To get around this, I flip the power strip power off/on quickly. Printer detects resume. I immediately pause print, turn sensor off, change filament, and resume. Not good.

**Comment by 3d-gussner** [comment]
@dsjove This is the repository for MK2.5/S and MK3/S/+. Please close this issue here and open it at the MINI, MK3.9, MK4, XL repository https://github.com/prusa3d/Prusa-Firmware-Buddy
