### ISSUE TITLE
No resume afer SdCard remove/reinsert

### ISSUE THREAD

**Issue by BerBuz** [prusa3d/Prusa-Firmware#459]
Printer Mk2S
Firmware version 2.1.0
Printer will not resume print if SDcard is removed and reinserted.
Occurs: Always
Test sequence:
1.	Start à print
2.	Wait until layer 1 starts printing
3.	Remove the SDcard 
4.	Check for “**Card Removed**” message
5.	Reinsert the SDcard 
6.	Check for “**Card inserted**” message
7.	Navigate to “**Resume Print**”
8.	Validate “**Resume Print**”
9.	Check for “**Heating ….**” Message
10.	Check for the head temperature target value: **(0) zero!!!!**

Print will not resume because temperature target is set to **0** instead of material fusion temperature. 
This bug is most probably due to the recent changes in pause behaviour that stops the head heating during pause. The target value taken on “resume print” is not the good one.

You may be under the impression that nobody is stupid enough to withdraw the SDcard during print. Agree, I never did that but SDcard contacts tend to get loose as time passes and a vibration generates the same effect. I lost a few prints for this reason and it’s a real heartbreak when it occurs.

Following is my personal opinion: The pause behaviour with stopping head heat should only be entered if pause duration exceeds a few minutes. In my case pauses most often does not exceed 30 seconds, the time to remove a chip or to visually check some details. 
Regards,
BerBuz

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete.

Marina Curzi
Prusa Research
