### ISSUE TITLE
[FEATURE REQUEST]<Added other filaments to MK4>

### ISSUE THREAD

**Issue by TOMASNetr** [prusa3d/Prusa-Firmware#4603]
Hi,
I have new MK4 and i use Spectrum PCTG filament. 
There is a profile for this filament in PrusaSlicer, but MK4 does not recognize it. I introduce the filament as PETg and then upload the gcode sliced for PCTG. However, when starting the printer, the printer throws a message that the gcode is for a different filament than the one installed.
Please add knowledge of other types of filaments to the printer.
Thanks

**Comment by 3d-gussner** [comment]
@TOMASNetr As this is a PrusaSlicer-setting related issue please close it here and open a new issue here https://github.com/prusa3d/PrusaSlicer-settings

**Comment by TOMASNetr** [comment]
moved to correct thread
