### ISSUE TITLE
stop and pause don't work when printing from prusaconnect (FW latest git 23-02-2024)

### ISSUE THREAD

**Issue by Ro3Deee** [prusa3d/Prusa-Firmware#4609]
**Printer type** - MK3S+
**Printer firmware version** - latest commit c5a036d817607dabc8d6cfe4f3c3b08269e7b465, self compiled (it happed with older commits)

**MMU upgrade** - MMU3
**MMU upgrade firmware version** -3.0.1 [disabled for this print]

prusalink 0.7.2
Prusa Connect SDK 0.7.1

**Prusaconnect** - fiels were send using prusa connect

**Describe the bug**
stop and pause from the printer menu don't work.
  
**To Reproduce**
  Send a print from prusaslicer using prusaconnect. 
 After it starts printing, try to use pause and stop from the printer display. 

It works from prusaconnect webpage, not from the printers display.
  
**Expected behavior**
 The prin should pause/stop.

  
**G-code**
happens every time, with all prints.
[bottom_0.3mm_PETG_MK3S_2h25m.zip](https://github.com/prusa3d/Prusa-Firmware/files/14389112/bottom_0.3mm_PETG_MK3S_2h25m.zip)

**Comment by 3d-gussner** [comment]
@petrubecheru We changed the actions to save few bytes. https://github.com/prusa3d/Prusa-Firmware/commit/c9aba688e3f3d95015d5d1a526c382b703353ddc and the responding PrusaLink version is 0.8.0alpha4 or the newest master https://github.com/prusa3d/Prusa-Link which you can also try to install.

If you want to keep PrusaLink 0.7.2 revert the `//action:<whatever>` to `// action:<whatever>` for your private build.

This is not a bug as the Prusa-Firmware/MK3 and PrusaLink/master are under constant development. So issues like this may happen.

The branch/firmware isn't fully tested, even we try to verify and test each PR before merging. Building and using the firmware from the development branch is of course at own risk.

As soon FW is released we ensure that the matching PrusaLink version is also released.

**Comment by Ro3Deee** [comment]
>Building and using the firmware from the development branch is of course at own risk.

I know. 

It also fires change filament routine multiple times on the first layer. I'll print from SD card to see if if happens again.
