### ISSUE TITLE
Version 3.1.1.198 confirm "default settings loaded" during every startup

### ISSUE THREAD

**Issue by derjungewilde** [prusa3d/Prusa-Firmware#461]
Hi,

I updated to latest version 3.1.1.198 from last weekend. Since than I have to confirm a message "default settings loaded" on the LCD screen every time. This is very annoying because I sometimes print remotely with octoprint and when I turn on my printer I'm not there to confirm this message. Without confirming octoprint will not establish a connection.

**Comment by Affas** [comment]
Same problem here, any suggestions?

**Comment by 3d-gussner** [comment]
Newest MK2.5 and MK3 stable firmware is 3.1.3 and for the MK2 3.1.0.
Where did you get 3.1.1.198 from?
UPDATE: Sorry it is an old issue from @derjungewilde 
@Affas Which printer and firmware do you have installed?

BTW: When you compile from the github you should change to one of these things in the 'Configuration.h' file to prevent LCD messages:

- following settings will generate LCD messages
#define FW_DEV_VERSION FW_VERSION_UNKNOWN
#define FW_DEV_VERSION FW_VERSION_DEGUB
#define FW_DEV_VERSION FW_VERSION_ALPHA
#define FW_DEV_VERSION FW_VERSION_BETA

- to get rid:
#define FW_DEV_VERSION FW_VERSION_RC
or
#define FW_DEV_VERSION FW_VERSION_GOLD

**Comment by Affas** [comment]
I am using Version 1.3.6 Octoprint and latest Prusa update for MKS2. Never experienced this on earlier setup

**Comment by 3d-gussner** [comment]
@Affas So you have the issues with OctoPrint and the MK2s firmware 3.1.0 from 12th November 2017?
There is a M110 fix which has been pulled by Prusa on 20th December 2017 but Prusa didn't publish yet a new firmware release with it.

You should try to compile it yourself from the github source code
or try my custom firmware https://github.com/3d-gussner/Prusa-Firmware/releases look for the MK2/S/MMU firmware https://github.com/3d-gussner/Prusa-Firmware/releases/tag/v3.1.0-001-HFM
If you choose my custom firmware PLEASE read the release notes!

**Comment by mwyborski** [comment]
Same problem here. I would like to know which default settings are meant? Because XYZ calibration is saved and definetly no default setting. So what should this message tell me? The default settings for which feature are loaded?

**Comment by 3d-gussner** [comment]
@robotrovsky Which printer and firmware version do you have?

**Comment by mwyborski** [comment]
@3d-gussner i have a prusa i3 mk2 with MMU and the latest official release 3.1.0

**Comment by 3d-gussner** [comment]
@robotrovsky Do you have that issue with SD or OctoPrint or both? If you use OctoPrint which version do you use? Latest official firmware release 3.1.0 from Nov 2017? If so read my comment above.

**Comment by mwyborski** [comment]
@3d-gussner Thank you for your support. Independent if i use OctoPrint or SD, whenever i turn on the printer i get the message. I read your comment and will consider to use your firmware. But actually i was only wondering to which setting the message refers. The default settings for which setting have been loaded? Do you know to which default setting the message refers?

**Comment by 3d-gussner** [comment]
@robotrovsky Check Marlin_main.cpp around line 1236

**Comment by mwyborski** [comment]
@3d-gussner Thank you very much! So it seems the reason is, that the version in the eeprom is wrong/old. I will try to save the settings with the M50X gcodes like described here:
https://github.com/MarlinFirmware/Marlin/wiki/EEPROM

**Comment by mwyborski** [comment]
BTW sending M502 followed by M500 like indicated in the EEPROM link removed "default settings loaded" message.
