### ISSUE TITLE
  [ENHANCEMENT] Ability to add SteelSheet selection in Footer line

### ISSUE THREAD

**Issue by Acidham** [prusa3d/Prusa-Firmware#4611]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** -MK3.5
**MMU Upgrade** - no

**Is your enhancement related to a problem? Please describe.**
  When printing on the new MK3.5 it is important to directly see which steel sheet is being configured (for z-settings) to avoid damage. 
  
**Describe the solution you'd like**
The ability to add selected steel sheet in footer line.

**Comment by 3d-gussner** [comment]
@Acidham This is the MK2.5/S and MK3/S/+ repository, please close the issue here and reopen it https://github.com/prusa3d/Prusa-Firmware-Buddy which is for MINI, MK4, XL, MK3.5 and MK3.9

**Comment by Acidham** [comment]
https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3789
