### ISSUE TITLE
  [ENHANCEMENT] Steelsheet configuration needs Satin steel sheet as an option

### ISSUE THREAD

**Issue by Acidham** [prusa3d/Prusa-Firmware#4612]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MK3.5
**MMU Upgrade** - no

**Is your enhancement related to a problem? Please describe.**
Available steelsheet configurations are only available for Smooth, Textured and Custom. 
  
**Describe the solution you'd like**
Please add Satin steel sheet to the selection

**Comment by 3d-gussner** [comment]
@Acidham This is the MK2.5/S and MK3/S/+ repository, please close the issue here and reopen it https://github.com/prusa3d/Prusa-Firmware-Buddy which is for MINI, MK4, XL, MK3.5 and MK3.9

**Comment by Acidham** [comment]
https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3788
