### ISSUE TITLE
[BUG]<Layer shift>

### ISSUE THREAD

**Issue by derfeznoj** [prusa3d/Prusa-Firmware#4623]
**Printer type** - [XL]
**Printer firmware version** -  [6.0.0-alpha+14120]

**MMU upgrade** - [e.g. MMU2S, MMU2, MMU1]
**MMU upgrade firmware version** - [e.g. 1.0.6, 1.0.6-RC2, ...]

**SD card or USB/Octoprint**
  Print from Prusa Slicer to XL USB via Ethernet

**Describe the bug**
  A layer shift was experienced twice (1 week apart) near layer 5, two different models. Just preceding layer shift I heard a loud 'chunk', but don't know what generated the sound.
  
**To Reproduce**
  Not reproducible on re-printing exact same file from USB
  
**Expected behavior**
  No layer shif
  
**G-code**
  Please attach a G-code. This will make it easier for us to replicate the error.

**Video**
  Please attach a video. It usually helps to solve the problem.
![IMG_1147](https://github.com/prusa3d/Prusa-Firmware/assets/120122941/2a86d69c-b159-464f-8745-a401ac40d368)
[Royal UR case T project_0.6n_0.32mm_PETG,PETG_XLIS_3h30m.bgcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/14476061/Royal.UR.case.T.project_0.6n_0.32mm_PETG.PETG_XLIS_3h30m.bgcode.zip)

**Comment by 3d-gussner** [comment]
@derfeznoj Thanks, but this is the issue tracker for the MK2.5/S and MK3/S/+ 8-bit firmware. Please close it here and open the ticket in [here](https://github.com/prusa3d/Prusa-Firmware-Buddy)
