### ISSUE TITLE
[FEATURE REQUEST] Add support for long filenames to M28

### ISSUE THREAD

**Issue by Patronics** [prusa3d/Prusa-Firmware#4626]
**Printer type** - All
**MMU Upgrade** - N/A

**Is your feature request related to a problem? Please describe.**
  It's frustrating how with OctoPrint, existing files on the SD card show up fine with the full filename, but when uploading files via OctoPrint they're given the truncated 8.3 filenames. Manually attempting to create a longer filename via M28 gives the following error messages:
```
Send: M28 LONGFILENAMETEST.GCODE
Recv: echo:Now fresh file: LONGFILENAMETEST.GCODE
Recv: open failed, File: LONGFILENAMETEST.GCODE.
```

**Describe the solution you'd like**
Support for creating files on the sdcard with names longer than 8.3 characters. [Marlin has has this feature since 2022.](https://github.com/MarlinFirmware/Marlin/pull/23526).

Additionally, if other metadata could be written such as creation timestamps, that would also be very helpful, arguably moreso than the long filename alone.

**Comment by 3d-gussner** [comment]
@Patronics Thanks for the suggestion. The firmware is based on an old Sd2Card library and would need a lot of resources.  This won't be implemented except a volunteer is willing to provide a pull request.
