### ISSUE TITLE
[QUESTION]<get a error when trying to run „python .\utils\bootstrap.py“>

### ISSUE THREAD

**Issue by KingJulian97** [prusa3d/Prusa-Firmware#4627]
Hey Guys,

want to compile Prusa-Firmware-3.13.2 for my MK3S, but I get a error when trying to run „python .\utils\bootstrap.py“.

I have only little understanding of programming except of getting Marlin Firmware configured ;-), I try to give you all informations required. Please let me know if is something missing.

Using Mac OS Monterey 12.7.3; VS Code Version: 1.87.0; Python 3.12 - installed with homebrew, also virtual evn via pip; Xcode library 

I‘m googling und trying/testing for weeks now, but nothing worked so far or maybe I understood it not the right way.

Thanks for your help! I really appreciate it!

![Screenshot_VS-Code](https://github.com/prusa3d/Prusa-Firmware/assets/162431185/09f0478f-aea6-4e94-bbd0-021f7a043c8d)

**Comment by 3d-gussner** [comment]
@KingJulian97 Please verify that `python --version` shows `Python 3.12.x` 
The `python .\utils\bootstrap.py` is for Windows please look at the Linux section of the README.
I don't have any MAC OS but please try to execute `./utils/bootstrap.py`

Also not sure if these works on MAC OS Monterey
- https://github.com/ninja-build/ninja/releases/tag/v1.10.2 the `ninja-mac.zip`
- https://github.com/Kitware/CMake/releases/tag/v3.22.5 the `cmake-3.22.5-macos-universal.tar.gz`
- https://www.microchip.com/en-us/tools-resources/develop/microchip-studio/gcc-compilers `avr8-gnu-toolchain-osx-3.7.0.518-darwin.any.x86_64.tar.gz`

**Comment by KingJulian97** [comment]
@3d-gussner thanks a lot for your fast reply! 
That was the issue, somehow I managed to get stuck to the "VS-Code" in the title and did not noticed the underlaying "windows" anymore.

Have a nice day!

**Comment by 3d-gussner** [comment]
Please close this issue. BTW FW 3.13.3 is released please use this https://github.com/prusa3d/Prusa-Firmware/tree/v3.13.3 as your base to build the firmware.
