### ISSUE TITLE
[BUG] No heat in hotend after X crash

### ISSUE THREAD

**Issue by a3acx** [prusa3d/Prusa-Firmware#4631]
Printer type - [Prusa i3 MK3S+ with MMU3]

Printer firmware version - [3.13.3]

Original or Custom firmware - [Original]

Optional upgrades - [MMU3]

USB drive or USB/Octoprint
SD CARD

Describe the bug
When an X, Y, or Z crash occurs, the printer does not heat up when I try to unload the filament into the MMU3.

How to reproduce
Do an X, Y, or Z crash and select not to continue the print

Expected behavior
The MMU will attempt to unload the filament even though the extruder is not heated

**Comment by 3d-gussner** [comment]
@anandsathy Thanks for bug report, it has been addressed and will be in FW 3.14.0.
Please consider to close it.

**Comment by a3acx** [comment]
Thanks!
--
Anand Sathy
Student
Class of 2030

*Westminster*
1424 West Paces Ferry Road, NW
Atlanta, GA 30327
P. 404.998.7567
