### ISSUE TITLE
Issues with 0,6mm nozzle Prusa MINI

### ISSUE THREAD

**Issue by pukspuks** [prusa3d/Prusa-Firmware#4636]
Original Prusa Mini +
FW 5.1.2.
Recently updated from 4.4.1
Nozzle 0,6mm

1. DO not get Nozzle diameter warning. After FW update nozle diameter set to 0,4mm previous settings 0,6mm
2. No warning about mismatch, warnings activated.
3. Significant underextrusion on models used earlier. G-CODE in attachment.

[AIS.CABLE.3D.BR.SET MINI GST PLA 240313_0.6n_0.3mm_PLA_MINI_3h15m.zip](https://github.com/prusa3d/Prusa-Firmware/files/14597065/AIS.CABLE.3D.BR.SET.MINI.GST.PLA.240313_0.6n_0.3mm_PLA_MINI_3h15m.zip)

**Comment by 3d-gussner** [comment]
@pukspuks This is the repository for the MK2, MK2.5/S and MK3/S/+ 8-bit printers. Please close your issue here and open it at https://github.com/prusa3d/Prusa-Firmware-Buddy which is for the MINI, MK3.5/9, MK4, XL 32-bit printers
