### ISSUE TITLE
[QUESTION]<Enter comprehensive title>

### ISSUE THREAD

**Issue by Sid-Dimarco** [prusa3d/Prusa-Firmware#4652]
Please, before you create a new question, please make sure you searched in open and closed issues and couldn't find anything that matches.

**What is your question?**
Problems nozzle heating

**Comment by 3d-gussner** [comment]
@Sid-Dimarco Can you please write a detailed issue you have with nozzle heating? Also feel free to use the Prusa 24/7 Chat as they may help you as well https://www.prusa3d.com/

**Comment by 3d-gussner** [comment]
Closing due to lack of interaction.
