### ISSUE TITLE
Set 'Unload Filament' min temp based on goal temp

### ISSUE THREAD

**Issue by mrjohnc** [prusa3d/Prusa-Firmware#466]
**Problem**: A couple of times I have accidentally pressed unload filament whilst the printer is warming up above the min temp required to start the filament unload but below the temperature that leads to a successful unload. This means a lump of plastic gets clogged in the extruder and I have to take the whole thing apart to get it out which takes ages. 

**Solution 1**: based the safe unload temperature on the material used, set the safe unload temperature is based on the temperature the printer is trying to get to at that time. Also to raise the safe unload temperature overall, I've unloaded PLA and had a blockage before. I realise this solution is not perfect, that the filament in the machine may be different to the filament you want to load but it would lead to less issues than currently. 

**Solution 2**: The other option would be to raise the unload temperature to around 200C, this would allow safe unload of PLA, ABS and most other materials. 

Thanks

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete.

Marina Curzi
Prusa Research
