### ISSUE TITLE
[BUG]<Random color changes on MK3S+ throughout print since 3.13.3-7094>

### ISSUE THREAD

**Issue by jgarrettg** [prusa3d/Prusa-Firmware#4664]
Since upgrading to 3.13.3-7094 My MK3S+ does random color changes throughout the print sometimes.  I'm not running an MMU.

**Comment by 3d-gussner** [comment]
@jgarrettg Please contact Prusa Support as this looks like cable connection issues. Same in https://github.com/prusa3d/Prusa-Firmware/issues/4665.

**Comment by 3d-gussner** [comment]
Closing due to lack of interaction.
