### ISSUE TITLE
[BUG]<Mk3S+ winks out during bed leveling since 3.13.3-7094 upgrade>

### ISSUE THREAD

**Issue by jgarrettg** [prusa3d/Prusa-Firmware#4665]
Mk3S+ winks out during bed leveling since 3.13.3-7094 upgrade.  Both thermistors report 0 degrees and it kicks off a mintemp error.  Files sliced with Prusa Slicer 2.7.4

**Comment by 3d-gussner** [comment]
@jgarrettg Please contact Prusa Support as this looks like cable connection issues. Same in https://github.com/prusa3d/Prusa-Firmware/issues/4664.

**Comment by 3d-gussner** [comment]
Closing due to lack of interaction.
