### ISSUE TITLE
  [ENHANCEMENT]<Prusa XL MultiTool - Cancel Object to stop unneeded toolhead changes and purging>

### ISSUE THREAD

**Issue by brianirwin** [prusa3d/Prusa-Firmware#4669]
**Printer type** Prusa XL 5-Tool, Prusa Slicer 2.7.4+win64, Firmware 5.1.2.

**Is your enhancement related to a problem? Please describe.**
If you cancel all objects in a print that require a tool-change, on subsequent layers the printer still switches tool, primes the no longer needed tool(s) on the wipe tower and then switch back to the tool that is required. Wipes on the tower, and resumes the print.

**Describe the solution you'd like**
Once all objects that are required for a tool are cancelled, the printer should not grab / prime that tool again. If only a single tool is now required, no further use of the purgeblock/wipetower should be done.

**Comment by 3d-gussner** [comment]
@brianirwin This is the repository for MK2, MK2.5/s and MK3/S/+ printers. Please reopen your issue [here](https://github.com/prusa3d/Prusa-Firmware-Buddy) 

Closing as wrong repository
