### ISSUE TITLE
[BUG]Prusa Mini firmware 6.0.0 error #12604 firmware file missing

### ISSUE THREAD

**Issue by richtw370** [prusa3d/Prusa-Firmware#4673]
I am running boot loader 2.3.4 and firmware 6.0.0 on my Prusa Mini.

If I start up with no USB inserted there is no issue

If I start up with the usb drive with all my files I get error #12604 firmware file missing in the USB drive.

Same behavior was found in lower version of firmware.

Copying the firmware file to the usb seems to prevent the error

**Comment by ggppjj** [comment]
You will want to open this on the mini firmware github, as this is the MK3S+ firmware page. 

Link: https://github.com/prusa3d/Prusa-Firmware-Buddy

**Comment by 3d-gussner** [comment]
Wrong repository
