### ISSUE TITLE
[FEATURE REQUEST] Improved filament change process when changing material types requiring lower temps.

### ISSUE THREAD

**Issue by KrisasMan** [prusa3d/Prusa-Firmware#4675]
Improve filament change process when changing from a high temp filaments to lower temp filaments to avoid high temp residue causing nozzle clogs.

If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** - [MK3.5, MK3.9, MK4, XL, mini] Any printer with 32 bit xBuddy board and similar

**Is your feature request related to a problem? Please describe.**
When changing from higher temp filaments such as PETG, ABS, or PC Blend, I often get partial or full clogs if I don't modify the filament load process when returning to PLA.  The fix has been I load the PLA into the printer but when queried I tell it I am loading PETG (if that is what I last used).  I then purge until the color has changed, as well as 2 more purges.  I then unload the filament and reinsert it.  This time when asked the filament type I tell it I am loading PLA and purge until the temp is down to PLA temps.
  
**Describe the solution you'd like**
Since the xBuddy on my MK4 clearly tracks what type of filament I currently have loaded, I would like to have it also track the 'last filament type loaded' so that when it detects a reduction in filament temp it can do the following procedure.
- When unloading filament the material type is stored in a 'last loaded type' variable
- When filament is loaded and the material type is different selected by the user and the new material prints at a lower temp than the prior one the following procedure is followed:

1. Message to user 'Filament type is lower than prior type, enhanced purge' or similar.
2. Nozzle is heated up to the temperature for the 'last loaded type'
3. Purge procedure is run as normal but continues for 2-3x the normal purge
4. Nozzle is set to the new material's lower temperature and purging continues until the new lower temp is reached (to prevent cooking the new filament in the nozzle).
5. User is prompted for color change accuracy as usual with the Yes, Purge More, Retry options.

**Comment by 3d-gussner** [comment]
@KrisasMan This is the repository for 8-bit MK2.5/S and MK3/S/+ printers please open your feature request in the 32-bit Prusa-Firmware-Buddy repository https://github.com/prusa3d/Prusa-Firmware-Buddy
