### ISSUE TITLE
Thanks for your feedback.

### ISSUE THREAD

**Issue by mobil750** [prusa3d/Prusa-Firmware#4676]
Thanks for your feedback.
This issue has the developers' attention.

Michele Moramarco
Prusa Research

_Originally posted by @Prusa-Support in https://github.com/prusa3d/Prusa-Firmware/issues/4380#issuecomment-1967680331_

**Comment by mobil750** [comment]
When will be there a fix? I don't think that this can be a big thing because in earlier versions it worked like a charm ...

mobil750

**Comment by 3d-gussner** [comment]
@mobil750 I am closing this issue tracker as #4380 is still active and we don't need a duplicate.
