### ISSUE TITLE
MK4 MMU3 0,25 mm nozzle profile for PS

### ISSUE THREAD

**Issue by Tadyzz** [prusa3d/Prusa-Firmware#4680]
**Printer type** - MK4
**MMU Upgrade** - MMU3

Hello guys,

It´s possible that Prusa create 0,25 mm nozzle profile for MK4 MMU3 (for PrusaSlicer)?. Right now we are waiting for our MMU3 but after we receive that upgrade we need to print 300+ 4colour key chains. Due to the small dimensions we chose to print with 0,25mm nozzle.

**Comment by 3d-gussner** [comment]
@Tadyzz This is the MK2.5/S and MK3/S/+ repository. I would guess best place to request any PrusaSlicer settings is [here](https://github.com/prusa3d/PrusaSlicer-settings) and maybe [here](https://github.com/prusa3d/PrusaSlicer)

**Comment by 3d-gussner** [comment]
@Tadyzz You are aware that the smaller nozzle and also smaller layer height will increase the print time and wipe tower by a huge factor?
Here a short example with 5x5x5 cubes:
MK3S+MMU3
0.4 nozzle and 0.2mm layer height
![image](https://github.com/prusa3d/Prusa-Firmware/assets/25530011/d39e1701-6ddd-4eae-88a7-39fcba3283d2)
vs 0.25 nozzle and 0.1mm layer height 
![image](https://github.com/prusa3d/Prusa-Firmware/assets/25530011/1ed3ed78-0b07-4710-8477-c42492c9aefa)

**Comment by Tadyzz** [comment]
> @Tadyzz This is the MK2.5/S and MK3/S/+ repository. I would guess best place to request any PrusaSlicer settings is [here](https://github.com/prusa3d/PrusaSlicer-settings) and maybe [here](https://github.com/prusa3d/PrusaSlicer)
Ah ok...i had a link from prusa support..:)

**Comment by Tadyzz** [comment]
> @Tadyzz You are aware that the smaller nozzle and also smaller layer height will increase the print time and wipe tower by a huge factor? Here a short example with 5x5x5 cubes: MK3S+MMU3 0.4 nozzle and 0.2mm layer height ![image](https://private-user-images.githubusercontent.com/25530011/329954710-d39e1701-6ddd-4eae-88a7-39fcba3283d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTc4NDMsIm5iZiI6MTcxNTU5NzU0MywicGF0aCI6Ii8yNTUzMDAxMS8zMjk5NTQ3MTAtZDM5ZTE3MDEtNmRkZC00ZWFlLTg4YTctMzlmY2JhMzI4M2QyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEwNTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNWUxYWJlYzdkYmYwYmUzOTk2NWY0ZjI2Yjg0YTM5ZmI3NWIxNzdkM2ZjZTNjN2NiNGVhNmJmNTY1NTQ4ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rlfz46MLcz28UPD8l-n8b-I3Cq_y0KlDTuepAnurQMo) vs 0.25 nozzle and 0.1mm layer height ![image](https://private-user-images.githubusercontent.com/25530011/329955224-1ed3ed78-0b07-4710-8477-c42492c9aefa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTc4NDMsIm5iZiI6MTcxNTU5NzU0MywicGF0aCI6Ii8yNTUzMDAxMS8zMjk5NTUyMjQtMWVkM2VkNzgtMGIwNy00NzEwLTg0NzctYzQyNDkyYzlhZWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEwNTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMmU2NjRhMmNmY2IwZmY3ZTE5OTdiMjJmZTE5MWE4MWIwOWVkYTZhMGRkZGM4MThjMGZiODc0OGY2YzI2YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KF7yRMJ0VfVRZL5GlZWW_lC1p0Or_3PXBBY1vMeeh7Q)

I know that..but i need to print 300+ pcs 4 colour key chains..there are few small details...maybe i try to make a new 3D model for 0,4mm nozzle...

**Comment by 3d-gussner** [comment]
> I know that..but i need to print 300+ pcs 4 colour key chains..there are few small details...maybe i try to make a new 3D model for 0,4mm nozzle...

I have found one tester having great results with the MK4 0.25 nozzle and MMU3 but that wasn't an official test.

**Comment by 3d-gussner** [comment]
Closing as wrong repository.
