### ISSUE TITLE
[BUG] MK3 When in the Pause state, Unload Filament is absent from the menus.

### ISSUE THREAD

**Issue by DavidPhillipOster** [prusa3d/Prusa-Firmware#4694]
**Printer type** - MK3
**Printer firmware version** -  3.13.3

**MMU upgrade** - no

**SD card**

**Describe the bug**
MK3 When in the Pause state, Unload Filament is absent from the on-printer menus.
  
**To Reproduce**

* During printing, I notice that there is problem with the current filament, example: a knot 1 meter from the extruder.
* I pause the print.
* I look through the on-printer menus for **Unload Filament** so I can unload the filament, fix the problem, and load filament.
* **Unload Filament** is not present. 

I have cases where I could not trust the filament out sensor, so I want to be able to unload the filament manually.
  
**Expected behavior**
In the Pause state, **Unload Filament** should be on the main menu. (I remember that it used to be there, but not now.)

**Comment by 3d-gussner** [comment]
@DavidPhillipOster During Pause you can use the LCD Tune -> Change filament menu.
