### ISSUE TITLE
[BUG FW3.13.3 Revo6] degree character in the file name of the gcode on sdcard

### ISSUE THREAD

**Issue by juckendesAuge** [prusa3d/Prusa-Firmware#4695]
Printer: MK3+ with Revo6 Hotend

Firmware: 
E3DREVO_fw_MK3S_MK3S+_3_13_3_7094.hex

Issue:
The degree sign (°) exactly at this point is the problem.
If I remove the character, it can be printed directly without errors.

I have also moved the character to the back to test it.
This is how I namend the file for testing:
240C drippy_0.2.mm_PETG_°_MK3S_3h24m.gcode
There was no error message here.

Maybe the number in front of it is disturbing. But this is just a shot in the dark.

Edit:
Similar from 2020? It is closed.
https://github.com/prusa3d/Prusa-Firmware/issues/2654

![uebersicht](https://github.com/prusa3d/Prusa-Firmware/assets/24550429/c12ea0f1-2d1a-42d8-95a1-d8f37c8018a8)
[240C drippy_0.2mm_PETG_MK3S_3h24m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/15461696/240C.drippy_0.2mm_PETG_MK3S_3h24m.gcode.zip)

**Comment by 3d-gussner** [comment]
@juckendesAuge Thanks, Dankeschön, for the quite detailed issue.

Please use only `aA-zZ`, `0-9` and `._-` characters in file names. The reason you get an error is that the printer uses 8.3 filenames and this special char `°` in the beginning probably causes the issue.

We will not fix that as we have limited resources and need to keep these free for other feature requests.

Please close this issue.
