### ISSUE TITLE
  [ENHANCEMENT]<MK4 Z-height Display>

### ISSUE THREAD

**Issue by James-G4CLF** [prusa3d/Prusa-Firmware#4697]
My MK2 and my MK3 display their current Z-height while printing - this is convenient, especially when expecting a pause for nut/magnet insertion or filament change. My MK4 does not. I know I can see it on the dashboard, but often my computer is off while I am printing.

Please include this display with the next firmware upgrade.

It is possible that this feature is available - but if so I have been unable to turn it on - therefore it is badly indexed in that searches do not reveal how to enable it.

In this case please make it easier to find.

**Comment by mix579** [comment]
You can customize what you see on the display footer in the LCD menu settings, including Z height

**Comment by James-G4CLF** [comment]
Thank you - problem fixed, and first nut embedded on time!

But the manual should make it clearer that you can do this - and how.

**Comment by James-G4CLF** [comment]
Thank you very much - I hadn't found this - now displaying Z-height as wanted.

James



At 18:14 31/05/2024, you wrote:-
