### ISSUE TITLE
[BUG]M< Error message at end of every Print>

### ISSUE THREAD

**Issue by DavidAIsom** [prusa3d/Prusa-Firmware#4702]
**Printer type** - [MK3.5]
**Printer firmware version** -  [6.02..]

**MMU upgrade** - [e.g. MMU3]
**MMU upgrade firmware version** - [3.0.3.]

**SD card is used for printing 
  

**Describe the bug**
  At the end of every print message appears 
![IMG_2756](https://github.com/prusa3d/Prusa-Firmware/assets/58168488/1d371811-d0b3-49a8-ba01-7e671c115ee2)

**To Reproduce**
  Once a few filament loading errors have been made and detected this message appears and won’t go away …..ever 

**Expected behavior**
  The only way to clear message on MK3.5  is to do a factory reset.  All will then  be ok until you get any more errors and then  it returns. With MK4 @cupajoe24 has found an option in the firmware to clear this counter/bit.

There's a reset in "Settings > Hardware > Nextruder Maintenance

We need a similar option for MK3.5
![IMG_2756](https://github.com/prusa3d/Prusa-Firmware/assets/58168488/fc39128a-6a59-48a2-9873-644fe579c8a6)

**G-code**
  Please attach a G-code. This will make it easier for us to replicate the error.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by MarkusReichart** [comment]
Opened in wrong repository. Should be moved to Prusa-Firmware-Buddy. Nevertheless I have the same problem. After fixing a loose filament sensor, this warning persists.

**Comment by 3d-gussner** [comment]
@DavidAIsom This is the MK3/S/+, MK2.5/S repository, as you refer to the MK3.5 and FW 6.0.2 please close this issue here and reopen it in the 32-bit MINI, MK3.5, MK3.9, MK4, XL repository https://github.com/prusa3d/Prusa-Firmware-Buddy

**Comment by 3d-gussner** [comment]
Wrong repository closing it.
