### ISSUE TITLE
FIrmware should check filament sensor before nozzle change

### ISSUE THREAD

**Issue by dangerweenie** [prusa3d/Prusa-Firmware#4703]
MK3

I often forget to unload filament before beginning nozzle change heatup, which leads to clogs due to the 280c heatup.

Would be very very simple for FW to simply check filament sensor and/or remind user to unload filament before heating up for nozzle swap.

**Comment by 3d-gussner** [comment]
@dangerweenie Thanks for the idea. Can't promise anything but mark it for FW 3.14.1

**Comment by 3d-gussner** [comment]
@dangerweenie FYI @sarusani PR has been merged and will be in FW 3.14.1
