### ISSUE TITLE
[BUG]<Prusa Connect Cancel Objects Some Are Not Visible and not clickable>

### ISSUE THREAD

**Issue by Sk4nk-Hunt** [prusa3d/Prusa-Firmware#4705]
**Printer type** - [Prusa Connect/ XL]
**Printer firmware version** -  [6.0.0]

**USB**

**Describe the bug**
  In Connect.prusa (prusaLink) If you have a hollow object like a cylinder and place a smaller object in the hole/gap of the cylinder. IN Prusa Connect when you go to cancel objects THE inner object inside the cylinder is not visible.
**To Reproduce**
  -Create cylinder with a center hole. 
  -Within the cylinder create a smaller object with in that hole/gap
  -Send to XL printer
  -Start Print
-Select the tab/ section where it allows you to cancel object inside of Prusa Connect of the current print. 
-Notice how the inner object Is not visible properly inside the cylinder.
-Cancel Cylinder object
-Revealing the Smaller object within also not being able to select with mouse inner objects. 

**Expected behavior**
  The cylinder is being acted in an outline for but the Slicer or Prusa Connect is not considering the gap as a negative value to properly display it inside the Cancel objects section. It sees it as only a solid object. 

**G-code**
 None

**Video**
https://we.tl/t-JRrsCragOP

**Comment by 3d-gussner** [comment]
@Sk4nk-Hunt This is the MK3/S/+, MK2.5/S repository, as you refer to the XL please close this issue here and reopen it in the 32-bit MINI, MK3.5, MK3.9, MK4, XL repository https://github.com/prusa3d/Prusa-Firmware-Buddy

**Comment by 3d-gussner** [comment]
Wrong repository closing it.
