### ISSUE TITLE
Printer model check problem.

### ISSUE THREAD

**Issue by jam2606** [prusa3d/Prusa-Firmware#4712]
### Description of the bug

al crear un archivo con prusa slicer 2.8.0 para mi mk3s+ com firmware 3.14.0 y mmu2s con firmware 3.0.2 y con el perfil de mk3s+ con mmu2 s ya sea en modo un filamento o multicolor al mandarlo a la impresora me dice que el archivo es para otra maquina

when creating a file with prusa slicer 2.8.0 for my mk3s+ with firmware 3.14.0 and mmu2s with firmware 3.0.2 and with the profile of mk3s+ with mmu2s either in single filament or multicolour mode when sending it to the printer it tells me that the file is for another machine.

### Project file & How to reproduce

![IMG_2014](https://github.com/prusa3d/PrusaSlicer/assets/133910560/66bbb9f5-21df-4a15-8780-09f71cb5587a)
![IMG_2015](https://github.com/prusa3d/PrusaSlicer/assets/133910560/a6618bd6-ce71-4d41-aad6-e5451a640ae5)
![IMG_2016](https://github.com/prusa3d/PrusaSlicer/assets/133910560/95a34e50-d3a4-4278-b4c5-76fa46fd96ef)
![IMG_2018](https://github.com/prusa3d/PrusaSlicer/assets/133910560/45154b3b-c4b8-4401-ae36-61c776032062)
![IMG_2021](https://github.com/prusa3d/PrusaSlicer/assets/133910560/4084b2b5-7cbc-421f-b956-55ae7493c664)
![IMG_2022](https://github.com/prusa3d/PrusaSlicer/assets/133910560/043c9ff9-6117-46d7-98f0-9d9d0ea792dc)
![IMG_2023](https://github.com/prusa3d/PrusaSlicer/assets/133910560/6a5112cc-7828-470b-bc59-09e87356642b)
![IMG_2024](https://github.com/prusa3d/PrusaSlicer/assets/133910560/f609fa5e-7792-4f8d-85e6-32f5a4e3dec7)
![IMG_2025](https://github.com/prusa3d/PrusaSlicer/assets/133910560/84541c53-8e10-469e-a045-189834c04a26)
![IMG_2026](https://github.com/prusa3d/PrusaSlicer/assets/133910560/1f836c3d-edaf-461b-9191-aeb636983a52)
![IMG_2028](https://github.com/prusa3d/PrusaSlicer/assets/133910560/41802b07-8e76-443b-96db-606f547b3c5c)
![IMG_2029](https://github.com/prusa3d/PrusaSlicer/assets/133910560/d285e512-64b1-426b-9264-32f7ae941ed6)
![IMG_2030](https://github.com/prusa3d/PrusaSlicer/assets/133910560/3862ece2-bb1d-4c90-bff1-ae7d5ff6fe97)
![IMG_2032](https://github.com/prusa3d/PrusaSlicer/assets/133910560/80df62c6-e22f-4cec-9a58-8b025fa2c5b7)

### Checklist of files included above

- [ ] Project file
- [ ] Screenshot

### Version of PrusaSlicer

2.8.0

### Operating system

windows 11

### Printer model

mk3s+ con mmu2s

**Comment by rtyr** [comment]
The g-code output uses correct printer model (for years), so it seems like some FW issue.
`M862.3 P "MK3SMMU2S" ; printer model check`

**Comment by 3d-gussner** [comment]
@jam2606 Thanks for reporting this issue.
I just tested FW 3.14.0+8066 (hash b97131bd) + MMU3 3.0.2 on MK3S+ with the [MK3S hex file](https://github.com/prusa3d/Prusa-Firmware/releases/download/v3.14.0/MK3S_MK3S+_FW_3.14.0_MULTILANG.hex).

Also used PrusaSlicer 2.8 with newest profiles` Original Prusa MK3S & MK3S+ MMU3 Single` to sclice a 25x25x2 cube and sent it to the printer. No warning that the gcode is sliced for wrong printer.

Please ensure that you have flashed the printer with the `MK3S MK3S+` firmware and not the `MK3` hex file, which would explain the issue.

Gracias por informar de este problema.

Acabo de probar FW 3.14.0 + MMU3 3.0.2 en MK3S+ con el [MK3S hex file](https://github.com/prusa3d/Prusa-Firmware/releases/download/v3.14.0/MK3S_MK3S+_FW_3.14.0_MULTILANG.hex).
Tambien use PrusaSlicer 2.8 con los perfiles mas nuevos Original Prusa MK3S & MK3S+ MMU3 Single para sclice un cubo 25x25x2 y lo envie a la impresora. No hay advertencia de que el gcode es rebanado para la impresora equivocada.

Por favor, asegúrate de que has flasheado la impresora con el firmware `MK3S MK3S+` y no con el archivo hexadecimal `MK3`, lo que explicaría el problema.

**Comment by ojrik** [comment]
> ) + MMU3

MK3S+ FW 3.14.0 - MMU3 FW 3.0.2
It is no longer compatible with SLICER Profil MK3S+ MMU2S. The printer will report an error in the G-code. For MMU from FW 3.0.2 Slicer Profile MK3S+ MMU3 should be used.

Firmware settings for MK3S+:
// Printer revision
#define PRINTER_TYPE PRINTER_MK3S
#define PRINTER_NAME PRINTER_MK3S_NAME
#define PRINTER_NAME_ALTERNATE PRINTER_MK3_NAME //the other similar printer to this.
#define PRINTER_MMU_TYPE PRINTER_MK3S_MMU3
#define PRINTER_MMU_NAME PRINTER_MK3S_MMU3_NAME
#define FILAMENT_SIZE "1_75mm_MK3S"
#define NOZZLE_TYPE "E3DREVO"

// Printer name
#define CUSTOM_MENDEL_NAME "Prusa i3 MK3S+R"

**Comment by XSSammy** [comment]
I have the same issue same printer with a mmu2s.  @ojrik I haven't tried printing with the mmu3 profile but I can confirm it doesn't report the same error if I use that profile.

**Comment by ojrik** [comment]
FW from 3.0.0 to 3.0.3 is for MMU3 device. If you use the mmu2s profile, the G-Code will be for a different type of printer. I have MK3.5 MMU3, MK3S+ MMU2S, MK3S MMU3 Ulti multi everywhere I use SLICER profile for MMU3. By the way, I made g-cod for MK3S+ MMU2S and started printing on my MK3S+ FW 3.14.0 - MMU2S FW 3.0.2 device reported G-Code error for different printer type.

@3d-gussner  also used a profile for MMU3 and no report.

@XSSammy do you have a similar but different report?

**Comment by ojrik** [comment]
A small note, if you just flashed FW 3.0.2 to the MMU2S device without UPGRADE, you already have MMU3.
