### ISSUE TITLE
[BUG]MMU3 manual filament load fail due improper possition

### ISSUE THREAD

**Issue by vogll** [prusa3d/Prusa-Firmware#4713]
**Printer type** - MK3S+
**Printer firmware version** - 3.14.0

**MMU upgrade** - MMU3
**MMU upgrade firmware version** - 3.0.2

**SD card or USB/Octoprint**
via SD card

**Describe the bug**
Manual changing position to 2 via button from position 1 followed manual action to load filament caused improper moving idler to position 1 

**To Reproduce**
Power On. Move to possition 1. Move to possition 2. Press middle button to lad filament. Idler change angle to possition 1. Diode on the panel and carriage are in the possition 2.

**Expected behavior**
 Idler didn't move to right position

**G-code**
Manual 

**Video**

**Comment by cugnonr** [comment]
Same issue for me. 
Same firmware versions on printer and MMU2S

**Comment by gudnimg** [comment]
I'm unable to reproduce this issue.

My steps:

1. After homing the selector starts at position 5 (far right side).
2. I select the left button until it reaches slot 1.
3. Select right button to move the selector to slot 2
4. Select middle button to start loading -- inspect idler at the same time
5. Idler bearing is correctly moving to slot 2 such that the bearing is on top of the pulley gears.
