### ISSUE TITLE
3.1.1-RC5-150: Extruder crashes into bed after sending "Off" command in Pronterface

### ISSUE THREAD

**Issue by eriksogge** [prusa3d/Prusa-Firmware#473]
I hope this is the correct way to report a potential bug in the firmware.

When I was printing with Pronterface over USB i clicked "Off" in the interface. This resulted in the print stopping, the display on MK3 saying "Crash detected", the extruder homing and crashing severely into the bed. The extruder pushed down so hard that the bed was bending down. I had to quickly disconnect power to stop the motors from pushing further down.

This is the output from Pronterface:
```
echo:busy: processing
tmc2130_init(), mode=STEALTH
Print paused at: 14:23:43
; Motors off
SENDING:M84
; Extruder off
SENDING:M104 S0
; Heatbed off
SENDING:M140 S0
; Fan off
SENDING:M107
; Power supply off
SENDING:M81
echo:busy: processing
start
echo: 3.1.1-RC5-150
echo: Last Updated: Jan 17 2018 22:04:15 | Author: (none, default config)
Compiled: Jan 17 2018
echo: Free Memory: 1811  PlannerBufferBytes: 1312
echo:Hardcoded Default Settings Loaded
adc_init
CrashDetect ENABLED!
tmc2130_init(), mode=STEALTH
PAT9125_init:1
FSensor
DISABLED
echo:SD card ok
echo:enqueing "CRASH_DETECTED"
echo:enqueing "G28 X"
echo:enqueing "G28 Y"
echo:enqueing "CRASH_RECOVER"
echo:busy: processing
INT4
start
echo: 3.1.1-RC5-150
echo: Last Updated: Jan 17 2018 22:04:15 | Author: (none, default config)
Compiled: Jan 17 2018
echo: Free Memory: 1811  PlannerBufferBytes: 1312
echo:Hardcoded Default Settings Loaded
adc_init
CrashDetect ENABLED!
tmc2130_init(), mode=STEALTH
PAT9125_init:1
FSensor
DISABLED
echo:SD card ok
```
I'm not sure if the output displays info after I turned the power on again. I have not tried to replicate this error due to the potential damage of the bed.

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete.

Marina Curzi
Prusa Research
