### ISSUE TITLE
[BUG] Display remaining time for color change on the LCD screen

### ISSUE THREAD

**Issue by majedation** [prusa3d/Prusa-Firmware#4734]
**Printer type** - MK3S
**Printer firmware version** -  3.14.0

**SD card or USB/Octoprint**
  SD Card

**Describe the bug**
  In the previous firmwares, the MK3S showed the remaining time for color change; it toggled every few seconds between the remaining time for the print (##:##R) and the remaining time for color change (##:##C). However, the remaining time for color change isn't showing in firmware 3.14.0.

**To Reproduce**
  Add color change at specific layer.

**Expected behavior**
  The MK3S should show the remaining time on the LCD screen and keep toggling between the remaining time for print and the remaining time for color change.

**Comment by 3d-gussner** [comment]
@majedation Thanks for the bug report. It is not an issue with the FW 3.14.0 firmware as injecting `M73 C1` while printing will show on the LCD the `##:##R` and `00:01C`.

During testing I have found that PrusaSlicer 2.8 generates the M73 gcodes but `C` is always 0 which means that **NO** filament changes are expected in normal mode. At the same time the `D` parameter has some value decreasing over time, but this is only shown in Silent mode.

```
M73 P0 R27
M73 C0
M73 Q0 S27
M73 D3
....
M73 P1 R26
....
M73 D2
....
```

I will report this issue to the PrusaSlicer team.

**Comment by 3d-gussner** [comment]
@majedation Please consider to close this issue as it is not firmware related.

**Comment by 3d-gussner** [comment]
@majedation FYI found an internal ticket and :crossed_fingers: it will be solved in next PrusaSlicer version

**Comment by 3d-gussner** [comment]
@majedation FYI it is back working in [Prusa-Slicer 2.9.1-alpha1](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.9.0-alpha1) 
![image](https://github.com/user-attachments/assets/7cd54c3a-180b-4707-bcc0-e3086fd3fe0e)

**Comment by samdurnxn** [comment]
It works only for M60x gcode. 
For multimaterial painting, the slicer add Tx gcode but not M73 Cx or M73 Dx
Bug is not solved entirely.

is it possible to reopen the ticket ?

**Comment by 3d-gussner** [comment]
@samdurnxn No need to open it here as it is a Prusa Slicer issue. I will send the new info to PrusaSlicer team.

Can you share the 3mf file where it still fails? Does that work in and older version of PS?

**Comment by 3d-gussner** [comment]
I am not sure if PrusaSlicer ever calculated the Time to change with MMU prints. Do you have an example where it worked?

**Comment by samdurnxn** [comment]
No, I havn't a working example. As it work with M600, I thought that the way it calculate will be the same and it was only a bug to add gcode Tx support to the function which calcutated the time. Maybe it have to be a new feature ?
It's not essential but for monitoring purpose, it can be usefull.
