### ISSUE TITLE
[BUG] Firmware 3.14.0 M601 Resume Print Menu item is missing

### ISSUE THREAD

**Issue by dg2312** [prusa3d/Prusa-Firmware#4757]
**Used Prusa Slicer Version:**
PrusaSlicer
Version:   2.8.0+MacOS-arm64
Build:     PrusaSlicer-2.8.0+MacOS-arm64-202406270929
Operating System:    Macintosh
System Architecture: 64 bit

**Used Printer:**
MK3S 
Firmware 3.14
**Printer type** - [e.g. MK3S, MK3, MK2.5S, MK2.5, MK2S, MK2]
**Printer firmware version** -  [e.g. 3.8.1, 3.8.1-RC1, ...]

**Printed via Octoprint**

**Describe the bug**
Created an M601 Order in Prusa Slicer to place in my case magnets.
The printer stops and on the printer menu and you can see your defined message unil here everything was like the other firmwares before. 
After placing I want to resume the print, but the menu item was not there as it was with older firmwares.
So, I tried to resume the print via octoprint. It resumes but without heating the nozzle again, so no filament was extruded. 
Using Octoprint was with older firmwares no problem with an M601 order it works fine.

**Expected behavior**
The resume print menu item should be available again after a pause for placing bearings or other stuff.

**Comment by 3d-gussner** [comment]
@dg2312 Please read https://github.com/prusa3d/Prusa-Firmware/issues/4706
