### ISSUE TITLE
[ENHANCEMENT] Export as .3mf 

### ISSUE THREAD

**Issue by JamesMakesit** [prusa3d/Prusa-Firmware#4785]
### Printer model

- [X] MK3S/+
- [ ] MK3
- [ ] MK2.5S
- [ ] MK2.5

### Describe the enhancement

Hello, it would be very useful to export a file as a .3mf file with the existing modifications. For instance, an object that has a negative volume in a specific position. At the moment I can only export as an stl, which removes any modifications. Thank you keep up the good work!

**Comment by 3d-gussner** [comment]
@JamesMakesit Thanks for the issue report, but this is the Prusa-Firmware repository for the 8-bit MK2.5/S and MK3/S/+ printers.
I guess this request is for the Prusa Slicer. If so please close this issue here and open it https://github.com/prusa3d/PrusaSlicer
