### ISSUE TITLE
[BUG] Printer  MK3S Revo with MMU2S claim on firmware 3.14.0 rise warning "G-code sliced for different printer"

### ISSUE THREAD

**Issue by NightSkySK** [prusa3d/Prusa-Firmware#4792]
### Printer model

MK3S/+

### MMU model

MMU2S

### Firmware versions

3.14.0

### Upgrades and modifications

Revo hotend

### Printing from...

OctoPrint

### Describe the bug

Since I upgraded SW to 3.14.0 via file [E3D_REVO_FW_MK3_MK3S_MK3S+_FW_3.14.0.zip](https://github.com/prusa3d/Prusa-Firmware/releases/download/v3.14.0/E3D_REVO_FW_MK3_MK3S_MK3S+_FW_3.14.0.zip) MK3S_MK3S+-E3DREVO_FW_3.14.0_MULTILANG.hex printer claim on each g-code that it is sliced for different printer type.
(I've uploaded this firmware multiple times to ensure that I didn't mix anything)

I used previous releases of PrusaFirmware made for E3DRevo hotend modification and always all worked well

In PrusaSlicer I use Original Prusa i3 MK3S & MK3S+ MMU2S Single profile. 

Here is example G-code (using 0.6 nozzle, but there is the same with other nozzle sizes)

[lock_cover_thin_0.6n_0.35mm_PETG_MK3SMMU2S_3h2m.zip](https://github.com/user-attachments/files/17412962/lock_cover_thin_0.6n_0.35mm_PETG_MK3SMMU2S_3h2m.zip)

### How to reproduce

1. Upgrade pinter with E3DRevo extruder to 3.14.0
2. Slice g-code as before
3. upload g-code to printer
4. Start print
5. "G-code sliced for different printer" warning appear on printer LCD 

### Expected behavior

Printer should accept his g-code without warning

**Comment by 3d-gussner** [comment]
@NightSkySK Thanks for the report. Are you using a custom PrusaSlicer Profile?
In the provided GCode you can see these two `M862.x` Gcodes
```
;TYPE:Custom
M862.3 P "MK3SMMU2S" ; printer model check
M862.1 P0.6 ; nozzle diameter check
```
which tell the printer for which printer type and nozzle size the Gcode has been sliced for.
The `M862.3 P "MK3SMMU2S" ; printer model check` points out that it is sliced for a MK3S with and MMU2S.
As the printer can't detect which hardware version of the MMU is connected it will set the type to `MK3SMMU3` and that doesn't matches the provided version.

Please use the newer PrusaSlicer MK3S + MMU3 profile and / or update your custom PrusaSlicer profile.
If you don't have the MK3S+MMU3 profile use the Wizard to add it.
In case you have a custom profile for your REVO, you can use the `Compare presets with another` in PrusaSlicer to make a new MK3S+MMU3 profile from your custom MK3S+MMU2S profile.


See also https://github.com/prusa3d/Prusa-Firmware/issues/4786
