### ISSUE TITLE
Extruder Linearity Correction for MK3.5(s)

### ISSUE THREAD

**Issue by 0uincy** [prusa3d/Prusa-Firmware#4793]
### Printer model

- [ ] MK3S/+
- [ ] MK3
- [ ] MK2.5S
- [ ] MK2.5

### Describe the feature

I used linearity correction for the extruder motor on my MK3s+ before upgrading to MK3.5s. I went to look for it in the MK3.5 settings page and noticed that it isn't present on the current firmware.

I saw a significant improvement to extrusion consistency when I used it on my MK3s+ and would like to see it added to a future version of the MK3.5 firmware.

**Comment by 3d-gussner** [comment]
@0uincy As you updated the MK3S to MK3.5 please close this issue here and open it in the 32-bit [Prusa-Firmware-Buddy repository](https://github.com/prusa3d/Prusa-Firmware-Buddy) .

**Comment by 0uincy** [comment]
> @0uincy As you updated the MK3S to MK3.5 please close this issue here and open it in the 32-bit [Prusa-Firmware-Buddy repository](https://github.com/prusa3d/Prusa-Firmware-Buddy) .

Oops. Thank you
