### ISSUE TITLE
[ENHANCEMENT] G81 results in Prusa Connect

### ISSUE THREAD

**Issue by rbronco21** [prusa3d/Prusa-Firmware#4800]
### Printer model

- [ ] MK3S/+
- [ ] MK3
- [ ] MK2.5S
- [ ] MK2.5

### Describe the enhancement

Can G81 results be made accessible using Prusa Connect, rather than requiring a computer running Pronterface and a USB cable? I am using a Mini, but I'm sure the results would be appreciated for all models. A displayed heatmap could be nice, but a simple table or even the ability to send a command and see results would work.

https://forum.prusa3d.com/forum/original-prusa-i3-mk3s-mk3-improvements-archive/bed-levelling-mod-bed-level-calibration-guide-for-beginners-also/

**Comment by 3d-gussner** [comment]
@rbronco21 This is the Prusa firmware repository for the MK2.5/S and MK3/S/+ printers. Please close your issue here and open it in the https://github.com/prusa3d/Prusa-Firmware-Buddy which is for the MINI, MK3.5/S, MK3.9/S, MK4/S and XL.
