### ISSUE TITLE
[BUG] 3.14.1 MK3S+ new filament load screen german translation broken

### ISSUE THREAD

**Issue by Smooph86** [prusa3d/Prusa-Firmware#4819]
### Printer model

MK3S/+

### MMU model

No-MMU

### Firmware versions

Standard 3.14.1, downloaded from Prusa

### Upgrades and modifications

None

### Printing from...

PrusaLink

### Describe the bug

The new firmware 3.14.1 introduced the new possibility to select "Yes", "No" and "Eject" after loading filament. In the english translation this looks nice and works, but if I set the printer to German language, the screen is broken. (see picture)
Screen Says "rf.ament extrudiert mit richtiger Farbe? Ja, Nein, Auswe"

### How to reproduce

I tried switching back and forth from English to German. Reflashed 3.14.1 while in English - English stays correct, German stays broken.

### Expected behavior

I would expect the message to say "Filament extrudiert & mit richtiger Farbe? Ja, Nein, Auswerfen"

### Files

![photo_2024-12-14_16-16-32](https://github.com/user-attachments/assets/8ed4b994-9d1b-4ccf-b073-27ef5e580a2b)

**Comment by 3d-gussner** [comment]
@Smooph86 Thanks for reporting the issue. Dankeschön
I assigned this issue to myself

**Comment by 3d-gussner** [comment]
@Smooph86 Thanks again for reporting this issue. There are multiple languages having the same issue. Created a PR #4820 to solve it.
