### ISSUE TITLE
[ENHANCEMENT] MMU3 - When MMU is empty and "Unload Filament" M702 C is sent, don't reload filament first.

### ISSUE THREAD

**Issue by ggppjj** [prusa3d/Prusa-Firmware#4822]
### Printer model

- [X] MK3S/+
- [ ] MK3
- [ ] MK2.5S
- [ ] MK2.5

### Describe the enhancement

I have an MK3S+ and MMU3 connected to Octoprint. When I cancel a USB print from the LCD, the firmware currently will run an unload on the MMU3 and then process post-cancel script commands from Octoprint. When cancelled within Octoprint, it will only run post-cancel script commands.

The issue:

I have an `M702 C` (unload current filament) command in my cancel script in Octoprint for parity in behavior between cancelling from the LCD and cancelling within Octoprint. This causes the MMU to unload normally and the script itself works fine when cancelling a print within Octoprint, but cancelling from the LCD seems to cause the firmware to unload the filament on its own before passing the info on to Octoprint that it cancelled the print and then processing the cancel script. Sending `M702 C` to an unloaded printer will cause it to prompt the user to load a filament first (no cancel). If the user selects a filament, it will then load the filament to the extruder and immediately unload it. As this is being done during a cancel, there is a strong possibility that the extruder is no longer being heated and this could cause the filament to jam.

To be overly clear, current behavior:
Cancel print from Octoprint's GUI -> Printer unloads filament, parks.
Cancel print from LCD -> Printer unloads filament, parks, prompts user to select filament to load, loads filament, unloads, parks again.

### Expected functionality

If I send an `M702 C` to a printer that currently does not have filament loaded, I would like it to continue instantly as a success without first loading and then unloading filament. ("Unload? I am unloaded. Done.") This solves the (expected) firmware behavior difference between LCD cancel and print hosts and allows print hosts to send an `M702 C` without the need to know whether the MMU is currently loaded or not to avoid unexpected behavior.

**Comment by 3d-gussner** [comment]
@ggppjj Thanks for the idea. Please check https://github.com/prusa3d/Prusa-Firmware/issues/4807#issuecomment-2459082569 and the linked issues helps with your setup.

**Comment by ggppjj** [comment]
Thank you for the reply, although I don't believe that this is a configuration issue. I believe the issue I'm facing is due to the way the firmware behaves with the MMU connected. When possible, I will send my cancel script as it is in Octoprint.


Specifically with the MMU attached, I believe there is a firmware difference in what it does when you tell the printer to cancel from the LCD vs telling Octoprint to handle the cancel. When cancelled from the LCD, the printer appears to trigger an `M702 C` before continuing to process Octoprint's cancel script. When cancelled from within Octoprint, Octoprint controls the entire process and the firmware doesn't trigger its own unload.

I confirmed with the Octoprint Discord support channel that there isn't a way for Octoprint cancel gcode to differentiate between LCD cancels and Octoprint GUI cancels.

It would seem that the only best way forward that allows me to have `M702 C` enabled in my Octoprint cancel script would be for either the printer to not do its own unload before passing control back to Octoprint or for `M702 C` to not trigger a reload if it's called with no filament loaded, that way the firmware's unload can be followed by Octoprint sending an unload command without issue.

**Comment by ggppjj** [comment]
Here is my current Octoprint cancel gcode:

```G-Code
G91
G1 Z1
G90
G1 X0 Y210 F7200 ; park
G91
G1 Z49
G90

M140 S0 ; turn off heatbed
M107 ; turn off fan

M702 C ; Unload filament


G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA
M104 S0 ; turn off temperature
M84 ; disable motors
```

This is mostly copied from the ending G-code from PrusaSlicer.

Following what you linked:

>  -> After print job is cancelled: M603 and M77

I am curious as to what [M603](https://marlinfw.org/docs/gcode/M603.html) would do in this case, unless the functionality is overwritten in Prusa's Marlin.

In any case, this would leave the hotend and bed on until timeout if cancelled in the GUI with just the following, wouldn't it? And it would leave the MMU loaded if I cancelled the print from the print host?
```g-code
M603 
M77
```

**Comment by 3d-gussner** [comment]
@ggppjj `M603` is in Prusa-Firmware stops the print see https://reprap.org/wiki/G-code#M603:_Stop_print_.28Prusa_i3.29

We try to follow the RepRap Gcode wiki as there are multiple firmware listed. In case of a new feature we check if a Gcode in RepRap is already there or we can reuse one that is very similar.

As you can see the M603 frankly has two meanings depending which firmware you are using.

Rolling back the history [M603 Stop print](https://reprap.org/mediawiki/index.php?title=G-code&oldid=189231#M603:_Stop_print) was before [M603 Configure Filament Change](https://reprap.org/wiki/G-code#M603:_Stop_print_.28Prusa_i3.29) has been added to Marlin.

To get the host (Octoprint) and the printer in sync the configuration of the Gcode scripts ensures that the printer behave the same wherever you select pause, resume or stop print.

Pausing the SD or Host print form LCD screen results in the same as pausing from host (OctoPrint)
Same for resume and stop/cancel print.

Test:

Pause and Resume
SD print
1. Start SD print
2. Pause print from LCD screen
3. Resume print from LCD screen
4. Pause print from LCD screen
5. Resume print from host (OctoPrint)
6. Pause print from host (OctoPrint)
7. Resume print from LCD screen
8. Pause print from host (OctoPrint)
9. Resume print from host (OctoPrint)

Host print

1. Start host (OctoPrint) print
2. Pause print from LCD screen
3. Resume print from LCD screen
4. Pause print from LCD screen
5. Resume print from host (OctoPrint)
6. Pause print from host (OctoPrint)
7. Resume print from LCD screen
8. Pause print from host (OctoPrint)
9. Resume print from host (OctoPrint)

You can repeat this also for stop print, pause and then stop print.

Without the GCode scripts the printer or the host may not know what the state is and behave odd.

**Comment by ggppjj** [comment]
Understood, I will change my scripts and reopen if I run into issues. Thank you for the explanation, apologies for the misunderstanding.

**Comment by 3d-gussner** [comment]
@ggppjj No apologies needed. The two `M603` entries make it difficult to know what which firmware is doing.

I really hope that the settings in OctoPrint GCode scripts work for you, as they do for me. I mostly use PrusaLink and PrusaConnect but as OctoPrint is a widely used and a great host system, I try to get it working as well.

Please also install the OctoPrint Activate Prusa HostTimer plug-in. The firmware behaves differently when it "knows" that the host is "listening".

Some examples:
When the printer "knows" the host is connected and listening, the Resume of a host print is different:

It sends to the host an action command `//action:resume` so it resumes the host print. Without the "knowledge" if that is a host print or the host is "listening" the firmware will try to resume normally, which may fail for a host print.

When power panic event is triggered while PrusaLink/PrusaConnect printing the firmware handles the recover differently:
1. The printer will recover as far as it can and pauses until PrusaLink also recovers from the power outage.
2. PrusaLink will then send `M79 S"PL` or `M79 S"PC"` to the printer.
3. The firmware "knows" that PrusaLink is back up and running and "unlocks" the Resume function on LCD
   a. Without this the user may press Resume, and this command to the host would be lost as PrusaLink isn't back online and connected. 
5. Then PrusaLink will request few information from the printer and trying to recover the PrusaLink/PrusaConnect print.

At this moment I have not seen any OctoPrint Plugin that is using this new feature to recover host prints after a power panic event.
