### ISSUE TITLE
Crashed LCD output and possible other corruption

### ISSUE THREAD

**Issue by mozgy** [prusa3d/Prusa-Firmware#493]
Start with 'Calibrating Z' or XYZ, at the menu 'is steel sheet on' choose 'Yes'. That results in LCD garbage and very possibly some other corruption. It's repeatable on FW 3.1.1-201. One time it even resulted in complete inability to start any print, with error 'Heater/Thermistor Not connected'.
FW reflash clears that roadblock and enables printing again.

**Comment by darrellittle** [comment]
This happened to me as well. I did a factory reset, re-flashed the firmware with 3.1.1-201 and another factory reset and it resolved the issue. The second factory reset may not be necessary, I was just being cautious.

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete. In case the issue is still not solved, please contact info@prusa3d.com.

Marina Curzi
Prusa Research
