### ISSUE TITLE
Statistics issue in 3.1.1 -- 201

### ISSUE THREAD

**Issue by cnlson** [prusa3d/Prusa-Firmware#498]
This will take reviewing the pictures while i narrate. After a print ends the time continues to accumulate on the screen, as if the print is continuing. Once you start a new print the accumulated time from the last print is added to the statistics. So the time is basically the entire time you have had the printer on since the last time off _unless_ you reset the printer or turn the printer off. 

in this picture note the accumulated time
![20180223_112404](https://user-images.githubusercontent.com/1442027/36610658-9a366c2a-1896-11e8-9474-fd5fba389b90.jpg)
in this picture note the print time of 00:25 minutes and the apparent accumulating time since the print of 11 hr 17 min
![20180223_123028](https://user-images.githubusercontent.com/1442027/36610696-c5c253ae-1896-11e8-872b-0e7e47721da3.jpg)
starting a print resets the clock 
![20180223_123041](https://user-images.githubusercontent.com/1442027/36610707-d499e9c8-1896-11e8-9770-cc6d30594b5b.jpg)
and appends the 11;17 onto the total time
![20180223_123103](https://user-images.githubusercontent.com/1442027/36610735-e28cb844-1896-11e8-84bb-1510c241bef6.jpg)

resetting or turning off and on completely stop the counter accumulation
![20180223_123054](https://user-images.githubusercontent.com/1442027/36610786-09e8dc7e-1897-11e8-8da3-0ad9799b5dc5.jpg)

**Comment by magkopian** [comment]
I have the same issue and I'm running the latest stable firmware release 3.1.3. I just finished printing a calibration cube on my new MK3 and that was the result. So far it happened only once, but I haven't done more than 15 prints in total.

![20180404_203600](https://user-images.githubusercontent.com/1429068/38324794-f3c59504-3849-11e8-87da-116527a238db.jpg)

**Comment by tofb15** [comment]
Just encountered this on my MK3s with MMU2s running firmware 3.8.0.
![IMG_20190815_200113](https://user-images.githubusercontent.com/24247942/63116488-12a23580-bf9a-11e9-8d58-332c3098c12c.jpg)
![IMG_20190815_200135](https://user-images.githubusercontent.com/24247942/63116489-12a23580-bf9a-11e9-8073-fc2d219f3d3d.jpg)
![IMG_20190814_115002](https://user-images.githubusercontent.com/24247942/63116490-133acc00-bf9a-11e9-8454-0190e5597672.jpg)




Each print adds 1000+ hours to the Statistics.
