### ISSUE TITLE
Belt Status

### ISSUE THREAD

**Issue by danielegger1** [prusa3d/Prusa-Firmware#499]
After the new firmware (3.1.2 RC1 255) update I had to rerun the Self test and I checked the Belt status afterwards which is now completely wrong.
X = 1692
Y = -31883

**Comment by stahlfabrik** [comment]
I can confirm that belt status is broken in 3.1.2 RC1. Did a full factory reset before self test.

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete. Please open a new issue if this is not solved yet.

Marina Curzi
Prusa Research
