### ISSUE TITLE
option to heat up for filament when unloading

### ISSUE THREAD

**Issue by erikcramerjr** [prusa3d/Prusa-Firmware#500]
When you press unload filament and the nozel is not hot enough.
You get an error, it would be more user friendly if you would get a question as to, to what temperature would you like to heat up the nozel.

How can i tag this as a feature request ?

**Comment by jcwren** [comment]
It would also be nice if it extruded 5cm of filament before it begins retracting. That's the only way I've found to reliably avoid getting a bump in the filament that jams the extruder gear.

**Comment by cnlson** [comment]
i second both of these suggestions

**Comment by sylphio** [comment]
Extruding before removing filament is mandatory on my printer too.

**Comment by wsmagee** [comment]
I agree that the ability to preheat and extrude a small amount before unloading would be beneficial.
