### ISSUE TITLE
Put Download Files behind a CDN

### ISSUE THREAD

**Issue by dalgibbard** [prusa3d/Prusa-Firmware#513]
Hey all!
Small request... Please consider placing files found on https://www.prusa3d.org/downloads/drivers/ behind a CDN - Download speed here is less than 100KB/s on a 300Mbit connection :(
AWS Cloudfront? :)

**Comment by MrManny** [comment]
Judging from the HTTP response headers, it would appear that they are already using Cloudflare.

**Comment by dalgibbard** [comment]
Sounds fair, maybe I was just too quick off the mark on my region for it to be cached :) closing.
