### ISSUE TITLE
3.1.0 No update for Repetier Server?

### ISSUE THREAD

**Issue by Parker-Drouillard** [prusa3d/Prusa-Firmware#526]
Just contacted Prusa through the support widget on the website, I've been waiting for a while now to update my machines (We use repetier server for all our machines) and we haven't yet as the firmware currently states there is a bug with repetier server.

Noticing that it actually says 3.1.0 FINAL & That there have been many revisions for the MK3 by now, I was starting to get a bit concerned that you guys might not actually be updating the old software.

After contacting support I was told that they don't believe they are either. I'm kind of dissapointed if this is true, as we were really looking forward to these new updates that were released in 3.1.0, and all the benefits that come with it

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete.

Marina Curzi
Prusa Research
