### ISSUE TITLE
3.1.2

### ISSUE THREAD

**Issue by DataCrypt** [prusa3d/Prusa-Firmware#531]
Per user martin.m25 on Prusa forum:

Bed level correction does not work.

To reproduce:

1. print bed level test pattern
2. measure height of the nine fields
3. change bed level correction right side to - 50 um
4. print and measure again
5. see that there is no siginificant change.

Others are reporting this as well, see:
https://shop.prusa3d.com/forum/original-prusa-i3-mk3-f30/first-layer-issues-pre-assembled-printer--t14705.html#p69822
https://shop.prusa3d.com/forum/original-prusa-i3-mk3-f30/mesh-bed-leveling-tuning-t14668.html

Maybe related to the PINDA bug Stahlfabrik discovered?

**Comment by Prusa-Support** [comment]
Hello! If you are still having this issue, please contact us at info@prusa3d.com.

Marina Curzi
Prusa Research
