### ISSUE TITLE
MK3 3.1.3 Last print time

### ISSUE THREAD

**Issue by radovanma** [prusa3d/Prusa-Firmware#544]
When printing is finished, the last print time will not remain on the display.
This information is now replaced by "Prusai3 MK3 ok".
-------- edit
The situation occurred (on both my mk3 printers) only on the first print immediately after FW upgrade. It has never happened again.

**Comment by Prusa-Support** [comment]
Hello! If you are still having this issue, please contact us at info@prusa3d.com.

Marina Curzi
Prusa Research
