### ISSUE TITLE
latest firmware, impossible to move manually the x and y axis 

### ISSUE THREAD

**Issue by blandiant** [prusa3d/Prusa-Firmware#546]
Hi,
i can't move the x and y axis from the menu "move axis" in "setting", (i try to restart the printer, it doesn't work)
but i can move the z axis and when i'm printing all the axis are working great,
it happened just after i updated the firmware...

**Comment by blandiant** [comment]
update: after the 3d printer finished a print, i retry to move the x and y axis and it re-worked very strange...

**Comment by PavelSindler** [comment]
Hello, 
are you talking about MK2.5 or MK3 firmware?

**Comment by blandiant** [comment]
I'm talking about the mk3 firmware
Sorry i forgot to say that

**Comment by joysfera** [comment]
I can confirm that. Tried moving the Y axis, couldn't enter less than -4 (by rotating the knob). Latest MK3 firmware.

**Comment by radek-senfeld** [comment]
I'm experiencing the exact same behavior.

**Comment by ruairidh37** [comment]
I can confirm only for moving X-axis left: the setting will not go below +0.0. MK3S running FW 3.8.1

**Comment by leptun** [comment]
This is normal behavior. The axes should not go out of bounds when manually moving. You must home all axes first.

**Comment by ruairidh37** [comment]
Thanks, was not aware of this. All is well post-auto home.
