### ISSUE TITLE
mesh bed leveling not working worse when PINDA temp changes

### ISSUE THREAD

**Issue by Crunch69** [prusa3d/Prusa-Firmware#558]
mesh bed leveling is not working first layer inconsistent across build platform. Right side much higher than rest of bed mesh bed correction unable to correct especially the center points in between corners mesh bed leveling even worse if pinda temp goes above 35c

**Comment by jiggersplat** [comment]
Concur. The front right of my bed appears to be higher than the back right. Mesh bed leveling is not correcting for it based on some single layer calibration prints.

**Comment by matthew-humphrey** [comment]
Concur. My MK3 has the exact same symptoms as @jiggersplat

**Comment by Zaf9670** [comment]
I have similar issues as well but have you all tested your build sheet thickness? I've been curious if it's the double sided PEI thickneess.

A possible fix would be if the calibration could do a double pass reversing the order? Or maybe of it would allow a paper check on each calibration point as a verification step.

**Comment by 3d-gussner** [comment]
Did you read this issue ? https://github.com/prusa3d/Prusa-Firmware/issues/421

**Comment by Prusa-Support** [comment]
Make sure to have the latest firmware for your printer, and to run the full calibration. It is also possible to use the [bed level correction](https://help.prusa3d.com/article/bed-level-correction_2267). If the issue is still not solved, please contact us at info@prusa3d.com.

Marina Curzi
Prusa Research
