### ISSUE TITLE
MK3 Y-Axis crashes everytime after power cycle

### ISSUE THREAD

**Issue by RacingHell** [prusa3d/Prusa-Firmware#559]
After a power-cycle, autohoming and bed-leveling the Y-axis crashes without detection before starting the gcode. The axis moves to startpoint and drives through the mechanical end stop, the belt snaps with a rattle-noise over the pulley. Second print doens‘t have this issue anymore. This behaviour started 2-3 fw-releases earlier than 3.1.3 final. Belt tension is already high at 289.

**Comment by PlacidCat** [comment]
I have this same issue. My Y-axis belt is very tight - sounds like a bass string as recommended.

**Comment by RacingHell** [comment]
Maybe it's the same issue posted in
[](https://github.com/prusa3d/Prusa-Firmware/issues/378) as well.

**Comment by RacingHell** [comment]
Solved at 3.2.0 alpha.
