### ISSUE TITLE
[Feature Request] Silent/Normal Mode on Infoscreen

### ISSUE THREAD

**Issue by cjander** [prusa3d/Prusa-Firmware#562]
right now to check if the (MK3) printer is running in normal or silent-mode, we need to check it in the menu. But on the info screen second line next to the flow rate on the very right, there are three unused char fields. My suggestion is to show on the very right in that line an S for silent-mode or N for normal.

**Comment by Panayiotis-git** [comment]
In MK2 there is no need to show a sign at the display. It is so obvious! :)

**Comment by Patronics** [comment]
I (and I imagine lots of other people) never use silent mode, so I think it would be better if it showed nothing for normal mode, but could still show an “S” for silent mode. I think it would be better if it could be a configurable indicator, as I would benefit more from an indicator of whether the filament sensor is on for example.
