### ISSUE TITLE
SD Card not detected or content not refreshed

### ISSUE THREAD

**Issue by patrovite** [prusa3d/Prusa-Firmware#564]
On a MK3 with the firmware 3.1.3.245, when I insert the SD card the content on the display is not refresh and sometime the SD is not detected. If I press the reset button, the machine reboot and the real content of the SD card appear.

SD type : SD ship with machine
Machine : MK3
Firmware : 3.1.3.245
Occurence : Always
Current solution : Reset to update the content of the SD

**Comment by smhgit** [comment]
I have the same issue / same firmware version. 

Update:

If the card inserted fast enough, it does work.

**Comment by Prusa-Support** [comment]
Please update to the latest [firmware](https://help.prusa3d.com/downloads). If you are still having this issue after flashing the firmware, please contact us at info@prusa3d.com.

Marina Curzi
Prusa Research
