### ISSUE TITLE
M600 X10 Y10 not moving to correct Position

### ISSUE THREAD

**Issue by luke321** [prusa3d/Prusa-Firmware#577]
Hello,

I have a repeatable problem with the M600 command.
If I use M600 X10 Y10 the printer moves to a position somewhere around X110.
If I use M600 X-90 Y10 I end up where I wanted to be.

**Comment by 3d-gussner** [comment]
I can't reproduce the problem on my MK2. Also checked MK2, MK2.5 and MK3 firmware routines and the code looks fine for the M600 in all 3 versions.
Which printer (MK2/MK2.5/MK3) do you have and which firmware version do you have installed?

**Comment by luke321** [comment]
Hello MK3 with Firmware 3.1.1 I will upgrade and try again.
I am using Octoprint maybe this is the cause?

2018-03-26 19:44 GMT+02:00 3d-gussner <notifications@github.com>:

**Comment by 3d-gussner** [comment]
@luke321 Try MK3 firmware 3.1.3 you can find the newest version here:
https://www.prusa3d.com/drivers/
or
https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.1.3

**Comment by Prusa-Support** [comment]
Hello! If you are still having this issue, please contact us at info@prusa3d.com.

Marina Curzi
Prusa Research
