### ISSUE TITLE
setup wizard crashes consistently

### ISSUE THREAD

**Issue by cornim** [prusa3d/Prusa-Firmware#581]
Hi, I have the following problem:
I bought a new i3 mk3, unpacked it, plugged it in and hit "... guide you through the setup process -> Yes".
Then the extruder cooler powers up and the screen briefly shows "Original Prusa i3 Prusa resarch" and then it jumps back to "Hi, I am your Original Prusa i3 printer. Would you like me to guide you ..."

I also tried:
Selecting No for the setup wizard
Installing the firmware to 3.1.2 and selecting Yes and No
Downgrading the firmware to 3.1.1 and selecting Yes and No
Upgrading to 3.1.3 and selecting Yes and No

No luck and the same error in all cases.
Any help would be much appreciated.

Best
Cornelius

**Comment by 3d-gussner** [comment]
@cornim Hi, is it a pre-build printer? If so contact Prusa support via chat.
If you build it yourself check the wiring and your build before contacting Prusa support.
You should consider to post a picture in the Prusa forum or in one of the facebook Prusa groups or a short video on YouTube or so.

**Comment by Prusa-Support** [comment]
Hello! If you are still having this issue, please contact us at info@prusa3d.com.

Marina Curzi
Prusa Research
