### ISSUE TITLE
MK2S Did Not Issue Oversized Build Warning

### ISSUE THREAD

**Issue by mheida17** [prusa3d/Prusa-Firmware#592]
## Summary
When printing a rather tall piece, I did not notice that the size exceeded the maximum z by a few mm.  There was no warning within either Slic3r or the printer screen; I'm not sure if this feature exists and this was an issue with my machine or if the feature does not exist yet.  

## Printer Details
Prusa MK2S, Firmware 3.1.0
Slic3r Prusa Edition, Version 1.39.1

**Comment by Prusa-Support** [comment]
The latest version of PrusaSlicer should warn you if the piece exceeds the size of the print area.

Marina Curzi
Prusa Research
