### ISSUE TITLE
Minor Bug: Fail Stats shows same results for “last print” and “Total”

### ISSUE THREAD

**Issue by Patronics** [prusa3d/Prusa-Firmware#593]
On the Mk3 running firmware 3.1.2-231 the “Filam. runouts” and “Crash”es are reporting the same number for both the last print and total (it seems to display the total numbers for both). Unlike the other stats, “power failures” are reported correctly for both. This is as shown from the LCD menu during an octoprint-controlled print, if that’s relevant. I have observed this behavior several times, so it’s not just a fluke.

**Comment by wavexx** [comment]
Related: #676
