### ISSUE TITLE
Add "ignore filament sensor" option when filament sensor triggers

### ISSUE THREAD

**Issue by rrauenza** [prusa3d/Prusa-Firmware#594]
When the filament sensor isn't working properly, it's a real pain...  when it triggers falsely you have to allow it to unload the filament, snip it, reload it, let it clear, clean off the strings, ... (and then probably do it again 15 mins later.)

Could we add more options to the menu when it triggers?  Like,

* Unload Filament -> Load Filament -> Continue
* Ignore & continue
* Ignore & disable filament sensor & continue

edit:

Also, the behavior may be different from octoprint / usb / vs SD.  At least with Octoprint, I was unable to go to the physical menu and turn off the filament sensor until the job was done.  That's why I'd like it to be done just in this menu.  

Also, trying to send M406 via Octoprint terminal just gave me an error:

```
Send: M406
Recv: Unknown M code: M406
Recv: ok

```

See https://github.com/prusa3d/Prusa-Firmware/issues/563 for more info on whether that gcode is supported or not..

**Comment by wsmagee** [comment]
This would be a very benefical change.  The choices rrauenza lists are the same three I would want to see as well.

**Comment by tetraDB** [comment]
A workaround [EDIT](if using sd card) is to pause the print, that gives you access to the settings menu and then you can turn off the filament sensor.

**Comment by rrauenza** [comment]
@tetraDB I think that doesn't work when using octoprint?

**Comment by tetraDB** [comment]
@rrauenza I've edited my comment to specify with SD card, sorry about that,
