### ISSUE TITLE
[Feature Request] Edit Preheat temperatures

### ISSUE THREAD

**Issue by jzkmath** [prusa3d/Prusa-Firmware#604]
It would be awesome if it was possible to edit the default preheat temperatures from the LCD screen/GCODE commands.

i.e. be able to set PLA preheat from 215C to 210C

**Comment by mvasilakis** [comment]
I agree with this. It would be nice to change the defaults.

**Comment by 3d-gussner** [comment]
As Slic3r PE and PrusaControl have the 1st layer for PLA at 215°C i think the firmware matches their defaults.
Adding custom PLA, ABS,... preheat settings are possible but may blowup the code a bit. This firmware is close to the limits of the ATMega2560 platform (multi language on the MK3 is cut down to two languages at this moment, MK2/s had six), so adding that kind of features may be less important than others to improve the print quality and improve usage for "normal" users.

You can use the default preheat and just tune it down via the LCD menu, but don't forget to have the same Slicer settings for your 1st layer.

**Comment by gertlind** [comment]
If you just want to heat the hotend for loading/unloading filament, create a gcode file and put it on your SD card. <pla_210C.gcode>.
This could be included by Prusa on their SD card that they ship with the printer. 

I use Octoprint to preheat the hotend when swapping filament.

**Comment by JohnSvensk** [comment]
I was going to suggest a Cooldown target temp for cold pulls, but a separate gcode file for this allows one to add an annoying beep as well. Great idea. :)
