### ISSUE TITLE
MK2.5 Self Test will crash nozzle in bed if no sheet on

### ISSUE THREAD

**Issue by SaijSaij** [prusa3d/Prusa-Firmware#605]
Printer: MK2.5
Firmware: 3.1.3 official release
Issue: When you run the self test without the steel sheet on the nozzle will crash into the bed on testing z-endstop as the probe is not above one of the new points (looks like the position is for the old MK42 bed points).
Steps:
1. Remove steel sheet
2. Start self test via menu
3. Wait (and keep a metal thing at hand to trigger the probe endstop)
Repeatable: yes

**Comment by Martorias** [comment]
I built mine 2 days ago and didn't have this issue. Didn't put the sheet on until asked by the calibration wizard.

**Comment by SaijSaij** [comment]
Well just run the selftest yesterday and it did the descripted thing.

**Comment by gertlind** [comment]
I just completed the 2.5 upgrade.
Had no issues during the calibration process.

**Comment by clearbucketLabs** [comment]
self-test is a different thing from calibration....

**Comment by gertlind** [comment]
Idid the self test also. No issues.

**Comment by SaijSaij** [comment]
Just downgraded back to MK2S or else I could upload a video.
Maybe you need todo a factory reset to trigger this problem (this is what I ever do when I'm doing such an upgrade)

**Comment by SaijSaij** [comment]
Sorry for not writing for so long.

I rebuild the MK2.5 and tested the selftest again. This time I did not a factory reset and I did a short video of the whole self test process.

Link to video: https://www.youtube.com/watch?v=q1546BJgfIQ&feature=youtu.be

As you can see, the probe is not above the point on the heatbed.

**Comment by Prusa-Support** [comment]
Hello! I am absolutely sorry for not intervening on this sooner. Was the issue resolved in the meantime? From the video and description, I believe the main contributor was the PINDA probe position being too high. Closing the issue for now, but in case you still have similar problems, can you please let me know via email? info@prusa3d.com mentioning me. 

Alessandro Pantaleo
Prusa Research
