### ISSUE TITLE
Prusa3d Specific G-code explanation?

### ISSUE THREAD

**Issue by sarf2k4** [prusa3d/Prusa-Firmware#61]
Hi, I would like to know what do these g-codes do when issued especially

- G80
- G86
- G87
- G88

From my point of view at G80, it is almost similar to G29, but another addition after all 9 points has been probed is that the print head will go to position 0,0,0. I need confirmation on G80 though because at the start g-code of slic3r, no Z movement were issued.

**Comment by PavelSindler** [comment]
G80 measures height of all 9 points (relative to zero point), apply live adjust Z and apply bed level correction on measured points. Then it counts correction matrix which is used in planner for Z coordinates correction when printing. 
G86 and G87 changes calibration status. Calibration status is just information about calibrations which have been run successfully. This infromation is stored in EEPROM. If some calibrations have not been run yet, user is informed what is the next step. G88 is currently not used.
Using G86 and G87 in your gcodes can set calibration status to value which doesn't correspond to calibrations which have been run.
Why do you need this information? What are you dealing with?

**Comment by sarf2k4** [comment]
Does G80 will move to the 0,0,0 position after it has probed all 9 points?

**Comment by PavelSindler** [comment]
Yes it does.

**Comment by sarf2k4** [comment]
Another one, basically it is a G29 but added extra path to move xy first, then z to 0 lastly. 

I can use the old G29 instead of G80 also right?

**Comment by PavelSindler** [comment]
Why would you do that?
G29 is not used in current firmware version. If you send G29 via serial, nothing happens.

**Comment by bubnikv** [comment]
http://reprap.org/wiki/G-code

G29: Detailed Z-Probe

G80: Cancel Canned Cycle (CNC specific)

There has been a long discussion on various forums, that we should have
used G29 for the bed leveling. First, our bed leveling does a bit more than
what G29 is supposed to do, second the decision has been met a year ago and
now it is late to change to G29.

**Comment by fbujold** [comment]
I do not understand the difference between G28 and G80
