### ISSUE TITLE
MK 2.5 3.1.3: Extrusion fan error, hotend shuts off, but heated bed stays on

### ISSUE THREAD

**Issue by langph** [prusa3d/Prusa-Firmware#626]
Prusa MK 2.5 3.1.3

Some filament parts came into the extrusion fan, because of a failed print. It triggered an extrusion fan error, the hotend shutted off (good), but the bed stayed on (not so good). :-)

**Comment by PavelSindler** [comment]
This is desired behavior. If you remove filament (or another obstacle) from fan, you can resume print the same way as paused print. That is why heatbed stays hot during fan error - you want your partialy printed object to stay on heatbed (pause print works the same way).

**Comment by langph** [comment]
Ok, but this is theoretical: if filament blocks the fan, it is a sign that the whole print is messed up

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being the intended behavior. 

Marina Curzi
Prusa Research
