### ISSUE TITLE
MK3 3.2.0-RC1 - home xyz without steel sheet - nozzle scratches the bed

### ISSUE THREAD

**Issue by stahlfabrik** [prusa3d/Prusa-Firmware#628]
I installed the new RC1 firmware. I did a home xyz without the steel sheet on (right after a factory reset). The PINDA came down not 100% over the trigger spot but a little more to the right of the center of the circle. So it triggered low, too late. The nozzle then scratched over the heat bed, leaving three marks. :-(

**Comment by stahlfabrik** [comment]
Wha! It happenend again, now fully calibrated. Wanted to restart temperature calibration. Had no steel sheet on. Nozzle goes into the bed.

**Comment by stahlfabrik** [comment]
I heard a interesting theory that the firmware might confuse the printer models so that it assumes calibration spots to be in wrong places. So the issues #625, #627, #628 etc are all result from the same error. 
The MK2S has different calibration points than the MK3

**Comment by GurliGebis** [comment]
That would explain why the problem has appeared after the MK2(.5) variants has been added.

**Comment by GurliGebis** [comment]
If you know your way around git, you could try and do a bisect between 3.1.3 and 3.2.0-RC1 and see which commit introduced the problem.
It is 216 commits, so should take around 8 builds/firmware flashes :)

**Comment by stahlfabrik** [comment]
Haha. Yeah but NO thanks!;-)

**Comment by Crunch69** [comment]
i can confirm this same issue when you run z calibrate z or temperature calibration with a little difference The PINDA came down over the trigger spot but a little more to the LEFT and BACK of the center of the circle

**Comment by stahlfabrik** [comment]
Yeah, left and back I got also when doing the temp calibration for the second time (first time I had steel sheet on)

**Comment by stahlfabrik** [comment]
Luckily its fixed in 3.2.0-RC2 for me!
