### ISSUE TITLE
3.2.0 MK3 Nozzle drop in bed

### ISSUE THREAD

**Issue by Murky7** [prusa3d/Prusa-Firmware#629]
After flashing new 3.2.0, my nozzle drop in bed in front right corner when making XYZ calibration

**Comment by morimorida** [comment]
After upgrade I had similar problem, during xyz calibration first 2 points were ok but 3 and 4th point of calibration, the nozzle was dragging the paper.  Luckily it was not digging into paper.  Otherwise I would have stopped it.

**Comment by geobruce** [comment]
For me this happened in the front left corner

**Comment by Prusa-Support** [comment]
The issue has been fixed in later releases of the firmware.

Marina Curzi
Prusa Research
