### ISSUE TITLE
Home Before Calibration

### ISSUE THREAD

**Issue by sarf2k4** [prusa3d/Prusa-Firmware#63]
One thing I noticed is that there is no auto home sequence added right before either calibration option xyz nor z.

Without auto homing before this, this also increases the risks of having the nozzle crashing onto the bed since the probe aren't always on the probe point unless manually homed first

**Comment by PavelSindler** [comment]
There is no need to manually home before xyz calibration nor z calibration. It is included in xyz/z calibration code already.
Have you observed some issue regarding this?

**Comment by sarf2k4** [comment]
If i remember correctly, the printer asked me to raise the z axis directly
without homing, then lowers down. I dont know until when the axis will stop
moving. I eventually will do check again later

**Comment by sarf2k4** [comment]
okay, I've confirmed that even without homing before doing the calibration, the printer will stop at that particular height. This actually scares me a bit especially when it got close to bed
