### ISSUE TITLE
Nozzle crashes into bed during the start of temp calibration 3.2.0 RC1

### ISSUE THREAD

**Issue by Crunch69** [prusa3d/Prusa-Firmware#632]
Nozzle crashes into bed during the start of temp calibration 3.2.0 RC1 after completing XYZ Calibration and Live Z calibration.  note nozzle also crashes bed during XYZ cal see also #628 and #629

**Comment by MarekC3D** [comment]
Is the "XYZ calibrabration" and "fist layer" was performed before starting temp. calibration? Is better to do XYZ and first layer calibration after each update.

**Comment by Crunch69** [comment]
yes of course all data erased in eprom then run wizard the XYZ calibrabration, and live z are always performed before starting temp. calibration that is normal procedure when installing new firmware

**Comment by Prusa-Support** [comment]
The issue has been fixed in later releases of the firmware.

Marina Curzi
Prusa Research
