### ISSUE TITLE
MK3 3.2.0-RC1 Gcode M860 and M861 do not appear to work Error Unknown M code

### ISSUE THREAD

**Issue by Crunch69** [prusa3d/Prusa-Firmware#634]
MK3 3.2.0-RC1 Gcode M860 and M861 do not appear to work Error Unknown M code

**Comment by mylife4aiurr** [comment]
Same. On new firmware 
Send: M861 
Recv: no valid commandok

**Comment by stahlfabrik** [comment]
It is because it is not valid. Try „M861 ?“

Does it work?

See Marlin_main.cpp for all options

**Comment by Crunch69** [comment]
M861 ? works never required a "?" mark before for Gcode

**Comment by mylife4aiurr** [comment]
I also didn't know about the "?". I actually thought the command wasn't working. So now that know about the "?". I ran the command after doing a "temp. calibration"
Send: M861 ?
Recv: PINDA cal status: 1
Recv: index, temp, ustep, um
Recv: n/a, 35, 0, 0.00
Recv: 0, 40, 0, 0.00
Recv: 1, 45, 0, 0.00
Recv: 2, 50, 0, 0.00
Recv: 3, 55, 0, 0.00
Recv: 4, 60, 0, 0.00
Recv: ok

Is that correct?

**Comment by stahlfabrik** [comment]
Well - I wonder - what should a mere "M861" do? Please have a look at Marlin_main.cpp where all options are listed.
Besides the "?" there is also the "Sx Iy" to set values. And other options.

The M860 works also not by just "M860" - obviously you want to give the temperature to wait for:-) Like "M860 Sx" 

Could this issue be closed?

**Comment by Crunch69** [comment]
Yes this issue can be closed
