### ISSUE TITLE
MK3 3.2.0-RC1 Purge line and print is moved "up" in y direction

### ISSUE THREAD

**Issue by stahlfabrik** [prusa3d/Prusa-Firmware#637]
As pointed out by others in the forum - I also experience now the phenomena that the purge line in front of the print is now shifted "up" in y direction. Exactly to where the lowest lasered line on the steel sheet is. With earlier version the line was more "down".

Also the print, which is supposed to be in the middle, seems to be moved "up" in y direction.

Here is the forum discussion: https://shop.prusa3d.com/forum/general-discussion-announcements-and-releases-f61/9-days-without-commit-on-github-i-feel-something-b-t15124-s40.html#p77996

**Comment by vanvlierden** [comment]
yep, can confirm: after the upgrade everything shifted about 5mm to the back. Purge line as well as print.

**Comment by Crunch69** [comment]
the PINDA probe also triggers off center to the back and left of the probe bed points

**Comment by alientek** [comment]
Fix: revert to official firmware, factory reset, run wizard then update to 3.2.0.

**Comment by stahlfabrik** [comment]
We are on official firmware (RC1 is official), I did a factory rest and calibrated in RC1.

I understand the workaround that you propose (downgrade to latest stable version, calibrate there, then update to RC1, do NOT do factory reset then and DO NOT calibrate) - correct?

**Comment by alientek** [comment]
Downgrade to latest stable version, then factory reset. After the wizard is run then upgrade back to RC1.

**Comment by alientek** [comment]
Do not run selftest or XYZ cal on RC1

**Comment by Crunch69** [comment]
If you do as alientek states you can run the temp cal of the pinda in 3.2.0 and it wont crash the bed. also since the xyz cal was done ie: in FW3.1.3 the pinda triggers correctly over the calibration points.  the xyz calibration points also translate differently when going from 3.1.3 to 3.2.0.  In 3.13 status xyz cal  i show 10.3 and 10.25 and in 3.2.0 status xyz cal  shows 6.93 and 6.37 There is definitely something wong in  the 3.2.0 xyz cal

**Comment by PavelSindler** [comment]
We are working on this issue. Thank you for reporting it.

**Comment by stahlfabrik** [comment]
Hmm. 3.2.0-RC2 - the line now has moved "down" again - but I wonder if it is still "higher" than in 3.1.3? Anybody else?

**Comment by edspeds** [comment]
I too noticed the purge line is closer to the original position but as you see, not quite where it was pre 3.2.0 RC1

**Comment by stahlfabrik** [comment]
I think this is fixed - or I got used to it. Closing...
