### ISSUE TITLE
Pausing print, and resuming it, disables option to edit Live Z-Axis

### ISSUE THREAD

**Issue by gcmartinelli** [prusa3d/Prusa-Firmware#641]
Using MK2S Kit received yesterday. 3.1.0 firmware.

**Comment by GurliGebis** [comment]
What height was it at, when you tried adjusting it?
AFAIK it only looks at the current height, and if it is higher than a few layers, it disables the Live-Z edit, since it only affects the first layer.

**Comment by Prusa-Support** [comment]
Hello! If you are still having this issue, please contact us at info@prusa3d.com.

Marina Curzi
Prusa Research
