### ISSUE TITLE
Dimming the LCD backlighting

### ISSUE THREAD

**Issue by koryba** [prusa3d/Prusa-Firmware#644]
It would be great, if the LCD backlighting could be dimmed. Especially in darker environments (e.g. printing during night) the very bright display can be disturbing.

Ideally in the "Settings" menu there is an option to dimm the backlighting with the rotation knob.

Thanks
Leo

**Comment by mvasilakis** [comment]
Not sure if it can be coded or not but in the interim you can print a cover. 
https://www.thingiverse.com/thing:2235933

**Comment by GurliGebis** [comment]
If I recall correctly, the backlight is controlled by a trimpot, so it cannot be controlled by software. (I might be wrong - it's been a while since I looked at the PCB for the LCD)

**Comment by Panayiotis-git** [comment]
As @GurliGebis mentioned, there is a trimmer on the LCD unit that defines the brightness of the LCD module.

**Comment by 3d-gussner** [comment]
There is a contrast trimmer R1 but the backlight (RLED on the silk) has a resistor 0 Ohm so it is very bright.
Checkout https://www.youtube.com/watch?v=WNIgmgV_O6Q how you can add a trimmer.

**Comment by MarekC3D** [comment]
Hi, MK3 is ready to set display backlight in 16 levels... we tested it :-) I will push this request forward to our Firmware development team.

**Comment by 3d-gussner** [comment]
@MarekC3D That is interesting ... is that a special LCD as i can see on my MK2 LCD that it is connected to 5V via the R1 0 Ohm resistor

**Comment by MarekC3D** [comment]
Oh, sorry. Einsy 1.0 board is ready for display backlight control, but current display module does not support it. No way how to control backlight with current version of hardware.

**Comment by karolzlot** [comment]
you can try this: https://www.thingiverse.com/thing:3213892

**Comment by mikromcz** [comment]
I think this can be closed. See:  #2270 for more
If you have FW 3.9.0+ and LCD board version A004+you have this option in menu ;)
For mod older LCD board see: https://forum.prusaprinters.org/forum/original-prusa-i3-mk3s-mk3-user-mods-octoprint-enclosures-nozzles-.../old-lcd-board-modification-to-allow-fw-3-9-0-brightness-control/
