### ISSUE TITLE
Option to turn of the beep when working with the LCD

### ISSUE THREAD

**Issue by koryba** [prusa3d/Prusa-Firmware#645]
It would be great to have the option to turn off the short beep when operating at the LCD.
This sound can be a little disturbing and might not always be required.

Thanks
Leo

**Comment by MarekC3D** [comment]
Thanks for feeedback, I will add this reqest to the development system.

**Comment by Prusa-Support** [comment]
From firmware 3.4.0 for MK3/MK2.5, and from firmware 3.2.2 for MK2S you can adjust the beeper notifications.

Marina Curzi
Prusa Research
