### ISSUE TITLE
Printing error doesn't display status info on LCD

### ISSUE THREAD

**Issue by dalgibbard** [prusa3d/Prusa-Firmware#648]
Hey all,
My printer encounters an error whilst printing, beeps a lot, and then demands that I push the button to unload filament, but doesn't actually say why it wants to do this, or what the problem is.

Would suggest it should display an error message first, then prompt user for filament removal.

Firmware: 3.2.0-RC1-461
Model: MK3 stock

**Comment by stahlfabrik** [comment]
That sounds to me like false positive from filament sensor. Workaround is to use other filament or turn sensor off.

**Comment by dalgibbard** [comment]
Ah that would make sense; this is the first time using translucent PETG. My main request is that the printer should say what's up on the LCD though :) I'm no psychic 😁

**Comment by stahlfabrik** [comment]
I agree!

**Comment by Prusa-Support** [comment]
You can see in our [Knowledgebase](https://help.prusa3d.com/article/filament-sensor-mk3-non-s_2125) the expected behavior of the filament sensor.

Marina Curzi
Prusa Research
