### ISSUE TITLE
MK3 3.2.0 RC1-461 flow rate at 95%

### ISSUE THREAD

**Issue by JoePrints** [prusa3d/Prusa-Firmware#651]
When turning the printer on, it is at 100% flow. But when a print starts is automatically goes down to 95% and I have to manually change it back to 100%.
Definitely repeatable as I have to do it for every print

**Comment by GurliGebis** [comment]
Does it also happen with the gcode files on the SD card, that was there when you built the printer?
It might be your slicer that is configured wrongly, so it sets the flow rate in every gcode file it creates.

**Comment by JoePrints** [comment]
I have checked Slic3r several times (1.39.1) and it checks out to be set correctly (works just fine on my MK2S). Someone on Prusa's website support said that it may be hardcoded that way...?
**EDIT** I found in Slic3r the start Gcode is set to 95-
M221 S{if layer_height==0.05}100{else}95{endif}
