### ISSUE TITLE
MK3 3.2.0 RC1-461 knob direction

### ISSUE THREAD

**Issue by JoePrints** [prusa3d/Prusa-Firmware#652]
The knob rotation direction is completely opposite of my MK2S.
MK3- **counterclockwise** to menu down and values up
MK2S- **counterclockwise** to menu up and values down
This is really frustrating when changing between printers.
Repeatable

**Comment by jwest75674** [comment]
Adding a menu item to reverse this as an option would be a great idea if possible.
--> I've only ever had an MK3, as such, swapping the rotation direction's impact on the menu would be really frustrating for users like me.

**Comment by JoePrints** [comment]
This is something that is frustrating no matter who you are.
Printing on both machines.... I start getting more than frustrated when the menu does not move the way the other one does.

**Comment by jwest75674** [comment]
As a side project, you could design a knob/LCD screen cover that have an arrow on it for rotation. While we wait for (hopefully) a fix to be implemented into the firmware.

**Comment by devilhunter84** [comment]
Hah! I built two MK3 clones, and used the normal 2004 LCD display for them.
Wondered why the knob rotates into the wrong direction, i thought the LCD assembly was slightly different from the stock Prusa ones. 

devs, please fix, so that it's like on the MK2. This is hella' annoying.

**Comment by Panayiotis-git** [comment]
See https://github.com/prusa3d/Prusa-Firmware/pull/656#issuecomment-397438236

**Comment by Panayiotis-git** [comment]
Please, have another look on https://github.com/prusa3d/Prusa-Firmware/pull/656#issuecomment-397715008.
I think that this issue should be closed.
