### ISSUE TITLE
3.2.0 Y axis shift when printing

### ISSUE THREAD

**Issue by Crunch69** [prusa3d/Prusa-Firmware#653]
When running firmware 3.2.0 there is a major Y axis shift when printing.  Downgraded to 3.1.3 Y shift is gone

**Comment by cnlson** [comment]
I think the devs will need an image to understand you could probably link the forums so they can see it.

**Comment by MarekC3D** [comment]
We are working on this issue. The version 3.2.0 RC2 will be patched.

**Comment by tarikku** [comment]
The fix as present in v3.2.0 RC2 does not resolve this issue for me. I used v3.1.3 before, and upgraded to 3.2.0 RC1 _without_ doing XYZ calibration afterwards. There was no shift in the Y axis visible.

After flashing v3.2.0 RC2 yesterday, and running XYZ calibration, the purge line is being extruded at the very edge of the printable area, i.e. some 5mm closer than it used to be with v3.1.3. You can see the previous purge line position faintly as there is some of the older purge line printed in PETG still visible.
XYZ calibration itself worked seemingly without a problem.

Edit: After having re-flashed v3.2.0 RC2 and ran the wizard, the issue has disappeared.

![photo 29 04 18 09 52 48 s](https://user-images.githubusercontent.com/3681601/39409790-b2f7346c-4bed-11e8-8aa3-911ec24d06eb.jpg)

**Comment by Prusa-Support** [comment]
Hello! Sorry for intervening on this thread so late. I can see this has been resolved with 3.2.0 RC2, closing the issue for now based on this info. In case of any more related issues, do not hesitate to let me know via email info@prusa3d.com mentioning me ("attn: Alessandro"). 

Alessandro Pantaleo
Prusa Research
