### ISSUE TITLE
3.2 (and previous) Calibrate Z doesn't ask about presence of steel sheet

### ISSUE THREAD

**Issue by jhoff80** [prusa3d/Prusa-Firmware#659]
When performing calibrate XYZ, the firmware asks me if the steel sheet is on the heatbed and confirms that it's in the correct state.

On the other hand, when performing calibrate Z, the firmware just starts calibration...even though (to my knowledge) it'll fail without the steel sheet on the heatbed.

**Comment by calvinbui** [comment]
+1
