### ISSUE TITLE
Selt Test fails on front fan in 3.0.10-8

### ISSUE THREAD

**Issue by ChinookTx** [prusa3d/Prusa-Firmware#68]
Downloaded 3.0.10-8 on Apr 1st 2017 (no it's not a joke).  Seems like the self test fails on the front fan on 2 of my printers.  After the previous test  (left fan test), it just fails without giving me a choice to select an answer.  If, upon pressing the button on the previous screen (left fan test) I quickly scroll the wheel and then press the button, it succeeds and moves on to the next step, allowing me to continue.

**Comment by PavelSindler** [comment]
Thank you for reporting this issue. It is related to long button press implementation and it will be fixed in next commit.
