### ISSUE TITLE
Using M600 with optional arguments results in too fast extruding

### ISSUE THREAD

**Issue by yschroeder** [prusa3d/Prusa-Firmware#69]
The `M600` command has optional parameters (`X`, `Y`, `Z`, `E`, and `L`).
While `X`, `Y` and `Z` work as expected, using `E` and `L` can result in too fast (unsafe) extrusions.

Reproduction:
* `M600 E0 L0` results in a filament change operation without any retraction (this can be handy if you do not actually want to change the filament but stop to insert something into the print and then continue)
* Pressing the knob as told by the display results in very fast (hardcoded) filament feed to load the new filament
* As the filament was not unloaded before and is still in the nozzle it is extruded at high speed as implemented [here](https://github.com/prusa3d/Prusa-Firmware/blob/MK2/Firmware/Marlin_main.cpp#L4997)

Expected behaviour:
The code to handle `M600` should check if the filament was unloaded and only load it if it was really unloaded first.

The original Marlin firmware has a check and only loads if it unloaded first as implemented [here](https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/Marlin_main.cpp#L7269).

This needs to be fixed for both, `E` and `L` parameter.

**Comment by PavelSindler** [comment]
Thank you for reporting this issue.
