### ISSUE TITLE
3.2.0 RC2 mk3 Temp. Calibration fails @2/6

### ISSUE THREAD

**Issue by rainersc** [prusa3d/Prusa-Firmware#692]
I updated to RC2 yesterday, ran full calibration XYZ without problems, but when trying to run a temp. calibration, the process stops @ step 2/6.
i wait for >30 minutes, but nothing happened any more.
The power supply clicks when the bed is being heated in sync with the LED. ( i have not noticed that "clicking" anytime before with my MK3.

**Comment by CacikeOtoao** [comment]
I experienced the same issue on MK2.5 when on 3.2.0-RC2. downgraded to 3.2.0-RC1 and was able to do TEMP Calibration.

**Comment by BManx2000** [comment]
Same here on my MK2.5, it failed on 1/6.

**Comment by Prusa-Support** [comment]
Hello! Sorry for intervening on this thread so late. From the info I have at hand, this should have been resolved in the meantime with the more recent firmware releases. Closing the issue for now based on this. In case of similar issues, do not hesitate to let me know at any time info@prusa3d.com mentioning me ("attn: Alessandro"), we'll look into it. 

Alessandro Pantaleo
Prusa Research
