### ISSUE TITLE
3.2.0 RC2 mk3 inconsitent 9 point bed level check failures

### ISSUE THREAD

**Issue by TimothyGold** [prusa3d/Prusa-Firmware#693]
I installed RC2 last night.  I did a full reset and went through all the calibration and self check which went really good.  I started a few test prints and one thing I noticed right a way was that my Live Z offset had to be set way lower.  It went from about 6.34 to 9.34 in the new 3.2 RC2.  After getting this set right I noticed that about 50 percent of the time for no real reason the 9 point mesh check failed.  Because I use Octoprint when this happens then it kills my serial connection and I have to reset the printer and reconnect to start again.  Something in this new check does not seem real reliable.  The bed is clean and the nozzle is clean and all the initial calibration passed 100% with a perpendicular calibration.

**Comment by PavelSindler** [comment]
Don't you know what was the errror message when the calibration failed?

**Comment by TimothyGold** [comment]
I am very aware that the calibration failed and was indicated by the message.  My concern is primarily that it fails randomly for no apparent reason and when it does fail it kills my serial connection to OctoPrint which forces me to reconnect and then go through the reheat process etc to try again.  Then I try again without any other changes and it succeeds.  About a  50/50 gamble of whether it passes or not.  Every other calibration succeeded first try including temp calibration.  Kind of a pain when this is the result of this kind of failure..  I also seem to be having as many false crash detections as I did with the last released firmware but now for some reason it seems that I am not recovering and a layer shift results.  I can say that there are some definite positives in this release.  First layer consistency seems to be better.  The temp of the extruder motor is definitely lower now.  I may have to revert back to the the latest release in order to keep going as I have to have a better chance of completing my prints at this point.  Thanks for all the hard work..

**Comment by TimothyGold** [comment]
I need to add another issue to this 9 point calibration issue.  Tonight I continued to work with RC2 and started a print.  This time when it failed the usual Serial disconnect happened but this time when I reset the printer to start again the head bed failed to heat even though I could see that the preheat had set it for 80 C.  I stopped everything and cooled it down and tried again.  I opened the box to check the fuses and all were good.  I powered up and still the bed would not heat.  I checked the voltage on the heat bed feeds and they were at 0 when it should have been trying to heat.  I let it sit for a while and then tried again and the bed started to work again.  When it fails the calibration it stops abruptly and I don't think whatever is happening is good as it abruptly kills a process.

**Comment by PavelSindler** [comment]
PR https://github.com/prusa3d/Prusa-Firmware/pull/701 fixes false mesh bed leveling errors (it was caused by high sensitivity of Z-axis stall guard). If you have layer shifts after crash detection, please re-run selftest. It contains accurate sensorless rehoming calibration.

**Comment by AYapejian** [comment]
Running into a similar issue on RC2, I also compiled the latest from head ( rev 777beac ) and almost every time mesh bed leveling runs I get the message "Bed leveling failed. Sensor didnt trigger. Debris on nozzle? Waiting for reset." previously I never saw this message before.  I reran self test which fails due to disconnected filament sensor but everything else passes so that should be fine I think.  Cleared my XYZ calibrations tried to recalibrate and that fails as well on the second calibration point saying it couldn't find the point. 

I'm reverting FW versions now to make sure the problem is resolved, I suspect it will be, will update if that is not the case however.

**Comment by TimothyGold** [comment]
I noticed last night that these false triggers only occur when I am feeding filament from a spool holder that is further away than the default frame mounted spool.  This seems to put a little bit more tension on the filament than maybe I get from the other.  The tension is not a lot at all but I think is enough to fail the mesh level checks at random points.  @PavelSindler adjusted the stallguard sensitivity for the next RC.  Hopefully this will be enough to pass the tests for users that have a need for other filament holders.

**Comment by AYapejian** [comment]
Curious, I reverted to FW 3.1.3 and I'm seeing the same issue (cleared/reran calibration first) failure on 3rd point mesh leveling.  @TimothyGold  interesting comment, I did recently switch out filaments, going to rerun everything with filament removed, see if I can get a working printer at this point.  I assume you mean the below values in the variant configs? Thanks for the heads up

```c++
#define TMC2130_SG_HOMING       1     // stallguard homing
#define TMC2130_SG_THRS_X       3     // stallguard sensitivity for X axis
#define TMC2130_SG_THRS_Y       3     // stallguard sensitivity for Y axis
#define TMC2130_SG_THRS_Z       3     // stallguard sensitivity for Z axis
#define TMC2130_SG_THRS_E       3     // stallguard sensitivity for E axis
```
