### ISSUE TITLE
3.2.0-RC2 - MK2.5 Under Extrusion

### ISSUE THREAD

**Issue by cobramike** [prusa3d/Prusa-Firmware#694]
After the latest update i have noticed under Extrusion. And befor the update there was none.

**Comment by MarekC3D** [comment]
Can you send me a g-code with this issue? 
What kind of filament do you use?

**Comment by PavelSindler** [comment]
Please check also axis steps per unit for extruder. You can do it by connecting to printer via serial line (115200 baud) and sending M503.

**Comment by Prusa-Support** [comment]
Hello! If you are still having this issue, please contact us at info@prusa3d.com.

Marina Curzi
Prusa Research
