### ISSUE TITLE
M600 results in communication timeout with host

### ISSUE THREAD

**Issue by yschroeder** [prusa3d/Prusa-Firmware#70]
While waiting for a filament change after issuing a `M600` command  the printer does not answer to the host resulting in a timeout (in my case in OctoPrint).

It should instead answer with busy messages regularly so the host knows that a long running command is running (like original Marlin does).

**Comment by PavelSindler** [comment]
Thank you for your feedback. This is related to #67.

**Comment by yschroeder** [comment]
Yes, sorry for the duplicate I just searched for "timeout" and "M600".
