### ISSUE TITLE
Print Fan error on 3.2.0-RC2

### ISSUE THREAD

**Issue by cahe** [prusa3d/Prusa-Firmware#703]
Hi,
On 3.2.0-RC2 I'm getting print fan error when transitioning from layer 1 to layer 2. Self check says print fan is OK. On 3.1.3 (downgraded to check) the same gcode works fine.

[Obudowa Furia D.zip](https://github.com/prusa3d/Prusa-Firmware/files/1961374/Obudowa.Furia.D.zip)

**Comment by PavelSindler** [comment]
Thank you for reporting this and for gcode. It was caused by mistake when merging MK25 branch into MK3 which results in missing fan check synchronization with planner. PR https://github.com/prusa3d/Prusa-Firmware/pull/713 fixes this issue.
