### ISSUE TITLE
High pitch noise from cooling fan at less than 100% fan speed

### ISSUE THREAD

**Issue by kacperd2808** [prusa3d/Prusa-Firmware#706]
While printing with PET-G I need to decrease fan speed from 100% to 0-60% and the high pitch noise from cooling fan gives me a headache.

**Comment by magkopian** [comment]
That's because the used PWM frequency is on the audible range. There's already an open issue regarding this #460.

**Comment by DRracer** [comment]
Duplicate of #460 , closing
