### ISSUE TITLE
Strange extruder behaviour after 3.2.0 upgrade

### ISSUE THREAD

**Issue by ghost** [prusa3d/Prusa-Firmware#708]
After the 3.2.0 upgrade I was about to print the same model that I already printed about 25 times with 3.1.3 
When it prints the first layer, I could observe that the extruder puts down blobs at certain spots (Marked green in the pic) with a noticable click (extruder gears speed up for a fraction of a second). The click also appears on the turning points of the first layer (marked red) in a rising manner. 
Just to be clear: this was NOT the case with 3.1.3 with the exact same gcode.
Addition to the green marked blobs: The printhead stops there for a moment (about 1/2 second), clicks / speeds up and goes on after this

Is this a known issue?
![31732115_10155658723396925_7807423178807967744_n](https://user-images.githubusercontent.com/31340618/39476433-2f09c992-4d5c-11e8-8c1e-d907cc9c761d.jpg)
Video of the issue:
https://www.youtube.com/watch?v=-5NeWJXItd0&feature=youtu.be

**Comment by alientek** [comment]
Check your belts

**Comment by ghost** [comment]
Dude, seriously?
Did you even read what I wrote and watched the video?
The issue was not there in 3.1.3 (printed the same model 5 minutes prior to the upgrade).
It's an extruder issue, not a belt issue

**Comment by alientek** [comment]
@Paulbsh Im having no issue's and it sounds like a screw is loose on the x,y motors.

**Comment by ericclinedinst** [comment]
@Paulbsh this alientek guy is trolling the github posts. He's ober on 602 and many others doing the same. I think he's a Prusa employee. Or King Prusa himself.

**Comment by ghost** [comment]
I see. Maybe someone without a complex has a clue?
I repeat: This does not happen with 3.1.3

**Comment by alientek** [comment]
@ericclinedinst Could you kindly remove the stick from your ass? you didn't even come here to help only bash me. @Paulbsh At least i came with some input you ungrateful bastards.

**Comment by ghost** [comment]
Alientek, please get out of this thread. Your "input" was clearly not meant in a serious manner.

**Comment by alientek** [comment]
@Paulbsh Well if thats what you think then good luck fixing it yourself.

**Comment by ghost** [comment]
Do you really think that "check your belts" is the right thing here? If you would have read one single line of my post, you would have not commented. 
I'm now waiting for people who actually have a clue. Thank you

**Comment by andredigenova** [comment]
They reduced current to the extruder stepper in 3.2.0 in an effort to reduce the heat generated by the motor. Sounds like your extruder is missing steps as a result of that change. Other people are experiencing this as well.

Try increasing your temps or taking other measures to reduce the amount of force required to extrude. Otherwise revert back to 3.1.3 until they come up with a fix.

**Comment by moggieuk** [comment]
I was also thinking that your extruder was missing steps as a result of reduced current.  You can push the current back up with gcode to test.  Alternatively slow your print down (reducing flow rate) as a test of the theory.

**Comment by ghost** [comment]
@moggieuk, wouldnt that mean that the gears would jump backwards?
They're jumping forward at the mentioned points

**Comment by moggieuk** [comment]
Hmmm, I just watched your video, very strange. It's hard to tell what the extruder is doing but it certainly looks like it is trying to lay down a blob at the end of every line.  Thinking of what has changed in the firmware other than extruder current the other thing is linear advance.  Does your gcode have a silly k-factor setting that would have been ignored in v3.1.3?

**Comment by Crunch69** [comment]
i had a very similar issue and it was caused by something in my gcode script.  I did not do any heavy analyses as I needed to get a print started I just replaced my script I used in 3.1.3 with the simple 1 below and it went away. 

G28 W ; home all without mesh bed level
G0 X50 Y50 Z0.15 ; this is a good PINDA heating position
M104 S215; set extruder temp
M140 S60; set bed temp
M190 S60 ; wait for bed temp
M109 S215; wait for extruder temp
M860 S35 ; wait until PINDA is >= 35C
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0  F1000.0 ; intro line
G1 X100.0 E

**Comment by PavelSindler** [comment]
Hello @Paulbsh , can you send the gcode file?

**Comment by Mike4U** [comment]
Does this only happen only on the first layer.  It looks like your live z is to low.  The low height is causing the pressure to rise and the extruder to skip.

Note the actual z distance changes with the same live z number between some of the revisions.

**Comment by wavexx** [comment]
I think I fixed this without knowing with #2416 which didn't handle G92 E0 correctly, likely causing stuff like this.

**Comment by Prusa-Support** [comment]
This thread could be related to issue #765, or could be solved by PR #2416 mentioned above.
Also, this thread has been silent for years.
For these reasons, this issue will be closed.

Please check the issue and the pull request mentioned above to learn more about the conclusion of this case. 
Comment below or feel free to open a new issue if you feel this issue deserves a separate discussion.

Michele Moramarco
Prusa Research
