### ISSUE TITLE
Temperature tower function in firmware

### ISSUE THREAD

**Issue by hanpal** [prusa3d/Prusa-Firmware#710]
It would be very handy to have a built-in function in the firmware for "temperature tower" or similar for finding the best temperatures. This would simplify a lot for all users since a temperature tower is a bit awkward to produce without more or less complicated tweaking using the slicer.

**Comment by GurliGebis** [comment]
Might be better to implement it in Slic3r, so it can generate it using the different settings for printer, filament ect. - and it wouldn't add any more code to the firmware, which is already reaching the space limit.

**Comment by stahlfabrik** [comment]
And in Slic3r is everything present to do it easily already (temp change at certain layer heights). So someone who bothers for a perfect temp will have a straight forward way to do it already?!

**Comment by hanpal** [comment]
Yes you can do it but it would simplify the task a lot if this was built-in in firmware. Load new filament, adjust min max temp and height steps if needed. Press OK and it runs without having to use a slicer. If similar operation was included in Slic3r, fine, would still be easier from the printer.

**Comment by stahlfabrik** [comment]
Like GuliGebis said: there is no memory left to spare AFAIK - and there are many other things that need work.:-)

**Comment by mylife4aiurr** [comment]
@stahlfabrik 

> And in Slic3r is everything present to do it easily already (temp change at certain layer heights). So someone who bothers for a perfect temp will have a straight forward way to do it already?!

I could not find how to easily do it slic3r?? Cant "find temp change at certain layer heights" setting??

**Comment by mvasilakis** [comment]
@mylife4aiurr 
Identify the Z height you need to change temperatures and add this Gcode to change temps on certain layers. Change the z==# to the z height of each layer where you want a temp switch. This will work in any slicer on layer change gcode section.

Paste G-code into Slic3r, Printer Settings, Custom G-code, After Layer change G-Code.

{if layer_z==10}M104 S190{endif}
{if layer_z==20}M104 S195{endif}
{if layer_z==30}M104 S200{endif}
{if layer_z==40}M104 S205{endif}
{if layer_z==50}M104 S210{endif}
{if layer_z==60}M104 S215{endif}
{if layer_z==70}M104 S220{endif}

**Comment by mylife4aiurr** [comment]
@stahlfabrik 
Thanks for posting instructs. I didnt know how to accomplish this in slicer, although I wouldn't call it easy. Not hard but Simplify3d and Cura definitely have more noob friendly ways to accomplish a temp tower. So i agree with @hanpal

**Comment by bubnikv** [comment]
Instead of 
{if layer_z==10}M104 S190{endif}

you can vary the speed using a numeric expression, like
M104 S{190+layer_z}

**Comment by Panayiotis-git** [comment]
If there was a modulo function defined, it could be even simpler! But not yet.

**Comment by vestom** [comment]
Thanks for the instructions! I will try this in Slic3r.

Instead of spending precious firmware space on a hard coded temperature tower, it could just be added to the example files shipped on the SD card.
Why not generate such a file and and make a pull-request to https://github.com/prusa3d/Prusa3D-Sample-Objects ?
