### ISSUE TITLE
Thermal runaway reset

### ISSUE THREAD

**Issue by hon-po** [prusa3d/Prusa-Firmware#711]
Compiling the latest code (3.2.0-RC2), want to make sure the hotend thermal runaway protection is working (thanks to Thomas video).

With fuse F2 removed, the protection kick in at about 1:54 (for first occurrence). If I do not reset the board, but issue M999 to clear the error, motion is re-enable, but for subsequent heat up, protection kick in just after 17s.

Also, in the error state, M107 will stop the print fan. I think ignore M106/M107 gcode in error state is more desirable.

**Comment by Prusa-Support** [comment]
Hello! I am absolutely sorry to intervene on this so late. This should have definitely changed in the meantime, at this time the thermal runaway blocks the printer power when the temperature drops by more than 15 °C for more than 45 seconds. If the temperature reading doesn't recover in the set time period, the printer will shut down and display the Thermal Runaway error. 

In case it's still relevant - how did you reproduce the thermal runaways? 

Alessandro Pantaleo
Prusa Research
