### ISSUE TITLE
Higher z in home position would simplify loading filament and cleaning the head bed

### ISSUE THREAD

**Issue by hanpal** [prusa3d/Prusa-Firmware#721]
A. The home position is very low in z and it's hard to see if the loading is successful without bending down and directing a lamp under the nozzle. Also note that all users are not 20 years old with perfect sight.

B. Sometimes the filament will also pile up and clog the nozzle, as a result of the nozzle being so near the heat bed.

It's tedious to adjust z manually before loading filament but this is what I do now and then to solve both problems.

A simple solution for both problems would be to have a higher z value in the home position. This will also simplify cleaning the heat bed.

No extra memory in firmware required...

Another option would be to increase z automatically when unloading filament. But to also simplify cleaning of the heat bed, it's better to increase z in the home position.

**Comment by stahlfabrik** [comment]
Hi @hanpal 

I do not know if your request is possible because "home" means "0" - where the ends are.

It would be nice though if with "autoload filament" Z would raise - but that would require that the printer is homed:-) So it is unrealistic too

Do you know that long pressing the dial knob takes you quickly to "move z". So changing z is not tedious at all. I think that might help you getting along. So before you insert filament, just move Z up quickly to your liking

**Comment by hanpal** [comment]
OK didn't know about that long pressing. "home" cannot be zero in z since the nozzle is some distance above the heat bed already. I just want it to be 50-100mm higher to simplify loading and cleaning. Should not be a big deal and are there really any big disadvantages?

**Comment by stahlfabrik** [comment]
I am not sure - there  might be pros and cons for both. 

I just think that loading filament can also happen without the printer being homed. So why change home's z hight if you do not even know where z is:-) For me personally the long press is good enough for that aspect (loading filament)

**Comment by hanpal** [comment]
I don't know the home's z and don't need to.  "z_home = z_home + 50.0" would be sufficient...

**Comment by nospoon** [comment]
I'd say having the print head move to the top after finishing the print would also help with decoupling the steel sheet. I always find myself manually moving the Z up with smaller prints just to get the extruder out of the way.

**Comment by koenkooi** [comment]
I've changed the end gcode in slic3r to always raise z to 209, it's a huge time and motivation saver :)

**Comment by rommer** [comment]
Raising the Z height will effect mesh bed leveling since the pinda probe will not be over 35C which is needed to get a decent first layer. 

The long press works very well for me as well.

**Comment by stahlfabrik** [comment]
The solution is really to discover and use the end gcode imho.

All the way up is the worst I can imagine. That noisy Z axis should run as little as needed:-) And as @rommer said. The PINDA likes it warm so it likes to stay low.

No doubt could Z raise to a minimum value after a print so that the heatbed sheet could be easily detached - but again: the end gcode is your friend

**Comment by sniper85500** [comment]
@hanpal 

so why you just change the prusa firmware just for you to get a higher Z? I dont want it on my printer :-D

**Comment by nospoon** [comment]
I don't see how rising Z after finishing the print can possibly affect bed leveling which is done at the begining. You would still need to wait for the bed to cool down before taking the part off and starting a new print, so I really see no relevance here.
That being said, I'm not insisting on having this in the firmware, I don't mind manually moving the Z axis :)

**Comment by bubnikv** [comment]
With the upcoming Slic3r 1.40-beta we will move the print head couple of cm
up at the end of the print.

**Comment by hanpal** [comment]
You only need to raise z if below a certain level after finished printiing, 5cm or similar. If lower, raise to this z.

**Comment by bubnikv** [comment]
@hanpal 
> You only need to raise z if below a certain level after finished printiing, 5cm or similar. If lower, raise to this z.

This will be freely configurable through a Slic3r custom end G-code.

**Comment by hanpal** [comment]
Thank you. My Prusa i3 Mk3 is so hazzle free so the remaining manual actions become visible... Like:

- Raising z when changing filament, to see what's happening and to avoid clogging of nozzle due to filament piling up when z is close to the heat bed.
- Raising z when removing the flexible steel sheet, it can otherwise hit the nozzle or is tedious to remove if this shall be avoided.
- Preheat, maybe I should write another issue since I usually manually enter the Preheat dialog and then step down and select PLA. What about an automatic preheat to last selected Preheat setting when turning on the power to the printer? Would make it even more simple to use.
