### ISSUE TITLE
[MK3 - 3.2.0] After finishing every layer, extruder moves to beginning of X-Axis.

### ISSUE THREAD

**Issue by jl1990** [prusa3d/Prusa-Firmware#725]
As title says, after one layer is finished, extruder moves to the beginning of the X-Axis. After reaching that point, it comes back and continues printing again...
Please, fix soon, as it increases a lot printing time and leads to other printing problems.

Thanks

**Comment by GurliGebis** [comment]
Are you using Octoprint? If so, do you have the timelaps feature enabled?

**Comment by jl1990** [comment]
Yes to both questions... Maybe I got some configuration wrong?

**Comment by stahlfabrik** [comment]
No, that is what octolapse does. You could close this issue! 

EDIT: Sorry, do you have octoplapse even installed? (was a little quick there;-))

**Comment by jl1990** [comment]
Yes, exactly I had octolapse installed, I will read about how to configure it properly. It's strange that this started happening to me from RC2 in advance when I had it installed earlier. Thanks!

**Comment by stahlfabrik** [comment]
Yes the coincidence is funny:-)
