### ISSUE TITLE
Error in Wikipage: Manual temperature calibration

### ISSUE THREAD

**Issue by stahlfabrik** [prusa3d/Prusa-Firmware#726]
Dear @PavelSindler: The first step IS a must. For the manual print based temperature calibration to succeed the temperature calibration MUST be turned off. There are two ways to do that: a) "M861 Z" erases the offset values in the EEPROM. b) in menu/setting/Temp. cal., the "switch" has to be toggled to "off". To be sure, BOTH actions are recommended

I would suggest:

**Manual temperature calibration procedure:**

1. Be sure to completely turn off current temperature calibration. In order to do that, erase current temperature calibration offset values by "M861 Z" gcode. This will store zero offsets to EEPROM for all PINDA probe temperatures in 35 - 60 °C range. You can check with M861 ? which values are currently stored in EEPROM. Additionally, it is recommended to go to the menu / settings and make sure that "temp. cal." is "off".

**Comment by stahlfabrik** [comment]
Could I gain write access to that page?:-) I am sure it is not necessary - I am just wondering

**Comment by PavelSindler** [comment]
Yes, you are right of course. I just edited it. I will definately improve this wiki page tomorrow (I need to add info how to count offsets in usteps).

**Comment by stahlfabrik** [comment]
yes that is one thing that is missing:-) On the forum thread that I started, some people now have done the manual print based calibration. They also offered more tricks on how to choose the perfect first layer and even how to lay out the first layer infill. Nice stuff. If you have a few minutes, you could read through the (maybe?!) last 3 pages or so. There is some nice content there

**Comment by stahlfabrik** [comment]
Start the read here please: https://shop.prusa3d.com/forum/hardware-firmware-and-software-help-f64/1st-layer-problems-in-depth-look-at-software-pinda-t14815-s150.html#p82250

**Comment by PavelSindler** [comment]
Thank you, I will definately check it.

**Comment by stahlfabrik** [comment]
Hi @PavelSindler 
while still waiting for your refreshed guide on how to to the calibration I saw that the start GCODE snippet that you have integrated to the WIKI pages is missing a
`G28 W ; home all without mesh bed level`
in the beginning - otherwise the various movements cannot be done safely (or at all)

**Comment by gertlind** [comment]
This row seems to be wrong ; Calculate the ustep values for each temperature T (40, 35, 45, 50, 55, 60).
Should be 35, 40 .....   I guess.

**Comment by gertlind** [comment]
A calculation example how to get the microsteps would be nice.

**Comment by stahlfabrik** [comment]
I agree that the article still could be enhanced for sure! But now that the misinformation is gone, I will close the issue
