### ISSUE TITLE
Filament out Issue

### ISSUE THREAD

**Issue by AikiAviator** [prusa3d/Prusa-Firmware#734]
When receiving a filament out issue the 3.2.0 firmware identified a filament out and stopped print. Upon reload of new filament, printing restarted, however print temperature was reset to cooldown. Printer continues Xyz movements, however no filament is extruded as printer response was that too cool to print and print needed to be manually stopped.

NOTE: Filament out message was erroneous. Was utilising 3dFillies PETG and filament was loaded and operational. Had erroneous Filament out error most likely due to shininess of filament.

Noob to this process, so if further info required, please advise.

**Comment by PavelSindler** [comment]
PR https://github.com/prusa3d/Prusa-Firmware/pull/760 fixes this issue.

**Comment by Prusa-Support** [comment]
Hello! Sorry for intervening so late in this thread. Closing this thread based on the linked pull request that fixed the issue at hand. In case anyone might be experiencing similar issues, do not hesitate to let me know info@prusa3d.com mentioning me in the subject ("attn: Alessandro"). 

Alessandro Pantaleo
Prusa Research
