### ISSUE TITLE
Garbage output during self-test & xyz calibration on 3.2.0

### ISSUE THREAD

**Issue by zmerlynn** [prusa3d/Prusa-Firmware#736]
I was running another self-test, and right after waiting for bed cooling (and possibly one other step), it went into this garbage display like the LCD was just displaying random memory. Freaked me out for a second, then the self-test continues. 

Then something similar happened during XYZ calibration.

I didn't see either of these, so I'm assuming it's something to do with (MK3) 3.2.0

Screenshots attached.

<img width="606" alt="screenshot 2018-05-11 22 45 19" src="https://user-images.githubusercontent.com/4942464/39954121-aa56b596-556e-11e8-9017-fa364b3dd0e5.png">

<img width="597" alt="screenshot 2018-05-11 22 56 27" src="https://user-images.githubusercontent.com/4942464/39954122-b7e5e1c8-556e-11e8-82bd-7bf6119a4f4f.png">

**Comment by Zaf9670** [comment]
Did you compile your firmware using Arduino IDE or just apply the release file?

**Comment by tuxmobil** [comment]
I've seen similar garbage before my MKS 2.5 upgrade and, as no other malfunction appeared, assumed that it is an interference problem with the display wires. Haven't seen this after rewiring during MKS2.5 upgrade.

**Comment by lolsborn** [comment]
I had this happen during initial calibration once.  Restarting it seemed to fix the issue and I haven't seen i since.
