### ISSUE TITLE
Turned of hotend and heatbed after several Y crashes, filament sensor not detected until printer turned off and on (reset was not helping)

### ISSUE THREAD

**Issue by pacaj2am** [prusa3d/Prusa-Firmware#739]
Gcode was with LinearAdvance 

I did Extruder linearity correction 

I started print - was printing approx. 3 hours (unfortunately 9 Y crashes) , but when I came to the printer - both heatbed and HE was set to 0°C and printer was printing to the air (extruder was not jammed, when I preheated PLA i was able to get out filament). When I wanted to re-insert filament, filament sensor was not working, reset did not helped - I needed to turn of the printer, than it was able to detect filament sensor (reset did not help).

**Comment by Zawadaki** [comment]
I had the same issue, filament sensor did not trigger when putting new filament, and during print I got a filament runout message which never happens me before with this filament, I disabled filament sensor as I did with the crash detector which also gves me false alarms

**Comment by MarekC3D** [comment]
What is the status in Settings - Fil.sensor ?

**Comment by Zawadaki** [comment]
Now is OFF but when this happed was ON

**Comment by pacaj2am** [comment]
On my machine, there was N/A. When I tried to turn on, there was error message I don't remember.

Needed to power of printer and turn ON again.

**Comment by japato** [comment]
I had the same issue as is on beginnig of this thread. Seems at me, there is only problem between 3.2.0 and Octoprint 1.3.8, see listing from Octoprint terminal, codes for cut-off temperature are sent to printer after crash message from printer. I had to dissable serial port on printer. Printing went from SD. No filament sensor issue, it  is always on.

[Crash.txt](https://github.com/prusa3d/Prusa-Firmware/files/2083337/Crash.txt)

**Comment by zehkaiser** [comment]
I'm also having this issue. The first time the filament sensor was disabled and I walked into my office to see the HE and bed were turned off while the printer was still running. The second time I had enabled the filament sensor and it had a false detection of no filament. On resume both were off again. I have disconnected Octoprint (even though I've been printing from SD), disabled the filament sensor, and enabled stealth mode. I'll see if it happens again.

**Comment by applekeith** [comment]
I just had my filament sensor replaced. Apparently, there was a bad batch. Mine was working fine, then went N/A and never came back. Their online chat resolved it quickly and efficiently.

**Comment by pacaj2am** [comment]
I can confirm, that Heatbed and HotEnd were turned of after Y-crash detected. It happend yesterday aswell. Never happened before. I started to use Linear Advance with the new firmware.

**Comment by jdn-za** [comment]
Having the same issues https://github.com/prusa3d/Prusa-Firmware/issues/754

FW: 3.20 & 3.2.1

**Comment by PavelSindler** [comment]
Was there message "Heating disabled by safety timer." on display? Were you printing from SD card?

**Comment by PavelSindler** [comment]
Ok, It is clear to me now. This issue is caused by crash detection when using Octoprint (even if you are printing from SD and using Octoprint only for monitoring purposes).

**Comment by pacaj2am** [comment]
Any other workaround than to turn off rpi port?

**Comment by Dolnor** [comment]
3.5.1. Had a safety timer pause on a 20h print pause itself at 18h mark via Octoprint, without losing printer communication. And it has decided it's gonna stop right then..

**Comment by 3d-gussner** [comment]
@pacaj2am This is an old issue and I think that has been fixed, Please confirm and close this issue.
[stale][fixed]

**Comment by JohnnyDeer** [comment]
I'm closing this issue as stale, thanks for understanding.
