### ISSUE TITLE
File names get cut off on OctoPrint

### ISSUE THREAD

**Issue by mnl1121** [prusa3d/Prusa-Firmware#74]
Please add this fix to the firmware!
https://github.com/MarlinFirmware/Marlin/commit/2d22902d080b08c65ebdf5f8b3f03529ccd58144

Without it OctoPrint can't be used to print from the web interface as uploading, selecting, starting files doesn't work. 
http://i.imgur.com/5B4xcyh.png

**Comment by mnl1121** [comment]
Hmm looking at the code it appears to be already implemented. I'm not sure why then, but the file names are incorrect when viewing on OctoPrint. Also can't upload, select, or start printing any files using OctoPrint.

**Comment by bubnikv** [comment]
The FAT library which the Marlin integrates does not support long file names. In general, the FAT code does not support manipulation of files by their long names. The only place where the long file names are supported is the directory listing,

**Comment by mnl1121** [comment]
Can you explain further? You mean it only supports short file names as in 8 characters or fewer? For OctoPrint to be compatible do I only need to ensure the file name is short enough?

EDIT: Or is nothing wrong with the short file names and the problem of selecting/uploading/starting a print is unrelated?

**Comment by bubnikv** [comment]
In the times of MS DOS the file names had maximum 8.3 (8 for file name, 3 for extension) characters. Then came Windows 95 with a VFAT file system supporting long names, but also maintaining a legacy 8.3 file name for each long file name. These 8.3 short file names are still supported and you can list them by running dir /W on Windows.

So you can work with the long file names by their 8.3 counterpart.

**Comment by mnl1121** [comment]
I see. So this problem is unrelated.

**Comment by mnl1121** [comment]
For anyone else with the problem of not being able to upload, select, or start prints, take out the SD card and try again. Upload directly to the Pi instead and OctoPrint works great with the Prusa i3 MK2.
