### ISSUE TITLE
[MK3 3.2.0] - PID Calibration not suitable for HTPLA

### ISSUE THREAD

**Issue by workinghard** [prusa3d/Prusa-Firmware#742]
While printing HTPLA, the nozzle is around 10C below the set temperature of 245C.
Reproducible issue. First layer is printed without a fan, nozzle keeps up at 245C. For the second layer as soon as the fan kicks in 100%, temperature drops by 10-15C. PID control reacts and trying to regulate but stays around 10C under the set temperature.
* Raising the temp leads to raised temp but still stays around 10C under the set temp
* Deactivating FAN leads to stable 245C
* Raising the FAN speed slowly (first layer 10%, second layer 20%.... to 100%) leads to stable 245C
* No issue on MK2S 3.1.0

I suggest to increase Kp and Ki values to make PID control more aggressive and to compensate strong part cooling fan on MK3

**Comment by kwaad2** [comment]
My PID is *PERFECT* and I don't wanna mess with it. (I get about 0.2c fluctuation)
But is it possible to do PID calibration with the fan on at 100%? That might help?

**Comment by workinghard** [comment]
@kwaad2: Have you tried the described scenario? Does it work for you?

**Comment by kwaad2** [comment]
https://preview.ibb.co/fxG5GJ/PID.png

it took about 1.5 minutes to go from 210 to 240, with fan at 100%. My print finished, however it stabalized at 237, and was slowly "heating". (It was at 239.5 when my print finished)
There was a PID hiccup though. (but not a "big" deal)

**Comment by workinghard** [comment]
@kwaad2 Your screenshot does not look like perfect PID control :).
I have a workaround by raising the fan speed slowly over time. But that's not ideal solution causing the layer look slightly different. MK2S does not have this issue. It reacts a lot faster and stabilize at 245C already on the second layer. 
I can see PR is limiting a fan speed at 50% for their PET profile (240C). This is also one of the solutions to bypass this issue for HTPLA. But again, I see no reason why the PID control (or calibration) shouldn't be adjusted for MK3 to work with 100% Fan speed, even for higher temps.

**Comment by PavelSindler** [comment]
Thank you for feedback.
Have you tried to run PID calibration? 
There is gcode M301 for setting Kp, Ki and Kd. You can do it manually using this gcode and then store it to eeprom using M500.

**Comment by workinghard** [comment]
@PavelSindler: Yes, I ran the PID calibration without noticeable change. Is there any way to read the current values? Would be great to have a starting point for modifications. Will also try to run PID calibration with Fan on and report back the results.

**Comment by kwaad2** [comment]
M503 will display your current values.
I am working on getting a PERFECT 230c (with part fan @100%).
I did a PID tune and it did good getting up to temp. (Slight hiccup at 236) but it's not holding steady enough for me. (Plus or minus 1.5c)
Restarted the PID tune, gonna take a while. I'll post my PID values when it's done. (assuming it's successful, although I have a custom fan)

Not sure if there is a PID tuned for every printer, or if it's just a "Default" value. But here is the PID that was on my printer, before I changed anything.
M301 P16.13 I1.16 D56.23

**Comment by stahlfabrik** [comment]
Just as an side note: Are you using an E3D sock? It blocks air flow from the fan and also keeps heat inside. I love it and it makes temperatures mores stable and the printer more energy efficient

**Comment by workinghard** [comment]
@stahlfabrik: Purchase for E3D sock placed. Will be able to evaluate this weekend. Thanks for the hint

**Comment by stahlfabrik** [comment]
@workinghard I should have put a affiliate link;-) But I am not affiliated with them - just a fan of the product. Did you order the new one? There is an old one and a new one.

The new is NOT the "pro" one - this is the new one: https://e3d-online.com/v6-sock-3pack

**Comment by workinghard** [comment]
No idea which one is new or old. I can see a "Pro" version and regular. I bought the V6-SOCK-PRO-3PACK version.

**Comment by stahlfabrik** [comment]
Can you cancel? It is the old one IMHO

**Comment by workinghard** [comment]
Done. Got the "newer" ones.

**Comment by kwaad2** [comment]
https://preview.ibb.co/jd3fJy/PID.png
First heatup is 220c, with fan on.
Second heatup is 240c, with fan on.
The small "spike" on the 240c line, is me turning the cooling fan off.
Third heatup is 230c, with fan off.


I tuned my PID a little bit.
I turned the part cooling fan, and then ran
M303 C50 S240
(this took a while)

I, like you tend to print "hot" and I also print with my cooling fan on.

My end result was
M301 P20.29 I2.26 D45.48
Recv:  Kp: 20.29
Recv:  Ki: 2.26
Recv:  Kd: 45.48

I do however have a different cooling fan nozzle than you, so my numbers would not be optimal for you.

**Comment by workinghard** [comment]
Turning on the fan and do the PID calibration afterwards did the trick.
With regular PID calibration: Kp:15.73 Ki:1.14 Kd:54.00
After the Fan+PID calibration: Kp:17.73 Ki:1.34 Kd:58.47
<img width="598" alt="bildschirmfoto 2018-05-15 um 22 32 58" src="https://user-images.githubusercontent.com/872831/40098435-53f4a1ac-5890-11e8-8ac7-2ac82f9e70dd.png">
Started printing, with the second layer temp wasn't able to keep up. Canceled the print. Did the enhanced PID calibration. Started the same print again. Temp is stable now with the second layer. 
Please consider to add this result to FAQ or/and adjust the default Kp,Ki,Kd values for MK3.

**Comment by zafuquazar** [comment]
@workinghard what is “enhanced PID cal”?

**Comment by workinghard** [comment]
Like described above. Turn the fan on to 100% (or maybe something 50-100% will work as-well). Then run the PID calibration. During the PID calibration you can't change the fan speed, so you have to do that prior calibration. This way the calibration logic determines more aggressive K* values. The only disadvantage is slightly less stable temp. In my case right now it's +/- 1C during printing.

**Comment by zafuquazar** [comment]
Thanks, @workinghard!

**Comment by workinghard** [comment]
I'm closing this issue because it can be handled with proper PID calibration or E3D sock. Thanks for working out the solutions. Further discussions can be handled in [this forum](https://shop.prusa3d.com/forum/general-discussion-announcements-and-releases-f61/-howto-pid-calibration-your-way-t18479.html)
