### ISSUE TITLE
3.2.0 Final Firmware LINEAR ADVANCE BUG

### ISSUE THREAD

**Issue by MROJOD** [prusa3d/Prusa-Firmware#749]
i just updated the 3.2.0.   10 may  firmware, when i slice any gcode on any print setting that includes linear advance it purges normally, prints brim normally, but as soon as it starts printing the piece it self it starts clicking when retracting until it finally pushes the filament all the way back, if i slice again deleting the m900 k line from the gcode and i select any print setting without linear advance it prints normally, i run latest version of drivers and only use prusa slicer( latest version) i was asked by the support chat to try many things like turning off filament sensor or try sample prusa gcodes wich prints normally but the problem always comes when i use linear advance settings, if i go back to any previous firmware it all goes back to normal on the same gcodes,  i was offered to send the printer back but since i use it for work this is kind of a downside for me plus i really think its only a bug so why send it all the way back right ? any help on this ? many thanks in advance

**Comment by HFMan** [comment]
Very odd.  I don't have any issue with LA enabled.  Can you paste your exact start GCODE script?  And what slicer are you using?

**Comment by MROJOD** [comment]
i only use prusa slicer (latest version) and this is my exact gcode start script :

 M115 U3.1.0 ; tell printer latest fw version
M201 X9000 Y9000 Z500 E10000 ; sets maximum accelerations, mm/sec^2
M203 X500 Y500 Z12 E120 ; sets maximum feedrates, mm/sec
M204 S1500 T1500 ; sets acceleration (S) and retract acceleration (T)
M205 X10 Y10 Z0.2 E2.5 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M83  ; extruder relative mode
M104 S[first_layer_temperature] ; set extruder temp
M140 S[first_layer_bed_temperature] ; set bed temp
M190 S[first_layer_bed_temperature] ; wait for bed temp
M109 S[first_layer_temperature] ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0  F1000.0 ; intro line
G1 X100.0 E12.5  F1000.0 ; intro line
G92 E0.0


as i said the problem only shows when i choose 1.5mm or 2.0mm linear advance setting and m900 k30 on the filament gcode, as soon as i erase the m900 k30 from the filament gcode and choose 1.5mm or 2.0mm normal setting it prints normally and here its the exact start gcode of the same print gcode thats shows the problem on the new firmware 3.2.0 but it can be printed just fine on the previous 3.1.4 firmware, same gcode same SD card : 

; generated by Slic3r Prusa Edition 1.39.2+win64 on 2018-05-16 at 12:18:47

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.35mm
; first layer extrusion width = 0.42mm

M107
M115 U3.1.0 ; tell printer latest fw version
M201 X9000 Y9000 Z500 E10000 ; sets maximum accelerations, mm/sec^2
M203 X500 Y500 Z12 E120 ; sets maximum feedrates, mm/sec
M204 S1500 T1500 ; sets acceleration (S) and retract acceleration (T)
M205 X10 Y10 Z0.2 E2.5 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M83  ; extruder relative mode
M104 S208 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S208 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0  F1000.0 ; intro line
G1 X100.0 E12.5  F1000.0 ; intro line
G92 E0.0
M900 K3330; Filament gcode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
;BEFORE_LAYER_CHANGE
;0.2


G1 E-0.80000 F2100.00000
G1 Z0.600 F7200.000
;AFTER_LAYER_CHANGE
;0.2
G1 X60.108 Y62.961
G1 Z0.200
G1 E0.80000 F2100.00000
M204 S1000
G1 F1800
G1 X60.691 Y62.711 E0.01989
G1 X61.320 Y62.624 E0.01989
G1 X188.676 Y62.624 E3.99316
G1 X189.417 Y62.744 E0.02355
G1 X190.087 Y63.092 E0.02367
G1 X195.116 Y67.392 E0.20748
G1 X199.887 Y74.649 E0.27230
G1 X200.138 Y75.224 E0.01965
G1 X200.230 Y75.843 E0.01965
G1 X200.205 Y133.076 E1.79449
G1 X200.009 Y133.734 E0.02154
G1 X195.513 Y143.205 E0.32871
G1 X194.939 Y143.757 E0.02496
G1 X189.892 Y147.039 E0.18879
G1 X189.309 Y147.289 E0.01989
G1 X188.680 Y147.376 E0.01989
G1 X61.258 Y147.375 E3.99522
G1 X60.651 Y147.277 E0.01929
G1 X60.089 Y147.027 E0.01929
G1 X54.839 Y143.765 E0.19380
G1 X54.442 Y143.428 E0.01633
G1 X54.127 Y143.013 E0.01633
G1 X53.831 Y142.230 E0.02626
G1 X52.186 Y132.635 E0.30523
G1 X52.192 Y75.534 E1.79035
G1 X52.308 Y74.957 E0.01846
G1 X54.577 Y68.184 E0.22395
G1 X54.814 Y67.691 E0.01716
G1 X55.240 Y67.186 E0.02071
G1 X60.063 Y63.000 E0.20024
G1 F5760
G1 X60.691 Y62.711 E-0.23953
G1 X61.320 Y62.624 E-0.21966
G1 X62.188 Y62.624 E-0.30081
G1 E-0.04000 F2100.00000
G1 Z0.800 F7200.000
G1 X54.563 Y75.709
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F1800
G1 X54.563 Y86.423 E0.33592
G1 X55.317 Y86.423 E0.02365
G1 X55.317 Y75.879 E0.33060
G1 X56.071 Y75.879 E0.02365
G1 X56.071 Y86.423 E0.33060
G1 X56.825 Y86.423 E0.02365
G1 X56.825 Y68.958 E0.54761
G1 X57.579 Y68.958 E0.02365
G1 X57.579 Y86.423 E0.54761
G1 X58.333 Y86.423 E0.02365
G1 X58.333 Y68.958 E0.54761
G1 X59.087 Y68.958 E0.02365
G1 X59.087 Y86.423 E0.54761
G1 X59.842 Y86.423 E0.02365
G1 X59.842 Y68.958 E0.54761
G1 X60.596 Y68.958 E0.02365
G1 X60.596 Y86.593 E0.55293
G1 F5760

**Comment by Sebastianv650** [comment]
Well, that's not realy surprising, if you set:

> M900 K3330; Filament gcode

I guess you edited the start gcode and pressed "3" too often ;)

**Comment by MROJOD** [comment]
i have noticed that but in fact no i havent edited anything i just copy pasted it, thats the point it keeps adding that value to every gcode i slice it keeps adding odd values to the  m900 k *  values, i guess thats where the bug is...

**Comment by HFMan** [comment]
Why are you editing the gcode direct?  Put the K value in the start script.

**Comment by TheCodeSharman** [comment]
Sounds like the problem is in the per filament gcode rather than the start gcode. I'm guessing there is a "M900 K3330" command in the specific code for the filament. 

This defaults to something  like:
`M900 K{if printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{else}30{endif}; Filament gcode`

But is user editable (just like the start up gcode).

The code inserted depends on which filament is selected. @MROJOD check your per filament settings in Slic3r ?

**Comment by MROJOD** [comment]
@HFMan as i said twice before, i am not editing anything, i just copy pasted the gcode as it is, still thanks for your input.

**Comment by MROJOD** [comment]
@TheCodeSharman  nope, that wasnt the issue either, but its already solved thanks to the prusa support chat, afer a hard reset on the board its all good now, thanks for your time

**Comment by Panayiotis-git** [comment]
I'm happy that the hardware reset fixed your issue.

But, in the g-code file that you have posted, it is clearly written:
M900 K3330; Filament gcode
It is an extreme value. I have no idea how the firmware will handle it.

I guess that at the filament g-code field on Slic3r, you somehow edited the value to this:
`M900 K33{if printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{else}30{endif}; Filament gcode`

If you want the K value to be 33, you should enter the following g-code:
`M900 K33; Filament gcode`

**Comment by MROJOD** [comment]
@Panayiotis-git  thanks for taking the time, as i said i did not edited o make any changes to the firmware or the slicer, as i have other 2 mk2s printers with 3.1.4.0 firmware both using the same slicer same settings and the only printer with 3.2.0 firmware was presenting the issue, the only gcode that came out different from the sd card was the one in the 3.2.0 mk2.5 printer, i am still using same slicer same settings same gcode as before and all printer are working fine, thanks for your input
