### ISSUE TITLE
3.2.1 Filament sensor error during self-test

### ISSUE THREAD

**Issue by neilenns** [prusa3d/Prusa-Firmware#751]
I've updated my MK3 to 3.2.1 from 3.1.1 and now the self-test is failing with a filament sensor error and wiring error. This appears to be the same error [reported in this post by william.t14](https://shop.prusa3d.com/forum/hardware-firmware-and-software-help-f64/firmware-3-2-1-for-original-prusa-i3-mk3-t18474.html#p86105).

The filament sensor worked fine on the previous version of the firmware.

**Comment by neilenns** [comment]
The fix for this, at least as a workaround, was simple: I turned the printer off and then on again and self-test passed.

I didn't ever power cycle the printer after flashing the new firmware and starting the calibration wizard.

**Comment by neilenns** [comment]
Another report in the forums: https://shop.prusa3d.com/forum/hardware-firmware-and-software-help-f64/firmware-3-2-1-for-original-prusa-i3-mk3-t18474-s20.html#p86428

**Comment by stahlfabrik** [comment]
So the issue is resolved after power up? What is the issue then? Honest question:-)

**Comment by neilenns** [comment]
At least three people have reported hitting the problem in the forums, and then waste their time debugging trying to figure out why it doesn't work. Presumably an error after upgrading the firmware isn't designed behaviour...

**Comment by neilenns** [comment]
It can certainly be a decision to not fix this since there's a workaround that can be documented, but saying "what's the issue then" belittles the people who paid $800 for a printer because they expected it to be generally better quality than what else is out there, hit this, and then struggle.

**Comment by stahlfabrik** [comment]
Understand. Maybe it is unfixable. But maybe the communication routine could be improved. 

I always do a factory reset after an update so I always start clean. The MK3 with its ruff release in November somehow taught me that lesson

**Comment by neilenns** [comment]
Another report: https://shop.prusa3d.com/forum/hardware-firmware-and-software-help-f64/filament-sensor-wiring-error-t18636.html

**Comment by gadams999** [comment]
I have the same issue on a new build, albeit I did have the cable backwards. Heading to the menu shows N/A for the sensor. Power cycling hasn't helped. I've reached out to Prusa for guidance (and cost on a new sensor if I blew it up)....
