### ISSUE TITLE
MK3 3.2.1 Nozzle crash on temp calibration

### ISSUE THREAD

**Issue by trogdor88** [prusa3d/Prusa-Firmware#757]
After flashing 3.2.1 on my MK3 I performed a ALL DATA factory reset.  Went through wizard just fine with light paper dragging at front right corner. Went to perform temp calibration and first test is fine nozzle hit heat bed after homing on the start of the second test.  Test was successfully run on 3.2.0 and 3.1.4

**Comment by Zaf9670** [comment]
I know some people have said they needed to lower their PINDA probe on a recent update. And it could also be the temperature calibration on the PINDA causing the issue. May want to disable that and try again.

**Comment by trogdor88** [comment]
I did re-verify the PINDA height as one cable tie.  I can lower it, but the interesting thing is after the crash and subseqent calibration failed if I long press the control for a live z adjust it shows a positive value.  It looks like TEMP Cal is OFF What did you want me to disable I will try that before I move the PINDA.

Perhaps you mean for me to perform a manual calibration? https://github.com/prusa3d/Prusa-Firmware/wiki/Manual-temperature-calibration

Thank you

**Comment by Zaf9670** [comment]
I decided to put my PINDA probe at pinching the zip tie close due to my head crash issue. It's better to have the probe closer than further as others have discussed on here.

I was also just suggesting the temperature offsets could be right on their tipping points but I think the general consensus has been that the manual calibration should be performed for best performance.

What were you heated to when it crashed? PLA or something hotter?

**Comment by kroll999** [comment]
@trogdor88 same problem here. 
Confirm test was successfully on 3.2.0

**Comment by trogdor88** [comment]
Just to clarify I was not printing at the time.  I was only running the temperature calibration under the calibration sub menu.  I did have PLA loaded but as the nozzle was cold [25,26]C and clean.

**Comment by vaxxi** [comment]
Can confirm the problem on 3.2.1. Started temperature calibration (steel sheet removed), nozzle lowered until it was touching the heatbed, when moved for the next step it was dragging on the heated bed. Reset printer, Z coordinate was indicated as 0.15 even if the nozzle was touching the heatbed (with the steel sheet removed).

**Comment by klonk** [comment]
Same for me. 3.2.1 on mk3 Nozzle  just dig to the heated plate

**Comment by PavelSindler** [comment]
Dont you know if homing at the beginning of temp calibration happened with PINDa probe right above calibration point?

**Comment by klonk** [comment]
In my case yes.  

Before that i have some z adjustment issue. In one print -0.6 , in the folowing -0.12 ( via live adjust ) .
So I start temperature calibration.  Pinda cool down and then bite to plate.

**Comment by trogdor88** [comment]
It did.  In my case it is on the start of the second test. I have yet to move the PINDA as @Zaf9670 suggested so it is 100% repeatable for me let me know if you need a video or anything.

**Comment by PavelSindler** [comment]
I made PR with temp calibration fix and improvements for improved safety (MK3 Z crash detection, no XY movements near heatbed surface etc.): https://github.com/prusa3d/Prusa-Firmware/pull/788 .

**Comment by trogdor88** [comment]
Thank you!  Once I finish printing I'll build and give it a shot.

**Comment by chankinfun** [comment]
I also have this problem, but no problem on 3.2.0

**Comment by sidoh** [comment]
This also happened to me (picture attached).  It also didn't complete -- was stuck on 6/6 for about two hours before I gave up and reset.  I can try again on 3.2.0, but I'm a little fearful for my heated bed!

<img src="https://user-images.githubusercontent.com/589893/41515256-98ec19c0-7262-11e8-83a3-cb370a6750d3.jpg" width="400" />

**Comment by trogdor88** [comment]
All working with MK3 running 3.3.0-RC1.
