### ISSUE TITLE
3.2.1 - Enclosed ABS Print, Heatbed & Hotend set 0 after 3h while XYZ motion continues

### ISSUE THREAD

**Issue by TheZeroBeast** [prusa3d/Prusa-Firmware#758]
##FW: 3.2.1 MK3
**SD PRINTING** on **ALL FAILURES**
Enclosed ABS Print, Heatbed & Hotend set 0 after 3h while XYZ motion continues with serial communication advising **"cold extrusion prevention"**

Why did the heaters shutdown is the question.

Appears to have started happening since SafetyTimer implementation in FW even though MK2.5 on same FW & SafetyTimer imp. is running ABS enclosed fine.

Gcode attached bellow with screenshot of failure position and temp graph of failure.

A very similar situation occured prier to this print after an M600 change that had to waited 3h before I could get the next colour loaded in and kick it off again.
  - M600 had cooled hotend and kept bed hot as expected
  - When clicking hotend came to temp, resumed beeping until I unloaded/loading new filament and resume
  - Approximately ~30m later the heaters had been turned off for no apparent reason causing **"cold extrusion prevention"**
    - Perfect looking print with base Slic3r ABS presets despite more seamingly un-reneeded **crash detections**
    - Print continued on as if no issue encountered even though heaters were disabled

[RAPTORMixed.zip](https://github.com/prusa3d/Prusa-Firmware/files/2021248/RAPTORMixed.zip)

![mk3](https://user-images.githubusercontent.com/20939095/40290823-49e0147a-5cb0-11e8-9577-4c0d9eae6890.png)
![mk3](https://user-images.githubusercontent.com/20939095/40290879-b46d451a-5cb0-11e8-99c9-b1bcc9b17143.jpg)

**Comment by TheZeroBeast** [comment]
I think there is a trend with other reported issues perhaps.
#734
#720
#739
#754

**Comment by TheZeroBeast** [comment]
![jsi3 q6sr3cnr8wqa3ui6w](https://user-images.githubusercontent.com/20939095/40303557-913e9edc-5d36-11e8-906a-f53a55f9ca61.jpg)

**Comment by Zaf9670** [comment]
@TheZeroBeast Do you know what layer it froze up?

**Comment by TheZeroBeast** [comment]
Hi @Zaf9670, heaters turned off just past the 3h mark of the print at about 4mm in height which led the extruder to stop when hotend dropped bellow mintemp of 180-190C which ever the MK3 FW is using at present.

**Comment by TheZeroBeast** [comment]
As others have suggested this issue is happening when a crash is detected I ran a test PLA print and induced some crashes although it worked as expected without shutting off heaters.
This leads me to think it is time dependant.

**Comment by TheZeroBeast** [comment]
OK, the next piece of the puzzle, I sliced the same parts for my MK2.5 which is printing in the same enclosure and using MK2.5 3.2.1 firmware without issue, ~~currently 9h into the 18h print. (50%)~~ which has now successfully completed, all 18h of it.

This would suggest there is an issue with the differences between MK3 & MK2.5 features and their implementation as most of the code for both is the same.

### Running list of differences in 3.2.1 MK3 & MK2.5 Code
- **TMC2130**
      - Crash Detection
      - Sensor less homing
      - Different current settings

- ~~**POWER PANIC**~~
      - [Forum regarding POWER PANIC Stopping only heaters](https://shop.prusa3d.com/forum/hardware-firmware-and-software-help-f64/heaters-disabled-power-panic-sense-fault--t18422.html) Looks as though a hardware issue is appearing on EINSY or power sense board in **PSU**
To test this issue, I monitored **nAC_FAULT** by connecting my digital multimeter and ran the bed at 115C for 3h. **Voltage was stable at 5.1v due to 5.1v zener clamping it there.**
        _nAC_FAULT line dropping bellow AND gate high which is 70% of VCC would result in heaters not getting the PWM signal prior to Atmega processor registering power panic fault, i.e. loss of power._

- ~~**Ambiant temperature thermistor**~~
      - ~~MINTEMP~~ Looks as though this is working although on Lines **673** & **767** of temperature.cpp when checking if **AMBIENT** is within limit it is incorrectly checking if it is outside limits. "(current_temperature_ambient < MINTEMP_MINAMBIENT)" instead of "**(current_temperature_ambient > MINTEMP_MINAMBIENT)**"
      - ~~OVERTEMP~~  I can't locate code that enforces a MAX_AMBIENT, just MIN_TEMP @ 25C

- ~~**Cooling Fan Tacho monitoring TACH_1**~~
Extruder and Part cooling fans report above 4000rpm full on even when carriage is moved to extents of X & Z axis.

**Comment by Zaf9670** [comment]
So are you suggesting this issue is do to a false positive on the power panic? Or that you may have had a brownout/blackout that caused this to happen? Just following this in case it is something that could happen to a long running print of my own.

Side note: You can try resuming the print from where it left off next time. Roughly find where your print ended and tell the slicer to begin at that height and continue the print. The poor man's fix to a filament runout midprint.

**Comment by TheZeroBeast** [comment]
Hi @Zaf9670, as per the forum post which is linked above there could have been an issue with the nAC_FAULT input and on @nicholas.g9 board the voltage drift suggests this. Voltage dropping to a point where half the hardware triggers results in heaters off and print continues. Error state indeed and not normal operation.

Once heaters are off there is at least 15m of printing plastic that increasingly doesn't adhear properly to previous layers so recovery of most prints would be a waste compaired to prints that have just stopped e.g. power loss on MK2.

**Comment by TheZeroBeast** [comment]
I also just identified issues with the pause and resume functions M25 & M24.
Print pauses and kills heaters and disengages steppers.
Resuming print states on LCD ".....heating" although never sets target values. When set manually through menu and at temp again printer homes Z axis before promptly running head long into what was already printed. Luckily no damage from what I can see but not happy.

Same 3.2.1 FW on MK2.5

In my mind pause print would consist of pause, cool hotend, saving X,Y&Z values, move Y Bed forward, hotend to the side. Safety Timer disabled so print doesn't detatch with cooled bed.

Resume would consist of heating, homing of X,Y and resuming at saved X,Y&Z values.

**Comment by TheZeroBeast** [comment]
I also just identified issues with the pause and resume functions M25 & M24.
Print pauses and kills heaters and disengages steppers.
Resuming print states on LCD ".....heating" although never sets target values. When set manually through menu and at temp again printer homes Z axis before promptly running head long into what was already printed. Luckily no damage from what I can see but not happy.

Same 3.2.1 FW on MK2.5

In my mind pause print would consist of pause, cool hotend, saving X,Y&Z values, move Y Bed forward, hotend to the side. Safety Timer disabled so print doesn't detatch with cooled bed.

Resume would consist of heating, homing of X,Y and resuming at saved X,Y&Z values.

**Comment by jdn-za** [comment]
I have managed to do a 41 hour print with crash detection off so I expect the issue is there?

In my cash the false crash was always on y

**Comment by PavelSindler** [comment]
Yes it was caused by crash detection. Explanation is here: https://github.com/prusa3d/Prusa-Firmware/issues/754

**Comment by TheZeroBeast** [comment]
Hi @PavelSindler,
thank you for getting to the bottom of this issue. I look forward to testing it.
Rob
