### ISSUE TITLE
Farm mode

### ISSUE THREAD

**Issue by wschadow** [prusa3d/Prusa-Firmware#76]
Hi, today I downloaded and compiled the latest version 3.10.8, and got the same issue that the self-test fails. Besides some "farm mode" was turned "additional F -/-" showed up in the display, and after the printeI was asked if print was ok. I could only turn this off by recompiling by setting farm_mode to false in Marlin_main.cpp.

**Comment by PavelSindler** [comment]
Hello, thank you for reporting this issue. It was fixed in https://github.com/prusa3d/Prusa-Firmware/commit/70b6e13de4b147a73d52f557d262d7960b942639. It is possible to turn off farm mode in settings menu -> disable farm mode. Please keep in mind that last stable firmware version is 3.0.10.
