### ISSUE TITLE
Menu live Z option appearing and disappearing during print

### ISSUE THREAD

**Issue by nicholas1230-zz** [prusa3d/Prusa-Firmware#768]
While printing (At least 10% complete) if the menu is active and you scroll up and down past "tune". The live Z adjustment option appears and then disappears. Very glitchy and random.

**Comment by cjo20** [comment]
https://github.com/prusa3d/Prusa-Firmware/blob/MK3/Firmware/ultralcd.cpp#L5715 
`#define Z_HEIGHT_HIDE_LIVE_ADJUST_MENU 2.0f`
It looks like it's meant to disappear above 2mm. It could be z-hopping around 2mm takes the z-axis over and under the threashold repeatedly.

**Comment by Zaf9670** [comment]
I think it would be hard for it to be set near 2.0 without the PINDA being nearly level with the nozzle. What is your current Z setting from your calibration/wizard @nicholas1230?

**Comment by cjo20** [comment]
@Zaf9670 The option disappears when the z axis current position is over 2mm, not the live Z offset.
