### ISSUE TITLE
Tune temperature while printing not working since 3.2.1 (MK3)

### ISSUE THREAD

**Issue by chhu** [prusa3d/Prusa-Firmware#770]
Just as announced. I often use while printing Tune->Nozzle Temp. New nozzle temp is on the display (set temp) but the measured temp stays around the temp from gcode... :( Bed temp and other tuning still works.

Best,
Ch

Update: sometimes it works. Pausing helps... 
Update2: further investing this it seems to not react to new temps for unneccessary long delays, like 10 layers until it starts adjusting, most of the time it works straight away.

**Comment by easycheese** [comment]
Same here.  I'm doing it right now where my filament starts at 235 and goes to 230. I tried manually changing it to 240 and nothing happened. When I upped it to 250, the temp made it to 240 before stopping.
