### ISSUE TITLE
PowerPanic does not work on 3.2.1

### ISSUE THREAD

**Issue by jonnieZG** [prusa3d/Prusa-Firmware#772]
PowerPanic feature does not work on 3.2.1:

After resuming from a PowerPanic event, the bed and the nozzle heat up, head goes to last position and stays there, nothing happens. 

I would like to hear from someone who tested it successfully with release 3.2.1, if any.

Cheers,
Jonnie

**Comment by PavelSindler** [comment]
Were you printing from SD card?

**Comment by PavelSindler** [comment]
Can you provide gcode file?

**Comment by tbedore** [comment]
Hi, I just tested this on a gcode I was running on my machine, printing from SD card everything worked fine, print resumed perfectly.

**Comment by tbedore** [comment]
Though after the test was ran, the timer for how far into the print had reset, and there is no text showing where it would usually say printing this object

**Comment by Prusa-Support** [comment]
Hello! If you are still having this issue with the latest firmware, please contact us at info@prusa3d.com.

Marina Curzi
Prusa Research
