### ISSUE TITLE
MK3 3.2 Print Fan Error does not reset bed temperature to 0

### ISSUE THREAD

**Issue by rainersc** [prusa3d/Prusa-Firmware#774]
I currently have a problem with my print fan. i had 2 instances of print fan error (sorted the replacment via chat already)
what i saw was that even though the hotend temperature was reset to 0 , the bed temperature stayed on 80.
![image](https://user-images.githubusercontent.com/5039493/40619684-4c8111f2-6296-11e8-892e-ffc16ae9717c.png)

i assume it should be turned off as well as there is now possibility to resume the print after that error.

**Comment by PavelSindler** [comment]
There is chance to resume print in some cases. You can have some obstacle which blocks your fan and after removing it you can continue printing. That is why fan error behaves as pause print. You can decide if you want to stop print or try to resume.

**Comment by rainersc** [comment]
it did not offer me any chancce to resume.. ( which would have been nice when it stopped at 90% of a 12h print yesterday).. is there a timeout?
btw. above picture was taken in the morning. the problem occured approx. 10h earlier and the printer was happily heating the room through the night.
so unless there is a possibility to resume, it should be turned off.... at least in case there is a timeout or something

**Comment by PavelSindler** [comment]
You can resume it from main menu (the same way as paused print). I understand that this is not user friendly. We will improve that.
Turning off heatbed would cause that you lost contact between steel sheet and printed object and it is not possible to resume then.
