### ISSUE TITLE
3.2.1 Wizard Calibration failure on MK3

### ISSUE THREAD

**Issue by Lymen78** [prusa3d/Prusa-Firmware#776]
This is more of an FYI. Prior to 3.2.1 my MK3 was running 3.1.3 just fine. I updated the firmware and when I ran the wizard, it fails on the self test. It said:

> -1st screen-
> Selftest error !
> Please check : 
> Axis length
> Axis                               X
> 
> -2nd screen-
> Selftest failed
> -------------------------------
> 
> -3rd screen-
> Please check our 
> handbook and fix the 
> problem. Then resume 
> the Wizad by     (2 down arrows)
> 
> -4th screen-
> rebooting the 
> printer.
> 
>                            (check mark)

The 1st time it failed showed some hieroglyphs.
Restarted the printer. 
The 2nd time it went back to the normal home screen. (Failed in the same spot)
Restarted the printer.
The 3rd time the Wizard completed.

I am printing something now and if there is any issue I will report back.

**Comment by BrendonW** [comment]
I had a similar failure on the Z-axis. When I figured it out, it was my stupidity. I'd left the filament sensor connector disconnected -- sensor is not working and I had a second cable connected to test -- the connector was hitting the cross beam, limiting Z travel.

So make sure you don't have anything messing with X-travel. The firmware counts the steps and expects the length to be correct.

**Comment by Lymen78** [comment]
There wasn't anything messing with it. I was able to manually move it back and forth. The only different I did between 2 and 3 was change the Z axis to be closer to the bed. It was near the top from a previous print.

**Comment by pieroway** [comment]
I was having the x-axis length failure.  Tried adjusting pretty much everything hardware wise. 
In the end, what worked for me was a factory reset (https://help.prusa3d.com/article/SYvbQ66IXF-factory-reset) that must've cleared out some bad in memory settings.
All good after that.
