### ISSUE TITLE
3.2.1 Inconsistent mesh bed leveling

### ISSUE THREAD

**Issue by martinowren** [prusa3d/Prusa-Firmware#778]
Been having issues with inconsistent mesh bed leveling, in that sense I have to re-adjust the live adjust Z for every print, even with the same G-Code to get the same first layer. 

MK3
FW: 3.2.1
Crash detection on.
Filament sensor on.
Inside an enclosure.

**Comment by stahlfabrik** [comment]
Did you temperature calibrate your Pinda? That is MOST likely your issue.

As a workaround - if you do not want to calibrate - make SURE to start the print always with the same PINDA temperature of 35C - NOT warmer, not colder.

You do that by starting a print with PINDA on ambient temperature. Modify your start gcode to move the PINDA in a heating position. Then use the GCODE "M860 S35" to wait until the Pinda has reached 35C. Then home, then mesh bed leveling and go.

**Comment by stahlfabrik** [comment]
https://github.com/prusa3d/Prusa-Firmware/wiki/Manual-temperature-calibration

**Comment by stahlfabrik** [comment]
If it all worked great for you with an older firmware, you could recreate that state by loading the old temperate calibration offsets into EEPROM by "M861 !" and then enable temp cal in the settings in the menu

**Comment by martinowren** [comment]
Automatic PINDA calibration should be something I choose from the calibration menu on the printer itself. I remember this was a problem with the MK2, but the MK3 had the new PINDa to compensate for temperature changes.  Is there not a simpler solution?

**Comment by stahlfabrik** [comment]
The automatic calibration is not working out good for some users/printers like me/mine. There is no easy solution I am aware of. But the options are not "hard" really. The manual print based calibration is quite easy once you understood it and takes about 2 hours.

**Comment by martinowren** [comment]
The temperature calibration takes approximately 5+ Hours for 4/6 stages. Had to cancel it because it took too long. The manual Pinda calibration, if I correct it for PLA, wouldn't it be all screwed if I then changed to ABS with different live adjust Z?

**Comment by imrichh** [comment]
The automatic temp calibration took <30mins for me and improved the first layer. Although, it is still far from perfect. 
MK3
Firmware 3.5.0-1749
crash detection, filament sensor ON
No enclosure
