### ISSUE TITLE
File incomplete warning if filename contains an umlaut

### ISSUE THREAD

**Issue by mariusoe** [prusa3d/Prusa-Firmware#796]
Hi,

the latest firmware (also the once before) show the "file incomplete" message (when printing from SD card) if the G-code's filename contains an umlaut/mutated vowel (like: ä, ö, ü) even the G-code file is valid. Renaming or removing all of these characters from the file's name solves the "problem".

**Comment by bubnikv** [comment]
by the way, the slic3r pe 1.40.0 renames umlauts in file names to 7bit
ascii when exporting a g code.

**Comment by NielsPlougman** [comment]
Also problem with Danisk/ Swidish / Norigan æøå

**Comment by mumboz** [comment]
Same problem as in #2130 it sounds like.

**Comment by JakobSuppan** [comment]
Having the same problem, my printer even managed to crash completely when I tried to print this file

**Comment by mumboz** [comment]
Still an issue on my MK3S with the latest firmware 3.13.0-6873.

Renaming any file to include e.g. `ü` seems to reproduce it easily.
