### ISSUE TITLE
Link to Driver 2.1.6 not working

### ISSUE THREAD

**Issue by Mr-Mik** [prusa3d/Prusa-Firmware#797]
The orange "Download for Linux' link on https://www.prusa3d.com/drivers/ does not work.

It just loops back to the same page, using Firefox, Brave and Chrome browsers.

**Comment by Prusa-Support** [comment]
Hello! I am absolutely sorry this hasn't been replied to at the time of reporting. Closing the thread, all solved on the Drivers page. 

Alessandro Pantaleo
Prusa Research
