### ISSUE TITLE
MK2.5 Temperature Calibration never finishes step 6/6

### ISSUE THREAD

**Issue by desaster** [prusa3d/Prusa-Firmware#798]
On my MK2.5, running firmware version 3.2.1, the temperature calibration never finishes step 6/6.

Looking at the temperatures in the debug menu, the PINDA temperature manages to reach around ~56°C, while the calibration wants it to reach 60. At step 6/6, the hotend target temperature is set to 50°C, and the bed temperature at 110°C.

In my case, the problem seems to be that the hotend cooling fan is cooling the PINDA probe just enough to keep it from reaching 60. By forcibly stopping the fan, the temperature calibration soon reaches the end.

Some possible solutions/improvements:

* Keep the hotend target temperature slightly below 50°C to keep the hotend fan from turning on
* Disable the hotend fan by some other means in the code
* Automatically cancel the temperature calibration if it doesn't reach the end after a reasonable time.
* Display the PINDA temperature during the calibration so the user has a better idea of what is going on

**Comment by PavelSindler** [comment]
Thank you for your feedback.

**Comment by geeksville** [comment]
My new MK3 running 3.3.1 has a similar issue of not getting past step 5/6.  Even if I cover the hotend fan (to keep its turning on from cooling the penda).  So I can't use this feature for now.

**Comment by cara** [comment]
Same problem here with MK2.5 and 3.5.1. Still hanging at 6/6

**Comment by franzbischoff** [comment]
3.7.0 stuck in 1/6

**Comment by CCMCAGP** [comment]
I am also stuck at 1/6 with a stock MK3S (no modification whatsoever). I have been stuck there for 30 minutes already. Firmware is also 3.7.0...

**Comment by franzbischoff** [comment]
Firmware 3.7.1 (the latest), Model Mk2.5S

I see in the code that during the first step (1/6):
- My room temperature is 27ºC
- start_temp is set to 35ºC
- the bed temperature is set to (70 + (start_temp - 30)) ==> 75ºC
- while() waits for PINDA temperature to reach 35ºC

But:
My PINDA temperature never gets more than 13ºC. Nozzle temperature reached a maximum of 43ºC.

Is this ok? The 35ºC limit is really for PINDA or should be to Nozzle? Is my PINDA broken?

**Comment by leptun** [comment]
13C looks like broken/disconnected thermistor wire of pinda. You should contact support and get it replaced

**Comment by franzbischoff** [comment]
Found my problem. My v-cable came wrong

![image](https://user-images.githubusercontent.com/984592/57719344-72c1cc80-7677-11e9-9f44-6978ee60401b.png)

![image](https://user-images.githubusercontent.com/984592/57719373-84a36f80-7677-11e9-8c62-ecd0e0fef56c.png)

**Comment by mrmoo06** [comment]
And did swapping the wire over solve this issue?

**Comment by franzbischoff** [comment]
Totally

**Comment by mrmoo06** [comment]
OK, thanks.  Just checked mine and it is correct but it still just sits at 1/6 with the bed at 75C.....
Who knows, just another thing that doesnt work properly with this thing ##shrug
