### ISSUE TITLE
MK2 Skew Correction casues X and Y axes to twitch

### ISSUE THREAD

**Issue by c-stewart** [prusa3d/Prusa-Firmware#802]
This issue affects MK2/S on latest 3.1.0 firmware.
After running XYZ calibration my skew was 0.05 degrees. meaning that there should be no skew corrections applied to the movement of the X and Y axes. After printing a single wall cube I found vertical lines on all sides of the cube that didn't change position when I changed the feed rate of the print.

![img_20180529_185356](https://user-images.githubusercontent.com/10202389/40890208-83057d5e-6740-11e8-9b42-3398fcef22c8.jpg)
![inkedimg_20180529_185438_li](https://user-images.githubusercontent.com/10202389/40890209-8750fb0e-6740-11e8-83de-dd7ba1414164.jpg)

When I put my finger on the gear pulley on either the X or Y axis while it's printing, I can feel the stepper 'twitch' or 'tick' at the same frequency of the lines. If I then clear the XYZ calibration info, then re-run just the Z calibation and print the same gcode, the lines are gone and the steppers don't twitch anymore. It would seem that skew correction is making the steppers thitch like this even if it is supposed to be off and not correcting anything.

Here is a video as it is tricky to photograph 2 cubes beside each other. On the left is the cube with XYZ calibration active at 0.05 degree skew, same as in the pictures above. Notice the 6 vertical lines. On the right is the same gcode with XYZ calibration cleared and just Z calibration run, and the lines are gone.

https://photos.app.goo.gl/5KwPmnvItw1jjypG2
(the change in surface finish / ringing lines on both cubes is from me changing the feed rate of the print at different intervals.)

**Comment by gregsaun** [comment]
As you said what is really weird is that, according to Prusa, under 0.12° there is no adjustment. So we should not see this clicking!

Same issue here : 
https://shop.prusa3d.com/forum/others-archive--f82/clicking-from-x-y-axis-stepper-motors-when-idle-du-t2863.html

**Comment by c-stewart** [comment]
Thanks Greg, forgot to post that link. That's where the issue/fix was originally found.

**Comment by clearbucketLabs** [comment]
i've had this twitch/tick on non-prusa machine with repetier that i remember.  no ABL, no skew... maybe even with marlin but i don't remember.    Y is more obvious since its louder.
