### ISSUE TITLE
Safety Timer On Filament Runout

### ISSUE THREAD

**Issue by tbedore** [prusa3d/Prusa-Firmware#803]
Either the safety timer in the 3.2.1 firmware should be disabled for filament run-out.  Or you have to have the bed re-heat after filament run-out.  Though really it should just be disabled completely.

**Comment by PavelSindler** [comment]
Yes, it has been fixed already in PR https://github.com/prusa3d/Prusa-Firmware/pull/760 and it will be in next release.
