### ISSUE TITLE
ultralcd.cpp errors - redefinition

### ISSUE THREAD

**Issue by imaluschi** [prusa3d/Prusa-Firmware#81]
Downloaded the Firmware today - need to build one for a geared extruder.
It seems there is a typo or copy/paste error (however you want to call it).

Line 111 equals to line 116, 112 equals to 117, 114 equals to 118.

I'm not a programmer, but at least i managed to solve this problem by commenting out the doubled lines (116 to 118).
;-)

![Arduino IDE Error](https://cloud.githubusercontent.com/assets/15073635/25357345/bc1c3c46-293d-11e7-88ca-470298542d2f.jpg)

**Comment by PavelSindler** [comment]
This has been fixed in https://github.com/prusa3d/Prusa-Firmware/commit/7ec45271c2b07c38f84e676b4572a9efa3233669.
