### ISSUE TITLE
erroneous movements when stopping a print

### ISSUE THREAD

**Issue by stahlfabrik** [prusa3d/Prusa-Firmware#823]
When I stop a print via menu OFTEN the MK3 keeps printing a little, but in erroneous directions - as if the sign of the "movement vector" gets flipped. It does not happen every time. 
![img_1612](https://user-images.githubusercontent.com/4614972/41191017-0fb679cc-6be9-11e8-8e21-14ef17a9e65a.JPG)

**Comment by alientek** [comment]
Same here +1

**Comment by PavelSindler** [comment]
I made pull request which should fix this issue: https://github.com/prusa3d/Prusa-Firmware/pull/860. This erroneous movements could occur also during crash detection before rehoming and during filament detection. It needs more investigation to be sure that all scenarios are covered. We will test it tomorrow. Thank you for your feedback.

**Comment by stahlfabrik** [comment]
@PavelSindler the PR went into the firmware? We might close this issue then:-)
