### ISSUE TITLE
MK2.5 M601 Gcode command not working?

### ISSUE THREAD

**Issue by CoolNamesAllTaken** [prusa3d/Prusa-Firmware#825]
I used to be able to use the M601 gcode command from Octoprint to initiate a long pause (raise hotend, turn off extruder heater, bring bed forward) and the M602 command to resume the print.  These commands have ceased to function properly on the MK2.5.  Are they still implemented?

**Comment by PavelSindler** [comment]
Yes, it should still work but these commands are currently for SD card printing only. It works if you print file stored on printer SD and uses Octoprint for monitoring and controlling the printer.

**Comment by CoolNamesAllTaken** [comment]
Are there any plans to reimplement this functionality for gcode streaming from Octoprint?  It worked in the past and was very convenient.

In the meantime, if you have any advice on how to backup/restore extruder temp and extruder position it would be greatly appreciated!  I'd like to cobble together a gcode script approximation of M601 and M602.

**Comment by CoolNamesAllTaken** [comment]
Are M601 and M602 enabled for gcode streaming again?  I still haven't managed to build pause gcode script that works for all extruder temperatures, since it requires finding a temperature to restore to and that depends on the filament that's being printed.
