### ISSUE TITLE
MK3 - Display confused after resume printing over USB

### ISSUE THREAD

**Issue by njcrawford** [prusa3d/Prusa-Firmware#843]
Steps to reproduce:

1. Make sure crash detection is enabled
2. Start a print over USB (from OctoPrint, in my case)
3. Trigger crash detection
4. Wait for printer to re-home X and Y, and resume printing

Expected result:

Printer would resume printing from the point a crash was detected, and display would return to the same state, showing updated text from M117 commands.

Actual result:

Printer resumes correctly but display is confused. Temperatures and Z height continue to update as expected but "-->USB" is replaced with "SD 0%" and the bottom line is blank. M117 commands seem to be ignored.

Additional information:

- Printer seems to remain in this state until it is reset or power is cycled
- Changing filament seems to trigger the same problem
- Filament runout seems to trigger the problem as well

Image of confused display
![img_20180614_235851](https://user-images.githubusercontent.com/4052721/41449977-5f12adb8-7032-11e8-8196-f29f3ee22c23.jpg)

**Comment by PavelSindler** [comment]
Thank you for your feedback. We are currently working on crash detection and filament detection fix for printing over USB. It will be fixed in next release.

**Comment by njcrawford** [comment]
Thank you for taking a look at it. If you need any more information or testing, I'm happy to help.

**Comment by PavelSindler** [comment]
Thank you. Actually I have one question. How do you use M117 commands? What are you using it for? Are they in your gcode file or did you set Octoprint to send some information using M117 commands?

**Comment by njcrawford** [comment]
I'm using an OctoPrint plugin called Detailed Progress (https://plugins.octoprint.org/plugins/detailedprogress/) to show percent complete and estimated time remaining. It sends M117 about every 10 seconds. I can send you the config I'm using if that's helpful, I had to modify the default format strings to get it to work.

**Comment by PavelSindler** [comment]
I have just tested it with Octoprint with the plugin. It works well. You issue was fixed in pull request https://github.com/prusa3d/Prusa-Firmware/pull/810 .

**Comment by njcrawford** [comment]
Wow, that was fast! Fixed 10 days before I reported it :-) Thanks for looking into this, I'll be sure to test it when the next alpha/beta is released.

**Comment by njcrawford** [comment]
Just tested with 3.3.0-RC1, it does indeed work well. Thanks again!
