### ISSUE TITLE
MK3 Addition Z height during paused prints

### ISSUE THREAD

**Issue by OurHeroXero** [prusa3d/Prusa-Firmware#853]
It's not a common occurrence, but every now and again when I pause a print it raises the extruder an addition 20mm. (40mm total) Even if I resume the print the extruder is only lowered 20mm and begins printing in air.

(I'm pausing prints to load a different filament to add more colour to my prints. Pausing a print is always a gamble whether it'll raise 20mm or 40mm.)

**Comment by 3d-gussner** [comment]
@OurHeroXero You probably should use the M600 filament change gcode by using PrusaContol to switch filaments. It is more accurate than a pause and moves the hotend to a defined place where it is easy to change it and guides you through the process.
And if you manually change the position why should the printer keep track of it? Why don't you undo the your manually adjustments?
I can imagine that somebody wants to print a base/case for something,  pause it, place that external part inside and manually adjust the height to that part and continue printing.

**Comment by Panayiotis-git** [comment]
I think this relates to the https://github.com/prusa3d/Prusa-Firmware/issues/804.
The behavior described there, happens to me only when during the pause command the extruder rises in two steps: 20mm + 20mm = 40mm.
If it rises only 20mm, the resume works fine.

**Comment by Zingabopp** [comment]
It would be nice if the firmware saved the position when paused so that if you have to move the extruder for whatever reason (like to clean buildup on or around the nozzle) it would return to the correct position when it resumes.

**Comment by OurHeroXero** [comment]
Exactly like what Panayiotis-git has described. It raises in two parts. The first 20mm happens after the pause as per usual. The extruder moves off to the side and then it raises a second 20mm.

I haven't edited a lot of gcode on my own, however I will look into incorporating the M600 Thank you for the suggestion ^.^
