### ISSUE TITLE
feature request: multiple z-adjust slots

### ISSUE THREAD

**Issue by kortschak** [prusa3d/Prusa-Firmware#854]
Given that the MK3 can have more than one print surface and that different print surfaces may have different z-adjusts, it would be nice to have more than one slot to store the z-adjust (at least two - one for smooth PEI and one for powder coat). With this feature changing print sheets would then involve just selecting the z-adjust from a settings menu, rather than having to do a live adjust at the start of the print.

**Comment by OutlawAndy** [comment]
Bump!

Anything happening here?  Is this feature being considered?

**Comment by m-cas** [comment]
I guess that this would probably need to be managed in a more comprehensive way as the z-value will change for each of the combinations between bed, filament and layer height.
Would be nice to be able to store such a matrix (that I hold in excel and set manually when changing any of the above factors).
Something for slic3r? Add a tab with z-adjust values and send it to the printer via GCODE?

**Comment by kortschak** [comment]
Still wanted

**Comment by 3d-gussner** [comment]
@kortschak There are multiple sheets in Settings -> HW Setup -> Sheets with the values. Also the gcode `M850` allows you to read and set the sheet name `M850 - Set sheet data S[id] Z[offset] L[label] B[bed_temp] P[PINDA_TEMP]`

Example to read first sheet: `M850 S0`
Result on my printer: `Sheet 0 Z-0.8000 R-320 LSmooth1 B0 P39`

**Comment by 3d-gussner** [comment]
Please consider to close this issue.
