### ISSUE TITLE
Use silent-mode only during XYZ calibration

### ISSUE THREAD

**Issue by ChrisP-Git** [prusa3d/Prusa-Firmware#86]
If the printer have issue finding the calibration points during XYZ calibration, and that stepper current control is set to "power mode", the damage can be heavy on the bed if the nozzle goes deep in the bed (even with a paper sheet).

To limit damages in such an event, it would be nice to switch to "silent mode" just for the XYZ calibration, or event with special lower current control.

Does that make sense ?

**Comment by PavelSindler** [comment]
Hello @ChrisP-Git ,
yes you are right that heatbed surface can be damaged during xyz calibration. In manual there is written, that user should place piece of paper on heatbed to check if the nozzle isn't too close to heatbed during first calibration phase (searching for first points). So the paper isn't there for heatbed protection actually. The user should be present and turn off/restart printer if the nozzle grabs the paper.
Lowering currents during xyz cal. may help with heatbed protection, but also increases danger that there will be some shift during xyz calibration.
