### ISSUE TITLE
Where is FirmwareUpdater now?

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [prusa3d/Prusa-Firmware#866]
I cannot find firmware updater for MK2 neither in FIRMWARE 3.1.0 nor in DRIVERS & APPS 2.1.7

![image](https://user-images.githubusercontent.com/937933/41815879-36232616-7745-11e8-8176-7debdadad769.png)

Where can I find it?

**Comment by Orillian** [comment]
Check out point 10 on the 2.1.7 Drivers list!

*Firmware Updater Integrated into Sic3r PE

**Comment by zpdDG4gta8XKpMCd** [comment]
nice, although its not what the instruction says:

https://help.prusa3d.com/l/en/article/r5ByKgVm69-firmware-upgrade-and-flashing

![image](https://user-images.githubusercontent.com/937933/41816281-c3d685da-774e-11e8-97f9-39c2fce345fb.png)


so i've been looking for the FirmwareUpdater app

**Comment by Orillian** [comment]
I think they need to update the site to reflect the changes in a couple places.
It's definitely confusing when the help docs don't match up!

**Comment by bubnikv** [comment]
Thanks for heads up, I have notified the content guys.
