### ISSUE TITLE
MK3 3.3.0-RC1 Extreme Z movements during temperature calibration

### ISSUE THREAD

**Issue by trogdor88** [prusa3d/Prusa-Firmware#883]
When attempting temperature calibration right after calibrate z (hot nozzle). Calibration correctly waits but with extreme speed jumps to a high Z from home to wait for cool down.  When cool down completes it just as rapidly moves to home to resume calibration.  The noise emitted from the printer makes me thing this jump is too much for the trapezoidal nuts.

**Comment by 3d-gussner** [comment]
@trogdor88 I think that has been fixed, can you please close this issue?
[stale][fixed]

**Comment by JPtestERAU** [comment]
Closed. It’s fixed.

**Comment by trogdor88** [comment]
Thank you!
