### ISSUE TITLE
3.3.0 RC1 Nozzle crashed at „blob-cleaning-point“

### ISSUE THREAD

**Issue by RacingHell** [prusa3d/Prusa-Firmware#887]
After several tries to start a print correctly z-axis moved all the way down without crash detection on full torque at the beginning of bed leveling. Bed was bend like 10mm down, needed to reset the printer to move this collision free. What in detail has been done befor this misbehaviour I can‘t tell anymore. PINDA detected.

**Comment by RacingHell** [comment]
![55a9f225-7a92-442d-badb-54b8caa860fb](https://user-images.githubusercontent.com/37401401/42183798-7274aaae-7e43-11e8-8066-fbf7124f2010.jpeg)

In the middle the negative surface of the nozzle at collision position.

**Comment by andredigenova** [comment]
I’ve had this happen to me on 3.2.1 — not sure what the cause is and I haven’t reproduced it since. It drove the nozzle straight in to the exact same spot and left the same deep mark.

**Comment by jayPhantomic** [comment]
I had this happen in 3.2.1 as well. Just upgraded to 3.3.0, will let you all know if it does it again.

**Comment by andredigenova** [comment]
Just had this happen again in 3.3.1. I moved Z really high up using the LCD interface and then initiated bed levelling. When going to probe the first point it drove the nozzle straight in to the bed hard.

**Comment by O-Alex-O** [comment]
Happened to me today, with firmware 3.4.0
I started printing from sd-card, then I pressed the lcd-button to move the z-axis upwards
After preheating, he collides with the bed at the same point instead of performing the calibration.
