### ISSUE TITLE
MK3 3.3.0 Resuming a paused print -> way too fast z movements

### ISSUE THREAD

**Issue by stahlfabrik** [prusa3d/Prusa-Firmware#892]
I paused a print using the menu. The printer went nice and slowly into pause position. When I resumed the z movement was WAY too fast - I really had the feeling the Z axis (nuts) get damaged.

I attach the gcode that I have printed. 

[Uhrlasche.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/2160709/Uhrlasche.gcode.zip)

if you look into the gcode: I paused the print shortly before the bridging

**Comment by stahlfabrik** [comment]
I sliced it again - this time with stock profile - now the z movement was normal fast. There must be something fishy with my custom profile

**Comment by gdombiak** [comment]
Found another issue that seems to produce similar behavior: https://github.com/prusa3d/Prusa-Firmware/issues/883.

**Comment by stahlfabrik** [comment]
Yeah sound just like that

**Comment by stahlfabrik** [comment]
@PavelSindler should that bug be fixed by now? I have not paused a print for a while:-) And it was not 100% happening all the time to begin with
