### ISSUE TITLE
MK2.5 Firmware 3.3.0 - Failing Calibration on 3rd Point

### ISSUE THREAD

**Issue by pshankland** [prusa3d/Prusa-Firmware#895]
As the description; newly built MK2.5 from MK2S and updated immediately to 3.3.0 as instructed. Each time the wizard tried to find the 3rd calibration point it failed. Downgraded to 3.2.1, ran the wizard and all passed.

**Comment by aderusha** [comment]
I'm seeing similar behavior.  I have a MK2 > MK2s > MK2.5, been running without problem on 3.2.1, upgraded firmware to 3.3.0 and calibration fails on the second calibration point.  Revert to 3.2.1 and everything works like normal again and prints complete without problems.

**Comment by micblazek** [comment]
I had the same problem. It helped me when I came up right side my heatbed with the pads. New XYZ calibration seems to have a limited height range.

**Comment by pshankland** [comment]
Just tested with 3.3.1 and the issue still remains. It appears as though MK2.5's can only calibrate with 3.2.1

**Comment by clearbucketLabs** [comment]
Same here, after 5-6 tries the same thing.  since i was adjusting a few things on my X i figured i messed something up, but nope.   only downgrading helped.

**Comment by hckygoalie29** [comment]
After flashing firmware update 3.3.1 on to my MK2.5 I too am having failed bed calibrations at the third point. I am currently flashing back to older software so that I can calibrate my machine.

**Comment by morphogenetic2** [comment]
Same here, using 3.3.1 in MK3.  Nozzle pushes on the heatbed on the first point, and then crashes on the third point.  I had to downgrade to 3.1.2 to calibrate and then get back to 3.3.1
