### ISSUE TITLE
MK3 Firmware 3.3.0 - Failing Calibration and Calibration Z

### ISSUE THREAD

**Issue by Crunch69** [prusa3d/Prusa-Firmware#897]
MK3 Firmware 3.3.0 - Failing Calibration and Calibration Z it give and error clean nozzle but nozzle is clean downgrade FW to 3.2.1 and calibration works

**Comment by PavelSindler** [comment]
Check if your PINDa isn't too high (your nozzle probably crashes to heatbed slightly). 3.3.0 contains crash detection during Calibration Z. On 3.2.1 fw, this issue is just not detected by the printer. Let me know if nozzle touches the heatbed and if lowering PINDa helped.

**Comment by Crunch69** [comment]
No it does not crash the printer was built by Prusa and worked great until upgrade  fails calibration on the last point #9.   If I run it a second or third time it works
