### ISSUE TITLE
MK2 with MMU with Einsy-Retro 

### ISSUE THREAD

**Issue by Lino77** [prusa3d/Prusa-Firmware#900]
Is it possible tmc 2130 to implement in the MK2 firmware, would like to swap the mini Rambo through the Einsy-retro, so are almost identical thus I can bring my MK2-MMU 1.0 still a little quieter

**Comment by 3d-gussner** [comment]
Guess you have to build your own firmware based on the MK3 branch for TMC support, with defining a new board for the einsy retro and en-/disable features and functions. But the MK3 branch has no MMUv1 support. So you need parts from MK2 and MK3 branches + new board definition.
Prusa doesn't have any Einsy Retro boards so it will be difficult for them to develop and support it.
I would return the retro and get a einsy or even leave the miniRAMbo as it is way too much work on your own.
