### ISSUE TITLE
FW3.3.0-830 on Mk3 does not recover from power failure

### ISSUE THREAD

**Issue by bobstro** [prusa3d/Prusa-Firmware#902]
I've had trouble with resuming prints after power outages since FW3.2.0. Prior to that, it worked quite reliably. I updated to FW3.3.0 today and tried again. I let a print start, then removed the power plug. On reinsertion of the power plug, I immediately got a "resuming print" message instead of the "resume print?" prompt in earlier versions. The printer waited for the bed & nozzle to heat up, then moved the extruder into position. It then now stalled displaying a "Bed done" message. The extruder & bed remained at the correct temperatures.

**Comment by PavelSindler** [comment]
"resume print?" is shown in case that it was long power failure. If power failure was short, printer auomaticly resumes print. Was it SD card print? What was your filename? Was this file stored in subfolder?

**Comment by bobstro** [comment]
It was a brief outage (plug pull). I can reproduce longer if desired. Definitely an SD card print, as I don't use Octoprint. Longer filename with spaces in root of SD card . Any particular pattern you'd like to test for filename? Edit: Just repeated with a short filename (40mm.gcode) located in root of SD card filesystem. Removed power via power strip switch and let it sit for > 20 min. On power on, was prompted to resume print Y/N. Temperatures heated to previous settings, extruder moved over print and hovered in place while heated with "Bed done" message with no scrolling dots.

**Comment by Zaf9670** [comment]
Wasn't plug pulling the improper method for testing? You should be using an external switch like a power strip or light switch for testing.

Plug pulling and powering off the PSU are not what the power panic can easily detect IIRC.

Edit: Didn't read final message and fixed capitalization.

**Comment by bobstro** [comment]
Power off via PSU switch defeats recovery (at least according to what I've read and tested). I've also been using a power strip with switch. Have tried both ways, but will repeat. This is pretty obvious though.

**Comment by bobstro** [comment]
Are you awaiting more of a response? I think I've included everything.
