### ISSUE TITLE
EEPROM usage map ?

### ISSUE THREAD

**Issue by alsand61** [prusa3d/Prusa-Firmware#91]
I'd like to experiment some mods I have in mind, which require saving a few long int values to EEPROM (16 to 32 bytes).
Where can I find a map of the EEPROM usage?

**Comment by thess** [comment]
See `Configuration.h` -- Starting at line 15. Allocated top-down.

**Comment by alsand61** [comment]
Thanks, I also found  in `ConfigurationStore.cpp` about the lower 170 bytes or so allocated to Marlin settings.
