### ISSUE TITLE
flashing 3.3.0 to MK3 verification error

### ISSUE THREAD

**Issue by tomaslieven** [prusa3d/Prusa-Firmware#910]
i flashed 3.3.0 via slic3r 1.40.1+ to my MK3 but that resulted in first mismatch at byte 0x3c001
         0x00 != 0x06

`

avrdude: Version 6.3-20160220-prusa3d, compiled on Jul  5 2018 at 06:36:32
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "/Applications/Slic3r.app/Contents/MacOS/../Resources/avrdude/avrdude.conf"

         Using Port                    : /dev/cu.usbmodem1411
         Using Programmer              : wiring
         Overriding Baud Rate          : 115200
         AVR Part                      : ATmega2560
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PA0
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    10     8    0 no       4096    8      0  9000  9000 0x00 0x00
           flash         65    10   256    0 yes    262144  256   1024  4500  4500 0x00 0x00
           lfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           lock           0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : Wiring
         Description     : Wiring
         Programmer Model: AVRISP
         Hardware Version: 15
         Firmware Version Master : 2.10
         Vtarget         : 0.0 V
         SCK period      : 0.1 us
avrdude: AVR device initialized and ready to accept instructions
Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e9801 (probably m2560)
avrdude: reading input file "/Users/..../Downloads/prusa3d_fw_MK3_3_3_0.hex"
avrdude: writing flash (253106 bytes):
avrdude: stk500v2_command(): command failed

Writing | ################################################## | 100% 44.30s

avrdude: 253106 bytes of flash written
avrdude: verifying flash memory against /Users/.../Downloads/prusa3d_fw_MK3_3_3_0.hex:
avrdude: load data flash data from input file /Users/.../Downloads/prusa3d_fw_MK3_3_3_0.hex:
avrdude: input file /Users/.../Downloads/prusa3d_fw_MK3_3_3_0.hex contains 253106 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 32.41s

avrdude: verifying ...
avrdude: verification error, first mismatch at byte 0x3c001
         0x00 != 0x06
avrdude: verification error; content mismatch

avrdude done.  Thank you.
`

i also tried to downgrade to 3.2.1 with slic3r and FirmwareUpdaterV21b which i had on mac with same error. 

printer now loads with flickering screen and i cant use that

**Comment by tomaslieven** [comment]
only way to get printer back working was to reflash and i tried all the way back to 3.1.3 with FirmwareUpdaterV21b which made printer work again, flashing again with new slic3r from 3.1.3 to 3.3.0 got me same verification error

**Comment by tomaslieven** [comment]
also flashing from 3.1.3 to 3.2.0 with FirmwareUpdaterV21b is causing error:
![screenshot 2018-07-11 10 31 54](https://user-images.githubusercontent.com/10801085/42559878-a4e6dd32-84f5-11e8-8811-2d7b3d288bad.jpg)

**Comment by GurliGebis** [comment]
Sounds like the flash chip is going bad. You might want to contact support via the chat on the website. The flash shouldn't wear out that fast, especially for a microcontroller

**Comment by XPila** [comment]
@tomaslieven it seems to be flash chip or bootloader problem, have you original prusa bootloader?

**Comment by Karlosek** [comment]
I have the same problem.
The last fw I can flash via FirmwareUpdaterV21b is 3.1.1 stock fw from download website. I tried different USB cables, no luck.

This is the output when I was trying to flash the latest fw via slic3r:

Programmer Type : Wiring
         Description     : Wiring
         Programmer Model: AVRISP
         Hardware Version: 15
         Firmware Version Master : 2.10
         Vtarget         : 0.0 V
         SCK period      : 0.1 us

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e9801 (probably m2560)
avrdude: reading input file "/Users/kk/Desktop/prusa3d_fw_MK3_3_3_0.hex"
avrdude: writing flash (253106 bytes):
avrdude: stk500v2_command(): command failed

Writing | ################################################## | 100% 44.33s

avrdude: 253106 bytes of flash written
avrdude: verifying flash memory against /Users/kk/Desktop/prusa3d_fw_MK3_3_3_0.hex:
avrdude: load data flash data from input file /Users/kk/Desktop/prusa3d_fw_MK3_3_3_0.hex:
avrdude: input file /Users/kk/Desktop/prusa3d_fw_MK3_3_3_0.hex contains 253106 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 32.31s

avrdude: verifying ...
avrdude: verification error, first mismatch at byte 0x3c000
         0x10 != 0x14
avrdude: verification error; content mismatch

avrdude done.  Thank you.

<img width="435" alt="screen shot 2018-07-16 at 18 49 12" src="https://user-images.githubusercontent.com/17452440/42772199-06a3360a-892a-11e8-9b4d-17d16e63f7ad.png">

**Comment by Karlosek** [comment]
My Einsy came directly from Ultimachine.

**Comment by Karlosek** [comment]
I am normaly on MAC, but just tried to flash the fw using PC. No luck either. The same error.

**Comment by 3d-gussner** [comment]
@Karlosek stock Ultimachine Einsy has standard Arduino bootloader and Prusa firmware may not fit. That's why Prusa has its one boot loader saving few bytes.

**Comment by Karlosek** [comment]
Yeah, might be the problem. How easy to reflash the bootloader?

**Comment by 3d-gussner** [comment]
@Karlosek search the github issues there are some helpful comments. @XPila Is it possible you provide a how-to flash prusa boot loader on Einsy ?

**Comment by XPila** [comment]
bootloader update is possible with USBasp adapter or similar https://www.fischl.de/usbasp/

**Comment by XPila** [comment]
next release should be <0x3c000 and compatible with this bootloader, but we cannot assure this in future...

**Comment by Karlosek** [comment]
All I have right now is USBTiny or Arduino Uno somewhere.  I asume I can flash the bootloader with USBTiny, right?

**Comment by tomaslieven** [comment]
@XPila yeah i have stock orginal prusa MK3 printer no changes or hardware upgrades

**Comment by Karlosek** [comment]
I am trying to flash the bootloader with Arduino Uno. It says:

Arduino: 1.8.5 (Mac OS X), Board: "RAMBo"

Error while burning bootloader: missing 'bootloader.tool' configuration parameter

I understand that RAMBo parameters (processor, fuses etc) has to be mentioned in boards.txt but I cannot find the correct config. Any idea?

**Comment by XPila** [comment]
@tomaslieven if you have stock MK3, please contact Prusa3D support, you will receive new Rambo board.

**Comment by XPila** [comment]
@Karlosek it is better way to flash bootloader without Arduino, using avrdude only. I thing bootloader is not properly set in board definition file.

**Comment by Karlosek** [comment]
Thank you XPila. I tried flashing the bootloader with Arduino UNO and AVRdude from command line. I found some info on Ultimachine GitHub.:

2560 upload command:
$ avrdude -v -v -p m2560 -c avrispmkII -P usb: -e -Ulock:w:0x0F:m -Uefuse:w:0xFD:m -Uhfuse:w:0xD0:m -Ulfuse:w:0xFF:m -U ./stk500boot_v2_mega2560.hex 

-You might need to be super user.
-The last -U flag is the location of the hex file you want to upload.

https://github.com/ultimachine/RAMBo-Uploader/blob/master/notes.txt

But still no luck. I might as well go to Prusa "factory" and ask for help there. I hope they can flash the board for me. (I live in Prague). Might be faster than order dedicated ISP programmer.

**Comment by Barnabasek** [comment]
@tomaslieven What version of the Einsy board do you have? Is there a Prusa "patch board" inserted in the LCD connectors?

**Comment by KoKuToru** [comment]
@Karlosek when using arduino as ISP Programmer you need to use the following command:
```sh
avrdude -v -v -c avrisp -b 19200 -P /dev/ttyACM2 -pm2560 -Uefuse:w:0xFD:m -Uhfuse:w:0xD0:m -Ulfuse:w:0xFF:m -Ulock:w:0x0F:m -Uflash:w:stk500boot_v2_mega2560.hex:i
```
you need to change `/dev/ttyACM2` to your arduino..

Whats much more important is.. the J19 Header "REST" for ICSP ist inverted.
Use the the P2 Pin3.. (or change the arduino ISP to invert RESET ? [not tested])  (https://github.com/ultimachine/Einsy-Rambo/issues/2)

It's in the PDF page 5
![image](https://user-images.githubusercontent.com/1866790/43044594-41b239ca-8da9-11e8-8bde-2d4c724828aa.png)
![image](https://user-images.githubusercontent.com/1866790/43044596-48864822-8da9-11e8-91ca-5b4741199936.png)
![image](https://user-images.githubusercontent.com/1866790/43044600-5997a8c2-8da9-11e8-98c6-1ce2a050d8eb.png)


I flashed my Einsy 1.1a successfully this way.
With the new bootloader, flashing the new firmeware worked without any problems.

**Comment by Karlosek** [comment]
![einsy slave off uno master](https://user-images.githubusercontent.com/17452440/43046269-a07e2de8-8dc6-11e8-977a-fea3debeaa2c.png)

Thank you for your comment!  I connected it this way - exactly how you describe it. thanks for the command. I will try it tonight.

I assume I can power the Einsy from the UNO and there is no need for external DC power.

I visited Prusa and I am pretty sure the service technician connected his USBasp dongle in the middle of J19 (pin 5,6,7,8,9,10) where the round sticker was. I just hope he did not burn anything. He had external PSU attached to the board. No need to mention he could not help me.

**Comment by KoKuToru** [comment]
The image looks correct

> I assume I can power the Einsy from the UNO and there is no need for external DC power.

Yes i used no external power, the moment you connect power (from arduino to einsy) leds will light up.

**Comment by neiion** [comment]
Hi
I am in need of help, Here is what i have done so far. maybe i am doing it completely wrong?
I have connected the einsy board (from ultimaker) to the arduino( using connection diagram from above ). i then loaded audrino isp sketch to arduino. I then open cmd in c:\winavr bin folder, copied prusa bootloader hex file into bin folder. I then run " avrdude -v -v -c avrisp -b 19200 -P com23 -pm2560 -Uefuse:w:0xFD:m -Uhfuse:w:0xD0:m -Ulfuse:w:0xFF:m -Ulock:w:0x0F:m -Uflash:w:stk500boot_v2_mega2560.hex:i "  It keeps giving me a "Yikes! invalid device signature error" .

Am i going about this the right way?  any help would be great

Thanks

**Comment by KoKuToru** [comment]
The diagram is only for **Arduino UNO (or Duemilanove)** for other versions see: 
https://www.arduino.cc/en/Tutorial/ArduinoISP#toc3

When you get the `Yikes! invalid device signature error`
It should tell you what device ID it got.. which might help

**Comment by neiion** [comment]
Thanks for the info KoKuToru 

I am using the arduino uno as the programmer running arduino as isp sketch.  I am lost as to where i run the commands to upload bootloader to einsy connected to arduino. is it from winavr or from inside the arduino ide. thanks for the help

**Comment by Karlosek** [comment]
I just tried the command and got error.

Karels-MBP:~ kk$ avrdude -v -v -c avrisp -b 19200 -P /dev/tty.usbmodem1411 -pm2560 -Uefuse:w:0xFD:m -Uhfuse:w:0xD0:m -Ulfuse:w:0xFF:m -Ulock:w:0x0F:m -Uflash:w:/Users/kk/stk500boot_v2_mega2560.hex:i

avrdude: Version 6.3, compiled on Sep 18 2017 at 20:31:51
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "/usr/local/Cellar/avrdude/6.3/etc/avrdude.conf"
         User configuration file is "/Users/kk/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/tty.usbmodem1411
         Using Programmer              : avrisp
         Overriding Baud Rate          : 19200
         AVR Part                      : ATmega2560
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PA0
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    10     8    0 no       4096    8      0  9000  9000 0x00 0x00
           flash         65    10   256    0 yes    262144  256   1024  4500  4500 0x00 0x00
           lfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           lock           0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : STK500
         Description     : Atmel AVR ISP

avrdude: stk500_getparm(): (a) protocol error, expect=0x14, resp=0x14

avrdude: stk500_getparm(): (a) protocol error, expect=0x14, resp=0x02

avrdude: stk500_getparm(): (a) protocol error, expect=0x14, resp=0x10
         Hardware Version: 32766
         Firmware Version: 32766.-406646912
         Topcard         : STK502
         Vtarget         : 1.8 V
         Varef           : 0.0 V
         Oscillator      : Off
         SCK period      : 0.1 us

avrdude: stk500_initialize(): (b) protocol error, expect=0x10, resp=0x01
avrdude: initialization failed, rc=-1
         Double check connections and try again, or use -F to override
         this check.

avrdude: stk500_disable(): protocol error, expect=0x14, resp=0x10

avrdude done.  Thank you.

Karels-MBP:~ kk$

**Comment by Karlosek** [comment]
I then used the command line with the -F param, to override the check:
avrdude -v -v -c avrisp -b 19200 -P /dev/tty.usbmodem1411 -pm2560 -F -Uefuse:w:0xFD:m -Uhfuse:w:0xD0:m -Ulfuse:w:0xFF:m -Ulock:w:0x0F:m -Uflash:w:/Users/kk/stk500boot_v2_mega2560.hex:i

Got this msg:

avrdude: stk500_initialize(): (b) protocol error, expect=0x10, resp=0x01
avrdude: initialization failed, rc=-1
avrdude: AVR device initialized and ready to accept instructions
avrdude: Device signature = 0x000000 (retrying)
avrdude: Device signature = 0x000000 (retrying)
avrdude: Device signature = 0x000000
avrdude: Yikes!  Invalid device signature.
avrdude: Expected signature for ATmega2560 is 1E 98 01
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: stk500_disable(): protocol error, expect=0x14, resp=0x10

avrdude done.  Thank you.

**Comment by KoKuToru** [comment]
Please don't `-F` There is a reason for these checks.. 

1. Get an arduino UNO
2. Open Arduino IDE
3. Load Arduino ISP sketch
4. Upload Sketch (Board = Arduino UNO, Programmer = AVRISP mkII)
5. connect ISCP to Einsy   
I used the lcd/sd cabel like this: 
![image](https://user-images.githubusercontent.com/1866790/43058286-14dd8c6c-8e47-11e8-9b0a-793e54bdad15.png)
![image](https://user-images.githubusercontent.com/1866790/43057961-6322d1e0-8e45-11e8-9955-3c08b6c3da5f.png)
![image](https://user-images.githubusercontent.com/1866790/43057969-7200cf5a-8e45-11e8-8a4c-012c5855abb8.png)
![image](https://user-images.githubusercontent.com/1866790/43058307-2ee6ef40-8e47-11e8-9bc1-c06e8da00fbb.png)

As you can see, the moment you connect to Einsy the LED above the USB-Port should light up

6. open a terminal and execute avrdude
```
[luca@LucaArchLinux stk500v2-prusa-master]$ ls
avr_cpunames.h       command.h  lcd.h        Makefile    stk500boot.c  stk500boot.hex
[luca@LucaArchLinux stk500v2-prusa-master]$ ../arduino-1.6.8-linux64/arduino-1.6.8/hardware/tools/avr/bin/avrdude -C /home/luca/3dPrinter/arduino-1.6.8-linux64/arduino-1.6.8/hardware/tools/avr/etc/avrdude.conf -v -v -c avrisp -b 19200 -P /dev/ttyACM1 -pm2560 -Uefuse:w:0xFD:m -Uhfuse:w:0xD0:m -Ulfuse:w:0xFF:m -Ulock:w:0x0F:m -Uflash:w:stk500boot_v2_mega2560.hex:i

avrdude: Version 6.0.1, compiled on Apr 14 2015 at 19:04:16
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2009 Joerg Wunsch

         System wide configuration file is "/home/luca/3dPrinter/arduino-1.6.8-linux64/arduino-1.6.8/hardware/tools/avr/etc/avrdude.conf"
         User configuration file is "/home/luca/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/ttyACM1
         Using Programmer              : avrisp
         Overriding Baud Rate          : 19200
         AVR Part                      : ATmega2560
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PA0
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    10     8    0 no       4096    8      0  9000  9000 0x00 0x00
           flash         65    10   256    0 yes    262144  256   1024  4500  4500 0x00 0x00
           lfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           lock           0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : STK500
         Description     : Atmel AVR ISP
         Hardware Version: 2
         Firmware Version: 1.18
         Topcard         : Unknown
         Vtarget         : 0.0 V
         Varef           : 0.0 V
         Oscillator      : Off
         SCK period      : 0.1 us

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.02s

avrdude: Device signature = 0x1e9801
avrdude: safemode: lfuse reads as FF
avrdude: safemode: hfuse reads as D0
avrdude: safemode: efuse reads as FD
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: reading input file "0xFD"
avrdude: writing efuse (1 bytes):

Writing | ################################################## | 100% 0.01s

avrdude: 1 bytes of efuse written
avrdude: verifying efuse memory against 0xFD:
avrdude: load data efuse data from input file 0xFD:
avrdude: input file 0xFD contains 1 bytes
avrdude: reading on-chip efuse data:

Reading | ################################################## | 100% 0.01s

avrdude: verifying ...
avrdude: 1 bytes of efuse verified
avrdude: reading input file "0xD0"
avrdude: writing hfuse (1 bytes):

Writing | ################################################## | 100% 0.01s

avrdude: 1 bytes of hfuse written
avrdude: verifying hfuse memory against 0xD0:
avrdude: load data hfuse data from input file 0xD0:
avrdude: input file 0xD0 contains 1 bytes
avrdude: reading on-chip hfuse data:

Reading | ################################################## | 100% 0.01s

avrdude: verifying ...
avrdude: 1 bytes of hfuse verified
avrdude: reading input file "0xFF"
avrdude: writing lfuse (1 bytes):

Writing | ################################################## | 100% 0.01s

avrdude: 1 bytes of lfuse written
avrdude: verifying lfuse memory against 0xFF:
avrdude: load data lfuse data from input file 0xFF:
avrdude: input file 0xFF contains 1 bytes
avrdude: reading on-chip lfuse data:

Reading | ################################################## | 100% 0.01s

avrdude: verifying ...
avrdude: 1 bytes of lfuse verified
avrdude: reading input file "0x0F"
avrdude: writing lock (1 bytes):

Writing | ################################################## | 100% 0.02s

avrdude: 1 bytes of lock written
avrdude: verifying lock memory against 0x0F:
avrdude: load data lock data from input file 0x0F:
avrdude: input file 0x0F contains 1 bytes
avrdude: reading on-chip lock data:

Reading | ################################################## | 100% 0.01s

avrdude: verifying ...
avrdude: 1 bytes of lock verified
avrdude: reading input file "stk500boot_v2_mega2560.hex"
avrdude: writing flash (258444 bytes):

Writing | ################################################## | 100% 0.00s

avrdude: 258444 bytes of flash written
avrdude: verifying flash memory against stk500boot_v2_mega2560.hex:
avrdude: load data flash data from input file stk500boot_v2_mega2560.hex:
avrdude: input file stk500boot_v2_mega2560.hex contains 258444 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.00s

avrdude: verifying ...
avrdude: 258444 bytes of flash verified

avrdude: safemode: lfuse reads as FF
avrdude: safemode: hfuse reads as D0
avrdude: safemode: efuse reads as FD
avrdude: safemode: Fuses OK (H:FD, E:D0, L:FF)

avrdude done.  Thank you.

[luca@LucaArchLinux stk500v2-prusa-master]$ 
```

If this doesn't work, I suspect.. .something is broken

7. Disconnect everything and flash Einsy like normal via USB

**Comment by Karlosek** [comment]
Thank you very much for detailed walkthrough!  I am currently on vacation for three weeks.  I will try it again when I come back home.

I really appreciate all your help!

**Comment by neiion** [comment]
thanks for detailed info  . going to give it a try later on. cheers

**Comment by neiion** [comment]
@KoKuToru  i successfully flashed bootloader last nignt . problem was due to  using winavr (verification error ) in windows . when i used avrdude in my linux (debian) laptop it worked first time. thanks for all the help.

**Comment by baloan** [comment]
Another description with some more background information is at https://learn.sparkfun.com/tutorials/installing-an-arduino-bootloader. It was not clear to me that the Arduino needs to have the _ArduinoISP_ sketch uploaded which is included in the Ardunio IDE as an example.

**Comment by baloan** [comment]
Root cause seems to be the size of the bootloader. The RAMBo has an address space from 0x00000 to 0x3ffff (equiv to 262144 bytes). The hex coding for the `stk500boot_v2_mega2560.hex` shows the bootloader is loaded from 0x3e000 (or 3000:E000 in intel segment notation) to 0x3fd1e. The ATmega2560 is set to execute 0x3e000 on poweron. The original bootloader (and that I don't know for sure) seems to occupy memory starting 0x3c000, and that's why there are verification errors after write. Not sure but maybe the bootloader does't allow to overwrite its reserved memory? It would explain why my firmware files which are greater than 0x3c000 fail. hex format details at https://en.wikipedia.org/wiki/Intel_HEX

**Comment by 3d-gussner** [comment]
@baloan Hi, did you follow the latest build instructions? https://github.com/prusa3d/Prusa-Firmware/blob/MK3/README.md

I personally install Arduino IDE 1.6.9 and 1.8.5 in portal mode dedicated to Prusa firmware. For other projects i have a standard IDE 1.8.5 installation (ESP8266, ESP32, Marlin ...)
BUT never update the AVR boards in 1.6.9 as these will give you issues. Updating the libraries in 1.6.9 i never experienced any issues compiling/uploading the firmware.

Is it a miniRAMbo you got from Prusa or is it from somewhere else?
- If you got it from Prusa, contact them via Chat. They should help you, maybe the Prusa Bootloader isn't flashed correctly on that.
- If you got it from somewhere else you should consider to flash the Prusa Bootloader

**Comment by mochery** [comment]
@KoKuToru Worked great with my arduino package installed locally w/ it's avrdude.  Thanks so much for the tutorial.  Purchased einsy direct from Ultimachine and had to work off an old F/W build.  Can bring in changes from prusa now.

**Comment by Karlosek** [comment]
Just for a record: Arduino UNO as ISP programmer needs 10µF electrolytic capacitor connected to RESET and GND.

![arduino uno as isp](https://user-images.githubusercontent.com/17452440/52201017-82589a80-286a-11e9-8e06-730a6213ab3e.jpg)

**Comment by martins6413** [comment]
Hallo,ist dieser tread noch aktuell ?
