### ISSUE TITLE
Add M860 to Wiki - Supported G codes

### ISSUE THREAD

**Issue by kazoob** [prusa3d/Prusa-Firmware#920]
The "M860 Sx" g-code (wait for PINDA probe temperature) is not listed in the Wiki @ https://github.com/prusa3d/Prusa-Firmware/wiki/Supported-G-codes

**Comment by CrashCash** [comment]
And while you're at it, neither is M73 - the new "time remaining" code.

**Comment by Prusa-Support** [comment]
Hello! Sorry for the very late response to this. We added these, but currently we refer to another page from our Knowledge Base for GCode list: https://help.prusa3d.com/article/prusa-specific-g-codes_112173 

Alessandro Pantaleo
Prusa Research

**Comment by leptun** [comment]
To add to this answer, I think a very up to date gcode documentation can also be found here: https://reprap.org/wiki/G-code
We try to keep this wiki updated as well. You can also use doxygen on the source code (all gcodes are documented there)
