### ISSUE TITLE
Please add:  M118 - Serial print 

### ISSUE THREAD

**Issue by ieatacid** [prusa3d/Prusa-Firmware#921]
The OctoPrint [ActionCommands plugin](https://github.com/benlye/OctoPrint-ActionCommandsPlugin) relies on serial output from M118 to execute the commands that are specified to it. 

Please add it back.

Is there a specific reason it was removed?

Edit: This is regarding MK3 firmware. I'm unsure of M118 availability on other variants.

**Comment by petrzelka** [comment]
When printing from SD and using OctoPrint to monitor the print, one could use M118 in Slic3r in BEFORE_LAYER_CHANGE custom gcode to let OctoPrint know about Z change. 
This way (with a trivial OctoPrint plugin that I can create) it could do timelapse on z change, which currently isn't possible when priting from SD card.
