### ISSUE TITLE
feature request: total number of prints appears in lcd_menu_statistics

### ISSUE THREAD

**Issue by johncronan** [prusa3d/Prusa-Firmware#928]
Can there be an EEPROM variable that stores the number of prints, as for filament and runtime? This would be very helpful to use along with the 'fail stats' info. (And a related one: I would be interested to know how many prints were canceled by the user.)

Thanks

**Comment by JohnOCFII** [comment]
> Can there be an EEPROM variable that stores the number of prints, as for filament and runtime? This would be very helpful to use along with the 'fail stats' info. (And a related one: I would be interested to know how many prints were canceled by the user.)

These items get to be "expensive" in terms of using up scarce resources in firmware.  If you were to use OctoPrint, you can track all of these items and more.  https://octoprint.org

**Comment by johncronan** [comment]
Ok, forget the second one. Just one int, please!

(Users here definitely appreciate the simplicity of having only one machine interface, with an SD card.)
