### ISSUE TITLE
M20 sends hidden/trashed files from FlashAir Card

### ISSUE THREAD

**Issue by Jonnie-Cache** [prusa3d/Prusa-Firmware#938]
When sending an M20 command, the Prusa sends files even if they are hidden/trashed by the FlashAir device.

`Send: M20`
`Recv: Begin file list`
`Recv: ABS_2X~1.GCO 32768`
`Recv: KFACTO~1.GCO 2900`
`Recv: ABS_AD~1.GCO 32768`
`Recv: ABS_BA~1.GCO 316982`
`Recv: MK3_PL~1.GCO 3552905`
`Recv: ABS_GE~1.GCO 7798931`
`Recv: ABS_PR~1.GCO 294564`
`Recv: MK3_PL~2.GCO 2206259`
`Recv: ABS_WH~1.GCO 769280`
`Recv: MK3_PL~3.GCO 23846383`
`Recv: MK3_PL~4.GCO 224162`
`Recv: MK3_PL~5.GCO 5966830`
`Recv: MK3~F8D7.GCO 25074366`
`Recv: MK3~39A3.GCO 9991779`
`Recv: MK3_~F52.GCO 21788066`
`Recv: MK3~A603.GCO 319820`
`Recv: MK3~5B93.GCO 1163600`
`Recv: MK3~801F.GCO 10256022`
`Recv: MK3~C1EC.GCO 3794419`
`Recv: MK3~35B3.GCO 17819561`
`Recv: MK3~E536.GCO 7586128`
`Recv: MK3~714A.GCO 839525`
`Recv: KFACTO~2.GCO 2900`
`Recv: /TRASHE~1/501/MK3_PL~1.GCO 25074366`
`Recv: /TRASHE~1/501/MK3_PL~2.GCO 0`
`Recv: /TRASHE~1/501/MK3_PL~3.GCO 0`
`Recv: /TRASHE~1/501/MK3_PL~4.GCO 0`
`Recv: /TRASHE~1/501/MK3_PL~5.GCO 0`
`Recv: /TRASHE~1/501/MK3_P~51.GCO 0`
`Recv: /TRASHE~1/501/MK3_P~59.GCO 0`
`Recv: /TRASHE~1/501/MK3_P~69.GCO 0`
`Recv: /TRASHE~1/501/MK3_P~79.GCO 0`
`Recv: /TRASHE~1/501/MK3_P~89.GCO 0`
`Recv: /TRASHE~1/501/MK3_P~97.GCO 0`
`Recv: End file list`
`Recv: ok`

**Comment by TheZeroBeast** [comment]
Hi @Jonnie-Cache,

This appears like the hidden files Mac OS X store when deleting files, if you had deleted some files on Mac if you insert it again and empty your trash can it should remove that folder and its contents.
