### ISSUE TITLE
MK3 Firmware 3.3.1  Resume print bug

### ISSUE THREAD

**Issue by knightofcarnage** [prusa3d/Prusa-Firmware#949]
After resuming a print  the hot-end never heats back up.  This was occurred 3 times, since flashing the firmware. It did not happen every time.  Also the print was paused by user.

https://youtu.be/XA5i0a_gtwU

**Comment by magkopian** [comment]
Just wanted to say that I have experienced the same issue on 3.2.0, but it only happened once and I have stopped my printer multiple times in the past while using the same firmware version. So, I don't believe the bug was cause by a change in the latest firmware version.
