### ISSUE TITLE
Belt tension status check - addition to menu please

### ISSUE THREAD

**Issue by jonnyhifi** [prusa3d/Prusa-Firmware#968]
Given  there is code written to test it ...  could it be added to as a menu item, (eg in calibration menu) as currently I believe the only way it can be measured is to run the complete “new machine” wizard which takes ages, if you’re just working on getting the belt tension sorted. This is a common thing new people with their mk3s (and presumably  other models) do once the machine is working as part of their initial “dialing stuff in” activities. To have to wait for what feels like 15/20 minutes for the machine to run the whole wizard is very frustrating whilst iterating just on belt tension - it would be great to be able to test and display the belt tension(s) alone.

**Comment by KD7LRJ** [comment]
Running the "Selftest" function also tests the belt tension and on my MK3 it took 2.5 minutes running from room temperature.

**Comment by Panayiotis-git** [comment]
I agree with @jonnyhifi.

The selftest as it is currently implemented, checks in the beginning the hotend and then the belts. If you want to calibrate the belt, then after each belt regulation you have to wait for the hotend to cool and then be able to execute the selftest again.

If you compile the firmware yourself, there is an experimental option that enables the belt check and other.

**Comment by jonnyhifi** [comment]
Indeed the other self tests that are performed - are they worth putting on sub menus to aid people fault finding, eg testing axes ..? (Not that I’ve aS yet had a need for the others in an isolated way, and I suspect there’s less user need for)

**Comment by Jacks3DPrinting** [comment]
It would be easier if we had a extra belt tension measuring option, instead of running the whole self test.

To wait between every selftest for the bed and nozzle to cool down is pretty annoying.

**Comment by boelle** [comment]
does anyone even know in what file etc the selftest is "hidden" ?

**Comment by devhdma** [comment]
For me those values are bs... I have achieved 259 for Y but so much stress on the parts so I reduced it. Definitely not able to reach 240 without breaking printed parts.

**Comment by twindan** [comment]
Yes, the self test takes forever to run since it has to heat up your build plate and extruder. It would be better if we could just test the belt status rather than having to go through the rest.

**Comment by vintagepc** [comment]
This is fixed by #2473
