### ISSUE TITLE
[Feature Request] Add option for disabling the fan check just for the layer fan

### ISSUE THREAD

**Issue by magkopian** [prusa3d/Prusa-Firmware#979]
Currently, if I try to use a layer fan that only has 2 wires on my MK3 that results to a fan error. As a workaround, I can turn off the fans check from the menu, which while it fixes the problem it also disables the check for the heatsink fan.

If the layer fan fails during a print the worst thing that can happen is that the quality of the particular print after that point will suffer, especially if it’s a PLA print with some steep overhangs. If the heatsink fan fails however, this will most likely result to a filament jam and might even cause the extruder parts that are in direct contact with the heatsink to warp if the temperature of the heatsink gets too high, as they are made of PETG.

So, for the reasons mentioned above I'd like to request if possible, the addition of a menu option for allowing the user to disable just  the fan check for the layer fan instead of both it and the heatsink fan.

**Comment by Prusa-Support** [comment]
Hello! I am sorry for the very late response to this. I'll label this as a feature request, can be an aspect to evaluate - from a first check I have done, the fans check is still the "same" for both, so fair point on the potential issues with not checking the heatsink fan. 

Alessandro Pantaleo
Prusa Research
